### ISSUE TITLE
Error compiling in Ubuntu 16.04

### ISSUE THREAD

**Issue by Locario** [elysium-project/server#10]
Hi there, i have this errors:

[ 15%] Building CXX object src/game/CMakeFiles/game.dir/AdvancedPlayerBotAI.cpp.o
In file included from /home/oscar/elysiumOS/server/src/game/AI/CreatureAI.h:28:0,
                 from /home/oscar/elysiumOS/server/src/game/AI/PlayerAI.h:28,
                 from /home/oscar/elysiumOS/server/src/game/PlayerBots/PlayerBotAI.h:4,
                 from /home/oscar/elysiumOS/server/src/game/AdvancedPlayerBotAI.h:13,
                 from /home/oscar/elysiumOS/server/src/game/AdvancedPlayerBotAI.cpp:11:
/home/oscar/elysiumOS/server/src/game/ObjectGuid.h:333:11: error: redefinition of ‘class std::hash<ObjectGuid>’
     class hash<ObjectGuid>
           ^
/home/oscar/elysiumOS/server/src/game/ObjectGuid.h:239:12: error: previous definition of ‘class std::hash<ObjectGuid>’
     struct hash<ObjectGuid>
            ^
src/game/CMakeFiles/game.dir/build.make:62: recipe for target 'src/game/CMakeFiles/game.dir/AdvancedPlayerBotAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AdvancedPlayerBotAI.cpp.o] Error 1
CMakeFiles/Makefile2:560: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@ubuntu:/home/oscar/elysiumOS/server/src# gcc
gcc: fatal error: no input files
compilation terminated.

root@ubuntu:/home/oscar/elysiumOS/server/src# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Anubisss** [comment]
Try this: https://github.com/elysium-project/server/pull/11
