### ISSUE TITLE
Wrath of Cenarius isnt proccing on all swings 

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/server#1000]
http://db.vanillagaming.org/?item=21190
Technically Wrath of Cenarius should be working on all seal swings

Reckoning bomb is an attack where all 5 swings are swung at thesame time. Despite hits and seals being in an order on the combat log, the swings are all technically swung at thesame time. 

Wrath of Cenarius is not proccing on all seals. 
Fix: Wrath of Cenarius should proc on all swings

**Comment by theloras** [comment]
https://github.com/elysium-project/server/issues/420
