### ISSUE TITLE
Only Blazefury Medallion should scale with spell damage

### ISSUE THREAD

**Issue by ImperfectCell** [elysium-project/server#1013]
Storm gauntlets was proven not to scale with spell damage but that doesn't mean Blazefury Medallion shouldn't scale. Both don't work with thesame way. Storm Gauntlets devours stormstrike, Blazefury medallion doesn't. Storm gauntlets are NOT thesame and blazefury medallion required fixing other mechanics for breaking sap/gouge in patches. Storm gauntlets were never breaking sap/gouge or mentioned in the patch they were fixed for sap/gouge. Therefore necklace should be changed and others ignored.

PROOF http://db.vanillagaming.org/?item=17111 scales with spell damage

http://wowdata.getbuffed.com/item/Armor/Blazefury-Medallion-17111
Translated comment: "Yes, just about. Had that thing with my Druid too at level 60 and was really nice.... in BWL against fire vulnerable mobs had that some even made up to 12 damage per hit...."

Yep. Mobs. Not bosses. Therefore it was an http://db.vanillagaming.org/?npc=12461

A german druid player on wowdata named Rifler claims he "hit" 12 damage on BWL fire vulnerable 100% Overseer mobs. (NOT BOSSES) The problem is even if the item critted (x1.5 from wowhead/elysium/thottbot comments) critted and had every single vulnerability increasing buff in the game
it would never reach 12 damage. Just this item should be changed back to spell damage scaling without others being changed. 

It can't hit 12, from 2 with all the vulnerability buffs in the game including it critting. It would of HAD to scale with spell damage.

Druids have some spell damage 
http://db.vanillagaming.org/?item=16424

Retail player was a level 60 druid - Rifler - EU-Connected Kult der Verdammten
http://www.warcraftrealms.com/charsheet/20970026
http://www.warcraftrealms.com/search.php?search=rifler&btn-search.x=0&btn-search.y=0
You can see according to his level on census he was raiding in the vanillla period
(He is the only german player on census)

Power Infusion does not work on Blazefury Medallion
(only vulnerabilities work on the item)

Only these work
15% Nightfall
100% BWL immunity mobs
10% curse of the elements
15% scorch invulnerability

Even with a crit it will not hit 12. It will crit 8.7 (8 on his screen)
It will hit 5.8 (5 on his screen)

This would benefit only shamans and paladins and druids. Not rogues. Rogues would lose damage

Damage doesnt round down, the damage is still 5.8 but it doesn't show 6, it shows 5 on the screen.
-For example on Elysium a seal of 178 damage shows 195 damage with sanctity aura.

BWL immunity is exactly 100% as stated here in February 9, 2006  http://z15.invisionfree.com/The_Dungeon/ar/t35.htm
http://i.imgur.com/wm8px2o.png

Even if the item did scale it would be very weak. Rogues would gain less dps from it in fire damage gear considering only it scales. At 12% only, they would gain far less dps compared to T3/R14.

The judgement set is 200 spell damage. BiS spell damage melee players have 300 spell damage. That's 38 damage on a swing. That is incredibly weak. You lose 34 spell damage as well without http://db.vanillagaming.org/?item=18814 so that's only 23 damage on every swing. You also lose 15% melee crit speccing this necklace.

Bwl mobs are 100%. That's double damage (X2). 

0 spell damage would mean he would have 5 appear as a hit and 8 appear as a crit.

Conclusion: It should show 12 hit damage on the screen,  not 5 hit or 8 crit.
Therefore item should scale
Fix: Necklace should be changed back the way it was before at 12%

**Comment by GuybrushGit** [comment]
BWL immunity is more than 100%. This item should not scale under any circumstance, it would be incredibly OP.

**Comment by ImperfectCell** [comment]
The average spell damage players have is 300. That's 36 damage on a swing. I don't agree its OP.

**Comment by ImperfectCell** [comment]
Therefore there should be at least some spell damage scaling. In order for a druid with a few pieces of spell damage to increase the damage by 5. It would of needed to be 10% of spell damage the minimum.

**Comment by Mostprovidedlinks** [comment]
He is right. 46 hit on swings but you have now instead of 30% crit, you have 5% crit.

**Comment by Mostprovidedlinks** [comment]
I think it wouldn't make much a difference in dps. Only shamans and paladins would benefit from it.
Rogues can't /warriors can't, chances of them having spell damage gear is low.

**Comment by ImperfectCell** [comment]
One item would make no difference.

**Comment by GuybrushGit** [comment]
BWL vulnerability is not 100%: http://db.vanillagaming.org/?spell=22277
Stop trying to make spellpower rogues a thing, this isn't feenix.

**Comment by ImperfectCell** [comment]
So what you're expecting me to believe is I would do a 66,000 crit? huh

**Comment by ImperfectCell** [comment]
This would benefit shamans and paladins. Not rogues.

**Comment by thepparker** [comment]
The elemental vulnerability from BWL gives triple the damage. The spell grants a -75% taken modifier from all schools and 1100% increased taken from a specific school, resulting in a (1 - 0.75) * (1 + 11) = 3 multiplier.

Your base damage from Blazefury is 2 damage. The overall multiplier if curses, fire vuln, nightfall, etc were on the target would be: 1.1 * 1.15 * 1.15 * 3 = 4.36, resulting in 8.7 damage (rounded to 8). If this crits, that gives a damage of 13.4 (13, a little more than what your evidence reported). Since it's unlikely anyone had improved scorch in BWL, we can probably ignore that modifier, resulting in a damage of 1.1 * 1.15 * 3 * 2 = 7.6, or 11.4 if it crits.

If the item were scaling with spellpower we'd see higher values.

**Comment by ImperfectCell** [comment]
Too bad it says 100% in the 2006 post. The vulnerability from chrommagus is the exact same vulnerability from the Overseers and 2006 sources point out. 100% Vulnerability

**Comment by thepparker** [comment]
A single (incorrect) post from some date in the past. The debuff has remain unchanged to this date, as you can see on http://www.wowhead.com/spell=22280/elemental-shield

In the video: Corruption ticks for 930 with shadow vuln, 78 without. 78 / 0.25 -> 312, 312 * 3 = 936 (~930, remembering that we lose a lot of damage due to integer math). If it were only 100% (i.e. double damage), we'd see ticks of ~620.

Shadow bolt crit for 6982 (likely ruin specced) -> 3491 non-crit, or 1163 with no vuln. This is pretty average for a warlock at even entry level BWL gear level with shadow weaving and shadow bolt vulnerability. Coincides with his early hits of ~3k too.

**Comment by ImperfectCell** [comment]
He never said anything about bosses. Therefore it was 100% and on overseers

**Comment by thepparker** [comment]
Nice backtracking and deletion of your post. They use the exact same buffs, which you even mentioned before you removed it.

**Comment by ImperfectCell** [comment]
You proved they didn't

**Comment by thepparker** [comment]
Chrommagus is a mob, and so are Death Talon Overseers. They use the same spell, as there are no other spells with the same effects.

**Comment by ImperfectCell** [comment]
Chrommagus is a boss and Overseers use 100%

**Comment by ImperfectCell** [comment]
No they don't. It was stated the Overseers are at 100%.

Besides I have proof these items scaled in a 2006 description. You can't possibly prevent this.

**Comment by GuybrushGit** [comment]
rofl 🤦

**Comment by ImperfectCell** [comment]
Yeah. http://wowwiki.wikia.com/wiki/Wyrmguard_Pack

rofl

**Comment by ImperfectCell** [comment]
Too bad I have further proof indicating this does scale. Will be uploading soon

**Comment by stesve** [comment]
I guess the people that made addons to track the vulnerabilities would know the correct multiplier. 

http://stormreaverclan63147.yuku.com/topic/2047/BWL-Vulnerability-testing-for-GLOCK#.WTriUWawe70
