### ISSUE TITLE
A Donation of Runecloth (Darkspear Trolls / Elysium)

### ISSUE THREAD

**Issue by Phoosy** [elysium-project/server#1019]
It appears that the quest A Donation of Runecloth (http://db.vanillagaming.org/?quest=7824) for the Darkspear Trolls requires the previous Donation tiers for *Orgrimmar*, not Darkspear - IE, you currently must have the following quests completed before it will allow you access to ID 7824:

7826 (Wool)
7827 (Silk)
7831 (Mageweave)

The intended behavior is that the following quest IDs are required:

7833 (Wool)
7834 (Silk)
7835 (Mageweave)

**Comment by FlorianKaufmann** [comment]
True, I have the same problem, I I can't get any quest from the NPC after completing the 3 previous quest. I'll then donate to orgrimmar in order to unlock the quest.

**Comment by Phoosy** [comment]
Assuming that https://github.com/elysium-project/server/pull/1028 was fully committed, going to close this out.
