### ISSUE TITLE
Creatures flying even with vmaps and mmaps.

### ISSUE THREAD

**Issue by SilvioDoMine** [elysium-project/server#1020]
Some creatures when start to walk, they fly to get into the location.
I have the lasted mmaps and vmaps working.

![image](https://user-images.githubusercontent.com/20645369/26909225-c7518f16-4bd5-11e7-9779-7e65321e7de0.png)

**Comment by DonkeyKongRacer** [comment]
I cannot reproduce this, at the exact same spot, and I've never seen this anywhere else.
Are you sure you are using the latest build and extracted the vmaps and mmaps with the tools provided ?

**Comment by SilvioDoMine** [comment]
@DonkeyKongRacer 

I'm checking here, and this happens to some mobs when using the command ".reload creature_template", also sometimes change npcs level, such as 

![image](https://user-images.githubusercontent.com/20645369/26993907-9feaf8a6-4d3b-11e7-912d-aa01c45d64db.png)

![image](https://user-images.githubusercontent.com/20645369/26993985-fb5e4c24-4d3b-11e7-90dc-be4dbeb464a3.png)

**Comment by brotalnia** [comment]
Holy shit, I wouldn't mess with that boar.

**Comment by thepparker** [comment]
Looks like something is corrupt with your installation
