### ISSUE TITLE
Mangosd in docker ubuntu 17.04 container doesn't stay online

### ISSUE THREAD

**Issue by zaphot** [elysium-project/server#1022]
Hi, thanks for making the code open source!

Currently I am trying to setup an elysium docker-compose environment in order to develop and experiment with the code. However I encounter some problems and maybe you can help me. I setup 4 db containers, a realmd container and a mangos container. But when i start everything the mangosd server just stops after a bunch of db errors with Halting process.... (Here is the full server.log https://pastebin.com/9ip6bUwW )

I think its best to describe everything i did to setup the docker-compose environment:

I have one ubuntu 17.04 build container which pulls the server source from the elysium server git repo and builds the core with cmake etc. Everything here seems to be okay and I don't encounter any errors and the compilation results in the following shared libraries: libframework.a, libgame.a, libscripts.a, libshared.a and the two executables: realmd and mangosd.

Now I setup 4 mariadb 10.1 container: characters, logs, realmd, world where the respective database in each are called correspondingly and all with the user mangos pw mangos.

Then I created two ubuntu 17.04 container realmd and mangosd with all external lib dependencies. In both I created a workdir where I placed all shared libs. In the container mangos I copied the executable mangosd and in the container realmd the executable realmd. In the corresponding container I placed the *.conf files, in which I edited the db infos.

I linked the mangos docker container with all 4 db container and the realm db container to realmdb database. I also created a folder for the log files and created data folder containing the dbc, maps, mmaps and vmaps.

Oky, I then started the db server and filed them with the sqls from the migrations folder in the elysium server repo as follows:

realdm ← logon.sql
world ← world.sql
characters ← character.sql
logs ← logs.sql

then I applied the world database:
world ← world_full_02032017.sql

and afterwards all migrations in the order of their date.
Character migrations on the characters db
and world migrations on the world db

Now I started the whole docker compose setup and got an error which I could refer to a missing realm entry. Therefore I just did an "INSERT INTO `realmlist` (`name`) VALUES ('DOCKER');" on the realmd db.

The error was gone and the realmd server seems to start correct. Here is the output from the realmd.log:
2017-06-07 10:18:07 Core revision: 2e4a9e50fd5ed974d978 / 2017-05-31 10:35:44 +0100 / Linux_x64 (little-endian) [realm-daemon]
2017-06-07 10:18:07 <Ctrl-C> to stop.

2017-06-07 10:18:07 Using configuration file realmd.conf.
2017-06-07 10:18:07 Max allowed open files is 1048576
2017-06-07 10:18:07 Database: db_realmd;3306;mangos;mangos;realmd
2017-06-07 10:18:07 Added realm "DOCKER"

Oky now comes the part where I am lost: the mangosd server

I start the server with the following command ./mangosd -c mangosd.conf and then I get around ~3000 db errors like for example:
2017-06-07 10:18:39 Table `creature` have creature (GUID: 18614 Entry: 15552) with `creature_template`.`RegenHealth`=1 and low current health (320000), `creature_template`.`minhealth`=1000000.

Here is the server log: https://pastebin.com/9ip6bUwW

At the end of the errors I get the following lines in the server.log before it shuts down:
2017-06-07 10:19:22 World initialized
2017-06-07 10:19:22 SERVER STARTUP TIME: 0 minutes 44 seconds
2017-06-07 10:19:22
2017-06-07 10:19:22
2017-06-07 10:19:22 >> Only expired mails (need to be return or delete) or DB table `mail` is empty.
2017-06-07 10:19:22 Max allowed socket connections 1048576
2017-06-07 10:19:24 Halting process...

Maybe you can help me with this error(s). I just dont get it. Is there an direct communication between mangosd and realmd, which i missed because their containers are not directly linked and could only communicate across the realmd database. If i get it to work i can post my dockerfile(s). With them it would be far easier for everyone to get into your codebase.

Thanks in advance

**Comment by zaphot** [comment]
Oky found that it can be referred to a crash in mangosd console which is fixed by b61b0aefd856a83ce650b3b7e41f288063b5c28f

would be cool if this commit could  be merged into release

**Comment by aboretum** [comment]
Hi @zaphot  Can you share your docker setup with me? I am trying to build on my own to experiment with the code base.

**Comment by aboretum** [comment]
I was doing something similar with a different approaching utilizing vagrant box, something derived from https://github.com/NostalriusTBC/Vagrant

But I think using docker is way cooler 👍

**Comment by zaphot** [comment]
here it is: https://github.com/zaphot/docker-elysium
