### ISSUE TITLE
Quest "The Nightmare Manifests" broken, doesn't complete 

### ISSUE THREAD

**Issue by notpentadactyl** [elysium-project/server#1024]
We did this [quest](http://db.vanillagaming.org/?quest=8736) yesterday again (after we successfully did it during the opening event), but it never completed.

GM response after hours of waiting was "just do it again".

This seems to be happening to a LOT of players (whispering other guilds confirmed it).

GM implied that "doing it twice" will make it complete, which seems like an insane workaround (if it even works).

**Comment by thepparker** [comment]
Did the person who Remulos was following die? Did you finish the event with Remulos not near Eranikus?

**Comment by strudelkuchen** [comment]
No one died. Remulos was right next to Eranikus.

**Comment by thepparker** [comment]
Did any of you get credit for it?

**Comment by Ajjtem** [comment]
Nope, we all got stuck with an uncompleted quest

**Comment by Ajjtem** [comment]
I also talked to another player that had done this event with his guild, while being the only questholder and he ended up the same as us.

**Comment by strudelkuchen** [comment]
We did it yesterday again with 3 people (with a GM watching us) and it worked fine.

**Comment by thepparker** [comment]
Very strange. The only obvious reasons I can see for it failing are what I listed above, but it seems to have worked for you the second time
