### ISSUE TITLE
Six Demon Bag not working properly.

### ISSUE THREAD

**Issue by Mithedhel** [elysium-project/server#1025]
I've been using this trinket on Elysium Project for a while and noticed how the mechanics are significantly different than the original one.

http://db.vanillagaming.org/?item=7734#wh-comments

**Damage numbers:** Currently its Fireball proc is hitting for 135 flat, frostbolt between 150-175 if I'm not wrong. Top rated comment in Vanilla states different numbers similar to other comments later on.

"Frostbolt - 200-250 dmg, slows target movement.
Fireball - 200-250 dmg.
Chainlightning - 175-225 dmg, 3 targets."

**Polymorph effect**. Currently the polimorph is **only** affecting the owner of the trinket, when it's supposed to be a chance between the target and the caster. This is also claimed by all the comments.

**Casting times**. Currently frostbolt and polimorph are being casted with a weird delay as opposed to being instant like it should be. Also, the fireball effect is not having the visual pyroblast that should appear. Video evidence (also showing the polimorph on target): https://www.youtube.com/watch?v=6X278igTGuY

**Scaling** . The current scaling seems to be very little compared to what it used to be. Multiple youtube videos show high numbers.

**Pet damage** Felhound spawned does more damage and not jusr 5-6- https://www.youtube.com/watch?v=ArXSpYa0yvU it also does manaburn as claimed by the comments on the thread.

Scalings were removed in 2.2 in official retail, but this trinket used to be much better and heavily used in arenas even in TBC.

**Comment by Mithedhel** [comment]
@GuybrushGit Any thoughts or looks into this? Haven't found any duplicate. Thanks!

**Comment by binary909** [comment]
Any way to bump this post? 
I'm facing similar issues, came to report the polymorph on others and pet damage issues,
would be great if this could be looked into by anyone.

Cheers

**Comment by GuybrushGit** [comment]
**Damage numbers:** Need the correct spell ids.
**Polymorph effect** Confirmed
**Casting times** No delay, probably just lag.
**Scaling** Spells are following the default scaling rules. Need concrete evidence to add exceptions.
**Pet damage** Confirmed.

**Comment by Mostprovidedlinks** [comment]
@guybrushgit in elysium when i last used it it wasnt caused by lag but the cast time of frostbolt or fireball 
I Hope it was fixed

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit in elysium when i last used it it wasnt caused by lag but the cast time of frostbolt or fireball
I can record it with no lag or was it fixed?

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit  I just tested six demon bag and the delayed cast is still there

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit  https://youtu.be/asv2MyOEU6I

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit I just tested six demon bag and the delayed cast for frostbolt is still there

Its not caused by lag on elysium

https://youtu.be/asv2MyOEU6I

retail video above on youtube shows there is no delayed cast.
