### ISSUE TITLE
New skills disappearing from trainer when levelling - without being able to train

### ISSUE THREAD

**Issue by admansrq** [elysium-project/server#1035]
My priest hit level 22. At 20, trained and saw the level 22 skills (smite 4, etc). Once I hit 22, went to trainer and there were no skills for 22, just for 24

Smae happened on my mage levelling tailoring

**Comment by m-laniakea** [comment]
@admansrq In the top right corner of the trainer window, make sure the green "Show available" is checked.

**Comment by thepparker** [comment]
Closing pending further info
