### ISSUE TITLE
Faerie Fire (feral) doesnt register as a talent.

### ISSUE THREAD

**Issue by BonoboWoW** [elysium-project/server#1036]
The talent Faerie fire (feral) doesnt register as a talent when u learn it from the talent tree, it is learned in the book of spells tho.
Here are screenshots of me being specc 0/29/21 at lvl 60 being stuck with 50 talents points : 
http://imgur.com/a/qLZwb
It happened as i respecced on the 9/06/2017. I respecced twice and same results every time.

**Comment by DonkeyKongRacer** [comment]
Works fine on my local server. 
Might be an issue with the server's DBC, I don't really know, but this is not an issue with the core.
http://imgur.com/a/ax6Fk

**Comment by BonoboWoW** [comment]
I cant really try it more as it will only end up with me running out of gold for no reason. I dont know what to do, i tried a third time and it still appear like this when I press the Faerie Fire (feral) talent (it register in the book of spells but not in the talent tree resulting in me loosing a talent.)

**Comment by DonkeyKongRacer** [comment]
Don't do it and call an admin, there's no point in doing a respec. I don't know where the bug comes on their part but all I can see is broken DBC files, given they use the same core and database.

**Comment by BonoboWoW** [comment]
well i really wanted to play today so i respecced a fourth time and it actually worked... I dont understand what happened, but i lost 50gold.
