### ISSUE TITLE
Hero of the Stormpike/Frostwolf quests not added in 1.8.0 update

### ISSUE THREAD

**Issue by realredaria** [elysium-project/server#1037]
The title basically says it all. The quests added in patch 1.8.0 to replace the Korrak kill quests were not added, as the Korrak quests are still available. These quests are Alterac Valley quests, one for the Alliance and one for the Horde.

**Comment by GuybrushGit** [comment]
Elysium might want to keep AV pre-nerf past 1.8, like Nost did.

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
