### ISSUE TITLE
Priest's Zandalar Confessor's bindings fail to apply its healing effect on its carrier

### ISSUE THREAD

**Issue by baque** [elysium-project/server#1042]
**BUGGED BEHAVIOR**
I put on both mine Zandalar Confessor's Mantle and Confessor's bindings ( see the first picture I linked under SOURCES) , and from the panel of my stat addon on the top-right, you can see only 44 healing effects has been applied on me, which is 22 healing from the mantle plus the 22 healing from the 2/5 effect of confessor's set.

**CORRECT BEHAVIOR**
It should apply its own healing effects, which is 24 to its carrier

**SOURCES**
![1sd1qsd](https://user-images.githubusercontent.com/6969028/26999420-882ba18a-4dcb-11e7-9c36-8d51cfbbe6b4.jpg)

**Comment by stesve** [comment]
Your addon doesn't recognize the set-bonus.

**Comment by baque** [comment]
> Your addon doesn't recognize the set-bonus.
If my addon doesn't count the bonus, it must show as 46 instead of 44. (22 from shoulder and 24 from waist)

**Comment by baque** [comment]
> No matter what. Your addon doesn't know how the server is handling the stats, it just read numbers from your items.
Then could you tell me how the server handles the stats?

**Comment by brotalnia** [comment]
Spell healing/damage is not an actual stat that can be assigned to items, like it is in wotlk, but a spell aura that is added as an "on equip" effect. If you believe a certain bonus is not getting applied, an easy way to test it would be to edit the spell that gives the bonus in Spell.dbc and give it an absurd value like 9999. If your heals are healing for a huge amount after the change, then the bonus is being correctly applied. To see the id of the spell applying the spell power bonus, find the item on db.vanillagaming.org and simply click on the effect. It will take you to the spell that is used, and you can see the Id at the end of the url.

**Comment by baque** [comment]
> Spell healing/damage is not an actual stat that can be assigned to items, like it is in wotlk, but a spell aura that is added as an "on equip" effect. If you believe a certain bonus is not getting applied, an easy way to test it would be to edit the spell that gives the bonus in Spell.dbc and give it an absurd value like 9999. If your heals are healing for a huge amount after the change, then the bonus is being correctly applied. To see the id of the spell applying the spell power bonus, find the item on db.vanillagaming.org and simply click on the effect. It will take you to the spell that is used, and you can see the Id at the end of the url.<


Looks it works fine now after i updated my addon and deleted the WDB folders.
