### ISSUE TITLE
"The Test of Righteousness" Paladin quest bugged

### ISSUE THREAD

**Issue by ColinBundschu** [elysium-project/server#1043]
The quest log says complete, I have all 4 of the items in my inventory, but the quest giver has a gray question mark and I cannot turn it in.

**Comment by GuybrushGit** [comment]
What did you do with the quest items to cause this?

**Comment by ColinBundschu** [comment]
I didn't do anything with them I don't think. At one point some of them were in the bank.

**Comment by GuybrushGit** [comment]
That was it then.

**Comment by ColinBundschu** [comment]
Wait does that break quest items? That seems like a pretty serious bug if so.

**Comment by GuybrushGit** [comment]
Its not a quest issue. This happens when the player does some very specific actions, for example banking an item by dragging and then taking it out by right clicking (already fixed this here https://github.com/elysium-project/server/pull/1039).

**Comment by thepparker** [comment]
Duplicate
