### ISSUE TITLE
[Quest] The Matron Protectorate

### ISSUE THREAD

**Issue by Miracilous** [elysium-project/server#1044]
The quest "The Matron Protectorate" in Winterspring is bugged. I have the quest item required in my bags ( "Awbee's Scale" ) and I can't turnin the quest, it shows as grayed out. I made a tricket about this and GM <Thari> told me to put the quest item in my bank, then exit the game and delete my WDB folder and try again. So after doing all that I grabbed the quest item from my bank once more and went to the quest NPC (Haleh) and it still didn't let me complete it.
![x41pxtx](https://user-images.githubusercontent.com/21103661/27005180-ab1c7c22-4e21-11e7-8d0c-ba7b3a21b4e3.jpg)

**Comment by GuybrushGit** [comment]
Drag the item to the bank and drag it back to your inventory (dont right click it).

**Comment by thepparker** [comment]
Duplicate
