### ISSUE TITLE
Warlock - Improved Drain Soul

### ISSUE THREAD

**Issue by lduguid** [elysium-project/server#1045]
Have 2/2 in Improved Drain Soul, should be 100% proc if kill target with drain, does not seem to proc at all now.  I know I am getting the kill as its generates a soul shard.  I believe it was working previously.

**Comment by lduguid** [comment]
After playing for about 5 more levels, I did see it actually proc and return mana but I could count on one hand how many times it has done it, the way I read if the talents are 2/2 it should proc 100%.

**Comment by Spaztick** [comment]
If your pet kills the target instead of you the buff won't proc.

**Comment by lduguid** [comment]
Two thing;
1. It seems strange that if my pet is sniping the kill, I still get the soul shard or is the soul shard based on the fact that I am channeling when the mob dies as opposed to me getting the actual killing blow?
2. At first I thought it may have been just that, a client side visual bug, but I also noticed that I was not getting any mana returned as well as not seeing the proc buff.

Anyway, should be easy enough to confirm, will just make a hack macro to put pet on passive when draining soul, that way it should never snipe the kill and I should in theory see it proc 100% if what you say is true.

If confirmed, I will come back and close this issue ticket in a day or two.

Cheers.

**Comment by lduguid** [comment]
As stated by Spaztick, this was indeed the problem, pet sniping killing blow.  For anyone else interested, my solution was to use a macro that made the pet passive when draining soul, which in turn saw my improved drain soul working as expected. cheers.

**Comment by goudekid** [comment]
Is there any reason to believe your pet should be able to snipe your imp drain soul proc from you? That seems like a bug to me but I can't find anything regarding it one way or the other from before the launch of TBC
