### ISSUE TITLE
Equipping Carrot on a Stick in-flight resets the flight spline progress

### ISSUE THREAD

**Issue by martinjlowm** [elysium-project/server#1046]
When the player equips `Carrot on a Stick` while on a flight path, the client resets the progress of the flight by returning to the starting point.

**Comment by fgsfdss** [comment]
Changing any item equips while flying does this actually.

**Comment by sknnbones** [comment]
Huh... I get "you are mounted" when trying to equip/unequip items while flying

**Comment by fgsfdss** [comment]
Still happening. Found out not every item switch causes this to happen, only those that alter movement speed in some way. (Mainly Carrot and boots enchanted with movement speed.)
Relogging fixes the flight but it's still a pain, especially if you use Outfitter.

**Comment by thepparker** [comment]
Duplicate #927
