### ISSUE TITLE
AQ40 boss armor values [close pls since its fixed already]

### ISSUE THREAD

**Issue by taurenrogue** [elysium-project/server#1049]
Currently on Anathema Fankriss, C'thun, Emperor Vek'nilash and probably a few more that I didn't check have a base armor value of 6220.
Few minutes of watching youtube kills of AQ bosses, and simple math should prove that they should have ~4691 armor instead...

**Comment by gemt** [comment]
It's the Elysium teams attempt to make our dps slightly more in line with what it would have been in patch 1.9, considering all the differences between a 1.9 and 1.12.1 client/server etc. For AQ it might not be completely unreasonable, as long as they don't do it for Naxx too, where it makes no sense with those arguments in mind

**Comment by taurenrogue** [comment]
So... a grand total of 5 weapon skill a rogue for example gained from patch 1.9 to 1.12 (that can be offset with gear) is equivalent to 1529 armor??

Why not increase resistances? Boss HP? Anything but just a flat gimp to only 3 classes in the game?

What this does atm is gimping physical dps, and making guilds bring more caster heavy groups to AQ40, and therefore does almost nothing to the "difficulty of the fight"...

Also why are armor values in bwl/mc "low" if we want to "compensate for how amazing melee get with minor talent changes"?

I guess im rolling a mage/warlock soon...

**Comment by Netherfrost** [comment]
#AllClassesMatter #StopMeleeDiscrimination

**Comment by gemt** [comment]
The resistances are increased too. Casters are op because casters were op in AQ. Just look at the basic mechanics of the fights. Straight up singletarget nuke of a boss, and melees compete with casters. It's all the movement and resistance gear that nerfs melees, not the armor. 

I'm not part of the Elysium team. I'm just reporting what I know. I never agreed with the armor/resistance changes either, but it was an argument to be had there to compensate for some of the class and core mechanic changes from 1.9 to 1.11/12. Was it the right way to go about it? Idk.

**Comment by Netherfrost** [comment]
75 which is negated by the curse? You can't call that increased resistances, unless youre referring to the first day of AQ

**Comment by fgsfdss** [comment]
Current boss resistance in AQ (according to public db)
Skeram: 115
Bug Trio: 135
Sartura: 135
Viscidus: 155
Huhuran: 175
Twins: 195
C'Thun: 215

**Comment by Netherfrost** [comment]
This is not whats on live.

**Comment by Netherfrost** [comment]
Could any official shred some light on this custom change?

**Comment by taurenrogue** [comment]
current boss resistances in AQ on anathema:  75 arcane/shadow/frost/fire (0 with curses) on ~every boss
current boss armor values in AQ on anathema: 6220 on every boss....
?

**Comment by vindruvor** [comment]
Current boss resistance in AQ (according to public db)
Skeram: 115
Bug Trio: 135
Sartura: 135
Viscidus: 155
Huhuran: 175
Twins: 195
C'Thun: 215


Is this from Anathema's Source Code you mean?

**Comment by taurenrogue** [comment]
/run DEFAULT_CHAT_FRAME:AddMessage("> "..UnitResistance("target",6).." arc, "..UnitResistance("target",2).." fire, "..UnitResistance("target",3).." nat, "..UnitResistance("target",4).." fro, "..UnitResistance("target",5).." sha")
^from this macro

**Comment by fgsfdss** [comment]
Yes it is vindruvor, but if taurenrogue's macro is correct then that db is unreliable anyway.

**Comment by vindruvor** [comment]
ive heard that that macro only shows the resistance values of your client, not necessarily the server's scripted values

**Comment by taurenrogue** [comment]
even if above was the case it wouldnt explain the lack of partial resists by mages on cthun for example...
still the problem is: why increase both armor (already increased) and resists(not increased) if one can just give the mobs more HP instead...

**Comment by taurenrogue** [comment]
This can now be closed since armor has been fixed pretty much on bosses/trash in aq
