### ISSUE TITLE
Eastern Plaguelands Herb Spawns

### ISSUE THREAD

**Issue by Kotopess** [elysium-project/server#105]
Issue: herb spawn node quantity, herb spawn timers, and herb pick-up chances have all diminished since about 2 weeks ago (server crash - with 2 day downtime). This was an issue in EPL about 4 weeks ago, but seemed to get fixed. It has now repeated. In a single day I managed to get 9-11 spawns with 1 herb, 5 spawns with 2 herbs, no spawns with 3 herbs. While I understand this may be an anomaly, it is a daily issue now. 

Source: Me. I sit in EPL 3-4 hours a day picking herbs. The competition is very low and plaguebloom market is skyrocketing to 45-55g/stack. 

Even with oversaturation of players in EPL in the past, the herbs have not been this bad. Any clarification on this?

**Comment by Kotopess** [comment]
This applies to sungrass, plaguebloom, arthas tears, golden sansam and dreamfoil.

**Comment by m-laniakea** [comment]
Spawntime for these herbs has been significantly reduced.

**Comment by Kittnz** [comment]
Any commit for this issue? I don't see any changes, why is this issue closed?
