### ISSUE TITLE
Improved Devotion Aura bugged

### ISSUE THREAD

**Issue by Khailik** [elysium-project/server#1051]
Either the Improved Devotion Aura talent or the buff tooltip is bugged. I have 2 points in the talent but still only have 55 armor from the buff.

**Comment by Spaztick** [comment]
Upload screenshots.

**Comment by Khailik** [comment]
http://imgur.com/d0iSnTq
http://imgur.com/Xj1ir9y
http://imgur.com/6d5qdjn

**Comment by Spaztick** [comment]
Buff tooltips don't change with talents.
