### ISSUE TITLE
Grave Moss spawn timers 1-2h+

### ISSUE THREAD

**Issue by Grimjoy123** [elysium-project/server#1052]
I've seen this issue being posted here before and just want to magnify it. The respawn timers should be 6-8min or something which is blizzlike.

 I currently try farming them on Zeth'Kur as the lone Grave Moss farmer, no competition, been camping both Ironbeards tomb and raven hill cementary and the fastest respawn I came across yet is 1h 30min.

There's literally NO grave moss ever on AH and people are even making videos on how to farm it in SM GY because there's 1 spawn in there thats guaranteed and u can do it 4 times in a hour. 

Now for things to go THAT far, it's clearly become an major issue especially with Naxxramas and Greater Shadow Protection Potion consuming soon coming up on Anathema.

Blizzlike: http://www.wowhead.com/item=3369/grave-moss#comments
Issue: https://elysium-project.org/bugtracker/issue/2551

**Comment by stesve** [comment]
There is only vanilla comment on that page and it actually recommends farming them in SM.

> Farming for these for Loatheb has made me want to kill myself.

> But, if you are looking to farm them, I've found the best place to be in Scarlet Monastery. I'm getting about 3 grave moss and some kingsblood and fadeleaf every time i reset the graveyard.

**Comment by Grimjoy123** [comment]
Alright, what about the missing spawns?

**Comment by GuybrushGit** [comment]
Respawn is 30 mins but 2/3 of the nodes on the database are disabled, no clue why.

**Comment by Grimjoy123** [comment]
LEGEND, thank you sir for helping out!
