### ISSUE TITLE
'Elixir of Poison Resistance' Bug

### ISSUE THREAD

**Issue by mubeopja** [elysium-project/server#1055]
Translator is in use. Thank you in standard language.

Because 'Elixir of Poison Resistance' is Elixir, it must be available regardless of the potion's latency.

But now 'Elixir of Poison Resistance' shares potions and latency. After using 'Elixir of Poison Resistance', you can not use 'Elixir of Poison Resistance' and potions for 2 minutes.
I can not use 'Elixir of Poison Resistance' for 2 minutes after using potion.

**Comment by m-laniakea** [comment]
This was done on purpose. It won't change for now.

**Comment by mubeopja** [comment]
Translator is in use. Thank you in standard language.

Why did you intentionally change it? Is it not the balance break that is advantageous only for rogue?
And I'm wondering if there will be a patch to fix it in the future. If you have a patch scheduled, please let me know. And if you do not plan on patching, please let me know why.

# Mage has to make a distance to fight rogue. The only skill to open that distance is 'blink'. Rogue uses stun skill and mage uses 'blink' to spread the distance. At this time, rogue will give the mage a stun skill and 'gouge' at the same time, and the mage will take 'blink' and 'gouge' at the same time.
The only skill that allowed mage to open the streets was useless.
This is a very good bug for rogue.
+
Changing 'Elixir of Poison Resistance' to make it more advantageous for rogue is a big deal.

**Comment by mubeopja** [comment]
Translator is in use. Thank you in standard language.

Why did you intentionally change it? Is it not the balance break that is advantageous only for rogue?
And I'm wondering if there will be a patch to fix it in the future. If you have a patch scheduled, please let me know. And if you do not plan on patching, please let me know why.

# Mage has to make a distance to fight rogue. The only skill to open that distance is 'blink'. Rogue uses stun skill and mage uses 'blink' to spread the distance. At this time, rogue will give the mage a stun skill and 'gouge' at the same time, and the mage will take 'blink' and 'gouge' at the same time.
The only skill that allowed mage to open the streets was useless.
This is a very good bug for rogue.
+
Changing 'Elixir of Poison Resistance' to make it more advantageous for rogue is a big deal.

**Comment by mubeopja** [comment]
Translator is in use. Thank you in standard language.

Why did you intentionally change it? Is it not the balance break that is advantageous only for rogue?
And I'm wondering if there will be a patch to fix it in the future. If you have a patch scheduled, please let me know. And if you do not plan on patching, please let me know why.

# Mage has to make a distance to fight rogue. The only skill to open that distance is 'blink'. Rogue uses stun skill and mage uses 'blink' to spread the distance. At this time, rogue will give the mage a stun skill and 'gouge' at the same time, and the mage will take 'blink' and 'gouge' at the same time.
The only skill that allowed mage to open the streets was useless.
This is a very good bug for rogue.
+
Changing 'Elixir of Poison Resistance' to make it more advantageous for rogue is a big deal.

**Comment by mubeopja** [comment]
Translator is in use. Thank you in standard language.

Why did you intentionally change it? Is it not the balance break that is advantageous only for rogue?
And I'm wondering if there will be a patch to fix it in the future. If you have a patch scheduled, please let me know. And if you do not plan on patching, please let me know why.

Mage has to make a distance to fight rogue. The only skill to open that distance is 'blink'. Rogue uses stun skill and mage uses 'blink' to spread the distance. At this time, rogue will give the mage a stun skill and 'gouge' at the same time, and the mage will take 'blink' and 'gouge' at the same time.
The only skill that allowed mage to open the streets was useless.
This is a very good bug for rogue.
+
Changing 'Elixir of Poison Resistance' to make it more advantageous for rogue is a big deal.
