### ISSUE TITLE
Enemy NPC Minions aggroing from way too far away when right clicked

### ISSUE THREAD

**Issue by oloens** [elysium-project/server#106]
When right clicking the enemy or the minion from a far distance the minion aggros.

**Comment by turinpt** [comment]
Issue happens here but I don't know enough about PetAI to fix it:
https://github.com/elysium-project/server/blob/43452c0d9cdce841bef71c592a381c38fb68d37a/src/game/AI/PetAI.cpp#L470

When you right click a pet you get inserted into his attackers list. The pet's update thread will then run by that code and attack whatever is on its attacker list.
