### ISSUE TITLE
Skeram teleports to the same platform

### ISSUE THREAD

**Issue by Hechie** [elysium-project/server#1063]
When skeram splits he sometimes teleport to the same location, so you will have to AOE taunt all 3 clonse this is sadly not blizzlike and should be changed so more players can enjoy AQ 40 :)

https://www.youtube.com/watch?v=K-A9l8bL_Fw&t=12s

**Comment by thepparker** [comment]
Either I don't understand the issue you're reporting, or you are wrong. https://youtu.be/K-A9l8bL_Fw?t=337, one of the clones clearly teleports to the same platform as an existing clone.

**Comment by Hechie** [comment]
Ye 1 at The time On anathema They teleport all 3 at The same time

**Comment by Pleasant-Elysium** [comment]
This isn't a bug, this is "Blizzlike."

**Comment by Hechie** [comment]
well then, its now how i remember it but its also ages ago i have been there. i just dont remember it doeing a 3 skeram teleport to the same platform :+1:
