### ISSUE TITLE
" Setup"rogue talent subtlety not working at all.

### ISSUE THREAD

**Issue by neale111** [elysium-project/server#1065]
Bugged behaviour: 
"Setup" from rogue's subtelty talent tree is not working at all. It is bugged and does not give combo points at all.

Correct behaviour:
"Setup" adds 1 combo point every after dodged attack or resisted spell.

1/3  15% chance
2/3 30% chance
3/3 45% chance

**Comment by WobLight** [comment]
It works just fine on development branch, can you double check and/or provides additional info?

**Comment by neale111** [comment]
Hi currently setup does not give combo points on rogue dodges or resists.
 It never does.
 I have 2/3 setup talent

It should show +combo text on dodges or resists of rogue if it ever worked.
Anathema pvp

**Comment by afrodav** [comment]
![setup_rogue](https://user-images.githubusercontent.com/31714101/30140767-28b2bf6c-9377-11e7-92a3-aa065527b5f2.jpg)

Hello I have tryed to get a combo point through dodging with 3/3 Setup talent.
Even with Evasion on dodging nearly every attack I dont get a singe combo point.

I set all my Talent points torwards this Setup talent, now i will have to set them again D:

Anathema pvp

**Comment by neale111** [comment]
It is fixed now guys, it now gives combos properly.

**Comment by neale111** [comment]
I tested 2/3 and it works properly now. But afridav's testing says 3/3 does not work properly pve?

**Comment by afrodav** [comment]
Ahhh wow ok now it works thank you. 
It alsow works PVE now 3/3 and i figured you have to attack the target actively so the dodges make combo points.  

Regards, David.

**Comment by neale111** [comment]
Alright the talent setup is now fixed and works properly now.

**Comment by fgt1234** [comment]
''Setup'' still doesn't work properly, the dodge part was fixed and it works, however, it doesn't add combo points in spell resists, not versus mobs nor players, it completely lacks this element.
