### ISSUE TITLE
Quest: Nefarius's Corruption timer is far too short.

### ISSUE THREAD

**Issue by Spaztick** [elysium-project/server#1066]
Bugged behavior: The quest line for the red scepter shard for Scepter of the Shifting Sands (Nefarius' Corruption) currently has a timer of 90 minutes.

Correct behavior: The blizzlike time for the quest was five hours.

**Comment by m-laniakea** [comment]
This was done on purpose to make the challenge similar in difficulty. Times change.

**Comment by Spaztick** [comment]
And yet the timer includes having to go to Anachronos to complete the quest, which often times means waiting another week to accept the quest so you have time to turn it in. Are the developers interested in being blizz-like or not?
