### ISSUE TITLE
Feral Dragonhawk Hatchling cannot be skinned

### ISSUE THREAD

**Issue by preslim** [elysium-project/server#1067]
I picked up skinning along with my skinning knife outside Silvermoon.  

I say that the tooltip for Feral Dragonhawk said they were beast but cannot skin their body.  Should be labeled dragon possibly?

**Comment by m-laniakea** [comment]
Didn't know we're running the Burning Crusade expansion. Sure you're in the right place?

**Comment by preslim** [comment]
oh i'm sorry, i was given the wrong link
