### ISSUE TITLE
[Elysium] Mana Tide Totem incorrect number of ticks

### ISSUE THREAD

**Issue by Belzique** [elysium-project/server#1073]
The attached image shows four instances of Mana Tide Totem being dropped and the amount of mana it restored. These results were produced with the following procedure:

Casting Healing Wave four times to both clear the combat log as well as provide confirmation of this indeed being four different instances due to absence of time stamps by showing the different amounts healed between screenshots.
Casting Mana Tide Totem and waiting until it disappears.
Casting Healing Wave a few additional times to again provide separation as well as prove that there were indeed no more ticks to be seen as obviously the additional casts would take longer than another tick would take.

In this video https://youtu.be/ZMrEgNF8fZ0?t=5m43s starting at 5:48 (link starts video at 5:43 for your convenience) you can see a shaman, attempting a Four Horsemen kill on October 2006, drop a Mana Tide Totem. Slow the video and monitor the combat log and you will clearly see five ticks of Mana Tide, not three or four.

At the moment Mana Tide Totem seems to not be ticking upon cast and sometimes failing to tick prior to despawning.

Please help us restore up to 2900 more mana to our group.

![manatide](https://user-images.githubusercontent.com/29428405/27132605-fd277082-50fe-11e7-9105-3fee994ec30a.jpg)

**Comment by Phoosy** [comment]
Possibly related: https://github.com/elysium-project/server/issues/887

Could be a timing issue.

**Comment by thepparker** [comment]
It is indirectly related. I'm looking into fixing this while squashing the channeling issue as well
