### ISSUE TITLE
Goblin jumper cables not working on released players.

### ISSUE THREAD

**Issue by SiguDS** [elysium-project/server#1074]
At the moment Goblin Jumper Cables XL (Id=18587) only work if the specific player has not released. If the player releases it's not possible to ress with the cables which to my knowlegde is not how it should be working.

Video of it not working once you have released on anathema core: https://www.youtube.com/watch?v=aR37z9BkGTg&

Check comment for source link.

Dunno if this is evidence is enough if people are not convinced it's a bug:
A long thread discussing jumper cables not a single one mentioning it having issues on released players. 
[https://www.gamefaqs.com/boards/534914-world-of-warcraft/46340685](url)
Another thread not talking about it (though TBC)
[https://www.gamerswithjobs.com/node/1131436](url)
A person describing that he had around 50 % sucess rate with it back in 2008. I know it's a vague argument but i would guess if it did not work on people that released spirit you would find the success rate quite a lot lower. http://i.imgur.com/BlEJGmg.png
Also i have yet to find any thread talking about it only working on people who did NOT release spirit.

(Tjofmajik is saying it should work after a person is released and i would like to use him as source)

**Comment by SiguDS** [comment]
Found a souce[https://web.archive.org/web/20060216113529/http://wow.allakhazam.com:80/db/item.html?witem=18587](url) "My normal cables work 1 in 3 times. However it is vital the dead person does not do release spirit otherwise they never work."
"It's a common misconception that the person can not release for jumper cables to work.  I have used them on our groups priest after they had released and was out at the graveyard. You just have to make sure you have their body selected when you try to use them, don't click on their portrait in the group window.   "

**Comment by Maartix** [comment]
Are you sure about this, I have tried it over 10 times on released players. I dont even get the 100 dmg proc from "failed" attempts when it does. Always fail no "short stun".

**Comment by SiguDS** [comment]
What? You mean it doesn't work on released players? that is what i'm trying to report as a bug.

**Comment by Phoosy** [comment]
He is referencing archive material indicating it is _supposed_ to work on released players despite the claim that it might have mattered in retail back then - if it does not actually work when a player is released rather than conjecture assuming it doesn't, then it's a bug that needs to be fixed.

**Comment by SiguDS** [comment]
Well i did make a video where we tested it :)

**Comment by SiguDS** [comment]
@GuybrushGit PLZ save these poor lost souls!

**Comment by SiguDS** [comment]
https://www.youtube.com/watch?v=zrBOEGtevgw&
Another instance of it not working on live anathema

**Comment by SiguDS** [comment]
Another recording of it
https://www.youtube.com/watch?v=58NwwzdO4Po&
