### ISSUE TITLE
Barkskin does not reduce falling damage

### ISSUE THREAD

**Issue by Fiskehatt** [elysium-project/server#1075]
### **Bugged behavior** 

[Barkskin ](http://db.vanillagaming.org/?spell=22812)does not reduce falling damage in any way at the moment. I made 5 test jumps with and without Barkskin from a fixed height and did not notice any significant difference:

| No Barkskin | With Barkskin |
|-------------|---------------|
| 1422        | 1422          |
| 1331        | 1363          |
| 1349        | 1422          |
| 1422        | 1325          |
| 1326        | 1331          |

### **Correct Behaviour**

Barkskin should reduce falling damage (which is physical damage) by **20%** as stated by its tooltip:

"The druid's skin becomes as tough as bark. **Physical damage taken is reduced by 20%.** While protected, damaging attacks will not cause spellcasting delays but non-instant spells take 1 sec longer to cast and melee combat is slowed by 25%. Lasts 15 sec."

Thus, the fall damage with Barkskin should have been in my tests around:

**Fall damage = avg dmg * 0.8 = 1370 * 0.8 = 1096 = ~1100**

### **Additional evidence**

A blog post at [http://darksoda.com/blog/?p=3](http://darksoda.com/blog/?p=3) quotes a post by Pythka on the WoW Forums (7/14/2006 - patch 1.11.2(?)) that states:

"**Barkskin lessens falling damage**"

In addition, I was unable to find any evidence that Barkskin was changed in relation to falling damage after 1.11.2 so I would assume the 20% reduction was in place at least until the end of Vanilla.

**Comment by GuybrushGit** [comment]
Same for Shield Wall:
https://www.gamefaqs.com/boards/534914-world-of-warcraft/49430135?page=1

**Comment by vindruvor** [comment]
Does this mean I take less damage as a warrior when I swap from for example Berserker stance to defensive stance?

**Comment by Fiskehatt** [comment]
It should as it reduces "all damage taken":

> Decreases damage taken from **all sources** by 10%. Decreases damage caused by 10%.
Increases threat generated by 30%.

[Some proof](http://www.gamesradar.com/cheats/4024/) (although from TBC):

> The other essential for tanking is defensive stance. It will reduce all damage
taken (physical, magical, **fall** and any other way you manage to injure yourself)
by 10% and gives a boost to your threat generated which is much more than you
will lose from the -10% damage.

Apparently, it worked even in later [expansions](http://wowironmanchallenge.proboards.com/thread/1318/falling-damage-avoid).
