### ISSUE TITLE
No loot Razorgore Darrowshire 

### ISSUE THREAD

**Issue by Venustas1337** [elysium-project/server#1076]
At 20:09 ST 14-06-2017 <Might and Magic> (A) Darrowshire downed Razorgore in BWL, which gave no item loot, only gold. The body was skinned after looting the gold.

Video proof of the encounter and looting: https://www.youtube.com/watch?v=8wZaYksRemA&feature=youtu.be
Raid ID: 1007

**Comment by Phoosy** [comment]
An in-game needs to be made using the Help interface. You've met part of the requirements listed here: https://forum.elysium-project.org/topic/47242-boss-looting-failures/. See below for what you're missing.
`There should be one ticket, multiple tickets slow us down, confuse the situation and can lead to refusal.

This ticket should come from the raid leader or a nominated replacement. If the person sending the ticket is not the raid leader, they should say on the ticket in what capacity they are sending the ticket, and indicate that the named raid leader has asked them to.`

**Comment by Venustas1337** [comment]
Thanks for the help. Ingame ticket will be made.
