### ISSUE TITLE
Lunar Wand should be able to get +23 damage or +35 healing

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#1078]
Lunar Wands don't seem to go beyond +13 spell damage or +20 healing. They should be able to go higher.

Source: https://web.archive.org/web/20060304235858/http://wow.allakhazam.com:80/db/item.html?witem=15283

**Comment by adura90** [comment]
Even on 1.0.9 itemization?

**Comment by Sabre142** [comment]
@adura90 Need to be implemented on Elysium, Zeth'kur and Darrowshire.

**Comment by adura90** [comment]
OK, but are those stats correct for the current itemization patch? If so, prove it.

**Comment by GuybrushGit** [comment]
Same as https://github.com/elysium-project/server/issues/1077
