### ISSUE TITLE
"Boat Wreckage" Quest bugged.

### ISSUE THREAD

**Issue by Ichena** [elysium-project/server#1080]
I can't get the follow quest of "The Missing Courier" from the boat wreck on the shore in feralas. I Turned it in and said "you do not meet the requirement". However the only requirement fo the followup quest is to turn that quest in.  So I am curious how I get the follow up quest called "Boat Wreckage" in feralas. Since I can not do all the follow quests (10 total) and I will miss out on important rewards such as reputations.
I can not interact with the sunken boat at all as of this moment, so I can not get the quest or even see it, however a friend of mine I level with got it. So now she will level up faster than me and get more reputation.
She can not share the quest with me either because it's an dagger called "discarded knife" that you get from picking up the quest.

**Comment by TNadal** [comment]
what level are you.

**Comment by Ichena** [comment]
47

**Comment by TNadal** [comment]
check your quest log and make sure you don't have it. check your inventory and make sure you don't have any of the quest items related to the quest (if you do, destroy them) then i'd start at Latronicus Moonspear, verify that he doesn't have the quest for you. go down the list till you get to the part you turned in and were told the quest is unavailable. if none of that allows you to pick the quest back up:

what race are you ingame, and what level did you try the quest at previously?

**Comment by Ichena** [comment]
GM contacted me ingame saying that it was reset and I should check back with Latronicus as well. I got it now. Ty for the tip and awesome work of the GM staff.
