### ISSUE TITLE
Quest completion with correct items in inventory won't allow turn in

### ISSUE THREAD

**Issue by shmigy429** [elysium-project/server#110]
First had this happen with [Ledger from Tanaris](http://db.vanillagaming.org/?quest=4450) I collected all of the items and get to Tanaris for the hand in and [Krinkle](http://db.vanillagaming.org/?npc=5411) has a grey ? and can't hand in the quest. 

Fix suggestions from the comment section are:
-Put items in the bank then take them out again
-Abandon quest and re-take

I tried the abandon one first (uggh forgot the quests starts in Searing Gorge) and got the quest again and handed in the quest no problem.

Happened again at the Blasted Lands quests:
[Snickerfang Jowls](http://www.wowhead.com/quest=2581/snickerfang-jowls)
[A Boars Vitality](http://www.wowhead.com/quest=2583/a-boars-vitality)
etc..

Pick up the quests, go kill the mobs to get the correct amount of items and go to turn in; the quest giver has a grey ? and can't hand in the quest.

Abandon Quest -> Retake same quest -> Hand in works fine

I think it's worth mentioning the similarity of after picking up the quests I: 
-Got some of the quest items
-Logged out at some point
-Logged back in 
-Finished getting the quest items
-Tried to hand in the quest

**Comment by llacczy** [comment]
As far as i know this quest has the same bug, where you have to retake the quest to complete:

[Seasoned Wolf Kabobs](http://db.vanillagaming.org/?quest=90)

**Comment by QAkvastskaft** [comment]
Issue on old tracker for reference: 
https://elysium-project.org/bugtracker/issue/2134
https://elysium-project.org/bugtracker/issue/3848
