### ISSUE TITLE
Mind Control

### ISSUE THREAD

**Issue by WobLight** [elysium-project/server#1100]
Upon breaking, a lot of thread should be generated. Currently the NPCs run home instead.

# [WoWWiki](http://wowwiki.wikia.com/wiki/Mind_Control?oldid=243595)

> When the spell ends, the controlled unit -- if not a player -- will have a large degree of aggro on the priest who controlled it.

 # [video](https://youtu.be/cQ3gkWbnNnM?t=62)
You can see after breaking, the priest is still in combat being chased by the formerly controlled NPC.

**Comment by neutrals** [comment]
Can confirm, believe it generated around 1000 threat per cast back in vanilla, as a single fade (-800) was not enough to drop aggro back then.

**Comment by WobLight** [comment]
According to other sources threat is equal to the target's HP.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/50445-development-update-19072017/
