### ISSUE TITLE
Various Item stuff

### ISSUE THREAD

**Issue by some2** [elysium-project/server#1102]
**Manaweave Robe (ID: 7509):**

BuyPrice/SellPrice should be 1376/275 (*8) instead of 2769/553
ItemLevel should be 15, not 20 (*8)

**Evergreen Pouch	(ID: 11020):**

RequiredLevel should be 0, not 47 (Blizzlike).
Nostalrius changed this to 47 (*9) but i dont know why.

**Seeping Willow (ID: 12969):**

Speed should be 3.3 (instead of 3.6) and dmg 142-214 (instead of 155-233) (*11)

**Reins of the Winterspring Frostsaber (ID: 13086):**

ItemLevel and RequiredLevel should be 60 (not 40), BuyPrice should be 10000000 (1000g not 100g, without exalted bonus) (*12)

**Beheading Blade:**

RequiredLevel should be 57, not 47. (*15)

**Hurricane (ID: 2824):**

BuyPrice/SellPrice should be 160159/32031 (*1) instead of 160160/32032

Until 1.11.0: Should deal addional frost damage (1-5 dmg) (or physical - blizzbug) (*2)
1.11.0 and later: Chance to trigger a damaging frost effect (31-45) (*3)

**Dwarven Hand Cannon (ID: 2099):**

Until 1.12.0: Should deal addional fire damage (1-11 dmg) (or physical - blizzbug) (*5)
1.12.0 and later: Chance to trigger a damaging fire effect (33-49) (*4)

**Bow of Searing Arrows (ID: 2825):**

Until 1.12.0: Should deal addional fire damage (1-5 dmg) (or physical - blizzbug) (*7)
1.12.0 and later: Chance to trigger a damaging fire effect (18-26) (*4)

**Venomstrike (ID: 6469):**

Until 1.12.0: Should deal addional nature damage (3-6 dmg) (or physical - blizzbug) (*6)
1.12.0 and later: Chance to trigger a damaging nature effect (31-45) (*4)

**Galgann's Fireblaster (ID: 9412):**

Until 1.12.0: Should deal addional fire damage (1-3 dmg) (or physical - blizzbug) (*6)
1.12.0 and later: Chance to trigger a damaging fire effect (12-18) (*4)

**Shell Launcher Shotgun (ID: 13146):**

Until 1.12.0: Should deal addional fire damage (1-4 dmg) (or physical - blizzbug) (*6)
1.12.0 and later: Chance to trigger a damaging fire effect (18-26)

----------------------------------------------------
1 http://www0.xup.in/exec/ximg.php?fid=66640670 (BradyGames Official Strategy Guide)
2 http://wowwiki.wikia.com/wiki/Hurricane_(bow)?oldid=283527
3 http://wowwiki.wikia.com/wiki/Patch_1.11.0
4 http://wowwiki.wikia.com/wiki/Patch_1.12.0
5 http://wowwiki.wikia.com/wiki/Dwarven_Hand_Cannon?oldid=157660
6 http://wowwiki.wikia.com/wiki/Venomstrike?oldid=99392
7 http://wowwiki.wikia.com/wiki/Bow_of_Searing_Arrows?oldid=157685
8 http://www0.xup.in/exec/ximg.php?fid=60425525 (BradyGames Official Strategy Guide)
9 https://forum.nostalrius.org/viewtopic.php?f=2&t=31252 / https://forum.nostalrius.org/viewtopic.php?f=45&t=29150
10 http://www.lurkerlounge.com/forums/printthread.php?tid=4725 / http://www0.xup.in/exec/ximg.php?fid=78682127
11 http://www0.xup.in/exec/ximg.php?fid=39931925 (BradyGames Official Strategy Guide)
12 https://web.archive.org/web/20060510041143/http://wow.allakhazam.com:80/item.html?witem=13086
13 http://wow.gamepedia.com/Relentless_Scythe
14 http://www0.xup.in/exec/ximg.php?fid=16342480 (BradyGames Official Strategy Guide)
15 http://www0.xup.in/exec/ximg.php?fid=11454456 (BradyGames Official Strategy Guide) / allakhazam

**Comment by Sabre142** [comment]
Problem is that the strategy guides are often wrong.

**Comment by some2** [comment]
> Problem is that the strategy guides are often wrong.

I've compared all values from the strategy guide with the ones from http://wow.allakhazam.com

**Comment by ifyousayso** [comment]
Beheading Blade:

RequiredLevel should be 57, not 47. (*15)

http://www0.xup.in/exec/ximg.php?fid=11454456
-----------------------------------------------------------
Wrong?! Okay, so someone changed it to req. lvl 57 without thinking this through:
- It's DPS is between other uncommon swords ±(2-3) levels.
- It's vendor price is between other uncommon swords ±(2-3) levels.
- It disenchants like other uncommon handheld items in the 46-50 range.
- It drops from lower level mobs (47)..

You can't just go in and change one property of an item and make it "right". Everything is part of a greater pattern..

**Comment by Phoosy** [comment]
https://github.com/elysium-project/server/pull/1322
>It might be a minor fix but it's not useless. All corrections help preserve the game as it was and are appreciated

**Comment by ifyousayso** [comment]
Not all corrections: #1774. This worked properly 6 months ago until someone decided to "correct" it. :(

It's okay, though.. I know this item and its icon and it's not like I'm going to waste my money on it.

**Comment by Phoosy** [comment]
Not all corrections are a stupidly simple itemization fix that requires a SQL statement change rather than core code changes.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
