### ISSUE TITLE
5p Giantstalker GUI bug

### ISSUE THREAD

**Issue by Soopra** [elysium-project/server#1103]
5 piece giantstalker - when pet is dead
![bug pet dead](https://user-images.githubusercontent.com/29525708/27264755-34cfc8fe-54c9-11e7-900c-1b208f050853.jpg)
, you get a message every 5 seconds "your pet is dead" because its trying to apply the 5p set bonus (increases pet stamina by 30 and resistance by all)

**Comment by Phoosy** [comment]
Fixed by https://github.com/elysium-project/server/pull/994
Don't believe it's been merged into live yet.
