### ISSUE TITLE
Clutch of Andros

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#1106]
Meant to have no spell hit on it until Patch 1.10.

The correct stats are: http://web.archive.org/web/20060306105628/http://wow.allakhazam.com:80/db/item.html?witem=13956

**Comment by stesve** [comment]
Currently implemented with no spell hit, but gets updated in 1.9.

**Comment by Sabre142** [comment]
Gets 1% hit in patch 1.10.

> This thing used to have +22 int before patch 1.10. I hate those stealth nerfs.

http://wayback.archive.org/web/20070314190040/http://www.thottbot.com:80/i13956

**Comment by Sabre142** [comment]
Closing as it has been fixed.
