### ISSUE TITLE
Feroticas the Dream Eater quest bugged

### ISSUE THREAD

**Issue by kaxadon** [elysium-project/server#1108]
Feroticas the Dream Eater (NE starting area) quest bugged -- the Gnarlpine Necklace item that you are instructed to right click and take out the jewel just gets greyed out when you right click it, making you unable to complete the quest.

**Comment by Spionida** [comment]
Exit WoW, delete the WDB folder, lig back in. Fixes it, but it's a continual problem.

**Comment by Spionida** [comment]
Invalid in that it does not happen, or invalid in that it's know?
