### ISSUE TITLE
Group leader jumping around

### ISSUE THREAD

**Issue by llacczy** [elysium-project/server#111]
Theres some conditions when the group leader changes:

- being offline
- getting in a dungeon
- travelling past continent on boat (and zeppelin i suppose)

The bug:
The leader, while being on the loading screen does not gain information about the fact, that the group leader changed, the ui still offers group leader activities and this leads to the visual bug, where a person sees multiple group leader sign at the party frame.

**Comment by brotalnia** [comment]
This should have been fixed in https://github.com/elysium-project/server/pull/60 Maybe it's not on the live server yet?

**Comment by llacczy** [comment]
Ah probably, thanks, i will look around more before posting next time.
