### ISSUE TITLE
a strange red key

### ISSUE THREAD

**Issue by klather19** [elysium-project/server#1114]
i just stumble on a quest in Felwood at Jaedenar in the cave near the mounten i got a key that had a quest in it call a strange red key when i tog the key and try to turn it in there was a problem the bug was bug i try to reload ui/restart the game and noting when then went on the web and fount that Nostalrius had the same problem with this quest no one can complete it so i just wanted to make this post to maybe help fix it in the future

**Comment by Ripper007** [comment]
On Darrowshire works.

**Comment by QAkvastskaft** [comment]
See: #2667
