### ISSUE TITLE
One hand weapons are currently 5% and should be 9.2% per 1.0 weapon 1 hand speed and Judgement of righteousness should be 73%  coefficient (currently 43%)

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/server#1116]
currently judgement of righteousness is at 43% coefficient which is too low.

 http://www.imtwelve.com/3069-my-maths-on-new-sor-aelic

 
Lunais Nov 14th, 2006, 12:08 pm 
  
Alright, according to this thread Seal of Righteousness now has a coefficent of 9.2% spell damage per 1.0 second of speed on a one hander. Meaning with 100 spell power and Quel'Serrar you would add about 18 damage on top of the damage coming from SoR already. 

Judgement of Righteousness now has a 73% coefficient. That's a healthy helping of spell power: a paladin in full judgement with a lot of +spell power gear will be able to judge Righteousness for as much or more damage than stunned SoC. 

Aelic Nov 14th, 2006, 2:10 pm 
  
I'll give you some numbers later tonight, I only have a 2.4 speed one-hander tho (Aelicsong Pallyblade pew pew). Weren't you trying to go for a 2.0 speed weapon Lunais? I thought this might be a decent weapon for tanking with that sort of mindset: 

 

Using Azuresong Mageblade (2.4 Speed sword) with Seal of Righteousness 

354 Spell damage 
- Hits for 136 per swing, judges for around 440 (660 crit) 

354 Spell damage + 198 Spell damage via JotC 
- Hits for 180 per swing, judges for around 580 (870 crit) 

354 Spell damage + 198 spell damage via JotC + Sanctity Aura 
- Hits for 197 damage per swing, judges for 630 (950 crit) 

Imp. Seal of Righteousness is really weaksauce. I think the seal itself doesn't really receive any benefit atm. i.e. SoR was only doing 2 more damage per swing with Imp. SoR. 

354 Spell damage + Imp. Seal of Righteousness 
- Hits for 138 per swing 

It does however affect JoR but only the base damage of JoR. So it's +15% of JoR's damage with 0 spell power and doesn't scale. Basically the talent itself is equivalent to giving yourself +38 spell damage. 
----------------------------------------------------------------------------------------------------------------

As of right now on Elysium my 2.4 speed weapon at 354 spell damage is hitting 115 spell damage 
and judging 334 judgement

Needs fix: Currently Sor is NOT 9.2% per 1.0 speed (1hand)

Currently sor is giving 5%!!! per 1.0 speed 

Fix needed: Judgement spell damage coefficient should be 73% in vanilla (currently at 50% coefficient doing 339 JoR damage @ 358 spell damage, says it should do 440)

**Comment by Itembugs** [comment]
You can see the 73% he is stating is from vanilla. It says the Imp SoR/JoR talent only increases his damage by 4. In tbc this was changed to 15% from talents (meaning 58% coefficient in tbc + 15%)

Vanilla coefficient was made to 73%

**Comment by Mostprovidedlinks** [comment]
two hand damage is accurate one hand is very very off. this guys right

**Comment by Itembugs** [comment]
50% was the coeffcient of early vanilla

**Comment by Pleasant-Elysium** [comment]
You link is referencing TBC mechanics.
