### ISSUE TITLE
Tarantulas in Redridge Mountains has too much health

### ISSUE THREAD

**Issue by Selektiv** [elysium-project/server#1117]
The tarantulas in the zone Redridge Mountains has more than twice the amount of health compared to other monsters of the same level and type.

**Comment by adura90** [comment]
Maybe they have lower armor and resists. You should try to find proof to support your theory.

**Comment by Phatcat** [comment]
No. He is right. they have way too much health. They have somewhere around 550 - 600 according to my mobinfo2 (can't be bothered to check in the db)

If you look in Brady Games Bestiary it clearly shows the Tarantula should have around xxx health.

![billede](https://user-images.githubusercontent.com/1907820/28173670-6d36643a-67ef-11e7-91c5-4216411337ad.png)
![billede](https://user-images.githubusercontent.com/1907820/28173656-623a9f88-67ef-11e7-8c97-0ff09e875024.png)

**Comment by kampeador** [comment]
Currently, they have 594 health points.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
