### ISSUE TITLE
Armor dmg calculation incorrect

### ISSUE THREAD

**Issue by ItsmeAga** [elysium-project/server#1118]
The current Armor formula has a slight mistake in, namely a change from the tbc beta.
Current Formula:
`float levelModifier = (float)getLevel();`
    `if (levelModifier > 59)`
        `levelModifier = levelModifier + (4.5f * (levelModifier - 59));`
    `float tmpvalue = 0.1f * armor / (8.5f * levelModifier + 40);`
    `tmpvalue = tmpvalue / (1.0f + tmpvalue);`

This part is incorrect and results in slightly less dmg reduction through armor: 
`if (levelModifier > 59)`
        `levelModifier = levelModifier + (4.5f * (levelModifier - 59));`

Vanilla should not have a different formula for above level 59 players, see http://wowwiki.wikia.com/wiki/Damage_reduction?oldid=323458 at the very bottom introducing the change for 59+ players in the tbc beta.

Without the 59+ part the Damagereduction fits the ingame tooltips reduction aswell, should just remove that part.

**Comment by blubba22** [comment]
Just out of curiosity, how big is the difference?

**Comment by ItsmeAga** [comment]
for bosses attacking around ~7% less migitation
