### ISSUE TITLE
Master loot gave out inappropriate loot 

### ISSUE THREAD

**Issue by lucuris** [elysium-project/server#112]
I was handing out the Arcane Infusion Gem to our Hunter Trollinah when I was forced out of looting (no character inputs by me). When I go back to do it over again Bracers of the Ten Storms mysteriously gets sent to Trollinah. The bracers even show up on the loot screen for a second before vanishing off.

Vod of Master Looter: https://www.youtube.com/watch?v=Uwx19GHvx_o&t=8m30s
Raid ID: http://imgur.com/0wOAyd2

**Comment by thepparker** [comment]
Cannot reproduce, possibly an addon causing problems
