### ISSUE TITLE
QUEST BUG : [Get the Goblins Drunk]/[Get the Gnomes Drunk] 

### ISSUE THREAD

**Issue by Morthall** [elysium-project/server#1126]
Dear Sir or Madam,

I am unable to start a quest called [Get the Goblins Drunk]/[Get the Gnomes Drunk] at Mirage Raceway in Thousand Needles. The NPC: Kravel Koalbeard does not propose me anything.
However, I accomplished [Back to Booty Bay], [Zanzil's Mixture and a Fool's Stout] and I own the quest item [Fool't Stout] in my inventory.

I talked about this problem to other players who had the same issue and they think that it is a bug. Can you help me to unblock the situation?

Yours faithfully.

**Comment by Morthall** [comment]
up

**Comment by Ripper007** [comment]
On horde it doesn't work since you can get the follow up quest that sends you to Mirage Raceway

**Comment by Morthall** [comment]
What Can I do then?

**Comment by GuybrushGit** [comment]
Fixed with https://github.com/elysium-project/server/pull/1028

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/50445-development-update-19072017/
