### ISSUE TITLE
Vengeance Talent does not work

### ISSUE THREAD

**Issue by plasmatix** [elysium-project/server#1132]
The Vengeance talent in the Druid Balance tree is not working as intended.

When my Moonfire, Starfire or Wrath spells critically strike, I only receive double damage
instead of the critical strike damage bonus of 100% with all five talent points invested.
A Moonfire that hits for 72 Arcane damage and critically strikes for 144, should give 288
damage with five points into this talent, as this is what the talent says that it does:

(72 * 2 = 144) * 100% = 144, (144 + 144) = 288 <- I am not sure if it works that way or
(72 * 2 = 144) * 100% of the 72 = (144 + 72) = 216 <- or this way, but it does not work anyway

Adding any amount of points into this talent did not change the critical strike damage multiplier,
and removing them kept the damage as-is.

**Comment by Spaztick** [comment]
Spell critical strikes are 150% damage and not 200%. A moonfire that hits for 72 will crit for 108 without talents and 144 with Vengeance.

**Comment by thepparker** [comment]
You seem to be confused about how the crit multipliers work.

If you hit for base 72 and crit, that will yield 1.5 (50% base multi for spells) times the damage, i.e. 108. If you talent into crit damage, the talent will multiply the base multiplier. 

So for example if you have a 100% increased crit damage talent, your hit of 72 will now be multiplied by 2 (1 + .5 * 2), and give you 144 damage.
