### ISSUE TITLE
cauldron and theramore deserter in possibly wrong location

### ISSUE THREAD

**Issue by llacczy** [elysium-project/server#1135]
Anathema  76.3 55.1 dustwallow marsh
in the ocean at theramore, cauldron is floating in the air and the npc swimming in the water, probably they should be at/in the nearest ship

http://imgur.com/a/LcbxT

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
