### ISSUE TITLE
Judgement of command scales at 43% in stun but is only scaling at 23% normally (should scale 43% regardless of whether its a non stun or a stun)

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1136]
https://www.youtube.com/watch?v=ay7RU0N-44Y

Judgement of Command hits in 390 spell damage gear (NO sanctity aura)  for exactly 342 or more damage on the rogue in this video, 4:95 and 384 damage on 10% berserking stance at 2:00
he appears to be hitting some wartriors for exactly 10% more damage
if you add all the healing enchants etc and gear he has that he goes through and hes even mentioned in the description it was 390 spell damage here https://www.youtube.com/watch?v=ay7RU0N-44Y

Currently on elysium I am hitting a pathetic 260-270 judgement of command with 390 spell damage and thesame weapon and same gear. (no sanctity aura)

after doing 30 judgement of commands in 0 spell damage gear I am doing 170-180 judgements. (same as tooptip)

With 204 spell damage hero charm trinket + 390 spell damage gear (594)  I am hitting 305-310 judgement of command. He is hitting far higher judgements than us on this server without using his trinket. Fix please

The coefficient needs to be higher since you can see him hitting higher than elysium. 
I am currently dissapointing with thinking we are being cheated of retail damage. The damage is also coming from late vanilla. There are many changes, for example

I am only gaining 90 damage on judgement of command right now with 390 spell damage

which is a 23% coefficient with lothamir. 
judgement of command should scale at 43%. 

http://i.imgur.com/CGLtyjo.png
This paladin is doing 244 judgement of commands at 58 spell damage in 1.12
watch his video please

Reply

Sorry Imba but I dont agree. Most of the dates are late with dernos too and As we can see this paladin in late vanilla (naxx patch) and is in exactly 163 spell damage gear, and 313 with the flask meaning he should hit
non stunned judgement of command for 305-340 (he states before crusader strike in description)

and 335-374 with sanctity

http://db.vanillagaming.org/?spell=20920

is hitting a 449 judgement of command hit 2:43 and up to 500 judgements (vengeance added)

he hits commands many times in the mid 400s

nightfall procs at one moment later and the damage is higher.

his crits are very very high and this means it doesnt scale at a measly 23% change this please

https://www.youtube.com/watch?v=VEs9coe5XRg&spfreload=10

I didnt include judgement of the crusader which is the reason he is hitting in the 449 and not 335-375 @43% coefficient, meaning judgement of the crusader increases his damage and vengeance included

The funny part is, on elysium the judgement of command is scaling for 43% coefficient when it stuns, but only 23% when not using stun

This is proven wrong in the video. It should scale at 43% regardless of whether its a non stun or a stun

a new video I found scaling at 43%. paladin has no flask of supreme or judgement bindings and paladin is at around 150-156 spell damage in this video

https://www.youtube.com/watch?v=rXNWvytYbyo&t=0m53s

Sept 2006

his judgement of command is hitting 339 with sanctity aura and jotc

**Comment by Imbaslap** [comment]
i wonder if this is one of those TBC prepatch coefficient/vanilla coefficient mix ups @GuybrushGit ran into.

**Comment by supasteed** [comment]
The video clearly shows him doing 43% JoC in vanilla 2006

**Comment by Imbaslap** [comment]
yes but the video is from patch 1.9 (as you can see silithus and AQ geared) also he most likely made the video during the paladin changes showcasing it. http://wowwiki.wikia.com/wiki/Patch_1.9.0

so the OP is suggesting the coefficient was 43% at the 1.9 patch level.. but where is the evidence at 1.12 patch level?  find a source showing it never changed near the end of the patch cycle and the devs can probably take a look into this.
@GuybrushGit might know more.

-Judgement of Command - Instead of placing a debuff on the victim, this spell now does immediate damage. If the victim is not stunned, they only take 50% of the total damage. The damage on this Judgement was increased significantly.

-Judgement of Righteousness - The damage of this judgement was increased significantly. This judgement can now trigger procs. The bonus from spell damage items has been increased slightly.

1.9 is the start, where is the end is my question..  did blizzard nerf coefficients after the entire paladin class revamp or not. (most likely yes as that is a bad habit of blizzard nerfing things after adding new things)

**Comment by supasteed** [comment]
Sorry Imba but I dont agree. Most of the dates are late with dernos too and  As we can see this paladin in late vanilla (naxx patch) and is in exactly 163 spell damage gear, and 313 with the flask meaning he should hit
non stunned judgement of command for 305+ (he states before crusader strike in description)

is hitting a 449 judgement of command hit  2:43

he hits commands in the 400-500

nightfall procs at one moment later and the damage is higher.

his crits are very very high and this means it doesnt scale at a measly 23% change this please

https://www.youtube.com/watch?v=VEs9coe5XRg&spfreload=10

**Comment by Mostprovidedlinks** [comment]
Sorry Imba but I dont agree. Most of the dates are late with dernos too and As we can see this paladin in late vanilla (naxx patch) and is in exactly 163 spell damage gear, and 313 with the flask meaning he should hit
non stunned judgement of command for 305-340 (he states before crusader strike in description)

and 335-374 with sanctity

http://db.vanillagaming.org/?spell=20920

is hitting a 449 judgement of command hit 2:43

he hits commands many times in the mid 400s

nightfall procs at one moment later and the damage is higher.

his crits are very very high and this means it doesnt scale at a measly 23% change this please

https://www.youtube.com/watch?v=VEs9coe5XRg&spfreload=10

I didnt include judgement of the crusader which is the reason he is hitting in the 400s and not 335-375 @43% coefficient, meaning judgement of the crusader increases his damage for roughly 100

or 80-90 damage if he was using fervor

**Comment by Imbaslap** [comment]
i'm not saying you're wrong, i'm saying you need an end point of evidence showing blizzard didn't stealth nerf JoC right before TBC prepatch. Blizzard has a bad habit of doing that as shown from history.

another thing that begs to question is what does the 1.12.1 Theorycraft addon have for coefficient and is it correct matching the new videos? if for example, the TC addon in 1.12 shows 23% for JOC coefficient, and was not 43% between 1.9 - 1.12..  what other things may be wrong with the addon that the devs are using for a basis of coefficients? it's more of re-checking the basis of coefficients upon new evidence being presented. 

the new video provided is the "end" point showing 43% coefficient still in even during TBC prepatch.

**Comment by Mostprovidedlinks** [comment]
the TC addon is wrong. There is no 23%

All the damages in the new videos from 1.9 or before and up to anywhere in late naxx patches are 43%

This is very well a mistake

**Comment by Imbaslap** [comment]
i don't know what TC has, but if that is where they got 23% then the source they are using is wrong and they should probably recheck other spell coefficients in that case.

**Comment by Mostprovidedlinks** [comment]
for all spells probably yes, ive seen numbers for warlocks and mages being lower than they show in late naxx videos

**Comment by Mostprovidedlinks** [comment]
If something as simple as this is wrong, i wouldnt be surprised if soulfire was doing less than its supposed to.
Conflagrate crits are right though. They are hitting for thesame amount as this warlock in the video but his soulfire hits harder than elysium.

**Comment by Mostprovidedlinks** [comment]
The funny part is, on elysium the judgement of command is scaling for 43% coefficient when it stuns, but only 23% when not using stun

**Comment by theloras** [comment]
SEAL of Command should scale at 23% of spell dmg and 29% of Holy Damage (ie: Judgement of the Crusader)

Whereas JUDGEMENT of Command should scale at 43% whether stunned or not and this was the case all the way through TBC

**Comment by Mostprovidedlinks** [comment]
https://www.youtube.com/watch?v=rXNWvytYbyo&t=0m53s

Sept 2006

339 damage also proves judgement of command should scale at 43%

**Comment by SirSkillalot** [comment]
Just take what is provided from blizzard which is 43% for instant cast spells as Command is..

**Comment by Hsekr** [comment]
The patch notes are most likely referring to seal itself as seen on the tool tip a stunned enemy gets judged by 339-373 damage while a normal 169-187 witch is 50% of the stunned one ( total possible damage ) if the 50% modifier came after all modifiers like spell power/vengeance/aura ( as it currently is ) it would definitely be mentioned on tool tip to prevent player confusion and false bug reports back in the day

**Comment by SirSkillalot** [comment]
http://paladin-guide.blogspot.ch/2005/12/judgements.html 43% coefficient stated here aswell which is after 1.9

**Comment by theloras** [comment]
I still can't believe that this was ever even under scrutiny (ie: JoC being at 23%) but at any rate, could someone find out where in the code JoC's scaling is registered and confirm whether its set at the incorrect 23% or the correct 43% - or if there is a discrepancy between the stunned and unstunned version of it?

**Comment by sopaipleto** [comment]
this should get fix asap  :(

**Comment by sopaipleto** [comment]
i did a math and realized the current damage its  low :
tested this in the ptr with  spell damage from gear 293.
-plus  a libram that add holy damage to jotc 33 + 140 from jsotc ( no talent )= 173 holy damage 
-  in total 466  spell damage on target.
- 43% of that 466  = 200,38  added  damage to judgement of Soc.
                                                                           Normal       |       Crit
- base damage of judgement of SOC=     169,5 - 204,5       |   339 - 409
- with 43%  damage added =             369,88 - 404,88         |   739.76 - 809.76
- with sanctity aura 10% =             406,868 - 445,368          |   813.736 - 890.736
- with vengeance 15%  =                467.8982 - 512.1732     |   935.7964 - 1024,3464

- in the current picture i crit for 674 with debuff of jsotc on target, sanctity aura plus vengeance
and thats below the crit range.

https://ibb.co/cY6bev

**Comment by Mostprovidedlinks** [comment]
Someone please fix this

**Comment by GuybrushGit** [comment]
JoR 50% - Confirmed.

Went through all of these videos and checked the hits on non stunned. The math checks out coefficient is 43%. Someone else did the math on stunned and its 43% as well: https://pastebin.com/aFbgDZrZ

The TC addon has stunned at 21% and non stunned at 43%, which is the opposite of what the server has. Makes no sense having non stunned hits doing more damage than stunned. TC is incorrect.

The patch note "they only take 50% of the total damage" is almost certainly wrong. Its not total damage only base damage.
