### ISSUE TITLE
Raid mobs immune to Crystal Charge

### ISSUE THREAD

**Issue by fgsfdss** [elysium-project/server#1137]
When using Crystal Charge after a shatter phase for AoE on Viscidus blobs, only a few of them report "immune", and it has no effect at all on any others which it was supposed to hit.
I believe Flame Imps and Core Hounds in MC are also immune to Crystal Charge, even though they are not immune to Hellfire, Rain of Fire or Sapper Charge.

At least three people in my guild have used it for the past six weeks, and not once has it shown up on scrolling combat text, in the combat log or on Legacy Logs aside from the odd "immune".

Unfortunately I have no idea what would be the cause of this as it works just fine on most other mobs (e.g. Yauj and Fankriss adds).

**Comment by theloras** [comment]
+1 as I also reported this on the Dev Discord as well

**Comment by fgsfdss** [comment]
Tried today on a pre-Huhuran wasp pack and all mobs were immune there as well.

**Comment by fgsfdss** [comment]
Garr adds also immune.

**Comment by fgsfdss** [comment]
Any update on this?

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
