### ISSUE TITLE
currently judgement of righteousness is at 43% coefficient which is too low. judgement of command is also too low. seal of righteousness is too low

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/server#1138]
currently judgement of righteousness is at 43% coefficient which is too low.

It is meant to scale at 73%
http://www.imtwelve.com/3069-my-maths-on-new-sor-aelic
(hits more than a stunned judgement of command!)

currently judgement of command is scaling at 23%
it is meant to scale at 43%

seal of righteousness is scaling at 5% currently 
It should scale at 9.2% per 1.0 speed (one hand) 10.8% per 1.0 speed 2 hand

https://github.com/elysium-project/server/issues/1116

This is still not fixed

**Comment by Itembugs** [comment]
It should be changed to 73%

**Comment by stesve** [comment]
Seems like they are referencing numbers from tbc beta.

"Alright, according to this thread (http://**beta.**worldofwarcraft.com/thread.html?topicId=690079&sid=1&pageNo=1)"

**Comment by Pleasant-Elysium** [comment]
Stesve is correct. This is referring to TBC coefficients. 

This is included in the patch 2.0.1 notes:

"HoTs, DoTs, and channeled spells have been re-balanced to receive a more appropriate (higher) percentage of +spell damage and +healing."

Invalid report
