### ISSUE TITLE
Nightfall spell vulnerability proc not proccing on every swing of reckoning bomb- 15% damage only affects 3 out of 5 hits 

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1142]
nightfalls proc when it procs is not proccing on all my swings which i hit at thesame time

http://i.imgur.com/jPpulwF.png

change to make it proc on 5 hits fix please

If they are swung at zero swing time then it should all be affecting each seal regardless of the seal order

**Comment by stesve** [comment]
If i understand you correctly. If one of the 5 attacks proc nightfall then you want all 5 attacks to be affected by it?

Isn't very unlikely that this very specific mechanic existed in vanilla?

**Comment by Mostprovidedlinks** [comment]
they are all swung at the same time, it would make no sense for them all 5 to be affected. Sometimes one our of the five swings are affected. I find that silly

**Comment by stesve** [comment]
> it would make no sense for them all not to be affected since they are technically swung at the same time

They are swung one-by-one with zero swingtime.

**Comment by Mostprovidedlinks** [comment]
If they are swung at zero swingtime then it should all be affecting each seal

**Comment by stesve** [comment]
> If they are swung at zero swingtime then it should all be affecting every seal regardless of what order they are in

Zero swingtime doesn't mean that the swings are simultaneously or happen at the same time, but only that there are nearly zero delay between them.

**Comment by supasteed** [comment]
No it doesnt. Zero swing time means theres no delay between the hits

**Comment by stesve** [comment]
It's executed sequentially:

Swing -> 3 sec swingtime delay -> swing -> 3 sec swingtime delay -> swing
Swing -> 0 sec swingtime delay -> swing -> 0 sec swingtime delay -> swing

If you somehow insist that there should be a separate mechanic for this, that somehow deviate for the default behavior for multiple attacks, you should try to find some evidence for that mechanic existed.

**Comment by Mostprovidedlinks** [comment]
It doesnt matter the order they are in. They are hitting at thesame time in 0.01 motion in mpc

Technically they hit at thesame time so technically the buff should affect all 5 swings.

**Comment by stesve** [comment]
> Technically they hit at thesame time so technically the buff should affect all 5 swings.

Technically they don't. 

You should try to find some evidence for that mechanic really existed in late vanilla retail.

**Comment by thepparker** [comment]
They don't all hit at the same time, it is literally 5 sequential and separate weapon swings. If only the last hit procs Nightfall, only the last hit will be affected by it.

**Comment by supasteed** [comment]
That's not what im seeing on my screen

**Comment by thepparker** [comment]
Yes it is, hence you see some of the attacks are unaffected by Nightfall
