### ISSUE TITLE
"Bring the Light" quest with 2 rewards deletes 2nd reward if only one spot in inventory

### ISSUE THREAD

**Issue by zhunter3** [elysium-project/server#1143]
I just finished the quest "Bring the Light", which rewards both the "Vanquisher's Sword" 1h sword and "Amberglow Talisman" necklace.

I had only one inventory space when turning it in (and an ammo pouch with empty slots). It only gave me the sword, not the talisman. The talisman was seemingly deleted. 

The yellow quest text in the chatbox shows me receiving both items, but the green text that shows the actual item going into my bag (?) only mentions the sword. See attached screen cap. (Note, in the screen cap there is an extra empty bag slot. This is because I tried removing another item after the fact to see if the talisman would suddenly appear.) 

![bringthelightbug_elysium](https://user-images.githubusercontent.com/17136212/27505336-17f9d896-5852-11e7-8e79-3c64534f3875.png)

**Comment by supasteed** [comment]
Bring in the light is also meant to give a +32 stamina word of fortitude buff from benedictus everytine you accept this quest on retail.

**Comment by supasteed** [comment]
http://db.vanillagaming.org/?spell=2791

**Comment by connormcgregor** [comment]
@thepparker By remedi (1,659 – 1·3·10) on 2007/08/19(Patch 2.1.3)

As you accept the quest, the archbishop will make you a fortitude buff.


It says you get the buff when you accept the quest.
