### ISSUE TITLE
Bring the Light quest should give 32 stamina buff

### ISSUE THREAD

**Issue by supasteed** [elysium-project/server#1144]
Bring in the light is also meant to give a +32 stamina word of fortitude buff from benedictus everytime you accept this quest on retail.

http://db.vanillagaming.org/?spell=2791

http://db.vanillagaming.org/?quest=3636#wh-comments says it in 2.1.3 but it was also prior

**Comment by stesve** [comment]
https://youtu.be/mHJe2HpX3g4?t=5m59s

**Comment by supasteed** [comment]
Thanks guess this was only in TBC
