### ISSUE TITLE
Frost Damage equips/Spell damage enchant does not stack to Blizzard

### ISSUE THREAD

**Issue by Sapplejacks** [elysium-project/server#1145]
Hi, I've noticed that my +30 Spell damage and Frost damage equips only work with frostbolt and don't work with blizzard. My frostbolt is supposed to be 74-82 but it does about 100-120 now. But with blizzard it only does 26 damage to all mobs, I've taken off the gear and no difference, still the same 26. I was told it's probably broken, so I made a post. Thanks! My mages name Is Pantry.

**Comment by Pleasant-Elysium** [comment]
Will need QA to test higher ranks but this could be a matter of using a lower level spell and the co-efficient not being high enough to see any meaningful increase to your spell damage .

**Comment by Sapplejacks** [comment]
I'm level 43 now and I do 76 with rank 4 blizzard and lots of spell/frost damage equips, though I doesn't affect but maybe 1-2 damage

**Comment by thepparker** [comment]
Blizzard scales appropriately
