### ISSUE TITLE
Talisman of Binding Shard should be lootable

### ISSUE THREAD

**Issue by supasteed** [elysium-project/server#1146]
It isn't fair how the people on retail got to keep it and a few people on old nostalrius still have it yet it is unobtainable now. I think the 3% drop item should be lootable. Its only fair since it doesn't hurt anything if its lootable. It hurts if we cant loot it since others get to keep it and we don't.
http://db.vanillagaming.org/?item=17782

I think its stupid that others get to keep this item and we don't. I think it doesn't hurt to make it lootable.

Its a stupid tease to allow this item lootable in previous patches and not now.

**Comment by Nelythia** [comment]
You are wrong.

It dropped once on Nostalrius, to offer the same as on retail.
One player that gets and keeps it.

No one else.

One drop on Nostalrius PvP, since then removed from the loottable.

**Comment by supasteed** [comment]
Yeah and has it occurred to you thats total bs. One person keeping the item is totally unfair.

**Comment by StadenElysium** [comment]
This is already working as intended.
