### ISSUE TITLE
Annihilator proc rate

### ISSUE THREAD

**Issue by Beastboi** [elysium-project/server#1147]
BUGGED BEHAVIOR:
Proc chance is MUCH lower than intended(Its 1ppm right now!!!). Making item completely useless. (mats cost for it ~500g...)

 CORRECT BEHAVIOR:
Discussable. ~27% proc rate. According to old EJ topic. But I believe it should be rough 15%, same as other crafted tank weapons from this "line" Masterwork Stormhammer and Frostguard(btw theyr proc rates are bugged too)

 SOURCES:
http://forums.elitistjerks.com/forums/topic/7811-thunderfury-vs-the-annihilator-for-tanks https://web.archive.org/web/20061231034159/http://www.thottbot.com/?i=24718 - check comments "The proc on this is pretty regular, only time I've seen it max is on elites (mostly because normal mobs don't last long enough)." and other indirect proofs that proc rate should be much higher than its now(now its like 90% of times you cant get hugher than 1/3 stacks(45sec stack duration mean that at least during 45 sec only 1 proc). The only one guy tested it in http://forums.elitistjerks.com/forums/topic/7811-thunderfury-vs-the-annihilator-for-tanks and reports 27-29% proc chance for more than 1000 attacks in few test atempts.

Again: now its cant stack up to 3x times (never seen that while using it). Peoples reports that it was "stacks very fast" back to 2006. And ofc logic - its very expensive item.

**Comment by GuybrushGit** [comment]
Copy pasting an old forum post on weapon proc rates since its not available any more, no clue how accurate it is:

> Weapon Chance on Hit procs:
> Blackblade of Sharam = 8%; ppm = 1,3714 (1,4)
> Felstriker = 4%; ppm = 1,4117 (1,4)
> Blackhand Doomsaw = 6%; ppm = 1,0285 (1)
> The Nicker = 6%; ppm = 0,9
> Venomspitter = 8%; ppm = 2,5263 (2,5)
> Fang of the Crystal Spider = 8%; ppm = 3
> Keris of Zul'Serak = 8%; ppm = 2,6666 (2,7)
> Demonfork = 10%; ppm = 2,1428 (2,1)
> Ironfoe = 10%; ppm = 2,5
> Wraith Scythe = 4%; ppm = 1,0909 (1,1)
> Flame Wrath = 10%; ppm = 1,8181 (1,8)
> Lord General's Sword = 8%; ppm = 1,8461 (1,8)
> Force of Magma = 6%; ppm = 1,125 (1,1)
> Seeping Willow = 6%; ppm = 1
> Quel'Serrar = 12%; ppm = 3,6 (author: only %)
> Gutgore Ripper = 4%; ppm = 1,3333 (1,3)
> Shadowstrike/Thunderstrike = 8%; ppm = 1,5483 (1,55)
> Bonereaver's Edge = 15%; ppm = 2,6470 (2,6) (author: only proc because can perma up)
> Perdition's Blade = 4%; ppm = 1,3333 (1,3)
> Sulfuras, Hand of Ragnaros = 10%; ppm = 1,6216 (1,6)
> Thunderfury = 18%; ppm = 5,6842 (5,7) (author: only proc chance(till end bc best tank weapon in threat))
> Frightalon = 8%; ppm = 3,4285 (3,4)
> Gravestone War Axe = 6%; ppm = 1,0588 (1,1)
> Barovian Family Sword = 10%; ppm = 2,8571 (2,9)
> Frightskull Shaft = 8%; ppm = 1,4117 (1,4)
> Ebon Hilt of Marduk = 8%; ppm = 1,7777 (1,8)
> Bonechill Hammer = 8%; ppm = 2
> Silent Fang = 10%; ppm = 3,75 (3,8)
> Soul Breaker = 10%; ppm = 3,75 (3,8)
> The Cruel Hand of Timmy = 10%; ppm = 3,3333 (3,3)
> Demonshear = 6%; ppm = 0,9473 (0,9)
> Gargoyle Shredder Talons = 8%; ppm = 2,6666 (2,7)
> Hammer of the Titans = 10%; ppm = 1,5789 (1,6) (author: lower there was another Hammer of the Titans with 8% chance)
> Skullforge Reaver = 8%; ppm = 1,92 (1,9)
> Vis'kag the Bloodletter = 6%; ppm = 1,3846 (1,4)
> Deathbringer = 8%; ppm = 1,6551 (1,7)
> Eskhandar's Right Claw = 8%; ppm = 3,2
> Eshkandar's Left Claw = 8%; ppm = 3,2
> Empyrean Demolisher = 8%; ppm = 1,7142 (1,7)
> Black Amnesty = 6%; ppm = 2,25 (2,3)
> Nightfall = 20%; ppm = 3,4285 (3,4) (author: only proc chance(weapon got nerfed in bc))
> Ebon Hand = 8%; ppm = 2,0869 (2,1)
> Sulfuron Hammer = 6%; ppm = 0,9729 (1)
> Arcanite Champion = 10%; ppm = 2
> Jeklik's Crusher = 6%; ppm = 1
> Halberd of Smiting = 4%; ppm = 0,6857 (0,7)
> Arlokk's Grasp = 8%; ppm = 3,2
> Ancient Hakkari Manslayer = 6%; ppm = 1,8
> Sceptre of Smiting = 6%; ppm = 1,3846 (1,4)
> The Untamed Blade = 10%; ppm = 1,7647 (1,8)
> Drake Talon Cleaver = 6%; ppm = 1,0588 (1,1)
> Kalimdor's Revenge = 8%; ppm = 1,5
> Dark Edge of Insanity = 10%; ppm = 1,7142 (1,7)
> Neretzek, the Blood Drinker = 6%; ppm = 0,9729 (1)
> Corrupted Ashbringer = 8%; ppm = 1,3333 (1,3)
> Misplaced Servo Arm = 6%; ppm = 1,2857 (1,3)
> Teebu's Blazing Longsword = 6%; ppm = 1,2413 (1,2)
> Frostguard = 15%; ppm = 3,9130 (3,9)
> Blazing Rapier = 6%; ppm = 2,1176 (2,1)
> Phantom Blade = 10%; ppm = 2,3076 (2,3)
> Masterwork Stormhammer = 10%; ppm = 3
> Serenity = 15%; ppm = 4,5
> The Shatterer = 12%; ppm = 3
> Annihilator = 15%; ppm = 5,2941 (5,3)
> Blight = 5%; ppm = 1,1111 (1,1)
> Truesilver Champion = 6%; ppm = 1,2
> Frost Tiger Blade = 10%; ppm = 1,7647 (1,8)
> Dark Iron Pulverizer = 6%; ppm = 0,9729 (1)
> Dragon's Call = 10%; ppm = 1

> Source: forum thottbot wow-wikki for the information of the %
