### ISSUE TITLE
Crystal Yield

### ISSUE THREAD

**Issue by Beastboi** [elysium-project/server#1148]
Is there any reason to why "Crystal Yield" dosent stack with "Sunder Armor"?

http://www.wowhead.com/item=11565/crystal-yield#comments

"Cannot be used on mobs with a level 70 sunder/devastate on them "a more powerful spell is active"  <-- Thats TBC

**Comment by GuybrushGit** [comment]
Its not supposed to stack: 
http://web.archive.org/web/20070511215508/http://thottbot.com:80/i11565
