### ISSUE TITLE
[Sulfuras, Hand of Ragnaros] - Proc chance too low.

### ISSUE THREAD

**Issue by storfan** [elysium-project/server#115]
BUGGED/INCORRECT BEHAVIOR:
Through extensive testing I have determined that the current proc chance on Elysium (Anathema) is 4.87% (Probably set to 5% by Devs). However, it is actually 6% on retail live server.

---------------------------------------------------------------------
Anathema testing method:
Recorded with the addon "DPSmate".
- 3179 hits only with sulfuras and only with abilities that are able to trigger the weapons proc.
- 155 procs
Proc chance: 155/3179 = 0,0487574709027996 = 4.87%
Screenshot: http://imgur.com/a/BSqG9
---------------------------------------------------------------------

Retail-live Testing method:
Recorded with the addon "Recount".
- 10k hits on a Target dummy in Ironforge.
- 619 procs
Proc chance: 619/10001 = 6.19%
Screenshot: http://imgur.com/a/p8iL2
---------------------------------------------------------------------

CONSLUSION: Devs have assigned Sulfuras a 5% proc-rate because of lack of in-depht testing. 5% is a "nice and even" number and could very well have been the actual rate. However, after 10k hits it has now  been proven beyond a resonable doubt that the proc-rate is infact 6%. A 1% deviation is simply too large when it comes to a pool of 10k hits to chalk down to RNG.

**Comment by AndersSahlin** [comment]
This is assuming retail stats haven't changed since 1.12, but I guess it might be difficult to find any information about procc rates from way back.

**Comment by storfan** [comment]
Yeah, I've sifted through comment sections on Allakhazam and throttbot with WayBackMachine (internet archive) and I've seen proc-rates mentioned all between 10-30% but with no data to back that up. I have not been able to find any info on ElitistJerks though since those forums wasnt available to the archiving softwares. I dont think the proc-rate would've changed though since they'd have no reason to. Other item's such as Ironfoe or Thunderfury was nerfed with TBC due to the fact that their procs scaled with level and gear but since Sulfuras only ever was a flat damage proc I see no reason for it to have been changed.

**Comment by GuybrushGit** [comment]
Sulfuras currently has 1 PPM = 3.7 / 60 = 6.166% chance to proc.

**Comment by storfan** [comment]
The discrepancy is too big to be random, but I guess that leaves bad methodology on my part, or perhaps DPSmate is doing something wrong.

**Comment by fidbugs** [comment]
I can confirm that almost two months ago on 4000 hits i got significantly lower proc rate of Sulfuras(5.1%) than Maelstrom(6.5%), which both should be around 1PPM.

https://gyazo.com/e9216b135ccef74737d8a2da6f87e98c

But in past few days, maybe week, testing something else, wielded almost identical proc rates(on much lower sample, where expected deviation could be higher).

https://gyazo.com/d6bd96e244b832d849e5c7b0ad19afe8

https://gyazo.com/d684c9c3bdf050088da91833c37016df

@GuybrushGit Do you know was it recently patched and fixed?

**Comment by GuybrushGit** [comment]
Not aware of any change to those items.

**Comment by vindruvor** [comment]
With only 3179 hits tested the result can vary a few percent.
Statistical proportion calculator: http://vassarstats.net/prop1.html 

It pretty much says that with your amount of hits the proportion can vary around +/- 0.7%.

4.87% + 0.7% = 5.68% (which is almost 6.166%, which GuybrushGit said was the procc chance).

All in all it's hard to determine 100% exact procc chance numbers without testing with many many hits.
