### ISSUE TITLE
Two-Handed Weapon Specialization applies to damage even as dual-wield (visually at least)

### ISSUE THREAD

**Issue by vindruvor** [elysium-project/server#1150]
https://cdn.discordapp.com/attachments/266588048853172225/328298254003339277/unknown.png

https://cdn.discordapp.com/attachments/266588048853172225/328298319992586252/unknown.png

As you can see on the two screenshots; 5/5 Two-Handed Weapon Specialization gives 5% increased damage with 2handers, however even though you use 1handers it shows that you have 105% damage. 

Not sure if this is just a visual bug or if it actually gives damage to 1handers as well.

**Comment by vindruvor** [comment]
anyone? :<

**Comment by GuybrushGit** [comment]
Its a visual bug, the damage doesnt change.
