### ISSUE TITLE
Item lost after server shutdown

### ISSUE THREAD

**Issue by ajn1129** [elysium-project/server#1152]
Hi, my character's name on Elysium is Decker. I had won the roll on the Clutch of Andros in Scholomance roughly 5 minutes or so before the server shutdown today. When I logged back in, I did not have the item and seemed to have lost the last 10 minutes or so of my playtime. Is there any way that this can be resolved? Thanks.

**Comment by Sabre142** [comment]
Probably not without video unfortunately. Oddly magical belt is better though.

**Comment by StadenElysium** [comment]
This is an issue for the gamemasters to deal with, although it's unlikely that they'll restore your item.
