### ISSUE TITLE
casting a spell should cause you to stand when sitting

### ISSUE THREAD

**Issue by supasteed** [elysium-project/server#1153]
casting any spell should isnt making me stand when sitting

this bug is still happening.

every other vanilla server has this fixed

**Comment by brotalnia** [comment]
I think that's how it is supposed to work in vanilla. You have to stand manually.

**Comment by stesve** [comment]
https://wow.curseforge.com/projects/project-812

> - If sitting down, it will say "You can't do that while sitting". Just ignore it. Until I can find a clean way to detect sitting, this will have to stay.

http://wowwiki.wikia.com/wiki/Sit

> A character cannot engage in combat or use many items or skills directly from a sitting position, they must first stand

> As of Patch 2.3, if you are seated and try to use abilities that require you to be standing, you will stand up and use them. This can be disabled with: /console autoStand 0

**Comment by StadenElysium** [comment]
Working as intended.
