### ISSUE TITLE
Gorosh The dervish, the arena boss is not dropping any loot.

### ISSUE THREAD

**Issue by Deathmisa** [elysium-project/server#1154]
Did so many brd runs, everytime gorosh is up he drops just some silver and runecloth.  NPCID:9027
http://db.vanillagaming.org/?npc=9027#drop
1st screen) http://prntscr.com/fnz8zk
Also after his death he drops silver 3times in a row.

**Comment by some2** [comment]
https://web.archive.org/web/20060525211701/http://wow.allakhazam.com:80/db/mob.html?wmob=9027

> Savage Gladiator Chain
> Bloodclot Band
> Leggings of Frenzied Magic
> Flarethorn
> Savage Gladiator Helm

**Comment by brotalnia** [comment]
He is dropping loot, you are just unlucky. I just killed him 20 times on the dev branch, and he dropped Leggings of Frenzied Magic and Bloodclot Band once, and Rune Cloth a bunch of times.

Here is his loot table straight form the database:
Item: 11446, Chance: 25%, MaxCount: 1, Condition: QUEST_REWARDED 4242
Item: 14047, Chance: 23%, MaxCount: 4, Condition: NONE
Item: 18945, Chance: 4%, MaxCount: 6, Condition: NONE
Item: 22528, Chance: 9%, MaxCount: 4, Condition: ACTIVE_GAME_EVENT 155

And a 15% chance to drop something from a referenced loot template. Here is the referenced loot:
Item: 11726, Chance: 15%, MaxCount: 1, Condition: NONE
Item: 22257, Chance: 30%, MaxCount: 1, Condition: NONE
Item: 22266, Chance: 25%, MaxCount: 1, Condition: NONE
Item: 22271, Chance: 30%, MaxCount: 1, Condition: NONE

**Comment by Deathmisa** [comment]
I guess I can say you are right BUT the npc drops some silver. After u loot it, it drops some silver again. Then after you loot the second silver , some NEW silver appears again. THEN ! It instantly despawns(Unlike other bosses) I think the npc is behaving like crap. Also its a shame since he drops one of the best items for a warrior.

**Comment by theloras** [comment]
still not dropping any loot as of last night

**Comment by GuybrushGit** [comment]
The chance to drop from the referenced table is at 15% instead of 100%, making his chance to drop gear way too low (3% legs, 2% chest, etc).

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
