### ISSUE TITLE
Lucifron applies curses too frequently

### ISSUE THREAD

**Issue by curacaoblue** [elysium-project/server#1156]
Lucifron applies his curse every 3.4 seconds to our raid, according to an addon.
Usual timer should be around 15 seconds.
Encounter is extremely difficult without high numbers of mages or Restorative potions right now.
This was confirmed by other raid groups. Happens on Elysium.
It's suspected the Frequency of his curse scales with number of people alive in raid for some reason.

**Comment by thepparker** [comment]
Cannot confirm on dev, applies every 15s for me as it should. I'll keep an eye out next MC on Elysium

**Comment by Pleasant-Elysium** [comment]
There have been some previous reports that the curse timer application timer can happen more frequently if the raid group wipes on Lucifron previously. Was this the case?

**Comment by curacaoblue** [comment]
Yes, that's true. The group wiped. And the first try the timer was at about 15s. Second try it was 8.6s and for the 3rd try it was the 3.4 s as written originally.

**Comment by stesve** [comment]
Should m_Events be cleared in Lucifrons reset() before scheduling new events?

I'm not sure how the events work, but from my point of view it looks like 3 new events are applied each reset.
