### ISSUE TITLE
[Quest] A little slime goes a long way

### ISSUE THREAD

**Issue by Aurigon** [elysium-project/server#1160]
Both this quest and its follow-up with the same name were added with patch 1.11.1
So they shouldn't be available with the current patch (1.3, soon 1.5).

Source: http://www.wowhead.com/quest=4513/a-little-slime-goes-a-long-way

**Comment by brotalnia** [comment]
If you are basing this solely on the fact that it says "Added in patch 1.11.1.10772" on the wowhead page, you should know that it says that for every vanilla quest, as that is when they began collecting data.

Allakhazam has the quest listed as early as 18 February 2005 -> https://web.archive.org/web/20050219141111/http://wow.allakhazam.com:80/db/quest.html?wquest=4513

That would be patch 1.2.
