### ISSUE TITLE
Juju flurry - only affects MH and lowers damage due to AP/weaponspeed

### ISSUE THREAD

**Issue by stesve** [elysium-project/server#1163]
Found this on old bugtracker and its still bugged as far as i can tell.

https://elysium-project.org/bugtracker/issue/4441

 - OH gain no attack speed.
 - MH weapon damage is lowered due to ap/speed ratio.

**Comment by vindruvor** [comment]
You mean lowers damage for instant attacks?

**Comment by stesve** [comment]
Here is comparison i did today. Left is unbuffed and right is with the juju.

http://imgur.com/gallery/zaBhi

**Comment by Mostprovidedlinks** [comment]
fix please

**Comment by thepparker** [comment]
The speed not affecting offhand/ranged is bugged, however the damage compensation may be intended as per http://wowwiki.wikia.com/wiki/Juju_Flurry?direction=next&oldid=311100. However, this may also be an unintended bug from the patch 1.12 haste changes.

**Comment by Sylvestersnr** [comment]
I can confirm this also, it does only lower the attack speed of the MH and lowers the attack damage of the MH also, even though it does not state this in the item description.

http://i.imgur.com/Vj7NeEr.png

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/52678-development-update-23082017/
