### ISSUE TITLE
Pet movement speed when riding

### ISSUE THREAD

**Issue by ettern** [elysium-project/server#1169]
If my pet (Voidwalker) gets into combat while I am riding, the speed of my pet is drastically reduced. My pet is not dazed nor got any speed debuffs.

Test scenario:
1. Use epic mount (Dreadsteed)
2. Ride around and find some hostile mobs.
3. Make sure the pet, not you, gets into combat, while you are riding.
4. Continue riding, and you will notice the reduced speed of your pet.
5. Your pet will follow at normal speed once its out of combat.

Ps: I am not sure if this is intended or not, but it seems weird.

**Comment by sknnbones** [comment]
With Hunter pets, they automatically swap to passive, and the pet bar becomes disabled.

Is this not the case for Warlock pets? Ny pet never starts combat while I am mounted, simply stays passive while following me.
