### ISSUE TITLE
Elemental invasion event not occurring [Darrowshire]

### ISSUE THREAD

**Issue by neutrals** [elysium-project/server#1170]
**Bugged Behavior**

The elemental invasion event has not occurred on Darrowshire for over two months now. The event is supposed to 'respawn' after 2-3 days after it ends but no signs of it since at least the middle of April

**Correct Behavior**

The elemental invasion event re-occurs every **few days** at Un'goro, Silithus, Winterspring and Azshara.

**Sources**

http://wowwiki.wikia.com/wiki/Elemental_Invasions

https://web.archive.org/web/20050425002614/http://www.worldofwarcraft.com/patchnotes/patch-05-04-19.html original patch notes

"Elemental invasions are "Invasions by elementals at different locations on Kalimdor have reportedly been occurring sporadically every few days."

**Comment by Vivenmort** [comment]
Can confirm. Got a level 20 Warlock camped out in Azshara for Azuregos and I haven't seen a single Earth invasion.

**Comment by Teadrinker1234** [comment]
The Earth invasion is far away from azuregos spawn. how are u getting there on a lvl 20?

**Comment by neutrals** [comment]
bump
