### ISSUE TITLE
Dark runes / demonic runes / potions / Goblin sapper charge should also scale with players Melee critical strike

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1177]
I agree with everything else GuybrushGit has mentioned about other items scaling but,
this is not one of them I agree about. (Only other being maelstrom)

Dark runes, demonic runes, potions and goblin sapper charge should scale with player critical strike
It was proven by omniusaspirer that they scaled with melee critical strike

---------------------------------------------------------------
"Also, the 10% crit rate for potions has absolutely zero evidence supporting it that I can find anywhere, which leads me to assume the percent was just a hack they applied since they knew that potions should crit but couldn't find solid data.

In my own research, I came across a bug report on the Corecraft tracker which contained some discussion on this. They seemed to have concluded based on the spell mask that potion crit rate scaled off of melee crit.

ccshiro/cc-buglist#2581

written by omniusaspire
-------------------------------

Not a fixed 10% which https://github.com/elysium-project/server/pull/992 is suggesting all of these consumables should scale under

So far runes have been proven to scale from unlimited spell damage and not fixed.
http://www.lurkerlounge.com/forums/printthread.php?tid=4252

Second based on omniusaspirers research they infact scale off physical crit

The healing spell of the potions got SpellSchoolMask = 1 (MASK_PHYSICAL) so they are affected by physical crit

The post by GuybrushGit says that they procced 10% of the time that is like saying, he is suggesting this: My weapon procced half of the time in the raid so therefore it has a 50% proc chance.

"I did a check of out Hyjal/BT mop up for the night and out of 85 health stones 9 crit. a little under 10%. I seem to remember seeing/reading something that all consumables were at that 10% rate on the average.  Means according to the players crit, he could of had any amount of crit and could of gotten any amount of estimate. He estimated based on his players crit that it procced 10% of the time."
Not the same as a 10% fixed proc. 

1. That player could of had ANY amount of crit which could of affected the 85 potions
2. That player didn't say it was a fixed 10% crit, he said out of them it procced 10% of the time.
3. If that same player had 100% crit strike he would have 85 of them critting. And we can assume
GuybrushGit is incorrect at suggesting they are fixed.

It is also proven the runes scale with player spell damage
http://www.lurkerlounge.com/forums/printthread.php?tid=4252

**Comment by GuybrushGit** [comment]
To summarize, this is what we have:
- Evidence that potions in WoD scale with crit (melee and spell are merged)
- 1 comment from Wotlk claims it scales with spell crit
- 1 comment from TBC claims it scales at 10% fixed
- Wowwiki article claims a fixed rate

There isn't enough evidence to conclude anything, but IMO keeping the fixed rate would be the best from a game design perspective. That way both casters and melee have the same chance to crit, eliminating any unbalance issues in pvp.
