### ISSUE TITLE
Item Correction Needed - Vis'kag The Bloodletter

### ISSUE THREAD

**Issue by Stunlocked** [elysium-project/server#1181]
Suppose to be updated with AV patch 1.5! 
http://db.vanillagaming.org/?item=17075 
They even had it nerfed when it was buffed to early in Nostalrius server
https://forum.nostalrius.org/viewtopic.php?f=6&t=15110
 
Incase you didnt read post and the evidence in forums i took time to screenshot and mark where on the webpage and the urls. so you can check yourself 
http://imgur.com/a/RbGxb
-------------------------------------------------------------------------------------------------------------------
Elysium current Vis'kag The Bloodletter stats.
http://imgur.com/a/VVSnl

**Comment by MagicGanja** [comment]
Fix pls :)

**Comment by Stunlocked** [comment]
Still not fixed its half fixed!
http://imgur.com/a/RaWOw

51 dps lvl 58 should be level 60

**Comment by thepparker** [comment]
Fixed
