### ISSUE TITLE
Items not updated.

### ISSUE THREAD

**Issue by Totchaa** [elysium-project/server#1183]
As far as I can see only T1 and T2 gear is updated (have deleted WDB).
List of items I can see right now that is not updated (there is really too many items to list all):
http://db.vanillagaming.org/?item=18407
http://db.vanillagaming.org/?item=13170
http://db.vanillagaming.org/?item=13001
http://db.vanillagaming.org/?item=12543
http://db.vanillagaming.org/?item=12930

Like I said, haven't been able to see any updated items that is not T1 or T2.

**Comment by gilgA1337** [comment]
http://db.vanillagaming.org/?item=13967 isn't updated either

**Comment by Totchaa** [comment]
Fixed.
