### ISSUE TITLE
"The Legend of Korrak"-Quest is not available.

### ISSUE THREAD

**Issue by jessemon** [elysium-project/server#1184]
"The Legend of Korrak" from Warmaster Laggrond is not currently in game.

http://db.vanillagaming.org/?quest=7181

Was available before the crash happened.
(@ Horde)

**Comment by DoctorMoses777** [comment]
It is my belief these items need to be added as they were there on patch release. Please see below.

Per Allakahazam : Added: Jun 7th, 2005
https://web.archive.org/web/20060325021820/http://wow.allakhazam.com/db/quest.html?wquest=7181

Per WoW Wiki:
Patch/Release Date/Version/Interface.toc
Patch 1.5.0 / 7 June 2005 / 4442 / 1500
http://wowwiki.wikia.com/wiki/Patches/1.x

**Comment by thepparker** [comment]
Fixed
