### ISSUE TITLE
Jom Gabbar triggers 2min CD on Earthstrike

### ISSUE THREAD

**Issue by stivil** [elysium-project/server#1185]
Jom Gabbar triggers a 2min CD on Earthstrike instead of just 30secs how it should be with all on use trinkets.

**Comment by stivil** [comment]
should be fairly easy to fix.

**Comment by smkrus** [comment]
It sure does

**Comment by strudelkuchen** [comment]
Still broken, also puts a 2 minute cooldown on ZHC and Renataki's Charm of Trickery.

**Comment by GuybrushGit** [comment]
"Many trinkets will now trigger a cooldown equal to the duration of their effects that will prevent simultaneous use of more than one of these trinkets." 
http://wowwiki.wikia.com/wiki/Patch_1.10

"Fixed a bug with the Jom Gabbar trinket which was causing it to trigger a category cooldown for a duration longer than intended."
http://wowwiki.wikia.com/wiki/Patch_1.12
