### ISSUE TITLE
Felheart incorrect stats

### ISSUE THREAD

**Issue by schmelzgesic** [elysium-project/server#1186]
The stats are incorrect for the set at 1.5. The set was updated twice, once in 1.4 and 1.9.3.
Here are the correct stats for 1.5:
http://web.archive.org/web/20060207011850/http://wow.allakhazam.com:80/db/itemset.html?setid=203

The following is the newest stat, identical to the one on dbvanillagaming.
http://web.archive.org/web/20060410033855/http://wow.allakhazam.com:80/db/itemset.html?setid=203

to be exact, the second round of buffs was in 1.9.3, stealth buffed together with Arcanist set.

Source: http://www.lurkerlounge.com/forums/thread-4878-post-101302.html
Do a bit of googling on the exact patch number will also net the same result. This will also apply to Arcanist set.

**Comment by thepparker** [comment]
Fixed
