### ISSUE TITLE
Many blue/epic tank items not with the correct stats! List is here!

### ISSUE THREAD

**Issue by mehailz** [elysium-project/server#1189]
http://db.vanillagaming.org/?item=15413a (still 15 defense)
http://db.vanillagaming.org/?item=12550 (still 6 defense)
http://db.vanillagaming.org/?item=11927 (still 22 defense)
http://db.vanillagaming.org/?item=12115 (still 12 defense)
http://db.vanillagaming.org/?item=18383 (still 10 defense)
http://db.vanillagaming.org/?item=12602 (still 15 defense)
http://db.vanillagaming.org/?item=11746 (still 11 defense)
http://db.vanillagaming.org/?item=13955 (still 10 defense)
http://db.vanillagaming.org/?item=17066 (still has old stats with 3 arcane damage & 2291 armor)

All of theese, blue pre-raid bis items, haven't been nerfed. They still display the old values, as shown after the link.

Can you update your database correctly please? don't know wich value to trust atm...

**Comment by thepparker** [comment]
There shouldn't be any defense nerfs until 1.7 http://wowwiki.wikia.com/wiki/Patch_1.7.0

**Comment by thepparker** [comment]
Fixed
