### ISSUE TITLE
Arathi basin & others - swirl animation missing from flag captures.: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#119]
BUGGED BEHAVIOR
The swirl animation is missing from the AB/AV Flags & Gurubashi chest.

 CORRECT BEHAVIOR
AB:

https://youtu.be/7MzqS1tCh-0?t=7m

AV:

https://youtu.be/-GkmvNJhvMI?t=6m25s

https://youtu.be/dCVMWSQC0HM?t=2m28s

STV chest animation:

https://youtu.be/lICHcCaY6dw?t=9m45s

 SOURCES
https://youtu.be/7MzqS1tCh-0?t=7m

https://youtu.be/-GkmvNJhvMI?t=6m25s

https://youtu.be/dCVMWSQC0HM?t=2m28s

https://youtu.be/lICHcCaY6dw?t=9m45s

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/2469

**Comment by WobLight** [comment]
Result of investigation:
- spell `24390` triggers `24391` every two secs
  - `24390` target type is `TARGET_SELF`
  - `24391`target type is `TARGET_SCRIPT_COORDINATES` and play the actual visual
- script coordinates are missing
  - `insert into spell_script_target (entry, type, targetEntry) values (24390, 0, 180089);` was successfully  used to test Farm flag in AB
- banners have buggy entry (column data1 should be in data0)
  - they can be found with `select * from gameobject_template where data1 = 1479;`
- banners and gurubashi treasure chest share value 17 for column 11 in lock database
