### ISSUE TITLE
Vis'kag

### ISSUE THREAD

**Issue by NeedElysium** [elysium-project/server#1190]
![viskag](https://user-images.githubusercontent.com/29754316/27638499-bff5bcd0-5c13-11e7-8148-a7b9e4f2f592.PNG)

Vis'kag is wrong according to the patch

Supposed to have:
One-hand	Sword
100 - 187 Damage	Speed 2.60
(55.2 damage per second)
Chance on hit: Delivers a fatal wound for 240 damage.

And as you see on the screenshot i've posted it is not so.

WDB folder has been deleted 10 times (just for good measures)

**Comment by Stunlocked** [comment]
post has already been made just comment on it
and has all the evidence you didnt leave no evidence to where links are proof.

**Comment by thepparker** [comment]
Fixed
