### ISSUE TITLE
Missing Engineering items.

### ISSUE THREAD

**Issue by saigooner** [elysium-project/server#1191]
http://db.vanillagaming.org/?item=18986
http://db.vanillagaming.org/?item=18984

http://db.vanillagaming.org/?item=18634
http://db.vanillagaming.org/?item=18639
http://db.vanillagaming.org/?item=18638

http://wowwiki.wikia.com/wiki/Patch_1.4.0

**Comment by saigooner** [comment]
Still the case after the restart

**Comment by thepparker** [comment]
All items are available now, I believe
