### ISSUE TITLE
Items with incorrect stats

### ISSUE THREAD

**Issue by Floydmaest** [elysium-project/server#1192]
Greetings, 

Tooth of Gnarr is still +15int ; +10sp instead of: http://db.vanillagaming.org/?item=13141
Fordring's Seal is still +33heal instead of: http://db.vanillagaming.org/?item=16058
Bracers of Prosperity missing +2 heal: http://db.vanillagaming.org/?item=18525
The hammer of Grace missing +2 heal: http://db.vanillagaming.org/?item=11923
Brightly Glowing Stone missing +4 heal: http://db.vanillagaming.org/?item=18523
Stormrage legguards missing mp/5 : http://db.vanillagaming.org/?item=16901

Thank you :)

**Comment by Kvel2D** [comment]
Also other big healing items:

Red Dragonscale Breastplate and Robes of the Exalted should have their +healing buffed as well.
Source for Red Dragonscale Breasplate: http://wowwiki.wikia.com/wiki/Red_Dragonscale_Breastplate?oldid=183062  (bwl patch was July 12)

**Comment by thepparker** [comment]
Tooth of Gnarr updated in 1.10
Fordring's Seal and other items have their correct healing
Stormrage MP5 added in 1.9
