### ISSUE TITLE
Gurubashi event, no chest spawns (Elysium)

### ISSUE THREAD

**Issue by Abeneezer** [elysium-project/server#1193]
I was at the arena at 3:00 pm server time, and hung around for like 30 mins. No chest spawned.

**Comment by merlsti** [comment]
I can confirm

**Comment by djlax805** [comment]
The event still does not work.

**Comment by merlsti** [comment]
Any news on this topic??

**Comment by merlsti** [comment]
bump

**Comment by sipertruk** [comment]
probably fixed by #1744 when it'll be on live servers

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
