### ISSUE TITLE
MC loot not dropping

### ISSUE THREAD

**Issue by Lynxesguide** [elysium-project/server#1194]
Items that should start dropping in 1.4 & 1.5 but they are not available to query thus not dropping:
- Helm of the Lifegiver
- Manastorm Leggings
- Salamander Scale Pants
- Flamewalker Legplates
- Heavy Dark Iron Ring
- Ring of Spellpower
- Sorcerous Dagger
- Deep Earth Spaulders
- Aged Core Leather Gloves 
- Magma Tempered Boots
- Quick Strike Ring
- Talisman of Ephemeral Power
- Obsidian Edged Blade
- Brutality Blade
- Ancient Petrified Leaf
- The Eye of Divinity
- Fireguard Shoulders
- Wild Growth Spaulders
- Fireproof Cloak
- Cauterizing Band
- Core Hound Tooth
- Finkle's Lava Dredger
- Crown of Destruction
- Choker of the Fire Lord
- Band of Sulfuras
- Essence of Pure Flame
- Perdition's Blade
- Plans: Elemental Sharpening Stone
- Pattern: Core Armor Kit
- Schematic: Core Marksman Rifle
- Pattern: Flarecore Wraps
- Schematic: Force Reactive Disk
- Schematic: Biznicks 247x128 Accurascope
- Recipe: Major Rejuvenation Potion
- Formula: Enchant Weapon - Spell Power
- Formula: Enchant Weapon - Healing Power

**Comment by Pleasant-Elysium** [comment]
Did you clear your WDB folder?

**Comment by ItsmeAga** [comment]
I cleared my WDB and those items still cannot be queried

**Comment by Lynxesguide** [comment]
I deleted my WDB folder twice

**Comment by eekapes** [comment]
What about onslaught girdle?

**Comment by Lynxesguide** [comment]
I was able to query onslaught girdle

**Comment by StadenElysium** [comment]
Fixed.
