### ISSUE TITLE
Bloodseeker, Icebarb etc + Quest not implemented? Ely [1.5]

### ISSUE THREAD

**Issue by Hadrilkar** [elysium-project/server#1198]
http://wowwiki.wikia.com/wiki/Bloodseeker

**Comment by knasen88** [comment]
++++++++++++++++++

**Comment by kallith** [comment]
Evidence that it existed pre BWL can be seen in the 1.6.0 patchnotes it says:

> - The Bloodseeker crossbow's firing animation has been corrected.

**Comment by Hadrilkar** [comment]
The link provided says added 1.5 in addition to ^ it also states

Patch 1.6.0 (12-Jul-2005):

    Bloodseeker has had its damage variance altered to be more in line with other crossbows and bows. While the minimum and maximum damage values of the item has changed, the average DPS value of the weapon has not changed.
    The Bloodseeker crossbow's firing animation has been corrected.

 Patch 1.5.0 (2005-06-07): Added.

**Comment by Hadrilkar** [comment]
https://web.archive.org/web/20060325021820/http://wow.allakhazam.com/db/quest.html?wquest=7181

**Comment by ingram1** [comment]
++++++++

**Comment by DoctorMoses777** [comment]
It is my belief these items need to be added as they were there on patch release. Please see below.

Per Allakahazam : Added: Jun 7th, 2005
[https://web.archive.org/web/20060325021820/http://wow.allakhazam.com/db/quest.html?wquest=7181](url)

Per WoW Wiki: 
Patch/Release Date/Version/Interface.toc
Patch 1.5.0 / 7 June 2005 / 4442 / 1500 
[http://wowwiki.wikia.com/wiki/Patches/1.x ](url)

**Comment by thepparker** [comment]
Fixed
