### ISSUE TITLE
Elysium 1.5 Patch T1 Mage Shoulders Stats not Updated, Dragonrider Boots Stats not Updated

### ISSUE THREAD

**Issue by ArthurFrayn** [elysium-project/server#1199]
After patch and deleting WDB folder with WoW closed T1 Arcanist Mantle's stats have not updated yet. Still showing +21 Arc Dmg, instead of the updated +14 spl dmg and 4mp5. Dragonrider Boots' stats have not been updated yet as well (+18 spl dmg).

**Comment by thepparker** [comment]
Fixed
