### ISSUE TITLE
Freezing band not showing correct stats

### ISSUE THREAD

**Issue by dcish** [elysium-project/server#1200]
http://db.vanillagaming.org/?item=942 -- Still has 14 damage only.

**Comment by dcish** [comment]
Updated to 21 damage but dropped the freezing proc.

**Comment by bawbcat** [comment]
Confirmed -- the damage has been updated but Proc has been completely removed. 

item:942:0:0:0:0:0:0:0:0

Here are the correct stats:

![image](https://user-images.githubusercontent.com/29760859/27655154-5ab6a268-5c12-11e7-92cc-89ae3674e299.png)

**Comment by thepparker** [comment]
Fixed
