### ISSUE TITLE
Elysium 1.4 shaman quest 'The Darkreaver Menace' not ingame

### ISSUE THREAD

**Issue by eyesackle** [elysium-project/server#1202]
There's supposed to be a quest from Sagorne Creststrider as of patch 1.4 that rewards the Skyfury Helm.

**Comment by shenna-elysium** [comment]
Source?

**Comment by shenna-elysium** [comment]
Quest was added in 1.4; but the reward 1.7.

**Comment by eyesackle** [comment]
fair enough, but as of now there is no quest and no reward.

**Comment by Myezule** [comment]
I support this! Please fix this bug. I want to get the quest done so I can have my awesome helmet when ZG comes out :D

**Comment by thepparker** [comment]
Quest will be available once the rewards are available
