### ISSUE TITLE
[Elysium 1.5] Job Opening: Guard Captain of Revantusk Village

### ISSUE THREAD

**Issue by Razorwynd** [elysium-project/server#1203]
The quest "Job Opening: Guard Captain of Revantusk Village" is not in the game yet. However, according to http://wowwiki.wikia.com/wiki/Quest:Job_Opening:_Guard_Captain_of_Revantusk_Village this quest was introduced in 1.5.

Is this intended?

**Comment by thepparker** [comment]
Fixed
