### ISSUE TITLE
Dreadsteed of Xoroth is bugged

### ISSUE THREAD

**Issue by Rendasza** [elysium-project/server#1208]
Jeevees doesnt put down any of the items and the Dreadsteed isn't being summoned when using the corresponding item.

**Comment by Nymis** [comment]
Can confirm. No items are being put down, the imps spawn but after they are killed the event is simply canceled.

**Comment by deblood** [comment]
I do confirm too

**Comment by Silhu** [comment]
Can confirm that too

**Comment by StadenElysium** [comment]
Fixed.
