### ISSUE TITLE
NPC pets should not de-spawn on master death: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#121]
BUGGED BEHAVIOR
Currently NPC pets de-spawn when their master is killed. This is incorrect.

 CORRECT BEHAVIOR
1. NPC pet should stay in combat with the player until killed or de-aggroed.
2. When de-aggroed the NPC pet should despawn to not clutter the world with npc pets.

SOURCES
1. 2:45 for a fight vs a mob with a pet. Note how the Voidwalker stays and fights after npc death. https://youtu.be/16_fiObHoVo?list=PLMeJnlp72R7p-X7PgsMFqqjPtcxhF7kB_&t=162

2. I have no source for no. 2 but if 1 is changed to correct, number 2 is needed to prevent unintended behavior.  EDIT: source: https://www.youtube.com/watch?v=x9M61jaHFVM&t=1h29m05s
Thank you Healyheals

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/3272

**Comment by GuybrushGit** [comment]
NPC pet despawn was hardcoded by nost for some reason.
To fix this you can simply remove these lines: https://github.com/elysium-project/server/blob/development/src/game/Objects/Unit.cpp#L7848

But why would they add that in the first place?

**Comment by QAkvastskaft** [comment]
Well, the improved de-spawn mechanic seen here #114 might be needed to ensure that mobs de-spawn when dropping combat if their master is dead. This might have been a quick fix to ensure no loose "pets" roaming the world not de-spawning. 

What is your opinion? video show pet (likely) despawning as soon as combat is droped when the master is killed: https://www.youtube.com/watch?v=x9M61jaHFVM&t=1h29m05s

**Comment by GuybrushGit** [comment]
That mechanic applies only to temp summons, not pets. 
I tried removing that nost code and it worked like in that video, pet stayed alive and despawned when I ran away and leashed it.

**Comment by QAkvastskaft** [comment]
Fixed
