### ISSUE TITLE
Felcloth Hood/Felcloth Shoulders/Felcloth Gloves etc... Incorrect stats

### ISSUE THREAD

**Issue by merlsti** [elysium-project/server#1213]
These following items do not have the right stats and should have their stats corrected to the following ones according to db.vanillagaming.com

Felcloth Hood: 10 int, 30 Shadow Power, 61 armor.
Felcloth Shoulders: 5 spirit, 26 Shadow Power, 60 armor.
Felcloth Gloves: 9 stamina, 33 Shadow Power, 55 armor.
Felheart Bracers: 11 int, 8 spirit, 18 stam, 13 Spell power.
Songstone of Ironforge: 7 int, 4 spirit, 18 Spell power.

**Comment by schmelzgesic** [comment]
Check your values for Felheart Bracers.
http://web.archive.org/web/20060207011850/http://wow.allakhazam.com:80/db/itemset.html?setid=203
Don't cite db.vanillagaming.org as a source; it is 1.12.1 stats and is not accurate.
Felheart and Arcanist sets were both updated twice, once in 1.4, and then another 1.9.3.
