### ISSUE TITLE
The Eye of Shadow

### ISSUE THREAD

**Issue by Tharim** [elysium-project/server#1214]
http://db.vanillagaming.org/?item=18665 [The Eye of Shadow] does not appear to be lootable in game yet.
Since it is part of the 1.4 Benediction/Anathema Quest it should be 100% droprate from Kazzak and a low droprate from Elite Demons in Winterspring and Blasted Lands.

**Comment by AnnihilatedTyro** [comment]
My guild farmed 2 of them last night in Blasted Lands.
