### ISSUE TITLE
fang of mystics isnt updated

### ISSUE THREAD

**Issue by xhummerx** [elysium-project/server#1216]
fang of mystics still has its old stats and is missing 40 spell dmg 
[http://db.vanillagaming.org/?item=17070](

**Comment by saigooner** [comment]
Doesn't get updated until AQ

**Comment by xhummerx** [comment]
i recall it got updated on nost before 1.11 since the wowwiki was wrong and it got updated with mc patch/ when they added the extra loot tables to azuregos/lord kazzak

**Comment by saigooner** [comment]
https://web.archive.org/web/20051115164528/http://wow.allakhazam.com:80/item.html?witem=17070

November 2005 - After the release of 1.4 and 1.5

**Comment by Citano** [comment]
This item did not (and should not) get updated with this patch, nor should it be updated in patch 1.11.

Correct patch for update is 1.10
Source: https://web.archive.org/web/20060612222415/http://wow.allakhazam.com:80/db/item.html?witem=17070

**Comment by thepparker** [comment]
Updated in 1.10
