### ISSUE TITLE
Jintha'alor elite quests from Call to Arms! board are missing

### ISSUE THREAD

**Issue by fragk** [elysium-project/server#122]
Job Opening: Guard Captain of Revantusk Village
http://db.vanillagaming.org/?quest=7862
and
Wanted: Vile Priestess Hexx and Her Minions
http://db.vanillagaming.org/?quest=7861

Are not present on the Call to Arms! board in Revantusk village in the Hinterlands.

Expected Behavior: Both quests should be here from the start as they are not unlocked from chain quests or aren't supposed to.

**Comment by QAkvastskaft** [comment]
They are disabled by intent on the realms Elysium and Zeth'kur. They were added at a later patch and will be similarly handled here

**Comment by fragk** [comment]
Thanks for the quick response, do you happen to know which patch # that is?

**Comment by QAkvastskaft** [comment]
http://wowwiki.wikia.com/wiki/Patch_1.5.0

**Comment by fragk** [comment]
Thank you, closing.

**Comment by ssishtar** [comment]
Jintha Alor quests should be up the AV patch, yet they still miss. Yesterday they were up on Elysium, then we had the server crash and they disappeared again.
