### ISSUE TITLE
BattleGear of might

### ISSUE THREAD

**Issue by Defend2** [elysium-project/server#1225]
Battlegear of Might is showing stats for patch 1.8 instead of patch 1.5

https://forum.nostalrius.org/viewtopic.php?f=6&t=16607#p105622

Might:
1.3
http://web.archive.org/web/20050207014147/http://wow.allakhazam.com/db/itemset.html?setid=209

1.5 
http://web.archive.org/web/20050729085314/http://wow.allakhazam.com/db/itemset.html?setid=209

1.8+ 
http://web.archive.org/web/20051211002451/http://wow.allakhazam.com/db/itemset.html?setid=209

https://www.reddit.com/r/wowservers/comments/5gn3r6/nostalrius_item_update_pre_av_through_avbwlzg/

**Comment by kyle21b** [comment]
i approve of this post

**Comment by thepparker** [comment]
Fixed
