### ISSUE TITLE
Grimtotem naturalists in Feralas dont attack in their bearform: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#123]
BUGGED BEHAVIOR
When i attacked them (with frostbolt) they just walk a few yards then stop, doing nothing, sometimes they un-shapeshift and start healing.

 CORRECT BEHAVIOR
Attack?!

 SOURCES
Me

FROM PRT:
The combat movement AI flag of this creature is turned to off. That is probably the source of this issue.
http://i.imgur.com/MFsCDX0.png

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/877

**Comment by GuybrushGit** [comment]
`UPDATE creature_ai_scripts SET event_inverse_phase_mask=14 WHERE id=772613;`
Will fix the movement but he still wont use abilities, all the EventAI for this mob needs to be redone.

**Comment by QAkvastskaft** [comment]
Here is the fixed proposed by Fuzedknight for this mob. I think its aimed at Cmangos but it might be helpful.

update creature_template set minlevel = 41, maxlevel = 42, minmeleedmg = 55, maxmeleedmg = 77, minlevelhealth = 1521, maxlevelhealth = 1585, minlevelmana = 1332, maxlevelmana = 1381, armor = 1841, speedwalk = 1.0, speedrun = 1.14286, meleebaseattacktime = 2600, inhabittype = 3, resistancenature = 65 where entry = 7726;

update creature_template set AIName = 'EventAI', ScriptName = '' where entry = 7726;

delete from creature_ai_scripts where creature_id = 7726;

insert into creature_ai_scripts (id, creature_id, event_type, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772601, 7726, 11, 0, 0, 0, 0, 0, 30, 1, 1, 3, 'Grimtotem Naturalist - Random Phase Spawn');

insert into creature_ai_scripts (id, creature_id, event_type, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772602, 7726, 21, 0, 0, 0, 0, 0, 30, 1, 1, 3, 'Grimtotem Naturalist - Random Phase Evade');

INSERT INTO creature_ai_scripts VALUES
(772603, 7726, 9, 13, 100, 1, 0, 40, 3200, 3300, 11, 9739, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Cast Lightning Bolt (Phase 1)'), 
(772604, 7726, 3, 13, 100, 1, 15, 0, 100, 100, 21, 1, 0, 0, 22, 2, 0, 0, 0, 0, 0, 0, 'Start Combat Movement and Set Phase 2 when Mana is at 15% (Phase 1)'), 
(772605, 7726, 9, 13, 100, 1, 35, 80, 0, 0, 21, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Start Combat Movement at 35 Yards (Phase 1)'), 
(772606, 7726, 9, 13, 100, 1, 5, 35, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Prevent Combat Movement at 15 Yards (Phase 1)'), 
(772607, 7726, 9, 13, 100, 1, 0, 5, 0, 0, 21, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Start Combat Movement Below 5 Yards'), 
(772608, 7726, 3, 11, 100, 1, 100, 30, 100, 100, 22, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Set Phase 1 when Mana is above 30% (Phase 2)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772609, 7726, 14, 13, 1, 500, 40, 15000, 20000, 11, 12160, 6, 1, 'Grimtotem Naturalist - Rejuvenation (Phase 1)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772610, 7726, 4, 7, 0, 0, 0, 0, 0, 11, 19030, 0, 7, 'Grimtotem Naturalist - Bear Form (Phase 3)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772611, 7726, 0, 7, 1, 2000, 8000, 7000, 10000, 11, 12161, 1, 0, 'Grimtotem Naturalist - Maul (Phase 3)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772612, 7726, 0, 7, 1, 3000, 11000, 11000, 12000, 11, 15727, 1, 32, 'Grimtotem Naturalist - Demoralizing Roar (Phase 3)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action2_type, action2_param1, comment) values (772613, 7726, 2, 13, 0, 15, 0, 0, 0, 25, 1, -47, 'Grimtotem Naturalist - Flee at 15% (Phase 1)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action2_type, action2_param1, comment) values (772614, 7726, 2, 11, 0, 15, 0, 0, 0, 25, 1, -47, 'Grimtotem Naturalist - Flee at 15% (Phase 2)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772615, 7726, 0, 7, 1, 1000, 1500, 1000, 2000, 21, 1, 0, 0, 'Grimtotem Naturalist - Turn on Combat Movement (Phase 3)');

insert into creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment) values (772616, 7726, 1, 13, 1, 1000, 1500, 1000, 2000, 28, 0, 19030, 0, 'Grimtotem Naturalist - Remove Bear Form (Phase 1)');
