### ISSUE TITLE
Unexpected PvP Honor Rank result this week. 

### ISSUE THREAD

**Issue by lordmaffe** [elysium-project/server#1235]
Hello. I ranked from rank 4-5.8 this week with standing 44 and 330k honor earned. This seems low compared to other players of similar rank and the Rank Points I got previously. 

pic related, me on the right: http://imgur.com/a/bwPz4

CAn you confirm if this is correct?

ign: Fossegrimen Elysium PvP

**Comment by smkrus** [comment]
Refer to this http://wowwiki.wikia.com/wiki/Honor_system_(pre-2.0)
You probably earned somewhere between 10-11k RP with that standing.
Rank 4 (near start, 0%) = 10k RP - 20% decay (2k) = 8k RP before the weeks earnings.
8k (initial)+ 10k (earned) = roughly 18k
You can see where 18k is on that chart. Around where you ended up.
