### ISSUE TITLE
Hurricane needs fixed

### ISSUE THREAD

**Issue by DJVirute** [elysium-project/server#1236]
Please update the Hurricane bow. It is missing the 34 frost damage chance on hit. Right now it is a completely useless trash epic, plz update this. TY

**Comment by RussianE39** [comment]
On elysium the bow stats is wrong, but this bow shouldnt have 34 frost dmg effect at the current patch level. Source:
https://web.archive.org/web/20050529061950/http://wow.allakhazam.com:80/item.html?witem=2824

**Comment by GuybrushGit** [comment]
Same as https://github.com/elysium-project/server/issues/513
