### ISSUE TITLE
The Balance of Light and Shadow can't be completed.

### ISSUE THREAD

**Issue by Morran213** [elysium-project/server#1242]
The quest from Eris Havenfire (The Balance of Light and Shadow) can't be completed and turned in. If the event is successfully finished, nothing happens and the quest does not register as completed. Two other priests experienced the same problem as I did.

**Comment by Sulpitz** [comment]
I can confirm that. Did all waves but the quest did not complete.

**Comment by Sulpitz** [comment]
I did the quest again just now. All 5 waves got to the end and just despawned. Quest giver is still there. Quest status did not change. After i reloged, now the quest is completet, but I'm not able to turn it in at  the quest giver.

**Comment by Maethgwen** [comment]
I can confirm that, too. Quest is listed as complete in my questlog. Can't turn in the quest. If needed I recorded the entire event (crappy smartphone quality tho..)

**Comment by Desalous** [comment]
I got both eyes last night and completed my quest too.just says completed but she won't take it or give me my Benny! :'(

**Comment by gonor** [comment]
I have it completed. However, I cannot turn it in.
![benediction quest](https://user-images.githubusercontent.com/28951460/27815994-eeeb8d14-60cb-11e7-9e9f-cedfd09a995c.PNG)

**Comment by thepparker** [comment]
Fixed
