### ISSUE TITLE
Being hit by melee should cause you to stand , and second, I should not be able to /sit while stunned

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1247]
Being hit by melee should cause you to stand
Yet after melee hits I am still sitting.

Fix please

http://i.imgur.com/63rucYV.png
http://i.imgur.com/nZyXU2L.png

First fix: Allow all melee hits to force player to stand

Second fix: Prevent players being able to sit when stunned 

As of right now players can use divine shield while stunned BUT are forced to press x to STAND after they are drinking.
This feels stupid and non blizzlike. 

Proof
-----------------------------------------

Melee attacks against a sitting target automatically hit and cause double damage. The first damage taken while sitting will cause a target to immediately stand. 
http://wow.gamepedia.com/Sit

This is gamebreaking and allows rogues to stunlock kill players who would normally be using divine shield from being forced to stand VIA being hit by any melee attack. This was never how vanilla was working. Melee forces players to stand thus forcing them to use bubble to protect them from a stunlock

Players who DRINK constantly such as me when I am farming are at constant risk as I farmed fel cloth in blasted lands

**Comment by Mostprovidedlinks** [comment]
Melee attacks against a sitting target automatically hit and cause double damage. The first damage taken while sitting will cause a target to immediately stand.

**Comment by Mostprovidedlinks** [comment]
Melee attacks against a sitting target automatically hit and cause double damage. The first damage taken while sitting will cause a target to immediately stand.

**Comment by Mostprovidedlinks** [comment]
I should not be able to sit while stunned either

**Comment by Mostprovidedlinks** [comment]
I should not be able to sit while stunned either

**Comment by stesve** [comment]
https://github.com/elysium-project/server/commit/c0bb4993a6f37250c7c3f5b9260f4d56cbd4dc6c
