### ISSUE TITLE
List of items not in game on Elysium that should be in

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#1250]
Items in Scholomance, Stratholme, UBRS and DM:W:

Cloth:
Shivery Handwraps
Burial Shawl
Coldstone Slippers
Shroud of the Nathrezim
Crimson Felt Hat
Shadowy Laced Handwraps
Thuzadin Sash
Sacred Cloth Leggings
Diabolic Mantle

Leather:
Ghoul Skin Leggings
Tattered Leather Hood
Icy Tomb Spaulders
Malefic Bracers
Plaguebat Fur Gloves
Plaguehound Leggings

Mail:
Bone Golem Shoulders
Shadowy Mail Greaves
Barrage Girdle
Stratholme Militia Shoulderguard
Feralsurge Girdle

Plate:
Wraithplate Leggings
Death Knight Sabatons
Belt of the Ordained
Grand Crusader's Helm
Death Grips
Chitinous Plate Legguards
Morlune's Bracer
Fel Hardened Bracers

Back:
Phantasmal Cloak
Pale Moon Cloak
Gracious Cape

Jewellery:
Necromantic Band
Innervating Band
Anastari Heirloom
Band of Rumination

Weapon:
Specter's Blade
Malicious Axe
Hammer of the Vesper
Hammer of the Grand Crusader
Peacemaker
Bone Slicing Hatchet

Off Hand:
Spellbound Tome
Intricately Runed Shield
Dreadguard's Protector

Ranged:
Oblivion's Touch
Ancient Bone Bow
Screeching Bow
Carapace Spine Crossbow
Xorothian Firestick

Recipes:
Schematic: Ultra-Flash Shadow Reflector
Schematic: Hyper-Radiant Flame Reflector

-----------------------------end of dungeon items-----------------------------

Molten Core:
Sulfuron Ingot
Flarecore Wraps
Force Reactive Disk

Azuregos:
Cold Snap
Snowblind Shoes
Crystal Adorned Crown
Mature Blue Dragon Sinew

Kazzak:
Fel Infused Leggings
Flayed Doomguard Belt
Blacklight Bracer

Onyxia:
Ring of Binding
Onyxia Tooth Pendant
Mature Black Dragon Sinew

Alterac Valley:
[most reputation rewards]
Yeti Hide Bracers
Frozen Steel Vambraces
Winteraxe Epaulets	
Deep Rooted Ring
Cold Forged Blade
Frost Runed Headdress

Quest:
Nat Pagle's Extreme Angler FC-5000
Rune of the Guard Captain
Deep Woodlands Cloak
Woven Ivy Necklace
Arena Grand Master
Plans: Sulfuron Hammer
AV 1-6 Insignias
Wand of Biting Cold
Bloodseeker
Cold Forged Hammer
Ice Barbed Spear
Royal Seal of Alexis
Elemental Circle
Ocean's Breeze
Tidal Loop

World Invasions:
Baron Charr's Sceptre
Elemental Ember
Avalanchion's Stony Hide
Hardened Stone Band
Tempestria's Frozen Necklace
Frigid Ring
Pattern: Stormshroud Gloves
Sash of the Windreaver
Zephyr Cloak
Pattern: Stormshroud Gloves

Stranglethorn Fishing Extravaganza:
Arcanite Fishing Pole
Hook of the Master Angler
Lucky Fishing Hat
Nat Pagle's Extreme Anglin' Boots
Rockhide Strongfish

Other:
'of X Wrath' and 'of Healing' gear
Dark Iron Residue
Hyper-Radiant Flame Reflector
Ultra-Flash Shadow Reflector
Schematic: Gyrofreeze Ice Reflector
Gyrofreeze Ice Reflector
Dimensional Ripper - Everlook
Ultrasafe Transporter: Gadgetzan
Arena Bracers
Arena Wristguards
Arena Vambraces
Arena Bands
Sulfuron Hammer

None of these items are queryable by the server.

**Comment by Hadrilkar** [comment]
Bump

**Comment by JosipbrozElysium** [comment]
"Staff of Metanoia" should be added in patch 1.10!
http://wowwiki.wikia.com/wiki/Staff_of_Metanoia

**Comment by JosipbrozElysium** [comment]
"Pattern: Stormshroud Gloves" should also be added in patch 1.10!
http://wow.gamepedia.com/Pattern:_Stormshroud_Gloves

**Comment by JosipbrozElysium** [comment]
"Dimensional Ripper - Everlook" is on the PTR, but has no spell attached!
"Sash of the Windreaver" is still missing on the PTR.
Will add/correct those items!

All other items have been added to the PTR and will be deployed soon to the live servers. Thank you for the report!

Best regards!

**Comment by Sabre142** [comment]
Thanks @JosipbrozElysium, closing this issue due to being fixed.
