### ISSUE TITLE
Warlock final mount quest (summoning the dreadsteed)

### ISSUE THREAD

**Issue by nigenigel23** [elysium-project/server#1254]
After using J'eevee's Jar in DMW while standing on the summoning circle to release the imp, he does not place the Black March, Doomsday Candle, and the Bell of Dethmoora, therefore making the summoning fail.

**Comment by Silhu** [comment]
Can confirm

**Comment by Rendasza** [comment]
+1

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
