### ISSUE TITLE
Onyxia's loot-table still messed up...

### ISSUE THREAD

**Issue by drtakhs** [elysium-project/server#1255]
This has been going on for too long... All of us thought that the yesterday's patch would finally fix that issue, but it didn't.

Here is the loot from Onyxia kills that happened yesterday evening (after 1.4&1.5 patch).

![9aupd175ug6z](https://user-images.githubusercontent.com/15212862/27682448-3bf6cdbc-5ccb-11e7-94ad-5a72749f323c.jpg)

The problem is still here. 

And lot's of guilds can confirm that. 

https://www.reddit.com/r/ElysiumProject/comments/6k4a6z/guys_onyxia_loot_table_is_fixed/

Will this ever be fixed?

Thanks for your time :)

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
