### ISSUE TITLE
Drillborer Disk, Defense Items

### ISSUE THREAD

**Issue by Beheader** [elysium-project/server#1256]
After the MC loot fix-restart around 19-20.00 server time 28/06/17 the drillborer disk lost its added block value from the patch - Most of the blue tank items had been nerfed in defense rating because of the patch, these values were rerolled back to their value before the patch. An example could be the Draconian Deflector. I didnt double check to see if the Defense-nerf was indeed this patch- BUT the drillborer disk should have block value, good day!

**Comment by thepparker** [comment]
Fixed
