### ISSUE TITLE
Freezing Band & Arcanist Mantle - wrong stats & no proc chance

### ISSUE THREAD

**Issue by Drozdy3** [elysium-project/server#1257]
Hello, 

I've noticed 2 items with bugged stats:
1. Arcanist Mantle - still has +21 arcane damage instead +14 spell dmg
http://db.vanillagaming.org/?item=16797 - Arcanist Mantle
2. Freezing Band - it only adds +21 frost dmg, but the 1% proc chance to freeze the attacker is gone. 
http://db.vanillagaming.org/?item=942 - Freezing Band

**Comment by Citano** [comment]
Arcanist Mantle is not supposed to have +14 spell damage before much later on (around patch 1.9.0)
However, it should have been updated with this patch to the following stats:
**76 Armor** (same as before)
**+24 Intellect** (same as before)
**+10 Stamina** (same as before)
**+5 Spirit** (down from +9 Spirit)
**+7 Shadow Resistance** (changed from +5 Fire Resistance)
**Equip: Restores 4 mana per 5 sec.** (New)
**Equip: Increases damage done by Frost spells and effects by up to 11.** (changed from 21 Arcane damage)
Source: http://web.archive.org/web/20050721073949/http://wow.allakhazam.com:80/db/itemset.html?setid=201


Regarding the Freezing Band, it should indeed have the proc change to freeze the attacker still.
Source: http://web.archive.org/web/20060109070615/http://wow.allakhazam.com:80/db/item.html?witem=942

**Comment by wassupsheldo** [comment]
i'm perfectly fine with it only giving the 11 spell damage however i thought this template for was for patch 1.5 http://db.vanillagaming.org/?itemsets
https://docs.google.com/spreadsheets/d/10sJ6FVcVXVHKVmzVCLTxfEYGtDikeNuumaiX-DMAwX8/edit#gid=0

**Comment by Citano** [comment]
Vanillagaming uses 1.12 values so it's not reliable until Elysium itself reaches this content patch.

**Comment by thepparker** [comment]
Stats are correct
