### ISSUE TITLE
Restorative elixir removes only 1 debuff at a time

### ISSUE THREAD

**Issue by ssishtar** [elysium-project/server#1258]
Restorative elixir should remove ONE of EACH magic, poison, curse or disease debuffs at a time, each 5 seconds. Currently, if you have 2 different debuffs on you, it's removing ONLY ONE at the 5 second tick, which is wrong. Even tooltip specifies this, please fix, it's a very important potion to have in raids, especially in BWL.

On both retail and Nostalrius, Restorative Potion removed even 4 debuffs at a time, if they were different, say at Chromaggus in BWL. So if you have 1 magic, 1 curse, 1 poison, all of these debuffs should be removed in 1 tick.

**Comment by drtakhs** [comment]
Removes 1 magic, curse, poison _**or**_ disease effect on you every 5 seconds for 30 seconds.

**Comment by ssishtar** [comment]
it always removed all types of debuffs at once on both live and nostalrius. we used it at chromaggus in both retail and nostalrius and worked like that.

**Comment by taurenrogue** [comment]
and i dual wielded thunderfuries on a mage... what you need here is a source ^_^

**Comment by thepparker** [comment]
Working as intended
