### ISSUE TITLE
Fandral Staghelm reffered to as "ArchHunter": CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#126]
BUGGED BEHAVIOR
Throughout the quest chain "Crown Of The Earth" in Teldrassil Arch Druid Fandral Staghelm is reffered to as "Arch Hunter"

 CORRECT BEHAVIOR
He must be reffered to as Arch Druid

 SOURCES
I think it is quite obvious but http://vanilla-wow.wikia.com/wiki/Fandral_Staghelm

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/826

**Comment by FractalCabush** [comment]
A pull request is up for this :)

**Comment by FractalCabush** [comment]
See : https://github.com/elysium-project/server/pull/176
