### ISSUE TITLE
Onyxia's head and the quest

### ISSUE THREAD

**Issue by Unbanmongy** [elysium-project/server#1262]
You can not hand in the quest, started by Onyxia's Head to Bolvar Fordragon. Bolvar has 0 to offer you, acts like u don't have a quest at all!

**Comment by Sapplejacks** [comment]
You go to Bolvar after right clicking the head, then head to the 2nd gate of stormwind and there's a guy you turn in the quest.. lol

**Comment by Unbanmongy** [comment]
Once again... I can't speak to Bolvar

**Comment by kampeador** [comment]
Have you completed these quests earlier?
http://db.vanillagaming.org/?quest=7495
http://db.vanillagaming.org/?quest=7496

**Comment by paytime** [comment]
Done. Should be corrected on the next update.

Best regards!

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
