### ISSUE TITLE
Leaf followup - [  The Ancient Leaf]

### ISSUE THREAD

**Issue by EmZeN** [elysium-project/server#1271]
This quest is now able to be started, but when arriving at felwood the quest there or the NPC there is not able to be spoken to. Yesterday when I made the ticket I reminded you lads to make sure the quest is actually able to be done as well not just picked up. Would really really appreciate if you guys could sort this due to that the complexity of this quest and the time needed to be invested!

SO please, fix the issue of all the quest, the npcs and the objectives for this questline so it can be done!

Yours sincerely,
Trial

**Comment by Varrixx** [comment]
Can confirm, am able to find Vartrus The Ancient but am unable to interact with him in any way.

**Comment by Hadrilkar** [comment]
Get ready for the bottle neck

**Comment by Varrixx** [comment]
There was a system message announcing bugged quest for Benediction and Warlock/Paladin class mounts but not the Leaf quest. Talked to GM and he said to resubmit a ticket after maintenance if the problem persists

**Comment by thepparker** [comment]
Fixed
