### ISSUE TITLE
My Warrior can't shoot

### ISSUE THREAD

**Issue by cacaillo** [elysium-project/server#1272]
good afternoon, i have a problem with my warrior Darkbreaker in Darrowshire he can't shoot my gun with ammo (the gun don't react with nothing),  the character of my companion too, his character is Rhagna and his wands does the same.

greetings.

**Comment by poomato** [comment]
My wand works fine, reinstall WoW.

**Comment by cacaillo** [comment]
sorry i've tried and nothing has happened

**Comment by thepparker** [comment]
Make sure you are using the correct shoot skill for your weapon and you have ammo in the ammo slot
