### ISSUE TITLE
Striker's mark wrong stats

### ISSUE THREAD

**Issue by Strikersmarkfetish** [elysium-project/server#1273]
Striker's Mark(http://db.vanillagaming.org/?item=17069) should have 22 attack power 69 - 129 damage, 2.5 speed and 1% hit on Elysium PVP with 1.5 patch.

**Comment by taurenrogue** [comment]
probably as of 1.4 patch already^

**Comment by StadenElysium** [comment]
Possibly patch 1.3. An Allakhazam comment made during patch 1.3 has the buffed stats, yet a cached version of the page from earlier in the month (still 1.3) has the old stats. There weren't any patches between those two dates, so I'm not sure if it was a stealth buff that didn't coincide with a client patch or whether the Allakhazam data hadn't been updated for a month.

```
Posted @ Fri, Apr 22nd 8:35 PM 2005
Striker's Mark 
69 - 129 Damage Speed 2.50 
(39.6 damage per second) 
Requires Level 60 
Passive: +22 Attack Power. 
Passive: Improves your chance to hit by 1%. 
```
1.3 release: 7 March 2005
1.4 release: 5 May 2005

Sources:
https://web.archive.org/web/20050901002516/http://wow.allakhazam.com:80/db/item.html?witem=17069
https://web.archive.org/web/20050404063519/http://wow.allakhazam.com:80/db/item.html?witem=17069

**Comment by StadenElysium** [comment]
https://web.archive.org/web/20050429163320/http://www.thottbot.com:80/?i=27150

```
Posted by aznxboy616 on 2005-03-22 18:55:40
I wanna see the reaction when a rogue/warrior rolls on this and says he could use the extra 1% to hit and atk power.  Oh yeah, probably the same reaction when u damn hunters roll on Deathstriker, Blackblade of Shraham.  Pay backs a bitch isnt it, so u hunters stay away from weapons that clearly belong to us warriors/rogues.
```

Patch 1.3 with outdated data being displayed on the sites.

**Comment by thepparker** [comment]
Updated in 1.4 alongside other MC items
