### ISSUE TITLE
The Woodland Protector - quest completion text: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#128]
BUGGED BEHAVIOR
upon completion, the text is (...) Should you find yourself in Dolanaar, able <class>, seek out the knowledgeable <class>, Athridas Bearmantle. He shares our concern for the well being of the forest.(...) if you're a warlock it will say seek out he knowledgeable warlock, Arthidas Blabla...

 CORRECT BEHAVIOR
while it should be (...) Should you find yourself in Dolanaar, able <class>, seek out the knowledgeable druid, Athridas Bearmantle. He shares our concern for the well being of the forest. (...)

 SOURCES
wrong: http://db.vanillagaming.org/?quest=459 right: http://wow-mania.com/armory/?quest=459

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/76

**Comment by FractalCabush** [comment]
Pull request open to correct this :)

**Comment by henkethebenke** [comment]
Fixed in #131 by Fractal. This issue shouldn't be left open.
