### ISSUE TITLE
mc loot table bugged

### ISSUE THREAD

**Issue by eyesackle** [elysium-project/server#1280]
afaik no one has gotten either wristguards of true flight or onslaught girdle in like 40 raids and the chances for neither dropping are so abysmally low that I've decided to make this post

**Comment by ItsmeAga** [comment]
you just totally forgot to mention which stuff is broken/not dropping correctly

**Comment by eyesackle** [comment]
whoops

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
