### ISSUE TITLE
Blastershot Launcher wrong stats

### ISSUE THREAD

**Issue by t00b3ar** [elysium-project/server#1281]
Blastershot Launcher (http://db.vanillagaming.org/?item=17072) should have 73 - 136 damage, 2.6 speed, +6 stam and 1% crit on Elysium PVP with 1.5 patch.

Now:
![blastershot launcher old](https://user-images.githubusercontent.com/29797454/27735173-eac3f280-5da6-11e7-8585-ad4d3c19abdf.jpg)

Should be:
![blastershot launcher new](https://user-images.githubusercontent.com/29797454/27735182-f9b5ad10-5da6-11e7-8f77-edba347bf5a8.jpg)

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
