### ISSUE TITLE
MC drop table bugged

### ISSUE THREAD

**Issue by GhostVez** [elysium-project/server#1282]
Looking over http://www.realmplayers.com/RaidStats/RaidList.aspx?realm=Ely done by many many guilds, there have been zero of certain MC items dropping.

Robes of Volatile Power
Mana Igniting Cord
Ring of Spell Power

Meanwhile I see a large amount of Obsidian Edged Blades & Quick Strike Rings dropping.

**Comment by Manlet** [comment]
Saw Ring of SP drop last night on Elysium

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
