### ISSUE TITLE
[Elysium 1.5] Briarwood Reed not updated

### ISSUE THREAD

**Issue by Grookshank** [elysium-project/server#1285]
Item had new stats for a short time on Wednesday, then was reverted and now has old 1.3 stats again.

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.
Next time, make sure to properly state the problem, compare values and provide proof. Thanks!

Best regards!

**Comment by Kittnz** [comment]
Shouldn't this be closed if its fixed? Can you link commit?

**Comment by JosipbrozElysium** [comment]
I don't have any permissions to do so, though I will forward all the finished issues.
The item was checked on our internal PTR!
