### ISSUE TITLE
[Elysium 1.5] Dragonrider Boots not updated

### ISSUE THREAD

**Issue by Grookshank** [elysium-project/server#1290]
Item had new stats for a short time on Wednesday, then was reverted and now has old 1.3 stats again.

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.
Next time, make sure to properly state the problem, compare values and provide proof. Thanks!

Best regards!

**Comment by Grookshank** [comment]
@JosipbrozElysium Sorry, I did this sloppy, since the values in your update repo for 1.3 > 1.5 were correct, but just not applied (same for the other tickets where I left out the information).
