### ISSUE TITLE
Additional quest removed after abandoning quest?

### ISSUE THREAD

**Issue by Papalok** [elysium-project/server#1297]
I had just finished the quest Assessing the Threat in Redridge Mountains and was running to turn it in when I decided to abandon the tiresome Redridge Goulash quest. I noticed immediately an available quest icon pop up on my minimap, which was odd since I hadn't leveled at all and that wasn't the NPC for Redridge Goulash. Nope, it was the quest that I just finished. Thinking I made a terrible mistake I checked my quest log but I had in fact removed the Redridge Goulash quest as I intended. I definitely did not abandon two separate quests so this has to be some sort of freak bug. If it matters the quests were next to each other in my quest log.

**Comment by thepparker** [comment]
Vanilla does not have quest indicators on the minimap, aside from hand-ins for completed quests. It is an addon issue.
