### ISSUE TITLE
Arcanist mantle not updated!

### ISSUE THREAD

**Issue by wassupsheldo** [elysium-project/server#1300]
Still not updated at all, should either give 11 bonus dmge or 14 not sure which is right and 4 mp5.

http://db.vanillagaming.org/?itemsets

https://docs.google.com/spreadsheets/d/10sJ6FVcVXVHKVmzVCLTxfEYGtDikeNuumaiX-DMAwX8/edit#gid=0

http://web.archive.org/web/20050721073949/http://wow.allakhazam.com:80/db/itemset.html?setid=201

**Comment by sauceboy** [comment]
Arcanist bindings also have wrong stats. Only gives 6 spell damage and should have 12 spell damage.

**Comment by thepparker** [comment]
Stats are currently correct
