### ISSUE TITLE
Black Lotus in Alterac Valley spawns too fast (Elysium)

### ISSUE THREAD

**Issue by ssishtar** [elysium-project/server#1302]
Currently there is a very fast spawn of only 20 minutes in each Alterac Valley, which never happened on live retail in 2006. The Black Lotus in Alterac Valley had a random 60-120 min respawn timer.

This fast spawn destroys the gameplay since half of players just constantly stay in the middle, trying to get Black Lotus. Please fix.

**Comment by martinjlowm** [comment]
The reduced respawn timer is intended due to the high population. However, I do see your point with at most 40 people in a BG and removing the dynamic respawn for just AV should be possible.

**Comment by ssishtar** [comment]
Look, if you need to reduce spawn timer, do it outside AV, not IN AV. Make 20 mins in Silithus, Eastern Plaguelands, Winterspring, but never in AV or you end with eternal games and with people botting all the time in the middle to get Black Lotus. It's as simple as that. 

Revert fast at 60-120 mins the AV Black Lotus spawn or AV is doomed.

**Comment by martinjlowm** [comment]
I'm not the one calling the shots :) But I agree it's a bit broken.

**Comment by GhostVez** [comment]
Yes I can understand the argument about the dynamic spawn should be turned off in AV since it's limited to only 40 people but most zones may have 40 people or less farming Lotus so it's not really a huge difference.

**Comment by staplerx300** [comment]
any update on this?

seems strange to make it spawn more often in AV instead of just the open world

**Comment by martinjlowm** [comment]
Many herb respawn times were decreased by the recent herb "fix", however it also decreased AV Black Lotus ones to 20 minutes respawn.

I contributed [1] recently, which adds dynamic flags for all Black Lotus except for those in AV.  I would expect those in AV to be reverted back to 76 minutes respawn which they were originally. I do not know if it went live today, but it should be fairly easy to figure out.

[1] https://github.com/elysium-project/database/blob/master/tools/Dynamic%20herb%20spawns.sql
