### ISSUE TITLE
Horde Alterac Valley reputation rewards missing

### ISSUE THREAD

**Issue by ssishtar** [elysium-project/server#1303]
I am revered and I can't buy dagger, nor cloak or anything else. The quartermasters and Supply Officers (Grunnda Woflheart and Jekyll Flandring) don't sell any reputation rewards apart of some useless crap like bandages etc. Please fix asap

**Comment by paytime** [comment]
Done. All items were added/corrected on our internal PTR and will be deployed to live servers soon.

Best regards!

**Comment by JosipbrozElysium** [comment]
Done. All the items have been added/corrected on our internal PTR. The update should be deployed to live servers soon!

Best regards!
