### ISSUE TITLE
Having a hard time with Arcane Missile

### ISSUE THREAD

**Issue by Oudeis1447** [elysium-project/server#1305]
Trying to cast Arcane Missile in raid is almost impossible, the spell keep getting interrupt for no valid reason (no damage taken, no movement). We did some testing to see if it's was a debuff limit issue but no. For what I have seen, it's look like only 1 person can channel 1 arcane missile at a time, as if the effect could only be apply by a single mage.

**Comment by Spaztick** [comment]
Different ranks of the same spell will break a channel or remove a debuff. Known bug.

**Comment by thepparker** [comment]
Duplicate
