### ISSUE TITLE
Hammer of the Titans does not have a 10% proc rate 

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1308]
http://db.vanillagaming.org/?item=12796
should have a 10% proc rate
proc rate too low at the moment on elysium
https://vanilla-twinhead.twinstar.cz/?issue=718

retested 5 times ancient hakkari seems to be working actually

**Comment by JosipbrozElysium** [comment]
Can you provide more proof to this?

**Comment by Mostprovidedlinks** [comment]
Sure Ill upload videos

**Comment by Mostprovidedlinks** [comment]
seems to be fine as of 1.10
