### ISSUE TITLE
Mind Control Mob Heals

### ISSUE THREAD

**Issue by Icarus568** [elysium-project/server#1309]
Mind Control, when broken early, heals the mob to full health. Incorrect behavior - mob should be left with the health and mana it had when MC was broken.

**Comment by Spaztick** [comment]
Mind control itself does not, but sometimes the mob will evade and reset if pulled too far away from it's spawn location. Do you have any screenshots or video?

**Comment by WobLight** [comment]
No need to bother, NPC resetting after MC should get fixed by #1101

**Comment by Spaztick** [comment]
It was a fun change having AI on PvP MC although I know there was no AI in vanilla,

**Comment by thepparker** [comment]
Fixed
