### ISSUE TITLE
Cannot start chain for dreadsteed

### ISSUE THREAD

**Issue by samemari** [elysium-project/server#1311]
Jubahl Corpseseeker and Spackle Thornberry has silver exclamation mark for 60 lvl warlock. So chain for dreadsteed cannot be started and Mor'zul Bloodbringer in the Burning Steppes doesn't give quests too. See at least 4 warlocks with the same problem in Ely

![image](https://user-images.githubusercontent.com/29822974/27764997-c5595d14-5eaf-11e7-896d-054bfd987e32.png)

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
