### ISSUE TITLE
Cannot start Paladin epic mount Quest Chain

### ISSUE THREAD

**Issue by Phagocyte** [elysium-project/server#1313]
Level 60 Human paladin - Phago on elysium server
Unable to start epic mount quest chain. Grayed out quest above Duthorian Rall's head. 
https://puu.sh/wzaD9/19a502ac52.png

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!

**Comment by Phagocyte** [comment]
Thanks, I love you. Marry me.
