### ISSUE TITLE
friends in friends list keep showing unknown

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1317]
Social (O) is bugged and needs to be refreshed (Closed and opened) to show character name etc

It says unknown and doesnt show the persons name etc unless i close the tab and click it again.

Ive been doing this 40 times a day and its annoying

Can elysium fix this im sick of closing social and reopening it. This didnt happen on retail

it keeps saying "UNKNOWN"

**Comment by StadenElysium** [comment]
I haven't encountered this before. Please try deleting your WDB folder and then report back.

**Comment by Mostprovidedlinks** [comment]
Sure I will

**Comment by Mostprovidedlinks** [comment]
Its still doing it even after i delete WDB

**Comment by thepparker** [comment]
Cannot reproduce
