### ISSUE TITLE
[Elysium 1.5] - wrong stats on Sapphiron Drape

### ISSUE THREAD

**Issue by Grookshank** [elysium-project/server#1319]
Stats in game are:

49 Armor

+10 Stamina

+15 Intellect

+5 Arcane Resistance

+5 Frost Resistance

Equip: Increases damage and healing done by magical spells and effects by up to 7.

Stats should be:

55 Armor

+10 Stamina

+17 Intellect

+6 Arcane Resistance

+6 Frost Resistance

Equip: Increases damage and healing done by magical spells and effects by up to 14.

Source: https://web.archive.org/web/20050429162955/http://www.thottbot.com:80/?i=27268

and: https://web.archive.org/web/20050610085116/http://wow.allakhazam.com:80/db/item.html?witem=17078

The allakhazam link is from 10th June 2005; Patch 1.5 came out 7th June 2005. Next patch after that was 1.5.1. So the stats I linked should be the stats the item has on 1.5 right now.

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!

**Comment by Grookshank** [comment]
Has been fixed. Thanks.
