### ISSUE TITLE
Elysium 1.5 - wrong stats on Seal of the Archmagus

### ISSUE THREAD

**Issue by Alienlex** [elysium-project/server#1320]
Currently the stats for Seal of the Archmagus on Elysium 1.5 are incorrect.
In game it reads- 

Seal of the Archmagus
Binds when picked up
Unique
Finger
+10 Stamina
+10 Intellect
+10 Spirit
+5 to All Resistances
Requires Level 60
Equip: Restores 2 mana per 5 sec.

The stats for Seal of the Archmagus as of 1.5 should be-

Seal of the Archmagus
Binds when picked up
Unique
Finger
+11 Stamina
+11 Intellect
+11 Spirit
+6 Arcane Resistance
+6 Fire Resistance
+6 Nature Resistance
+6 Frost Resistance
+6 Shadow Resistance
Requires Level 60
Equip: Restores 3 mana per 5 sec.

Sources- 

rexas.tv/nostitems

https://web.archive.org/web/20070103162055/http://www.thottbot.com:80/?i=27567

https://web.archive.org/web/20050227201728/http://wow.allakhazam.com:80/item.html?witem=17110

and my personal experience from 2004-2006

Thank you for continuing doing the work of the vanilla WoW Gods \m/

**Comment by JosipbrozElysium** [comment]
Noted

**Comment by thepparker** [comment]
Fixed
