### ISSUE TITLE
[Huhuran] Noxious Poison

### ISSUE THREAD

**Issue by smkrus** [elysium-project/server#1324]
http://wowwiki.wikia.com/wiki/Princess_Huhuran
Noxious Poison - 2900 nature damage over 8 seconds + Silence. Will hit a random person and anyone around her. Cannot be cleansed.

Half of this ability isn't going off on Anathema. The random ranged player part.
A bit ambiguous in wowwiki. When this actually does get implemented, it looks like only the targeted player should be silenced by this. Not everyone hit by the DoT.

https://www.youtube.com/watch?v=mMF6XIro3oQ
PoV druid @ 1:24 appears silenced
Druid to the right of PoV @ 2:22 appears silenced

https://www.youtube.com/watch?v=VvZXQnK3wp0
Top right priest @ 3:12 appears silenced
Far right druid @ 3:47 appears silenced

https://www.youtube.com/watch?v=1uBaJRWslIo
Left side front healer @ 2:45 appears silenced

https://www.youtube.com/watch?v=NF4Swjou28Q
Middle paladin @ 0:40 who ends up bandaging appears silenced
Priest back left @ 1:00 appears silenced
Paladin back left @ 2:00 appears silenced

**Comment by StadenElysium** [comment]
The silence component is part of the spell, which makes it fairly clear that all afflicted players should be silenced.

**Comment by Lorilay2** [comment]
I specifically remember making fun of our guild leader for getting me silenced on retail by standing too close.

**Comment by smkrus** [comment]
Then explain why every caster with the green DoT doesn't get silenced, and it appears that only exactly 1 does.

**Comment by GuybrushGit** [comment]
The wowwiki article used to mention the silence hits only 1 target but it was later removed and someone wrote in the talk page "_Is it true that only the person targetted by Noxious poison is silenced? I got the impression that everyone in the AE range took the silence and the DoT._"

The spell data from the client clearly states that the silence goes to everyone in a 15yd radius.

Looks like the spell was changed from 1.9 to 1.12 or it was just bugged for a while. 
Either way we should not change this.

**Comment by smkrus** [comment]
You aren't quite grasping the report fully. The spell isn't even being used to begin with... hence being able to skip trash and fight her all clumped up in the tunnel.

**Comment by GuybrushGit** [comment]
Oh I see, its targetting the tank instead of a random target.

**Comment by smkrus** [comment]
It should do an area around her as the center as well as target a ranged person
