### ISSUE TITLE
Ice Armor not receiving the buffed armor/resistance from 2/2 Talent "Frost Warding" 

### ISSUE THREAD

**Issue by Sapplejacks** [elysium-project/server#1325]
Title says it all, It still gives only 380 Armor + 9 resistance from frost instead of the extra from the talent as shown here; http://prntscr.com/fqxa72 & the talent tree http://prntscr.com/fqxajq + the buff tooltip http://prntscr.com/fqxana

**Comment by nobomehl** [comment]
tooltip is incorrect, try looking at your stats in character info before and after casting ice armor
