### ISSUE TITLE
Issue: Flarecore Wraps not in tailoring craftable list

### ISSUE THREAD

**Issue by pingaan** [elysium-project/server#1326]
Hi,

The recipe dropped on Gehennas (raid ID: 627). I learned the recipe but It's not showing in my tailoring inventory. 
My characters name is Pingaan.

Regards.

**Comment by Sabre142** [comment]
The item is not implemented in the game but the recipe is.

**Comment by pingaan** [comment]
Err.. OK. So could I perhaps get the recipe back to learn it later, once the item is in the game?

**Comment by Sabre142** [comment]
If you hover over there recipe in Atlas or linked in chat does it say already learned?

**Comment by pingaan** [comment]
No, it doesn't.

**Comment by pingaan** [comment]
@Sabre142 Are you a developer? Any idea how long it will take to sort out this issue?

**Comment by Sabre142** [comment]
@pingaan I think you are out of luck unless you have recorded the drop on realmplayers or video, even then I doubt it. I'm not a developer.
