### ISSUE TITLE
The Wrong Stuff warlock quest has insanely low drop rate

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1328]
The rotting wood from the quest (50) The Wrong Stuff has an insanely low drop rate

**Comment by Chromo23** [comment]
Bump. I have killed over 13 of the Irontree people and no drops at all.

**Comment by stesve** [comment]
Supposedly it should have a very low droprate.
http://db.vanillagaming.org/?item=20613#wh-comments

**Comment by StadenElysium** [comment]
Drop rate on Anathema appears to be 50%, which is far too high.

https://web.archive.org/web/20060307171108/http://wow.allakhazam.com:80/db/item.html?witem=20613
