### ISSUE TITLE
[Elysium 1.5] All items updated or added with bonus Defense values this patch have been given faulty values.

### ISSUE THREAD

**Issue by Omnipollo** [elysium-project/server#1329]
Hi! I'll start off by saying thanks for all the work you guys put into this! Now to the point.

Every item introduced or reitemized this patch have been given their post-ZG nerf Defense values. With Patch 1.7 every item in the game with bonus Defense had their values reduced by approx. 33%. I quote patch notes saying:

"We have determined that the defense statistic was being applied to items too liberally, causing those items to be stronger than they should have been relative to other items of the same level with different effects. As a result, we have reduced the amount of defense points on all items with bonuses to defense by approximately 33% in order to bring those items in line with other similar items."

This affects Battlegear of Wrath, Battlegear of Might, Heavy Dark Iron Ring, Onyxia Blood Talisman and Core Forged Greaves. Drakeclaw Band suffers from the same issue.

Wrath leg and head pieces should have their Defense values bumped up from the current +11 to +16 to counter the 33% nerf, as per https://web.archive.org/web/20050813084531/http://www.thottbot.com:80/?set=218.

The entire Might set should have their Defense bonueses of +5 and +7 bumped up to +8 and +10 respectively, as per https://web.archive.org/web/20050806073236/http://www.thottbot.com:80/?set=209. Head, chest and legs should be given +10 each instead of the present +7. Shoulders, gloves, belt and boots should be given +8 instead of the present +5.

Onyxia Blood Talisman with it's current in-game bonus of +8 Defense should be bumped up to +12 as per https://web.archive.org/web/20050525113911/http://thottbot.com/?i=35991.

Heavy Dark Iron Ring should have it's Defense bonus of +5 bumped up to +8 as per https://web.archive.org/web/20050519133612/http://www.thottbot.com:80/?i=37315

Drakeclaw Band of the... suffers from the same issue, having it's Defense value nerfed to post-1.7 values. A data scan from May and Aug 2005 shows the correct value of +6 instead of the nerfed +4. https://web.archive.org/web/20050520195605/http://wow.allakhazam.com:80/item.html?witem=10795

I am unable to find a correct database scan for Core Forged Greaves from pre-1.7 but given the evidence in these previous cases I am sure this item should have a Defense bonus of +6 instead of the current +4, given 4/(2/3)=6.

Sincerely, Oliver.

EDIT: Added Drakeclaw Band.

**Comment by Blackbear123** [comment]
Which means Drakeclaw Band gets nerfed in the ZG patch to the current 4 defense? That is a very good ring. indeed, if you can hit the RNG roll.

**Comment by Omnipollo** [comment]
Yep indeed Blackbear123, I have a tiger +10/+10 and a whale +9/+9 for myself.

**Comment by JosipbrozElysium** [comment]
Should be all corrected. Thank you very much!

For still bugged items please file a bug report for each item!

Best regards!
