### ISSUE TITLE
Stratholme

### ISSUE THREAD

**Issue by Fraerock** [elysium-project/server#1330]
There is some annoying bug on Stratholme during Baroness fight - if a player who is getting MCed gets an overkill damage he dies, but it happens that it only shown in chat, that player died, but he can still walk like still alive, cannot interact with any objects and has to do a relog or two, then it will spawn him at the graveyard normally as a ghost and he can get back to the dungeon. Not sure if it was reported or being adressed, but as the players gear up it happens more and more frequently. Usually to proc that warriors executing their target, but we managed to do a killing blow without such finishers just yesterday. Can make some video i guess if it's necessary.

**Comment by martinjlowm** [comment]
Should be fixed by #1111

**Comment by StadenElysium** [comment]
Fixed in the next core update.
