### ISSUE TITLE
Animated Chain Necklace not dropping from Stratholme (Ramstein)

### ISSUE THREAD

**Issue by meeaf** [elysium-project/server#1331]
It seems like the new loot in Stratholme is not dropping correctly and while other items like the crimson felt hat has been reported as an issue, i can not seem to find that the Animated Chain Necklace has been reported before.

It should drop from Ramstein and proof of it being added in patch 1.4 can be found here: http://wowwiki.wikia.com/wiki/Animated_Chain_Necklace

Thanks for your time

**Comment by Sabre142** [comment]
Correct, make sure to check realmplayers before spending time for new items

http://realmplayers.com/ItemUsageInfo.aspx?realm=Ely&item=18723

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!
