### ISSUE TITLE
balance of light and shadow complete. but no turn in available 

### ISSUE THREAD

**Issue by Desalous** [elysium-project/server#1334]
I completed my quest last night for my benediction staff (after about maybe 6 tries) quest giver yells the peasants have been saved ( have screen shot) quest only said completed in my logs after logging out(have screen shot if needed). but the quest giver has no option to turn in the quest. It bums me out because this is literally hands down my favorite item in the game. got both eyes and completed the quest all in one night ( I want it that bad) Is there anything I can do about this issue? P.S. thank you for putting the quest in the game. most private servers skip that. was very nostalgic thank you for that! but please help fix this quest I really want the staff and I really don't want to have to repeat the quest again in the process.

**Comment by JosipbrozElysium** [comment]
Done. Should be corrected on the next update.

Best regards!

**Comment by Desalous** [comment]
I love you 😭
