### ISSUE TITLE
Elysium 1.4/1.5 : Maiden's Circle has wrong stats

### ISSUE THREAD

**Issue by Mingrien** [elysium-project/server#1335]
"Maiden's Circle" should have been updated in the last patch. It should have 18 Spell Power! 
Proof: Archive picture taken, May 2005, Patch 1.5 was released in June 2005
Link to Archive: http://web.archive.org/web/20050507081352/http://wow.allakhazam.com:80/item.html?witem=13001
Patch release days i compare to the Archives to get knowledge about the correct stats:
http://wowwiki.wikia.com/wiki/Patches/1.x

**Comment by JosipbrozElysium** [comment]
Done
