### ISSUE TITLE
[Elysium] Horn of the Frostwolf Howler price discounts being wrongly applied

### ISSUE THREAD

**Issue by deskys** [elysium-project/server#1338]
On Elysium server--
The initial price of 100g should be reduced by 10% from both the honored and r3 discounts. Instead, only one of the discounts is applied, which results in a final price of 90g.
http://imgur.com/a/k8m1Q

**Comment by Sabre142** [comment]
Think the rank 3 discount only applies to Orgrimmar, Undercity, Thunderbluff and Darkspear Trolls factions.

**Comment by thepparker** [comment]
R3 discount only applies to faction NPCs
