### ISSUE TITLE
Elysium 1.4/1.5 Transmute: Arcanite has 48 h cooldown!

### ISSUE THREAD

**Issue by Blackbear123** [elysium-project/server#1340]
I just learnt the transmute on my 35 dwarf priest a few days ago, the first transmute and the second both had a 48 hour cooldown. I am over 280 alchemy. 
Char name: Vulma (35 dwarf priest)

**Comment by Kolmarwow** [comment]
this is how it's  supposed to work. arcanite transmutes have a 2 day CD, and elemental transmutes (fire -> earth and things like that) have a 1 day CD.
