### ISSUE TITLE
Nightfall should be 25% proc rate, Nightfall is meant to have a higher proc than Thunderfury and is proccing MUCH less than thunderfury

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1342]
2006 link suggests nightfalls proc is up about 25% of the time
http://wow.allakhazam.com/forum.html?forum=243&mid=11607605822840518

Proof Nightfall 12 hits tested today
https://youtu.be/yL6lcxVuX48

thunderfury proccing on every 4th hit
https://youtu.be/OeeeQKU-Xh8

Thunderfury has a proc of 18% yet procs more than nightfall does per swings (not swing speed time)

Nightfall (the two hand) has 2% higher proc rate than thunderfury and nightfall is not proccing at 25% proc

I have swung 11 times and not a single proc was given that day

Yet ...Thunderfury is proccing on nearly every 4th swing maximum

Fix: Raise nightfall to 20-25% proc (the 2 hand sword)
at the moment Nightfalls proc rate is closer to 10%

**Comment by Picajzla** [comment]
you do realize that RNG is a major factor at only 12 hits? I'd suggest testing it properly and swinging cca 200 times to have decent amount of test samples. With 10 samples you can be unlucky and get less procs than expected or lucky and get more than expected. With 200 swings luck factor is reduced to minimum and if the difference in proc is still way off you can make this statement

**Comment by Haiwuu** [comment]
You keep linking that kronos bug report like its a reputable source for proc rates.

**Comment by Mostprovidedlinks** [comment]
Yet I have linked proof showing it is up around 25% of the time.

**Comment by Mostprovidedlinks** [comment]
Thunderfury was stated to be 30% then nerfed to 20% in 2006 on old thottbot 
Nightfallis stated to have a 25% proc chance
