### ISSUE TITLE
Elysium 1.4/1.5 "Briarwood Reed" incorrect stats

### ISSUE THREAD

**Issue by Mettyman** [elysium-project/server#1346]
Briarwood reed should have 29 spell damage!

Archive from May 2005:
https://web.archive.org/web/20050529023958/http://wow.allakhazam.com:80/item.html?witem=12930

Patch 1.5 came out AFTER May 2005, it came out June 7th 2005:
http://wowwiki.wikia.com/wiki/Patches/1.x

This means that Briarwood Reed should have had 29 spell power since patch 1.3 at least.

**Comment by JosipbrozElysium** [comment]
Fix will be applied on the next maintenance (today at 12:00 CEST)!

**Comment by eron-elysium** [comment]
Maiden's Circle (+18 spell damage), Songstone of Ironforge (+18 spell damage), Robe of the Archmage (+40 spell damage), and many others have also need to be changed to have correct stats.

From the 1.4 Patch Notes:

"+Spell damage and +Healing effects have been increased in effectiveness to make them more attractive to players. Effects that increased damage and healing done by all magical spells received the largest increase, especially if the previous amount was small. We also fixed a couple bugs relating to these effects."

Do you need me to go in an tell you the entire list of items and exactly which stats they should have?
