### ISSUE TITLE
Pickpocketed lockboxes contain no grey items

### ISSUE THREAD

**Issue by ad154** [elysium-project/server#1348]
I was pickpocketing in BRD before the shutdown, and was receiving occasional boxes. Cannot remember exact name, Strong Lockbox?
They often had a grey item in it, eg: http://db.vanillagaming.org/?item=24282

But after the reset, the boxes either contain a white item (like they previously did), or nothing at all.

**Comment by Turto29** [comment]
Was pickpocketing RFK after the reset and I had the same issue

**Comment by Phoosy** [comment]
http://db.vanillagaming.org/?item=16883 has been reported to be doing the same.

**Comment by ad154** [comment]
@JosipbrozElysium Do you need any more information about this bug? Let me know what is required to progress this out of "QA Denied".

**Comment by gjcgl** [comment]
ye，i noticed it too ,after the reset.

**Comment by JosipbrozElysium** [comment]
Can you provide some evidence that this is correct behavior? Based on the ID and on this info: http://wowwiki.wikia.com/wiki/Rogue%27s_Diary the diary should drop in a way later patch, possibly 1.10 or 1.11!

I thought I had left a comment here before though, sorry for that!

Best regards!

**Comment by ad154** [comment]
Hmm not sure if the behaviour before the recent patch was correct or not, but it was definitely dropping grey items. Let me do some looking.

**Comment by ad154** [comment]
It looks like you are correct, going through item history in WBM and allakhazam, all of the grey items that were dropping out of these boxes, were only introduced in 1.12. I don't know what (if anything) used to drop from these boxes, didn't play rogue back then.

Here is the info about the items and the first time they are seen:
Coarse Snuff
First seen August 23rd, via a comment in allakhazam
http://web.archive.org/web/20071026083946/http://wow.allakhazam.com:80/db/item.html?witem=24231

Shabby Knot
First seen August 23rd
http://web.archive.org/web/20071104175537/http://wow.allakhazam.com:80/db/item.html?witem=24232

Rogue's Diary
2006-08-22 22:03:07	Initial Entry
http://web.archive.org/web/20080314130010/http://wow.allakhazam.com:80/db/itemhistory.html?witem=24282'

Carved Ivory Bone
Posted: Aug 23rd 2006 1:29pm
http://web.archive.org/web/20071030052704/http://wow.allakhazam.com:80/db/item.html?witem=24281

Humanoid Skull
Posted: Sep 29th 2006 2:47am
http://web.archive.org/web/20071111042121/http://wow.allakhazam.com:80/db/item.html?witem=27729

**Comment by JosipbrozElysium** [comment]
Alright, then. Then it's confirmed that it was bugged so far. Thank you very much for the provided links, They might just come in handy for us now.

Closing.

Best regards!
