### ISSUE TITLE
[Elysium PvP] Rosewine Circle - No Stats whatsoever

### ISSUE THREAD

**Issue by Hobrow** [elysium-project/server#1349]
Since the latest 1.4/1.5 Update Rosewine Circle http://db.vanillagaming.org/?item=13178 doesn't have any Stats anymore. Had about 7 Agi and 16 Spi. Should be updated to the stats as seen in the link above.

**Comment by JosipbrozElysium** [comment]
The stats were updated in Patch **1.10**, as seen in this source: http://wow.gamepedia.com/Rosewine_Circle

Best regards!
