### ISSUE TITLE
Rune of the Dawn shouldn't be in game on Elysium PvP

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#1353]
Only the melee trinket should be in:

http://web.archive.org/web/20050119152717/http://wow.allakhazam.com:80/db/quest.html?wquest=5213

The melee trinket should not be able to grant you scourgestones until Patch 1.6:

>Patch 1.6.0 (12-Jul-2005): The Seal of the Dawn trinket now counts as though you were also wearing an Argent Dawn Commission trinket. - http://wowwiki.wikia.com/wiki/Seal_of_the_Dawn

The caster trinket is added in Patch 1.7:

>Patch 1.7.0 (13-Sep-2005): The Argent Dawn quest "The Active Agent" now offers a choice of rewards: Seal of the Dawn and Rune of the Dawn. - http://wowwiki.wikia.com/wiki/Quest:The_Active_Agent

**Comment by thepparker** [comment]
The same quest rewards both items, it makes sense to have them both available at once

**Comment by Sabre142** [comment]
@thepparker Makes the game easier, especially how strong the caster trinket it (flat 48 damage increase similar to Beast Slaying).
