### ISSUE TITLE
Legplates of the Eternal Guardian doesn't give +Def

### ISSUE THREAD

**Issue by JynEly** [elysium-project/server#1356]
As stated in the title Legplates of the Eternal Guardian does not give +22 Def as it should. Wearing them does not increase my Defense rating in the Skills tab. The item description also shows it as a Use effect instead of and Equip bonus, which might be the problem.
As a side note Deathbone Chestplate has the mana per 5 as a Use effect, which I suspect to be a mistake as well. This might make the mana per 5 effect not work either, but I wouldn't know as a warrior.

**Comment by mehailz** [comment]
I can second this. Same for me.

**Comment by kyle21b** [comment]
I can third this.

**Comment by StadenElysium** [comment]
This should be fixed.

**Comment by thepparker** [comment]
Fixed
