### ISSUE TITLE
After update, I lost my Dragonskin Cowl of Shadow Resistance

### ISSUE THREAD

**Issue by Citano** [elysium-project/server#1357]
Just logged on after work and my character Mildah is missing her Dragonskin Cowl of Shadow Resistance.
https://i.gyazo.com/66826bd57cfaa9ad282cd0ef9931edd6.jpg

Not sure if this is item specific or if there are others whom also have lost their items after today's update.

**Comment by StadenElysium** [comment]
This item was not supposed to be available on Elysium yet.

**Comment by Citano** [comment]
Then you should compensate those who had these for so long. The item has been ingame since server launch (half a year) without either of you doing anything about it.

**Comment by Sabre142** [comment]
Just get a dreamweave circlet.
