### ISSUE TITLE
Elysium 1.5 - T1 Mage Gloves/T2 Mage Pants Incorrect stats

### ISSUE THREAD

**Issue by Reebs89** [elysium-project/server#1359]
Arcanist Gloves currently missing +SP on Elysium 1.5
http://db.vanillagaming.org/?item=16801

Netherwind Pants currently missing 1% Spell Crit on Elysium 1.5
http://db.vanillagaming.org/?item=16915

**Comment by JosipbrozElysium** [comment]
Both items are correct on Elysium. 
More accurate sources:
https://web.archive.org/web/20050318171722/http://wow.allakhazam.com:80/db/item.html?witem=16915
https://web.archive.org/web/20050318171022/http://wow.allakhazam.com:80/db/item.html?witem=16801

Best regards!
