### ISSUE TITLE
Defias set bonus +1 daggers: Bug with weapon skill

### ISSUE THREAD

**Issue by adura90** [elysium-project/server#1361]
Hi, I recently acquired the complete defias set during a deadmines run. The 3rd bonus of the set is +1 to dagger skill, but when my character leveled up and my dagger skill went up, it would not go above 94/95(+1). Even now after removing the defias set, and having only 94/95, my skill still wont go up to 95/95. I've attacked hundreds of times, so I think its bugged... Maybe someone should look into this?

**Comment by sknnbones** [comment]
In my experience (on my lv19 twink warrior) I have never hit weapon cap, even after weeks and weeks of playing on my lv19.

**Comment by thepparker** [comment]
You don't gain weapon skill in PVP, so if that's all you're doing it will never reach cap.

**Comment by adura90** [comment]
No, I wasn't PVPing. Now, I'm level 20 and still have the same issue...
