### ISSUE TITLE
[Bonereaver's Edge] doesen't works proper, after the "Fix".

### ISSUE THREAD

**Issue by zallmocse** [elysium-project/server#1363]
Before "The Fix", [Bonereaver's Edge] procced normally, with 3 stacks on you.
At this moment, you only get 1 buff/de buff on you, that meens you only ignore 700 armor.
When proc's again, doesen t stack, like how it will be normal, just refresh the de buff that u already have. So, instead of ignoring 1400 or 2100 armor, u are just stayin at 700.
Can you fix that, asap ?

Thanks.

**Comment by Persaer** [comment]
Thanks for bringing up the Bonereaver's Edge not functioning as it's supposed to in this patch. While we're discussing this, please nerf Bonereaver's Edge to function like it's supposed to function in this patch. 


First, proof that the effect initially did not function as a buff on the weapon user, but rather as a debuff proc on target:
https://www.engadget.com/2011/08/23/wow-archivist-patch-1-10-storms-of-azeroth/
http://wowwiki.wikia.com/wiki/Patch_1.10.0
>The Bonereaver's Edge's triggered effect has been changed. Instead of lowering your victim's armor, it will cause you to ignore a portion of your victim's armor. Its triggering rate was substantially increased as well as the magnitude of the effect. 

Here's the tooltip from back in the day. Notice the absence of "stack up to 3 times"
https://web.archive.org/web/20060612222558/http://wow.allakhazam.com:80/db/item.html?witem=17076

**Comment by zallmocse** [comment]
But the Chance on hit says "ignore enemys armor" not " decrese enemy armor", so that is working good, since i have the buff on me, enemy doesen t have any de buff on him. 
It s just, the buff on me refreshes, but stay at 1 stack, instead of 2 or 3. So, basically, it s ignoring only 700 armor.
Or.. can be a visual bug? How can I test that? Cause we don t talk about "decrease armor" so I can t really test that by myself.

**Comment by zallmocse** [comment]
![wowscrnshot_070617_013615](https://user-images.githubusercontent.com/29930940/27888036-a523e844-61ec-11e7-9cf9-95af29dc17ab.jpg)

**Comment by Persaer** [comment]
What the chance on hit says is fairly irrelevant if a patch note directly states in which way the functionality was changed. 
Your picture has no sort of patch timestamp in it, so it shouldn't be regarded as evidence for either argument.

**Comment by Itembugs** [comment]
yes fix please

**Comment by thepparker** [comment]
The proc that existed before 1.10 no longer exists in the game, therefore it cannot be used instead of the current effect. The stack limitation is the closest we can get to the original behaviour.

Yes, it has its advantages (in that you reduce all your targets armour when AoEing), but that's unfortunately something that we have to deal with.

**Comment by tellio02** [comment]
If youre going off the old proc then Bonereaver's edge is missing +16 Stamina? https://web.archive.org/web/20060612222558/http://wow.allakhazam.com:80/db/item.html?witem=17076

**Comment by Persaer** [comment]
No, that's just me accidentally linking a wrong timestamp. 

https://web.archive.org/web/20060215114712/http://wow.allakhazam.com:80/db/item.html?witem=17076
These are the stats on the item in 1.9, which is AQ patch.

**Comment by sun23563262** [comment]
Both Please immediately repair
For 16 endurance We also want to restore the original special effects

**Comment by zallmocse** [comment]
So ? Can I receive an official answer or something? I meen.. it hurts, for some reason. That Chance on Hit it s kinda everything at that weapon.

**Comment by sun23563262** [comment]
Hope the official will give us a reply, how to solve this problem? Our online waiting to be processed

**Comment by wodechengbao** [comment]
Hope the official will give us a reply

**Comment by wodechengbao** [comment]
fix please

**Comment by fgsfdss** [comment]
https://elysium-project.org/bugtracker/issue/2292

**Comment by wodechengbao** [comment]
When will the problem be solved? Can you give me an answe

**Comment by sun23563262** [comment]
16, without stamina, the stunt did not recover, equivalent to 2 successive losses.

**Comment by wodechengbao** [comment]
fix please

**Comment by taurenrogue** [comment]
fix what?
https://web.archive.org/web/20060612222558/http://wow.allakhazam.com:80/db/item.html?witem=17076

**Comment by sun23563262** [comment]
Has anyone come to deal with the problem?

**Comment by kampeador** [comment]
Strange...
I don't know which revision are used on live servers currently, but I can't reproduce this bug on my local test server(dev branch). I've killed some bears in Winterspring with auto-attack only and got 3 stacks.
https://ibb.co/bOuzFF

**Comment by wodechengbao** [comment]
Can you tell us when we can get the normal patch？

**Comment by thepparker** [comment]
1.11

**Comment by wodechengbao** [comment]
next week?

**Comment by sun23563262** [comment]
@thepparker  16 why is the stamina gone?
