### ISSUE TITLE
Thorium brotherhood

### ISSUE THREAD

**Issue by Reefah** [elysium-project/server#1365]
Several quests that were supposed to be added in 1.5 are missing from the Thorium Brotherhood questhub in Searing gorge, normally given by Master Smith Burninate:

Restoring Fiery Flux Supplies via Heavy Leather
Restoring Fiery Flux Supplies via Iron

Right now it is only possible to gain rep with the Kingsblood version of this quest.
The quests in searing gorge also reward lower rep than they're supposed to.

**Comment by Reefah** [comment]
Should've added, this is on the Elysium server, alliance side.

It might be smart to double check if the quest 'Gaining Acceptance' from the same NPC is available at honored reputation too.

**Comment by StadenElysium** [comment]
These quests weren't added until patch 1.7.0.

```
Two new quests have been added to Thorium Point in the Searing Gorge for Thorium Brotherhood reputation turnin for players with neutral faction. You will now be able to turn in Iron and Heavy Leather to increase your reputation with the Brotherhood.
```
