### ISSUE TITLE
Dark Iron Helm is not honored, but revered (big issue for new guilds)

### ISSUE THREAD

**Issue by ssishtar** [elysium-project/server#1367]
Dark Iron Helm should be honored, not revered and this is basically fucking up all the new guilds who try to get past Ragnaros/ Onyxia. There was never ever any Dark Iron Helm at revered, but at honored. Please fix.

http://wow.gamepedia.com/Classic_reputation_rewards#Thorium_Brotherhood

**Comment by StadenElysium** [comment]
Already appears to be honoured on Darrowshire and Anathema. This item isn't available on Elysium as it wasn't added until 1.6.
