### ISSUE TITLE
Dark Advisor's Pendant drop chance

### ISSUE THREAD

**Issue by schmelzgesic** [elysium-project/server#1368]
I notice from one of the commits in the Itemization repo:
-- Dark Advisor's Pendant ID: 18691
DELETE FROM reference_loot_template where item = 18691;
INSERT INTO reference_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES (323238, 18691, 0, 1, 1, 1, 0);
so it's not going to drop in this patch on Elysium?
http://web.archive.org/web/20060629164703/http://wow.allakhazam.com:80/db/item.html?witem=18691
The earliest comment is 11/10/2005, one day after 1.8.0. I'm checking the patch notes but nowhere does it mention there's any itemization changes, was it an undocumented change?
While I do understand wowwiki is not a good proof for the team, but it does say it was added in 1.4.0.
Can I get some clarification?

**Comment by thepparker** [comment]
It drops
