### ISSUE TITLE
Netherwind Pants missing crit, spirit too high

### ISSUE THREAD

**Issue by dcish** [elysium-project/server#1370]
http://db.vanillagaming.org/?item=16915 Have 12 extra spirit in game currenrtly and are missing 1% crit damage.

If you look at http://wow.gamepedia.com/Netherwind_Regalia, we can see that patch notes listing stat changes are only at 1.5 all the way until cata.

I believe they're supposed to look like this: https://web.archive.org/web/20060206075503/http://wow.allakhazam.com:80/db/item.html?witem=16915

but are being listed like this:

https://web.archive.org/web/20051224015417/http://wow.allakhazam.com:80/db/item.html?witem=16915

I can't find anyplace else listing where in patchnotes they would have been changed except 1.5. Thanks!

**Comment by Kolmarwow** [comment]
this is not correct, there were 2 points in vanilla (that i know of, maybe more) where the T2 items were updated. once in 1.4/1.5, and again in 1.9 (AQ patch), which is what the db.vanillagaming version is based of. 

source: https://web.archive.org/web/20051214044047/http://wow.allakhazam.com:80/db/item.html?witem=16915

"The new patch will change all of this. 

Netherwind Pants: 
Old Stats: 26 int, 27 spi, 8 agi, 3 nature / 17 frost resist, +27 frost dmg 
New Stats: 16 sta, 27 int, 17 spi, 10 arcane / fire resist, +30 all spell damage

Reference:: 
Test Server Forum 
1) http://forums.worldofwarcraft.com/thread.aspx?fn=wow-realm-test&t=22431&p=1&tmp=1#post22431 

Mage Forum (Alcaras) 
2) http://forums.worldofwarcraft.com/thread.aspx?fn=wow-mage&t=184298&p=1&tmp=1#post184298"

Posted on May the 30th 2005, a week before 1.5 went live on the 7th of June 2005 (he got this information from the test server which had 1.5 on it).
