### ISSUE TITLE
Fiery Core returns only award 200 reputation instead of 500. (Elysium)

### ISSUE THREAD

**Issue by Ihsm** [elysium-project/server#1372]
Returned a bunch of fiery cores @ BRD, and only after noticed that the amount of reputation received was incorrect. Only got 200 instead of 500.

**Comment by JosipbrozElysium** [comment]
Can you please provide some proof/references in this bug report that support the claim that this is bugged? We'd really appreciate that!

Best regards!

**Comment by Ihsm** [comment]
What kind of proof can I provide? I started at 0/6000 friendly, returned 30 Fiery cores, and I am now 0/12000 honored. Unfortunately I didn't document it anyhow. Character is Ihsm of guild Blood Pressure.

**Comment by Ihsm** [comment]
Would it be valid proof if I returned one more and screenshotted it?

**Comment by Ihsm** [comment]
http://imgur.com/a/e6aOt

**Comment by JosipbrozElysium** [comment]
I mean, proof that it should reward 500 rep instead of 200!

**Comment by Ihsm** [comment]
http://www.wowhead.com/quest=6643/favor-amongst-the-brotherhood-fiery-core

**Comment by Ihsm** [comment]
All guides etc say it should be 500

**Comment by JosipbrozElysium** [comment]
Sorry, but your source isn't accurate. We're talking here about Patch 1.5 after all, not Patch 7.2.5, where things have changed drastically.

Best regards!

**Comment by Ihsm** [comment]
(y)
