### ISSUE TITLE
Necromantic Band has no stats

### ISSUE THREAD

**Issue by farrodin** [elysium-project/server#1375]
Necromantic band dropped and has no stats:
![wowscrnshot_070517_211254](https://user-images.githubusercontent.com/29959106/27928954-6c0b83be-6291-11e7-927a-990959cae7d2.png)

Should have 8hp5: http://db.vanillagaming.org/?item=18760

**Comment by Citano** [comment]
8 hp/5 was added in patch 1.10.

However, it should possibly have 5 hp/5 at the moment until patch 1.10.
Source: http://web.archive.org/web/20060307185528/http://wow.allakhazam.com:80/db/mob.html?wmob=14516

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
