### ISSUE TITLE
Oily Blackmouth

### ISSUE THREAD

**Issue by sziebe** [elysium-project/server#1377]
Oily Blackmouth can't be fished from common lower level zones: Darkshore, Westfall, Wetlands, etc.  Some are having limited success in Feralas or Desolace. This fish is used for low leverl alchemy and for trade, and in the past was available in all locations listed here https://elysium-project.org/bugtracker/issue/2252 
This wasn't always an issue.  Not a problem on Nostralius, or early Elysium.  Was definitely not an issue in original WoW 1.12, as someone who played.  Please check fishing loop tables for bugs, perhaps since pools were removed, as others suggested.

**Comment by thepparker** [comment]
Duplicate
