### ISSUE TITLE
Witch Doctor Unbagwa

### ISSUE THREAD

**Issue by Kraameber** [elysium-project/server#1378]
Someone started his escort quest with bringing him 10 Gorilla Fangs. He killed the first 3 gorillas, but when the next 6 gorillas spawned they got pulled by someone else, and he ran away bringing the gorillas away from the witch doctor. And the witch doctor reset running back to his initial point where you can start the escort quest, but now you cant talk to him and start it. Can you please reset him, so we can start the escort quest again

**Comment by StadenElysium** [comment]
Open a GM ticket.
