### ISSUE TITLE
[Elysium PvP]  R14 Gear stat changes should be made to the existing items rather than new versions being added. 

### ISSUE THREAD

**Issue by Persaer** [elysium-project/server#1382]
Hello! 
As a staff member announced (https://forum.elysium-project.org/topic/48412-r14-and-pvp-updates/?do=findComment&comment=406166) the Dev team apparently plans to not update existing Rank 14 gear when the stat update hits. 
Staff quote: 

>  You must be Rank 14 at the time of purchase to obtain the new PvP Weapons / Gear updates 

> This gear will be Updated at the Vendor... Not on the items you already own 

**Reasoning given by Staff (quote referring to R14 gear):** 

> The PvP gear originally was updated at the Vendor ONLY on Retail.  Players have complained about this not being the case and wanted a more Blizz-like feel so we changed it back to the original [...]

However, this was not the case on retail. First of all, they were updated in Patch 1.6, 12 July 2005.  
Source: http://wowwiki.wikia.com/wiki/Patch_1.6.0 + https://www.engadget.com/2011/07/12/wow-archivist-world-of-warcraft-patch-1-6/

Here's the r14 weapon stats in May 2005. (this is before 1.6).
https://web.archive.org/web/20050529103912/http://wow.allakhazam.com:80/item.html?witem=18877

Here's the same weapon ID, stats in June 2006 (after 1.6, they are not changed at any point inbetween)
https://web.archive.org/web/20060629120918/http://wow.allakhazam.com:80/item.html?witem=18877

 
Notice of course same weapon ID. Notice also (by digging through https://web.archive.org/web/20060613141358/http://wow.allakhazam.com:80/dyn/items/wname8.html) that there are never, at any point of the game, two different sets of r14 weapons (buffed and unbuffed) in the game.

**Comment by Sabre142** [comment]
If it has the same item ID, it will be updated.

**Comment by StadenElysium** [comment]
What Sabre142 said.
