### ISSUE TITLE
about Thorium Brotherhood

### ISSUE THREAD

**Issue by capsules** [elysium-project/server#1385]
there is only one rep quest at Searing Gorge. Restoring Fiery Flux Supplies via Kingsblood.
i remember that it should be 3 quests there. Restoring Fiery Flux Supplies via Kingsblood, Restoring Fiery Flux Supplies via Iron, Restoring Fiery Flux Supplies via Heavy Leather. 
thats all. can you fix it?

**Comment by StadenElysium** [comment]
Duplicate of https://github.com/elysium-project/server/issues/1365.
