### ISSUE TITLE
[Elysium] Sulfuron Ingot droprate incorrect?

### ISSUE THREAD

**Issue by Braxalones** [elysium-project/server#1393]
The droprate on Sulfuron Ingots dropped from Golemagg the Incinerator seems incorrect since out of 19guilds  only 1guild have got it to drop (shown on realmplayers). And since the droprate should be around 30%, there should've been around 6drops. This can just be due to unlucky RNG but since it's quite a big gap it seems kinda fishy.

**Comment by druidish** [comment]
Where are you seeing 30%?

https://web.archive.org/web/20060619104543/http://wow.allakhazam.com:80/db/item.html?witem=17203

**Comment by Braxalones** [comment]
http://db.vanillagaming.org/?item=17203

**Comment by druidish** [comment]
Another private servers database isn't a valid source.

**Comment by Braxalones** [comment]
From what private server then? Is it Feenix?
