### ISSUE TITLE
[Elysium] Items with +5 Defense pre-hotfix had their defense wrongly set at +7 with last wednesdays patch.

### ISSUE THREAD

**Issue by Omnipollo** [elysium-project/server#1394]
Hi!

In my earlier issue submission [https://github.com/elysium-project/server/issues/1329](url) I provided sources and quotes as to why items with +5 defense introduced in patch 1.4/1.5 should have their defense values increased to +8. These items are Pauldrons of Might, Gauntlets of Might, Belt of Might, Sabatons of Might and the Heavy Dark Iron Ring. Instead of the intended +8 Defense these items were given a +7 Defense bonus.

Spell-ID pre-fix seem to be 13383, wrongly given Spell-ID is 13385 or 13386, intended Spell-ID is 13387.

Correct stats pre-ZG nerf: [Heavy Dark Iron Ring](https://web.archive.org/web/20050519133612/http://www.thottbot.com:80/?i=37315) , [Might set](https://web.archive.org/web/20050729085314/http://wow.allakhazam.com:80/db/itemset.html?setid=209)

Big thanks to fixing everything else in my first post, even Onyxia Blood Talisman and Ring of Binding were given their correct defense values!

Sincerely, Oliver.

**Comment by thepparker** [comment]
Fixed
