### ISSUE TITLE
Lifesteal weapon enchant proc rate bug. ELYSIUM PVP

### ISSUE THREAD

**Issue by neale111** [elysium-project/server#1396]
Current behaviour: The current proc rate of Lifesteal enchant is incorrect. I have tested and it is bugged.
Elysium pvp.

Correct behaviour: The correct formula should be weapon speed * 7.87 
Weapon speed x 7.87
Weaapon speed multiplied by 7.87

Source: http://rogerkarlsson.com/blogs/wow/lifestealing/
This blog heavily tested lifesteal proc in 2006 showing real datas.
All other sources from 2004 to 2006 confirms it.

**Comment by ItsmeAga** [comment]
what that blog describes is actually the PPM mechanic where lower speeds have a higher procchance
http://wowwiki.wikia.com/wiki/Procs_per_minute

**Comment by supasteed** [comment]
ItsmeAga is correct

**Comment by neale111** [comment]
@ItsmeAga
As the blog says the ppm is 5

**Comment by GuybrushGit** [comment]
Current ppm on Elysium is 6
