### ISSUE TITLE
[Elysium] Herb spawn rates post-AV

### ISSUE THREAD

**Issue by coryo** [elysium-project/server#1400]
Since the patch that fixed the issue with the AV rewards, it appears that the herb spawn rates have reverted to their pre-april 10th state. (see https://forum.elysium-project.org/topic/44067-re-herb-changes-%E2%80%94-anathema-elysium/ where the changes were first announced)

These changes were never on the github as far as I can tell, so was this an oversight in the patching or a deliberate change?

**Comment by Mettyman** [comment]
I can confirm, the herb spawnrates have been heavily reduced in all zones. It's literally a nightmare to pick flowers at the moment. I would greatly appreciate it if this issue is resolved as fast as humanly possible.

Kind regards,
Me

**Comment by martinjlowm** [comment]
While I cannot test it on the live realm, it is as if `POOL_FLAG_MAXLIMIT_SCALING_LINEAR` was set previously and isn't now.

**Comment by eagle132** [comment]
I am surprised there are not more comments on this! I am noticing the severely reduced herb spawns as well.

**Comment by djlax805** [comment]
+1

**Comment by jaffa343** [comment]
This really needs addressing, on Darrowshire I am unable to find herbs, at all

**Comment by coryo** [comment]
It should be fixed on wednesday for Elysium pvp at least.

**Comment by JosipbrozElysium** [comment]
Fixed.
