### ISSUE TITLE
Account selling caught from middleman screenshots

### ISSUE THREAD

**Issue by neale111** [elysium-project/server#1404]
<snip>

**Comment by Sabre142** [comment]
This is the wrong place to post this and you are lacking sufficient proof.

**Comment by Comfarol** [comment]
Tell him to take a screenshot of the character panel, not the inspect screen.

**Comment by JosipbrozElysium** [comment]
Closing this as it's unfitting for this website.
I have noticed that you're reporting this player everywhere, even though you lack any evidence. Spamming this message won't make us ban him.
