### ISSUE TITLE
Frost Runed Headdress [19105] item

### ISSUE THREAD

**Issue by kolokotrolis** [elysium-project/server#1408]
Currently this item is not in the game on Elysium PvP,it should be added and then removed at patch 1.6 according to http://wow.gamepedia.com/Frost_Runed_Headdress. It used to drop from Lokholar the Ice Lord and Ivus the Forest Lord with an approx 20% drop rate.Please fix this,it is the best frost mage helm in this patch.

**Comment by Sabre142** [comment]
It's been fixed and merged

Just needs to be updated on the live server.

https://github.com/elysium-project/server/pull/1120#event-1143673269

I'm not sure if it will drop after 1.5 is over.

**Comment by thepparker** [comment]
Implemented. Will stay in-game for the foreseeable future, as we are running AV in a pre-nerf state.

**Comment by Sabre142** [comment]
It's worth keeping them in forever to entice player pvp.
