### ISSUE TITLE
Lok'delar, Stave of the Ancient Keepers missing 2% crit on Elysium

### ISSUE THREAD

**Issue by Shazec** [elysium-project/server#1409]
As stated Lok'delar, Stave of the Ancient Keepers is missing 2% crit on Elysium server.

Proof: 
http://web.archive.org/web/20050430154330/http://wow.allakhazam.com:80/item.html?witem=18715
Archive of this item from April 2005 from patch 1.4
Elysium is now on patch 1.5
Patch 1.6 was added to retail on 12 July 2005
http://wow.gamepedia.com/Patch_1.6.0

**Comment by jessemon** [comment]
Rhok'delar, Longbow of the Ancient Keepers
Is also missing its 1% crit.

http://db.vanillagaming.org/?item=18713
http://web.archive.org/web/20050508114849/http://wow.allakhazam.com:80/item.html?witem=18713

**Comment by Derpyous** [comment]
Can confirm. Serious annoying.

**Comment by thepparker** [comment]
Fixed
