### ISSUE TITLE
Sithilus quest bugged

### ISSUE THREAD

**Issue by Pogapoe** [elysium-project/server#1411]
Seems that every Sithilus Quest seems to be bugged, such as the Deadly Venom quest- killed 30-40+ mobs without a single item drop-other players have also confirmed this. 
Note: It's not just this quest but every quest so far

**Comment by StadenElysium** [comment]
This quest isn't supposed to be available until patch 1.8.

**Comment by Pogapoe** [comment]
So why am I able to even pick it up? Another player even said he was able to complete it although it seems to be bugged for me and many others

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
