### ISSUE TITLE
Darrowshire BWL( Anathema aswell? ) , Goblin Technicians. ( Fix this before u release bwl on elysium )

### ISSUE THREAD

**Issue by Lisbuxx** [elysium-project/server#1413]
Goblin technicians are broken in a couple of ways.

#1 How it works ½ of the time: Goblin technicians attack the highest person on their threat table together. [ Correct ]
     How it works other ½ of the time : Goblin technicians are permanently aggroed to the person who pulled them and ignore threat until that person is dead. [ Wrong ]

For somereason i cannot create a highlight out of the video material i have proofing this but the fact alone that the goblin packs work inconsistently should suffice.

#2 How it works 100% of the time : Goblin technicians will start "harvesting" a dead players corpse and get stuck on it if there is no other players nearby.
 Abusable easily by : having 1 player pull goblin technicians far away from the raid and dying causing the goblin technicians to stay at that dead player and not go after the raid.

I don't have any proof for this either but i am pretty sure these mobs aren't supposed to stop and hump a corpse while the rest of that linked pack is still being killed. ( dragonkin , orc summoners & spellbinders)

I haven't reported bugs before and i am sorry if i am doing this wrong hopefully you can test this on the PTR or something.

**Comment by Lisbuxx** [comment]
**Bump**

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
