### ISSUE TITLE
Feralas chicken escort quest bugged

### ISSUE THREAD

**Issue by etwiech** [elysium-project/server#1414]
When you start Rescue OOX-22/FE in Feralas to escort the chicken, the first group of mobs to spawn will not despawn if they are not killed, which led to a group of 30 of them standing around and blocking the way for the escort, causing the quest to become impossible.

**Comment by SpaceVector** [comment]
the escort quest in Desolace with the goblin near Maraudine also share the same bug.

**Comment by kampeador** [comment]
Mobs despawn, unless they are in combat. How do you skip them?

**Comment by brotalnia** [comment]
Already fixed, but not pushed to live realms yet. https://github.com/elysium-project/server/pull/817
