### ISSUE TITLE
Druid- Dungeon Set 1 (Tier 0)  Wildheart 6/8 not working

### ISSUE THREAD

**Issue by hederob** [elysium-project/server#1416]
The Wildheart 6/8 set bonus, chance when struck to gain 10 rage, 40 energy, to the wearer, tested it for at least 30 minutes, it never proccs.

**Comment by hederob** [comment]
anyone else can confirm this?

**Comment by GuybrushGit** [comment]
Works in dev. Chance is very low (2%).
