### ISSUE TITLE
Elysium Rogue Lockpicking Fully Broken

### ISSUE THREAD

**Issue by metaknight17** [elysium-project/server#1417]
Before Wednesday's AV item update, lockpicking and pickpocketing was at least a somewhat viable gold farming option for rogues. Since the update though it is completely useless. Here are the issues with lockpicking and pickpocketing that need fixing:
1) junkboxes no longer give gray items
2) if a pickpocketed mob only has silver, it is very difficult to loot this silver due to the loot window closing before the silver is looted
3) percentage of mobs resisting pickpocketing is too high 

Please attempt to correct these issues as pickpocketing is the only viable gold farming method for rogues (whereas rdps/tanks/healers have many)

**Comment by StadenElysium** [comment]
See #1348 for your first point.
