### ISSUE TITLE
[Elysium PvP] "Bartolo's Yeti Fur Cloak" Quest Bug @ Hillsbrad Foothills

### ISSUE THREAD

**Issue by KrsNotFound** [elysium-project/server#1420]
Hello, 
Im currently on the quest called Bartolo's Yeti Fur Cloak, i have all the items in my backpack to complete the quest but it wont complete.

https://i.gyazo.com/13018f22c31036f115f56bd1870ea0f2.jpg

How to proceed?

**Comment by Sabre142** [comment]
You can abandon the quest and retake it to hand it in.
