### ISSUE TITLE
 Onyxia often only dropping 1 item from weapon/book/scale loot group

### ISSUE THREAD

**Issue by kschroeder31** [elysium-project/server#1424]
Since the patch that fixed loot drop percentages, many guilds are only receiving 1 item from the secondary loot group for Onyxia. (the book/collar/weapons/scale group)

Examples:
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=80149
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=80129
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=80123
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=80108
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=80105
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=80507
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=80480

https://www.reddit.com/r/ElysiumProject/comments/6li9w3/they_fixed_onyxia_loot_all_praise_the_loot_god/djurdns/?context=3

 CORRECT BEHAVIOR
There should be 2 items dropped from group #2.

Sources:
http://db.vanillagaming.org/?npc=10184#drop:0+14-13+1
Also, before the loot "fix" on Elysium, everybody was getting 2 items from that table (they were just almost always books)

**Comment by thepparker** [comment]
No, the way it works is there are two loot pools for the special (non-tier) items. One contains Sapphiron Drape, ACG, Eskhandar's and Ring of Binding. The other contains the Shard, Deathbringer and Vis'kag. 

The former drops 100% of the time, meaning you are guaranteed to get ONE of those items. The latter only has a 24% chance to drop (8% per item), meaning you only have a 24% chance to get an item from the second pool (making them much rarer).

The two tier pools are separate, and the head is another guaranteed drop on top of them.

VanillaGaming is not an accurate source, and if the pools were implemented as described on there you would be able to roll two weapons, or two books, or two rings, etc., yielding a much higher drop rate than what was seen in Vanilla.
