### ISSUE TITLE
Seal Fate not Awarding Double Combo Points

### ISSUE THREAD

**Issue by sight1989** [elysium-project/server#1426]
I have noticed that not all of my critical hits of combo point giving skills give me double combo points. I have a full 5 points into seal fate. I will try to gather video and update.

**Comment by Harkonnen13** [comment]
got same problem

**Comment by Harkonnen13** [comment]
Ok i solve this shit.  i saved my cache files from my account folder (cache.md5 and SavedVariables.lua.bak) to another place, and let WOW client recreate them. After that my Seal Fate talent works fine again.

**Comment by thepparker** [comment]
Addon issue
