### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by Tharnok** [elysium-project/server#1427]
Hello,

In Durotar near the Valley of Trials is an ooze covered Gold Vein, and the Respawnrates of Copper (all Mineals? I don´t know because i stuck on copper) are too low i my opinion. It is impossible to farm, an I know it was not as hard back in 2006 as it is today.

Best Regards

Tharnok

**Comment by Pisshead** [comment]
I think it's only a low level thing due to overfarming (god knows why anyone would need so much copper), because for high minerals it's completely the other way around (see post:"too many mining nodes in one spot"
