### ISSUE TITLE
Seal of Command Parry / Dodge / Block

### ISSUE THREAD

**Issue by Hsekr** [elysium-project/server#1428]
Seal of command procs currently can be Parried / Dodged / Blocked witch is incorrect 

Seal of command should only be resistable by higher than player level targets 
Source http://wowwiki.wikia.com/wiki/Patch_1.3.0

**Comment by theloras** [comment]
that change was reverted on the 1.3 PTR before going live due to a cascade of complaints from Ret Paladins - SoC is subject to Block / Dodge / Parry and working as intended

**Comment by Hsekr** [comment]
Interesting. Then should seal of command procs benefit from hit ? as it is with 9% hit i still get dodge/parry/block ? also should it benefit from human racial if i am using a sword ? ( gonna research on that now )

**Comment by thepparker** [comment]
Working as intended
