### ISSUE TITLE
Dire Maul - Dusty tome cannot be looted in combat - DARROWSHIRE

### ISSUE THREAD

**Issue by jaffa343** [elysium-project/server#1430]
BUGGED BEHAVIOR:
The dusty tomes in Dire Maul cannot be looted whilst in combat.

CORRECT BEHAVIOR:
The dusty tomes in Dire Maul are able to be looted whilst in combat.

SOURCES:
http://vbd.fr.yuku.com/topic/177/farming-forors-compendium-and-all-class-specific-books#.WVmdTITyuHs

http://forums.avowry.com/viewtopic.php?t=1641&sid=b87ccadf415d2248c797d95191a16a23

(both links are from 2005 and detail the method in DM: West)

Here is a link to a re-upped video from 2012 of the video mentioned in both links "dmfarmin101" as the host sites no longer exist:

https://www.youtube.com/watch?v=G-g9GcWJqpA

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
