### ISSUE TITLE
Drop rate on animated chain necklace is not proper

### ISSUE THREAD

**Issue by Roflkopterr** [elysium-project/server#1433]
All Vanilla data bases I see show animated chain necklace having a HIGHER drop rate than cape of the black baron. I have now seen FOUR capes drop in the last 4 nights and ZERO necks. Can you please fix this I Am sick and tired of running Strat UD every night.

**Comment by thepparker** [comment]
https://en.wikipedia.org/wiki/Random_number_generation

**Comment by Roflkopterr** [comment]
So how many runs would someone have to do before you admit theirs a problem?

**Comment by JosipbrozElysium** [comment]
Unfortunately, in this state, this report doesn't help anyone. Please provide a proper description and some concrete evidence that the current behavior is wrong. 
See this: https://github.com/elysium-project/server/blob/development/docs/Bug%20Reporting.md and try again. Closing.

Best regards!
