### ISSUE TITLE
Thorium Brotherhood Rep Quests

### ISSUE THREAD

**Issue by Gibi-gibii** [elysium-project/server#1435]
Horde Side
Thorium Brotherhood Rep quests:
Restoring Fiery Flux Supplies via Heavy Leather
Restoring Fiery Flux Supplies via Iron
Restoring Fiery Flux Supplies via Kingsblood

The questgiver is currently only giving rep via Kingsblood, the other quests are not visible

**Comment by Barry031** [comment]
Same on ally side, 100% done all the quests in SG and i only get the
 "Restoring Fiery Flux Supplies via Kingsblood"
My guild mate did the others a few months ago so it seems like this "changed" recently.

**Comment by ripstein** [comment]
I can confirm I completed Neutral to Friendly via Restoring Fiery Flux Supplies via Iron on my Horde 60 rogue pre patch 1.5. I am currently looking for the same quest on my 55 priest and only Restoring Fiery Flux Supplies via Kingsblood is available.

**Comment by Voff89** [comment]
Yep. This is currently not available and should be.

**Comment by lordhelmchench** [comment]
Was before Patch 1.5
<img width="253" alt="whattheflux" src="https://user-images.githubusercontent.com/17217403/28636175-9d1edc1a-723d-11e7-9e08-b3998b4b95b6.PNG">

**Comment by Phoosy** [comment]
This is intentional. Patch 1.7 introduced the Iron and Heavy Leather quests. http://wow.neoseeker.com/wiki/Patch_Notes
>Two new quests have been added to Thorium Point in the Searing Gorge for Thorium Brotherhood reputation turnin for players with neutral faction. You will now be able to turn in Iron and Heavy Leather to increase your reputation with the Brotherhood.

Non-issue. Close.
