### ISSUE TITLE
Rich Thorium Veins in ZG should be Hakkari Thorium Veins

### ISSUE THREAD

**Issue by fgsfdss** [elysium-project/server#1437]
http://wowwiki.wikia.com/wiki/Hakkari_Thorium_Vein?oldid=70766

According to these comments they are supposed to have a higher chance on uncommon gems and always have at least 1 in them. 
http://www.wowhead.com/object=180215/hakkari-thorium-vein#comments:id=43002

Of course these are the only veins where Souldarite can be mined from.

**Comment by GuybrushGit** [comment]
All the veins on the dev server are Hakkari.
