### ISSUE TITLE
Namdo bizzfizzle

### ISSUE THREAD

**Issue by astarielko** [elysium-project/server#1439]
Namdo bizzfizzle, an engeneering alliance vendor outside the gnomeregan alternate entrance isnt spawning. Elysium server.

**Comment by thepparker** [comment]
Unknown spawn conditions

**Comment by GuybrushGit** [comment]
>Namdo Bizzfizzle is also hiding up against the north side of the main platform on the lower level of this room. 
https://wow.gamepedia.com/Train_Depot
