### ISSUE TITLE
Wandering Shay gets stuck

### ISSUE THREAD

**Issue by ProfGurke** [elysium-project/server#1441]
The Npc Shay from the Escort Quest "Wandering Shay" gets stuck on the hill next to her. She didn't move anymore and ringing the bell did not free her either, after ~1 minute she fell through the ground and was gone. I abandoned the quest and waited for her to respawn again, but the respawn seems to be significally higher than it is after just failing the quest. 

![shay stuck](https://user-images.githubusercontent.com/29654553/28109318-030b0418-66ef-11e7-9069-a8e6bcd03e11.jpg)

**Comment by thepparker** [comment]
Duplicate
