### ISSUE TITLE
Hinterlands cant obtain two quests

### ISSUE THREAD

**Issue by LadyMystique** [elysium-project/server#1443]
I cant obtain from NPC these quests: Snapjaws, Mon! and The Final Message to the Wildhammer.
2-3 weeks ago these quests worked for me, so first q Snapjaws, Mon! i completed, but server went down and lots of q dissepared again and also reward from this q which is a fishing pole. Now, when these q finally can be done and implamented in the game, I cant take them anymore so I cant finish them for a reward. These NPC doesnt work, dont have any quests anymore. Tried to delete WDB files but it didnt work.

**Comment by thepparker** [comment]
Quests should be available now. Note that if you are higher level than the required for the Wildhammer PvP quests, you will not be able to pick them up.
