### ISSUE TITLE
Grazle in Felwood not giving out quests

### ISSUE THREAD

**Issue by LixxyT** [elysium-project/server#1445]
Hihii~ there weren't any quests available from Grazle in Felwood when i was Hostile with Timbermaw Hold, neither was there any when i was Unfriendly with them. Please help~
![grazle](https://user-images.githubusercontent.com/30118543/28119454-7eae4a3c-6747-11e7-92e5-1349bb8d12ca.jpg)

**Comment by Kolmarwow** [comment]
this is normal, Grazzle's quests are not patched in until either 1.9 or 1.10, can't remember which. you're playing on darrowshire which is on 1.7, so the quests do not exist on the server at the moment.

**Comment by LixxyT** [comment]
oic, ty!

**Comment by thepparker** [comment]
Added later
