### ISSUE TITLE
Major bubble hearth bug - lose 10% durability superman flying bug

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1446]
I hearthed from tarren mill
https://www.youtube.com/watch?v=5F8XAOV-X9I

**Comment by StadenElysium** [comment]
Are you able to reproduce this?

**Comment by Mostprovidedlinks** [comment]
Sure

**Comment by StadenElysium** [comment]
Are you able to post instructions on how to reproduce this? :thinking:

**Comment by Mostprovidedlinks** [comment]
1. I was at tarren mill and heartged from attacking the tarren mill flight master.

2. I teleported to stormwind

3. I died and lost durabity and magically flew 200km/h (125mph) in a forward direction unable to control my body

4. The whispers or chat of people still remained there 

5. I logged back on and my corpse was in stormwind

**Comment by Mostprovidedlinks** [comment]
Im hoping this was fixed.
