### ISSUE TITLE
[Earthstrike] 280 AP trinket, failed to get the last piece.

### ISSUE THREAD

**Issue by Fustershock** [elysium-project/server#1447]
Completed a quest, but the questgiver don't finishing my quest, telling i don't have the needed item, but i have it in my bag. Yes, i know, i can just abandon the quest and make it again, but it's not something like "kill 5 pigs, get their tusks to me", i wasted my own gold/reagents/stuff to summon multiple bosses in silithus, farmed this like all day, and now i have this bug. I don't ask you to fix the issue or anything, just give me the item from the quest please, i have proofs of compliting:
![1](https://user-images.githubusercontent.com/30127870/28136445-0b23a01e-674a-11e7-9934-a21a0c0d5983.JPG)
here you see i killed all needed dukes.
![2](https://user-images.githubusercontent.com/30127870/28136466-1d416b82-674a-11e7-9200-5dc16d69ffd6.JPG)
and here you see the quest is broken, can't finish.
http://db.vanillagaming.org/?quest=8538 - this quest,
http://db.vanillagaming.org/?item=20948 - this is the quest starting item which i have but the questgiver didn't see it
http://db.vanillagaming.org/?item=21508 - this is what i need to get after compliting

**Comment by Sabre142** [comment]
Put the scroll in your bank. log out, delete your WDB, log in, withdraw the scroll. You may be able to hand it in after that.

**Comment by couchsitter** [comment]
>Put the scroll in your bank. log out, delete your WDB, log in, withdraw the scroll. You may be able to hand it in after that.
--

I had this same issue as well and the above solution fixed it for me. Thanks

**Comment by Fustershock** [comment]
Scroll in bank, logged out, deleted my WDB. Log back, got it from my bank, going to Commander - nothing. Don't fixed

**Comment by xniko** [comment]
> Moving an item between bank / inv by dragging the item had a different behavior compared to doing it by right click, so if for example you stored a quest item by dragging and took it back by right clicking the quest would bug out.

This bug might be related.

[https://github.com/elysium-project/server/pull/1039](url)

**Comment by Fustershock** [comment]
Tried both by right click and by dragging. Not fixed
