### ISSUE TITLE
(Anathema) Onyxia quest chain in Stormwind bugged?

### ISSUE THREAD

**Issue by fleafgit** [elysium-project/server#1448]
The Onyxia quest in Stormwind (The Great Masquerade) seems to be bugged since yesterday. When I tried last night, the Marshal did his talking with the Lady and then just disappeared (possibly died?). There were Horde peeps in the throne room who might have killed Bolvar later that night, but I'm not sure they pulled it off. Now, a second person is having trouble completing the quest. There are Onyxia dragonkin in the keep, and no Bolvar. He also just did the Masquerade part, so there's no real reason for the dragonkin. What's going on? Can anyone reset the event on Anathema?

Regards Frob

**Comment by thepparker** [comment]
If Bolvar is not there, he is likely dead. You'll have to wait for the respawn
