### ISSUE TITLE
4 rare elites allys aroud xroad, ask a lvl 60 char and killed them

### ISSUE THREAD

**Issue by Jimmybug817** [elysium-project/server#1454]
4 rare elites allys aroud xroad, ask a lvl 60 char and killed them, a scroll dropped, said it is a quest.
but when i click accept, said im not meet the requirments.
Sorry about the description, i am using a chinese version client, so i don't know the item name in english.

**Comment by Fustershock** [comment]
It's just a simple quest, and you are too low level to accept it. Level up your char, and try again.

**Comment by xniko** [comment]
Scroll in question: [10621](http://db.vanillagaming.org/?item=10621)

Quest requirement: lvl15, also Friendly(?) reputation with Orgrimmar

Killed the Alliance Outrunners on my 60 troll hunter on Anathema and could accept the quest just fine.

**Comment by Jimmybug817** [comment]
I think the requirement level is 25 not 15, i will try when i hit 25, thank you guys.

**Comment by Jimmybug817** [comment]
Accepted the scroll quest at lvl 25. Question Solved, thank you guys.
