### ISSUE TITLE
Ahoy, me Hearties! If serious, I wanna report about discrimination of pirates.

### ISSUE THREAD

**Issue by Fustershock** [elysium-project/server#1455]
Bugged behavior:

All hand hoay! 
Blow me down! I farmed almost a month of these old salt scallywags from Booty Bay [huh](http://imgur.com/a/odmFC), with an aim to look like a bombastic buccaneer, feed the fish with [Baron](http://db.vanillagaming.org/?npc=2496) and, finally, get me [hat](http://db.vanillagaming.org/?item=12185) and [set](http://db.vanillagaming.org/?item=22746)
Well, with last patch i got my set, but shiver me timbers! There is a lil problem in the getting the crown piece of the corsair suit. The issue is in impossibility to get reputation penalty with Booty bay privateers [look](http://imgur.com/a/HRgDI), so, by the [quest](http://db.vanillagaming.org/?quest=4621), i'm not able to get the hat without having lower rep then neutral with them. Savvy?
  **[FUSTER](http://imgur.com/a/XUnsz) SEADOG WANT ME PILLAGE FOR SENDING THESE BUCKOES ONTO DAVY JONES' LOCKER**

Correct behavior:

Unique Items
Becoming friendly with the Bloodsail Buccaneers will grant you access to the following items:

    [Bloodsail Admiral's Hat] - Summons a Blood Parrot
    [Bloodsail Shirt]
    [Bloodsail Sash]
    [Bloodsail Pants]

Reputation
There is only one way to increase your reputation with the Bloodsail Buccaneers and that’s to unleash your wrath on any citizen of Booty Bay who can be found through out the Eastern Kingdoms. Below is a list of every citizen of Booty Bay and their reputation value. The amount gained with the Bloodsail Buccaneers is shown for a level 60 non-human. The amount lost for killing a citizen cannot be shown as it depends on your current level with Booty Bay and the importance of the person you kill. In addition to this what ever you lose with Booty Bay you will lose half of that in the other three goblin towns so if you lose 25 points in Booty Bay you will lose 12.5 points in Ratchet.

    Booty Bay Bruiser: 25 rep gained
    Booty Bay Elite: 25 rep gained
    Baron Revilgaz: 5 rep gained
    Blackwater Deckhand: 5 rep gained
    Many more NPCs!

Sources:

[Wikia 1](http://wowwiki.wikia.com/wiki/Bloodsail_Buccaneers_reputation_guide)
[On our homie DB](http://db.vanillagaming.org/?faction=87#quests)
[Wikia 2](http://wowwiki.wikia.com/wiki/Bloodsail_Buccaneers)

**Comment by adura90** [comment]
Love this post! It makes me want to yell YARR!

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
