### ISSUE TITLE
Pet Bombling

### ISSUE THREAD

**Issue by Fustershock** [elysium-project/server#1456]
Bugged behavior:
Not ~~exploding~~ follows the player. At all.
[sadly](http://imgur.com/WDbWJhc)
Correct behavior:
Companions (a.k.a. small pets, non-combat pets, mini-pets, or vanity pets) are small creatures (or mechanical replicas thereof) that follow your player character around. They are mainly for show. Several of these companions have their own characteristic behaviors
Sources:
[Wowwiki](http://wowwiki.wikia.com/wiki/Pet_Bombling)
[About Companions](http://vanilla-wow.wikia.com/wiki/Companion)
[Hey!](https://www.youtube.com/watch?v=hffeN9xEMS8)[So cute..](https://www.youtube.com/watch?v=zAp0uXAn0Ao)

**Comment by kampeador** [comment]
Duplicate: https://github.com/elysium-project/server/issues/381
Fixed in dev branch.
