### ISSUE TITLE
quest: A Reliquary of Purity

### ISSUE THREAD

**Issue by dima-zorin** [elysium-project/server#1457]
Server - Elysium
hey, i have no talk-chain from npc to get this quest (http://db.vanillagaming.org/?quest=5527#wh-comments)
i done pre-quest chain and was in DM many times (https://vanilla-twinhead.twinstar.cz/?issue=7070#comments)
also, since 12.07 nobody get reward from this chain (http://realmplayers.com/ItemUsageInfo.aspx?realm=Ely&item=18536&page=2)

**Comment by thepparker** [comment]
Added much later

**Comment by Asmadaeus** [comment]
http://wowwiki.wikia.com/wiki/Quest:A_Reliquary_of_Purity

http://wowwiki.wikia.com/wiki/Quest:Shards_of_the_Felvine

According to the Wiki, it was added in 1.3.0, so it should be available on Elysium. Same with the Shards of the Felvine, the follow up.
