### ISSUE TITLE
Lok'delar and Rhok'delar stats missing

### ISSUE THREAD

**Issue by Fraerock** [elysium-project/server#1458]
Currently on Elysium server the staff for hunters missing the 2% crit bonus, bow missing 1% crit bonus. 

http://db.vanillagaming.org/?item=18715 , http://db.vanillagaming.org/?item=18713
source of how it should look like, 

http://wowwiki.wikia.com/wiki/Lok%27delar,_Stave_of_the_Ancient_Keepers source to prove that it never changed in the state available on vanilladb. 

http://pacifistguild.org/index.cgi?start=40 On that page there is a picture posted in 2005

**Comment by thepparker** [comment]
Fixed in 1.6 next week
