### ISSUE TITLE
Hotkeys doubling on actionbars

### ISSUE THREAD

**Issue by Anomaly242** [elysium-project/server#1459]
![world of warcraft 07 13 2017 - 17 57 52 01](https://user-images.githubusercontent.com/30154311/28175542-d5d42112-67f4-11e7-80bc-fa7d9f439d9d.png)

As you can see here there are doubles of spells both on the main actionbar and the extra bars.
Whenever i place something on slot 1, it will also double (And remove what was previously) on the opposite slot.

**Comment by adura90** [comment]
Try pressing the up/down arrows on the far right of the main action bar or do Shift+Mousewheel Up/Down.

**Comment by thepparker** [comment]
You have the same bar shown twice

**Comment by Anomaly242** [comment]
What, no, the 'Main action bar' and ''extra action bar 1''and it is impossible to show the same bar twice in 1 photo, now if video would have been allowed i could have shown you me switching out skills on either action bar would automatically switch out skills on the other one aswell.

**Comment by thepparker** [comment]
Press Shift and a number key, you will see your main bar change between all other available action bars
