### ISSUE TITLE
Hillsbrad Farmers and Peseants bug

### ISSUE THREAD

**Issue by Stump88** [elysium-project/server#1460]
During the "battle of hillsbrad" quests on horde, all of the humanoid NPCs in that area are not being slowed while running away in fear. I've tried on several charaters to test it. Hunter's daze, Warrior's hamsting, Mages frost, all should have slowing effects. but the effects are ignored, and they all run at the same speed with nothing applied. I can frost nova them in place and stuns will stop them.

**Comment by thepparker** [comment]
Duplicate #1471
