### ISSUE TITLE
Quest chain missing from Loch Modan

### ISSUE THREAD

**Issue by Herry00** [elysium-project/server#1464]
There is a quest chain that is missing from Loch Modan making it a difficult leveling experience. 

The first of the In Defense of the king's lands can be completed http://db.vanillagaming.org/?quest=224

but all subsequent quests do not seem to be obtainable. They were all added in the 1.11.10772 patch according to wowhead http://www.wowhead.com/quest=224/in-defense-of-the-kings-lands so each one should come after the other.

Herry (Elysium Server - Character Broomsticks)

**Comment by QAkvastskaft** [comment]
The different stages of this quests are given by different NPCs. Make sure to check all dwarfs around the area.

Anything marked 1.11.10772 patch on wowhead is because wowhead did not exist before this patch

**Comment by Zero3X** [comment]
I was able to complete the entire quest chain a few days ago. It's probable that the quest giver was killed or hiding somewhere.

**Comment by thepparker** [comment]
Quests are implemented
