### ISSUE TITLE
Copper veins are very rare, seems bugged

### ISSUE THREAD

**Issue by divhun** [elysium-project/server#1466]
Copper veins are so rare, it is nearly impossible to lvl the profession up

**Comment by Phoosy** [comment]
Can we get some more information than this? What are you proposing the spawn rate of the nodes be? What evidence do you have to indicate they should be this way? Which nodes are you noting seem rare? What areas are you referencing? What server are you on? What is the spawn rate you've noticed thus far?

**Comment by Zero3X** [comment]
Have been playing on the Elysium realm for a few days now, levelling in Elwynn Forest, Dun Morogh, and Tirisfal Glades and copper veins are spawning at a rate that reminds me of vanilla retail WoW. I was able to raise mining and use mined ore to feed my engineering in line with how I was levelling. I'm about half way through Westfall and am ready to move on to making bronze bars, which is about right (as tin first starts appearing in Westfall I believe). In short, I see no issue.

**Comment by Heyhohohoho** [comment]
Taken straight from discord, no alterations- 
Akira - Today at 1:15 PM
@everyone Greetings!

With the latest patch, we introduced an unnoticed bug that affected the spawn rates of multiple herbs. (Black Lotus, Plaguebloom, Dreamfoil, Gromsblood, Mountain Silversage, Ghost Mushroom)

We are addressing the issue and will be implementing a fix within the next few days.

Apologies to any and all affected by this bug, and thank you for the feedback. :herb: :sunflower: :leaves: :tulip:
