### ISSUE TITLE
Resupplying the Excavation

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#1467]
quest not properly implemented;

completed on pickup (shouldn't be)
dwarves are not fighting when you find them (they should be)
the dwarves that ambush you should be ambushers, not raiders.

ref; https://github.com/cmangos/classic-db/issues/71
https://github.com/cmangos/mangos-classic/commit/3743bf7b02c4f7e812dc3af5f95b895bbfb348e8
https://github.com/cmangos/classic-db/commit/aa237c43ebf5260fd7ba463f9ae1cbe2bd1b617b

**Comment by kampeador** [comment]
Thanks for the links, but i will probably implement my own version of this event.
