### ISSUE TITLE
Recent Rollback deleted riding training

### ISSUE THREAD

**Issue by WildClaw** [elysium-project/server#1468]
Here's what happened - The recent rollback that happened on 7/13/17 deleted my riding training, but retained my mount and only 10g. However, the rollback set me back to a point where I was suppose to have my original 100g before I purchased either mount or riding training. This essentially means the rollback deleted my riding training (which cost 80g) and retained the extra 10g I had (since riding training + mount = 90g and I have the mount currently) I would like this to be fixed. Located on Darrowshire - Orc Shaman named Athremus

**Comment by JosipbrozElysium** [comment]
This is the wrong place to report these kind of issues. Contact a GM via ingame ticket for character issues. 
For the next time, please read this first: https://github.com/elysium-project/server/blob/development/docs/Bug%20Reporting.md

Best regards!
