### ISSUE TITLE
Pirate Hats Ahoy! (ID: 8365) not dropping

### ISSUE THREAD

**Issue by alex067** [elysium-project/server#1469]
The hats for this level 46 tanaris quest has stopped dropping all together recently. It was dropping fine a couple of days ago, but recently there's been 0 drops.

**Comment by Elitegamer010** [comment]
same problem here.

**Comment by JosipbrozElysium** [comment]
Please name the realm on where this issue is occuring. For the next time, please read this first before posting: https://github.com/elysium-project/server/blob/development/docs/Bug%20Reporting.md

Best regards!

**Comment by JosipbrozElysium** [comment]
Reference: https://web.archive.org/web/20061025223122/http://wow.allakhazam.com/db/quest.html?wquest=8365

**Comment by Elitegamer010** [comment]
its on Elysium

**Comment by JosipbrozElysium** [comment]
Alright, this quest shouldn't be on the realm at all! Will be fixed tomorrow!

Best regards!
