### ISSUE TITLE
Lenny "Fingers" McCoy

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#1472]
Located in Old Town, Stormwind.

He is a teacher, but of nothing... probably should not be a trainer npc.

![billede](https://user-images.githubusercontent.com/1907820/28189370-f96a7492-6825-11e7-865f-f1cba5c44fa0.png)

**Comment by JosipbrozElysium** [comment]
He is a lockpicking trainer. Please, next time read our guidelines: https://github.com/elysium-project/server/blob/development/docs/Bug%20Reporting.md

Best regards!

**Comment by Phatcat** [comment]
Should he have that empty window available to anyone who isn't a rogue? cause I was on a druid when interacting with him.

**Comment by kampeador** [comment]
This trainer shouldn't exist. Lockpicking cap is increased with players level. I have an old db, which mentions other 3 and they are already disabled here. Spells that they use to teach you are not behave like they should.

**Comment by Phatcat** [comment]
> 'invalid' 'QA Denied'

https://forum.elysium-project.org/topic/53637-development-update-08092017/
>Removed outdated Lockpicking trainers

Please, next time don't close issues which you don't understand.

Best regards!
