### ISSUE TITLE
Kodo mounts don't have a rearing animation

### ISSUE THREAD

**Issue by a-big-dumb-baby** [elysium-project/server#1475]
All the other mounts, when you're standing still and press space, will do some kind of idle/rearing animation; horses kick up their front legs, dogs "play bow" and bark, etc.  Kodos should toss their head back and forth and grunt but they don't.  Literally unplayable, plz fix.

**Comment by xniko** [comment]
From what I remember on Nost the animation works for 100% kodos, not for 60% ones.

**Comment by a-big-dumb-baby** [comment]
I have rank 11 kodo and it doesn't work, and also seen people with the 100% TB kodos that don't work either.

**Comment by Heyhohohoho** [comment]
Dev in discord already told u it's unfixable. yet you make an issue on github regardless? Lol

**Comment by a-big-dumb-baby** [comment]
Dev told me no such thing, but a GM told me to open an issue on github.
