### ISSUE TITLE
The "Prairie Wolf" doesn't bark =O

### ISSUE THREAD

**Issue by MaZeeT** [elysium-project/server#1476]
The "Prairie Wolf" from Mulgore, does not  bark when clicked... In retail is used to and still do bark when left or right clicked. 

I hope this will get fixed since it was my favorite pet because of this unit feature =)

Link to the pet: http://db.vanillagaming.org/?npc=2958

Sincerely
MaZeeT

**Comment by xniko** [comment]
Cute! Can you provide a source from vanilla? Video, written description etc.

**Comment by brotalnia** [comment]
What do you mean by bark. Should it play a sound, or a specific animation, or the /bark text emote?

**Comment by MaZeeT** [comment]
In the link I provided is a comment from patch 2.3.0 which talks about this.. It is the earliest source I have been able to find... I will search the BC and Vanilla client for the soundfiles.

It just play a few barking sound files when clicked. =)

**Comment by Mostprovidedlinks** [comment]
yes it should i remember it did

**Comment by kampeador** [comment]
I am pretty shure that sound is handled by client, not server. It appeared in TBC.
