### ISSUE TITLE
Being flagged when flying to Winterspring

### ISSUE THREAD

**Issue by Bierflasche** [elysium-project/server#1480]
Several people in my group and I got flagged for PvP on Darrowshire when we flew from Theramore to Winterspring. (Alliance)

**Comment by blubba22** [comment]
Yeah, it happens because you shortly enter the Orgrimmar zone.

**Comment by thepparker** [comment]
I believe this has been fixed, please update if it still exists

**Comment by Bierflasche** [comment]
Just tested it and it still occurs.
