### ISSUE TITLE
Icyfury Wand

### ISSUE THREAD

**Issue by Aceius** [elysium-project/server#1481]
Icyfury wand is not adding the +3 Intellect, possible not the +dmg either? as shown in the pictures, the wand has +3 intellect, but with or without it ive got 180 intellect.

![wowscrnshot_071417_175123](https://user-images.githubusercontent.com/30051661/28219722-3e64437e-68bd-11e7-9c18-004556341578.jpg)
![wowscrnshot_071417_174822](https://user-images.githubusercontent.com/30051661/28219720-3e5d913c-68bd-11e7-8e59-9696a60fe54b.jpg)
![wowscrnshot_071417_174817](https://user-images.githubusercontent.com/30051661/28219721-3e61a010-68bd-11e7-9c7c-c6944e944f81.jpg)

**Comment by Kolmarwow** [comment]
You're playing on Elysium, the Icefury Wand is a green +3 Frost Damage item on Elysium's current patch. This means that your cache is outdated, you need to exit the game, delete the entire "WDB" folder in your vanilla WoW folder and start up the game again, then you should see the correct stats on the wand. It should get updated to what you're seeing now in Elysium's next patch (1.6/BWL patch), which comes later this month.

**Comment by thepparker** [comment]
Clear WDB
