### ISSUE TITLE
Holy Spell Resist

### ISSUE THREAD

**Issue by mewcure** [elysium-project/server#1485]
Holy spells are definitely not working properly on this server.. From my understanding, and experience.. holy spells can't be resisted, at all, except by stun resist (so.. base 5% chance for everyone but orcs) .. At least there's something funny going on.. I do specifically remember leveling paladins in vanilla wow.. (i had 3 60 paladins).. a level 20 paladin should resist hammer of justice on a level 20 player just as frequently as a level 60 player.. but leveling on elysium, HOJing a higher level player.. was more or less impossible...

**Comment by theloras** [comment]
incorrect in vanilla

**Comment by Mostprovidedlinks** [comment]
Holy resistance never existed in vanilla

**Comment by thepparker** [comment]
Permanent 1% miss chance for spells and level-based resists exist
