### ISSUE TITLE
Barov Peasant Caller Trinket has lost it's use effect (image inside)

### ISSUE THREAD

**Issue by wambam22** [elysium-project/server#1486]
Barov Peasant Caller trinket is just a blue item that says Trinket, with no use effect. It should summon three servants.
screenshot: http://imgur.com/a/eo25l
item db: http://db.vanillagaming.org/?item=14022

**Comment by wambam22** [comment]
bump. I heard this is an alliance only issue. Can we get any clarification?

**Comment by kampeador** [comment]
Can't reproduce this issue on my local test server. Have you cleaned your WDB folder?

**Comment by wambam22** [comment]
yeah ive cleaned wdb. apparently i'm not the only one with the issue, others have reported the same in-game

**Comment by thepparker** [comment]
Fixed
