### ISSUE TITLE
[Anathema] Warlock "summon" type doodads duplicate on use

### ISSUE THREAD

**Issue by Spaztick** [elysium-project/server#1487]
Warlock spells such as Ritual of Doom and Ritual of Summoning  will spawn multiple non-functioning doodads when another raid/party member clicks on them. This results in 2 additional portals or 4 doomguard altars that spawn, for example.

**Comment by sipertruk** [comment]
I have high hopes  #1017 will fix that.

**Comment by thepparker** [comment]
Fixed
