### ISSUE TITLE
cant equip[Beheading Blade of the Eagle]

### ISSUE THREAD

**Issue by 346164097f** [elysium-project/server#1488]
i cant equip [Beheading Blade of the Eagle], it's requires level 47 .my current level 49.  when i try to equip it , it's said that my level to low, need to reach level 57. what happened?

**Comment by Grymskvll** [comment]
It currently requires level 57 to equip. If you delete your item cache, you'll see that as well. 

According to archived captures of Allakhazam, it started off as requiring 57 and then was lowered by 10 whole levels without changing the dps.

April 04 2005: [https://web.archive.org/web/20050404061627/http://wow.allakhazam.com:80/db/item.html?witem=15253](url)
After this capture, it requires 47.
August 29 2005: [https://web.archive.org/web/20050829211519/http://wow.allakhazam.com:80/db/item.html?witem=15253](url)

Maybe they'll lower it in the ZG update. Damn thing tricked my Enchantrix real good.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
