### ISSUE TITLE
[Anathema] Pyroguard Emberseer adds invulnerable

### ISSUE THREAD

**Issue by Fakero** [elysium-project/server#1490]
Every time the stone is clicked 3 times it spawns a new boss and makes the adds invalid target. We tried it 3 times, first 2 times we had just 3 people click the stone and 1 extra boss spawned each time and the adds were attackable for a short while. 3rd try we had 3 bosses up since they didnt despawn and had everyone click the stone at the same time, again the adds could be attacked for like 2 seconds and we ended up with 6 bosses.

**Comment by thepparker** [comment]
Fixed
