### ISSUE TITLE
Darkmoon Maelstrom scales in november to be posted later

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1491]

**Comment by Mostprovidedlinks** [comment]
maelstrom should have 43% coefficient like it states in the november revision.

http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?direction=prev&oldid=368615 Scales in November 24, 2006 Revision as of 08:33

http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?direction=prev&oldid=339113 The Revision of November 24, 2006 08:31 and beyond says it did.

http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?direction=prev&oldid=339109
and before say it didn't

You are not correct saying it has a 0% coefficient. Here is more evidence with later dates showing this.

**Comment by Razorwynd** [comment]
You seem to be quite knowledgeable about this trinket... what is its current proc rate? and is that what it will be on Elysium server later today?

**Comment by Mostprovidedlinks** [comment]
I need stadens help sadly to change it

**Comment by Mostprovidedlinks** [comment]
Other than clicking the close issue by mistake. Yes elysium, should fix this

**Comment by theloras** [comment]
https://github.com/elysium-project/server/issues/719

@GuybrushGit @StadenElysium - looks like this nerf was done in error

**Comment by fidbugs** [comment]
No, it was not, @4:14 he is affected by one of General's Warcry buffs that increase damage by 10/20/30%.

So that 360 hit can be any multiplication from one of the different increasements.

http://db.vanillagaming.org/?search=warcry

**Comment by theloras** [comment]
you can't prove 100% that it was General's Warcry - it buff icon could be from the 20% HP bonus that Balinda does to all Alliance players in AV as well

I can't watch the video from Canada so I can only go from the screenshot
