### ISSUE TITLE
Cenarion Hold badge vendor not offering quests on Anathema

### ISSUE THREAD

**Issue by Drakbak** [elysium-project/server#1494]
The Cenarion Circle badge reward vendor, Vargus, is not offering any of the 4 quests used to obtain the rewards on the Anathema server after the 1.10 patch.

Vargas:
http://db.vanillagaming.org/?npc=15176#starts

The quests:
http://db.vanillagaming.org/?quest=8573
http://db.vanillagaming.org/?quest=8574
http://db.vanillagaming.org/?quest=8572
http://db.vanillagaming.org/?quest=8548

**Comment by Bunguni** [comment]
Also he must ending
http://db.vanillagaming.org/?quest=8809
but now it's broken too. He's just selling blacksmith stuff now.

**Comment by Shiral12** [comment]
confirmed, please fix it

**Comment by gxy8221450** [comment]
Indeed, he is now only selling blacksmith's things, not the task, previously received the task can not end

**Comment by cloudx123** [comment]
i lost hope, naxxramas will probably come out before they manage to fix 1 npc
gotta be a really complicatd problem with this guy..

**Comment by 30daystofixthings** [comment]
Any quest ending in Vargus cannot be turned in still which means earthstrike and rockfury bracers are still unobtainable for 1 month+ now.

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
