### ISSUE TITLE
Relics not drop.

### ISSUE THREAD

**Issue by Fustershock** [elysium-project/server#1495]
Done 50 runs already, checked realmplayers no one has any totem/idol/pala shiet, it seems something went wrong with the update, guys..

[After half a day] Done 35 more runs, still nothing. Upwote me, so hope we will get some fix soon.

**Comment by Gebius** [comment]
relics are introduced in 1.10. 
http://web.archive.org/web/20101107215601/http://www.worldofwarcraft.com/patchnotes/patch1p10.html
"Relics have been introduced to the game. These are class specific items for Druids, Paladins, and Shaman which can be equipped in the ranged slot. Currently there are a handful for each class which can be found scattered throughout Blackrock Depths, Blackrock Spire, Dire Maul, Scholomance, Stratholme, and The Temple of Ahn'Qiraj."

**Comment by Fustershock** [comment]
Fixed
