### ISSUE TITLE
MageOrgrimmarAttackerAI Incorrect race and class

### ISSUE THREAD

**Issue by jzcxw** [elysium-project/server#15]
Race and Class was inverted in SpawnNewPlayer. Causing to create Troll shamans all the time

Fix: 
https://github.com/elysium-project/server/commit/9bb3e287b2ddc0d88a0030c1f33771a45ae77d91

**Comment by StadenElysium** [comment]
Thanks. Closed this with 782698d76970177a115f56fc700c8acb2edb1129.
