### ISSUE TITLE
Bonereavers edge proc rate is too high 

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1501]
http://db.vanillagaming.org/?item=17076

PROOF:

https://www.youtube.com/watch?v=dd90O5LkikY&t=8m0s 

Orshabaal, Warlord Undead Warrior using Bonereaver's edge from Ragnaros. From Sylvanas-EU realm
http://www.warcraftrealms.com/charsheet/24329916
starts at 8:00 bonereavers edge is proccing no where near every hit when he duels a paladin. Look at how often the bonereavers edge procs in the top right corner. Its proc should be around 12% like in that video
This is an arms warrior with horde equivalent gear of the arms warrior in the video 3 shotting us in BETTER gear than the t1 paladin in the video and his damage is less and his procs are less. 

An elysium arms warrior was doing this to 5500 armor plate paladin.
https://youtu.be/_xiuzbudRT4

The warrior took him from 100-0 with losing only 7% health...
This wasnt happening pre 1.10

Every single video in duels in the exact gear in 2006 retail videos show not even 1/2 of that damage.

- Fix: Lower bonereavers edges proc chance to be thesame as the undead warrior in this video
https://www.youtube.com/watch?v=dd90O5LkikY

**Comment by stesve** [comment]
What exactly is bugged? This is what i could see in your combatlog.

gains bonereaver's edge
Crit 768 + deep wound applied
parry = reduced swingtimer
mortal strike 483
heroic strike crit 1082
gains boereaver's edge(2)
enrage + bloodcraze
execute 1103
extra attack from sword spec

**Comment by Mostprovidedlinks** [comment]
Its not the damage. Its the proc chance of the damage. That warrior was literally proccing that damage on every hit.

**Comment by Mostprovidedlinks** [comment]
The warrior did far too much damage which is not normal in that sort of gear.

**Comment by stesve** [comment]
Well... The combatlog is showing on the video and that log tells more about the fight than a "damage was to high" statement.

**Comment by knasen88** [comment]
stupidest bugreport on the entire tracker, please reconsider your lifechoices.

**Comment by Mostprovidedlinks** [comment]
Stupid? There is a video of a warrior in the exact gear not even doing 1/10th of that damage.
