### ISSUE TITLE
Dragonchilli only scaling at 30% instead of 100% in 1.10 patch

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1502]
This still hasnt been fixed sadly

https://youtu.be/xwY9Bq5yffc

https://github.com/elysium-project/server/issues/606
proof https://github.com/elysium-project/server/pull/992

**Comment by Phoosy** [comment]
This was not merged into the 1.10 patch update.

**Comment by thepparker** [comment]
Should be fixed
