### ISSUE TITLE
Engi speci to Gnome does not work for me

### ISSUE THREAD

**Issue by Zomgy** [elysium-project/server#1505]
Hey i'm a lvl 35 Paladin Engi on 252 and i've used this Guide. "http://vanillagaming.org/forum/index.php?topic=17332.0"

I accepted the Quest in Ratchet,  "Take the quest [47] Gnome Engineering from Tinkerwiz in Ratchet, And delivered the quest Item to Oglethorpe Obnoticus in Booty Bay, Stranglethorn Vale. But now there is no Quest called "The Pledge of Secrecy ".

Some Guild Mates told me there should have been a Quest in Ironforge to speci. but there is none for me.. please look into it.

I've delete my WDB Folder and all that kind of stuff nothing seems to work.

**Comment by JosipbrozElysium** [comment]
Please keep individual issues to ingame tickets and the forums.

Best regards!

**Comment by Zomgy** [comment]
It is no individual Issue, i figured out, it is possible to do the "Hord Faction" pre Quest for Gnome Engi till a certain point but at the End you can not learn any Gnome Engi Stuff cause you ain't getting the further Quest. + You can't get any Quest at all at the right NPC in Ironforge anymore, where you usually learn Gnome Engi.

**Comment by JosipbrozElysium** [comment]
Alright, I will reopen this for now and try to replicate the issue!

Best regards!

**Comment by Zomgy** [comment]
Awesome, sorry m English is not the best i just wanna try to improve Elysium and don't want other Player to get the same Issue like me ;) may a GM got time to help me Ingame @Puredaisy <3
