### ISSUE TITLE
Enemy melee attacks are still not causing me to stand when spam sitting for my reckoning bomb as of 1.10

### ISSUE THREAD

**Issue by ImperfectCell** [elysium-project/server#1507]
Enemy melee attacks are still not causing me to stand in the new patch

I spam sit for reckoning and its part of my pvp strategy but when im stunned and hit I remain in sit stance, and cant bubbe

1. I should be allowed to spam sit just like this guy in 2005 states

05 August, 2005 - Paladinsucks.com
paladinsucks.blogspot.mk/2005_08_01_archive.html
Aug 2, 2005 - Araxes has discovered a really, really fun thing to do if you're using the Reckoning-bomb spec. He discovered that when you press X and sit ...

2. technically all melee attacks should force the player to stand so he can use his spells.

https://github.com/elysium-project/server/commit/c0bb4993a6f37250c7c3f5b9260f4d56cbd4dc6c

is not working

I am still not standing 

Proof

Melee attacks against a sitting target automatically hit and cause double damage. The first damage taken while sitting will cause a target to immediately stand.
http://wow.gamepedia.com/Sit

fix this please, still not fixed as of 1.10

Fix: cause all melee to make player stand or be standing and If paladin /sits all melee enemy does will force him to stand continuously from every melee hit.

**Comment by thepparker** [comment]
No patches have been deployed to the live realms yet, fixes are currently being reviewed by QA
