### ISSUE TITLE
Relics

### ISSUE THREAD

**Issue by Gebius** [elysium-project/server#1508]
Taken from archived orginial blizzard patchnotes for 1.10.
Relics should have been introduced.

"Relics have been introduced to the game. These are class specific items for Druids, Paladins, and Shaman which can be equipped in the ranged slot. Currently there are a handful for each class which can be found scattered throughout Blackrock Depths, Blackrock Spire, Dire Maul, Scholomance, Stratholme, and The Temple of Ahn'Qiraj."

Sincerely Gebius

source: http://web.archive.org/web/20101107215601/http://www.worldofwarcraft.com/patchnotes/patch1p10.html

**Comment by JosipbrozElysium** [comment]
That's correct and relics are indeed ingame. If you find out that a relic is missing, then please write a bug report for it, according to these guidelines: https://github.com/elysium-project/server/blob/development/docs/Bug%20Reporting.md

Best regards!

**Comment by Fustershock** [comment]
How can i make sources for it? Make a screenshot of each of 100 attempts which we tried? or look up at realmplayers, maybe it's just really an awesome massive unluck so no one on server got any relic?

**Comment by JosipbrozElysium** [comment]
@Fustershock Good question, actually! Now I am not aware of the opinion of the other devs, but personally I don't have any issue if you simply write an issue if you "suspect" that an item is missing. It is never bad to just simply ask, but please provide us with the following info:

- Realm
- The item with it's ID (link for example)
- Proof that it should be available in this patch

With this provided info I could at least easily check if this specific item is indeed dropping and even know the droppchance of it.

Best regards!

**Comment by Fustershock** [comment]
@JosipbrozElysium as i posted in #1509, the realm is Anathema PVP, all item's ID is in #1509 too.
Well, here is a proof of a druid [soloing Roccor for a relic](https://www.youtube.com/watch?v=Q142k1vEhO0), here is another proof from Allakhazam, where players commenting about [Totem of Rage](https://web.archive.org/web/20060410025954/http://wow.allakhazam.com:80/db/item.html?witem=22395), what other i should find? Everywhere you can see the dates - nearly after 1.10 patch release.
Best Regards!

**Comment by Gebius** [comment]
@JosipbrozElysium After you told me that Relics are indeed ingame, I didnt bother and continued farming.
My Source of Doubt is , that in
 https://forum.elysium-project.org/topic/46976-items-not-in-game-yet-on-anathema/
An offical Project-Elysium representive was claiming that Relics will only be released with 1.11.

That is why I was looking for confirmation to begin with.
So far we have 2 Statements , 1 from you , and 1 from Manaci, but we also have source or Indirect knowledge that no Player so far got an Idol after 1.10. release.

Specific for the Relic I am looking for 

Realm: Anathema 

Item: http://db.vanillagaming.org/?item=23198

Source: official Patch Notes http://web.archive.org/web/20101107215601/http://www.worldofwarcraft.com/patchnotes/patch1p10.html
"Relics have been introduced to the game. These are class specific items for Druids, Paladins, and Shaman which can be equipped in the ranged slot. Currently there are a handful for each class which can be found scattered throughout Blackrock Depths, Blackrock Spire, Dire Maul, Scholomance, Stratholme, and The Temple of Ahn'Qiraj."


the Idol is not directly named , though I checked and there is no other Relic in all of Stratholme, that is exclusive to Stratholme or named Instances, so it has to refer to Idol of Brutality.

Other than drops from these Dungeon, It might refer to the World drop relics with "We hope that you enjoy the first round of available relics and we will continue to add more in future patches."

Sincerely Gebius

p.s. thanks for looking into the matter
