### ISSUE TITLE
Kinda source of relics deficit.

### ISSUE THREAD

**Issue by Fustershock** [elysium-project/server#1509]
After https://github.com/elysium-project/server/issues/1508 was marked as invalid, i have done a little research on realmplayers, so here we go:
[Totem of Rage](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22395) - zero players
[Totem of Sustaining](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=23200) - zero players
[Totem of Rebirth](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22345) - zero players
[Idol of Ferocity](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22397) - zero players
[Idol of Rejuvenation](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22398) - zero players
[Libram of Divinity](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=23201) - zero players
[Libram of Hope](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22401) - zero players
[Libram of Truth](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22400) - zero players
[Idol of Brutality](http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=23198) - some strange two shady druids has this, aquired at 2017-04-20 and 2017-05-13 (?!).
Im yourself already can confirm - 100 tries, no one relic (LBRS/BRD/Scholo), who knows how many attempts have done other ppl, don't said nothing about Alliance poor (not) paladins!
So, is it just the biggest wave of unluck on the server, or what?
Go, please, try to kill some hundred times these bosses and then tell if everything is okay with relics drop... sorry for bad english

**Comment by Gebius** [comment]
as this is the actual open issue i am moving this here too:
@JosipbrozElysium After you told me that Relics are indeed ingame, I didnt bother and continued farming.
My Source of Doubt is , that in
https://forum.elysium-project.org/topic/46976-items-not-in-game-yet-on-anathema/
An offical Project-Elysium representive was claiming that Relics will only be released with 1.11.

That is why I was looking for confirmation to begin with.
So far we have 2 Statements , 1 from you , and 1 from Manaci, but we also have source or Indirect knowledge that no Player so far got an Idol after 1.10. release.

Specific for the Relic I am looking for

Realm: Anathema

Item: http://db.vanillagaming.org/?item=23198

Source: official Patch Notes http://web.archive.org/web/20101107215601/http://www.worldofwarcraft.com/patchnotes/patch1p10.html
"Relics have been introduced to the game. These are class specific items for Druids, Paladins, and Shaman which can be equipped in the ranged slot. Currently there are a handful for each class which can be found scattered throughout Blackrock Depths, Blackrock Spire, Dire Maul, Scholomance, Stratholme, and The Temple of Ahn'Qiraj."

the Idol is not directly named , though I checked and there is no other Relic in all of Stratholme, that is exclusive to Stratholme or named Instances, so it has to refer to Idol of Brutality.

Other than drops from these Dungeon, It might refer to the World drop relics with "We hope that you enjoy the first round of available relics and we will continue to add more in future patches."

Sincerely Gebius

p.s. thanks for looking into the matter

**Comment by Lorilay2** [comment]
@Gebius Idol of Brutality was added in 1.11, as you can see from the comments and the dates of the comments on its respective Allakhazam page: https://web.archive.org/web/20070216131839/http://wow.allakhazam.com:80/db/item.html?witem=23198

Please note that no one mentions its dropping until after the 1.11 patch date of June 20th, 2006.

**Comment by honeyhoney** [comment]
I doubt they are in-game and I would encourage you to double and triple check.

The following itemization patches seem to suggest that those handling the downgrades/patches believe that the relics were not added until patch 1.11:

- https://github.com/elysium-project/database/blob/master/itemization/Downgrade%201.12%20%E2%86%92%201.10.sql#L69
- https://github.com/elysium-project/database/blob/master/itemization/Downgrade%201.12%20%E2%86%92%201.2.sql#L85

Re-quoting patch notes that suggest otherwise:

>**World of Warcraft Client Patch 1.10.1 (2006-04-11)**
>
>**Items**
>- Relics have been introduced to the game. These are class specific
  items for Druids, Paladins, and Shaman which can be equipped in the
  ranged slot. Currently there are a handful for each class which can
  be found scattered throughout Blackrock Depths, Blackrock Spire, Dire
  Maul, Scholomance, Stratholme, and The Temple of Ahn'Qiraj. We hope
  that you enjoy the first round of available relics and we will
  continue to add more in future patches.

**Comment by Gebius** [comment]
yep while i am quite sad personally , I am very well satisfied with the evidence.
I didnt personally know the IDs of databases would be Blizzard IDs , and didnt check alkazam.

My doubt was primarly led by the missleading patchnotes text. with "currently" and "startholme", leading to only Idol of Brutality. Kinda was proof enough for me , that I didnt check further.


Thanks for all your work, great Job.

**Comment by JosipbrozElysium** [comment]
Thank you all for the responses. I will check all items now (if they are supposed to be ingame, if they are ingame, dropping etc.)

**Comment by JosipbrozElysium** [comment]
[Totem of Sustaining](https://web.archive.org/web/20060717175625/http://wow.allakhazam.com:80/db/item.html?witem=23200) is not supposed to be in patch 1.10!

[Idol of Brutality](https://web.archive.org/web/20070216131839/http://wow.allakhazam.com:80/db/item.html?witem=23198) is not supposed to be in patch 1.10!

[Libram of Divinity](https://web.archive.org/web/20070216131839/http://wow.allakhazam.com:80/db/item.html?witem=23201 ) is not supposed to be in patch 1.10!

**Comment by Gebius** [comment]
same with totem of the storm http://db.vanillagaming.org/?item=23199
                 idol of the moon http://db.vanillagaming.org/?item=23197
                  libram of fevor http://db.vanillagaming.org/?item=23203
 and obviously relics that drop in naxx

**Comment by JosipbrozElysium** [comment]
The 3 mentioned are not supposed to drop in this patch as well!

**Comment by Gebius** [comment]
all 1.11

**Comment by JosipbrozElysium** [comment]
All others are indeed missing and will be added tomorrow!

Best regards!

**Comment by Fustershock** [comment]
FINALLY

**Comment by Fustershock** [comment]
Can you, please, test, if the other relics except druid's drop or not? 2 days after, i am by myself maked like 30 runs and no totem... it seems, paladins didn't got librams too.. just some druids with their idols. I just ask you test in the game if they even drop..

**Comment by Lorilay2** [comment]
They were added to the loot tables in the maintenance yesterday.

**Comment by Fustershock** [comment]
@Lorilay2, you sure? Can you tell, where we can look at this table? Just for sure..

**Comment by SiguDS** [comment]
: http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22396 
http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22402
Always horde hate.  Can someone check if the totem is able to drop from fankriss since 1.10?

**Comment by Fustershock** [comment]
FIXED!
