### ISSUE TITLE
"Improved Mend Pet" is not working as intended.

### ISSUE THREAD

**Issue by ELouisYoung** [elysium-project/server#1510]
"Gives the Mend Pet spell a (15/50)% chance of cleansing 1 Curse, Disease, Magic or Poison effect from the pet each tick."
The "each tick" is not being taken into consideration.  It seems like it's a fixed 15/50% chance per cast instead.  In retail this worked literally as stated verbatim, and regardless of which rank was used.  Back in retail I would only put 1 point in this and use rank 1 to cleanse my pet.  the 15% per tick basically ensured that a cleanse would occur once per cast.

**Comment by ifyousayso** [comment]
Also, it doesn't seem to work at all if the pet is at full health (not healed).. not sure if this is working correctly or not, though.

**Comment by ELouisYoung** [comment]
@ifyousayso I can remember from retail, it's not working as intended.  the cleanse chance should not give any respect to pet health.
