### ISSUE TITLE
Warrior cannot execute at 20% HP

### ISSUE THREAD

**Issue by ELouisYoung** [elysium-project/server#1512]
The bug is: execute is only usable when a mob is 19% or less.
The spell clearly states "usable on enemies that have 20% or less health".
A warrior player's UI should show "20%" hp remaining and be able to use execute.

**Comment by luigimannoni** [comment]
Amazing to have spotted this, fix was easy enough. PR pushed and waiting for review.

**Comment by ELouisYoung** [comment]
@luigimannoni thanks so much for fixing this.  I be you would also be able to fix this equally as easy: https://github.com/elysium-project/server/issues/2033

**Comment by luigimannoni** [comment]
@thepparker please keep this issue open, the PR fixes only the Sweeping Strikes proc

**Comment by GuybrushGit** [comment]
https://youtu.be/sW4vbSJgF98?t=242

Execute only lights up at 19%

**Comment by elysium-asura** [comment]
A TBC example in addition to this - https://youtu.be/TTTfA4sya90?t=255

After Discussion with @GuybrushGit, and video footage from both TBC and Vanilla warriors, it is decided that this is working "as intended".
