### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by leeleegor** [elysium-project/server#1513]
<snip>

**Comment by Phoosy** [comment]
Ban appeals go on our forum, not Github

**Comment by leeleegor** [comment]
https://forum.elysium-project.org/forum     
is this

**Comment by Phoosy** [comment]
https://forum.elysium-project.org/announcement/9-ban-appeal-information-read-before-posting/

**Comment by JosipbrozElysium** [comment]
For your own security, please don't post any private account data!

Best regards!
