### ISSUE TITLE
Book "Soothsaying for Dummies" - respec from goblin -> gnome eng and back, not works

### ISSUE THREAD

**Issue by Fustershock** [elysium-project/server#1514]
Bugged behavior:
Not only not working, but even **NOT CLICKABLE** 
[here we go](http://imgur.com/a/ZzD7T)
Correct behavior:
Book "Soothsaying for Dummies" is a fixed device, book located on a table inside Narain Soothfancy's house North of Steamwheedle Port in Tanaris.

Reading this book removes previous commitment to a discipline specialization in a profession that has been completely abandoned. This enables professionals to choose a different discipline specialization in a profession they had previously known. 

 Respecialization for Leatherworkers and Blacksmiths

    Talk to one of the specialization trainers about switching
    Pay 100g to unlearn your current specialization
    Go to and speak with Narain Soothfancy
    Read the book to select a new specialization 

Respecialization for Engineers

    Speak with Narain Soothfancy
    Read this book
    Pay 150 gold to unlearn current specialty
    Read the book again to choose a new specialization
Sources:
[Nost forum](https://forum.nostalrius.org/viewtopic.php?f=45&t=3950)
[Wowwiki](http://wowwiki.wikia.com/wiki/Book_%22Soothsaying_for_Dummies%22)
[ Engineering Specialization

Engineers may choose to specialize in either Gnome Engineering or Goblin Engineering upon attaining level 30 and 200 skill. Specialization is optional, does not require Artisan Engineering proficiency and cannot be changed later without abandoning Engineering altogether, relearning it from the beginning and reading the book "Soothsaying for Dummies". ](http://vanilla-wow.wikia.com/wiki/Engineering)

**Comment by Sabre142** [comment]
Not implemented in vanilla.

**Comment by Zarant** [comment]
That is a tbc thing iirc, if you want to respec your professions in vanilla, you have to drop the profession and level it again.

**Comment by Phatcat** [comment]
... What... Yes, this was implemented in vanilla.

http://wowwiki.wikia.com/wiki/Book_%22Soothsaying_for_Dummies%22?oldid=344872 <- from november 2006. This goes back to at least july as well; http://wowwiki.wikia.com/wiki/Book_%22Soothsaying_for_Dummies%22?oldid=188981

Do you people just... guess?

> if you want to respec your professions in vanilla, you have to drop the profession and level it again.

You know dropping a profession doesn't drop the specialization if you've chosen one? If you've gone gnome engineer you can drop engineering all you want, you're still a gnomish engineer as soon as you pick engineering back up.

**Comment by thepparker** [comment]
If you read those Wiki posts, it clearly states that it lets you unlearn a specialization of an abandoned profession. Meaning, drop the profession and re-level. 

As far as I'm aware, your specialization is lost upon abandoning the profession on this server. If that is not the case, and you are locked into it despite re-leveling, that is a valid issue, but is not really what this report describes.

**Comment by Phatcat** [comment]
> As far as I'm aware, your specialization is lost upon abandoning the profession on this server. If that is not the case, and you are locked into it despite re-leveling, that is a valid issue, but is not really what this report describes.

Here's the issue report;

> Bugged behavior:
Not only not working, but even NOT CLICKABLE

So this is not what the report is describing? that this item should be implemented in vanilla, which 2 commenters went out of their way without knowing what they were talking about to say that they didn't think so... are you saying this shouldn't be fixed if elysium has hackfixed it to remove specialization upon dropping profession?

**Comment by thepparker** [comment]
I didn't say anything along the lines of whatever the existing implementation is being correct. The OP describes using the book to unlearn the current specialization, and then instantly learn a new one. The duplicate report he has created in #1545 similarly has links to implementations which do just that.

From the way I understand it should work, is that you must completely abandon the profession. Then you are able to use the book and change specializations, and re-level the profession. If that is what is meant to be stated in this report, then it should be edited to say as much.

**Comment by Fustershock** [comment]
@thepparker, How it's able to be: [something like that](https://www.google.com.ua/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjP9oKx5ZTVAhWBHJoKHZULAVAQtwIIPjAC&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9ffNV2ZRI7M&usg=AFQjCNFYaUMA9x9tPZCNnL0F2etHiwtBzA). Yes, i understand that it's from a later patch of WoW, but don't think blizzard changed something in gossip or book options, why do they change if it worked well.

**Comment by Phatcat** [comment]
@thepparker 

The report already says this;

> Reading this book removes previous commitment to a discipline specialization in a profession that has been completely abandoned.

Did you even read the report?

**Comment by kampeador** [comment]
Book exists in my old DB from dec 2006, but all approaches that you linked, use spells that don't exist in vanilla/classic.
These were added in wotlk:
engineering:
http://www.wowhead.com/spell=68334/
http://www.wowhead.com/spell=68333/

These are from TBC:
blacksmithing.
http://www.wowhead.com/spell=36436/
http://www.wowhead.com/spell=36435/
http://www.wowhead.com/spell=36441/
http://www.wowhead.com/spell=36439/
http://www.wowhead.com/spell=36438/
leatherworking.
http://www.wowhead.com/spell=36434/
http://www.wowhead.com/spell=36328/
http://www.wowhead.com/spell=36433/

As you cen see, another approach is needed to implement such mechanics. I don't see any problems here, but will elysium devs accept this feature?

Currently, there are some gossip options(except engineering) implemented in the core. They are using TBC spells, so you will receive "Can't do right now" error.
