### ISSUE TITLE
The Fargodeep Mine

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#1517]
The quest is not completable because the objective is never triggered nomatter what area of the mine you go to.

**Comment by Phatcat** [comment]
Nope. I am just bad at scouting through mines. This quest is working fine.

**Comment by kampeador** [comment]
This quest is not working fine.
It is 0 day bug in databases since the beginning of wow emulation. These quests are missing area-triggers.
The Fargodeep Mine, The Jasperlode Mine and one quest in Felwood.
