### ISSUE TITLE
Champions Battlegear - can't pick up the quests

### ISSUE THREAD

**Issue by Shiral12** [elysium-project/server#1519]
Vargus - the questgiver doesnt give any of the battlegear quests.. Please fix it ASAP :(

**Comment by cloudx123** [comment]
bumb hope they fix it really soon, almost a month now - without figuring out how to fix 1 npc gotta be complicated..

**Comment by GuybrushGit** [comment]
Same as https://github.com/elysium-project/server/issues/1494
