### ISSUE TITLE
Opening Screen Issue

### ISSUE THREAD

**Issue by Norfertu** [elysium-project/server#1523]
Normally when I open the screen, my characters will display the character, the name and then under the name is their level and race.  Now they just have three dots under the name.  I looked into settings, but must have missed something.  Is there an easy fix for this.  Doesn't effect game play, I don't think, but is kind of annoying.  Thank You for your help in this matter. :)

P.S. if it helps, I am using a MacBook.

**Comment by luigimannoni** [comment]
Probably you have a retina display which is messing around with the pixel rounding up mechanism on your client. Back then there weren't retina displays :) 

Resize your window a couple of pixels and it should disappear.

**Comment by Norfertu** [comment]
Worked perfectly!  Awesome, thank you very much!
