### ISSUE TITLE
Mangosd.exe not "autorefreshing"

### ISSUE THREAD

**Issue by 3mul4tor** [elysium-project/server#1526]
How come you will have to occasionally press a random key to make mangosd "move forward"? If there is new output data, it will not show unless I press like enter-key. Self-compiled development branch, for contribution purposes.

Is this related to logging settings?

**Comment by thepparker** [comment]
I assume you are using windows. You probably clicked on the console window, entering select mode, which pauses the running application. The only way to clear it is to right-click or press any key.
