### ISSUE TITLE
Viscidus blobs moving too fast.

### ISSUE THREAD

**Issue by rockmusicalways** [elysium-project/server#1527]
After Viscidus is shattered and splits into many blobs, the blobs are reforming WAY to fast.  
~20 sec clip showing my guilds brief attempt earlier today (16/7/2017) - sorry for any bad language in voice com's.   https://www.twitch.tv/videos/159712212

**Comment by StadenElysium** [comment]
Fix incoming on Wednesday.

**Comment by kampeador** [comment]
From what i saw in code: it is still not fixed. 
Retail: speed interpolated linearly from 0 to 1.
You can clearly see that in this video:
https://youtu.be/Kc8yIFZjV6s?t=132

Current implementation:
Hacky mess. Their speed starts at 1.0 and increases by 1.5 every second i.e 1.0, 2.5, 4.0, 5.5... which makes no sense at all.
Once i'll find some free time, i'll rewrite this.

**Comment by rockmusicalways** [comment]
What kampeador said is correct. Guild attempted Visc again today with the same results as the original video clip I posted.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
