### ISSUE TITLE
[ANATHEMA] Field duty silithus bugg ,ch quests bugged,  missing loot from mobs, portals bugg.

### ISSUE THREAD

**Issue by Sgsuckme** [elysium-project/server#1528]
The quest Field Duty, where you have to kill hunterkiller tog et your field duty papers signed, doesnt work properly. after killing the mob, krug skillsplit wont sign my papers, i have tryed several times and it is impossible after the patch :/ had nmo issues before but cant get em signed now for some reason. i have tryed to drop the quest but with new field duty papers its still bugging.

the follow up quests from field duty, i cant  turn in quests to get new tactical assignments.

twilight texts + twilight sets is not dropping from mobs, not after 100+ kills. and bec of this, i cant summon dukes etc to finish my quests.

portals are duplicating. when someone make a portal, it creates mirror portals. so after 5 summons there is like 15 portals.

PLEASE fix these buggs <3

**Comment by Mostprovidedlinks** [comment]
fix thois please

**Comment by GuybrushGit** [comment]
Field Duty fixed, twilight texts drop and portal bug doesn't happen anymore.
