### ISSUE TITLE
Zipping crash

### ISSUE THREAD

**Issue by Hearthcraft** [elysium-project/server#1531]
Having problem getting started.
Every time I try to unpack/zip the downloaded client-game it always stops at certain percentage and freezes my computer . The window with following message pops up: "Read error in the file E:/ELYSIUM/World of Warcraft 1.12 Client.rar" followed by another window: "The request could not be performed because of an I/O device error." What to do ?

**Comment by Hearthcraft** [comment]
Found the major problem! I successfully manually extracted every file except "terrain.MPQ" because every time I try to extract that file the computer freezes and gives the message written in the post. Please help out

**Comment by Phoosy** [comment]
Github is not the place for personal assistance - please make a post on our forums.

**Comment by Hearthcraft** [comment]
I was redirected here but fine

**Comment by Hearthcraft** [comment]
@Phoosy cannot submit any thread to the forum because it says its not available in my country , can you resolve my problem here ?

**Comment by brotalnia** [comment]
Try downloading the client from somewhere else. And make sure you have enough free space.

You can try with this one.
http://forum.nostalrius.org/viewtopic.php?f=32&t=2803#p25865

**Comment by Hearthcraft** [comment]
nvm that was a bug , made a post here https://forum.elysium-project.org/topic/50398-cannot-extract-terrainmpq/

**Comment by Hearthcraft** [comment]
@brotalnia i do have enough free space and i will try to dl that one as well . thanks

**Comment by Hearthcraft** [comment]
I re-downloaded game from the link brotalnia provided and the game works , as for anyone having the same issue just to de same and re-download the game :)
