### ISSUE TITLE
Silithus Quests bugged [ANATHEMA]

### ISSUE THREAD

**Issue by latyy** [elysium-project/server#1535]
![vargusbugged](https://user-images.githubusercontent.com/30239727/28277504-75b2b162-6b1a-11e7-8615-b750c8648724.jpg)
Vargus is currently not giving the quests for the Cenarion Circle gear : http://db.vanillagaming.org/?quest=8573 etc.

Also after killing quite a few of the Twilight mobs it seems the clothing (http://db.vanillagaming.org/?item=20407) required to summon the Templars, Dukes and Lords dosent drop aswell.

**Comment by Bergador** [comment]
game- and laty-breaking bug, pelase fix

**Comment by ramangan** [comment]
Can confirm. Killed 60-70 cultists with 0 twilight set pieces or text pages dropping. This is gamebreaking for the T0.5 quest line

**Comment by latyy** [comment]
Hello GMs? I cant finish my Earthstrike. pls HALP

**Comment by cloudx123** [comment]
sad to see it takes almost a month to fix 1 npc probably over 200+ people stuck with the issue hope they fix soon cant do anything else than being patient
