### ISSUE TITLE
Minor Wizard Oil Unusable - "This spell is not available to you"

### ISSUE THREAD

**Issue by Ascha90** [elysium-project/server#1536]
On my level 15 Warlock, on the Elysium server, I made four things of Minor Wizard Oil. I flew to Auberdine and tried to use the Minor Wizard Oil from my action bar on my Giant Tarantula Fang dagger. I got a message at the center of my screen saying "This spell is not available to you." I got the same result when trying to use the item from my bags. I ask in general chat and at least one person had gotten the same message. Logging out and back in hasn't helped. Restarting the client hasn't helped. Disabling all of my addons hasn't helped. Deleting my WDB and WTF folders hasn't helped. The same message keeps appearing. This is on Grualia, my level 15 Warlock on the Elysium realm.

**Comment by Haiwuu** [comment]
Disabled until a later patch.
