### ISSUE TITLE
People cannot change engineering specialization, if they choosed it wrong back in the past.

### ISSUE THREAD

**Issue by Fustershock** [elysium-project/server#1545]
Following #1514 , i looked up about some codes and/or other github servers fixes, or just useful links. I hope, something from that can help our devs to make this amazing book working and let hundreds of players GET THIS BATTLE SQUAWK GNOMISH CHICKEN FINALLY!!!1 aww..
[TrinityCore post](https://github.com/TrinityCore/TrinityCore/issues/1782)
[cmangos post](https://github.com/cmangos/wotlk-db/issues/26)
[elecyb's gists](https://gist.github.com/elecyb/78fb41f78f6940466350)
[some shietty Kronos post, but whatever](https://www.reddit.com/r/kronos2wow/comments/4n8gkc/how_do_i_switch_to_gnomish_engineering/)

Realm: Anathema

**Comment by thepparker** [comment]
The only way to change your specialization is to drop engineering and re-level it. The book to change was added in a later expansion.

**Comment by Fustershock** [comment]
@thepparker wt you talking about? Please, don't comment, if you don't know the true. I have already done it.. if you got any specialization, you will get immediately when you level your engineering again to 225. 
"@Phatcat in #1514 : if you want to respec your professions in vanilla, you have to drop the profession and level it again.
You know dropping a profession doesn't drop the specialization if you've chosen one? If you've gone gnome engineer you can drop engineering all you want, you're still a gnomish engineer as soon as you pick engineering back up."

**Comment by thepparker** [comment]
Let's condense this back into a single report, continuing in #1514

**Comment by thepparker** [comment]
Duplicate
