### ISSUE TITLE
Judgement of righteousness is 42% coefficient and should be 50% / judgement of command (no stun) is 23% and needs to be 43% coefficient

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1547]
Judgement of righteousness is a 42% coefficient when it should be 50%

I hit 186 spell damage with 0 spell damage
Then when I put on 243 spell damage JoR does 285 spell damage..

http://i.imgur.com/M8ALqQa.png

------------------------------------------------------

This also goes thesame for judgement of command.

judgement of command is doing too little

https://www.youtube.com/watch?v=vgD0YQ0VELU&t=5m20s
This paladin has 58 spell damage gear on him and is doing as much as me with 200 spell damage
Judgement of comman with 0 spell damage (no 6% bonus)
https://youtu.be/dTuS2BWWku0
is hitting between 170-183 judgement of command

https://youtu.be/tniBsp7zIpY
Here I have the sanctity aura like him and the 6% bonus like him.
As you can see he has 58 spell damage and is from patch 1.12 and I have 200 spell damage and hit 233-250 damage

https://www.youtube.com/watch?v=vgD0YQ0VELU&t=5m20s 
 He is hitting 229-244 with sanctity aura
http://i.imgur.com/CGLtyjo.png

- Note: 
Its only the non stunned judgement of command that is wrong. On average he is getting 43% coefficient compared to my 23% coefficient.

- Judgement of righteousness needs to be increased by 8% damage

- Judgement of command should be 43%

http://i.imgur.com/M8ALqQa.png

**Comment by Mostprovidedlinks** [comment]
This also goes thesame for judgement of comand. Its doing a 20% coefficient instead of 43%

**Comment by thepparker** [comment]
Duplicate
