### ISSUE TITLE
Player-owned Pet's ignore Stealth.

### ISSUE THREAD

**Issue by ophiates** [elysium-project/server#1548]
If a warlock sends his pet to attack you, it doesn't matter if you stealth from 60 yards away. The pet will hunt you down regardless.

**Comment by knasen88** [comment]
if owner sends pet on someone before they stealth, its intended and infact blizzlike.
only vanish rids pets.

**Comment by thepparker** [comment]
Intended behaviour, https://www.youtube.com/watch?v=Q0O4RKeD4g4
