### ISSUE TITLE
Item spell procs not procing judgement of wisdom or light

### ISSUE THREAD

**Issue by Xaph-er** [elysium-project/server#1549]
Items with spell procs like Fiery Plate Gauntlets, Storm Gauntlets and 2-piece Stormshroud Armor are not procing judgement of wisdom or light. Both wisdom and light should have a chance to proc off all physical and damage spells.

**Comment by GuybrushGit** [comment]
Giving procs to something that procs on every hit sounds like a really bad idea, you could easily double or triple the amount of health and mana gained per hit.

**Comment by Xaph-er** [comment]
I'm all for balancing the game when something would break it, like those items scaling from spell power despite it being blizzlike, but in this case I don't think it would break the game as it would in the case of spell power scaling but only improve both paladin and shaman output to where it should be in Vanilla wow. both the gauntlets can only be equipped by warriors and paladins, and the hunters and shaman can only equip the storm gauntlets. The class that benefits the most from this would be paladins because of seal of righteousness and the ability to overcome some of their mana issues.

Both seals are also a 40% chance, so in effect the most "broken" outcome you would get is a paladin running seal of righteousness getting 4 chances at a proc on each swing. I highly doubt it would break any encounter and, would be blizzlike.

I can see avoiding it on weapons that have added spell procs on every hit, but not armor. Something like the 2-piece Stormshroud proc is also only a 2% chance and would have no chance at being broken like spell power scaling on these types of items. Ultimately I think in this case, unlike with spell power scaling, it wouldn't break the game and is more blizzlike.
