### ISSUE TITLE
Cuergo's Gold Quest

### ISSUE THREAD

**Issue by Penguin790** [elysium-project/server#1550]
Clicking on the chest but the pirates do not appear so you are unable to get key to finish quest.

**Comment by Cabro** [comment]
Currently this quest requires level 42, when it should be 40. (your database shows it to need 42).
Also, cannot get this quest at all, right clicking on the quest starting item does nothing.

**Comment by brotalnia** [comment]
What is your source that the level requirement should be 40? I looked at the wowhead comments and nobody mentions doing it below 42.

**Comment by Cabro** [comment]
Read the item... http://db.vanillagaming.org/?item=9254

**Comment by brotalnia** [comment]
Just tested it on development branch and everything is working fine. The quest had Method set to 1 (disabled) on some of the live realms, it should be resolved now. Clear your cache and try doing the quest again.

Level requirement has been corrected to 40, as Thottbot also has it at 40.
https://github.com/elysium-project/server/commit/4ccfde4604f7eac0d8253d56d89d5c2bb36c53c7

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
