### ISSUE TITLE
Item spell crits not procing Vengeance

### ISSUE THREAD

**Issue by Xaph-er** [elysium-project/server#1551]
Items with spell procs like Fiery Plate Gauntlets, Storm Gauntlets and 2-piece Stormshroud Armor are not procing Vengeance when they crit. Vengeance should proc off all spell crits even if they originate from an item. Weapon damage procs currently are working as they should but damage procs originating from other item slots are not procing vengeance when they crit as they should.

**Comment by Mostprovidedlinks** [comment]
Fix please

**Comment by thepparker** [comment]
Duplicate
