### ISSUE TITLE
Fix alterac . Correct..

### ISSUE THREAD

**Issue by tallibs** [elysium-project/server#1552]
Players "hordes" using the landscape without a hitch pass to the base of the alliance, bypassing all defensive structures !!!!! Please correct !!!! Put something in there so they can not jump in there. bans them! Because it's unfair !!!!!!

**Comment by Ripper007** [comment]
This is an old issue, not even Blizzard did something to change that and the alliance is capable with a few people to hold the bridge and 20+ horde. And this is a BUG report. You can discuss on forums this problem.

**Comment by tallibs** [comment]
при чём тут мост они заходят  с боку с тылу!!!!!!   минуя все башни  и  всех  защитников!!!!!
 а  исправление банальное там где они запрыгивают используя ландшафт  можно просто что то положить что им не даст запрыгнуть или  поставить туда не убиваемого гварда чтоб он их ганкал!!!!!

**Comment by tallibs** [comment]
вы не поняли сути проблемы зайдите на "Альтерак"  и посмотрите как орда обходит все  защитные  сооружения  пользуясь   недоработкой в ландшафте!!!!!  по сути  попадая на кладбище альянса  минуя  всю охрану и  спокойно его  захватывая.... в то время как альянсу приходится прорываться с боем  к главной крепости и кладбищю орды!!!!!!! что  приводит  к 100% поражению  альянса даже при небольших усилия орды!!!!!!!!!

>Четверг, 20 июля 2017, 2:31 +07:00 от Ripper007 <notifications@github.com>:
>
>Это старая проблема, даже не Близзард сделал что-то изменить, что и альянс способен с несколькими людей, чтобы держать мост и 20+ орду.  И это отчет об ошибке.  Вы можете обсудить на форумах эту проблему.
>- 
>Вы получаете это ,  потому что автор нити. 
>Ответить на это сообщение непосредственно,  просматривать его на GitHub , или  приглушить нить .


С уважением,

Бородин Иван Александрович

**Comment by Ripper007** [comment]
@tallibs Try in english next time. First of all, you didn't undestand what i've said. This is a bug post. That issue isn't a bug, it is a feature. Not even Blizzard change that in retail. There is already an lengthy post in which this "issue" is discussed.
