### ISSUE TITLE
Pickpocket lockbox issues need resolved

### ISSUE THREAD

**Issue by Zaltec** [elysium-project/server#1553]
Patch 1.1.0 Pick pocketing now has a chance of getting you a locked Junkbox, which is a locked item that generally has money in it.

Patch 1.3.0 Very high-end gems will no longer be acquired from junk boxes or pickpocketing.

Patch 1.12.0 All manner of rogue reagents can be found in locked junkboxes (obtained from pickpocketing).

Only information available from blizzard site  Allakhazam was unreliable for drop rates since it was gathered from people donating data they logged.  I do remember 100% of all lockboxes having silver inside.

This information is from blizzard website patch notes.

Right now they are completely useless in 90% of opening.

**Comment by gjcgl** [comment]
they don't care about this。。。u are not the first one asking this question

**Comment by Zaltec** [comment]
Then might as well remove pick pocket from the game until Ravenholdt reputation.
