### ISSUE TITLE
Graveyard spawning locations are incorrect in some locations

### ISSUE THREAD

**Issue by lovemonkeyz** [elysium-project/server#1554]
Prime example: If you die in Darkshore as Horde, you end up at SPLINTERTREE POST in ASHENVALE. I can't find exactly which graveyard but from memory I believe Horde should always spawn at the GY east or north of Auberdine. This I recall from attempting to raid Darnassus back in vanilla. 

most likely this issue exists in other zones as well.

**Comment by Zarant** [comment]
There is a graveyard in southern darkshore, next to the ashenvale border, but for some reason it's not used on this server.

**Comment by lovemonkeyz** [comment]
Do you not spawn there when dying in BFD as it was in Vanilla then? Because I'm sure Horde only got that GY if dead in BFD area. I could be misremembering though.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
