### ISSUE TITLE
Every Corruption or Consecration and arcane missiles tick is not proccing Wrath of cenarius

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1555]
Patch 1.12: Wrath of Cenarius: This item will now trigger from Arcane Missiles.

https://web.archive.org/web/20070906075803/http://thottbot.com/i21190

1.12 has fixed this ring so all harmful spells proc the ring such as aoe effects like arcane missiles
which was not being affected and many people complained.

It was stated it does by someone in 2006 when they fixed arcane missiles

------------------------------------------------------------------------------------------------------------

Now WorthwhilePosted: Aug 22nd 2006 6:22pm\| IP: Logged \|  Reply to this
--
By: lakewoodjoe Score: Decent  Link to this post | Patch 1.12: Wrath of Cenarius: This item will now trigger from Arcane Missiles.

-------------------------------------------------------

Wrath of Cenarius
Score 0.96 Vote: [-] [+] by fexus, 1.4 years ago
so ive had the ring now for a bit.. these are the things i can tell you.. first off, im a 21 arcane 30 fire build.. ok. being into pvp alot ive tried it out in the bgs.. it does proc off sheeps, i have yet to see it proc of silence, although it was fun in bgs i swapped it out for a +dmg +crit ring because it was too inconsistent.. now it does proc often off aoes.. just about every other iae or blastwave of multiple targets.. now in instances this ring rocks imo.. in mc im changing up between fireball scorch fireblast and it procs quite often.. also just about every other arcane missile spam it procs..yes on individual ticks.. meaning ive had it proc on the third missile and so on.. so ive changed up my fight on rag some and now go back to spamming missiles due to the ring.. sure i burn mana like mad but to see the ring proc constantly, the dmg output was worth it.. all in all.. its fun to have around.. besides.. who knows when blizz decides to revamp it. Fexus.. 60 human mage.. garona

--------------------------------------------------------------------------------------------------------------

Re: comparison to Ring of Spell Power by ferrettyke, Score -0.32
good 4 arcane missles? by Adaryllis, Score -0.38
Arcane Missile spam? Then this ring is amazing. by cbuhl79, Score 0.63

It looks like the ring was made in 1.12 to proc off arcane missiles and on every tick.

It was changed in 1.10, then it was changed again in 1.12

Fix: Make every tick of corruption, arcane missiles, consecration, proc this ring as it was meant to in patch 1.12

due to the proof that it procs on each tick of arcane missiles

IN 1,12 there is more proof showing it  was changed to affect ALL damaging spells 

holy shield drain life etc fix please

**Comment by StafordDev** [comment]
This is progressive server, which running on 1.10 (Anathema), 1.7 (Darrowshire), 1.5 (Elysium). There's no server running on 1.12. Obviously, this ring procs works correctly.

**Comment by theloras** [comment]
@StafordDev - look at the arguments for and against Thunderfury on Elysium and there you have your precedent for items not being 100% blizzlike for their patch timeline implementation

**Comment by theloras** [comment]
anyway - original bug report is here - https://github.com/elysium-project/server/issues/420
