### ISSUE TITLE
Grand Marshal's Longsword/High Warlord's Blade old stats

### ISSUE THREAD

**Issue by saigooner** [elysium-project/server#1557]
Elysium PVP

Current - https://i.gyazo.com/497e6a616847e764d5d9a8aaad453806.png
Correct - http://db.vanillagaming.org/?item=12584

**Comment by saigooner** [comment]
Shield
Current - https://i.gyazo.com/80a28c685bb9164cf5b83283a85f3265.png
Correct - http://db.vanillagaming.org/?item=18825

1H Mace
Current - https://i.gyazo.com/94502822826fa6c029e5a48e24a09bde.png
Correct - http://db.vanillagaming.org/?item=18865

**Comment by schatti2093** [comment]
no its not an issue -.- ... the pvp weps got an update to this state with 1.12 naxx but on elysium it is! Correct how it is.

**Comment by saigooner** [comment]
They upgraded half of the weapon because they INTENDED for them to be updated now, as shown in their release plan (https://www.elysium-project.org/timeline) "Grand Marshal and High Warlord PvP Honor rewards have been updated with improved statistics." Every other weapon was upgraded except for the ones linked here which is an error as stated by JosipbrozElysium who has confirmed it to be an issue.

**Comment by thepparker** [comment]
Fixed
