### ISSUE TITLE
Low level level 24 elite inmates in stockades are resisting my level 60 spells

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1558]
Low level level 24 elite inmates in stockades are resisting my level 60 spells - my judgement of command

http://imgur.com/a/0vNzf

Im sure low level mobs of this difference shouldnt resist my spells often, this has been happening often

**Comment by Sabre142** [comment]
Depends on the NPCs resistances and all spells have a 1% chance to miss.

**Comment by Mostprovidedlinks** [comment]
I just feel this is happening too often
