### ISSUE TITLE
Looks like there is a bug in LBRS boss Gizrul the Slavener

### ISSUE THREAD

**Issue by RodrigueLeboeuf** [elysium-project/server#1561]
The boss seems to drop 100% of the time wolfshear leggings. I've done it 17 times and everytime its the same. Wolfshear leggings at 100% droprate looks fishy, so I was wondering if there was some kind of bug/script that stopped me from having my t0 spaulders.

**Comment by GuybrushGit** [comment]
Fixed in new database.
