### ISSUE TITLE
Blackhand's Command only drops for 1 person per raid

### ISSUE THREAD

**Issue by ascendancy05** [elysium-project/server#1564]
Currently hundreds of people in Blackrock mountain, in raids, trying to get the drop. Seems to only drop for one person per raid, confirmed on multiple kills across multiple raids. Is this expected behavior?

**Comment by Tunesisback** [comment]
I've heard conflicting 1st hand reports, of a player from SolidCore 1 hour ago said that in his 40 man raid each person was able to loot the letter, and that the respawn on quartermaster was 4 minutes.

I'll confirm myself asap

**Comment by ascendancy05** [comment]
Closing as this was ninja hotfixed earlier today by the staff
