### ISSUE TITLE
[Elysium] no longer able to turn in AB, AV, or WSG marks

### ISSUE THREAD

**Issue by tellio02** [elysium-project/server#1566]
After todays patch, it is no longer possible to turn in AB, AV, or WSG marks for the quest in any of the horde major cities.

**Comment by Ripper007** [comment]
I have the same issue on one character but on Darrowshire, i tried everything, relogging, deleting wdb, disabling addons. I only have Alterac Valley but not the other battlegrounds.

**Comment by Hyperial** [comment]
Same on Alliance side, is there a fix for turning in the marks problem?

**Comment by darbai** [comment]
I have the same issue. Alliance lvl 39 on Elysium.

**Comment by Gropy** [comment]
Same issue, this is a massive issue for rankers and should be fixed as prio if possible.

**Comment by thepparker** [comment]
Fixed
