### ISSUE TITLE
T1 Arcanist (mage) still incorrect with patch 1.5-1.6 (Elysium)

### ISSUE THREAD

**Issue by rebellone** [elysium-project/server#1568]
Item set still old after update AV and didnt changed from https://github.com/elysium-project/server/issues/1347 .
Correct: http://db.vanillagaming.org/?itemset=201
Here proof: http://wowwiki.wikia.com/wiki/Patch_1.5.0
 The following item sets have had their statistics, effects, and set bonuses updated: **Arcanist**, Netherwind, Prophecy, Transcendence, Felheart, Nemesis, Cenarion, Stormrage Raiment, Nightslayer, Bloodfang, Giantstalker, Dragonstalker, Earthfury, Ten Storms, Might, Wrath, Lawbringer, and Judgement.

**Comment by thepparker** [comment]
This set is updated again in 1.9, so the current stats are correct.
