### ISSUE TITLE
Aquadynamic fish attractor

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#1569]
The info says it will boost your fishing skill by 100 for 5 minutes (which would be the correct amount of time in vanilla), but the buff lasts for ten minutes.

**Comment by thepparker** [comment]
Are you using the lens or the attractor?

**Comment by Pisshead** [comment]
The aquadynamic fishattractor which engineers can build with bronze bars coarse blasting powder and nightcrawlers. After applying it to your fishing rod the buff in the upper right corner of the GUI displays that it will last for 10 minutes and does so too
