### ISSUE TITLE
Gathering tries with orange herbs/mining nodes do not work as supposed

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#1571]
If you try to gather something, which is, according to your skillpoints, orange, it should always cast to the end and only in the end it should tell you that it was a failed attemp. As by now it doesn't even cast the mining (for example), but already tells you in the beginning it was a failed attempt.

**Comment by luigimannoni** [comment]
Should've been fixed today.

**Comment by thepparker** [comment]
Fixed
