### ISSUE TITLE
Skinning bug?

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#1572]
I'm not sure about this one, but I think it's not the way it's supoosed to be: I can't remember in classic wow that you would skin something and not get anything. I think you got something in return on every attempt, but I might be wrong with this one.

**Comment by Phoosy** [comment]
You need some kind of citation or proof that this is supposed to be the case. Your Issue report needs substantiation beyond your own memory.

**Comment by luigimannoni** [comment]
Regardless of own memory sadly there's no proof, citation or mention anywhere. 
The complete absence of any mention of empty skinning loot or a patch note that states skinned mobs always drop loot should be a solid proof that skinning was always meant to be that way. 

In any case that has been already fixed on PR #1094 and that should be live with today's patch.

**Comment by thepparker** [comment]
Should be rectified, update if the issue persists
