### ISSUE TITLE
George Candarte Leatherworking supplies

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#1577]
![grafik](https://user-images.githubusercontent.com/26183948/28384276-69128d46-6cc4-11e7-9c99-22f687de6700.png)

His texture is kinda missing?

**Comment by Pisshead** [comment]
Thoradin's wall in the north is his position

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
