### ISSUE TITLE
Barov Peasant Caller doesn't work for alliance

### ISSUE THREAD

**Issue by wambam22** [elysium-project/server#1578]
Barov Peasant Caller trinket is just a blue item that says Trinket, with no use effect. It should summon three servants. I see horde using it in bg's.
screenshot: http://imgur.com/a/eo25l
item db: http://db.vanillagaming.org/?item=14022

**Comment by kampeador** [comment]
Your issue is related to itemization. Should be fixed with the next upgrade.
https://github.com/elysium-project/database/commit/90b608c0f236df73e02505050501a3b0542cc7c3

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
