### ISSUE TITLE
Elysium unable to logon

### ISSUE THREAD

**Issue by hylsan** [elysium-project/server#1580]
The client just says "disconnected from server" does that affect everyone or just me? :)

**Comment by memeroni** [comment]
same here dude

**Comment by HawtStuuf** [comment]
I think they are currently patching new content although i am not sure when they will be done

**Comment by HawtStuuf** [comment]
New in 1.6

"Blackwing Lair" Raid opened
Tier 2 Sets
"Bindings of the Windseeker" are now available on Garr and Geddon.
New recipes available from Argent Dawn, Timbermaw, Thorium Brotherhood reputation vendors and Lokhtos Darkbargainer in Blackrock Depths.
Grand Marshal and High Warlord PvP Honor rewards have been updated with improved statistics.
Warsong Gulch has new item rewards at the appropriate faction vendor near the entrance in the zone. These are available starting at Honored faction.

**Comment by Phoosy** [comment]
Game issues such as being unable to connect do not belong on the Github. See our Twitter/Website or forums for more information and assistance connecting.
