### ISSUE TITLE
[Anathema] Dire Maul North Bugged

### ISSUE THREAD

**Issue by ramangan** [elysium-project/server#1586]
- Cho'Rush is friendly even before engaging the King. She emotes things like "you will die...." etc during fight but doesn't stand up.

- No tribute chest spawns after talking with NPC requesting it

- Leaving party does not send you to hearth in 60 seconds. Also, I was unable to reset the instance using the script resetInstance command.

**Comment by thepparker** [comment]
Likely a result of a bugged lock out
