### ISSUE TITLE
Lesser firestone problem

### ISSUE THREAD

**Issue by spheed** [elysium-project/server#1587]
The text for the spell Create Firestone (Lesser) states at the end: "In addition, equipping the Lesser Firestone increases the damage done by fire spells by 10." However when equipped this damage increase is not applied, checked by looking at the combat log. On the item, there's only one "Equip:" effect for its buff to your main-hand weapon.

The item should have a second "Equip:" on it which reads: "Equip: Increases damage done by Fire spells and effects by up to 10." This effect should also actually be applied in-game.

http://db.vanillagaming.org/?item=1254

**Comment by thepparker** [comment]
Clear WDB for up-to-date item tooltips
