### ISSUE TITLE
Dawn Treaders have no stats

### ISSUE THREAD

**Issue by Kvel2D** [elysium-project/server#1591]
![2017-07-20 15_25_55-world of warcraft](https://user-images.githubusercontent.com/13269470/28415349-f42e85a4-6d57-11e7-91d9-9fe804f94f32.png)
Deleting WDB didn't help. Should have 18stamina, and +1% dodge.

**Comment by Razorwynd** [comment]
Can you please fix these... it has been more than a month!

**Comment by Borgean** [comment]
Hey, same issues as the guys before, any ETA ?

**Comment by Borgean** [comment]
Bump

**Comment by tanknstein** [comment]
bump

**Comment by brotalnia** [comment]
![tee](https://user-images.githubusercontent.com/6519171/31088066-012a1b94-a7a8-11e7-855a-6370886b666a.jpg)
No issue on development branch.

**Comment by tanknstein** [comment]
still no stats on Elysium, per original post

**Comment by GuybrushGit** [comment]
Should be fixed when new database goes live.

**Comment by tanknstein** [comment]
When will that be?  Oct 4 update did not fix the issue.

**Comment by Kvel2D** [comment]
Issue was fixed.
