### ISSUE TITLE
Blazefury Medalllion doesn't scale properly. item=17111

### ISSUE THREAD

**Issue by wowaskov** [elysium-project/server#1592]
It should scale off 50% of spell power. Proof is on WoWhead. Sametbh, a paladin on Nostalrius that i talked to confirmed that it did scale off spell power on Nostalrius before the transition over to the Elysium core.

http://db.vanillagaming.org/?item=17111#wh-comments
http://wow.gamepedia.com/Blazefury_Medallion

**Comment by theloras** [comment]
oh my sweet summer child...devs nerfed all the elemental proc items like 6 months ago

**Comment by Gebius** [comment]
@theloras do you have a link to that patch? ... couldnt find anything , but i noticed that Elemental deck : Maelstorm    has an abyssal procc rate

**Comment by theloras** [comment]
no they took down the original bug reporting repository on the website but suffice to say they made a conscious decision to remove the scaling
