### ISSUE TITLE
The quest I See Alcaz Island In Your Future..., bloodkelp drop

### ISSUE THREAD

**Issue by Amizaar** [elysium-project/server#1597]
I have a quest I See Alcaz Island In Your Future... (http://db.vanillagaming.org/?quest=8970) and killed more then 20 nagas and Bloodkelp (http://db.vanillagaming.org/?item=22094) didn`t droped for me. 
Can you be sure that drop chance is 20%?

**Comment by ramangan** [comment]
Did it last night. The drop rate ends up being around 15-20% because they can drop 2 at a time. Look for the baskets, those drop 1-3 bloodkelp and spawn faster than the mobs. There's one in front of the house left of the first fork, and another up top of the hill by the purple summon event. GL!
