### ISSUE TITLE
Death Talon Hatcher in BWL is bugged

### ISSUE THREAD

**Issue by wowaskov** [elysium-project/server#1598]
https://www.youtube.com/watch?v=lMwk4CY4c6c&feature=youtu.be

http://db.vanillagaming.org/?npc=12468

NPC just spawns brieftly and despawns. spooky stuff i say.

**Comment by theloras** [comment]
thats just the gauntlet respawn timer going off but then realizing that you have killed broodlord so the actual npc then despawns - its fine - happens to everyone

**Comment by thepparker** [comment]
Side-effect of hacky prevention of boss-specific mobs respawning
