### ISSUE TITLE
Stuck in Party / Raid

### ISSUE THREAD

**Issue by Athahlali** [elysium-project/server#1599]
Playing on Anathema. 

Currently unable to join or invite people to a party. Message that flags up is "You are not the party leader". 

When checking portrait to leave supposed party or raid that I may be in, the only option is to reset all instances. 

Any help would be fantastic.

Cheers.

**Comment by luigimannoni** [comment]
Does the command `/script LeaveParty()` work for you?

**Comment by Athahlali** [comment]
Just tried this and yes it does. Thank you very much for the help. :)
