### ISSUE TITLE
Cannot turn in Marks of Honor

### ISSUE THREAD

**Issue by Nakiri-WP** [elysium-project/server#1600]
Since the release of BWL, the turn-in NPC's for Marks of Honor do not work.  People like me have Marks of Honor that we worked hard for wasting away and disappearing in our mailboxes after expiring because these NPC's still have not been fixed.  All that precious Rep & Honor is just RIP?  Please help...
(Elysium)

**Comment by EgeusH** [comment]
I second this claim, it's very uresting that there's been no official post on such an important matter.

**Comment by Tarnumx** [comment]
cant turn it too

**Comment by Milfore** [comment]
Same, any suggestions/fixes incoming?

**Comment by darkwen** [comment]
same here on Anathema.
