### ISSUE TITLE
Retribution aura should be affected by vengeance  - Paladin bug

### ISSUE THREAD

**Issue by supasteed** [elysium-project/server#1601]
Ret aura should be affected from vengeance 

Gives you a 15% bonus to Physical and Holy damage you deal for 8 sec after dealing a critical strike from a weapon swing, spell, or ability.

 just like in this video, watch 5:15-5:50 very very carefully in slow motion
https://www.youtube.com/watch?v=Y1_jBM9Jkpk&t=5m13s
Nov 5, 2006

Pre Tbc stated in description

He has 20 damage ret aura and it becomes 23 when 15% vengeance procs

I tested it and it doesnt work, the damage of this level 38s ret aura remained 8
https://youtu.be/wyocdPdz6Bs

Fix 

- Make Ret aura affected by Vengeance

**Comment by theloras** [comment]
Ret Aura should also benefit by +10% if a 2nd paladin is in the group and provides Sanctity Aura

**Comment by Xaph-er** [comment]
That video was from the TBC pre-patch. Prior to that patch nothing affected Retribution Aura.

**Comment by theloras** [comment]
wrong @Xaph-er - sanctity aura from a 2nd paladin boosted it by 10%

**Comment by theloras** [comment]
that i can confirm 100% from my own personal playing

**Comment by Xaph-er** [comment]
Fair enough. I don't remember sanctity aura buffing it but vengeance definitely didn't.

**Comment by GuybrushGit** [comment]
Why do you say the video was from the TBC pre-patch? 
Uploaded in November and in the description he says "pre-TBC build", seems pretty solid evidence.

**Comment by supasteed** [comment]
Thanks @GuybrushGit

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
