### ISSUE TITLE
Plans: Dawnbringer Shoulders still broken after BWL patch.

### ISSUE THREAD

**Issue by AugustAPC** [elysium-project/server#1602]
I previously reported that the plans for Dawnbringer Shoulders weren't working correctly. It was stated in the recent BWL patch notes for Elysium that they have been fixed.
This is not the case. Upon using them, you still get the error message: "Missing Reagent: Thorium Bar."

**Comment by kampeador** [comment]
Have you cleaned your WDB folder?
