### ISSUE TITLE
Stuck in Feral form

### ISSUE THREAD

**Issue by Gebius** [elysium-project/server#1604]
Realm Anathema / Character Gebius / Bug : Stuck in Bearform
Similiar to the fix that was referred to in 19th july patch notes :

https://elysium-project.org/updates/2017-07-19

I have been Stuck in Bearform a lot , with the only possibility to shift out was via Spellbook(not via Ability KeyBinds)
It has only ever happened in Raids though .... at least I cant remember having the bug in Dungeons , Battlegrounds or open world.
I havent been able to actively reconstruct the bug, so I am not quite sure what would cause the bug.
Possibly It has to do with buff cap.

Anyways , as similiar Bug got fixed. And I have been seeing it lots , but being unable to reconstruct.
I hope someone finding this thread ,knows more about it.

**Comment by thepparker** [comment]
What's the error you get?
