### ISSUE TITLE
[Darrowshire] Pet ability Screech does not generate proper aggro/threat

### ISSUE THREAD

**Issue by Amanugai** [elysium-project/server#1607]
Issue: The pet ability Screech does not properly generate aggro on surrounding mobs affected by Screech (-100 Melee Attack Power).  This was a noted problem in Nostalrius but doesn't seem to be fixed in Elysium.  I have tested in game allowing up to EIGHT applications of Screech (both auto-cast and manual cast) on mobs that were not the main target and attacking them with auto-shot/multi-shot to find that no threat was applied as the mob instantly aggro'd on me each time. 

The issue was originally noted here: https://forum.nostalrius.org/viewtopic.php?f=38&t=36720
Asides from the threat issue, auto-casting is not an issue; my carrion bird applies Screech properly (roughly every four seconds when the previous Screech debuff duration wears off).

Proper behavior:
http://wowwiki.wikia.com/wiki/Screech 
Roughly 50% aggro of Growl per application of Screech.  At the very least apply threat/aggro equivalent to AP reduction like Demoralizing Shout from Warriors (-140 MAP = 140 threat).

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
