### ISSUE TITLE
Imp Delivery quest dosn't complete

### ISSUE THREAD

**Issue by Blackmace81** [elysium-project/server#1610]
when doing the imp delivery quest in Scholomance it dosn't complete when at lab.

is there anything you guys can do?

best regards
Blackmace of Valhall

![wowscrnshot_072117_005805](https://user-images.githubusercontent.com/30329285/28442642-a4708aa8-6db1-11e7-9782-47359db5a2ad.jpg)

**Comment by thepparker** [comment]
Can you post a screenshot of your quest log? Try deleting your WDB folder too. You will get credit for the parchment when the imp teleports away, however the imp itself 'keeps' the parchment.

**Comment by Blackmace81** [comment]
deleting the WDB folder helped on the problem.. thx
