### ISSUE TITLE
Too many mining nodes in one spot

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#1613]
from time to time it happens that multiple mining nodes can be found in one spot. Somehow the server doesn't check, if after the respawn time in this region one node already exists and just adds a new one. This leads to being multiple mining nodes in one spot/ mining node area. I don't know if this is intended, because of the high player amount on the server, but in classic this wasn't the case.

**Comment by thepparker** [comment]
Do you mean multiple nodes literally on top of eachother, or in the vicinity?

**Comment by Pisshead** [comment]
In vicinity, but even if it is only in vicinity to my knowledge this is still wrong and doesn't make sense considering the game mechanics in my opinion. And some mining spots and herbs are totally unreacheable or hidden in tree stems or hills. Should I send you the coordinates for these? Thanks for the good work by the way! needs to be said once in a while too ;) :)

**Comment by thepparker** [comment]
Some locations have an abundance of nodes. The logic does not check for nodes in existence within the radius of the harvested one, but for nodes within the same pool. There's an existing issue report where you can make mention of unreachable nodes.

**Comment by Pisshead** [comment]
But the logic should check for it. There are already too many gold selling hardcore farmers so they just profit from that issue

**Comment by Pisshead** [comment]
![mining nods](https://user-images.githubusercontent.com/26183948/31538948-6b4431ce-b007-11e7-9ecf-3a3433ff35aa.PNG)

That's what shouldn't happen
