### ISSUE TITLE
anathema warsong item bug

### ISSUE THREAD

**Issue by Clonnnn** [elysium-project/server#1617]
hi im anathema warlock player clon
my lock is rank 12 and wsg exalted

but i can't buy wsg trinket rune of perfection 20lvl
caster dps buy 40lvl rune of perfection but 20lvl rune of perfection not on the list
so i verify a fact our guild member class warlock
same problem

but melee dps can buy both trinket 20 and 40lvl

i want to buy caster trinket 20lvl rune of perfection

plz help problem

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
