### ISSUE TITLE
Elysium - [Quest] Timbermaw Ally is MISSING (important reputation quest)

### ISSUE THREAD

**Issue by Bearmanpig** [elysium-project/server#1620]
Current situation: As the title sais, the quest [Timbermaw Ally](http://db.vanillagaming.org/?quest=6131#wh-comments) [(wowwiki)](http://wowwiki.wikia.com/wiki/Quest:Timbermaw_Ally) is missing for my level 53 Undead Warlock on Elysium. The questgiver [Grazle](http://db.vanillagaming.org/?npc=11554) can be interracted with for gossip text, but no quests are offered.

Desired Situation: Offer this quest to everyone that is eligible. This quest is very important to get to unfriendly rep with the TImbermaw, so they won't attack you on sight.

Sources: The comments left on [Thottbot ](https://web.archive.org/web/20070317183008/http://www.thottbot.com:80/q6131) suggests this quest has existed as early as september 2005 (the linked page is from march 2007, the comments are 1.4 years old at that point) Elysium is currently on patch 1.6 (released July 2005), no mention of added Timbermaw quests has been made in patchnotes between July 2005 and September 2005, so I can only conclude the quest has to be available at patch 1.6.

**Comment by Zarant** [comment]
Timbermaw hold quests were added in patch 1.9.

> Old quests have been revised, and several new quests involving the Timbermaw Furbolgs have been added. 

http://wowwiki.wikia.com/wiki/Patch_1.9.0

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
