### ISSUE TITLE
Traveling Merchant(Greishan Ironstove) in Loch Modan isn't traveling

### ISSUE THREAD

**Issue by LollingChris** [elysium-project/server#1622]
He's just staying at where he is at (25,12), not moving an inch.

![image](https://user-images.githubusercontent.com/15726503/28467771-825049ba-6e63-11e7-85c4-3a08589a86f5.png)

**Comment by GuybrushGit** [comment]
This NPC is not missing waypoints so its prob just stuck. 
Prossibly fixed by https://github.com/elysium-project/server/pull/1380
