### ISSUE TITLE
Elysium [Quest] - The Monogrammed Sash / The Captain's Chest

### ISSUE THREAD

**Issue by Enuhal** [elysium-project/server#1624]
It's currently not possible to start the Quest "The Monogrammed Sash" - clicking on the supposedly quest-starting item obtained from the sea giant simply does nothing. The NPC involved in this quest chain, Captain Hecklebury Smotts, also give you the quest "The Captain's Chest", which is something he should do.

**Comment by sipertruk** [comment]
"The captain's chest" is unrelated.
Do you mean that Sprogger shouldn't give "The captain's cutlass" before "The Monogrammed Sash" is done ? 
The same is happening on Darrowshire.
It works with the current uploaded database so it should be a problem in the running servers db, nothing we could do here.

**Comment by Enuhal** [comment]
No, that's not what I'm saying. What I'm saying is that right now, you can pick up neither of these quests at all - neither the Captain nor Sprogger give you any quests, and right clicking on the item that's supposed to start "The Monogrammed Sash" doesn't start the quest, it does absolutely nothing.

**Comment by thepparker** [comment]
The quest is introduced in a later patch
