### ISSUE TITLE
Primal Blessing animation bug

### ISSUE THREAD

**Issue by Bloodmoon-Darrowshire** [elysium-project/server#1633]
![wowscrnshot_062517_141224](https://user-images.githubusercontent.com/30354821/28478646-212958d0-6e7b-11e7-972b-b41499247c37.jpg)
![wowscrnshot_072217_003252](https://user-images.githubusercontent.com/30354821/28478656-2b252da0-6e7b-11e7-9653-ceacd06860dc.jpg)
![wowscrnshot_072217_003300](https://user-images.githubusercontent.com/30354821/28478665-334e2d6a-6e7b-11e7-81da-53fec1b3915a.jpg)

**Comment by thepparker** [comment]
Client controlled
