### ISSUE TITLE
Pamela's Doll Quest

### ISSUE THREAD

**Issue by MBlood66** [elysium-project/server#1635]
I'm having an issue with the quest "Pamela's Doll" in Eastern Plaguelands. I've gone through the buildings in Darrowshire multiple times and there are no doll parts spawning to pick up, making the quest impossible. Is it just me or can no one finish the quest?

**Comment by Urgarok13** [comment]
Tried it multiple times yesterday same problem

**Comment by Shadowveil** [comment]
Same issue two days in a row on ELy. no doll parts anywhere but the ghosts spawn.

**Comment by stavrosvougo** [comment]
I stayed in the area for 3 hours yday. I got both limbs and i only need the head now. Never seen it spawn. Tons of people come and go. It seems the items spawn but maybe only once a day. Also most of my guildies said they did this quest without any problems so there might be problem with the new patch.

**Comment by Ordalito** [comment]
Tried yesterday for approximately 1 hour and half and hour today. No spawns for me.

**Comment by taxoro** [comment]
Tried it aswell over the couple of days, zero doll spawns, lots of ghosts. 

I never had any issues completing this quest on anathema or nostalrius, not sure what went wrong here, because it's definitely not working as intended.

**Comment by kschroeder31** [comment]
Can confirm. Spent way too long looking for them before I came here.

**Comment by Pattaclack** [comment]
Hello, 
I have the same problem. 
I took the quest [55] Sister Pamela given by Jessica Redpath in winterspring. Then i found Pamela in Darrowshire. I turn the quest get the follow up and there are no doll part spawning. But the goshts spawn.

I need to complete this quest for the rewards of Hidden treasure the ring of protection a BIS for Druid tank

**Comment by Bluntedstunt** [comment]
Hi, I play on Darrowshire and have been having this same problem for the last few days, I show up to the area every day to look for doll parts and face the same negative result. I am unable to do complete other quests as well cause this is a prequest to many others.

**Comment by Bootsybb** [comment]
hello, it seems like this quest is still bugged. i've done it on my warrior 2-3 months ago but i'm unable to obtain two of the parts on my druid. (I got one part, I mightve been lucky with a server crash/maintenance? or it wasn't broken at that point) it couldve to do that the respawn timer is broken and doesnt let it respawn or sth? idk.

**Comment by ruscur** [comment]
There's a respawn issue, anyone who needs this quest completed should aim to do it immediately after a server restart until it's fixed.

**Comment by Heyhohohoho** [comment]
still fucking bugged

**Comment by kschroeder31** [comment]
#druidtankslivesmatter

**Comment by hazzzy** [comment]
Just did this without a problem. The doll parts are all present and they seem to respawn after a few seconds. Upon approaching the doll part one ghost spawns and another ghost spawns after picking up the doll part.
Head -> northern house
Left side -> house ruins to the south
Right side -> bottom of the stairs in the largest house

**Comment by Heyhohohoho** [comment]
Sorry for the earlier bump, it wasn't bugged, i just didnt know how it worked. sry.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/52678-development-update-23082017/

**Comment by jtanman** [comment]
Was able to pick up two pieces and found the third but it wasn't clickable.
