### ISSUE TITLE
[Elysium] Un Goro Crystals of power not spawning

### ISSUE THREAD

**Issue by zaboti** [elysium-project/server#1638]
Yesterday and today all players in un goro could not locate any power crystal spawns for Crystals of Power quest.

**Comment by dogmax** [comment]
The power crystals are getting farmed heavily. Maybe that's the reason? I found a lot after the server restarted, so maybe the respawn rate is not as it should be?

**Comment by Blackbear123** [comment]
Just did a full circle, found 0 crystals. /who counts 15 players in the zone, 13.00 ST .

**Comment by blubba22** [comment]
There has to be something wrong with them!

**Comment by ifyousayso** [comment]
Wild guess: The power crystal nodes are the only ones (or some of the few) that choose randomly from 4 objects when spawning.. unlike the other nodes that have a fixed object per node. A recent patch broke the respawning behaviour of these nodes, but it's quite possible that all of them are up at server start!

**Comment by thepparker** [comment]
Duplicate
