### ISSUE TITLE
cant ressurect 

### ISSUE THREAD

**Issue by amphus** [elysium-project/server#1641]
I died in felwood, when I ran back to my body, i hit "accept" to resurrecting, and no matter how many times i press it i will not resurrect. i then tried going back to the 2 spirit healers in felwood, but neither of them are there (i have a map pulled up and i am in the right spots, i just cant see them) please help me

**Comment by JosipbrozElysium** [comment]
Not a bug report. Write an ingame ticket for assistance!

Best regards!
