### ISSUE TITLE
[Anathema] Lord Valthalak won't re-spawn in UBRS

### ISSUE THREAD

**Issue by ramangan** [elysium-project/server#1642]
Summoned Lord Valthalak for T0.5 questline and wiped on him. Went back to the room and I can place the Brazier on the ground, but he, or the adds, don't appear.

**Comment by thepparker** [comment]
You can only summon the T0.5 bosses once per instance lockout. I don't know why he despawned, however, unless you took an abnormal amount of time between pulls.
