### ISSUE TITLE
[Quest] - Unable to pick up "Pirate Hats Ahoy!" and "Southsea Shakedown"

### ISSUE THREAD

**Issue by MokIph** [elysium-project/server#1643]
The first time I talked to the NPC's I was able to pick up the quests, 
but I saved it to later at higher lvl.

Now the NPC's dont offer me any quests, so can't pick up the quests.
It has happend with other quests aswell, but I haven't bothered / thought it was just random bug.

This is on my character called "Iph"
Yes I have deleted WDB.

**Comment by ANENKELM** [comment]
Yes, it seems that this is bugged. The quest(s) above should be available to every character with min. level 40. Other quests don't work properly too. For example "Freedom for all Creatures" part two (also mentioned in #1667) is not obtainable. Other quests have a problem with the minimum level requirement. Like "The Platinum Discs". You can get the Quest from Uldaman and bring the Discs to the Dwarf in Ironforge, you also get to see the follow up quest. If you try to accept it, the error message "Your level is too low" or something pops up. I had this problem with other follow-up quests too, but ignored it. So I think that this is a bigger issue which affects gameplay in a negative way.

**Comment by Zarant** [comment]
Which server are you playing on? Those quests shouldn't be available on Elysium for sure, I don't know about other servers, they were added much later into the game.

**Comment by ANENKELM** [comment]
I personally play on Elysium. Well, if thats true then everything is all right, didn't knew that they were added later. Except for the min level requirements for follow-up quests I guess. But maybe thats vanilla too, i don't know, it just feels wrong.

**Comment by thepparker** [comment]
Added in a later patch

**Comment by ehatle** [comment]
This bug still persists for me.
