### ISSUE TITLE
Transmute Elemental Fire needed badly

### ISSUE THREAD

**Issue by ssishtar** [elysium-project/server#1647]
I know this is not a bug but Elysium population is 3-4 times bigger than the highest server on live retail 2005-2006, making impossible farming Elemental Fire, not counting the mafias that have all zones under control.  This makes Elemental Fire price going insane, sometimes even more than 10 gold per one, totalling a horrible raiding experience for everyone.

The solution is put ingame the Thorium Brotherhood Transmute Elemental Fire http://db.vanillagaming.org/?item=20761 a bit earlier than retail Patch 1.9. In 1.9 we wont need it anyway since we'll be in AQ40. Please devs, consider this, the Elemental Fire IS a huge problem right now and it's making everyone's life completely miserable, adding only frustration and unhappy players.

**Comment by Ravyd** [comment]
Farm BRD
??
Profit

**Comment by ssishtar** [comment]
mate, how you can farm BRD lol, you can do even 4-5 full runs and you can't get 1 elemental fire really...
