### ISSUE TITLE
There is no Spice Bread skill in cooking trainer's skill set

### ISSUE THREAD

**Issue by LollingChris** [elysium-project/server#1648]
Spice Bread should be available when you cook skill is 1. 
But there is no such thing in Elysium. I checked every trainer. None of them could teach me that, which is wrong.
![image](https://user-images.githubusercontent.com/15726503/28490765-c821476c-6f14-11e7-9443-9ae35cf30499.png)
![image](https://user-images.githubusercontent.com/15726503/28490768-d66df220-6f14-11e7-86d5-ae84c87f25c5.png)

**Comment by kampeador** [comment]
Spice Bread was added in TBC.

**Comment by AndreRieu1949** [comment]
lol

**Comment by LollingChris** [comment]
@kampeador thanks for clarification。 i was misled by the vanilla guide addon...
