### ISSUE TITLE
Anathema [Herbalism] spawn timers back to pre-buff state

### ISSUE THREAD

**Issue by AndreRieu1949** [elysium-project/server#1649]
Currently every major herbalism zone is emptied for herbs and prices are skyrocketing 2-300% once again. It seems herb respawn was put back to pre-buff state along with patch 1.10.

https://forum.elysium-project.org/topic/50380-herb-respawn-bugged/

**Comment by Trsko** [comment]
Been herbing for 3-4 hour some days for a few weeks, Gromsblood is back on 45-50 minute respawn rate

**Comment by AndreRieu1949** [comment]
Black Lotus is still on a 1hr timer and most herbs still don't seem to be interacting dynamically. Same can be said for rich thorium veins which have 45 minute + respawn timers.
