### ISSUE TITLE
Black lotus is messed up on Elysium due to recent bugs

### ISSUE THREAD

**Issue by ninjalootah** [elysium-project/server#1653]
A gm removed a spawn point from the game when the black lotus was spawning in the same spot over and over again.  So in turn... Now if the lotus is supposed to spawn in that location, it cannot spawn. therefore it won't respawn again, because it is never looted, which never sets off the trigger in the code to spawn more... So lotus will only spawn up until this spawn point is chosen. there after never spawning again until crash/reset.  

This is currently in burning steppes on elysium, and the other zones could be affected as well, please fix within the next 12 hours, it's so easy a caveman can do it.

**Comment by ninjalootah** [comment]
It's not spawning again, 52,63 is the location where it is supposed to spawn and causing the issue (this spot was removed by some GM which messed up the whole spawning situation).  Also this issue exists in winterspring, but unsure of which spawn.  It will be one of the 15 spawns that are available during non blizzlike populations/crashes... Which can also result in 0 lotus all day in between crashes

**Comment by ninjalootah** [comment]
Black lotus on Elysium does not respawn in burning steppes, and winterspring as well. This was due to a recent issue where the black lotus would spawn in the same location every respawn timer in all zones. And a gm thought it was a good idea to remove the spawn location, instead of correcting the issue.. So now this spawn location still persists, however nothing appears for players to loot because it is removed, yet the coding tells the server that it is spawned.. Which then requires a loot trigger for it to appear again, so now there is just an invisible lotus at 52,63 in Burning Steppes that is unlootable by players and there is not a single thing we can do about it, except wait for server crashes and hope it doesnt spawn there to bug it again.

It happened on the 2nd respawn after the crash 20 hours ago, which is honestly completely cancerous. 

So this issue of spawning in the same location is not related to the spawn location at all, as apparently the GM had thought, as I've seen this many times on nostalrius and elysium.. I don't know the cause but some players do know how to do it I am sure, it will only happen after a crash as well.. but all that needs to be done is the re implement the spawn points that the GM had removed, and it is solved. I would do it myself, but I lack required permissions to alter anything with the server sadly.

As it is not location specific, there is no reason to not reimplement it, nor was there a reason to remove the spawn point :D . Let's get this fixed finally today! My free time= farm lotus, it would be nice to get back my favorite activity!

**Comment by l1amm** [comment]
How do you know this issue is caused by a single spawn that was improperly disabled by a GM ?

**Comment by ninjalootah** [comment]
I get over 100 a week and it has not spawned there since it was removed, and after the fix they did they re enabled this spawn point.  However it is still removed, confusing yes. but it spawns there without actually being there now.

**Comment by Noxxel** [comment]
There definitely is a problem with the Lotus spawns in Burning Steppes and Winterspring.
I do not have as much insight as ninjalootah, but i can confirm that this is a real problem.

**Comment by ninjalootah** [comment]
thanks josip :)
