### ISSUE TITLE
It's a Secret to Everybody un'goro quest chain bugged

### ISSUE THREAD

**Issue by staplerx300** [elysium-project/server#1656]
This quest:
http://db.vanillagaming.org/?quest=3845

It gives you a small pack with 3 items in it when you click on the bag in the stream. Once you get it it's impossible to take the items out of the bag. Observe:

https://www.youtube.com/watch?v=h_4pAtVHfLU

Pls fix.

**Comment by staplerx300** [comment]
really want that boomerang lads :(

**Comment by zaboti** [comment]
Happened to me yesterday. Logged out and logged in, then i was able to open

**Comment by dogmax** [comment]
Happened to me two days ago. I kept the small pack in my bags and tried to open it again a couple of hours later. Then it worked.

**Comment by thepparker** [comment]
Duplicate #1278

**Comment by Elitegamer010** [comment]
same problem here
