### ISSUE TITLE
The Torch of Retribution quest problem.

### ISSUE THREAD

**Issue by Paramaunt** [elysium-project/server#1657]
Hi!
Was killed by mob before loot of the torch (saw this torch infront of me). No item was there after my ressurection. How could i get quest item now?

Thank you.

**Comment by kampeador** [comment]
There are some rare bugs with this event.
You have to wait until another player will start this quest event, and you'll be able to take the torch.

**Comment by Paramaunt** [comment]
But will that player be able to get this torch after?

**Comment by kampeador** [comment]
yes

**Comment by GuybrushGit** [comment]
Abandoning the quest and retaking will spawn another torch.
