### ISSUE TITLE
[Mage] Amount of conjured food/water tooltip doesn't update with new level

### ISSUE THREAD

**Issue by luigimannoni** [elysium-project/server#1659]
Any mage Conjure food/water spell has a tooltip which states: `Conjure X bottles of fresh water ...` / `Conjure X muffins...` where X should should reflect the additional items conjured for each extra level starting from the spell trained level base, at the moment always displays `2`.

**Comment by thepparker** [comment]
Tooltips are client-side

**Comment by luigimannoni** [comment]
Still... the tooltip was always correct on live server. 

Seems this behaviour it's only happening in private servers and a quick Google search do confirm it was a bug present on Nostalrius as well as some TBC emulator.
