### ISSUE TITLE
[Item] Using scrolls while having a powerful spell on destroys the scroll without applying any buff.

### ISSUE THREAD

**Issue by luigimannoni** [elysium-project/server#1660]
For example, using a `[Scroll of Stamina]` (+2 stamina) while having on `Power Word: Fortitude Rank: 2` (+8 stamina) destroys the scroll.

It should display a `A more powerful spell is already active` error.

**Comment by l1amm** [comment]
I always thought this was wrong as well... Assuming maybe int potions should do the same when you already have arcane intellect.

**Comment by thepparker** [comment]
Attempting to use an item which would not stack should yield a "You have a more powerful effect active" (or whatever it is) error

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
