### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Jerkypatrick** [elysium-project/server#1662]
Connection to the server goes through but the handshake will not complete, it then times out and disconnects from server.

**Comment by TheDipper315** [comment]
Same problem... when logging in, it says connected but then times out and says Disconnected from server. I was logged in just 10 minutes ago as well

**Comment by JosipbrozElysium** [comment]
Not a bug report. For server downtime, check out our twitter: https://twitter.com/elysium_dev

Best regards!
