### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by TheDipper315** [elysium-project/server#1668]
Connection to the server goes through but it will not finish. It then times out and Disconnects from server. (I was just logged in and playing 15 minutes ago)

**Comment by Fluwback** [comment]
Same for me.

**Comment by TheDipper315** [comment]
Still working on it...
After hitting the typical escape button or cancel while it tries to connect, I realize I can only log in to Anathema(which I don't have a character on.) Darrowshire and Elysium are both inaccessible.

**Comment by xdingo** [comment]
same for me. I have tried renaming WDB and WTF folders to WDB2 and WTF2 but still stuck at character selection screen then disconnected.

**Comment by LollingChris** [comment]
@xdingo no need to try that, the servers are down

**Comment by gore23** [comment]
Same, Only for Elysium Server though. Connected, but not actually going in and showing characters, and letting enter game.

**Comment by Slayycer** [comment]
same issue here

**Comment by tdegraaf1990** [comment]
I have the same problem, I can connect to Anathema but not to Elysium and Darrowshire.

**Comment by kpacko** [comment]
same

**Comment by tdegraaf1990** [comment]
The login issue is back, same thing is happening although I can now connect to Darrowshire and Anathema, but not Elysium.

**Comment by TheDipper315** [comment]
Still happening...

**Comment by JosipbrozElysium** [comment]
Not a bug report. For server downtime, check out our twitter: https://twitter.com/elysium_dev

Best regards!
