### ISSUE TITLE
leave /join notifications 

### ISSUE THREAD

**Issue by Wuushi** [elysium-project/server#1676]
Hi, 

When i logged in today (23th July, 5pm servertime), the lookingforgroup channel has become bugged or not as it was before. The problem is i see all the join/leave notifications of everyone joining and leaving the channel. This is only happening for this channel which i suspect it is a bug. To illustrate my issue further, please check the screenshot i have attached. 

Thank you! 
Regards,
Wuushi

![picture1](https://user-images.githubusercontent.com/30390292/28500927-86cc70da-6fd1-11e7-930e-bf6f9cc7ebd9.PNG)

**Comment by mitch6w9w** [comment]
Same issue. The amount of people that join/leave makes it nearly impossible to utilize the channel as intended.

**Comment by JosipbrozElysium** [comment]
This is not a server channel.

Best regards!
