### ISSUE TITLE
[quest] The horn of the beast, wrong level

### ISSUE THREAD

**Issue by theoden-dd** [elysium-project/server#1678]
http://db.vanillagaming.org/?quest=3181

Considered for 43 level, however in the db it's 48. Elite's level is 48, too.

Expected result: quest is for 48 level.

PS: if someone links to the guide, how to make PR for quests, I could end up with one.

![wowscrnshot_072317_150819](https://user-images.githubusercontent.com/2167281/28501289-78e5d172-6fe1-11e7-882e-185f3217710b.png)

**Comment by kampeador** [comment]
This bug exists, because some data was ported from wotlk. I've updated my PR.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
