### ISSUE TITLE
FIX THIS SERVER

### ISSUE THREAD

**Issue by Letmetankpls** [elysium-project/server#1679]
I mailed back several stacks of Gromsblood from my alt character "Dotfearme" to my main character "Letmetankpls". However, the mails with stacks of gromsblood, which I pressed the button "return" never arrived back to Letmetankpls. Whilst other mail before and after those mails DID arrive. This is very frustrating aswell as disturbing because a lot of people are counting on this for flask crafting.

PLEASE HELP ASAP!

Kind regards

**Comment by lovemonkeyz** [comment]
Contact GMs. Please stop using the bugtracker as a support-tool as you won't get any help here.
