### ISSUE TITLE
Snowshoe

### ISSUE THREAD

**Issue by Caeluma** [elysium-project/server#1680]
Hello

Just picked up Rabbit Crate (Snowshoe) from the running Dwarf among the Ram trainers outside Ironforge. I believe the texture for the rabbit is wrong, if you search for Snowshoe on Wowhead it will be white like the snow but the one you get in the crate is white with some brown patches. It is not how it was on retail, but I don't know if this is something that got changed with a patch.

**Comment by lovemonkeyz** [comment]
Working as intended. The pictures on Wowhead screenshots in this case are not relevant as they're not from Vanilla. The Snowshoe rabbit is supposed to be white/brown. 

"As of patch 3.0, this rabbit was changed to solid white."
