### ISSUE TITLE
9days res sickness ???

### ISSUE THREAD

**Issue by Charlieryan95** [elysium-project/server#1682]
Kasme - troll mage i have 9 days of res sick ? help xd  
http://imgur.com/a/Qe3Xy

**Comment by Sabre142** [comment]
Take res sickness again and it will go to 10 min

**Comment by JosipbrozElysium** [comment]
Not a proper bug report. For assistance, please visit our forums: https://forum.elysium-project.org/forum/303-help-support/

Best regards!
