### ISSUE TITLE
Remember Alterac Valley!

### ISSUE THREAD

**Issue by nickrockz** [elysium-project/server#1683]
![avbug](https://user-images.githubusercontent.com/30393634/28502693-b231c836-7000-11e7-89ad-94d31d420672.JPG)
The repeatable quest Remember Alterac Valley! is not available for my character, and as i checked the same thing happens to a friend of mine, which migrated with me from zeth'kur. 
So i am assuming that the specific Quest doesn't work on the transferred characters from zeth'kur.

**Comment by darkwen** [comment]
same for me. I did not transfer my character it. Leveled on Anathema
