### ISSUE TITLE
i think Auto loot (shift+mouse 1) is bugged.

### ISSUE THREAD

**Issue by alberte85** [elysium-project/server#1687]
ive seen ATLEAST 5 blue world drops in the fast loot table and when i check my loot chat it doesnt say i looted it, and its not in my bag, same thing happens from time to time when i skin (with shift+mouse1) loot

i contacted a GM he told me he could do nothing for me, and i should seek help here.

and when i say atleast 5 blue world drops that what im 100% sure of, i dont even wanna think about what i havnt gotten because of that bug.

my game is clean installed.

first and formost i write this because i cannot play with this loot dissapearing anymore, my heart is breaking.

second, is there any chance of me actualy getting the items i fairly shouldve gotten but didnt caus of bug?

i really hope for a fast answer and a helpfull one. 
this is REALLY making me sad 👎

**Comment by lovemonkeyz** [comment]
The bugtracker is supposed to be used for bugs relating to the server, not technical issues you might be having. There's a support forum for these topics. If you want to request some kind of item restoration for loot not received you need to contact the support staff, as there is 0 ways for us to replicate this issue you're having unless you provide some kind of proof.

**Comment by JosipbrozElysium** [comment]
Auto loot works. If you have any special issues, then please visit our help&support forum: https://forum.elysium-project.org/forum/303-help-support/

Best regards!
