### ISSUE TITLE
Sunder Armor ain't able to trigger chance on hit procs.

### ISSUE THREAD

**Issue by Phllippoussis** [elysium-project/server#1688]
The lasted updates said:Bloodthirst, Sunder Armor and Execute are now able to trigger chance on hit procs.
But after I test,the Sunder Armor still cant trigger chance on hit procs,at least,it cant work on Thunderfury, Blessed Blade of the Windseeker.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/52678-development-update-23082017/
