### ISSUE TITLE
Downloading the Torrent WIN

### ISSUE THREAD

**Issue by Varroes** [elysium-project/server#1689]
Whenever i click the Torrent WIN file from the Website the only thing that downloads is a 52kb file that cant be used at all. I was told to download Winrar to fix the issue but it hasnt been fixed. Is there some way to get it to work?

**Comment by brotalnia** [comment]
Have you never used torrents before? You can find another link from mega here, that does not require a torrent client. http://forum.nostalrius.org/viewtopic.php?f=32&t=2803#p25865

**Comment by lovemonkeyz** [comment]
The bugtracker is supposed to be used for bugs relating to the server, not technical issues you might be having. There's a support forum for these topics.
