### ISSUE TITLE
Can´t chat

### ISSUE THREAD

**Issue by silentgravity13** [elysium-project/server#1690]
My character on Elysium PVP, named Daren cannot use chat or see it.

**Comment by nukul4r** [comment]
Are you at least level 10?
https://www.google.de/search?q=elysium+cant+chat&oq=elysium+cant+chat

**Comment by lovemonkeyz** [comment]
The bugtracker is supposed to be used for bugs relating to the server, not technical issues you might be having. There's a support forum for these topics.

**Comment by SilverSaw** [comment]
No this is bug with anti-spam system of this core, youre muted without notification and you have to wait arround 1 hour

**Comment by Phoosy** [comment]
This isn't really a bug - if you chat frequently enough, it will trigger the anti-spam and mute you. It's a bit 'sensitive' but it's like that for a reason. It could use some fine tuning to make it less sensitive to actual player chats but it's not necessarily glitched.

**Comment by lovemonkeyz** [comment]
Apologies, my mistake!
