### ISSUE TITLE
Varimathras/Sylvanas not spawning

### ISSUE THREAD

**Issue by Kupovski** [elysium-project/server#1691]
Varimathras and Sylvanas has been dead for at least 8 hours now. Same bug as reported in January on Darrowshire. Can you fix?

*I Also believe Senior Sergeant Grimsford is missing, maybe same thing?

This is on Elysium-PvP

**Comment by waltersullivan1** [comment]
Half of day  there is no Varimathas or Sylvanas.

**Comment by kampeador** [comment]
Their respawn time is 24 hours.

**Comment by thepparker** [comment]
Very long respawn times
