### ISSUE TITLE
Alterac Valley NPC fight in the middle (Field of Strife)

### ISSUE THREAD

**Issue by Schmoha** [elysium-project/server#1692]
**Bug description:**
The NPC's in fighting in the middle at the Field of Strife are not supposed to be there. Nostalrius put them in there. Their reasoning is this: https://forum.nostalrius.org/viewtopic.php?f=32&t=35153#p249039

There is no evidence showing the NPC's fighting like that in the middle. No matter what old AV video you watch, you won't find it like on Elysium currently and before on Nostalrius, because this is wrong placement of pre-nerf NPC's and is custom. Nostalrius put it in ther because they didnt know where the pre-nerf NPC's should be.

Please remove them! They dont belong there!

**Evidence Video:**
Here is a video you can clearly see, there are no NPC's in the middle: https://www.youtube.com/watch?v=uYYYbZ51O8A (Watch 11:30)

Also if you wanted to know whether the AV on Elysium is the same as on Nostalrius, here is a Video of Nostalrius AV: https://www.youtube.com/watch?v=dRg2AUk3COY

If you are interested enought to watch more in that Evidence Video, you can see the pre-nerf NPC's, which never existed on Nostalrius and Elysium.

And by the way, the Evidence Video isnt from patch 1.12.1 or so. It is older than patch 1.8, first look at their gear, second, all the pre-nerf npcs are there, patrolling and defending constructions and beeing placed inside towers and bunkers.

If you need any more info, please comment!

**Comment by Schmoha** [comment]
Can this get some attntion please ?

**Comment by thepparker** [comment]
Duplicate #1887
