### ISSUE TITLE
Darkmoon Card: Maelstrom (Anathema) 

### ISSUE THREAD

**Issue by Fnt** [elysium-project/server#1698]
The card seems to be working properly, but there is a nuance her hits is never a critical.I have been using it for several months and I have never seen that the hit was critical.

**Comment by Phoosy** [comment]
Do you have a citation from a reputable source that Maelstrom should be critting (if it is indeed not actually critting by design rather than a flaw)?

**Comment by Fnt** [comment]
http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom
http://www.wowhead.com/item=19289/darkmoon-card-maelstrom#comments

**Comment by fidbugs** [comment]
Evidence that it can crit:

https://forum.theincrediblesguild.com/forum/public-area/general-chat/5305-info-on-darkmoon-card-maelstrom

http://web.archive.org/web/20071229154006/http://wow.allakhazam.com:80/db/item.html?witem=19289

**Comment by GuybrushGit** [comment]
Its currently critting, but its based on spell crit since its a magic spell.
