### ISSUE TITLE
mind control makes the person I duel unattackable

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1701]
mind control is making me unable to attack enemy and forced to /forfeit

can you please fix mind control its bugged ty

he mind controls me and when i bubble or get normal he is now un attackable 

he also hasnt forfeited the duel. I did forfeit just to show you

https://youtu.be/xVj5A3r5m9w
https://youtu.be/nFPjYkLkrrc
https://youtu.be/dJpFT80zyyI

This is annoying

**Comment by thepparker** [comment]
Duplicate
