### ISSUE TITLE
Dawn Treaders have bugged itemization on Elysium

### ISSUE THREAD

**Issue by insearchofthe** [elysium-project/server#1703]
Dawn Treaders, a Leatherworking crafted item added with the Patch 1.6 with the Argent Dawn rep reward additions, currently appear as Epic boots with no stats. The stats should be as follows:

http://db.vanillagaming.org/?item=19052

http://wowwiki.wikia.com/wiki/Dawn_Treaders - Added in Patch 1.6 along with http://wowwiki.wikia.com/wiki/Golden_Mantle_of_the_Dawn (which is currently stat'd properly).

**Comment by luigimannoni** [comment]
Duplicate of #1591

**Comment by ShortBusSubsidiary** [comment]
Any update on these?

**Comment by Razorwynd** [comment]
.. actually decent boots for druid tank

**Comment by thepparker** [comment]
Duplicate
