### ISSUE TITLE
Under the map after an Alterac Valley battleground

### ISSUE THREAD

**Issue by 3robimain** [elysium-project/server#1704]
I was playing a match of AV, after we won and i left the battleground this happend to me: 
![bug 3 0](https://user-images.githubusercontent.com/30418051/28540232-d385746a-70b4-11e7-9be8-b9595fb961fe.png)
After that you spawn at Tarren mill and you are dead (Dead bugged) the thing that worked for me was to exit the game and then i was alive again.

**Comment by nukul4r** [comment]
I had this bug as well. It happened when I stayed at the score screen after the AV was finished, and used the exit button about 10 minutes later. My suspicion is, that it has something to do with the AV instance being "closed down" before you exit.
