### ISSUE TITLE
A Vengeful Fate

### ISSUE THREAD

**Issue by cap1989** [elysium-project/server#1706]
Hi,
yesterday I have had completed the quest A Vengeful Fate (http://db.vanillagaming.org/?quest=1102), taking as a reward the Berylline Pads.
Today I'm not able to find the item, the xp and the quest item...
Can you please fix that?
I think it is reconducible to the world shut down.

Regards.
Matteo

**Comment by thepparker** [comment]
Open a ticket in-game
