### ISSUE TITLE
Mounting/riding  pala mount underwater in Arathi Basin

### ISSUE THREAD

**Issue by memeroni** [elysium-project/server#1715]
I just randomly jumped into the water in AB and I didn't get dismounted, I was still on the horse and was riding underwater. It was as if there was no water. I unmounted and tried checking again, and i could still mount and ride my mount underwater.

**Comment by memeroni** [comment]
the water doesn't make you float anymore, some people can abuse this bug lol

**Comment by memeroni** [comment]
update-only i can't float, everyone else can, please help. :'(

**Comment by Phatcat** [comment]
![billede](https://user-images.githubusercontent.com/1907820/29000150-79f91e02-7a63-11e7-8ebd-05da0d82ae83.png)

Trying to use aqua form;

![billede](https://user-images.githubusercontent.com/1907820/29000152-8cce5524-7a63-11e7-8530-14ed1f2dc3b4.png)

**Comment by thepparker** [comment]
Duplicate
