### ISSUE TITLE
Quest item "Deepstrider Tumor" doesn't drop out.

### ISSUE THREAD

**Issue by fatumepta** [elysium-project/server#1719]
STR
1. Take quest "Nothing but truth";
2. Go to "Swamp of Sorrows" location;
3. Kill "Dreaming Whelp" x 10.
Actual result: Quest item "Deepstrider Tumor" doesn't drop out, drop chance == 0.0.. %
Expected result: "Deepstrider Tumor" item has 100% drop chance (or 50-100 %)

**Comment by Phoosy** [comment]
Citation for the 50-100% drop chance?

**Comment by fatumepta** [comment]
I didn't understand your quastion. I mean that drop chance of this item should be in range (50,100) %.

**Comment by Peter2345** [comment]
Probably because at some patch levels, the Deepstrider Tumor dropped from the Deepstrider Giants in Desolace.

**Comment by fatumepta** [comment]
Understood. But where gamer can find this info? Quest text says - kill Dreaming Whelp. This DB says the same - http://db.vanillagaming.org/?npc=5601

**Comment by Peter2345** [comment]
I use http://db.vanillagaming.org - not 100%. In the comments there is the info.

**Comment by martinjlowm** [comment]
Fixed by #1847
