### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by Brandyboo21** [elysium-project/server#1728]
I made an account, dowloaded the server, and I changed the realmlist, but it is not letting me log on? I keep getting "connecting" then after a minute, it tells me i've been disconnected. Can someone help?

**Comment by Phoosy** [comment]
This is not the place to seek support. Go to the forums instead.

**Comment by Brandyboo21** [comment]
This is the forums? It gave me the option to contact. Why give the option,
if you're not there to help. But gee. Thanks.

**Comment by Phoosy** [comment]
This is the bug tracker for development issues, not for getting assistance. 
Go here instead: https://forum.elysium-project.org/

**Comment by Brandyboo21** [comment]
This is the place for issues. I posted an issue. If you have nothing helpful to say, say nothing at all.

**Comment by Brandyboo21** [comment]
Replied to these through email. Assumed it was a reply back from the forum
page. I tried there earlier
