### ISSUE TITLE
When log in everything resets

### ISSUE THREAD

**Issue by Map1991** [elysium-project/server#1729]
Hello people 

When playing elysium pvp server with my orc warrior when i log 

all video, interface and keybinds are all reset..

Can you help me with a solution for this??

Only the Best

Miguel Pereira

**Comment by Phoosy** [comment]
This is not the place to request for client/player issues. Visit the forums to get personalized assistance, as the Github is for reporting server development issues.

**Comment by JosipbrozElysium** [comment]
^

To be more specific, this is the appropriate forum section: https://forum.elysium-project.org/forum/473-in-game-issues/

Best regards!
