### ISSUE TITLE
Bonereavers edge proc chance is way too high - warriors can 3 shot plate as of 1.10 (2 stacks proc on 5 swings)

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1731]
http://db.vanillagaming.org/?item=17076

An elysium arms warrior was doing this to 5600 armor plate paladin. and 3 shot him
The warrior took this paladin from 100-0 with losing only 7% health...
This wasnt happening pre 1.10
https://youtu.be/_xiuzbudRT4

https://youtu.be/6Twm1aEo3v4 (2 stacks proc on 5 swings)
The bonereavers proc procced on the next swing...
I had skullflame shield/demonforge lifesteals and 9500 armor which is why it doesnt look like the warrior did alot. 

The warrior took this paladin with 5600 armor from 100-0 with losing only 7% health...
This wasnt happening pre 1.10

-------------------------------

PROOF proc should be lower:

https://www.youtube.com/watch?v=dd90O5LkikY&t=8m0s

Orshabaal, Warlord Undead Warrior using Bonereaver's edge from Ragnaros. From Sylvanas-EU realm
http://www.warcraftrealms.com/charsheet/24329916
starts at 8:00 bonereavers edge is proccing no where near every hit when he duels a paladin. Look at how often the bonereavers edge procs in the top right corner. Its proc should be around 12% like in that video
This is an arms warrior with horde equivalent gear of the arms warrior in the video 3 shotting us in BETTER gear than the t1 paladin in the video

The horde warriors proc chance for Bonereavers egde is way less against the paladin and not proccing the effect every few swings

It took about 6-7 swings in the video for Oshabaal to proc once on that paladin. This means it should be a 14% chance

Comment on wowhead
By firedemon on 06/19/2009 (Patch 3.1.3)
With my testing of about 7min on the training dummies, the proc seems to be near 12-15%; will do more testing later.

- Fix: Lower bonereavers edges proc chance to be thesame as the undead warrior in this video
https://www.youtube.com/watch?v=dd90O5LkikY

(at the moment proc chance is around double - 25-30%)

**Comment by stesve** [comment]
Bonereavers edge has a 2.6 ppm, which is equivalent to 14,73% pph.

**Comment by Mostprovidedlinks** [comment]
At the moment its proc chance is far too high.

**Comment by Mostprovidedlinks** [comment]
They should bring it down to a 14-15% proc chance then. At the most I swing 4 times and i have 2 stacks already. Its proc atm is like 25-30% and needs to be reduced so it procs like in the undead warriors video

**Comment by Mostprovidedlinks** [comment]
And night fall is the opposite. The proc chance of nightfall is far too low. Its proccing every 10-12hits. Alakazham has it at 20%

**Comment by stesve** [comment]
> They should bring it down to a 14-15% proc chance then. At the most I swing 4 times and i have 2 stacks already. Its proc atm is like 25-30% and needs to be reduced so it procs like in the undead warriors video

This is the current procrate on live servers:

> Bonereavers edge has a 2.6 ppm, which is equivalent to 14,73% pph.

But you are right, BRE is bugged... It should stack 3 times. Hopefully that will get fixed soon.

**Comment by vindruvor** [comment]
you can't take a sample size of 5 hits to determine what %proc chance it has, you need thousands of hits to determine it with accuracy.

**Comment by Mostprovidedlinks** [comment]
I have dueled that warrior 4 times. And each of those duels the warrior 3-4 shot me.
Its the weapons proc. Its too high

**Comment by thepparker** [comment]
BRE proc chance working as intended
