### ISSUE TITLE
Nightfall should have a 20-25% proc flat rate and not be a ppm weapon since it procs off hamstring (gcd)

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1732]
At the moment nightfalls proc chance is too low

Newest proof on old alazkazam
http://web.archive.org/web/20080106090952/http://wow.allakhazam.com:80/db/item.html?witem=19169

This should be flat rate

Ive been getting much more procs with SoR than without it
rng affects it in the way it will be proccing the set value on large data samples

the warrior was swinging at 3.5 seconds and no faster (no flurry etc)

Another comment off that page

Aernols axe

Posted: Aug 11th 2006 6:32am | IP: Logged | Reply... Reply to this

Sagros

2 posts
Score: Decent

I have this axe at kazzak  and i think that proc is like 20-25%

Nightfall
Posted: Nov 19th 2006 3:17pm | IP: Logged | Reply... Reply to this
johanhallberg
1 post
Score: Decent 

Procrate is about 20% (1 in 5) 
Weaponspeed 3.5 
5x 3.5 = 17.5s 
One 5s proc per 17.5s 
3x Axes 15s of 17.5s debuff on Boss 

--------------------

Another comment states over 20%

Posted: Aug 23rd 2006 9:20pm | IP: Logged | Reply... Reply to this
hickso
1 post
Score: Decent 
over 20%

Nightfall 12 hits tested on elysium (proc chance is around 8-10%)
https://youtu.be/yL6lcxVuX48

- Fix: Raise nightfall to 20-25% proc (so it procs every 5+ hits on average)

**Comment by stesve** [comment]
2 ppm = 11,66% pph

You may want to look into how ppm mechanics work.

> For example, a Warrior has Crusader (PPM of 1) on a 2.0-speed and a 2.5-speed weapon. These calculations assume ample Rage and no misses. 
> ◾Weapon 1 (speed 2.0): 30 white hits per minute, so PPH is 1/30. 
> ◾Weapon 2 (speed 2.5): 24 white hits per minute, so PPH is 1/24. 
> 
> Each minute, the Warrior also does 10 Bloodthirsts, 6 Whirlwinds, and 4 Overpowers, for a total of 20 instant attacks. 
> ◾Weapon 1 (PPH 1/30): 50 hits (20 instant + 30 white), so actual PPM is 50/30 = 1.67. 
> ◾Weapon 2 (PPH 1/24): 44 hits (20 instant + 24 white), so actual PPM is 44/24 = 1.83.

**Comment by Mostprovidedlinks** [comment]
Yeah well he says he is geeting a proc every five 3.5 second swings. 

That means it should have a 20% proc

**Comment by Mostprovidedlinks** [comment]
You cant ignore his one proc every 5 hits comment

**Comment by Itembugs** [comment]
Agree proc too low

**Comment by stesve** [comment]
> You cant ignore his one proc every 5 hits comment
You should look at the uptime comment instead and go read up on the ppm mechanics.

Multiple accounts.... meh.

**Comment by Mostprovidedlinks** [comment]
Another comment off that page





Aernols axe

Posted: Aug 11th 2006 6:32am | IP: Logged | Reply... Reply to this 

Sagros




2 posts
Score: Decent 


I have this axe at kazzak server and i think that proc is like 20-25%

**Comment by Mostprovidedlinks** [comment]
Its ppm should be 4
