### ISSUE TITLE
Suggestion: Gold Seller filter improvement

### ISSUE THREAD

**Issue by Nihlus** [elysium-project/server#1735]
Currently, it seems like it's popular among the gold sellers to colour their messages. This should be fairly easy to add as an automated flagging system - if a message is wholly or partially coloured (in ways that are  in contrast to the channel colour) without the coloured section being a valid item link, mute or ban. Normal players have no business doing this. There could be false positives, of course, but that's what audit logs and ban appeals are for.

This would be a quick and simple way of rapidly weeding out numerous accounts and addresses from the selling pool.

An example of these types of messages has been included.
![image](https://user-images.githubusercontent.com/2340428/28594149-306b52b4-718f-11e7-8d5d-32272bac4696.png)

**Comment by thepparker** [comment]
Channel colours are dictated by the client's settings. Improvements to the spam filter are in the works, however. Thank you for your suggestion.

**Comment by Nihlus** [comment]
Some form of control code is evidently being embedded in the message, similar to how you can create fake item links. For instance, the following macro snippet will alter the chat colour of your messages if player permissions are not properly checked on certain server cores. Obviously, some similar (or identical) method is being used on Elysium. Elysium is vulnerable to the following macro (which came up as the first result on Google), which will change the colour of the text for everyone, and not just client side.

```
/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg, type, lang, chan) scm("\124cff000000\124Hitem:19:0:0:0:0:0:0:0\124h" ..msg.."\124h\124r", type, lang, chan);end;
```

This particular macro overrides the chat colour to be completely black, and the zeroes at the start of the macro message contents can be substituted for any HTML colour code.
