### ISSUE TITLE
[4367] Small Seaforium Charge

### ISSUE THREAD

**Issue by kolokotrolis** [elysium-project/server#1736]
Currently,this item is only opening doors,but it should be opening locked items like lockboxes that are on the approriate skill level.When I tried to open a lockbox that was openable (Ornate Bronze Lockbox) I received an ''Invalid Target'' message.Please fix it,appreciate your work!

http://wow.gamepedia.com/Small_Seaforium_Charge

**Comment by Sabre142** [comment]
This was only implemented in early TBC I believe.

**Comment by kolokotrolis** [comment]
I believe it's not,since I am no rogue and the ''Locked'' word under the lockbox was orange when I had the seaforium charge in my bags,not red,which means it should be lockpickable(yes I invented a word).
