### ISSUE TITLE
Swimming seems to be broken (Elysium server)

### ISSUE THREAD

**Issue by arbosa** [elysium-project/server#1738]
Was able to swim previously, but just now I walked into the water and my char is walking on the floor of the lake. I cannot swim, I just jump and run normally as though not in the water. Breath bar is still functional

**Comment by arbosa** [comment]
![wow swimming](https://user-images.githubusercontent.com/30453064/28601419-bce96756-717d-11e7-8811-cde545dfbc4f.png)

picture evidence

**Comment by memeroni** [comment]
same thing randomly happens to me on arathi basin
i could even mount up and run  under water

**Comment by bobalazs** [comment]
Water walking works for me.
As a shaman, Ghost Wolf brakes it for me.
Spell buff still shows, but swimming instead of walking, whether it be ghost wolf or not.

**Comment by thepparker** [comment]
Duplicate, related to MC
