### ISSUE TITLE
Character bugged

### ISSUE THREAD

**Issue by Cheezdogg** [elysium-project/server#1739]
Jumped when I was on the boat, and now everytime I log in I instantly disconnect, need this fixed asap

**Comment by Cheezdogg** [comment]
It was on Cheezdogg on Elysium

**Comment by Peter2345** [comment]
In-game ticket, the GMs can "pull" you to a non crashing place. I assume that another character logs on OK and that you have tried without add ons.

**Comment by Cheezdogg** [comment]
Its all good i made a ticket and an admin teleported me to rachet, thanks for responding though, will know to make a ticket on my alt next time

Sent from my iPhone

On 26 Jul 2017, at 11:14 pm, Peter2345 <notifications@github.com<mailto:notifications@github.com>> wrote:


In-game ticket, the GMs can "pull" you to a non crashing place. I assume that another character logs on OK and that you have tried without add ons.
