### ISSUE TITLE
Shield Slam can't trigger mainhand procs

### ISSUE THREAD

**Issue by Zarant** [elysium-project/server#174]
According to the 2.0.1 patch notes, shield slam and shield bash got changed to not trigger main hand procs, which implies that was the case during the 1.12.1 patch.

Currently only shield bash can trigger main hand procs. I went through the source code myself and i found out a line of code that handles this particular case:
https://github.com/elysium-project/server/blob/development/src/game/Spells/Spell.cpp#L1168

Apparently only the shield bash icon ID is specified, thus, only shield bash can trigger weapon procs, shield slam can't.

**Comment by PlaskED** [comment]
Source?

**Comment by FractalCabush** [comment]
the comment in the code clearly states it should include both but only shield bash is actually checked in the code

**Comment by henkethebenke** [comment]
From [dev update 2016-12-15](https://elysium-project.org/updates/2016-12-15):

> "Shield Bash and Shield Slam can now trigger mainhand weapon procs.

**Comment by PlaskED** [comment]
Shield Slam always procced Thunderfury though. Are you sure it even goes under that mask? Have you tested this?

**Comment by PlaskED** [comment]
I just tested it, it indeed seems that Shield Slam does not proc weapon procs.
