### ISSUE TITLE
Frigid Ring shouldn't be a world drop

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#1743]
http://db.vanillagaming.org/?item=18679 this ring should only drop from Princess Tempestria in Elemental Invasions.

Source: http://web.archive.org/web/20051130220215/http://wow.allakhazam.com:80/db/item.html?witem=18679

**Comment by lovemonkeyz** [comment]
Do you have any proof of this dropping in the world then? 

Because linking vanillagaming's DB doesn't exactly prove anything more than on some servers that upload information to that database, the drop is incorrect.

**Comment by Sabre142** [comment]
@lovemonkeyz there are lots on Elysium, and I've asked people where they got their rings, from random mobs.

**Comment by GuybrushGit** [comment]
Fixed here https://github.com/elysium-project/server/pull/2618
