### ISSUE TITLE
Was killed by Alliance mage while not flagged in Barrens.

### ISSUE THREAD

**Issue by CptDavis** [elysium-project/server#1756]
Mage named Soulmask killed me while i was questing in the barrens while i was not flagged for pvp. around 20:20 server time. I typed /pvp to make sure i was not flagged for pvp.

**Comment by JosipbrozElysium** [comment]
Unflagging yourself doesn't happen instantly (or with the amount of information you've provided, I could also assume that you might've flagged yourself with the /pvp command?).

Best regards!

**Comment by CptDavis** [comment]
I used /PvP to flag myself after I revived from being killing to make sure
I was not flagged. I was not as my name was blue before hand and when I
used the command it went green. I'm playing a worrior so I have no buffs of
which I can use to flag myself by buffing someone else.
