### ISSUE TITLE
bug：raids  infinite Resurrection

### ISSUE THREAD

**Issue by twilightbug** [elysium-project/server#1759]
Now more than 90% of guild play BWL, use this bug, after treatment, death, resurrection, you can leave combat, and infinite resurrection of other dead players

**Comment by lovemonkeyz** [comment]
Are you saying Raid-wide combat when fighting a boss isn't working? 

Seems to have been reported here too a month back: https://github.com/elysium-project/server/issues/1003

**Comment by RussianE39** [comment]
Technically, it was still allowed on retail when BWL were released.

**Comment by stesve** [comment]
> Technically, it was still allowed on retail when BWL were released.

Servers are using 1.12 gamemechanics regardless of what content/itemization patch thats currently active.
