### ISSUE TITLE
Muted After Putting a Gold Spammer on Ignore

### ISSUE THREAD

**Issue by Soylentdali** [elysium-project/server#1760]
Not sure why but two days in a row I was playing fine and then I get spammed by a gold seller. Both times I immediately put the "player" on ignore and then _I_ was muted the rest of the day. Not sure what is going on but it really is putting a damper on playing with others. Any advice is much appreciated.

**Comment by JosipbrozElysium** [comment]
This is not a bug report. If you need any kind of support, then please check out the help&support forums: https://forum.elysium-project.org/forum/303-help-support/

Best regards!
