### ISSUE TITLE
resurrection sickness for 7 days

### ISSUE THREAD

**Issue by feyaares** [elysium-project/server#1764]
Hello,

Issue was on Elysium server.

Yesterday I've receive a # resurrection sickness of 7 days 
This issue could be fixed simply by dying again and taking again the resurrection sickness at the graveyard Valkyrie.

This can be quit annoying and I haven't found anything regarding this issue here (only on Elysium Forum)

Best regards,

Feya Ares

**Comment by JosipbrozElysium** [comment]
Known issue already!

Best regards!
