### ISSUE TITLE
[16912] Netherwind Boots

### ISSUE THREAD

**Issue by kolokotrolis** [elysium-project/server#1766]
Currently,this item has the wrong stats.It has the pre-1.4 MC drop stats,but it should be having  the 1.5 stats.I couldn't find an archive of the stats,this is all the proof I can offer:
http://wow.gamepedia.com/Netherwind_Regalia
 Patch 1.5.0 (2005-06-07): Statistics, effects, and set bonuses updated.

**Comment by Sabre142** [comment]
Here's the proof: https://web.archive.org/web/20050817113550/http://wow.allakhazam.com/db/itemset.html?setid=210
