### ISSUE TITLE
RAID ID's

### ISSUE THREAD

**Issue by NeedElysium** [elysium-project/server#1767]
Hello
![saveds](https://user-images.githubusercontent.com/29754316/28667158-90d50fbe-72ca-11e7-836f-636f3d0e81d3.PNG)

We are currently having problem with our guilds raidid - We havent been to BWL this week, and were going this evening at 19:00-
Currently our Main tank and Offtank got saved raidid to BWL and Dire maul.. Me myself currently got a saved RAIDid to dire maul- is this posible to fix before we have to go in there and kill it all? 

Sincerely Need, Rogue, Officer Nidvardir

**Comment by JosipbrozElysium** [comment]
Please write an ingame ticket and get it sorted out with a GM.

Best regards!
