### ISSUE TITLE
Quest: "Hive in the Tower" incorrectly only being available to alliance

### ISSUE THREAD

**Issue by Sirael11** [elysium-project/server#177]
The quest "Hive in the Tower", ID=1126, is currently available for alliance players only. The web archive 
(http://web.archive.org/web/20060521122921/http:/wow.allakhazam.com/db/quest.html?wquest=1126)
also states this quest to be alliance only but multiple comments on that page state the quest being completable by horde players too and the flag being set incorrectly.

The oldest comment on that issue: "Completed this quest as undead mage (and the follow-ups to eventually claim the +int ring as reward). I am sure most poeple know this, but this quest is NOT only available to Alliance." was posted 23. April 2005 which equals to Patch 1.3.

Since all servers are Patch 1.3 or later I think this should just be changed in general, also taking into account that this quest was probably available since version 1.0 of the game and has only been mentioned in one retail patch(1.4), where only the quest text was changed.

**Comment by StadenElysium** [comment]
Fixed in https://github.com/elysium-project/server/pull/220
