### ISSUE TITLE
BRE Proc Elysium

### ISSUE THREAD

**Issue by kaselol** [elysium-project/server#1771]
When BRE Will have 3 stacks in proc?  ELYSIUM SERVER

**Comment by fgsfdss** [comment]
1.11

**Comment by vindruvor** [comment]
https://github.com/elysium-project/server/issues/998

"We are on patch 1.12 when it comes to spells and talents"

"Chance on hit effects are actually spells that get triggered."

Does this only apply to Anathema realm and not Elysium?

**Comment by thepparker** [comment]
Dupe
