### ISSUE TITLE
Anathema realm. Quest item "Split bone necklace" drop chance much lower then 80%.

### ISSUE THREAD

**Issue by fatumepta** [elysium-project/server#1773]
Zone: Stranglethorn Vally, 42 lvl
STR
1.  Take quest  "Split bone necklace";
2.  Kill skullsplitter trolls  x 10.
Actual result:  less then 2 item is dropped out.
Expected result: 4-8 items dropped out.
Drop info: logic, official server WoW play experience (2005-2006 years), db (http://db.vanillagaming.org/?item=3916)

This quest makes people angry, rly!

**Comment by Fustershock** [comment]
Hey, man!

You know, DB.Vanillagaming is not our server's DB?
No point to make proofs like that "linked the item's code on a random database, hey ppl fix that !!!1"

Show some official proofs from patch notes/Allakhazam old posts or comments/old videos from retail vanila/any viable blizzard things or blue posts, and then ask for fix

Best regards!

**Comment by fatumepta** [comment]
Ok. I think you have QA-team. Give one of them task to try that quest then ask him about his fillings :)
it is not good if quest item for ordinary quest has so low drop chance. To end this quest user must lost more then 3 hours of hes time.
Sorry for my english.

Best regards.

**Comment by Fustershock** [comment]
@fatumepta i farmed this shitty bones half a day from 33 to 35 level, back 1.5 years ago on Nostalrius, it was always very low drop rate, search some true info and don't look at database's 80%, it's not always accurate

**Comment by Ripper007** [comment]
Blizzard upped the drop rate of those and many others when 2.0 launched. Many of the db's have that as reference. Many of those items like Bone Necklaces and Salt Flat Venom had abysmal drop rates in Vanilla.

**Comment by thepparker** [comment]
Working as intended
