### ISSUE TITLE
Cannot use chairs through walls

### ISSUE THREAD

**Issue by ifyousayso** [elysium-project/server#1774]
From when I started playing (AQ) to mid-TBC it was possible to use chairs through walls because it was possible to click/select/use items that were out of line of sight.

The best memory I have of this is from a room in Kharazhan that is next to the kitchen. It had a locked door, impossible to unlock, contained a few chairs and a table or two. But because one of the chairs was placed close to a wall, it was possible to teleport into that room.

With some TBC patch, they recoded the client so that the cursor would no longer be able to interact (no tooltip either) with anything that wasn't in sight of the camera, still no server LoS check.

http://db.vanillagaming.org/?quest=540#comments:id=731 shows both that a bookcase can be used through a wall (no proof for chairs, though) and that the agro range is messed up here.

It is extremely rare, if ever, that using a chair to teleport in is useful, but looting containers is perfectly fine.

If this server is aiming for blizzlike, please fix this as this bug was added just a few weeks ago.

**Comment by thepparker** [comment]
This is intentional to prevent players looting certain objects through walls, which is pretty clearly a bug.
