### ISSUE TITLE
Warlock Tier 2 Nemesis Belt, Boots and Robes have wrong ( still 1.3 patch) stats on Elysium

### ISSUE THREAD

**Issue by Hegelol** [elysium-project/server#1778]
Nemesis Belt, Nemesis Boots and Nemesis Robes have not been upgraded to patch 1.6 stats. However, all of the other pieces have been upgraded. Here is what these items need to look like in patch 1.6:

http://web.archive.org/web/20051211002606/http://wow.allakhazam.com/db/itemset.html?setid=212

**Comment by Dalleren** [comment]
Nope. Those are the stats for patch 1.9.

Also how can T2 Bracers, Boots and Chest have patch 1.3 stats when they were introduced in patch 1.6?

**Comment by Hegelol** [comment]
No, you are wrong. Stats for 1.9 are as follows:
http://web.archive.org/web/20060215115018/http://wow.allakhazam.com/db/itemset.html?setid=212

Stats for 1.6 are as follows:
http://web.archive.org/web/20051211002606/http://wow.allakhazam.com/db/itemset.html?setid=212

Stats for 1.3 are as follows:
http://web.archive.org/web/20050620074053/http://wow.allakhazam.com/db/itemset.html?setid=212

The reason there are stats for t2 in 1.3 (before they were introduced) is that they were in the game as placeholders.

Do more research before commenting here next time. I have been playing vanilla lock for 10 years now.

**Comment by towneh** [comment]
This should be an itemisation issue and raised under https://github.com/elysium-project/database/issues
