### ISSUE TITLE
Gear in inventory and quest are disappearing.

### ISSUE THREAD

**Issue by tmlsd** [elysium-project/server#1780]
Recently the cape of the brotherhood from the deadmines as well as a few of my quests from my journal have been deleted. The quest were easy enough to recover, however, the cape of the brotherhood has not been. I was hoping that something could be done to rectify this issue. maybe there is a way to restore the cape to me. Your help in this matter is greatly appreciated.

**Comment by lovemonkeyz** [comment]
Please submit a help request - https://forum.elysium-project.org/forum/473-in-game-issues/
