### ISSUE TITLE
WSG tokens

### ISSUE THREAD

**Issue by Humppastara** [elysium-project/server#1781]
SERVER: Darrowshire (horde)

Several other people can turn in the Warsong gulch marks of honor.

Can't turn in WSG tokens at Horde Warbringer in orgrimmar or undercity and the WSG place in barrens didn't have anything either.
Does it require to be friendly with Warsong outriders? Currently neutral.
Tried turning them in on shaman and rogue. Nothing.

**Comment by Phoosy** [comment]
This is a duplicate issue report, use the search function next time. Please close to reduce clutter.

**Comment by thepparker** [comment]
Duplicate
