### ISSUE TITLE
Block and Parry (Mobs)

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#1784]
So I've noticed that mobs without a melee weapon are able to parry. Should they? This also goes for mobs who have been disarmed, making riposte kind of useless in pve (especially since disarming a mob doesn't lower the damage either (there's already an issue open about this)
This also goes for blocking, mobs without shields seem able to block. How?

When looking at the tooltip for both parry and block for players, they require a melee weapon (for parry) and a shield (for blocking) - I can understand some special mobs not to follow these rules but random trash mobs in low level zones?

**Comment by lovemonkeyz** [comment]
I can confirm having seen this too. My pet usually gets parried/blocked by beasts, will check next time and paste combat log info.

**Comment by Phatcat** [comment]
No, tried looking a bit into this, seems some mobs were able to block and parry without weapons or shields, so closing this.
