### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by Newstrain** [elysium-project/server#1786]
I can't talk in any other channel but guild chat.Talking in /say also doesn't work. Only the guild chat seems to work.
Ty

Bobosmrad (name of the character,  realm-Elysium pvp)

**Comment by Haiwuu** [comment]
You've possibly been temporarily muted by the chat filter.

**Comment by JosipbrozElysium** [comment]
Not a bug/bug Report. For ingame assistance and questions, please visit out our Forums.

Best regards!
