### ISSUE TITLE
Disgusting Oozeling

### ISSUE THREAD

**Issue by polischuk16** [elysium-project/server#1790]
I killed over 200 oozes in Felwood and havent had a single Oozeling Bag drop,

**Comment by Haiwuu** [comment]
Bad luck does not constitute a bug quite yet.

**Comment by polischuk16** [comment]
You supposed to get at least one every 10 kills

**Comment by some2** [comment]
> You supposed to get at least one every 10 kills or so.

> People have reported farming for hours on end to get this pet so it may be on the same drop rate as whelplings and the like.

http://wowwiki.wikia.com/wiki/Disgusting_Oozeling?oldid=335866

**Comment by polischuk16** [comment]
You are supposed to farm it for hours. It has 2% drop chance from the oozeling bag, bags are supposed to drop from every 10th ooze or so, I spent 2 more hours last night just to confirm that its not a bad rng, and still didnt get a single oozeling bag from fellwood or epl.

**Comment by some2** [comment]
Flesh Hunter (Elite) - 12.7407%
The Ongar (Rare) - 10.5263%
Large Vile Slime - 4.8128%
Plague Slime (Elite) - 4%
Vile Slime - 3.5%
Devouring Ooze - 3.5%
Living Decay - 3%
Rotting Sludge - 3%
etc..

**Comment by thepparker** [comment]
#968
