### ISSUE TITLE
Dire Maul Raid ID bug

### ISSUE THREAD

**Issue by Gibi-gibii** [elysium-project/server#1794]
https://imgur.com/a/MGR3r

Dire maul is acting as a raid, Captain Kromcrush was missing, tribute chest did not spawn, Cho'rush did not aggro when king was pulled.
No clue what happened

**Comment by MoDerAoE** [comment]
same problem. Id appeared after the murder of onyxia.
http://imgur.com/Z8Ajr9M

**Comment by lovemonkeyz** [comment]
That is.. hilariously sad.

**Comment by lordhelmchench** [comment]
Same problem.
Dire Maul Raid ID. No Reset of instance possible,

http://www.directupload.net/file/d/4797/jqtyzrfk_jpg.htm

**Comment by keaarori** [comment]
This is because of the issue with raid id's and has been reported several times; A GM in game can help you remove the lockout via in game ticket.

**Comment by JosipbrozElysium** [comment]
Known issue. It should be fixed on the next maintenance. Closing for being a duplicate.

Best regards!
