### ISSUE TITLE
NPCs hit multiple times in first/one attack

### ISSUE THREAD

**Issue by ifyousayso** [elysium-project/server#1798]
Rangers always hit/attack twice on pull and most meleers hit 2-3 times usually on pull but also after polymorph.. This issue has been around for months (Darrowshire).

**Comment by Fustershock** [comment]
Maybe they have some specific abilities like "Thrash" or some similiar? Have you checked them on DB? Post some names of NPCs which do this

**Comment by Pewtersprite** [comment]
I'm having this issue while farming Princess Theradras in Maraudon, she hits me between 4 and 5 times at once when she catches up with me. I've also seen this happen with Black Dragonspawn in UBRS. I'm 99% sure neither has abilities that should allow them to do this.

**Comment by ifyousayso** [comment]
I can't find a mob right now, but I remember when my gnome mage was around level 12, doing that miner's gear quest in northern Loch Modan, the kobolds used to hit that way. I'll see if I can pull a ranger (not caster) to see if it double-shoots (as they all have done so far).

**Comment by GuybrushGit** [comment]
Related fix: https://github.com/elysium-project/server/pull/735
Need a list of mobs that still suffer from this.

**Comment by ifyousayso** [comment]
I tested many NPCs and none were broken last I was online. I don't think it has anything to do with a specific mob but some underlying mechanic. Right now this doesn't seem to be an issue.
