### ISSUE TITLE
gnomish mind control cap used to make me go afk in wsg

### ISSUE THREAD

**Issue by memeroni** [elysium-project/server#1801]
So i spawned at gy in wsg, a orc was waiting right there. He used gnomish mind control cap on me, made me run to the instance to go out. This lead to me getting the afk buff and i was thrown out of the game.I didn't know that works. Thats just broken. People are abusing it to get people out of the game against their will and made to be wait for another 15 mins. Please do something.

**Comment by Fustershock** [comment]
... and? This is the game's mechanics, he commanded to follow you..... and what?

**Comment by Phoosy** [comment]
This is not a bug or glitch.

**Comment by a-big-dumb-baby** [comment]
LOL

**Comment by WithTheWrist** [comment]
What was that assholes name?

**Comment by Itembugs** [comment]
Close this please. Im sorry to say but that is what used to happen.

**Comment by Itembugs** [comment]
You need to use a consumable that can get you out of it.

**Comment by Itembugs** [comment]
What class are you squidward let me see if me and patrick can fjnd the perfect item to prevent that mind control

**Comment by Itembugs** [comment]
Warlock can purge it off them. 
Paladins can bop or bubble it off
Mages can iceblock
Alliance warriors can use crystal of zin 

All other classes need to use invulnerability potion
Use this. And you only need to use it rarely
So its not expensive for you

**Comment by thepparker** [comment]
Working as intended
