### ISSUE TITLE
Warlock T2 Boots

### ISSUE THREAD

**Issue by Bleekthun** [elysium-project/server#1802]
Warlock T2 boots I believe should have 18 Spellpower not 27.

https://forum.elysium-project.org/topic/50971-warlock-t2-boots-in-patch-16/

**Comment by Hegelol** [comment]
Also Warlock Tier 2 Nemesis Belt and Robes have wrong stats. Here are the correct ones for 1.6:

http://web.archive.org/web/20051211002606/http://wow.allakhazam.com/db/itemset.html?setid=212

**Comment by l1amm** [comment]
My T2 boots show as having 18 spell power...?
