### ISSUE TITLE
Dragon's call

### ISSUE THREAD

**Issue by Wort1** [elysium-project/server#1803]
Hello, 
I have the weapon dragon's call from sunken temple that spawns a dragon whelp. The whelp does spawn, however, it does melee damage ranging from 8-14dmg. I heard that the whelp should do much more damage (around 200dmg) and not melee but range. Am I right or is it the way it should be?
Thank you in advance for your support.

**Comment by Fustershock** [comment]
Hello! Search for some official proofs from Blizzard, patch notes, old vanilla sites, anything. You can send some videos of it how it works right.. If you want it to be repaired, you have to do something

**Comment by Wort1** [comment]
Thank you for your advice, here are a few links about this amazing weapon:
http://www.wowhead.com/item=10847/dragons-call#comments 
http://db.vanillagaming.org/?item=10847#wh-comments

I don't know if that can be considered as a serious proof though... That's all I could find for now.

**Comment by Jakobud** [comment]
Another problem with this Dragon's Call dragon is that it acts like an hunter pet in aggressive mode. What I mean is that when it's spawned and then you exit combat after killing whatever you were fighting, if there is an enemy mob nearby, the dragon pet will automatically go attack that mob, putting you back into combat. Just like a hunter pet that is in aggressive mode.

This has caused wipes for my groups in dungeons before. It's terrible.

Also, here is the actual NPC pet that is spawned:

http://db.vanillagaming.org/?npc=8776#wh-comments

According to the comments, it melee hits for 250 dmg on a level 50 mob and casts 3 separate green poison (non-DOT I assume) bolts (nature dmg) for a total of around 750 dmg.

**Comment by Jakobud** [comment]
Also, FYI, here is the spell the dragon casts:

http://db.vanillagaming.org/?spell=9591

Or here is an up to date one on wowhead: 

http://www.wowhead.com/spell=9591/acid-spit

Here is archived data about the sword and the dragon:

http://wowwiki.wikia.com/wiki/Dragon%27s_Call?direction=next&oldid=161017

> The whelp is level 55, has 1500 health, and has a ranged attack which does 200-250 points of nature damage. You can have up to 3 Whelps summoned at the same time.

**Comment by AnafNatan** [comment]
Yes this needs to be fixed as soon as possible! Atm the proc does less then 5% of its actual damage and that as meele physical one, the dragon following each mob and having a large aggro range with this meele coding literally deems this weappon unusable in its bugged state to the point where even some green weappons of this level do better.

**Comment by AnafNatan** [comment]
http://db.vanillagaming.org/?spell=20657

**Comment by brotalnia** [comment]
Fixed in https://github.com/elysium-project/server/commit/8332d93eb72ef33c71893a553ca624223cbd872b.

**Comment by Jakobud** [comment]
> large aggro range

It's not really a large aggro range. It can better be described as a pet on aggressive mode. So that instead of aggro'ing NPCs nearby via proximity, it goes out of its way to attack NPCs that are not in combat. Like an aggressive hunter pet.

**Comment by AnafNatan** [comment]
Issue has been fixed the dragon's now do their Acid Spit scaling with their casters lvl.
