### ISSUE TITLE
Buff Bug in Battlegrounds

### ISSUE THREAD

**Issue by fixitnownownow** [elysium-project/server#1807]
Can't use blessing of sacrifice randomly on certain players or use greater blessings. This makes playing a paladin in pvp even more godawful. fix it 

edit: it's not just me other paladins have been complaining
edit: while im here, fix the forward button when you get out of CC... that has to be the second most annoying thing in the world above what i just mentioned

**Comment by Hyperial** [comment]
I can confirm this bug.

**Comment by leoguiders** [comment]
Can confirm this, too. Very annoying.

**Comment by SoulSharer** [comment]
confirmed

**Comment by thepparker** [comment]
Mind control related
