### ISSUE TITLE
Saved for Molten core

### ISSUE THREAD

**Issue by mahler92** [elysium-project/server#1813]
hey i cant figure out why im being saved for Molten core. got raid id 269. but have not been in MC for like 2 weeks now.

**Comment by lovemonkeyz** [comment]
This is a known bug with Raid ID's most likely. You can contact a GM through the forum to get it reset: https://forum.elysium-project.org/forum/473-in-game-issues/

**Comment by JosipbrozElysium** [comment]
Knwon bug!

Best regards!
