### ISSUE TITLE
ghost

### ISSUE THREAD

**Issue by hoppetusse** [elysium-project/server#1814]
hello 
im need help..

im a gost and are stuck in the maountens..  i cant get up..

i have try the stuck buttom but no help.

need a healer to find me in feralas in the cave the writhing deep, or are the somthing else i can do?

**Comment by lovemonkeyz** [comment]
Hi,

The github issue repository is to be used for bugs, not in-game issues relating to you not being able to get to your corpse. Post a help request on the forums here: https://forum.elysium-project.org/forum/473-in-game-issues/
