### ISSUE TITLE
Hunters pet gets deleted frequently.

### ISSUE THREAD

**Issue by Ramon3s** [elysium-project/server#1816]
Exactly as the title suggests, my hunters pet is constantly disappearing. At first it seemed to only happen when I would log in, but It just happen mid game while I was working on professions. Pets level slowly in Vanilla as you know and would really appreciate it if I didn't have to tame a new one multiple times a day. Just to be clear the game literally suggests I do not have a pet or have never tamed one, even though my wolf was running next to me moments before. If this is some wacky Vanilla mechanic I'm sorry for posting it as a bug as this is my first experience with vanilla. Thank you

**Comment by lovemonkeyz** [comment]
You mention this is your first experience with vanilla. I have never seen this happen and I play a hunter here and have played on in vanilla, there are no issues with pets disappearing. 

My assumption is: You don't know about loyalty mechanics. 

http://wowwiki.wikia.com/wiki/Loyalty

When pet is first tamed: 
> Rebellious (Rank 1) 
During this stage, your pet's happiness fluctuated a great deal. If the pet or yourself were constantly dying, or if you dismissed the pet too often, he could begin to become very hard to handle and might have left you.

**Comment by Ramon3s** [comment]
Thank you for the reply so quickly. This crossed my mind, but I fed them constantly keeping them at full happiness as much as possible. I played wrath plenty and never had any problems with the happiness system at that time. I'll take your word for it though and continue as normal, hopefully it was just  a string of bad luck.
