### ISSUE TITLE
Gouge - PvP set bonus not working

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#182]
The 1 sec cooldown reduction from 3/6 Marshal's/Warlord's Vestments and 4/6 Lieutenant Commander's/Champion's Vestments set bonuses do not apply.

Gouge Cooldown Reduction
Instant
Reduces the cooldown of your Gouge ability by 1 sec.

Spell Details
	
Duration 	n/a
School 	Physical
Mechanic 	n/a
Dispel type 	n/a
Cost 	None
Range 	0 yards (Self Only)
Cast time 	Instant
Cooldown 	n/a
Effect #1 	(6) Apply Aura #107: Add Flat Modifier (11) 

http://db.vanillagaming.org/?spell=23048

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
