### ISSUE TITLE
Snarler doesn't have his resists when tamed

### ISSUE THREAD

**Issue by pateuvasiliu** [elysium-project/server#1820]
In Vanilla Snarler was supposed to retain 100 resist in all schools once tamed. He doesn't on Elysium PvP.

**Comment by stesve** [comment]
> Fixed a bug where creatures were keeping their innate resistances after being tamed. This was unintentional and the fix will affect all existing pets. 

http://wowwiki.wikia.com/wiki/Patch_1.3.0

**Comment by pateuvasiliu** [comment]
http://www.wowhead.com/npc=5356/snarler

Added in patch 1.11.1.7272

Snarler was added after that patch. He is meant to have his resists until 2.0.0 when pets were all normalised.

**Comment by stesve** [comment]
> http://www.wowhead.com/npc=5356/snarler
> 
> Added in patch 1.11.1.7272
> 
> Snarler was added after that patch. He is meant to have his resists until 2.0.0 when pets were all normalised.

That is not correct. Since wowhead didn't exist until late vanilla, it has no data on the earlier patches.

Following posts confirms that Snarler was ingame in patch 1.2.1

Postdate 3. january 2005
http://www.mscclan.com/threads/king-bangalash.10098/

28. january 2005
http://forum.judgehype.com/judgehype/WorldofWarcraft/trouver-elite-sujet_241668_1.htm

And patch 1.3.0 clearly states:
the fix will affect **all** existing pets.

**Comment by stesve** [comment]
http://www.mscclan.com/threads/washte-pawne.10069/

> Yah I've known about him **since beta**, and once I hit 42 I'll be making a b-line to Feralas. Saddly just about ever hunter is after him so it can be a pain in the rear to try and tame him.

**Comment by Phatcat** [comment]
Here he is, in 2004; https://web.archive.org/web/20041115161923/http://wow.allakhazam.com:80/db/mob.html?wmob=5356

in late 2005 there's a bunch of comments specifically talking about him losing his resistances; https://web.archive.org/web/20051202123338/http://wow.allakhazam.com:80/db/mob.html?wmob=5356

> But since he's lost his resistances and all, if all you want is a black wolf there's always the Vilebranch Cubs in the Hinterlands or something, but those are level 46-47.

> yes thoose bastards at blizz, snaler now has 0 in all resists making him usless and thoose 5 days i spent to get him wasted.

**Comment by Phatcat** [comment]
Also it was never 100 to all resistances, it was 10; https://web.archive.org/web/20051202123338/http://wow.allakhazam.com:80/db/mob.html?wmob=5356

> I have this pet and he is great. Excellent armor and pretty fast. Has 10 to all resists.

**Comment by kampeador** [comment]
In all DBs i have since 2005, Snarler himself has 100 to all resistances, so i would assume, that after taming all those resistances remained.
@Phatcat 
Other comment in the page you linked above, mentiones that he had 100, not 10.

**Comment by Phatcat** [comment]
Well, in that case, let it be 100 and not 10. I have nothing else than that comment to back it up anyways and I rather trust your cached dbs then. And if he indeed had 100 then that is what he was supposed to have kept after taming... prior to 1.3 of course. After that he's supposed to get nothing, though´, correctly, which was the heart of the issue.

**Comment by thepparker** [comment]
Pets do not keep resistances post 1.3
