### ISSUE TITLE
WSG falling through world (after)

### ISSUE THREAD

**Issue by randomUsernameslol** [elysium-project/server#1825]
Hi,
Finished WSG, queued from OG [60 bracket]. 
Game finished, teleported to Dalaran (after load-screen), underneath the zone, fell through the world and landed in Tarren Mill GY (alive). 

There are no NPC's or PC here though, 
I can see chat, /reload doesn't fix, zoning out and back in doesn't reload the zone, no mobs either. 
Logged, came back - fixed.

Game of WSG was pretty straight forward, wasn't dead or dying at the end, game ended normally. No one else here from the game.
Weird!

**Comment by Fustershock** [comment]
Actually, when it's happening, you spawn at GY dead, but there is no animations or info which says it, only the spirit healer(who can't resurrect you) and when you try to use any item/ ability, the system say "U r dead". To fix that, simply use log out, no alt+f4 and no reload. Or if you have some friends, or anyone who can reque you to a bg in party, ask him to do it. When the bg will pop, you will enter the bg without any bugs with full hp

**Comment by Brunheda** [comment]
I've had this happen more than once. Deleting the WDB folder is all that would bring me back to life.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
