### ISSUE TITLE
I can't enter Dire Maul

### ISSUE THREAD

**Issue by mysensen** [elysium-project/server#1826]
I can't enter Dire Maul,I show here It's in my Raid information ID 196

**Comment by mysensen** [comment]
I can't enter Dire Maul,I show here It's in my Raid information ID 196

**Comment by lovemonkeyz** [comment]
Dire Mail Raid ID is a known bug. Please submit a help request on the forums to have the ID removed: 

https://forum.elysium-project.org/forum/473-in-game-issues/
