### ISSUE TITLE
Can't untrain Dragonscale Leatherworking 

### ISSUE THREAD

**Issue by Vilstar** [elysium-project/server#1827]
I went to untrain it in Badlands, but it keeps telling me "You cannot do that at this time." I tried logging out and logging back in. Nothing seemed to fix it.
![wowscrnshot_072917_123645](https://user-images.githubusercontent.com/30557756/28751028-bdf9c654-74b1-11e7-98fe-8b14897e5d5b.jpg)
![wowscrnshot_072917_123648](https://user-images.githubusercontent.com/30557756/28751029-bdfc9dde-74b1-11e7-91ba-e1e82498a730.jpg)

**Comment by Fustershock** [comment]
Realm?

**Comment by kampeador** [comment]
That gossip option uses TBC spell, so you are getting "You cannot do that at this time." error.
I wrote about this here:
https://github.com/elysium-project/server/issues/1514

I've asked about "custom" features, including this one. There were no feedback from Elysium team, so nobody is working on it.

**Comment by QAkvastskaft** [comment]
Gossip will be removed with #2141

**Comment by Vilstar** [comment]
Anathema
