### ISSUE TITLE
Missing stats - Stormpike Insignia Rank 4

### ISSUE THREAD

**Issue by forusak** [elysium-project/server#1828]
Mainly missing teleport is crucial. Lower ranks were ok.
http://db.vanillagaming.org/?item=17902
![screenshot_15](https://user-images.githubusercontent.com/25019621/28752203-1c12949c-751a-11e7-9f8c-69c546e97963.jpg)

**Comment by GuybrushGit** [comment]
Fixed with new progressive database.
