### ISSUE TITLE
Bloodfang proc (8/8 rogue Tier 2) self buff part can be dodged or parried by the rogue.

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#183]
Bloodfang proc (8/8 rogue Tier 2) is composed of a damage part on the target and a "buff" part for the rogue.

When the proc occurs, the rogue will sometimes DODGE or PARRY the buff part. It seems the rogue's own dodge/parry chance are taken into account while it shouldn't.

Example : http://imgur.com/a/Ovwrk

The Bloodfang buff should apply to the rogue with no chance of failure. Each time Bloodfang procs, only the damage component can be dodged/blocked/parried by the target. The HoT self buff part should never be dodged/parried by the rogue nor the target.

The Bloodfang proc has 2 effects :

Spell Details

Duration 6 seconds School Physical Mechanic n/a Dispel type n/a

Effect #1 (2) School Damage (Physical) Value: 283

-> This is the damage part of the proc.

Effect #2 (6) Apply Aura #8: Periodic Heal Value: 50 Interval: 1 seconds

-> This the self-healing buff part of the proc.

**Comment by Unknown-as-Captain** [comment]
Haha, funny
