### ISSUE TITLE
Duskwood Skeletal Mages display wrong dialogue

### ISSUE THREAD

**Issue by hristovf** [elysium-project/server#1830]
In Duskwood, the Skeletal Mages in Duskwood seem to have a chance at using dialogue that isn't theirs. I attached a screenshot of this happening to me when I was playing last night. Not a major issue, but I thought you should be aware of it.
![2](https://user-images.githubusercontent.com/30570316/28753242-b5ed8560-7531-11e7-8930-866e06f73168.png)

**Comment by brotalnia** [comment]
I guess that particular skeleton was a member of the Defias before he died and joined the Scourge :smiley:

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
