### ISSUE TITLE
Guards stacking near Dashel Stonefist (Stormwind)

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#1833]
![billede](https://user-images.githubusercontent.com/1907820/28754236-daa750ba-7541-11e7-95ca-b759a8f9fc90.png)

Guards are stacking, because they come in to help against Dashel's friends during The Missing Diplomat, which they shouldn't. Guards should not randomly come into this courtyard at all, especially not during this quest event.

also for some reason Ol' Beasley decides to get involved as well, which he probably shouldn't either.

What faction does Dashel's friends have? perhaps it's wrong? since the guards and Beasley don't attack Dashel, just his friends.

**Comment by kampeador** [comment]
I've rewrote all Missing Diplomat scripts completely.
https://github.com/elysium-project/server/pull/1395

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
