### ISSUE TITLE
quest. "The Active Agent" Not showing after doing quest. "The flesh does not lie".

### ISSUE THREAD

**Issue by Teqnical** [elysium-project/server#1835]
DId the quest. The followup showed for 5 seconds. Accepted it. Could not find it in the questlog. And the questgiver does not want to give it to me anymore

**Comment by JosipbrozElysium** [comment]
I assume you are talking about Elysium, correct?
As of now, the quest is not ingame as the **patch 1.6 version** does not give any quest rewards. They will be added in 1.7 and so will the quest. Check this out: http://wowwiki.wikia.com/wiki/Quest:The_Active_Agent

Best regards!

**Comment by Tunzer** [comment]
This is not correct: in patch 1.7 the Rune was added, prior to that the seal of the dawn was the only reward, but it did exist and it functioned as an Argent dawn trinket
http://wowwiki.wikia.com/wiki/Seal_of_the_Dawn
