### ISSUE TITLE
There is too much Spirit of Kirith.

### ISSUE THREAD

**Issue by Bloodmoon-Darrowshire** [elysium-project/server#1837]
There is too much Spirit of Kirith. )  When you kill Kirith the Damned (http://db.vanillagaming.org/?npc=7728) spawn Spirit of Kirith (http://db.vanillagaming.org/?npc=7729). But when Kirith the Damned respawn (about 15 min) Spirit of Kirith not despawned. ( I think the time of his disappearance should be about 10-15  min.)
![wowscrnshot_072917_215629](https://user-images.githubusercontent.com/30354821/28759636-dd0ac304-75c9-11e7-86a7-126d8f503755.jpg)

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
