### ISSUE TITLE
Black Lotus not spawning on Elysium PvP?

### ISSUE THREAD

**Issue by Neejrow** [elysium-project/server#1838]
Up until last week I was able to easily get a black lotus minimum of 1 a day if I went herbing for an hour or two. But I have not seen a black lotus (outside of AV) for the last 5 days and have spent roughly 15 hours herbing. I have spent months building up lotus locations and I have found over 50 locations in Burning Steppes. So it's not me simply not knowing the spawn locations.

Other people I have spoken to have been unable to find lotus over the last few days also.

I'm just wondering if other people have been experiencing this issue also? Perhaps it is linked to the similar issue in Un'goro with the bugged Power Crystal spawns.

**Comment by ninjalootah** [comment]
Black lotus does not spawn

**Comment by ninjalootah** [comment]
https://github.com/elysium-project/server/issues/1653  My thread on it, it had been bugged for over a month if you did not know :D.  I can't believe more people aren't reporting this, it requires a fix ASAP

**Comment by Neejrow** [comment]
I have been getting Black Lotus up until Thursday. So I'm not so sure that it has been bugged for over a month.

**Comment by ninjalootah** [comment]
The bug happens randomly is why, sometimes it won't happen in between resets, sometimes it will.  Maybe not a month but 3 weeks min.  All depends if the lotus spawns on the GM removed location

**Comment by Phoosy** [comment]
Duplicate report of https://github.com/elysium-project/server/issues/1653
Close this.

**Comment by JosipbrozElysium** [comment]
Fixed.
