### ISSUE TITLE
Anathema Patch 1.10 - missing item: Titanic Leggings

### ISSUE THREAD

**Issue by TheAtaman** [elysium-project/server#1845]
Its been over two weeks now since patch 1.10 has been released on Anathema. Along other features and changes the release of the titanic leggings (http://db.vanillagaming.org/?item=22388#dropped-by) should have happened (as confirmed by Manaci here: https://forum.elysium-project.org/topic/46976-items-not-in-game-yet-on-anathema/).

According to the drop chance and the number of encounters it should be dropping from, the time window the patch has been out (around 3 weeks) as well as the number of encounter kills in that time it sounds weird that the recipe has not dropped yet. One must assume some mistake was made and the item has not been added to the loot table.

**Comment by Trsko** [comment]
They should have atleast dropped a few times in Molten Core for some guilds or world bosses, maybe even 5 man dugeon like strat live, people are farming that like crazy.  I also think they forgot to add them or something got messed up.

**Comment by TheAtaman** [comment]
alrightm its been fixed!
