### ISSUE TITLE
Blackfathom Villainy

### ISSUE THREAD

**Issue by cocobrown23** [elysium-project/server#1846]
Quest is currently not accessible to lvl 19 twinks for the alliance. Best in slot wand comes from this quest. Horde can finish the quest, but the prequest for alliance (in search of thaelrid) is bugged to require lvl 20 at the moment.

**Comment by martinjlowm** [comment]
This is backed up by [1] where comments state it's attainable at level 18, following the Blackfathom Villainy at [2] where one comments states that the Allakhazam-gathered data is wrong (says attainable at 25) and the quest is in fact attainable at level 18.

[1] http://web.archive.org/web/20070311014718/http://wow.allakhazam.com:80/db/quest.html?wquest=1198
[2] http://web.archive.org/web/20070307032409/http://wow.allakhazam.com:80/db/quest.html?wquest=1200

**Comment by martinjlowm** [comment]
Fixed by #1847

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/50445-development-update-19072017/
