### ISSUE TITLE
Can not start quest "Desperate Prayer"

### ISSUE THREAD

**Issue by mylosivich** [elysium-project/server#1849]
I am currently a level 18 human priest, I have tried talking to High Priestess Laurena multiple times but I receive no option to start the quest. I have tried deleting WDB and it has not solved any problems.

**Comment by mylosivich** [comment]
![image](https://user-images.githubusercontent.com/30609265/28803715-722597cc-7613-11e7-919e-dd64057dfeef.png)

**Comment by GuybrushGit** [comment]
Laurena doesn't start this quest.
