### ISSUE TITLE
Missing herb nodes

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#185]
Several types of herb nodes are missing in open zones and instances :

    Dire Maul East lower courtyard (Old Ironbark room) does not have any herb nodes. Can just enter the instance by either of its portals, jump down with tracking Herbs and notice no herb nodes are in the lower courtyard.

-> DM East lower courtyard should have 2 Dreamfoil and 2 Gromsblood whose locations vary each reset.

    Gravemoss
        Arathi Highlands, Stromgarde Keep (cemetery area) > no nodes (1 player checked 07/02. Nothing for 30 mins)
        Desolace, Kodo Graveyard (middle of the zone map) > no nodes (1 player checked 07/02. Nothing for 30 mins)
        Dukswood, Raven Hill cemetary (west of the zone) + The Tranquil Gardens Cemetery (south east of the zone)

Gravemoss
        Arathi Highlands, Stromgarde Keep (cemetery area) > up to around 8 nodes close to the NPC Deneb Walker (27.0,58.8)
        Desolace, Kodo Graveyard (middle of the zone map) > up to around 10 different nodes located all over across the graveyard. These might exist but the respawn timer is far off what it should be.
        Dukswood, Raven Hill cemetary (west of the zone) > up to 10-15 nodes + The Tranquil Gardens Cemetery (south east of the zone) > up to around 6 nodes.

-> Gravemoss nodes should be on a (maximum) 30 mins respawn timer, to be affected by dynamic respawn timer mechanic. Currently on Anathema if you stick around these areas for 30 mins you will not see a single gravemoss node respawn.

Sources

    Allakhazam thread dating from Nov 26th 2006 : http://wow.allakhazam.com/forum.html?forum=69&mid=1164531156263294102
    Containing a list (scroll down) of herbs by locations and types dating dating from Oct-Nov 2005
    Allakhazam comment dating from Aug 5th 2006 : https://web.archive.org/web/20061026014830/http://wow.allakhazam.com/db/object.html?wobject=151

As a reminder, current patch Anathema realm is on (1.8.x) was released Oct 10th 2005 during retail. Therefore the list mentioned in that thread applies to current patch progression.

    "Dire Maul East has four guaranteed spawns, 2 Dreamfoil, 2 Gromsblood, in the lower courtyard where Old Ironbark is. The four spawn points do move around the courtyard and some you will need to kill mobs to get or you'll have to pass over." This comment is from Nov 26th 2006 which corresponds to patch 1.12.

    Video example of node locations (the mage has TBC talents but the sources above and below prove these herb nodes in DM E were already there pre-tbc) : https://www.youtube.com/watch?v=rkcBX_Hn7R0
    MAIN PROOF > 1st comment on this page from Aug 5th 2006 : https://web.archive.org/web/20061026014830/http://wow.allakhazam.com/db/object.html?wobject=151

 "Nov 27 2006 at 2:01 AM ohmikeghod the Venerable
Here's the list I made over a year ago: Arathi Highlands . Grave moss
Duskwood . Grave moss
Desolace . Grave moss

List upgraded 10-11-05: added Artha. s Tears- Black Lotus- Blindweed- Dreamfoil- Ghost Mushrooms- Gromsblood-

Wintersbite- additional location for Wildvine List upgraded 10-18-05: added Plaguebloom and Heart of the WIld List upgraded 10-22-05: added Mountain Silversage List upgraded 11-5-05: added Icecap and Bloodvine"

**Comment by dabadoo** [comment]
bump.

This fix would have a big impact on herb prices. Especially dreamfoil and gromsblood.

**Comment by Braindot** [comment]
Bump!
