### ISSUE TITLE
Paladin Reckoning doesnt display stacks

### ISSUE THREAD

**Issue by Monkeyondabs** [elysium-project/server#1850]
When a monster crits me (paladin) i can't see my reckoning stack however i do see after swinging multiple hits as if there was stacks, slight issue but still would like to see my stacks.

**Comment by theloras** [comment]
doesnt exist in the vanilla UI - you need the reck counter addon

**Comment by Mostprovidedlinks** [comment]
Download reckcounter 
Pls close this

**Comment by ssishtar** [comment]
Reckoning never displayed stacks in vanilla. Never ever.
