### ISSUE TITLE
MISSION BUG <A LIVELY SCOUT>

### ISSUE THREAD

**Issue by moilzymomo** [elysium-project/server#1852]
Dear GM:

hello from china,after this update,I find a bug of this mission,I have finish the mission **body can tell you truth** in the  eastern plaguelands,and I sucsess to get the misson  **A LIVELY SCOUT** ,But after I get it, my mission list is full 20/20,so I refuse it to get another one which is easy to finish.
But today I find that I cant get the  **A LIVELY SCOUT** again from the npc.I have discuss from other player in bbs in china,they meet the same problem as me. 
would u pls check the game on your side,I think it is a bug,I need the ornament from this mission,tks a lot,hope to get your reply soon

Marcomo

**Comment by Schmoha** [comment]
GAMEMASTER???? ARE YOU SEARCHING FOR A GAMEMASTER ON THE BUGTRACKER ???????????????????????????????????????

**Comment by moilzymomo** [comment]
anyone to help me?
