### ISSUE TITLE
Mark of the wild not reflecting talent points

### ISSUE THREAD

**Issue by zeravlwerdna** [elysium-project/server#1854]
Ive have rank 2 mark of the wild. I have maxed it out using 5 talent points, but it is still only giving me 65 armor. When hovering my mouse over it in the talent point box, it shows that an increase was to take place, but it is not being reflected when i use the spell on myself or others.

**Comment by GuybrushGit** [comment]
Can't reproduce. The spell tooltip stays at 65 that's not something we can change but your armor still increases by 87.
