### ISSUE TITLE
Raidlocked to BRD

### ISSUE THREAD

**Issue by Pewtersprite** [elysium-project/server#1859]
A few guildies and I went into BRD the other day, and instead of a fresh ID we were presented with an ID where numerous bosses and mobs were already dead, and those who entered the ID could not reset the instance to get another. On Raid Info, we now see that BRD is raid-locked to us, with no reset timer, so it appears we're permanently locked out of BRD. The BRD in question is 177.
![raid id bug](https://user-images.githubusercontent.com/30630139/28832677-71295c26-76dd-11e7-9c12-15bb16c3ea08.png)

**Comment by JosipbrozElysium** [comment]
Duplicate. Please use search first before posting.
