### ISSUE TITLE
Twilight Npc do not drop texts or twilight sets

### ISSUE THREAD

**Issue by Svartv** [elysium-project/server#1860]
As the title states, basically cleared an entire camp without a single text nor setpiece.
Please have a look, Hard to gain the CH rep w/o being able to turn in texts or doing Templars. same goes for tactical assignments. A lot of them require Templar kills.

**Comment by Phoosy** [comment]
Duplicate report, use the search function before posting a bug report.
https://github.com/elysium-project/server/issues/1619
https://github.com/elysium-project/server/issues/1535
https://github.com/elysium-project/server/issues/1528

**Comment by BrianWilliams28** [comment]
Dear dev team,

Can any update be provided on this bug? It's been a while since these items stopped dropping in Silithus on Anathema and they are needed in order to complete the Earthstrike quest. I've put in a lot of work to get the badges already.
