### ISSUE TITLE
Quest: The Missing Diplomat is not working

### ISSUE THREAD

**Issue by LollingChris** [elysium-project/server#1863]
See attach, I already beat him down under 20% HP, and he changed to friendly as expected, but the quest wasn't marked as finished.
![image](https://user-images.githubusercontent.com/15726503/28838957-9b4dd90e-7724-11e7-839e-7f0d515748cd.png)
![image](https://user-images.githubusercontent.com/15726503/28839004-cfd7cc0c-7724-11e7-9281-1c15aecdd5b8.png)

**Comment by kampeador** [comment]
Have you defeated him being in the group mode?

**Comment by Ivan-Villa** [comment]
Same Issue, no credit upon defeating him

**Comment by mmdobber538** [comment]
I noticed you're also a hunter, and following kampeador's suggestion I dismissed my pet and did the quest again, it worked fine then.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
