### ISSUE TITLE
Winterfall furbolgs reputation bug

### ISSUE THREAD

**Issue by Aenur** [elysium-project/server#1865]
Whenever I kill winterfall furbolgs, I am getting 5 negative rep with Timbermaw hold instead of 5 positive

**Comment by Aenur** [comment]
I seem to be getting positive rep for killing timbermaw furbolgs

**Comment by JosipbrozElysium** [comment]
Could you please provide some concrete evidence? And please tell the realm you're playing on. I cannot reproduce this issue on our QA realms.

**Comment by Aenur** [comment]
My apologies I made a big mistake with this one, all is well
