### ISSUE TITLE
Encrypted Twilight Texts won't drop

### ISSUE THREAD

**Issue by MBlood66** [elysium-project/server#1866]
I've been killing Twilight's Hammer people in Silithus for an hour now and no Encrypted Twilight Texts have dropped for the quest of the same name. Has anyone else experienced an issue with this?

**Comment by Phoosy** [comment]
Duplicate report, use the search function before posting a bug report.
https://github.com/elysium-project/server/issues/1619
https://github.com/elysium-project/server/issues/1535
https://github.com/elysium-project/server/issues/1528
https://github.com/elysium-project/server/issues/1860
