### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Ewberplz** [elysium-project/server#1869]
I am trying to log in for the first time and it automatically says "disconnected from server" i have verified my account, but still cannot get in...any suggestions?

**Comment by Deliv1** [comment]
I have the same problem. I can not connect. conect to server.... :(

**Comment by Ewberplz** [comment]
Servers are back online, still getting the same message. "Disconnected from server"

**Comment by JosipbrozElysium** [comment]
Not a bug report
