### ISSUE TITLE
58 shaman quest "Material Assistance" does not properly start the next quest in the chain

### ISSUE THREAD

**Issue by aliu92** [elysium-project/server#1870]
It it suppose to start the quest "The Darkreaver Menace" but once you turn in the materials, nothing happens. Avoid completing this quest at this time. The materials needed for this quest (Azerothian Diamond & Pristine Black Diamond) are quite expensive and you will lose them.

**Comment by GuybrushGit** [comment]
Darkreaver Menace is requiring level 60 instead of 58.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
