### ISSUE TITLE
Kicked off the game twice can't log back in

### ISSUE THREAD

**Issue by wadewell** [elysium-project/server#1871]
While doing DM west 15 to 20 minutes ago kicked off the game go to log back in and it says connected but won't pull anything else up Elysium. This also happened in DM North earlier and I couldn't log in for hours. What is going On? Can I get some kind of update? Trying to gear myself up but I keep getting kicked from the group because of this problem.

**Comment by wadewell** [comment]
Currently running 1060 gpu 16gb ram i5 1tb hd and 250gb solid. With 300mb  per sec internet

**Comment by pixle8did** [comment]
Same...and the Realm Status shows Online? What?

**Comment by wadewell** [comment]
Yeah says 5k+ online right now. It's either a bug or they're failing to update the page

**Comment by wadewell** [comment]
Still having the same problem

**Comment by wadewell** [comment]
Tried logging in on my laptop still nothing just connected. If your server is down have your webpage show it. This is a bug many people are dealing with but there is no kind of update from support

**Comment by JosipbrozElysium** [comment]
Not a bug report. Please, do not post any connection related issues here. Check out our Twitter feed for downtime.
