### ISSUE TITLE
My item in mailbox disappeared

### ISSUE THREAD

**Issue by potokadepus** [elysium-project/server#1872]
I bought another Gut Ripper(off-hand) in the ah. I went to the mailbox, clicked on the dagger, then i clicked again in it image. When i looked in my bag, it wasn't there and anywhere else. I spent the rest of my gold to buy this dagger, and now, for no reason, i lost it... i'm sending an SS to prove...
![wowscrnshot_080217_012958](https://user-images.githubusercontent.com/25845224/28858073-54b11a6a-7724-11e7-8ae4-d0da92f7f634.png)

**Comment by Peter2345** [comment]
See https://github.com/elysium-project/server/issues/599

**Comment by JosipbrozElysium** [comment]
Noted. I will close this issue though and let #599 stay open, as it's a duplicate.

Best regards!
