### ISSUE TITLE
My account couldn't login

### ISSUE THREAD

**Issue by nxnd1** [elysium-project/server#1873]
I got a large lag at about 6:00, and then , I ended the wow process in order to restart game. but I can't login 
for nearly two hours. can you help me?  I am a Chinese , May I have a Chinese reply?

**Comment by Heyhohohoho** [comment]
服務器維護

**Comment by nxnd1** [comment]
服務器什麼時候可以修復？

**Comment by JosipbrozElysium** [comment]
Not a bug report. Please visit our forums for this.

Best regards!
