### ISSUE TITLE
Returning WG mark of honor bug(no quest!!)

### ISSUE THREAD

**Issue by saze111231234** [elysium-project/server#1875]
I can't return my moh to npc.

He only accept AB moh. most of my WG moh is gonna disappear
![cap 2017-08-02 02-35-27-117](https://user-images.githubusercontent.com/30648650/28860845-3610a140-772c-11e7-8e14-b56e2dacdd1f.jpg)

Anathema, horde
ID : saze

**Comment by Stackieks** [comment]
I have the same problem. I cannot obtain the qeust to return warsong gulch marks. I made a ticket and the GM told me to retake the qeust (I cant see the qeust in my qeustlog) and delete my WDB folder. This didnt solve the problem and he told me to go here.

**Comment by berndbrotx** [comment]
I have the same problem. The npc only shows me the 'Invaders of Alterac Valley' quest. I can not turn my wsg or ab moh in. Also deleted my WDB folder but it didn't help.

**Comment by bora994** [comment]
me too

**Comment by Travnastington** [comment]
I am also having this issue.

**Comment by thepparker** [comment]
Duplicate
