### ISSUE TITLE
Unable to invite people into a party.

### ISSUE THREAD

**Issue by Akumati** [elysium-project/server#1876]
https://www.youtube.com/watch?v=z7sNhLb571A&feature=youtu.be

Issue happened upon logging in after that 4 hourish downtime patch. Tried restarting the game, my PC just incase, tried different character.

I do get the message if someone else is already in a party though, so I can't tell if i'm an isolated issue or what.

**Comment by JosipbrozElysium** [comment]
Not a bug report. Please visit our forums for this issue.

Best regards!
