### ISSUE TITLE
"Gol'dir" being killed by other NPC.

### ISSUE THREAD

**Issue by Narvad** [elysium-project/server#1877]
The spawn point of [Gol'dir](http://db.vanillagaming.org/?npc=2316) is situated on the line of sight with Sindicate Spy, which leads to his death every time he/his enemy respawns.
https://youtu.be/mFTMOm564Pw

**Comment by ifyousayso** [comment]
You know that if a tree falls in the woods and nobody is there to hear it, it makes no sound, right?

Same with Gol'dir: If noone is around, he doesn't get killed.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
