### ISSUE TITLE
Mark of Honor still in mailbox after 2 days + Honor reset

### ISSUE THREAD

**Issue by Jhn3712** [elysium-project/server#1878]
So i recently started ranking again, and a huge problem before was stacking marks. Some time ago this issue was fixed, and Marks was deleted in your mailbox av 24h. 

This is not happening anymore, some of my marks went out this  on Monday 31/7, was & still are in my mailbox after todays honor reset.

Please fix this.

**Comment by Phoosy** [comment]
This is a duplicate issue report. Use the search function, close this.
