### ISSUE TITLE
Cured heavy leather stack issues

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#1881]
Cured heavy leather doesn't stack to 20ies only tens

**Comment by Pisshead** [comment]
*hide

**Comment by thepparker** [comment]
Stack limit is correctly 10

**Comment by Pisshead** [comment]
Correct relating to what? Evne if it is correctly implemented the way Blizzard did it back in the days it still makes no sense: Cured light hides 20 stacks, cured medium hides 20 stacks, cured heavy hide 10 stacks(?!) cured thick hide 20 stacks cured rugged hide 20 stacks. Isn't this kinda odd...? Don't you think maybe Blizzard got it wrong there or one of the databases is wrong here? I don't want to argue and go on your nerves. I'm just pointing out the curious irregularity ;)
