### ISSUE TITLE
Plaugebloom spawn rate significantly reduced in EPL/WPL

### ISSUE THREAD

**Issue by preslim** [elysium-project/server#1882]
Dreamfoil and Arthus Tears seem fine

**Comment by Phoosy** [comment]
There's numerous issues already created about herb spawns being low (unintentionally or not). Use those instead of opening a new issue needlessly.

**Comment by preslim** [comment]
I see 0 on the front page.  I'm not wasting my time.

**Comment by Heyhohohoho** [comment]
Phoosy your input isn't needed

**Comment by Phoosy** [comment]
My input is attempting to keep the Issues list from being bloated from needless reports. No one is going to advocate for that. Just because they're not on the front page doesn't mean the issue doesn't exist. Use the search function.

**Comment by JosipbrozElysium** [comment]
@Heyhohohoho His input is welcome, as he is right. Please do not post duplicates and post proper bug reports. We cannot work with such bug reports.

Anyways, fixed.
