### ISSUE TITLE
Baron Aquanis dropped Quest two times, reward item twice 

### ISSUE THREAD

**Issue by precisionn** [elysium-project/server#1884]
Baron Aquanis quest dropped for me twice, first time I got Xp + reward item, second time go no xp but was able to get another reward item. I'm new player to WoW so i dont know if this is supposed to happen or not so im reporting it to the GM to confirm. Right now im dual wielding Outlaw sabre both from Baron Aquanis quest. Plz give me confirmation/

**Comment by ifyousayso** [comment]
Quest seems to be repeatable.. doubtful it should be.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
