### ISSUE TITLE
Ragnaros Isn't Spawning

### ISSUE THREAD

**Issue by Pewtersprite** [elysium-project/server#1886]
My guild is currently doing Molten Core ID 9042 on the Elysium server.
We've talked to Majordomo, and he has spoken his dialogue for summoning Ragnaros. Nothing happens, and Domo is just standing there, motionless and impossible to interact with.

**Comment by JosipbrozElysium** [comment]
Not a bug report. Please, contact a GM via ingame ticket.

Best regards!
