### ISSUE TITLE
Hurricane (Weapon,Bow)

### ISSUE THREAD

**Issue by Anomaly242** [elysium-project/server#1888]
Should deal an added 1-5 frost damage per hit.
It does not.

**Comment by JosipbrozElysium** [comment]
Please provide some detailed info. Check this out: https://github.com/elysium-project/server/blob/development/docs/Bug%20Reporting.md

Best regards!

**Comment by Phatcat** [comment]
Feb 2005; https://web.archive.org/web/20050224133941/http://wow.allakhazam.com:80/item.html?witem=2824
Apr 2006; https://web.archive.org/web/20060415151132/http://wow.allakhazam.com:80/item.html?witem=2824

(was later changed (but before TBC); (can be seen by hovering over the item link here); 
Nov 2006; https://web.archive.org/web/20061118024533/http://wow.allakhazam.com:80/dyn/items/iname15.html)

**Comment by GuybrushGit** [comment]
Same as https://github.com/elysium-project/server/issues/513
