### ISSUE TITLE
Quest Quel'serrar

### ISSUE THREAD

**Issue by andresnake** [elysium-project/server#1889]
Hello, I bought the Quel'serrar quest and got the quest, but the item disappeared and I was asked to quit the quest and erase the WDB folder but it did not work.

I did according to the message but the item did not reappear and now I'm without the sword quest, please I paid 330g to get it

**Comment by thepparker** [comment]
If you had already handed the quest in, you should be able to pick the next step up from the NPC. If not, make a ticket in-game.
