### ISSUE TITLE
Spirit of Zandalar shoud persist through death until patch 1.11

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#189]
Initially reported and **confirmed** here : https://elysium-project.org/bugtracker/issue/368

The "Spirit of Zandalar" Buff that is applied to you when you turn in Hakkars Heart is currently removed upon death.

Spell ID : 24425 Quest ID : 8183

The "Spirit of Zandalar" Buff shoud persist through death before Patch 1.11

Source : 1.11 official patch notes _"The Spirit of Zandalar will no longer persist through death."_

**Comment by Slicy** [comment]
Is it considered a mechanic ?

Swiftness of Zanza, Spirit of Zanza and Sheen of Zanza are currently persisting through death as supposed to pre 1.11, so I don't know what is the actual stance about this is.

**Comment by QAClayton** [comment]
Spirit of Zandalar needs to be fixed to implement through death like zanza's do. 
Confirmed.

**Comment by m-laniakea** [comment]
This was already fixed, and there should be a line somewhere in itemization.
This fix does not belong in the /server repository.
https://github.com/elysium-project/itemization

**Comment by Slicy** [comment]
The issue concerns the Spirit of Zandalar buff, not the 3 potions/flask (Swiftness of Zanza, Spirit of Zanza and Sheen of Zanza) which are indeed already fixed since 24 days and working as intended right now. The 3 consumables are mentioned as example of what has been decided to work pre 1.11 not long ago.

I do not know where it is actually handled, but Spirit of Zandalar is the buff resulting from the event (and not an item usage) occurring once the quest Heart of Hakkar is turned in at the NPC Molthor.

**Comment by StadenElysium** [comment]
Fixed in a04decd5cccb50d7a3f2818ca85abe3d537f9a24.
