### ISSUE TITLE
Marven Rivetseeker

### ISSUE THREAD

**Issue by RefractedChaos** [elysium-project/server#1894]
Marven Rivetseeker in Tanaris is not giving the "Secret of the Circle" quest, after completing the quest "The Stone Circle". My character is Level 50.

**Comment by Kolmarwow** [comment]
You're supposed to get "Into the Depths" after completing "The Stone Cricle". Then you turn in Into the Depths inside the Sunken Temple instance, and then you get the "Secret of the Circle" follow up. 

So as long as you have Into the Depths, then everything is working correctly.

**Comment by thepparker** [comment]
Follow the chain
