### ISSUE TITLE
(Quest) Weapons of Choice

### ISSUE THREAD

**Issue by LockeBox** [elysium-project/server#1896]
Can't turn it in. That's the only problem.

**Comment by ifyousayso** [comment]
Old issues that might still exist:
- Make sure you haven't moved any of the quest items to and from your bank.
- Make sure you haven't destroyed or sold any quets items before attempting to turn it in. For example: You pick up two daggers, throw away one and try to complete the quest = fail. Even if you have the correct amount left, if you have gotten rid of any, it might not be possible to finish the quest.

Try abandoning and re-accepting..
