### ISSUE TITLE
Unable to get quest.

### ISSUE THREAD

**Issue by Jorix1992** [elysium-project/server#1898]
Hello Dear GMs,

I'm unable to obtain the quest "Commander Gor'shak" - I have completed the quest ''Disharmony of Fire'' which is according to reports the pre-requisite for it. Is that quest still available? Thanks

Best regards,

Your biggest fan <3

**Comment by JosipbrozElysium** [comment]
Not a bug Report!

**Comment by Jorix1992** [comment]
What is it then? Also the point of posting is to find a solution. Will you provide one?
