### ISSUE TITLE
Unable to deliver quest

### ISSUE THREAD

**Issue by Jorix1992** [elysium-project/server#1899]
Hello Dear GMs,

I'm unable to deliver the quest ''Message to the wildhammer" (which is to kill 15 blood elves from 4 different categories) please help
Best regards,

Your biggest fan <3

**Comment by JosipbrozElysium** [comment]
Not a bug report.

**Comment by Jorix1992** [comment]
What is it then? Also the point of posting is to find a solution. Will you provide one?

**Comment by Nimeto** [comment]
Im not able to even pick up the Quest :S :S
