### ISSUE TITLE
Hurricane (Bow) Not having correct stats

### ISSUE THREAD

**Issue by Anomaly242** [elysium-project/server#1903]
The hurricane bow should have 1-5 frost damage, it currently does not.

I am reposting this as my previous post was deemed invalid, after asking me to provide more information,
I was asleep at that time though another person did post link to back up this statement.
So i will repost those links here and implore you to not ''Invalidate'' posts at the moment you see them.

Feb 2005; https://web.archive.org/web/20050224133941/http://wow.allakhazam.com:80/item.html?witem=2824
Apr 2006; https://web.archive.org/web/20060415151132/http://wow.allakhazam.com:80/item.html?witem=2824

+ 1 - 5 Frost Damage
(was later changed (but before TBC); (can be seen by hovering over the item link here);
Jul 2006; https://web.archive.org/web/20060720165455/http://wow.allakhazam.com:80/dyn/items/iname15.html

Equip: Chance to strike your target with a Frost Arrow for 31 to 45 Frost Damage.
(Looking at June 2006 it was still 1 - 5 frost damage; https://web.archive.org/web/20060616004124/http://wow.allakhazam.com:80/dyn/items/iname15.html)

**Comment by Phatcat** [comment]
... my beautiful formatting... butchered... xD

**Comment by Anomaly242** [comment]
I do apologize, i must admit i can be a bit lazy when it comes ,,, ''finishing touches''

**Comment by some2** [comment]
Hurricane (ID: 2824):

Until 1.11.0: Should deal addional frost damage (1-5 dmg) (or physical - blizzbug) (*2)
1.11.0 and later: Chance to trigger a damaging frost effect (31-45) (*3)

Dwarven Hand Cannon (ID: 2099):

Until 1.12.0: Should deal addional fire damage (1-11 dmg) (or physical - blizzbug) (*5)
1.12.0 and later: Chance to trigger a damaging fire effect (33-49) (*4)

Bow of Searing Arrows (ID: 2825):

Until 1.12.0: Should deal addional fire damage (1-5 dmg) (or physical - blizzbug) (*7)
1.12.0 and later: Chance to trigger a damaging fire effect (18-26) (*4)

Venomstrike (ID: 6469):

Until 1.12.0: Should deal addional nature damage (3-6 dmg) (or physical - blizzbug) (*6)
1.12.0 and later: Chance to trigger a damaging nature effect (31-45) (*4)

Galgann's Fireblaster (ID: 9412):

Until 1.12.0: Should deal addional fire damage (1-3 dmg) (or physical - blizzbug) (*6)
1.12.0 and later: Chance to trigger a damaging fire effect (12-18) (*4)

Shell Launcher Shotgun (ID: 13146):

Until 1.12.0: Should deal addional fire damage (1-4 dmg) (or physical - blizzbug) (*6)
1.12.0 and later: Chance to trigger a damaging fire effect (18-26)

See https://wow.gamepedia.com/Patch_1.12.0

Development branch is at 1.12.1 (AFAIK), so everything is correct. For versions below you should
probably create a "itemization" issue (other repo).

**Comment by Anomaly242** [comment]
It clearly states, Until 1.11.0, it should deal 1-5 frost damage, and it does not, the frost arrow effect should come after, and this i am not disputing, though venomstrike and galganns wich i've both used, seems it should not have their chance on effect until 1.12.0, wich they do currently have.

So there is obviously something that is not correct.

**Comment by lovemonkeyz** [comment]
All the weapons that had +x-y elemental damage was changed to have procs in 1.12 

We're running 1.12.1 itemization. Everything is as it should be.

**Comment by Anomaly242** [comment]
Alright, Then i wonder why the hurricane does not have anything (1-5 and or/ frost arrow)
Is it was always supposed to have some sort of buff.

**Comment by lovemonkeyz** [comment]
That is odd indeed. I thought I recalled seeing it with the correct proc, but that was bow of searing arrows. In the hopes it was a cache issue, I cleared it, yet again, nothing. 

So, apologies for not fully understanding the issue you reported. Since you spoke of the old +x/y damage I presumed it was that it lacked that, not that it didn't have any stats or procs at all. 

![capture](https://user-images.githubusercontent.com/26850364/28969361-984935d0-7924-11e7-8e7a-3d6b794052ca.PNG)

**Comment by Phatcat** [comment]
And yet to still continue to downvote his issue, Lovemonkeyz?

Is that out of sheer spite now?

**Comment by lovemonkeyz** [comment]
Continue to? No no, you got me wrong friend, I just simply didn't think about having left it there.

**Comment by Anomaly242** [comment]
Well now then that we all understand eachother, it is indeed missing something and a valid issue ?

**Comment by Phatcat** [comment]
Yes, it is a valid issue, that it gives nothing is an issue that belongs here, but it's gonna get fixed with the equip stat since that is 1.12.1, so in part it belongs as a database issue (the thing about it should be static + 1 - 5 frost damage on the running servers is an itemization thing and that part belongs on the other tracker).

**Comment by GuybrushGit** [comment]
Same as https://github.com/elysium-project/server/issues/513
