### ISSUE TITLE
Rallying Cry of the Dragonslayer does not give ranged attackpower

### ISSUE THREAD

**Issue by johnpettersson** [elysium-project/server#1905]
Rallying Cry of the Dragonslayer (which you get when you turn in the onyxia/nefarian head in orgrimmar/stormwind) does not give ranged attackpower. 

The tooltip says attackpower. Not exclusively melee attackpower. 

So i think it should give ranged attackpower aswell, right?

**Comment by Haiwuu** [comment]
http://blue.cardplace.com/cache/wow-hunter/263254.htm

no RAP.

**Comment by lovemonkeyz** [comment]
^ He is correct. It was the saddest part about playing a hunter in retail, honestly.

**Comment by stesve** [comment]
Buff tooltip: ""Increases melee, ranged, and spell critical strike rating and grants additional **melee attack power.**""

**Comment by johnpettersson** [comment]
Tooltip does'nt say melee attack power though, just says attackpower. Does for me anyway. But after reading more about it i realize that you guys are right it's blizzlike :(

**Comment by thepparker** [comment]
rip hunters
