### ISSUE TITLE
Unable to pick up the quest "Stalwarts Battlegear"

### ISSUE THREAD

**Issue by preats** [elysium-project/server#1906]
Hello
I am unable to pick up the quest "Stalwarts Battlegear" from Vargus, even though i have done all pre quests according to db.vanillagaming.org. I am also revered with CC, and I have tried deleting my WDB and disabling all mods.

I play on Anthema server and my ingame nick is Preat

Thank you

**Comment by theloras** [comment]
https://github.com/elysium-project/server/issues/1494

**Comment by thepparker** [comment]
Duplicate
