### ISSUE TITLE
Can't loot bosses every other time

### ISSUE THREAD

**Issue by DuMees** [elysium-project/server#1909]
Today happened again, at the boss, I see the drop, people are needing or greeding on it, but I am left out of the need/greed roll.

Happens quite often.

**Comment by DuMees** [comment]
And again, at the next boss. No looting for me.

**Comment by thepparker** [comment]
Is the item unique? Do you already have one? Do you have an addon that is hiding the roll?

**Comment by DuMees** [comment]
It only happens on "Blue" items as it seems. No addons being used on looting.

**Comment by ifyousayso** [comment]
Are you sure that others are rolling on them? Perhaps you only roll on epics and better..

**Comment by thepparker** [comment]
We can't reproduce this. Need more information. EG: item name, whether you have one, etc. If you have some, feel free to comment.
