### ISSUE TITLE
Argent Dawn Commission does not work sometimes: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#191]
BUGGED BEHAVIOR
wear Argent Dawn Commission -> log off -> log back on -> Argent Dawn Commission buff gone, have to put it off and put back on to regain the buff.

Similar behavior when player dies and resurrect.

 CORRECT BEHAVIOR
Argent Dawn Commission buff should stay all the time

 SOURCES
Myself

COMMENTS from QAKvastskaft:

The buff is confirmed to not re-apply after resurrection.
This affect the following 3 items:

Seal of the dawn item id: 13209 spell id: 23930
Rune of the dawn item id:19812 spell id: 24198
Argent dawn commission item id: 12846 spell id: 17670

The buff should be correctly re-applied when turning back alive.

Logging out and logging in works as intended when I tested.

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/222

**Comment by shmgiy429** [comment]
Pretty sure Feign Death is triggering this as well, I gave up trying to get scourge stones in Stratholme; every Feign would reset the aura and would have to take the trinket off and put it back on to collect them again.

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/43686-development-update-05042017/
