### ISSUE TITLE
Unable to pick up the quest "Badlands Reagent Run II" 

### ISSUE THREAD

**Issue by Golkosh** [elysium-project/server#1910]
Hello! I had herbalism/mining when i completed quest "Uldaman Reagent Run". After that i learned alchemy (skill 204), but i cant pick up quest "Badlands Reagent Run II". Thanks in advance for the answer.

**Comment by Kolmarwow** [comment]
you need an alchemy skill of 210.

**Comment by Golkosh** [comment]
Thank u very much!
