### ISSUE TITLE
WHERE IS THE FOOKIN DREADSTEED BOSS LOOT

### ISSUE THREAD

**Issue by staplerx300** [elysium-project/server#1915]
WHERE

IS

IT

http://i.imgur.com/Sp9gqa7.jpg

(video being uploaded momentarily)

**Comment by staplerx300** [comment]
What the hell do you mean invalid

https://youtu.be/VEnoPNR3oBE

We did the event and the dread lord didn't drop any loot

**Comment by JosipbrozElysium** [comment]
Invalid = poorly written bug report (bad title, bad text)
Check this out: https://github.com/elysium-project/server/blob/development/docs/Bug%20Reporting.md and then try again (as a new issue).

Best regards!

**Comment by staplerx300** [comment]
I did already, my bad lol I was mad at no loot. 

#1927 #1923
