### ISSUE TITLE
Brocade Bracers

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#1918]
Should be grey, but is currently a green (uncommon) item on elysium.

So that's a green set of cloth bracers with no stats and only 14 armor on Elysium atm, mind you.

https://web.archive.org/web/20041110051809/http://wow.allakhazam.com:80/db/item.html?witem=3379 <- from 2004, shows it as grey.

https://web.archive.org/web/20060618040422/http://wow.allakhazam.com:80/db/item.html?witem=3379 <- from 2006, still grey...

**Comment by Phatcat** [comment]
This is not an itemization issue, this is an item issue. It's not supposed to change rarity with any patch, it just has the wrong one set. This is just a database issue. This is why I showed it from both 2004 and 2006..

**Comment by GuybrushGit** [comment]
Fixed with new progressive database.
