### ISSUE TITLE
skewed MC drop tables

### ISSUE THREAD

**Issue by mfigueiredo** [elysium-project/server#1924]
My guild have been (in zelth'kur then in elysium) raiding MC for some time and ever since I got in the guild I've noticed that the drop tables are not really random, but skewed towards warlocks, shamans and druids, exactly the classes we have less members. For example, in this week raid almost every boss had 1 warlock item. We are able to fully equip warlocks in one or two raids. It's ridiculous. Each lock item should have close to 12% drop rate. That possibility of having a drop rate of 5 warlock tier items on raid with 10 bosses should be 0.002 %. We are we seeing this consistently every week.

And I hear that all the time MC is being raided, the guild had about 3 weapon drops. For almost 6 months? With the exception of the Shadowstrike which always drops. That's an item that should have a rate of 20% drop rate, but we measure it to be close 90%.

Please acknowledge and fix.
Thank you very much, Miguel (Beefzor)

**Comment by Phoosy** [comment]
Where is your citation for what the drop rate should be vs. what the drop rate actually is? Do you have concrete numbers for either or that would be actually helpful rather than vague speculation?

**Comment by Furnicarium** [comment]
I can confirm this - seems like loot is only for druids and warlocks, 0 rings dropped, 15 cloacks from Ragna.

**Comment by stesve** [comment]
http://realmplayers.com/RaidStats/RaidList.aspx?realm=Dar&InstanceFilter=MC

Can't see anything unusual. I could write a small script to parse the loot info... But seems like most the loot complaints is a little biased.

**Comment by mfigueiredo** [comment]
Hello guys, we have two raid logs. Here is last one:
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83649
magmadar - 2 warlock items, garr - 1 warlock item, baron gedom - 1 warlock item, shazzrah - 1 warlock item, golemagg - 1 warlock item
10 bosses -> 6 warlock items, 4 shaman, 3 mage, 2 priest, 1 warrior, 0 hunter, 0 druid, 0 rogue
sulfuron - we didn't loot, raid leader screaming at yet another drop of shadowstrike - 100% rate for our guild

previous week: http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=82686
2 shaman, 5 mage, 2 warrior, 2 hunter, 2 priest, 1 rogue, 0 druid, 0 lock- i'm suprised, no lock loot in this raid 
sulfuron - shadowstrike drops 

I'll try to find more evidence.

**Comment by stesve** [comment]
Well... you'll need a way larger samplesize to rule out rng. Probably 200-400.

**Comment by mfigueiredo** [comment]
@Phoosy I've looked at the % drop rate in Atlasloot addon.
It is on the same ballpark of http://db.vanillagaming.org. Examples for lock items:

(magmar) http://db.vanillagaming.org/?npc=11982, 11% on pants
(garr) http://db.vanillagaming.org/?npc=12057, 11% on head
(baron gedon) http://db.vanillagaming.org/?npc=12056, shoulders (17%, loot table 1), (6%, loot table 3)
(shazzrah) http://db.vanillagaming.org/?npc=12264, boots (17%, loot table 1), (6%, loot table 3)
(Golemagg) http://db.vanillagaming.org/?npc=11988, 11% on chest

**Comment by mfigueiredo** [comment]
@stesve the script to parse http://realmplayers.com/RaidStats/ would help greatly on having achieving a good enough sample size.

Looking at a few of other raid logs below. They do look fairly randomize on armor. 2 times excessive armor, 3 times excessive weapons, but mainly no shadowstrike drops.
It differs from our perceived experience were we almost never have weapon drops besides shadowstrike which always drops and skewed armor drops. Guildies joke that GMs are pushing the numbers.
I'll try to get more data.

http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83796, armor drops look well randomize, but 3 weapon drops (including shadowstrike)
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83791 armor drops look well randomize, but 2 weapon drops, no shadowstrike
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83791 armor drops look well randomize, but 2 weapon drops, no shadowstrike
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83763 armor drops look well randomize, but 4 weapon drops, no shadowstrike
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83743, 5 mage drops, no shadowstrike
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83755 armor drops look well randomize, no shadowstrike
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83736, armor drops look well randomize, no shadowstrike
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=83646, 4 shaman drops, 5 weapon drops including shadowstrike

**Comment by RussianE39** [comment]
I proposed a patch months ago which will fix that and many other issues. But they still not pushed it in.
https://github.com/elysium-project/server/issues/42

**Comment by mfigueiredo** [comment]
Thank you @RussianE39.

Been talking among my guildies, and don't think I'll be able to get more logs, unless they are future logs or if we prepare a report out of realplayers.com/RaidStats, by means of a script with the purpose that @stesve mentioned.

Anyway, since the patch exists, feels like the feeling is shared among more people of the community besides my guild and @Furnicarium.
Enough for someone to stop playing and code a fix for the problem. Perhaps worth giving some though.

**Comment by thepparker** [comment]
That patch actually makes little to no difference to drop rates despite the impression it may give you. Regardless of how the list is sorted, it is entirely dependent on the chance roll. The only time it would have a noticeable impact is if a pool is incorrectly configured and the total drop chance of items in it exceeds 100%. Furthermore, it literally has no impact on equally shared pools such as tier pools, where all items have an equal chance to drop. 

As with any RNG system, there is a distribution, and some people lie on either extreme. Unfortunately, if you are the extreme then it really sucks. In contrast to your experience, my guild has received only a single piece of Warlock T2 from Ragnaros in over 6 months of raiding on Elysium, and we have never seen a Warlock T2 helm drop from Onyxia. If anything, we receive a lot of Hunter pieces. In the end, it's all about RNG.

**Comment by RussianE39** [comment]
@thepparker , the patch mostly affects equally shared pools thats why it is so important. If you did Magmadar loot table check with current LootMgr, maybe you can also apply patch and show us results with patch applied?

**Comment by mfigueiredo** [comment]
Hello guys, last raid happened yesterday. Nice distribution of drops.
Except shadowstrike dropped again. Based on logs the chance of that happening should be 0.8% (based of 3 logged raids). Our past experience is 100% drop rate.

http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=84680
lock - 1, shaman - 3, rogue - 3, hunter - 3, mage - 3, druid - 1, priest - 1, warrior - 0

@thepparker thank you for the findings on the experience. But some percentages I see on Magmadar don't agree with what I see here: http://db.vanillagaming.org/?npc=11982

Tier items have 11%, and there should be 2 drops, so the percentage should be close to 22%. The measurements are around 20%. Seems fair enough.

The other drops, they don't seem right. All other epic items besides tier items should have a drop rate of 7% at Magmar, and we see a drop rate of 20% in the measurements. 13% is a big difference.
Comments are welcome.

**Comment by GuybrushGit** [comment]
The cmangos change will do nothing, Elysium loot system is random enough. 

Here's 100k rolls of Chromaggus:
![image](https://user-images.githubusercontent.com/26495604/29255448-631e3924-8099-11e7-9211-fc5d7c289b70.png)

Extremely close to the values in the database.

**Comment by mfigueiredo** [comment]
Hello @GuybrushGit, thank you very much for the effort and sharing the report.

Just double checked the item # id against http://db.vanillagaming.org/ (ex: ?http://db.vanillagaming.org/?item=16902). The percentages are indeed in the same ballpark. The percentages are also reasonably well distributed.

There's a difference of 4%, in that db.vanillagaming.org points to 21% on tier items and the report says close to 25%. Perhaps it has something to do with drop tables for current patch vs db.vanillagaming.org patch?

Also spotted a 5% difference for http://db.vanillagaming.org/?item=19347, it points to 15% and the report to 10%. It's the same difference 5% difference for all 10% items in the report (less possibility for drop).
The non tier item, non weapon-items, have also a difference of 5%. The report points to 20% and db.vanillagaming.org 15% (less possibility for drop).

Are these loot tables implemented as intended?

Anyway, my guild haven't looted anything from Chromaggus, so we could not have complained about his loot table yet. @thepparker posted a report on Magmadar where I pinpointed 13% difference between db.vanillagaming.org and his report on non tier items. That's a gross difference.

Also, I'm really interested to see a similar simulation on sulfuron and a reason why we consistently always get shadowstrike loot.

Comments are welcome.
Thank you very much, Miguel

**Comment by thepparker** [comment]
@RussianE39, like I said previously, the referenced patch only affects explicitly chanced pools, and even then only has an impact if the pools are incorrectly configured. The second patch you have linked is not necessarily blizzlike - it's still pretty unclear how duplicate drops across pools should be handled, and if they should even be possible.

In regards to the chances on VanillaGaming, they are not an accurate source for drop rates or loot pools, and are often incorrect. In the specific case of Magmadar, when the new MC items were added in 1.4, previous unique drops were not suddenly changed to the shared loot pool which all bosses now have (the items with 7%). Instead, a third pool was added to the boss, and the existing items spread between. This is why you see much higher droprates on https://web.archive.org/web/20060510042822/http://wow.allakhazam.com:80/db/mob.html?wmob=11982 than VG.

As such, the Magmadar pool functions similar to this:
Pool 1: 4 tier pieces, 1 unique item (from before 1.4) - 20% each
Pool 2: 4 tier pieces, 1 unique item (from before 1.4) - 20% each
Pool 3: 2 Magmadar specific unique items (Eskhander's Claw/Earthshaker 20% each) + 10 remaining shared items spread evenly (6% each)

The other bosses are in a similar situation. For Sulfuron (https://web.archive.org/web/20060424180247/http://wow.allakhazam.com:80/db/mob.html?wmob=12098):
Pool 1: 3 items (Hunter/Vendorstrike/Priest), 33% each (pre-1.4)
Pool 2: 2 Pre-1.4 Sulfuron items (Nightslayer/Might @ 30% each), +10 remaining shared items spread evenly (4% each)
These aren't as close to the Allakhazam records as Magmadar's, and could probably use some tweaking, but they are more accurate than VGs records. If you can find some evidence that suggests the pools should be spread differently, I'd be willing to take a look at it.

**Comment by mfigueiredo** [comment]
Thank you @thepparker.
You clearly know something about the loot tables. I concede that http://db.vanillagaming.org wont' be an accurate representation of blizzard loot tables drop % in 2006 or any year perhaps. The archive for alakazam would be a closer approach.
Still the percentages between http://db.vanillagaming.org  and alakazam archive do seem close for some items. For the Sulfuron example we see:
- 23.5% alakazam, 20% db.vanillagaming.org  on Shadowstrike (!)
- 19.6% to 21.1% alakazam, 20% db.vanillagaming.org on shoulder tier items 
- 2.8% to 1.25% alakazam, 7% db.vanillagaming.org on the remainder items 

I can't explain why drops for the other items are lower than 7% on alakazam. You seem to have a point when saying that the reminder of the items should be spread at 4%.
But still there is a large difference between the 33% for "Vendorstrike" and the 20% we see in vanillagaming and alakazam (from the point of view of my guild, it was 100%).
So there are two sources agreeing on for Shadowstrike to be around 20%, not 33%. Is the loot table poorly implemented?

My guild disbanded, so I'll stop providing more raid logs to feed this thread.
Thank you guys for all the feedback.
Cheers! Miguel
