### ISSUE TITLE
Bloodseeker Crossbow

### ISSUE THREAD

**Issue by Rageward** [elysium-project/server#1925]
Hello , I have completed the bloodseeker crossbow quest quite a while back and didnt receive the crossbow I know its a while now reporting this but all that i can get now is the rune recall item , as this is no fault of my own can you please reimburse me for this item as it is pre raid bis.

**Comment by Anomaly242** [comment]
I have the same problem, only getting rune, and not a choice of items

**Comment by stesve** [comment]
Github is for bugreporting. You should make a ticket ingame if you need support from a gm.

**Comment by Rageward** [comment]
They told me to make a ticket on the bug tracker
