### ISSUE TITLE
Quest Text Displaying wrong name (screenshot): CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#193]
BUGGED BEHAVIOR
Mac is supposed to be my character's name as seen in the screenshot.

https://www.dropbox.com/s/7enjg6h4yddlbcy/elysium_bug_wrong_name.jpg?dl=0

 CORRECT BEHAVIOR
In this case the quest should've displayed Unlink

 SOURCES
http://www.wowhead.com/quest=5064/grimtotem-spying

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/577

**Comment by QAClayton** [comment]
Confirmed.
