### ISSUE TITLE
The Active Agent quest bugged

### ISSUE THREAD

**Issue by MiinaLelih** [elysium-project/server#1931]
Tried to compete the Active Agent quest... have the item.... says complete in quest log... cannot turn into NPC.  Made a ticket, talked to GM Thunderskin, who asked me to abandon quest, delete wdb folder, and relog... did.  NPC did not offer the quest again, told GM again, after a minute the quests said "completed the active agent" in chat log and made the completion noise, ... I assume completed by the GM but it did not pop up the quest box to let me choose the item I wanted.  It did not give me an Item at all and it left the quest item still in my inventory.  I just wanted the Rune of the Dawn.... can this be fixed?

**Comment by Crafall** [comment]
I am having the same issue.

**Comment by Dalleren** [comment]
Please provide any evidence that this quest was supposed to be in patch 1.6.

Hint: Perhaps it was added by mistake.

**Comment by Crafall** [comment]
don't know if it was supposed to be in 1.6, but I picked up the quest, completed it, couldn't turn it in so I dropped it. Scourge Data is still in my inventory.

**Comment by thepparker** [comment]
The quest is not meant to be available yet, as the Rune was not added until 1.7
