### ISSUE TITLE
Haven't received any response 

### ISSUE THREAD

**Issue by potokadepus** [elysium-project/server#1933]
A few days ago, something happened to me in game. I bought a Gut ripper in the AH and tried to get it from the mailbox, when suddenly it disapeared. I've already created an issue (got closed cuz it was considered "duplicated" and even with me explaining that my item hadn't expire) and a ticket (since thursday morning have missed from the top screen "status", or how i see, got read already). However i didn't had any response from the staff, just feels like "ok, something happened... lets move on".  I need to know if you guys are going to do something or not... just answer me please. 
If you guys need it:
Darrowshire
Fluxxsync

**Comment by JosipbrozElysium** [comment]
It was closed and tagged as a duplicate, because this place is only for reporting bugs and we have already received a report on this. Individual problems (like you losing this item) belong to the forums and/or ingame tickets.

Best regards!
