### ISSUE TITLE
Un'goro Power Crystals

### ISSUE THREAD

**Issue by Hijop31** [elysium-project/server#1936]
After doing several laps around the Un'goro Crater between 12:00 am and 1:00 am servertime yesterday (4th of august) and between 12:00 pm - 1:00 pm (5th of agust) I've only come across one spawn of power crystals right next to Fireplume Ridge where I've actually seen the crystal in person. This leads me to believe that there is something wrong with the spawnrates of crystals throughout the zone. If this is an incorrect assumption by me and I've just had really bad luck, I apologize.
Thanks in advance.

![power crystals](https://user-images.githubusercontent.com/30749211/28995203-072187d2-79e3-11e7-966b-66a8b0a03e7d.jpg)

**Comment by Peter2345** [comment]
https://github.com/elysium-project/server/issues/1831

**Comment by thepparker** [comment]
Duplicate
