### ISSUE TITLE
Mind control glitch

### ISSUE THREAD

**Issue by Sneakyrhino1** [elysium-project/server#1937]
If a member of the opposite faction casts mind control on you or your party/raid members they will become half-alliance/horde meaning that they now posses the abilities of aquaman and can mount up and run with no water collision(water does not work for them, think=cant swim) and ontop of that some classes loses the ability to buff/interact and sometimes even heal the target that was mind controlled.

also ontop of the water issue if you were to be mind controlled as a paladin you can no longer Buff/blessing of sacrifice & blessing of protection or blessing of freedom friendlies untill you do a HARD relog. 

this creates the scenario where you dont know who is bugged if its you or them or both and not being able to buff/put helpfull spells on allies or yourself, sometimes not even cast heals is a major issue. 

example: 
horde1 mindcontrols alliance1 in arathi basin
alliance1 can now run from stables to BS underwater without being slowed down or in the "swim mode" and get there in 5seconds, and can no longer be buffed/given helpful spells and sometimes friendly targets will not be able to heal alliance1 because he is considered an enemy(when u cast the spell its invalid target)

theres alot of abuse going on with this spell currently. id suggest you to disable it untill fixed/reverted to previous state.

**Comment by Hsekr** [comment]
+Hard relog is not always fixing this issue on pve realm
+You see everybody as pvp flagged meaning u can attack then regardless if they are pvp flagged or not.
+Some npcs might become unfriendly to you ... cant buy/sell/quest


#1920 
#1912 
Issues are probably are related to this bug.

**Comment by sipertruk** [comment]
Other reports that include walking underwater :
#1715 
#1738

**Comment by Itembugs** [comment]
Mind control is also causing the priest casting mind control to become unattackable in duels
