### ISSUE TITLE
Stucked in a ghost form

### ISSUE THREAD

**Issue by JungleBoo** [elysium-project/server#1938]
Stucked in Arathi Higlands auto-unstuck doesn't work. Please return me to the graveyard as fast as possible ;)

Anathema-PVP

nickname : Kazanets (orc warrior 43)

**Comment by JungleBoo** [comment]
![image](https://user-images.githubusercontent.com/25306732/28995470-7781fbd8-79f2-11e7-9b54-254aa5595696.png)

**Comment by Peter2345** [comment]
You need an in-game ticket

**Comment by JosipbrozElysium** [comment]
Please contact a GM.

Best regards!
