### ISSUE TITLE
Magic Attunement talent mage

### ISSUE THREAD

**Issue by Linniee** [elysium-project/server#1945]
Magic Attunement talent in Arcane talent tree should increase effect of Amplify magic and Dampen magic by 25/50%. But it instead decreases these effects. 
I have 31 lvl mage, 2 talent points spent in it. Dampen magic rank 2, with base effect of decreasing spell damage taken by 30 and healing by up to 60. With talent decreasing damage taken by 20 and healing by up to 40. 
Amplify magic has decreased effect instead of increased too.

**Comment by GuybrushGit** [comment]
Works in dev.
