### ISSUE TITLE
[Anathema] Dungeon reset lockout also blocks raids.

### ISSUE THREAD

**Issue by delebota** [elysium-project/server#1948]
I can only confirm this on Anathema, but if you enter and exit a dungeon repeatedly and use your 5 resets per hour, you will also be blocked from entering a raid.

In my particular case I was farming SM:GY shortly before a ZG and MC raid. Both times I have been blocked from entering and had to wait for one of the dungeon resets to come off of cooldown in order to enter the raid.

**Comment by Fustershock** [comment]
It IS normal, it's SUPPOSED to be like this. That's why many people just do 3-4 runs if they think about some raids/needed dungeons later.

**Comment by delebota** [comment]
Ok, I wasn't sure and people in my guild thought it was supposed to be separate.

**Comment by JosipbrozElysium** [comment]
Yes, that's intended and blizzlike. Closing.

Best regards!
