### ISSUE TITLE
Pao'ka Swiftmountain isn't allied with PC while escorted

### ISSUE THREAD

**Issue by ifyousayso** [elysium-project/server#1949]
He starts Homeward Bound (q:4770) and starts to walk. When he runs into enemies, they fight, but if I pull something, he ignores them all. This makes the escort very difficult since I must let him walk straight into a bunch of mobs.

I'm not saying this is absolutely wrong, just that in all other escort quests, the escorted seems allied with the PC.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
