### ISSUE TITLE
Snufflenose Gopher (n:4781) took damage..

### ISSUE THREAD

**Issue by ifyousayso** [elysium-project/server#1950]
.. from Charlga Razorflank's (n:4421) Chain Bolt (s:8292). I'm not sure how this is supposed to work, but since the crate that spawns it is used up, perhaps this sort-of critter should be invulnerable?

**Comment by GuybrushGit** [comment]
>These things can move through walls and aggro mobs in the instance, so it's best to wait until after the instance is cleared before finishing off this quest.
http://www.wowhead.com/npc=4781/snufflenose-gopher#comments
