### ISSUE TITLE
fishing and nightfin snapper

### ISSUE THREAD

**Issue by orcleoqu** [elysium-project/server#1952]
sometimes it loots nothing and I assume it should be nightfin (cause its very low drop rate, not to 10%)  
the empty loot last 6 month since elysium starts

**Comment by Fustershock** [comment]
Close this and learn lurk more.

from WoWwiki
http://www.wowwiki.com/Fishing

There are 4 separate intervals of fishing times. These intervals are 6am-12pm, 12pm-6pm, 6pm-12am, and 12am-6am. During this time the drop rates of certain fish varies, for example, Sunscale Salmon and Nightfin Snapper. According to experimentation, the cycle appears to be the following:

* 6am-12pm - Nightfin and Sunscale
* 12pm-6pm - Sunscale only
* 6pm-12am - Nightfin and Sunscale
* 12am-6am - Nightfin only 

Nightfin Snapper has the highest drop rate from 12am-6am, but is never found between 12pm-6pm. On the other hand, Sunscale Salmon is never found between 12am-6am, but drops quite well from 12pm-6pm.

**Comment by Fustershock** [comment]
#1172 and #1935 can be useful here.

If you getting success cast on fish, but it's empty - it's not the needed time to get them.
Also, the server is not accurate to this times from wowwiki (6am-12pm and others), it might can be like 8-14 instead of 6-12.
