### ISSUE TITLE
Minor(?) quest sharing issue

### ISSUE THREAD

**Issue by ifyousayso** [elysium-project/server#1953]
So the full party entered Wailing Caverns (outside part, not instance) and I tried to share all quests multiple times while being at various distances from the others. Some accepted.. I guess.. didn't really check.

After more than an hour, we were done with the instance (all quests), the party disbanded.. and a few minutes later, I receive the server message that someone that had been in my party had accepted my quest.

This seems very weird/wrong to me.

**Comment by thepparker** [comment]
Probably using an addon that hides it
