### ISSUE TITLE
Judgement of command still scaling at only 20%..

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1958]
Judgement of command should scale at 43%

The normal spells range is 169-187
I am gaining a coefficient of only 20% on elysium
Roughly 60 damage from 295 spell damage.
I should be recieving 127 damage 
295x0.43=126.85 (damage scales up)
Video proof: I use 0 spell damage and my range is hitting 172-181 (min is 169 and max is 187)
I use 295 spell damage and hit 232-247

247-60 = 187 (highest)
232-60= 172
229-60 = 169 (lowest)

https://youtu.be/btnCCAfC7nk (elysium)
I used judgement many many times

Fix required: 

- Change judgement of commands coefficient to 43%

--------------------

Proof from late retail videos (naxx etc)

https://www.youtube.com/watch?v=ay7RU0N-44Y

Judgement of Command hits in 390 spell damage gear (NO sanctity aura) for exactly 342 damage on the rogue in this video, 4:95 and 384 damage on 10% berserking stance at 2:00
he appears to be hitting some wartriors for exactly 10% more damage
if you add all the healing enchants etc and gear he has that he goes through and hes even mentioned in the description it was 390 spell damage here https://www.youtube.com/watch?v=ay7RU0N-44Y

With 204 spell damage hero charm trinket + 390 spell damage gear (594) I am hitting 305-310 judgement of command. He is hitting far higher judgements than us on this  without using his trinket. Fix please

http://i.imgur.com/CGLtyjo.png
This paladin is doing 244 judgement of commands at 58 spell damage in 1.12
watch his video please

https://www.youtube.com/watch?v=VEs9coe5XRg&spfreload=10 (naxx patch) and is in exactly 163 spell damage gear, and 313 with the flask meaning he should hit non stunned judgement of command for 305-340 (he states before crusader strike in description)

and 335-374 with sanctity

http://db.vanillagaming.org/?spell=20920

is hitting a 449 judgement of command hit 2:43 and up to 500 judgements (vengeance added)

he hits commands many times in the mid 400s

nightfall procs at one moment later and the damage is higher.

I didnt include judgement of the crusader which is the reason he is hitting in the 449 and not 335-375 @43% coefficient, meaning judgement of the crusader increases his damage and vengeance included

This is proven wrong in the video. It should scale at 43% regardless of whether its a non stun or a stun

a new video I found scaling at 43%. paladin has no flask of supreme or judgement bindings and paladin is at around 150-156 spell damage in this video

https://www.youtube.com/watch?v=rXNWvytYbyo&t=0m53s

Sept 2006

his judgement of command is hitting 339 with sanctity aura and jotc

**Comment by Phoosy** [comment]
Creating duplicates of the same issue you yourself have already reported only muddies up the issue tracker with false reports. Close this one AND https://github.com/elysium-project/server/issues/1547 while you're at it and seek updates on https://github.com/elysium-project/server/issues/1136 rather than spam us with duplicates.

**Comment by thepparker** [comment]
Duplicate
