### ISSUE TITLE
Aimed Shot (Not working properly)

### ISSUE THREAD

**Issue by Anomaly242** [elysium-project/server#1961]
Aimed shot does not seem to increase damage by set amount, instead does stated amount damage directly.

The information states for example (Aimed Shot - Rank 5: An aimed shot that (Increases) damage done by 460)

Thus this should increase the base damage value of said shot by said amount. not due said amount of damage directly. spells like Multishot also states that it increases the damage done instead of doing said amount, And in the case of multishot this does ring true.

I can provide an endless amount of Aimed shot screenshots stating lower damage then what the spell is supposed to increase base damage value by. thus proving that it does stated damage instead of increasing it.

**Comment by Xyter** [comment]
It is bugged. I'm only level 37 with Aimed Shot Rank 3 but the tooltip says "An aimed shot that increases ranged damage by 200." My auto hits are 90-110 non crit but the Aimed Shot is only hitting for 210-225 max non crit.

**Comment by brotalnia** [comment]
I would think the damage just gets reduced by armor since it is physical.

**Comment by Xyter** [comment]
> I would think the damage just gets reduced by armor since it is physical.

80-100 less damage from skill tooltip+reg damage is a bit of a stretch for armor compensation.

**Comment by GuybrushGit** [comment]
Tested on a 0 armor target. Damage is being properly added.
