### ISSUE TITLE
Hunters pet Claw and ALL ranged shots (multi/autoshot etc) isnt giving redoubt when it crits me

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1963]
claw from the Hunters pet and ALL ranged shots (multi/autoshot etc) isnt giving redoubt when it crits me
All crits should proc redoubt

Proof:

https://youtu.be/QJbl2V7OJrQ

--------------
Another duel proof

https://youtu.be/D1JZiAXBfrs 1st part

Now look at combat log in 2nd part

https://youtu.be/Bmu4JhVVwM0 (part 2) shows all the hits

http://db.vanillagaming.org/?spell=20137

As you can see in the first and second videos I am receiving reckoning from ranged shots and redoubt from ordinary melee crits from the pet 
but claw and ranged shot crits are not giving me redoubt when they should.

Fix:

- make claw and ranged shot crits activate redoubt

**Comment by Mostprovidedlinks** [comment]
As you can see I am receiving reckoning and redoubt from ranged shots and melee crits from the pet but claw and ranged shots are not giving me redoubt when they must

**Comment by Mostprovidedlinks** [comment]
As you can see I am receiving reckoning from ranged shots and reckoning and redoubt from ranged shots and melee crits from the pet but claw and ranged shots are not giving me redoubt when they should.

Fix:

- make claw and ranged shots five redoubt

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
