### ISSUE TITLE
物品BUG：无尽黑暗之刃的效果不能被AOE法术触发

### ISSUE THREAD

**Issue by iiooo** [elysium-project/server#1970]
item ID:17780
无尽黑暗之刃的效果不能被AOE法术触发。
在官方版本中，这个属性效果是可以被任何伤害性法术触发的，包括群体伤害法术。例如暴风雪，冰锥术，奥暴术……
都可以正确触发装备的属性效果。

**Comment by Fustershock** [comment]
ni hao

**Comment by iiooo** [comment]
Hi

**Comment by knasen88** [comment]
The effect of endless dark edges can not be triggered by AOE spells.
In the official version, this property effect can be triggered by any damaging spells, including group damage spells. Such as blizzard, ice picks, Austrian storms ... ...
You can correctly trigger the effect of equipment properties.

using google translate, tldr he wants dagger to work with aoe spells, he would have to prove it somehow though.
