### ISSUE TITLE
Smoked Sagefish:  Spell is not available to you

### ISSUE THREAD

**Issue by Schmooz** [elysium-project/server#1971]
I'm currently at 113 cooking, Horde faction on Elysium.
I've learned the recipe, it's in my cooking GUI.  Have all the required materials in my bags, but I get a "Spell is not available to you" message on screen if I try to use the "Create" button, or the "Create All" button.

Recipe sells from Xen'to in Orgrimmar for 5s.  Says it only requires 80 cooking.

Already tried logging out / back in, but the issue persists.

**Comment by Kolmarwow** [comment]
This is intentional, since Smoked Sagefish wasn't added until patch 1.9. They've added some kind of ghetto fix to it by making the spell not available to you instead of removing it from the game, which often confuses people.

**Comment by Schmooz** [comment]
Thanks, so glad I bought those sagefish on the AH.

**Comment by thepparker** [comment]
Duplicate; added in a later patch.
