### ISSUE TITLE
Warrior Issues.

### ISSUE THREAD

**Issue by PlatinumAries** [elysium-project/server#1972]
Alright. I've got a couple things to address on the topic of warriors. Firstly, Why when attacking mobs am I missing, dodging and being parried so much? It seems every other attack is either parried or a miss. My weapon proficiency is maxed, mob is my level +/- 1 level, Changing from single to 2h or even dual wield nothing changes. Secondly. In Thousand Needles, the mob Boiling Elemental casts a debuff reducing your chance to hit by 52%. I as a 27 warrior legitimately CAN't solo them. The spell is on me 24/7. Honestly feel something should be done about this, whether changing how ofter the spell is cast or...

**Comment by Fustershock** [comment]
should be renamed "Warrior butthurts"

**Comment by Phoosy** [comment]
>Honestly feel something should be done about this, whether changing how ofter the spell is cast or...

This would not warrant an actual change. Can you provide any substantial evidence that the hit/miss chance is incorrect for what the values are _supposed_ to be for a Retail Vanilla WoW server?

**Comment by Crolug** [comment]
Welcome to the warrior's world :D. That's how the things are with warriors, either get used to it, level in groups or re-roll. If you decide to stay - watch out for any +% hit items you'll lay your eyes on - if you're not a tank, ignore if they're leather, mail or cloth.

**Comment by nikolay510** [comment]
Deal with it. The only thing you can do is dress yourself in INT gear and maxx out wep skill
