### ISSUE TITLE
NPC and Boss Knock Back effects are wiping out 100% of tank threat instead of just a % portion

### ISSUE THREAD

**Issue by Vigete** [elysium-project/server#1974]
this is the explenation: https://elysium-project.org/bugtracker/issue/1330

**Comment by stesve** [comment]
copy pasta for convenience.

> Multiple NPC mobs and Bosses such as Dire Maul North Guards, The Ravenian, Prince Tortheldrin, Magistrate Barthilas and Kirtonos the Herald with Knock Back effects are currently removing all threat to tanks when they cast.
> 
> This is especially troubling for Prot Paladins trying to tank any of these mobs or bosses due to not having a taunt to grab agro back asap.
> 
> BWL raid boss Broodlord Lashlayer may be similarly bugged seeing as he uses the same Knock Back as The Ravenian:
> 
> Knock Away 10 yd range Instant Inflicts normal damage plus 30 to an enemy and knocks it back. http://db.vanillagaming.org/?spell=18670
>

**Comment by stesve** [comment]
Broodlords knockbacks are working correctly imo. Threat isn't wiped.

Haven't tanked 5-mans for a while, but i dont recall total threatwipe on magistrate barthilas.

The threatthreshold is changed when you are knocked out of meleerange.

**Comment by theloras** [comment]
Original bug report back on the website repository:

NPC and Boss Knock Back effects are wiping out 100% of tank threat instead of just a % portion
https://elysium-project.org/bugtracker/issue/1330

**Comment by GuybrushGit** [comment]
Knockback is not resetting threat. Some bosses like Kirtonos or Prince just have an agro dump as part of their script.
