### ISSUE TITLE
Typo on the "Beer Basted Boar Ribs" quest: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#198]
BUGGED BEHAVIOR
Triggered

 CORRECT BEHAVIOR
Unsure

 SOURCES
http://i.imgur.com/I5H4sQM.jpg

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/1192

**Comment by QAClayton** [comment]
Confirmed.
