### ISSUE TITLE
how to stack crit to 100%

### ISSUE THREAD

**Issue by Isorfilith** [elysium-project/server#1980]
+ works on every elysium realm
+ must have talents "increases crit chance with weapons"
+ start a duel with warrior or rogue 
+ in duel rogue or warrrior uses on you "Disarm" - during disarm time you must unequip your weapon ant then equip it back 
+ this way crit stacks up to 100% until relog

hope it gets fixed soon, stupid warriors abusing in pvp

**Comment by Fustershock** [comment]
also there is a bug with running under water. PvP with a priest, use mind controll on you, get you to water,  end the MC. after this you will be able to walk on ground in water, even use mount. the speed is not reducing, you walk at your normal speed and mounting on +100%

**Comment by Fustershock** [comment]
@Dedathema

**Comment by Furnicarium** [comment]
Well known old bug, all "top"-guilds were using it always, look at crit % of their rogues, hunters and warriors with over 1200 dps.
