### ISSUE TITLE
Ancient hakkari manslayer proc chance non existent on flurry dual wield fury warriors

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1984]
Ancient hakkari manslayer proc chance too low warriors
http://db.vanillagaming.org/?item=19852

Proc is 6% and on paladins the proc seems to work every 18 normal swings on paladins or 9 using a seal of righteousness which acts as dual wield)

On this fury warrior I was hit 98 times (not including the extra abilities which mean I got hit over 110 times) and the proc didnt work since the start of the video. You can see at the start it procs but after all those hits it never procced again. Now watch the paladin video. Clearly there is something wrong. Warriors are being ripped off. Can someone fix the proc chance on dual wield please. Something is causing the proc chance to be terrible on warriors

https://youtu.be/Kd3Ln9jYzNQ (low proc on dual wield + flurry) 100+ hits and no proc since start of video
Warrior is using class strikes as well

https://youtu.be/CGXb6xgdcls (high proc on paladin using seal + swing (equivalent to dual wield)
(not as many hits and  many procs)

Fix:

- increase proc chance for Ancient hakkari manslayer for warriors using dual wield
(find out what spell is causing this problem in the warrior spellbook)

**Comment by GuybrushGit** [comment]
Procs are the same for every class. Tested in dev and got a proc in a few mins.

**Comment by Mostprovidedlinks** [comment]
That doesn't explain how it wouldn't proc in 110 swings on that warrior. I'll test it again.

**Comment by Mostprovidedlinks** [comment]
It procced every 14 swings or less on the paladin

**Comment by Mostprovidedlinks** [comment]
Its still happening for warriors. The proc is too low in dual wield.

**Comment by Mostprovidedlinks** [comment]
The proc chance is happening on dual wield like 1% while on paladins its much higher.

**Comment by Mostprovidedlinks** [comment]
The point is, when a warrior uses them they barely proc in a light year.

**Comment by Mostprovidedlinks** [comment]
They both proc GuybrushGit, ancient hakkari manslayer does proc on the dual wielded warrior or paladin
But my point is, when a warrior uses them they barely proc in a light year.

When a paladin uses it it procs at 6% and higher with sor it hits on every 16 second hit on average so 8 hits. (2.0 speed weapon)

sor + swing = warrior dual wield

Meaning that warrior should be proccing maybe 9%+ of the time with the weapon
and yet we see a 1% proc chance

There is something horribly wrong.

**Comment by Mostprovidedlinks** [comment]
I will upload another video
