### ISSUE TITLE
Quest Broken "Falcon's Call" Zanza the Restless

### ISSUE THREAD

**Issue by raja991** [elysium-project/server#1985]
Quest "Falcon's Call" from Zanza the Restless in ZG is broken on Anathema.  All three items are in inventory and I have honoured rep with Zanadalar.  The quest never completes as if an item is missing from inventory, please see screenshot.
EDIT - I have deleted the contents of my WDB folder already.

![rajazo_falcon_call](https://user-images.githubusercontent.com/30809166/29041237-11d44540-7b67-11e7-9dc8-f6d112caeeac.png)

**Comment by Kolmarwow** [comment]
Look closely at your Punctured Voodoo Doll.

"Classes: Priest"

You have the Priest version of the doll. You need to grab the version with "Classes: Hunter" on it. It's a bit confusing since all 9 dolls have the exact same name, the only difference is which class it's locked to.

**Comment by thepparker** [comment]
As above, wrong doll
