### ISSUE TITLE
Whipper Root Tuber, Night Dragon's Breath and Demonic Runes shares cooldown

### ISSUE THREAD

**Issue by Javelja** [elysium-project/server#1987]
Currently whipper roots, night dragon and demonic runes share a 2min cooldown.
Not only is them sharing cooldown wrong, but the cooldown itself is too long as well. The correct duration is 1 minute.
Source: https://youtu.be/UW5mv_e4ZmM?t=8m40s
(See upper left corner)
This goes for Mana Ruby and Dark Runes too.
Should be a quick fix.

**Comment by fgsfdss** [comment]
Mana Gem & Demonic/Dark Rune confirmed at 2:10 in the same video.

**Comment by Javelja** [comment]
That's right.
The [original video](http://www.warcraftmovies.com/movieview.php?id=10868) was uploaded 25/11/2005, which was [patch 1.8.3](http://wowwiki.wikia.com/wiki/Patch_1.8.3) during retail.

**Comment by femdead** [comment]
needs more evidence, also feet pics

**Comment by Javelja** [comment]
False comment. Please delete this "Femdead" person

**Comment by Javelja** [comment]
Appearently this was changed in [patch 1.11.0](http://wowwiki.wikia.com/wiki/Patch_1.11.0) (i.e. Naxx). The cooldowns on these items should not be shared until then.

_"We have re-evaluated the mechanics of consumable items in the game and concluded that these should work in a more intuitive manner. As such, most items that can not be equipped with right click abilities have been streamlined into one of three categories. Using an item of a particular category will trigger a shared cooldown among all other items in the same category. The categories break down as follows with category cooldowns as listed.
Potions 2 minutes: This includes items such as Health Potion, Mana Potion, Invisibility Potion and Mighty Rage Potion.
Aggressive 1 minute: This includes items such as explosives, Really Sticky Glue and Discombobulator Ray.
Non-Aggressive 2 minutes: This includes items such as Healthstone, Night Dragon's Breath, Whipper Root Tuber and Target Dummy."_

**Comment by Sabre142** [comment]
Unfortunately, I don't think item cooldown sharing will be changed to match the previous patches.

**Comment by thepparker** [comment]
We are using 1.12 spell mechanics, including item cooldowns.
