### ISSUE TITLE
Trueaim Gauntlets Not having their post 1.12 itemization values

### ISSUE THREAD

**Issue by Anomaly242** [elysium-project/server#1988]
Trueaim Gauntlets are currently uncommon quality wich increases bows +8
This were true pre 1.12

Now however these should be in there rare (Blue) state:

http://www.wowhead.com/item=13255/trueaim-gauntlets

This shows the itemisation change.
https://wow.gamepedia.com/Trueaim_Gauntlets

**Comment by Phoosy** [comment]
None of the realms are on patch 1.12. Your point?

**Comment by Kolmarwow** [comment]
The client itself is on patch 1.12.1, but the servers are on different server patches. Elysium is on patch 1.6, Darrowshire on 1.7 (soon 1.8), and Anathema on 1.10.

So the Trueaim Gauntlets should have their blue quality stats on Anathema, but not on Elysium or Darrowshire.

**Comment by Anomaly242** [comment]
Yet most other items have their itemisation changes post for 1.12

**Comment by Phoosy** [comment]
Those would be bugged and need to be reported then with evidence that their stats do not reflect the patch the individual servers are on and what they should be.

**Comment by JosipbrozElysium** [comment]
This is intended and blizzlike, not a bug!

Best regards!
