### ISSUE TITLE
BS token return qeust is fucked up

### ISSUE THREAD

**Issue by saze111231234** [elysium-project/server#1990]
ok so this is my second one in this forum coz I don't think this stupid bug is fixed in few days

there are no token return quests so I can't return my token

for 2 weeks, I had a disadvantage of honor because of this stupid bug

It is well seen issue for newly created character, and very critical as same as raid boss don't drop items.

Anathema/horde/character name: saze 

please fix this problem

**Comment by thepparker** [comment]
Duplicate
