### ISSUE TITLE
Banned and I don't know why

### ISSUE THREAD

**Issue by lemke1109** [elysium-project/server#1992]
I've been away from elysium for quite some time now and I'm assuming a chinese hacker or something of the kind got onto my account. Im not sure what I can do about getting my account back but I would love to hear back from you guys about what i can do. Thanks <3

**Comment by Peter2345** [comment]
https://forum.elysium-project.org/forum/351-ban-appeals/

**Comment by lemke1109** [comment]
I cannot sign in with my credentials there, however, I have no problem signing in on the elysium website.

**Comment by Peter2345** [comment]
Forum accounts and game accounts need different credentials. Create a forum account.

**Comment by lemke1109** [comment]
Peter I love you, thank you
