### ISSUE TITLE
Cannot turn in "Weapons of Choice" in Barrens

### ISSUE THREAD

**Issue by Apokryphe** [elysium-project/server#1993]
Playing a warrior on Elysium realm. I have all three of the required quest items for the quest "Weapons of Choice" and the quest shows as completed in my log, but the quest giver still has a silver question mark and I cannot click "Complete" in the quest dialog window.

Any help would be much appreciated.

**Comment by Sabre142** [comment]
You can attempt to abandon and retake quests which have this issue. You should be able to hand it in then.

**Comment by JosipbrozElysium** [comment]
What Sabre142 said.

This is an already known issue, which can happen to many other quests and not only to this one, thus, I will close this report as it's already known!

Best regards!
