### ISSUE TITLE
Emerald Dragons do no longer spawn since patch 1.10 release

### ISSUE THREAD

**Issue by Georgios-Mavridis** [elysium-project/server#1994]
**This information/report is focused on Anathema!**

# **BUGGED BEHAVIOR**
## Before the 1.10 patch release

Before the patch 1.10 was release (this means before 12.07.17) the Emerald Dragons did spawn but did not work 100% correct. The behavior was: Every Dragon had its own spawn timer, the timer always started when the dragon got killed. The timer was exactly 120h (5d). This means if you kill one dragon it will spawn in exactly 5 days again. Further more there was no variation of the dragons regarding the locations. It was always:

Duskwood
- Name = Ysondre
- Abilities = Ysondre
- Loot = Ysondre

Ashenvale
- Name = Taerar
- Abilities = Taerar
- Loot = Taerar

Hinterlands
- Name = Lethon
- Abilities = Lethon
- Loot = Lethon

Feralas
- Name = Lethon
- Abilities = Emeriss
- Loot = Lethon

So to sum it up, the dragons did always spawn 5 days after they got killed. The same dragon did always spawn at the same location with the same name and abilities mentioned above. There was no dragon with the name Emeriss but a double Lethon where one had the abilities from Emeriss (in Feralas).

Last time killed the dragons with the behavior mentioned above: 10.07.2017 (killed all 4 dragons more than 20 times with exactly this behavior)

## After the 1.10 path release

After the patch release the dragons spawned once on **15.07.2017** as expected (everyone exactly 5d after they got killed). However there was something different this time...

Duskwood

- Name = Emeriss
- Abilities = Ysondre
- Loot = Emeriss

Ashenvale

- Name = Taerar
- Abilities = Taerar
- Loot = Taerar

Hinterlands

- Name = Ysondre
- Abilities = Lethon
- Loot = Ysondre

Feralas

- Name = Lethon
- Abilities = Emeriss
- Loot = Lethon

As you can see, there was the first time a dragon with the name Emeriss and also the first time Emeriss loot. However, the names did again not match the abilities. The abilities were based on the location the same like it was before the patch, Ysondre abilities at Duskwood, Taerar abilities at Ashenvale, Lethon abilities at Hinterlands and Emeriss abilities at Feralas.

**After killing the Emerald Dragons on 15.07.17 they never spawned again.** It looks like the spawn timers are disabled or do not work as they did before the patch update. **3 weeks have been gone since the last kill and no spawn of a single dragon yet.**

To sum it up: **Emerald Dragons do no longer spawn**

# **CORRECT BEHAVIOR**
The very correct behavior would be:

All four Emerald Dragons spawn at the same time. There is no fix location. It is random where which dragon is going to be. Also very obvious there should be no double dragon and also the abilities and loot should match the name of the dragon.

The spawn timer for the dragons is disabled until all four dragons are dead! This means as long a single dragon is alive all others are not going to spawn. If the last dragon alive is dead the spawn timer is activated and will produce a random number between 96 and 144h. This means after the last dragon is dead it will take **at least 4 day**s or a **maximum of 7 days** till all 4 dragons are going to spawn again.

Here is a short example:

05.08.17 - 14:22 = All 4 Emerald Dragons are spawning, location is random.
Duskwood = Taerar (gets killed at the same day)
Ashenvale = Emeriss (gets killed at the same day)
Hinterlands = Ysondre (gets killed at the same day)
Feralas = Lethon (is still alive!)

07.08.17 - 16:15 = Lethon gets killed, all 4 Emerald Dragons are now dead.
Spawn timer is starting now and generates a random number...

Earliest spawn time/date = 11.08.17 - 16:15 (exactly 4 days after the last dragon got killed)
Latest spawn time/date = 14.08.17 - 16:15 (exactly 7 days after the last dragon got killed)

Somewhere between 11.08.17 - 16:15 and 14.08.17 - 16:15 all 4 Emerald Dragons spawn at the same time on a random location.
Duskwood = Lethon
Ashenvale = Taerar
Hinterlands = Emeriss
Feralas = Ysondre

# **SOURCES**
http://goodmorningazeroth.blogspot.com/2008/08/lessons-in-lore-dragons-of-nightmare.html
http://www.millenium.org/forum/showthread.php?4649-Worldboss-Repop
http://www.guildvalhall.eu/inc-news.php?id=8438
http://wow.ingame.de/forum/threads/97817-Worldbosse-spawn
http://wow.ingame.de/forum/threads/114775-alptraumdrachen
http://www.page-moving.info/The_dragon_in_Duskwood.html

**Comment by blubba22** [comment]
Pretty much the same bugs occured on the 1.8 PTR a week back.
The green dragons will be released on wednesday on Darrowshire, so I hope they fixed them and will implement the fixes on Anathema as well.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
