### ISSUE TITLE
UnitHealthMax and UnitHealth functions are not returning correct values.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#1995]
UnitHealthMax is returning 100, which i assume is the percentage of the full HP. It should be the absolute value of the npc's total HP. However, it shows correct value if you target YOURSELF.

UnitHealth is returning percentage of the full HP. It should be the absolute value of the npc's current HP. However, it shows correct value if you target YOURSELF.

Similar functions that work properly: UnitManaMax and UnitMana.

**Comment by thepparker** [comment]
You cannot see the absolute value of enemy units health in Vanilla. Nor can you see friendly unit health unless they are a group member.

**Comment by Cabro** [comment]
Not with the default UI, no.
That's why addons were invented.
http://wowwiki.wikia.com/wiki/API_UnitHealth?oldid=3374 proof it was working as i mentioned back in 2004.

**Comment by martinjlowm** [comment]
This is intended. It's the reason for the development of MobHealth in the early days.

**Comment by Phoosy** [comment]
UnitHealthMax:
>Returns the maximum health of the specified unit. The health is returned in real points only if the unit is in the player's party. Otherwise, a percentage is returned (which will always be 100 in this case). (Note, that the player, the player's pet, and any party member pets are considered to be in the party.)
Source: https://wow.gamepedia.com/index.php?title=API_UnitHealthMax&oldid=26117

UnitHealth:
>Returns the current health of the specified unit. The health is returned in real points only if the unit is in the player's party. Otherwise, a percentage is returned (0-100). (Note, that the player, the player's pet, and any party member pets are considered to be in the party.)
Source: https://wow.gamepedia.com/index.php?title=API_UnitHealth&oldid=60927

**Comment by Cabro** [comment]
I see, I guess this can be closed?
