### ISSUE TITLE
can't summon with the meeting stone

### ISSUE THREAD

**Issue by marksims** [elysium-project/server#1996]
group leader initiates a summoning with the milestone,  
summoning door opens, 
a player right click the door,  nothing happens,  the summoned player never receive a message

**Comment by Manlet** [comment]
They could never summon in vanilla.

They were used as meeting stones.

**Comment by markwendy** [comment]
the meeting stone doesn't work.
right click on the door won't do anything. the player to be pulled in the same group doesn't receive any message.

**Comment by Phoosy** [comment]
Reference: https://github.com/elysium-project/server/issues/207

Close this issue.

**Comment by JosipbrozElysium** [comment]
This is intended, though the current functionality is not blizzlike. Either way, you couldn't summon with Meeting Stones in vanilla, they acted like a random group finder.

Best regards!

**Comment by marksims** [comment]
this is no good, i can do it before

**Comment by Lorilay2** [comment]
No, you couldn't. This is a dumb bug report and you should feel dumb.

**Comment by stesve** [comment]
Was introduced in tbc - patch 2.0.1
http://wowwiki.wikia.com/wiki/Patch_2.0.1
"Meeting Stones now function similar to a Warlock Summon spell."

**Comment by marksims** [comment]
i don't feel dumb as i can do it before on previous build 2 months ago.
also, if it can't summon,  what can you do with it?  you can do nothing!! which is dumb you should feel dumb with a no use meeting stone.

**Comment by stesve** [comment]
> i don't feel dumb as i can do it before on previous build 2 months ago.
 also, if it can't summon, what can you do with it? you can do nothing!! which is dumb you should feel dumb with a no use meeting stone.

That seems really odd, since there has been no changes to Meeting stones.

Since this project is emulating a Vanilla server, there will be no summoning stones. Just like you wouldn't see a deathknight or a panda ingame.
