### ISSUE TITLE
how to stack crit to 100%

### ISSUE THREAD

**Issue by ghost** [elysium-project/server#1998]
+ works on every elysium realm
+ must have talents "increases crit chance with weapons"
+ start a duel with warrior or rogue 
+ in duel rogue or warrrior uses on you "Disarm" - during disarm time you must unequip your weapon ant then equip it back 
+ this way crit stack up to 100% until 

hope it gets fixed soon, stupid warrior abusing in pvp

**Comment by sipertruk** [comment]
#1999 should work
Thanks for reporting this.
