### ISSUE TITLE
Movement Map Generator

### ISSUE THREAD

**Issue by brotalnia** [elysium-project/server#2]
Mmap generator fails to compile on Windows. Ace include directory is not resolved automatically and detour.lib can't be found. After adding the directories manually, it produces the following errors:

```
1>------ Build started: Project: MoveMapGen, Configuration: Release Win32 ------
1>     Creating library C:/Users/Sunny/Desktop/Elysium/elysium.build/contrib/mmap/Release/MoveMapGen.lib and object C:/Users/Sunny/Desktop/Elysium/elysium.build/contrib/mmap/Release/MoveMapGen.exp
1>generator.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall ACE_Main_Base::ACE_Main_Base(void)" (__imp_??0ACE_Main_Base@@QAE@XZ) referenced in function _main
1>generator.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall ACE_Main_Base::~ACE_Main_Base(void)" (__imp_??1ACE_Main_Base@@UAE@XZ) referenced in function "public: virtual __thiscall ACE_Main::~ACE_Main(void)" (??1ACE_Main@@UAE@XZ)
1>generator.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall ACE_Main_Base::run(int,char * * const)" (__imp_?run@ACE_Main_Base@@QAEHHQAPAD@Z) referenced in function _main
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall ACE_RW_Mutex::ACE_RW_Mutex(int,char const *,void *)" (__imp_??0ACE_RW_Mutex@@QAE@HPBDPAX@Z) referenced in function "public: __thiscall VMAP::VMapManager2::VMapManager2(void)" (??0VMapManager2@VMAP@@QAE@XZ)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall ACE_RW_Mutex::~ACE_RW_Mutex(void)" (__imp_??1ACE_RW_Mutex@@QAE@XZ) referenced in function "public: virtual __thiscall VMAP::VMapManager2::~VMapManager2(void)" (??1VMapManager2@VMAP@@UAE@XZ)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall ACE_RW_Mutex::acquire_read(void)" (__imp_?acquire_read@ACE_RW_Mutex@@QAEHXZ) referenced in function "public: class VMAP::WorldModel * __thiscall VMAP::VMapManager2::acquireModelInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?acquireModelInstance@VMapManager2@VMAP@@QAEPAVWorldModel@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall ACE_RW_Mutex::acquire_write(void)" (__imp_?acquire_write@ACE_RW_Mutex@@QAEHXZ) referenced in function "public: class VMAP::WorldModel * __thiscall VMAP::VMapManager2::acquireModelInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?acquireModelInstance@VMapManager2@VMAP@@QAEPAVWorldModel@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall ACE_RW_Mutex::release(void)" (__imp_?release@ACE_RW_Mutex@@QAEHXZ) referenced in function "public: class VMAP::WorldModel * __thiscall VMAP::VMapManager2::acquireModelInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?acquireModelInstance@VMapManager2@VMAP@@QAEPAVWorldModel@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall ACE_Thread_Mutex::ACE_Thread_Mutex(char const *,struct ACE_mutexattr_t *)" (__imp_??0ACE_Thread_Mutex@@QAE@PBDPAUACE_mutexattr_t@@@Z) referenced in function "public: __thiscall std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class VMAP::ManagedModel>::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class VMAP::ManagedModel><class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class VMAP::ManagedModel,void,0>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class VMAP::ManagedModel &&)" (??$?0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@X$0A@@?$pair@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@@std@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@$$QAVManagedModel@VMAP@@@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall ACE_Thread_Mutex::~ACE_Thread_Mutex(void)" (__imp_??1ACE_Thread_Mutex@@QAE@XZ) referenced in function __unwindfunclet$??$?0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@X$0A@@?$pair@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@@std@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@$$QAVManagedModel@VMAP@@@Z$42
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall ACE_Thread_Mutex::acquire(void)" (__imp_?acquire@ACE_Thread_Mutex@@QAEHXZ) referenced in function "public: __thiscall std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class VMAP::ManagedModel>::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class VMAP::ManagedModel><class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class VMAP::ManagedModel,void,0>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class VMAP::ManagedModel &&)" (??$?0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@X$0A@@?$pair@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@@std@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@$$QAVManagedModel@VMAP@@@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall ACE_Thread_Mutex::release(void)" (__imp_?release@ACE_Thread_Mutex@@QAEHXZ) referenced in function "public: __thiscall std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class VMAP::ManagedModel>::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class VMAP::ManagedModel><class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class VMAP::ManagedModel,void,0>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class VMAP::ManagedModel &&)" (??$?0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@X$0A@@?$pair@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VManagedModel@VMAP@@@std@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@$$QAVManagedModel@VMAP@@@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall ACE_Stack_Trace::ACE_Stack_Trace(int,unsigned int)" (__imp_??0ACE_Stack_Trace@@QAE@HI@Z) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __thiscall ACE_Stack_Trace::c_str(void)const " (__imp_?c_str@ACE_Stack_Trace@@QBEPBDXZ) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: void __cdecl Log::outInfo(char const *,...)" (?outInfo@Log@@QAAXPBDZZ) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static class Log & __cdecl MaNGOS::Singleton<class Log,class MaNGOS::SingleThreaded<class Log>,class MaNGOS::OperatorNew<class Log>,class MaNGOS::ObjectLifeTime<class Log> >::Instance(void)" (?Instance@?$Singleton@VLog@@V?$SingleThreaded@VLog@@@MaNGOS@@V?$OperatorNew@VLog@@@3@V?$ObjectLifeTime@VLog@@@3@@MaNGOS@@SAAAVLog@@XZ) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static char const * __cdecl ObjectGuid::GetTypeName(enum HighGuid)" (?GetTypeName@ObjectGuid@@SAPBDW4HighGuid@@@Z) referenced in function "public: char const * __thiscall ObjectGuid::GetTypeName(void)const " (?GetTypeName@ObjectGuid@@QBEPBDXZ)
1>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static class World & __cdecl MaNGOS::Singleton<class World,class MaNGOS::SingleThreaded<class World>,class MaNGOS::OperatorNew<class World>,class MaNGOS::ObjectLifeTime<class World> >::Instance(void)" (?Instance@?$Singleton@VWorld@@V?$SingleThreaded@VWorld@@@MaNGOS@@V?$OperatorNew@VWorld@@@3@V?$ObjectLifeTime@VWorld@@@3@@MaNGOS@@SAAAVWorld@@XZ) referenced in function "public: void __thiscall VMAP::VMapManager2::releaseModelInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?releaseModelInstance@VMapManager2@VMAP@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>C:\Users\Sunny\Desktop\Elysium\elysium.core\bin\Release\MoveMapGen.exe : fatal error LNK1120: 18 unresolved externals
```

**Comment by jzcxw** [comment]
Confirm same issue.

**Comment by basedxx** [comment]
I got it working on linux and had to link with pthread and ACE libraries to fix those unresolved symbols.

I uploaded my mmaps to give you a head start until fixes are pushed.
https://mega.nz/#!7olQVDBL!se5gWOkov5gqPKnkEv_8MvkAH5FvOTYSIG0I42CiMp8

**Comment by Locario** [comment]
Hi, tnx for sharing mmaps, i'm using this core "https://github.com/EinBaum/server" in a Debian vm

When i run mangosd i obtain this errors (a lot):

`MMAP:loadMap: Could not open mmtile file './mmaps/0015539.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015639.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015739.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015839.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015939.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016039.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016139.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016239.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016339.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010040.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010140.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010240.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010340.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010440.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010540.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010640.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010740.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010840.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010940.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011040.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011140.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011240.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011340.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015640.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015740.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015840.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015940.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016040.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016140.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016240.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016340.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010041.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010141.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010241.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010341.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010441.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010541.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010641.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010741.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010841.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010941.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011041.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011141.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011241.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011341.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011441.mmtile'
Terminado (killed)
`

That files don't exist, (almost 2 last ones), then core crash

**Comment by fatalmatt** [comment]
Those mmaps cause an error for people that have compiled with windows. Has anyone got the mmaps extractor compiled for windows yet?

**Comment by brotalnia** [comment]
I compiled the latest version of the Giperion branch and MoveMapGen.exe no longer crashes.
[Elysium Extractors 18 March.zip](https://github.com/elysium-project/server/files/852498/Elysium.Extractors.18.March.zip)

**Comment by Locario** [comment]
how options must be used to use 4 cores extracting mmaps correctly?

Thanks all

**Comment by wowmui** [comment]
@Locario You can use 
movemapgen 0
movemapgen 1
movemapgen 030
movemapgen XXX
and more

**Comment by jzcxw** [comment]
@brotalnia It works in extracting however it the core still thinks too much is missing and will crash..
`MMAP:loadMap: Could not open mmtile file './mmaps/0010634.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010734.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010834.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010934.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011034.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011134.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011234.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011334.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011434.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015034.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015134.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015234.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015334.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015434.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015534.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015634.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015734.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015834.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015934.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016034.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016134.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016234.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016334.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010035.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010135.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010235.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010335.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010435.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010535.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010635.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010735.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010835.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010935.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011035.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011135.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011235.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011335.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011435.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015235.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015335.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015435.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015535.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015635.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015735.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015835.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015935.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016035.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016135.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016235.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016335.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010036.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010136.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010236.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010336.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010436.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010536.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010636.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010736.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010836.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010936.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011036.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011136.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011236.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011336.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0011436.mmtile'`

**Comment by Locario** [comment]
Same

**Comment by fatalmatt** [comment]
How long did it take you to extract the mmaps?

**Comment by Locario** [comment]
1 core more 15 hours loool

**Comment by fatalmatt** [comment]
@brotalnia Are the mmap / vmap files getting output from the extractors you compiled working for you..?

**Comment by brotalnia** [comment]
I haven't had time to try with the newest version, but vmaps worked fine before, and so did mmaps if i skipped continents. On map 0 mobs were walking in the air if they were near any buildings, and map 1 crashed the server.

**Comment by brotalnia** [comment]
Mmaps from Giperion branch seem to work fine if the core is compiled in x64.
