### ISSUE TITLE
i never see any wreckage pool for fishing 

### ISSUE THREAD

**Issue by monotemario** [elysium-project/server#2005]
Elysium Patch 1.12.1

I am following a guide for fishing but i never  see a wreckage pool in any of the places for that  reason i am thinking there non in the server.

i hope this will be fix

the guie page is :  https://legacy-wow.com/fishing-guide-pools-and-wreckage/

**Comment by Phoosy** [comment]
Elysium is not on patch 1.12.1 for progression, but on 1.6. Pools are not introduced until the Zul'gurub patch.

**Comment by JosipbrozElysium** [comment]
What Phoosy said. Closing.

Best regards!

**Comment by kampeador** [comment]
Itemization/progression should be handled independently from the core.
I have latest core+DB and never saw any of them. This issue is "global".
