### ISSUE TITLE
Darkmoon faire quest

### ISSUE THREAD

**Issue by islofdesp** [elysium-project/server#2009]
Hello.
Npc called  Yebb Neblegear should have 6 quests for Darkmoon Faire Prize Ticket, the one he misses is Glowing Scorpid Blood and More Glowing Scorpid Blood, pls add it.

**Comment by Spiritoflife07** [comment]
This is true. Also, to add to this, the quest "Vibrant Plumes" should be **available up until reaching 2500 reputation** into neutral according to this Allakhazam archive

https://web.archive.org/web/20080308122748/http://wow.allakhazam.com:80/db/quest.html?wquest=7902

However, it stops short at 2100 currently. 

The Allakhazam archive dates August 5th 2005 which is one month after the initial release of the Darkmoon Faire which was in patch 1.6 July 12th 2005 according to 

http://wowwiki.wikia.com/wiki/Darkmoon_Faire_(old)

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
