### ISSUE TITLE
Warrior's Charge ability

### ISSUE THREAD

**Issue by Heyhohohoho** [elysium-project/server#2011]
I have noticed a pet peeve bug while leveling that is occasionally recurring.

Some mobs (in dungeons) will disable Charge if another person pulls.

Now, I'm not talking about the mechanic where if you get within a certain distance of an elite instance mob, you will be placed in combat, that is intentional. I'm talking about some specific mobs will place you in combat from whatever range you are at, no matter where you are or whether you are out of line of sight.

Here is a list of the mobs i've encountered so far that do this-
Earthen Sculptor http://db.vanillagaming.org/?npc=7012 (the mobs that this specific one are grouped up with _possibly_ do this but I know for sure this one does, the similar ones of higher level later in the instance do not)

Sandfury Shadowhunter http://db.vanillagaming.org/?npc=7246

I will update this list whenever I notice it happening with different mobs.

**Comment by gemt** [comment]
There are some mobs who are scripted, have an EventAI entry or a creature_template flag to put themselves in combat with players in the entire instance on aggro like raidbosses generally do. Could be whoever scripted/added AI to these creatures did this intentionally, or its simply an oversight. Should try to figure out if perhaps these mobs should in fact put everyone in combat or not, might be correct, might not be.

**Comment by thepparker** [comment]
More information is required about the specific mobs
