### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by lostdream4** [elysium-project/server#2013]
I did TAQ open the task line, [60] Knapp Tullo J's anger, killed BOSS, did not drop mission supplies, below is the screenshot of that time, request repair.

**Comment by sickheals** [comment]
Can you post the screenshot? Make the title more descriptive.

**Comment by JosipbrozElysium** [comment]
Please rewrite the report according to this: https://github.com/elysium-project/server/blob/development/docs/CONTRIBUTING.md

Otherwise, the issue will be closed, as it doesn't help us.

Best regards!
