### ISSUE TITLE
Hunter Talents not Working: Pathfinding and Improved Hunter's Mark

### ISSUE THREAD

**Issue by MoneyTBE** [elysium-project/server#2020]
Dear Elysium,

Hunter's Talents Pathfinding and Improved Hunter's Mark do not work.

I have done several tests and have attempted training further points into them without any results.

For reference my character in the Elysium pvp server is Cazh (dwarf hunter currently level 38 when I write this).

I would really appreciate your confirmation, fix and/or input.

Thank you for this great server.

Best regards.

**Comment by Phoosy** [comment]
How about providing some numbers from your testing? What did you do to replicate this "issue"? Before and after numbers? Anything of actual substance??

**Comment by MoneyTBE** [comment]
Thanks for following up Phoosy.

Basically trained Pathfinding Level 2 and turned aspect of Cheetah on ... UI continues to show 30% Increased Speed. Furthermore asked a random hunter with Aspect of Cheetah on but no Pathfinding, raced him/her and we had the exact same speed. I do not have Screenshots of this because I decided to fully respect.

However, in about 2 hours I can submit a screenshot showing that I have Improved Hunter's Mark at Level 2 yet UI clearly shows the same Attack Power added from my Hunter's Mark talent (currently 45).

Please let me know what you think.

Thanks.

**Comment by MoneyTBE** [comment]
Oh man given the constant levelling and weapon changes I'm going through now I guess I'll just wait till 60 for the tests then. I'll ask around other hunters in the meantime to see if anyone else has actually done testing and let you know.I'm really hoping it's just a UI problem to just forget about it.

Anyways thanks very much for the support and keep up the great work.

Cheers.

**Comment by Xyter** [comment]
It is true that tooltips don't change when talents affect them. But I agree that Pathfinding isn't working because with 2/2 Pathfinding and cheetah on I run the exact same speed as a druid in cat form with their 30% talent increase.
