### ISSUE TITLE
Mighty Rage Potion doesn't stack with Juju Power

### ISSUE THREAD

**Issue by ohganot** [elysium-project/server#2024]
http://imgur.com/nblTaPQ My warrior with no buffs, 246 strength

http://imgur.com/l9BIYhN My warrior with Juju Power, 276 strength

http://imgur.com/Ab6bwGO My warrior with Mighty Rage Potion + Juju Power, 306 strength

Mighty Rage Potion and Juju Power should stack, since Juju Power is a elixir type buff (like Elixir of Giants) and Mighty Rage Potion is a battle potion.

Mighty Rage Potion should give the full 60 strength even with Juju Power active.

This issue is also related to #1296 (Diamond Flask and Juju Power not stacking) which is already confirmed, Mighty Rage Potion should behave the same way as Diamond Flask, since they are cooldowns.

**Comment by AndreRieu1949** [comment]
does Elixir of Giants stack with Mighty Rage Potion?

**Comment by blubba22** [comment]
Nope, Elixir of Giants and Mighty Rage Potion also don't stack:

http://imgur.com/a/7ekGH

**Comment by ohganot** [comment]
I might have found the issue in code, but im not 100% sure.

https://github.com/elysium-project/server/blob/6c502897340691455b7b560b035ad42c4ebe9508/src/game/Spells/SpellAuras.cpp

Starting from line 6801, theres tons of exclusive buffs listed. Juju Might and Earthstrike are listed there while Diamond Flask, Juju Power, Mighty Rage Potion aren't listed there.

I don't know the code well enough to know if this is relevant, but someone who understands it, please check it out and try to write a fix.
