### ISSUE TITLE
Feline Grace missing?

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#2026]
No reduced fall damage in cat form, making smolderweb druid solo impossible since you'll take fall damage (which you shouldn't) on the jump to the lower parts of LBRS, breaking stealth and drawing the mobs to you.

Looking in the spell book of a druid character doesn't show it either.. I can't remember what it was called, feline grace or something (yeah it was; http://wowwiki.wikia.com/wiki/Feline_Grace?oldid=94545)

**Comment by stesve** [comment]
My druid has feline grace. Did you forget to learn it at your class trainer?

**Comment by Phatcat** [comment]
> My druid has feline grace. Did you forget to learn it at your class trainer?

Yes.... Yes I did... that's embarrassing x'D
