### ISSUE TITLE
Lower level Warsong Gulch items not in game

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#2029]
Some rings, a necklace and a cape are not in game from the WSG reputation vendors. They are not queryable by the server. These are the level 10-19 items.

The IDs are:

20439
20442
20427
20426
20429

They need to be implemented since Elysium's on Patch 1.6.

**Comment by thepparker** [comment]
Added in 1.8

**Comment by Sabre142** [comment]
If you delay it to 1.8 then you might as well prevent sub 20s from doing warsong gulch.

>Players of levels 10 - 19 will now be able to participate in the battle for Warsong Gulch.

http://wowwiki.wikia.com/wiki/Patch_1.8.0
