### ISSUE TITLE
the problem with cooking

### ISSUE THREAD

**Issue by melris** [elysium-project/server#2034]
Hello. I had a problem with cooking http://db.vanillagaming.org/?item=21099 ,When cooking, I get a system message "this spell is not available to you".I play the realm Elysium character named melris . But on the realm anathema everything works fine, on the same client ,Therefore, I conclude that it is a mistake and I attach a screenshot with a cooking error
![error](https://user-images.githubusercontent.com/30897780/29188327-e3855e80-7e23-11e7-9796-89323ab4ad02.png)

**Comment by Phoosy** [comment]
Sagefish recipe is released in a later patch, Elysium is on a different patch level than Anathema. This is not an issue, but an itemization restriction purposefully made.

**Comment by melris** [comment]
thanks
