### ISSUE TITLE
Dropped Quests?

### ISSUE THREAD

**Issue by Lexarria** [elysium-project/server#2035]
Around 8-9am ST this morning on Darroswhire I picked up a quest on my warlock (the first part of reliquary of purity that sends you to Southwind Village) and I also picked up the initial lvl 50 class quest on my druid that sends you to talk to Torwa Pathfinder in Un'Goro. When I logged back on at around 2-3pm ST both quests were dropped from their respective logs. While my warlock seemed to have been advanced to the next part of that chain (that sends you to DM east for the felvine shard), my druid was unable to get quests from the initial questgiver or Torwa regarding that chain.

**Comment by Kolmarwow** [comment]
That's because Darrowshire was accidentally updated to 1.10 instead of 1.8, and was hotfixed back to 1.8. I'm not sure about the reliquary of purity thing, but the level 50 druid class quest isn't supposed to be in-game until patch 1.10.
