### ISSUE TITLE
Redridge Bashers in Redridge Canyon Doubles

### ISSUE THREAD

**Issue by Kuuppax** [elysium-project/server#204]
![image](https://cloud.githubusercontent.com/assets/26604605/24476981/0a327306-14de-11e7-8824-7b939c8bffd1.png)

**Comment by Kuuppax** [comment]
![image](https://cloud.githubusercontent.com/assets/26604605/24477073/516ae29e-14de-11e7-98c8-4276748d33c1.png)

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
