### ISSUE TITLE
Shadowmeld (Night elfs race ability) not usable in combat

### ISSUE THREAD

**Issue by NoSssssweat** [elysium-project/server#2041]
Shadowmeld isnt usable while in combat, it should be though.

**Comment by Sabre142** [comment]
Not a bug

http://wowwiki.wikia.com/wiki/Shadowmeld#Patch_changes

>Patch 3.0.2 (14-Oct-2008): Cooldown increased to 2 minutes, able to use in combat.

**Comment by NoSssssweat** [comment]
wow im sorry, must be just too long ago!
