### ISSUE TITLE
Scrying Goggles? No Problem! Possibly bugged?

### ISSUE THREAD

**Issue by Woosty** [elysium-project/server#2042]
A guildy and myself are on this leg of the scepter quest line. We have both cleared MC 4+ times and neither of us have had it drop. I know it is a low drop rate but everyone I have talked to has not seen it drop recently for anyone on this part of the quest line.

Server: Anathema

**Comment by Woosty** [comment]
A guildy and myself are on this leg of the scepter quest line. We have both cleared MC 4+ times and neither of us have had it drop. I know it is a low drop rate but everyone I have talked to has not seen it drop recently for anyone on this part of the quest line.

**Comment by Woosty** [comment]
Done

**Comment by Woosty** [comment]
Bump. Am running an MC on saturday in a group separate from my other guildy to see if that changes anything.

**Comment by GuybrushGit** [comment]
Drop chance is at 0.6%, which is probably too low.

**Comment by Woosty** [comment]
I got them finally last night in our guilds MC. A buddy also said a member of his MC group got it last night as well. Either crazy coincidence or maybe something was changed. Either way, I have finally finished the scepter questline!
