### ISSUE TITLE
My account is stuck in the Naxxramas (GM only) realm.

### ISSUE THREAD

**Issue by ATullo** [elysium-project/server#2048]
So yeah, as the title says. My account is currently stuck in the Naxxramas (gm only) realm with no way to get out of it so far it seems. Every time I try to log in it instantly disconnects me when I connect to the realm.

How do I fix this issue when I cannot change servers because I am not logged in to my account?

**Comment by Sabre142** [comment]
Go into WTF Folder

Click config.wtf

Control F 'Naxxramas' or what the GM server name is

Replace with 'Elysium'

Save

**Comment by thepparker** [comment]
Not related to server development. Post in the forums if you need further assistance.
