### ISSUE TITLE
Sweeping Strikes and Cleave

### ISSUE THREAD

**Issue by nikolay510** [elysium-project/server#2049]
Cleave should generate 1 more additional attack according to https://hilbert.wordpress.com/sweeping-strikes-guide/ and http://wow.allakhazam.com/forum.html?forum=243&mid=1184266570151899596#5

> • Cleave – two attacks, good damage.

**Comment by vindruvor** [comment]
Adding to that, for the sake of Whirlwind:

"The same functionality works with Whirlwind. _HOWEVER_, each hit that is generated from SS consumes a charge; so if you hit Sweeping Strikes and then Whirlwind with four mobs in range, they will get hit eight times (four from Whirlwind, four from Sweeping Strikes) and it will consume four Sweeping Strikes charges."

Source: http://wow.allakhazam.com/forum.html?forum=243&mid=1184266570151899596#5

(The same allakhazam post you linked)

**Comment by sickheals** [comment]
Can you post screen shots or a video of the problem, please?

**Comment by thepparker** [comment]
> Whirlwind - When this ability is used with Sweeping Strikes, it will burn only one charge of Sweeping Strikes and will generate only one additional attack. 

The same can be assumed for Cleave

http://vanilla-wow.wikia.com/wiki/Patch_1.10.0

**Comment by nikolay510** [comment]
> The same can be assumed for Cleave

So you're implying that Cleave is the same as Whirlwind? Isnt it sounds silly? There's nothing related to Cleave in the patchnotes you provided. 

And even if I provided video/screenshots from 2005 (I really tried, but noone used cleave in PvP videos for the same reason as Heroic Strike) you'd say something like 'Its not 1.10 patch, even if 1.10 doesnt countain anything Cleave related'. Do you hate warriors or something? Even in Sweeping Strikes guide I provided there's a section regarding 1.11 fixes for skill and you still think that Cleave shouldnt generate 1 more attack?

That's just stupid.
