### ISSUE TITLE
An issue after new server patch installation

### ISSUE THREAD

**Issue by Dreamcatcher89** [elysium-project/server#2051]
Yesterday I have bought a ring [Don Rodrigo's Band] for 67 gold.
After server repatch it disappeared from the invetory and it is not availible at the vendor.
Is it possible to get a refund?

Thanks in advance.

**Comment by thepparker** [comment]
No refunds are being given for furure-patch related removed items as far as I'm aware. You can make a ticket in-game and clarify.
