### ISSUE TITLE
Quest [60+] The Active Agent only offers one reward once completed

### ISSUE THREAD

**Issue by yobanchi** [elysium-project/server#2056]
Hello, I just completed the Strat UD quest The Active Agent, but instead of being able to choose from two rewards I only get one choice, the attack power item which I don't need, as you can see on screenshot.

(There should be a second choice called Rune of the dawn, the caster equivalent)
![bgs](https://user-images.githubusercontent.com/29761116/29235398-a37b6b78-7efe-11e7-94a2-ce1dba79387c.jpg)

**Comment by Sabre142** [comment]
Patch 1.7.0 (13-Sep-2005): Added.
http://wowwiki.wikia.com/wiki/Rune_of_the_Dawn

**Comment by yobanchi** [comment]
oops sorry so i can just complete quest and get new rune later when it gets patched right?

Also should I delete this post or something ty

**Comment by Sabre142** [comment]
You might not be able to so I would save it. There should be an option to change your trinket if you lose it later so but from my server it doesn't appear to be working. I will report that.

**Comment by brotalnia** [comment]
The option to change your trinket is working, it was fixed recently. You will be able to get your Rune of the Dawn from the NPC once the server is at the appropriate content patch.

**Comment by Sabre142** [comment]
That's good to know, @yobanchi you can close this.
