### ISSUE TITLE
No option to recover Seal of the Dawn/Rune of the Dawn

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#2057]
There's doesn't seem to be an option to recover your Seal if lost after completing The Active Agent quest. You also should be able to trade your Seal of the Dawn for a Rune of the Dawn, the latter which is added in 1.7. The quest text says that you can recover it later if you delete it.

![29235398-a37b6b78-7efe-11e7-94a2-ce1dba79387c 1](https://user-images.githubusercontent.com/26516348/29236897-279e0166-7f56-11e7-84d2-7d2f8a38fc2a.jpg)

> Players seeking to replace their Seal of the Dawn (or get a Rune of the Dawn instead) once they've finished "The Active Agent" quest should speak with Betina Bigglezink in Eastern Plaguelands.

http://wowwiki.wikia.com/wiki/Patch_1.7.0

**Comment by brotalnia** [comment]
Already fixed in https://github.com/elysium-project/server/commit/25dfd9d85f8f37d727e958db3d8debda9799477b
