### ISSUE TITLE
ghost saber - cat figurine

### ISSUE THREAD

**Issue by ezmonyezlife** [elysium-project/server#2060]
Hello, there is supposed to be a container/chest called Cat Figurine that spawns at the Ruins of Mathystra in Darkshore. This container has a chance to spawn the Ghost Saber mob.

These Cat Figurine containers are nowhere to be seen.

Hope I did this right!

Cat Figurine: http://db.vanillagaming.org/?object=13359
Cat Figurine lootable item: http://db.vanillagaming.org/?item=5329
Ghost Saber: http://db.vanillagaming.org/?npc=3619#wh-comments

**Comment by Sabre142** [comment]
They might have a long respawn timer, are you looking in the right places?

![capture](https://user-images.githubusercontent.com/26516348/29238888-ace7b06c-7f81-11e7-9de6-717fc0b4799a.PNG)

**Comment by ezmonyezlife** [comment]
I have repeatedly checked all the locations in these 2 videos 

https://www.youtube.com/watch?v=5BbeqvMdvtc

https://www.youtube.com/watch?v=UPVyOU2zaRQ

**Comment by brotalnia** [comment]
All the cat figurines are spawned correctly in the 1.12 database.
![cat figurines2](https://user-images.githubusercontent.com/6519171/29254629-07774e8c-80a1-11e7-8694-0f9852a8a227.jpg)

![cat figurine](https://user-images.githubusercontent.com/6519171/29254631-0d28b820-80a1-11e7-8f2a-78f14d25680d.jpg)

**Comment by ezmonyezlife** [comment]
Thank you very much for your confirmation. 

If I am reading your table correctly does it say they are on a 5 minute respawn timer?
Can they all be spawned at once independently of one another?

**Comment by brotalnia** [comment]
I think so.

**Comment by DanishDragon** [comment]
Even if they are spawning - something must be off with the respawn time. Been looking for an hour plus with multiple people, and we've found none

**Comment by gearselysium** [comment]
Can confirm figurines do not spawn or are not visible on Elysium, I spent half an hour went the zone was deserted searching. Do they share spawn nodes with the idols?

**Comment by ezmonyezlife** [comment]
What is the respawn timer? 
300 sec seems incorrect

**Comment by Jaderoamer** [comment]
I have spent the past 3 days, patrolling the ruins and checking known spawn points. I can confirm that the figurines have not been spawining.

**Comment by GuybrushGit** [comment]
This could be related to the respawn issue with herbs / crystals fixed today. Check if you can find them now.

**Comment by Meridaw** [comment]
works fine now
