### ISSUE TITLE
Horde onyxia chain and 'Rokaro'

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#2062]
I'm pretty sure this is still a thing, all the horde onyxia quest texts send you to 'Rokaro' despite that person not existing, instead ending at Rexxar. Rokaro is a TBC replacement for Rexxar. I propose that the quest texts in these quests be edited to remove all traces of Rokaro and replace them with Rexxar:

http://db.vanillagaming.org/?quest=6567
http://db.vanillagaming.org/?quest=6568
http://db.vanillagaming.org/?quest=6601
http://db.vanillagaming.org/?quest=6602

Edit: It appears that the first quest has text specifically catered towards this Rokaro character, mentioning that Rexxar is in Outlands. I will try to search for an original vanilla source that shows the quest text.

Here is the original Pre-TBC text: http://web.archive.org/web/20060415091139/http://wow.allakhazam.com:80/db/quest.html?wquest=6567

**Comment by martinjlowm** [comment]
It's already fixed with #1847. However, I don't think it's live yet. If it is, it requires you to clear your WDB directory since quest information is cached.

**Comment by Sabre142** [comment]
Ty
