### ISSUE TITLE
[Darrowshire] Missing quests for delivery AV/WSG marks

### ISSUE THREAD

**Issue by Hiddenpooll** [elysium-project/server#2063]
I have a problem with quests for the delivery of the [Warsong Gulch Mark of Honor] (quest=8399), and the [Alterac Valley Mark of Honor] (quest=8375), Alliance Brigadier General does not give any quest.

Screenshots are attached:
https://ibb.co/gvfi25

**Comment by Ripper007** [comment]
Same on Darrowshire - horde side, can;t deliver on one character marks to the Warsong and Arathi Basin and can't access any quest for the respective factions ( Warsong Outriders and Forsaken Defilers).
