### ISSUE TITLE
Gnomish Cloaking Device bugs

### ISSUE THREAD

**Issue by llacczy** [elysium-project/server#2065]
If we can trust this source of this old allakhazam comment the correct interactions of this trinket are the following:

http://wayback.archive.org/web/20050913024444/http://wow.allakhazam.com:80/item.html?witem=4397

> „… it cannot be used in combat, and cannot be stacked with jetboots or other trinkets to run faster. it can probabaly stack with cat form, sprint, pack, or any spell to run faster, but not trinkets. but you CANNOT use this in battle to drop aggro, and you CANNOT stack this with jet boots or stopwatch to run fast when invis, they will put 5min reuse on each other …”

**Current, bugged interactions:**

Gnomish Cloaking Device, Nifty Stopwatch, Gnomish Rocket does not cause 5 min cooldown on each other (i assume this would be the correct case from the description above) and they do stack with each other.
Gnomish Cloaking Device can be used in combat, but the mob „ignore” the invisibility effect, causing the trinket will be on cooldown, with the buff on the player, but without the desired effect. I assume the server should not let the trinket to be used in combat and instead send an error message to the player.

**An another issue** that would be worth looking into that the trinket does not interrupt enemy casting.
Now i do not have proof of this, but it might be obvious, since the caster loses (or should lose) the target when the user of the trinket gains invisibility.
( I understand that this might not be/ probably not a valid proof at this point, just wanted to mention if somebody could progress on this more )

**Comment by GuybrushGit** [comment]
>Gnomish Cloaking Device can be used in combat, but the mob „ignore” the invisibility effect, causing the trinket will be on cooldown  
This is the correct behaviour, it can be used in combat and mobs should keep attacking you.

https://web.archive.org/web/20070408173451/http://www.thottbot.com:80/i4397
https://www.youtube.com/watch?v=c4bgggKMvQU&feature=youtu.be&t=1m3s
https://www.youtube.com/watch?v=gJjZn5qxlNY&feature=youtu.be&t=20m43s
