### ISSUE TITLE
Cant find my hunter pet skills in spellbook

### ISSUE THREAD

**Issue by osteriossi** [elysium-project/server#2066]
Hey, I cant find my hunter's pet skills in my spellbook.. Its hard to play hunter when i cant use my pet skills like growl. can u repair problem? 
Greetings Osteriossi95

**Comment by hudy47** [comment]
I have the same problem. There is no pet skills tab in the spellbook. I tried to change a pet but it didn't solve the problem.
Greetings
Kaysoe

**Comment by Spionida** [comment]
Look on the General tab, not intuitive I know. This is learned from a quest that follows on from the learning to train pets quest series.

**Comment by ELouisYoung** [comment]
You have to finish the class quest that grants you the pet training ability.

**Comment by hudy47** [comment]
Thanks for help, there was Beast Training skill in general tab. Pet didn't know any skills so there wasn't any pet skills tab and I thought it was some kind of bug.
