### ISSUE TITLE
Alterac Valley Marks of Honor

### ISSUE THREAD

**Issue by oksorlie** [elysium-project/server#2069]
I am unable to turn in Alterac Valley Marks of Honor at the Alliance Brigadier General in any of the capital cities. This means that the badges are simply going to waste in my mailbox. Others in my guild have reported that they can turn in their marks with the quest "Remember Alterac Valley!", however this quest is not available to me. I have tried to reinstall my client and delete the WDB folder, but to no avail.

**Comment by Kolmarwow** [comment]
Having the same problem on Darrowshire. It seems like the first part of the battleground mark quests have been accidentally disabled, while the repeatables are still there. So your guildies probably completed the first part before it became bugged.

**Comment by thepparker** [comment]
Should be fixed
