### ISSUE TITLE
Meeting stone group finder functionality missing

### ISSUE THREAD

**Issue by llacczy** [elysium-project/server#207]
Bugreport on the bugtracker:
https://elysium-project.org/bugtracker/issue/1794

This function could be a nice addition to the servers.
If it was working on old elysium maybe with a little investment it could be imported to the current servers.
(hopefully)

**Comment by PlaskED** [comment]
Wrong expansion.

**Comment by StadenElysium** [comment]
This is unlikely to ever be added due to time constraints.

**Comment by brotalnia** [comment]
So much for optimism.
