### ISSUE TITLE
Murloc Scale Belt 

### ISSUE THREAD

**Issue by gomesc06** [elysium-project/server#2070]
The character screen is not reflecting the proper item values provided by the Murloc Scale Belt. When equipped the character's stats will only improve from the specified armor value. The stats to Strength and Agility are not reflected within the character screen.

![no belt](https://user-images.githubusercontent.com/18508822/29243562-8a85bf44-7f56-11e7-9b95-d567837e167a.PNG)

![belt](https://user-images.githubusercontent.com/18508822/29243564-909ba628-7f56-11e7-9b3d-1d7806fa97a0.png)

**Comment by gomesc06** [comment]
this is on the Elysium Server

**Comment by llacczy** [comment]
can you delete your wdb and check again please? if you have anathema itemisation cache or from other server you might see different item stats

**Comment by gomesc06** [comment]
yep that was the issue. Thank you, I will close this now.
