### ISSUE TITLE
[Anathema 1.10] Missing 3 items on loot tables

### ISSUE THREAD

**Issue by taurenrogue** [elysium-project/server#2071]
Server: Anathema, patch 1.10

Description: 2 totems and a libram are missing from boss loot tables according to realmplayers data...
http://db.vanillagaming.org/?item=22395  -  Totem of Rage
http://db.vanillagaming.org/?item=22396  -  Totem of Life
http://db.vanillagaming.org/?item=22400  -  Libram of Truth

Source: Item ID-s for 1.11 loot start at 22999, and these are clearly < 22999 so they should be added in patch 1.10

If it is needed i can add more sources, but think the item ID numbers are well accepted way of figuring which patch an item belongs to.

**Comment by SiguDS** [comment]
https://github.com/elysium-project/server/issues/1509 for people if they want more info regarding earlier discussions about adding of these .
