### ISSUE TITLE
Unguro Power crystals

### ISSUE THREAD

**Issue by Anhan873** [elysium-project/server#2073]
Hello, i think the spawn in Unguro power crystals are bugged, i have only found 1, in the 3 days i have been questing there now :)

**Comment by Anhan873** [comment]
and the same with ' It's a sceret to everybody, i cant loot the backpack i get :)

**Comment by luigimannoni** [comment]
Already known issue, duplicate of #1750 #1663 #1936 #1638 #1831 and god knows how many other same issues are open.
