### ISSUE TITLE
Brilliant Wizard Oil and Brilliant Mana Oil not usable

### ISSUE THREAD

**Issue by Lucilla-Korakion** [elysium-project/server#2077]
BUGGED BEHAVIOUR:
On Darrowshire server upon attempt of applying those on weapons you get message "Spell is not available to you"

CORRECT BEHAVIOUR:
Oils should be applied giving respective bonuses: Brilliant Wizard Oil: While applied to target weapon it increases spell damage by up to 36 and increases Spell Critical chance by 1% . Lasts for 30 minutes. Brilliant Mana Oil: While applied to target weapon it restores 12 mana to the caster every 5 seconds and increases the effect of healing spells by up to 25. Lasts for 30 minutes.

SOURCES:
Both were were added in patches 1.7 (ZG patch). Darrowshire is supposed to be on patch 1.8 (Dragons of Nightmare)

http://wowwiki.wikia.com/wiki/Brilliant_Wizard_Oil
http://wowwiki.wikia.com/wiki/Brilliant_Mana_Oil

**Comment by Haiwuu** [comment]
http://wowwiki.wikia.com/wiki/Patch_1.9.0

> Enchanters can now turn some of their dusts and shards into magical oils. These oils when applied to weapons add a temporary bonus to magical damage or mana regeneration that stacks with permanent enchantments. The lower levels of these recipes are found on normal enchanting vendors. The higher level versions are found on special vendors and are rewards for high Zandalar faction. 
> 

1.9.0
