### ISSUE TITLE
[Darrowshire] Is hit chance on Razorsteel Shoulders working ?

### ISSUE THREAD

**Issue by j0ker2** [elysium-project/server#2083]
Hellow, 

I've checked different profiles on Legacy Logs and the hit chance seems to show the right amount, except on my warrior which is missing 1% hit chance (he's wearing Razorsteel Shoulders from 1.8 patch).

Can you confirm there is a bug with this item please ?

http://db.vanillagaming.org/?item=20517

**Comment by Sabre142** [comment]
Delete your WDB (cache) folder. I logged on to Darrowshire and queried the item, it seems to be the same stats as you've linked including 1% hit.

**Comment by j0ker2** [comment]
Items is indeed showing correct stats. Problem is that on Legacy Logs, I have only +9% hit where I should have +10% hit. Can you count how many +x% hit chance you have on Legacy Logs ?

Maybe it's a bug on Legacy Logs but since I didn't have problems before 1.8, I want to be sure it's/ it's not a bug from Darrowshire server.

**Comment by Sabre142** [comment]
Why would you trust a third party site? It should definitely work.

**Comment by j0ker2** [comment]
One the biggest website for gathering datas, no problem with it before... And that's not the question, I want to be sure this hit chance works properly on this item on Darrowshire since it's hard to tell if it does by myself.
