### ISSUE TITLE
Nat Pagle 225+ fishing quest [Alliance issue]

### ISSUE THREAD

**Issue by Danawan** [elysium-project/server#2087]
It seems that Nat Pagle's quest to get Artisan Fishing is not available to Alliance players. 

When an ally speaks to him, he only works as a merchant with no item to sell.

**Comment by Sabre142** [comment]
You must be 225 fishing and level 35 first.

**Comment by Danawan** [comment]
I am 225 fishing and level 60, of course. It seems to work for Horde players only.

**Comment by Sabre142** [comment]
Alright, did you take the breadcrumb quest from the Ironforge fishing trainer that sends you to him?

**Comment by Danawan** [comment]
Alright i just went there again and now the quest is available... "temporary" issue i guess!
