### ISSUE TITLE
Problem with [The Forging of Quel'Serrar]

### ISSUE THREAD

**Issue by Shortarms** [elysium-project/server#2093]
Hello,

I first tried to make an GM ticket, but they sent me here.

I tried to finish the [The Forging of Quel'Serrar] quest in raid with my guild 13.08.2017 on my Character Jahera. 

This is what happened: I used the Ancient blade on onyxia @ around 14% and as far as i know i am supposed to be able to pick the blade up from the ground again and when she is dead i stab her with it and i will recieve "Treated Ancient blade". but since i couldn't pick  it up, i obviously couldn't finish the quest.

Also there were a wierd bug where i couldn't loot onyxia to see what dropped, i could only use skinning on her.

Picture of the ground after onyxia was dead and skinned: https://i.imgur.com/d9MhT2c.jpg

**Comment by Dalleren** [comment]
Your description does not mention that you actually placed the blade in a position where Onyxia was able to breathe fire on it.

**Comment by Shortarms** [comment]
True, because i got no proof. However i believe i did.
Placed it where people who have already succeded the quest told me too.

**Comment by Shortarms** [comment]
Oh well. Guess i'll just have to do it again.
