### ISSUE TITLE
Quest Item respawn time really long for [15]Bingles' Missing Supplies quest in Loch Modan [Alliance]

### ISSUE THREAD

**Issue by anthonycoffey** [elysium-project/server#2095]
You collect items on the trogg island, but a lot of players are just standing around waiting for the quest item to respawn. I think these quest items should spawn more quickly to allow for multiple players in the same area to complete the quest.

Thanks

**Comment by Phoosy** [comment]
Any citations on what you believe the respawn is supposed to be? This isn't a place for "suggestions", rather for reporting issues with code, quests, items, etc. that are not matching their retail Vanilla counterparts.

**Comment by anthonycoffey** [comment]
I have no idea... but it seems we all should be able to grab the item, no?
In vanilla, would people hang around the quest item spawn point? I didn't
play vanillla so I don't know :S ... sorry! ... I guess without the whole
phasing thing that's added later, on a high population server you will have
issues like this.

but I was waiting several minutes and the quest item still not showing even
quite a while after a player got to it before me.

I'll think twice before posting next time, just trying to help!

Thanks

*Anthony Coffey*
coffey.j.anthony@gmail.com
512-221-6745

**Comment by JosipbrozElysium** [comment]
The spawn timers are correct and blizzlike. You can post suggestions here: https://forum.elysium-project.org/forum/307-suggestions/

Best regards!
