### ISSUE TITLE
Braziers during the "egg" event in Sunken Temple

### ISSUE THREAD

**Issue by Heyhohohoho** [elysium-project/server#2097]
I've had this happen once to me and several other people, basically in Sunken Temple, when you use blood to extinguish one of the braziers, the brazier sometimes stays lit after using it, consuming the blood and usually causing a wipe later in the event.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
