### ISSUE TITLE
Player variables not saved

### ISSUE THREAD

**Issue by PlaskED** [elysium-project/server#21]
Anyone else have the issue that no server stored variables per character is stored? Such as macros, addon settings, keybinds etc.

**Comment by StadenElysium** [comment]
Could you post steps to reproduce the issue?

**Comment by soiloooor** [comment]
everything is working fine, except the map extractors .. ;)

**Comment by brotalnia** [comment]
In vanilla all those are stored client-side. If you login to the same account from another copy of the client, all of your macros and key bindings will be missing. That's not a bug.

**Comment by PlaskED** [comment]
Position of abilities saved either and those are definetly server side. I'm gonna look further into it when I come home but nothing was saved client side nor server side betwen the logins.

**Comment by PlaskED** [comment]
Ok, so basically the things server side such as abilities and what bar they are on is saved. However, nothing that is supposed to save client side is being saved?

I'm not sure how to reproduce, or if anyone else even encountered this issue. The server otherwise is running fine.

**Comment by PlaskED** [comment]
Closing this. For Whatever reason I must run the Client as administrator, even though the Directory is read/write. Weird windows bug indeed ;)
