### ISSUE TITLE
Winterspring Owl in Silithus: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#210]
BUGGED BEHAVIOR
There is 1 Winterspring Owl in the middle of Silithus (between the Alliance and Horde basecamps). It obviously shouldn't be there.

 CORRECT BEHAVIOR
Winterspring Owls belong in Winterspring, not in Silithus.

 SOURCES
Common knowledge

http://db.vanillagaming.org/?npc=7455

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/1943

**Comment by StadenElysium** [comment]
This spawn was actually on retail and was reproduced as a tongue-in-cheek reference to that 'bug'.
