### ISSUE TITLE
Timbermaw Rep but cannot trade with Meilosh

### ISSUE THREAD

**Issue by Esk11** [elysium-project/server#2102]
I am honored with Timbermaw Hold but cannot trade with Meilosh.  He shows as a friendly target but rightclicking him attacks.

I should be able to trade with Meilosh in Timbermaw Hold from Friendly and above.

This is occurring on Darrowshire realm.

**Comment by Haiwuu** [comment]
Turn of 'at war' with that faction.

**Comment by Esk11** [comment]
omg

and ty.
