### ISSUE TITLE
Bugged quest:-As Water Cascades(Auberdine,Darkshore)

### ISSUE THREAD

**Issue by kzorvanilla** [elysium-project/server#2103]
I've been leveling around here for an hour or something and one specific quest called "As Water Cascades" doesen't work,it's not just me because there were other people with me trying to do the same quest and they faced the same problem.
The explanation of it is that the quest wants you to fill a vial in a moonwell and when you get there it doesen't work and a message in red appears saying"Requires Cliffspring River Waterfalls",these happens when you try to use the vial in order to fill it woth the water in the moonwell.
I'm not the only one with these problem I repeat as i saw other people unable to do the quest having the same errors.
Thank you.

**Comment by kampeador** [comment]
Its not a bug. There are two items called: Empty Sampling Tube. They are for different quests.
You need this one:
http://db.vanillagaming.org/?quest=4812
instead of:
http://db.vanillagaming.org/?quest=4762
