### ISSUE TITLE
(Elysium) Un'goro Crystals - Darrowshire Pamela's Doll

### ISSUE THREAD

**Issue by maherl31** [elysium-project/server#2111]
It is as the title says guys.

Un'goro Crystals are not spawning and,

The doll for the quest Pamela's Doll is also not spawning.

I mean, they do not spawn at all.

Thanks.

**Comment by maherl31** [comment]
Server is; Anathema

**Comment by maherl31** [comment]
Alright, yesterday after the restart some of them respawned but - they still seem to be broken. They do not spawn again. Or - takes extremely long to spawn?

**Comment by l1amm** [comment]
You might want to make separate issues for separate issues, also: please make sure there are no open issues on the topic already. There are several open regarding the crystals already.

**Comment by thepparker** [comment]
Duplicate
