### ISSUE TITLE
Error when crafting [Elixir of Greater Firepower] 

### ISSUE THREAD

**Issue by Kinukimage** [elysium-project/server#2114]
Hello,

I receive an error message when attempting to create the potion [Elixir of Greater Firepower] - I have the formula learned, the proper alchemy level and the required materials.. About 2 or so weeks ago I was able to make this potion on this same character but now I receive an error message

Picture detailing the issue.
http://i.imgur.com/ka4QbTP.png

Thank you for your time!

p.s. first time reporting a bug/ uploading a pic to imgur so I'm sorry if  I did something incorrectly

**Comment by Sabre142** [comment]
Added in Patch 1.10.
