### ISSUE TITLE
Level 52 druid quest not obtainable

### ISSUE THREAD

**Issue by Pathways12** [elysium-project/server#2117]
Level 54 Night Elf Druid

Quest not obtainable from Mathrengyl Bearwalker

Quest name is Torwa Pathfinder

Quest simply just doesn't show up as an option - I verified it as the first quest in the chain and there's no available option to click on it

**Comment by Haiwuu** [comment]
Availability of the quest is patch specific 
http://wowwiki.wikia.com/wiki/Patch_1.10.0 lists having the druid although I believe it might be implemented with 1.8

**Comment by thepparker** [comment]
Assuming Elysium, the level 50 class quests are added in a later patch
