### ISSUE TITLE
[ANATHEMA] Vargus missing quests

### ISSUE THREAD

**Issue by ksi123123** [elysium-project/server#2119]
missing quests : 
Champion's Battlegear : https://wow.gamepedia.com/Quest:Champion%27s_Battlegear
Stalwart's Battlegear : https://wow.gamepedia.com/Quest:Stalwart%27s_Battlegear
Veteran's Battlegear : https://wow.gamepedia.com/Quest:Veteran%27s_Battlegear
Volunteer's Battlegear: https://wow.gamepedia.com/Quest:Volunteer%27s_Battlegear

Been like this the past month.

**Comment by kampeador** [comment]
I pretty sure, that this will be fixed with the next dev update.
https://github.com/elysium-project/database/commit/382192f7c4df88c5694abbd22fd33b923e283dff

**Comment by twdwrd** [comment]
Yes it was added today but all you can do is pick up the quest. No way to turn it in.

**Comment by JosipbrozElysium** [comment]
Should be fixed now. 

Best regards!
