### ISSUE TITLE
Shield Spike Damage: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#212]
BUGGED BEHAVIOR
Iron Shield Spike does not apply any damage on block. I have not been able to test the Mithril or Thorium spikes yet but I would assume they are also affected.

 CORRECT BEHAVIOR
Should be doing damage on block.

 SOURCES
My paladin BS

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/1204

**Comment by simppak** [comment]
You need to re-equip your shield after you die/log to make the spike work again.

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/44683-development-update-19042017/
