### ISSUE TITLE
Black Lotus doesn't spawn

### ISSUE THREAD

**Issue by Partybeams** [elysium-project/server#2121]
For several weeks now, the Black Lotus spawns have been absent. Only after server restarts do they spawn. It is getting desperate, affecting the servers ability to raid, since prices on flasks are going up. Could you please fix it or at least communicate about it?

I do not have any proof except my experience a few months ago compared to now. Then I found lots of Black Lotus, if I spent time searching for them. A lot of people I have spoken to share the same experience.

**Comment by martinjlowm** [comment]
They do spawn. There are just lots of people herbing and the chance of getting one is very low. The previous behavior is on its way, but haven't yet been tested by the QA team.

**Comment by Manlet** [comment]
They have been bugged since the 'fix' in a few zones, definitely doesn't feel fixed

**Comment by flowqz** [comment]
no the spawns arent fixed. the only reason the flask prices arent 200-300g now is av.

**Comment by Eegor74** [comment]
The the issue is the same as with the crystals in UG
https://github.com/elysium-project/server/issues/1831
Spawns work for a while then break

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/52678-development-update-23082017/
