### ISSUE TITLE
Sweeping Strikes damage consumption when used with Cleave/Whirlwind

### ISSUE THREAD

**Issue by Ektelion** [elysium-project/server#2122]
There is something that is definitely wrong when using Sweeping strikes together with whirlwind, it is basically our best aoe ability in terms of PvP, without it we're kinda gimped.
I know sweeping strikes was changed many times in order to work correctly, but we don't know what was the final implementation of how the ability should work, because in TBC it worked exactly the same like vanilla.

Pat famous Warrior - https://www.youtube.com/watch?v=BET3bKzcbEM - Vanilla WoW
Maydie famous Warrior- https://www.youtube.com/watch?v=YzPlictRoK8 - Vanilla WoW
Clinda famous Warrior -https://www.youtube.com/watch?v=dGWAB3mxA_A&t=187s - TBC WoW, go to 3:04 minute to see cleave with whirlwind to save your time

**Comment by nikolay510** [comment]
https://github.com/elysium-project/server/issues/2049

Good luck.

**Comment by thepparker** [comment]
> > Whirlwind - When this ability is used with Sweeping Strikes, it will burn only one charge of Sweeping Strikes and will generate only one additional attack.

> The same can be assumed for Cleave

> http://vanilla-wow.wikia.com/wiki/Patch_1.10.0

https://youtu.be/YzPlictRoK8?t=220 3:42 - 2 targets. Sweeping Strikes is up, and he Cleaves. There's only 3 hits, which means SS only added 1 hit despite the ability hitting two targets.
