### ISSUE TITLE
(Anathema) Warsong quest marks - cant' get the quest - marks expire in my mailbox

### ISSUE THREAD

**Issue by mdouchie** [elysium-project/server#2123]
Hello

Thank you for you attention and please, excuse me for my bad english.

I got some isssues with the Warsong Quest. I simply can't get the quest to change my marks. So I had several marks in my bags and mailbox that i can't use and will expire.

The 2 others quests (Alterac and Arathi) seem working. I just can't see it when I talk to the Horde Warbringer.

My character is Lancey (warlock) on Anathema.

Thanks a lot for your help and your work on these servers.

Max.

**Comment by Psthar** [comment]
same here anathema AV Marks the only turn in bg marks there no other quest than invaders of alterac valley

**Comment by thepparker** [comment]
Should be fixed
