### ISSUE TITLE
[Elysium] Cannot fly anywhere from Ratchet

### ISSUE THREAD

**Issue by SkedaddleRogue** [elysium-project/server#2128]
I have grabbed flightpaths in Feralas, Desolace and Tanaris - However I cannot fly to any of these from Ratchet. It only tells me I know no connecting flight points.

I have tried removing my WTF and WDB folder, but that didn't change anything.

**Comment by luigimannoni** [comment]
Wow vanilla doesn't allow to fly over undiscovered flight paths, so probably you are missing a flight path in between. 

If you are horde ratchet is only connected to Crossroads.
If you're alliance probably you are missing either a FP in Dustwallow Marsh or Azshara.

![alliance fp](http://tu9srvbirvvtmjikemftlnphbwltzy5jb200.g00.allakhazam.com/g00/2_d293LmFsbGFraGF6YW0uY29t_/TU9SRVBIRVVTMjIkaHR0cDovL3phbS56YW1pbWcuY29tL2ltYWdlcy8yLzYvMjY0ZTgzOWUxZTM2MzUzZTgwYThjMjBjM2ExNTk2NjAucG5nP2kxMGMubWFyay5pbWFnZS50eXBl_$/$/$/$/$)

**Comment by SkedaddleRogue** [comment]
I see, I was not aware of this. Thank you!
