### ISSUE TITLE
Priest Tier 2 8 set bonus causes strange buff: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#213]
BUGGED BEHAVIOR
When all 8 pieces of the priest tier 2 gear are equipped, a timerless buff appears called "Greater Heal Renew" with the Samwise icon. Right clicking does not remove it. Unequipping any pieces of the gear does remove it.

 CORRECT BEHAVIOR
No buff icon

 SOURCES
bug icon: http://wowwiki.wikia.com/wiki/Samwise_Didier

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/1221

**Comment by QAkvastskaft** [comment]
I have seen the same for tier 2 mage set also, likely caused by the same issue

**Comment by QAClayton** [comment]
This is Confirmed. Wearing 8/8 priest t2 gives you samwise icon. only comes off by removing a piece of tier 2 you are wearing.

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/43686-development-update-05042017/
