### ISSUE TITLE
Elysium - Lord Kazzak

### ISSUE THREAD

**Issue by keaarori** [elysium-project/server#2134]
Currently, on Elysium I believe that Fel Infused Leggings are not on Kazzak's loot table, the last several months of kills (~15 kills) have not had any Leggings for any guild, Can someone check the loot table currently on Elysium to make sure this item is properly dropping?

**Comment by some2** [comment]
Yep, they are not in his loot template.

**Comment by Nillerpiller01** [comment]
They have confirmed dropping on Elysium:
http://realmplayers.com/ItemUsageInfo.aspx?realm=Ely&item=19133
