### ISSUE TITLE
pvp marks

### ISSUE THREAD

**Issue by lockdandload** [elysium-project/server#2136]
I can spend only alterac vallys marks.to spend other marks doesnt offer. i have 2 computers and 4 accaunts. broblems r the same

**Comment by Popemall** [comment]
AV marks was fixed after the AV week ended and our marks were deleted from the mail box, can we please try and fix these issues before we lose another great deal earned honor and rep..

**Comment by Psthar** [comment]
I can only turn in AV Marks

**Comment by Travnastington** [comment]
I can also only turn in AV marks. 
![too many marks](https://user-images.githubusercontent.com/30742031/29483264-3265b32a-8468-11e7-8c50-a2bf9c9eafda.jpg)

**Comment by thepparker** [comment]
Should be fixed now

**Comment by lockdandload** [comment]
everything fine now.u r best
