### ISSUE TITLE
Are we there yeti? - quixxil- missing npc

### ISSUE THREAD

**Issue by githubkimdaniel** [elysium-project/server#2137]
Hello devs, 

I would like to report a missing NPC named Quixxil at Marshal's Refuge in un'goro crater. Said NPC is needed for third part of quest chain: "are we there yet?". NPC cannot be found at spawn location but can be targeted with /target command. Quest item: umi's mechanical yeti cannot be used on targeted NPC. 

Hoping for a quick resolution, thank you.

**Comment by berillis** [comment]
Other people doing that quest have scared her away to this location. For some reason if multiple people do the quest and manage to find her wandering outside her normal spawn they can scare her even further. When I was doing the quest I found the Winterspring NPC wandering at the ice lake.

**Comment by Spionida** [comment]
Was reset by GM - normally in-game ticket is needed.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
