### ISSUE TITLE
Game launching problem

### ISSUE THREAD

**Issue by Achillesleva** [elysium-project/server#2138]
I cannot enter the game for some reason., it says connecting for a while than says disconnected from server.. what should i do to fix it?

**Comment by luigimannoni** [comment]
Can be a number of reasons really, sometimes the login servers are unresponsive, sometimes Elysium goes down or can be a problem on your end such as connection or firewall rules.

Try again later, if you can login then it's the server otherwise try to connect with a different computer and see if you succeed

**Comment by brotalnia** [comment]
Did you maybe forget to change your realmlist?

**Comment by Achillesleva** [comment]
This problem persists for few days now.. my realm list is 'set realmlist logon.elysium-project.org' , nothing is wrong with the connection or the firewall is not blocking or anything.. i even re downloaded the client. So dont have any idea what els to do.

**Comment by luigimannoni** [comment]
Do a `ping logon.elysium-project.org` from cmd.exe and post results here

**Comment by Achillesleva** [comment]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Carbon>ping logon.elysium-project.org

Pinging logon.elysium-project.org [164.132.233.125] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 164.132.233.125:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

C:\Users\Carbon>

**Comment by luigimannoni** [comment]
Timeout is ok, just checking the IP which seems to be the correct one.

Have you tried to use another PC?

**Comment by Achillesleva** [comment]
@luigimannoni Problem solved by it self somehow.. i can enter the game now.. thanks for helping peace!
