### ISSUE TITLE
Quest: The Balance of Light and Shadow

### ISSUE THREAD

**Issue by yobanchi** [elysium-project/server#2145]
Hello, yesterday evening I accepted the quest The Balance of Light and Shadow at Eris in EPL, then the quest was failed by someone and mine was marked as Failed as well. 

Today after long hours of waiting I finally see Eris appear again, but she gives me no quest, starts no event, and I cannot abandon the failed quest in my journal (Nothing happens when I click "yes).

What should I do to prevent this/be able to take the quest again, thanks

**Comment by yobanchi** [comment]
![wrk](https://user-images.githubusercontent.com/29761116/29464737-135a530e-8437-11e7-93e7-e57c32409407.jpg)

**Comment by AndreRieu1949** [comment]
disable quest+questlog addons and try again

**Comment by yobanchi** [comment]
Disabled Questie and was able to abandon quest thank you very much
