### ISSUE TITLE
Soul Link warlock critical bug [elysium]

### ISSUE THREAD

**Issue by cocaine944** [elysium-project/server#2148]
You can't purge soul link buff from warlock nither his pet. 
You 100% could purge it from warlock's pet in retail times. Not sure about wl him self.
According to http://db.vanillagaming.org/?spell=19028 this is Dispel type | Magic spell. 
This is very important bug please fix asap,

**Comment by Haiwuu** [comment]
Please add proof.

**Comment by cocaine944** [comment]
Here is thottbot link. Same - Dispel Type | Magic
http://web.archive.org/web/20060114201929/http://www.thottbot.com:80/?sp=19028

**Comment by cocaine944** [comment]
and down below you can see what can purge/dispel this

**Comment by GuybrushGit** [comment]
1.9.0 (2006-01-03): Can no longer be dispelled off the warlock. In addition, Soul Link can no longer be used on non-demon pets.

1.8.0 (2005-10-10): The aura will last as long as the pet is active, and the pet must be the target of a dispel effect in order to dispel this ability.

**Comment by Itembugs** [comment]
this spell cant be purged

**Comment by GuybrushGit** [comment]
Rereading the second patch note: "Can no longer be dispelled off the warlock."
This could mean not dispellable at all rather than a reinforcement of the pet only rule. I most likely read that wrong.
