### ISSUE TITLE
Darkmoon card: Maelstrom proccing/breaking off CC (e.g. Gouge)

### ISSUE THREAD

**Issue by Zonati** [elysium-project/server#2149]
First of all, this is a difficult bug to find evidence for since there seems to be little direct information about how this particular item interacts with Incapacitating effects such as gouge. However, I have done numerous research into other proc items, which work in similar, or in the exact same way, as Darkmoon card: Maelstrom. One such proc is the Storm-shroud 2 set bonus: "5% chance of dealing 15-26 nature damage on a successful melee attack" http://db.vanillagaming.org/?spell=18979 (I'm aware this website isn't considered a valid source, but these are how the procs work on Elysium aswell) This works the exact same way as Maelstrom works, apart from proc rate and damage, http://db.vanillagaming.org/?spell=23686. The difference is that the Stormshroud set doesn't break incapacitate effects on proc (which is blizzlike: Patch 1.11.0 Stormshroud Set: The Lightning effect from this set will no longer break your Gouge; (source: http://shadowpanther.net/roguechanges.htm) However this trinket does. Additionally, comments from February 2006 say that this trinket should NOT proc on gouge: "this procs on melee strikes including instant attacks.  Not positive about a proc on sap, however it will proc on a gouge but does not break the gouge. (source: http://web.archive.org/web/20070515083410/http://www.thottbot.com/i19289 ). This comment was written when WoW was at patch 1.9, however; there are no patch notes atall regarding this trinket, apart from it's release in 1.6, so I assume that it was like that on release aswell.

**Comment by GuybrushGit** [comment]
Stormshroud is breaking CC as well, everything is.

**Comment by Harkonnen13** [comment]
Sad, bud this issue still works on Elysium. The Lifesteal enchant proc breaks Gouge (not really often, but still), as well as the Darkmoon card: Maelstrom.
