### ISSUE TITLE
[Elysium] Lootboxes (with research)

### ISSUE THREAD

**Issue by nydokade** [elysium-project/server#2153]
"Pick pocketing now has a chance of getting you a locked Junkbox, which is a locked item that generally has money in it."

http://wowwiki.wikia.com/wiki/Patch_1.1.0

right now most of the time they are completly empty

**Comment by Sabre142** [comment]
nerfed to counter gold farming

**Comment by nydokade** [comment]
no. 

Devs removed grey items cus they were added in 1.12, which is completly true.

**Comment by nydokade** [comment]
can you mention WHY it is invalid?
