### ISSUE TITLE
[46] Ledger From Tanaris - Bugged

### ISSUE THREAD

**Issue by precisionn** [elysium-project/server#2163]
Quest is completed but cannot be turned in.

**Comment by Spionida** [comment]
Try [https://forum.elysium-project.org/topic/47571-can-not-turn-quest-in/](url). If that does not work, in-game ticket.

**Comment by MikaTurin** [comment]
same for me, tried solution above, no result

**Comment by QAkvastskaft** [comment]
If you remember what you did to cause this, post here: #1977
