### ISSUE TITLE
Reclaimed Treasures bug

### ISSUE THREAD

**Issue by Naerya** [elysium-project/server#2164]
Hi,

I found that quest Reclaimed Treasures in Uldaman does not work properly. I can not click the chest in the South Common Hall to open it and loot it.

Can you fix that please?

**Comment by NeyaElysium** [comment]
Just did this Quest yesterday and nobody in our group had problems looting it.
Are you sire you were at the right spot?

**Comment by Naerya** [comment]
Yes were right! I was really in wrong hall! But there are 2 halls looking exactly the same, I checked it on youtube also. The thing is I assume,  that for the horde it is in the other common hall, I think North. And that was the guide I checked on youtube :). Thx m8
