### ISSUE TITLE
Dark rune and goblin sapper charge crit isnt giving redoubt or reckoning

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/server#2165]
https://youtu.be/rMiNPkF3hd0

https://youtu.be/EnPg76xCWW4

Still hasnt been fixed even up to naxx ptr or on anathema/elysium

spell reckoning: http://db.vanillagaming.org/?spell=20182
spell redoubt: http://db.vanillagaming.org/?spell=20137
http://db.vanillagaming.org/?item=20520 Dark Rune
http://db.vanillagaming.org/?item=10646 Sapper charge

Can you make goblin sapper charge and dark rune crits proc redoubt and reckoning.

**Comment by Mostprovidedlinks** [comment]
https://github.com/elysium-project/server/issues/604

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
