### ISSUE TITLE
Bug in General Drakkisath loot table?  - Darrowshire

### ISSUE THREAD

**Issue by tlank** [elysium-project/server#2167]
Hello, 

I was just wondering if there is any chance that the loot table for General Drakkisath in Upper Blackrock Spire (UBRS) could be bugged.  I have been trying to obtain an item (Draconian Deflector) which supposedly has an ~15% drop rate.  However, all I have seen in approximately 20 runs is the Brigham Girdle x2, Tooth of Gnarr x2, or Tooth of Gnarr x1 +Brigham Girdle x1 (plus a [semi]random T0 chest piece, seems to always be Valor or Magister's, never any other).  

I know it is possible to have a 15% drop rate and run something 20 times and not get it, but the probability of that is tiny and it is suspicious along with the reoccurring loot. If I am not mistaken, there is a 0.15 chance of getting the Draconian Deflector on a single roll and there are 2 rolls when you kill Drakkisath.  So if I have run 20 times that is 40 rolls which mean the probability of me NOT getting the Draconian Deflector by now should be ~0.15% (0.85^40) aka 1.5/1000.  Like I said, the probability of randomly experiencing what I have exists, but it almost does not.  

I appreciate any feedback. If I am just really really unlucky I am happy to accept that.  But like I mentioned above, the patterns I am seeing plus the unlikelihood of the scenario which I find myself in makes me think that something may be wrong with the loot table. 

To be clear I am noticing normal drop rates on all other bosses in UBRS (Pyroguard Emberseer, Jed Runewatcher, Rend Blackhand/Gyth, and the Beast), but the trend in Drakk's loot is odd. 

Best wishes and thanks for any feedback,

Warvillan, Darrowshire

**Comment by Sabre142** [comment]
Drakkisath has always been horrible in loot on Elysium. Drops brigam girdle and tooth of gnarr virtually every time. Yet according to [this ](http://web.archive.org/web/20050206230554/http://wow.allakhazam.com:80/db/mob.html?wmob=10363)they should all be equal.

**Comment by coryo** [comment]
before patch 1.10 Drakkisath will drop 2 items from:
```
item, name, chanceorquestchance
12602, Draconian Deflector, 18
13098, Painweaver Band, 18
13142, Brigam Girdle, 18
13141, Tooth of Gnarr, 0
```
Tooth of Gnarr is set at 0% and the other 3 are set to 18%. that means tooth of gnarr gets a 46% chance to roll.

![image](https://user-images.githubusercontent.com/678207/29498328-652482a4-85c7-11e7-843e-d61848a328de.png)

**Comment by tlank** [comment]
That drop query % looks great, much higher than I thought even.  That is from Darrowshire? 

If that is actual Darrowshire loot %'s then I guess I am just that person with statistically impossible luck  (36% drop rate with 24 attempts and 2 rolls per attempt gives me (0.64^48)=0.00000005% chance of 0 sightings over 24 runs).  

Bummer, but good to know that it is just unbelievably bad luck.  

I think this means I should buy a lottery ticket? Since, in some sense, I am accomplishing the mathematically impossible. 

Cheers, 

Warvillan, Darrowshire

**Comment by tlank** [comment]
Even if it is 18% chance to drop between the 2 rolls combined this means my chance of never seeing it over 24 runs would be  0.002%, still extremely small.

**Comment by coryo** [comment]
I don't know what Darrowshires database looks like. This info is just based on what's available on the Github.

**Comment by tlank** [comment]
Ok, good to know.  Thanks! 

Could anyone confirm that the drop %'s form Drakk on Darrowshire are consistent with those Coryo posted above?  

I am suspicious.

**Comment by Kolmarwow** [comment]
yeah i've seen the draconian deflector drop around 4 times in my last 10 runs on Darrowshire, though before that i hadn't seen it for like 15 runs. so i'd say it's just bad RNG on your part.

**Comment by GuybrushGit** [comment]
Fixed with new progressive database.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
