### ISSUE TITLE
Tier 2 Gloves Not Dropping Correctly

### ISSUE THREAD

**Issue by femdead** [elysium-project/server#2168]
There should be 2 sets of Tier 2 Gloves every BWL raid, split between the 3 Drakes. Currently the loot tables are seperately rolled, meaning it's possible to get anywhere between 0-3 sets of gloves which is incorrect.

from http://wowwiki.wikia.com/wiki/Blackwing_Lair_loot:
"The bosses of Blackwing Lair all drop two Tier 2 set pieces except for Firemaw, Ebonroc and Flamegor who drop two Tier 2 gloves between the three of them and can also draw from a shared loot table."

3 pairs of gloves: http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=85748
0 pairs of gloves: http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=85743
1 pair of gloves: http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=85759

**Comment by thepparker** [comment]
The gloves are dropping correctly. You can see in the following DKP logs from Vanilla that all 3 drakes dropped a pair of T2 gloves (http://mistertnt.com/default.aspx?mode=raids):
http://mistertnt.com/default.aspx?mode=raids&raidID=581
http://mistertnt.com/default.aspx?mode=raids&raidID=582
http://mistertnt.com/default.aspx?mode=raids&raidID=583

All from the same raid on 08/17/2016. I'm not aware of any loot drops that are dependent on what has dropped previously.
