### ISSUE TITLE
Nether-lace Tunic

### ISSUE THREAD

**Issue by greg00139** [elysium-project/server#2170]
Nether-lace tunic does not apply attributes correctly:
![image](https://user-images.githubusercontent.com/4556949/29490547-ede639a8-853f-11e7-952f-49c63131ca8c.png)
![image](https://user-images.githubusercontent.com/4556949/29490549-01109b54-8540-11e7-9569-4890ae2c45cc.png)
![image](https://user-images.githubusercontent.com/4556949/29490551-0a1f11b2-8540-11e7-9eee-847faa12e0c5.png)

Please note the before and after snaps of the attributes without and with the item equipped.
The item applies 2 stamina, 40 armor, 8 spirit.

**Comment by Sabre142** [comment]
Delete your WDB folder to get correct item stats

**Comment by thepparker** [comment]
Clear WDB
