### ISSUE TITLE
Unable to turn in Target: Hive'Regal Spitfires

### ISSUE THREAD

**Issue by Haitharn** [elysium-project/server#2171]
I had the quests [Target: Hive'Regal Spitfires](http://db.vanillagaming.org/?quest=8775) and [Target Hive'Regal Slavemakers ](http://db.vanillagaming.org/?quest=8776) completed in my questlog like [this](http://imgur.com/a/cqXVv), but the NPC to turn the quests into was still silver question marked. I had the two items required for the quests in the bags, [Combat Task Briefing IX](http://db.vanillagaming.org/?item=21253#objective-of) and [Combat Task Briefing X](http://db.vanillagaming.org/?item=21255#objective-of) for Spitfires and Slavemakers, respectively. After relogging, the quests were still uncompletable, so I deleted the items and and attempted to get new ones from a Hive'Regal Dossier. I opened the dossier, and there were no items in it. It would not allow me to see the 2 briefings I needed, even though I knew I had never opened that before. I had 2 more, same issue. I deleted all 3 dossiers and got a fresh HIve'Regal Dossier, still unable to loot the items. Put in a ticket, spoke with a nice GM Saturnian, and he told me to make a GitHub report about it since it had not been done before. He was unable to complete the quests for me, nor give me the quest rewards. I just killed 60 elite mobs for nothing, so I am pretty frustrated. 

Does anyone have any input on this issue? Ever had it before, know how to reproduce it, what causes it, how to fix it, anything?

**Comment by GuybrushGit** [comment]
I was able to get new briefings from a new dossier while keeping the original quest. 
Just make sure you're not in a raid group.
