### ISSUE TITLE
Rouge bug

### ISSUE THREAD

**Issue by josevalladares1** [elysium-project/server#2175]
Hello, I wanted to report a bug that is happening to me, maybe 2 the first is that I have less 15 of agi without any debuf the equipment is all good etc. The second is that I can not use steal out of combat reloguie mori etc to see if it worked and I do not even expect your response the name of my character is Rogguet thanks

**Comment by thepparker** [comment]
Unequip all your gear, delete WDB and restart your game. If you still have -15 agi post a screenshot

**Comment by josevalladares1** [comment]
ohh now yes i can steal again and dont have -15 agi thx!
