### ISSUE TITLE
Avatar of Hakkar encounter in Sunken Temple

### ISSUE THREAD

**Issue by Vartu** [elysium-project/server#2180]
Hello,
I would like to report several bugs during the Avatar of Hakkar encounter in Sunken Temple.

The fight appears to suffer from possibly multiple script errors. Once a fire is doused, most of the time the channeling add doesn't spawn. We also had only 2 wind serpents spawn, so only 2 bloods could drop.

After wiping we could douse the 4 flames (only 1 channeler appeared though) and nothing happened.

Using the Egg of Hakkar again during the fight is possible and results in even more broken scripts. We had it finally trigger Hakkar's appearance, but at the same time large amount of adds appeared, and the fires re-lit.

Edit: Typos.

**Comment by blubba22** [comment]
Yeah, the fight is seriously broken.
I have also encountered several bugs. Once no new wind serpent spawned, so we couldn't douse. Another time we had enough blood but the dousing simply didn't work. We had the channeling animation and the blood was used up but nothing happened.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/
