### ISSUE TITLE
Princess Saved bug

### ISSUE THREAD

**Issue by Nameless89** [elysium-project/server#2183]
Hi!

I can't pickup "The Princess Saved?" pre-quest Commander Gor'shak from Galamav the Marksman. I meet the requirements for this quest, but still I can't pick up it.

Can you help me?

Kind regards,
Greg

**Comment by thepparker** [comment]
You need to do Disharmony of Flame (kill Overmaster Pyron), and then kill Incendius. After that, you can get the Commander Gor'shak quest.
