### ISSUE TITLE
Iron Foe not proccing "fury of fortwright" on execute

### ISSUE THREAD

**Issue by Roflkopterr** [elysium-project/server#2189]
One of the most recent patches specifically stated that execute along with bloodthirst and sunder armor could now proc on hit attacks from weapons.

Bloodthirst and sunder armor are working as intended now.

Execute is not. For 2 full raids now I have been switching to IronFoe for bosses on 20%, on Nefarion tonight after casting almost 25 executes, my ironfoe was not proccing whatsoever.

Fix: Execute needs to be able to proc on hit attacks from weapons.

**Comment by blubba22** [comment]
5% proc chance on 25 executes means you "should" have gotten 1,25 procs. Not getting any proc is still well inside the expected margin, right?

**Comment by Roflkopterr** [comment]
When using iron foe on trash or during a regular rotation i see a proc
every 10 to 15 seconds of damage dealing. If i am getting an average of 1
proc per 13 seconds i should see atleast one during 40 seconds of straight
executing but this is not the case.

**Comment by Sirael11** [comment]
You do realize that after 25 Executes you still have almost 30% chance to not see a proc?

**Comment by Roflkopterr** [comment]
Once again so I Can clear this up for those of you being overly critical. I
did not JUST get iron foe and create this post after one raid. I have not
seen an Ironfoe proc during executes for MONTHS. let me state that time
frame again for you: I have not seen an Ironfoe proc during executes for
MONTHS (plural) aka 12+ weeks

**Comment by GuybrushGit** [comment]
Its working in dev.

**Comment by Roflkopterr** [comment]
Thats good news. Wtb this on live please.
