### ISSUE TITLE
(Warlock) Equipping Spellstone should increase crit change with spells by 1%

### ISSUE THREAD

**Issue by dogmax** [elysium-project/server#2193]
Spellstones have the passive effect of increasing the spell crit chance of the warlock by 1%. 

Currently this is not the case as there is no increase in spell critical strike chance.

This was added in patch 1.3.0

Source: 
http://wowwiki.wikia.com/wiki/Patch_1.3.0

**Comment by GuybrushGit** [comment]
Fixed with new progressive database.
