### ISSUE TITLE
Баг крита(Darrowshire)

### ISSUE THREAD

**Issue by TotoroRoE** [elysium-project/server#2206]
Здравствуйте , почините баг таланта Cruelty 5% крит у варов на Darrowshire.

**Comment by TotoroRoE** [comment]
Баг: при дизарме убираешь оружие в сумку  ,ждешь ,когда сападет дебаф, потом одеваешь оружие обратно  и получаешь 5%крита сверху)(если нету таланта на крит, баг не работает)
Пожалуйста ,почините этот баг)

**Comment by Sabre142** [comment]
Already been reported.
