### ISSUE TITLE
Missed Class Quest

### ISSUE THREAD

**Issue by AsterionLordofSuffering** [elysium-project/server#2209]
I Missed my level 10 Hunter class quest called "The Hunter's Path" and now can no longer receive it, being too high level. Any fix?

**Comment by Haiwuu** [comment]
I don't think you can be too high, its just that the quest npc won't have the quest marker above his head.

**Comment by Spionida** [comment]
It's a breadcrumb quest. If you have learned how to tame beasts, you can not get it again. All it is is a quest to sends you to your trainer to start the taming series.

I suspect that an in-game ticket that I answered explains in detail. Or I may be thinking of another.
