### ISSUE TITLE
[Elysium][Quest] Can't re-accept 'The Stone Watcher' after abandoned the quest.

### ISSUE THREAD

**Issue by LollingChris** [elysium-project/server#2213]
Hi, 

Here is the thing:

I had this quest and i was reading the dialogue to finish what the quest required: 'Learn the purpose of the Stone Watcher of Norgannon', and after several minutes, the NPC disappeared, and i can no longer complete the quest (cause i haven't finished the dialogue yet)

I tried re-login, no NPC. So I abandoned the quest, re-login again, still no NPC.
And I can't get the quest anymore.

Please take a look.
Thank you!

**Comment by GuybrushGit** [comment]
Need someone else to finish the previous quest so they spawn the NPC.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
