### ISSUE TITLE
safespotting  killed someone

### ISSUE THREAD

**Issue by viouszeze** [elysium-project/server#2214]
Dear GM:
  There was an alliace Gnome warlock(name:henjiaose)  use the blind area of  Gadgetzan guard to kill  some horde players.
 time:2:20 P.M
evidence linking: http://v.youku.com/v_show/id_XMjk4NTM4MzQ4NA==.html?spm=a2h3j.8428770.3416059.1

**Comment by Spionida** [comment]
Please make an in-game ticket with this information. If you do make a report, mention the realm.
