### ISSUE TITLE
Magic resistance potion is not stacking with Mark of the Wilds.

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#2216]
Problem: Magic resistance potion and minor magic resistance potion 
are not stacking with mark of the wild. http://db.vanillagaming.org/?spell=9885
http://db.vanillagaming.org/?item=9036 
http://db.vanillagaming.org/?item=3384

Anathema: https://youtu.be/XEzv57zT9LM (not stacking)

There are sources stating that the resistance potion only stacks with wilds. The paladin auras and priest's shadow resist buff is stated not to stack with resistance potions. Only Mark of the Wilds does.

Old page Source: http://web.archive.org/web/20070610010957/http://www.wowwiki.com:80/Resistance

http://wow.allakhazam.com/forum.html?forum=21&mid=118716905718093666

On anathema/elysium they are not stacking. 

Fix: 

- change resistance potions so they stack with Mark of the wilds

Thanks elysium team.

**Comment by druidish** [comment]
These aren't suppose to stack. It uses the same aura type as the other non-stackable resistance auras.
(6) Apply Aura #143: Mod Resistance Exclusive

If it was suppose to stack then it would use the following aura like the UBRS buff.
(6) Apply Aura #22: Mod Resistance


http://db.vanillagaming.org/?spell=16878 - MotW
http://db.vanillagaming.org/?spell=11364 - Magic Resistance Potion
http://db.vanillagaming.org/?spell=15123 - UBRS FR Buff.

**Comment by Sabre142** [comment]
Not a bug.

**Comment by Mostprovidedlinks** [comment]
Good find. It just goes to show you how wrong wowiki can be.
