### ISSUE TITLE
Elemental Sharpening Stone bug

### ISSUE THREAD

**Issue by Bloodmoon-Darrowshire** [elysium-project/server#2217]
When using Elemental Sharpening Stone (http://db.vanillagaming.org/?item=18262) on off-hand weapon there is no crit that summed up with total crit. Summed only main-hand crit.
Before using Elemental Sharpening Stone:
![wowscrnshot_082217_224513](https://user-images.githubusercontent.com/30354821/29576216-42aaf2fa-8791-11e7-85c0-87088c412927.jpg)
Using on Off-hand weapon:
![wowscrnshot_082217_224539](https://user-images.githubusercontent.com/30354821/29576277-75879c0a-8791-11e7-9026-ddf7f7440a6c.jpg)
Using on main-hand and off-hand weapons:
![wowscrnshot_082217_224553](https://user-images.githubusercontent.com/30354821/29576322-9a49c8ce-8791-11e7-8fdd-6c8104a1297a.jpg)

**Comment by blubba22** [comment]
I think this is intentional. 
If you use Elemental Sharpening Stones on the OH it only affects attacks with said offhand not your yellows/mainhand attacks.

**Comment by towneh** [comment]
Indeed, please see the Elysium patch notes from January 12th to see that this affect was intentional fixed and not intended to stack.
