### ISSUE TITLE
Crystal of zin-malor should keep ticking when i ressurect with thesame damage and mana drain

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#2219]
The effects from the crystal, mana drain and damage should not stop when i ressurect. 
On elysium when I ressurect the trinket stops.
The mana drain is also tied to the damage. So they would both do thesame thing.

Wrong: https://youtu.be/qhrNorhrook (anathema)
My buff disappears

Correct: https://www.youtube.com/watch?v=kBtSAjKmPPw 
(player ressurects many times)
Look where the buff is when player dies

In the video the buff is showing in spirit mode and when the player ressurects it ticks the exact SAME damage every time. It reticks when he ressurects.

Fix

- Make trinket so it is a constant buff that continues apon ressurecting like in the video 
and damage/mana drain stays thesame when you ressurect.

Reason: It will make my flag carrying ALOT easier and not waste hours swapping the item around changing its damage. Also it will prevent my second trinkets going on 30 second delays
------------------

I made this separate to this https://github.com/elysium-//issues/1907 post because the other post is about right clicking the buff off.

**Comment by Sabre142** [comment]
You are right but what is the point?

**Comment by Mostprovidedlinks** [comment]
This will save us time changing it all day on our warrior to set it everytime we die

**Comment by Mostprovidedlinks** [comment]
Instead of wasting 10 hours a day flipping it on my warrior or paladn

**Comment by Mostprovidedlinks** [comment]
It would be best used in pvp for us

**Comment by Mostprovidedlinks** [comment]
The damage and mana drain change up to 500 if its changed.

**Comment by Sabre142** [comment]
Why do you want to lower your health? A developer could do something more useful with their time

**Comment by Mostprovidedlinks** [comment]
Oh so pvp isnt the important part of the server?

**Comment by Sabre142** [comment]
I don't get why you want to lower your health in the first place.

**Comment by Mostprovidedlinks** [comment]
The 500 ticks would drop us in 8 seconds without being attacked. Im sure living 5 times longer is more important. Especially when a priest tries to mind control my warrior.

**Comment by Mostprovidedlinks** [comment]
I just told you

**Comment by Mostprovidedlinks** [comment]
it would be very good for pvp flag carrying on my warrior

**Comment by Mostprovidedlinks** [comment]
Currently because of the way it works it is useless

**Comment by Mostprovidedlinks** [comment]
Living 5 times longer as a flag carrier is a big advantage

**Comment by Mostprovidedlinks** [comment]
Fix: The damage and mana drain need to remain unchanged when ressurecting as the buff should be continuously on.

**Comment by thepparker** [comment]
Yet another duplicate
