### ISSUE TITLE
Improved power word: fortitude +prayer of fortitude bug

### ISSUE THREAD

**Issue by Asklepius** [elysium-project/server#2220]
Improved power word: fortitude with rank 2/2 should increase the effect of Prayer of Fortitude by 30%, but it doesn't improve it at all. However, it does increase the effect of Power word:  fortitude.

**Comment by ItsmeAga** [comment]
it does work for me

**Comment by Asklepius** [comment]
Thanks for the help! You're totally correct, my bad. I didn't notice I had PoF rank 1 instead of rank 2. Probably rank 2 with talent improvements gives +70 sta, as it should? Gotta find the codex now...
Please remove this bug report?
