### ISSUE TITLE
Ghost-o-plasm Round Up

### ISSUE THREAD

**Issue by Ledzoor** [elysium-project/server#2224]
The quest Ghost-o-plasm Round Up in Desolace is not registering correctly. The quest has the player go to the center of the Valley of Bones "between the two big skeletons in the valley, the Dead Goliaths." Once the player is there they should click on the Crate of Ghost Magnets the quest gives you and it should spawn a little twirly objects that summons ghosts to it. Except when I'm on the little hill between the skeletons and click on it, it gives a red message: Requires The Dead Goliaths.

**Comment by NeyaElysium** [comment]
I just did the Quest not even a day ago.
No problems at all besides the Ghost Spawn rather quick. Maybe you were just at the wrong spot.

**Comment by zack** [comment]
Agreed with @NeyaElysium. The spot is kind of specific and hard to pinpoint.

**Comment by thepparker** [comment]
Try in another spot
