### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by ogonwilka** [elysium-project/server#2229]
Hello,

i got some problem what i didnt get before anytime. When i trying to login in login panel i seen for few secounds connecting and after disconnect . Im deleted folders WTF/WTB, checked already realmlist . Dont know what to do ? any think how to fix it?

best wishes,
Ogonwilka

**Comment by JosipbrozElysium** [comment]
Not a bug report. You might've connection issues (or the server was down)!

Best regards!
