### ISSUE TITLE
Totem of life missing from Fankriss loot table. [ANATHEMA]

### ISSUE THREAD

**Issue by Haiwuu** [elysium-project/server#2233]
http://db.vanillagaming.org/?item=22396 seems to be missing from the Fankriss loot table according to 

http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22396 

**The data isn't conclusive** but it appears the druid epic counterpart http://db.vanillagaming.org/?item=22399 drops a lot http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=22399 

the two items were added with 1.10 so I feel its not unreasonable to assume if one is dropping with almost 100% certainty and the other one isn't there is some issue linking the two.

http://wowwiki.wikia.com/wiki/Patch_1.10.0 mentions relics dropping from aq.

http://wayback.archive.org/web/20070810161543/http://wow.allakhazam.com:80/db/item.html?witem=22396

Comments from march and april suggesting it dropped, timeframe is between patches 1.10 and 1.11

**Comment by SiguDS** [comment]
The paladin counterpart from fankriss is dropping yet not the shaman one? :/ Please don't leave the hordes hanging :(

**Comment by Haiwuu** [comment]
For what its worth, I was reliably able to get the item to drop on the elysium repack, a locally hosted version but I still can't say for sure anyone on anathema has gotten this item since it was supposed to have introduced with 1.10.
