### ISSUE TITLE
Wind Rider Master silithus does not get help from CH guards

### ISSUE THREAD

**Issue by vindruvor** [elysium-project/server#2238]
Runk Windtamer <Wind Rider Master> does not get help from Cenarion Hold infantry (guards) in Cenarion hold when attacked by alliance.

Sadly I did not record when I saw an alliance killing him in the middle of the camp, just next to many guards.

I have no proof that Guards should help the flight master. I could try to find some information about this but I believe it will be hard. So I guess it will be up to the server Developers to decide what is correct.

**Comment by thepparker** [comment]
Guards will only interfere when hostile creatures come near, or players engage in combat with each other. This is working correctly to our knowledge.
