### ISSUE TITLE
Blackout procs on periodic ticks instead of spell application

### ISSUE THREAD

**Issue by ItsmeAga** [elysium-project/server#2241]
The Priest's Talent "Blackout" should only proc on the initial application of periodic spells, not on their ticks.

src:
http://wowwiki.wikia.com/wiki/Blackout?oldid=302004
Client spellfiles: Unlike Nightfall, Blackout is missing the "18 Deal periodic damage" procflag.
https://youtu.be/w7pP4ouSkqQ?t=146 (proc at application, is a bit delayed due to blizz's spellcasting system) and lots of other pvp movies where you won't see blackout proccing from periodic ticks

**Comment by GuybrushGit** [comment]
https://github.com/elysium-project/server/pull/2227

**Comment by ItsmeAga** [comment]
he said he only fixed it for positive spells, aka heals and suggest to remove the periodic proc system in the future
