### ISSUE TITLE
Blasted Land Buffs should give +50 stats until 1.11

### ISSUE THREAD

**Issue by BrynjaDarrow** [elysium-project/server#2242]
Blasted Land buffs "should give +50 to their respective stats instead of +25 until 1.11:

https://web.archive.org/web/20060407225314/http://www.thottbot.com:80/?i=6228
https://web.archive.org/web/20060222234625/http://www.thottbot.com:80/?i=5175
https://web.archive.org/web/20060314032014/http://thottbot.com:80/?i=6261
etc."

quote by fgsfdss in #2197

**Comment by GuybrushGit** [comment]
Will not be implementing this, see https://github.com/elysium-project/server/pull/3005
