### ISSUE TITLE
Deleted Character from Old Server that was removed

### ISSUE THREAD

**Issue by Toxic12990** [elysium-project/server#2249]
Hello, I just logged on after taking a large break due to work and travel and my character and Zeth'Kur was deleted, my friend mentioned that I was able to move it? But I never got the chance to do so. Is there anyway I can get there character back. I don't know if this is the right place to post this but thank you for the help.

**Comment by Sabre142** [comment]
Your character was transferred to Anathema. There is no way to transfer this to Elysium so if you want to play there you have to reroll.

**Comment by Toxic12990** [comment]
Thats what I thought, but she is not on Anathema.

**Comment by thepparker** [comment]
You'll have to make a post on the forums and get in contact with a community rep
