### ISSUE TITLE
Server crash 8/25 early am caused bugged quest NPC

### ISSUE THREAD

**Issue by tanknstein** [elysium-project/server#2251]
I finished ("(completed)" in quest log) the "In Dreams" quest right before the server crashed last night and just before I could right click on Trion to pick up the neck piece.  This morning the quest still shows "(completed)" in the quest log, but the quest NPC (Trion) is not offering the turn-in (no question mark).  Please fix the status of the NPC so that I can pick up the Mark of Fordring.  Thanks!

**Comment by thepparker** [comment]
You'll have to redo it or wait for someone else to do it and you'll be able to hand it in
