### ISSUE TITLE
Resurection sickness 23 days remaining

### ISSUE THREAD

**Issue by stivgmer** [elysium-project/server#2273]
please help my character kartoska has resurection sickness for 23 days!

**Comment by brotalnia** [comment]
If you die and ress from the spirit healer again it should be fixed.

**Comment by ItsmeAga** [comment]
ye the workaround does help, but its a bug since it shouldnt appear in the first place

**Comment by ItsmeAga** [comment]
this is still a bug that should be fixed, is there already another report for it? if not then don't just close it because it repeatedly appears...

**Comment by Mostprovidedlinks** [comment]
I hope its fixed
