### ISSUE TITLE
[Elysium] Arcane Missiles is missing a tick

### ISSUE THREAD

**Issue by ItsmeAga** [elysium-project/server#2275]
Arcane Missiles is missing a tick, using rank2 arcane missiles I randomly only get 3 ticks, should be 4.(did not get interrupted, was on range) Possibly affects other channeled spells too

**Comment by Cabro** [comment]
Confirm for bandages also. Sometimes i get 7 ticks instead of 8.

**Comment by luigimannoni** [comment]
Related to #1637

**Comment by sadfx** [comment]
Known about this since release. Really stupid bug. Just like https://github.com/elysium-project/server/issues/2312.
