### ISSUE TITLE
[Darrow] When passing Orgrimmar while flying you get flagged as Alliance

### ISSUE THREAD

**Issue by BrynjaDarrow** [elysium-project/server#2283]
When flying from Gadgetzan to Azshara, for example, you get flagged while passing Orgrimmar.
I might be imagining things, but I think this was fixed at some point? Not sure about that though.

Proof:
http://imgur.com/a/4lwq9

**Comment by GuybrushGit** [comment]
Fixed with https://github.com/elysium-project/server/commit/5d2e1eec92c855b4cb860cf4199a277925695a0b

**Comment by BrynjaDarrow** [comment]
Damn, you are so fast that you fixed the issue in -5 days :D
