### ISSUE TITLE
Darrowshire: Boneclenched Gauntlets

### ISSUE THREAD

**Issue by alex1156** [elysium-project/server#2287]
8/28/2017

The Boneclenched Gauntlets I have read as "404 Armor, +15 Strength, +14 Stamina, Equip: Increased Defense +7", however I noticed while taking them on and off repeatedly that they do not increase my strength, stamina, or defense at all. They only increase my armor and not my stats.

Is this item supposed to be like this, but showing up with something different? Is this an earlier patch and the item hasn't been adjusted yet? Is this a bug?

**Comment by BrynjaDarrow** [comment]
delete your WDB folder to see the real stats.

**Comment by QAkvastskaft** [comment]
These are the current stats of the item: https://web.archive.org/web/20050427225550/http://wow.allakhazam.com:80/db/item.html?witem=14525
