### ISSUE TITLE
Darrowshire: Deathbone Sabatons

### ISSUE THREAD

**Issue by alex1156** [elysium-project/server#2289]
8/28/2017

Another item that has been giving me issues is the Deathbone Sabatons. This items states that it gives "438 Armor, +9 Stamina, Equip: Restores 6 mana per 5 sec, Equip: Increased Defense +10".

The problem I am finding is that it does not appear to be increasing my Defense skill at all.

Thank you for your time.

**Comment by BrynjaDarrow** [comment]
it does not have +10 defense.
that's a later patch, delete your WDB folder.

**Comment by Kolmarwow** [comment]
Brynja is correct, the Deathbone set does not have any defense at all besides the chest. The Gauntlets/Belt/Legs/Boots are all crappy greens until patch 1.10, where they all become blue and get defense & mana regeneration.

**Comment by alex1156** [comment]
Okay thank you for your responses, I will delete that folder, I had no idea.
