### ISSUE TITLE
Build error Ubuntu 16.10 64bit

### ISSUE THREAD

**Issue by Daylien** [elysium-project/server#229]
Good evening everyone,

i want too build the Server on Ubuntu 64 bit 16.10. But i get some strange errors. I hope somebody can help me. Thanks !

> GCC Version 6.2.0
> Cmake Version 3.5.2

`[ 60%] Building CXX object src/scripts/CMakeFiles/scripts.dir/eastern_kingdoms/burning_steppes/blackwing_lair/boss_vaelastrasz.cpp.o
/home/builder/Projects/ElysiumServer/src/scripts/eastern_kingdoms/burning_steppes/blackwing_lair/boss_vaelastrasz.cpp: In member function ‘void boss_vaelAI::BeginSpeech(Unit*)’:
/home/builder/Projects/ElysiumServer/src/scripts/eastern_kingdoms/burning_steppes/blackwing_lair/boss_vaelastrasz.cpp:174:9: error: ‘m_uiSpeachTimer’ was not declared in this scope
         m_uiSpeachTimer = 10000;
         ^~~~~~~~~~~~~~~
/home/builder/Projects/ElysiumServer/src/scripts/eastern_kingdoms/burning_steppes/blackwing_lair/boss_vaelastrasz.cpp:175:9: error: ‘m_uiSpeachNum’ was not declared in this scope
         m_uiSpeachNum = 0;
         ^~~~~~~~~~~~~
/home/builder/Projects/ElysiumServer/src/scripts/eastern_kingdoms/burning_steppes/blackwing_lair/boss_vaelastrasz.cpp:176:9: error: ‘m_bIsDoingSpeach’ was not declared in this scope
         m_bIsDoingSpeach = true;
         ^~~~~~~~~~~~~~~~
src/scripts/CMakeFiles/scripts.dir/build.make:1190: recipe for target 'src/scripts/CMakeFiles/scripts.dir/eastern_kingdoms/burning_steppes/blackwing_lair/boss_vaelastrasz.cpp.o' failed
make[2]: *** [src/scripts/CMakeFiles/scripts.dir/eastern_kingdoms/burning_steppes/blackwing_lair/boss_vaelastrasz.cpp.o] Error 1
CMakeFiles/Makefile2:678: recipe for target 'src/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by m-laniakea** [comment]
Taken care of, please pull changes.
