### ISSUE TITLE
moonfiry Does not display final values

### ISSUE THREAD

**Issue by melris** [elysium-project/server#2298]
Good afternoon ,game world  elysium patch 1.6 ,  talent "moonfury"It does not show the final values given base damage talent 
https://vanilla-twinhead.twinstar.cz/?spell=8951
![rold](https://user-images.githubusercontent.com/30897780/29812551-0bcb32dc-8cb8-11e7-9c02-fbb31afd81a4.png)
![prof](https://user-images.githubusercontent.com/30897780/29812569-18c5b2f0-8cb8-11e7-8303-6f54439570dd.png)
![667](https://user-images.githubusercontent.com/30897780/29812572-1d81bf50-8cb8-11e7-99ec-f0d272307228.png)

**Comment by GuybrushGit** [comment]
Tooltips are client side. The talent is working.
