### ISSUE TITLE
It's not possible to get multiple spell procs from cleaving

### ISSUE THREAD

**Issue by ohganot** [elysium-project/server#2299]
Issue: Currently, when you whirlwind or cleave, you can only proc one damage spell e.g. Darkmoon Card: Maelstrom, Thunderfury or Deathbringer shadowbolt. 

How it's supposed to work
- Whirlwind/Cleave can proc spells on each target hit
- All spell damage procs from whirlwind/cleave hits will release instantly on the respective targets they procced from

Proof: 
https://www.youtube.com/watch?v=apgkI-0tOB4
0:30 2 Thunderfury procs from Cleave

**Comment by thepparker** [comment]
1: WF proc, gets extra hit. Looks like TF procs from that. Cleave comes after and only procs TF once, not really conclusive
2: WW hits 2 targets, gets 2 spec procs- looks like it confirms that WW at least can proc multiple extra attacks. Now it depends on the patch level and whether this was changed like other multi proccing abilities

**Comment by ohganot** [comment]
Looks like AQ patch or pre-patch, since later on in the video he can be seen PvPing in silithus and you can see people farming Twilight Hammer mobs and elite bugs.

**Comment by ohganot** [comment]
Also, found a better example from the thunderfury video for Cleave + 2x Thunderfury Proc.

https://www.youtube.com/watch?v=apgkI-0tOB4 0:35
You can see he does 1 cleave, nothing else, and 2 thunderfury procs happen.

**Comment by Imbaslap** [comment]
sword spec was changed to only proc on "on next attacks" and white auto attacks (slam as well) in TBC.
in vanilla it can proc off all instant yellow attacks, including cleave/WW.  the currently targeted mob/player will be hit with the extra attack proc.  this is a vanilla only mechanic that gets nullified in TBC when changed in patch 2.1/2.2. same case for Mace spec.   in the video linked where Sword spec procced twice, if you calculate the damage from the player before the attack and after, it did enough to kill him from 33% to 0 in those 3 hits (1 from WW and 2 from sword spec procs)  no damage was shown on the pet who received the WW secondary hit, the white damage scrolling text hovered over where the current target was. 

TF and other procs do not proc from secondary targets hit by cleave/ww.
the video posted by Ohganot with TF was back when TF could proc off itself and extra attacks in 1.6. (the old pre nerf TF proc chance) and is not a reliable source for video footage.

**Comment by Imbaslap** [comment]
Sword Specialization: This talent’s free extra attacks can no longer trigger additional extra attacks.
http://wowwiki.wikia.com/wiki/Patch_2.2.0

the extra sword spec attack is from sword spec proc (1st one) not from whirlwind.

**Comment by ohganot** [comment]
Good find. My evidence is no longer valid for the extra attacks, but it should still be possible to proc multiple spell type attacks from cleaving.

0:30 https://www.youtube.com/watch?v=Ttbfhwv84EY

You gain 1 extra attack through Windfury Attack.
You crit Bronze Drakonid for 539.
Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.
Your Cleave crits Bronze Drakonid for 613.
Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.
Your Cleave crits Bronze Drakonid for 713.

Slow it down and watch frame by frame.
The Windfury attack happens before the cleave and doesn't proc Thunderfury.
The two Thunderfury procs were triggered by cleaves. The second Thunderfury also procced from cleave, otherwise the combat log order would have looked different.

Throughout the video you can see these combat log orders of thunderfury procs:

1) 1st Thunderfury procs from cleave and 2nd Thunderfury procs from 1st Thunderfury

Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.
Your Cleave crits Bronze Drakonid for 613.
Your Cleave crits Bronze Drakonid for 713.
Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.

2) 1st Thunderfury procs from cleave and 2nd Thunderfury procs from 1st Thunderfury

Your Cleave crits Bronze Drakonid for 613.
Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.
Your Cleave crits Bronze Drakonid for 713.
Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.

Based on these two examples, this combat log order has to mean that 2 Thunderfuries both procced from cleave.

Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.
Your Cleave crits Bronze Drakonid for 613.
Your Thunderfury hits Bronze Drakonid for 300 Nature Damage.
Your Cleave crits Bronze Drakonid for 713.

**Comment by Imbaslap** [comment]
http://forum.nostalrius.org/viewtopic.php?f=24&t=703
Patch 1.9
Jan 2,2006– (day before patch) – Thunderfury Proc Rate Nerfed, and Cannot Proc off itself and other damage effects ( poisons, trinkets, enchants etc).
Q. “Actual proc-rate are not lowered, except on Thunderfury…..they changed it so that On Next Swing abilities don’t have a chance to proc twice on hit (like they do now), and so that you can’t proc off a proc.”
Source: http://wow.allakhazam.com/forum.html?forum=21&mid=1136245524240202932#10

Cleave = On Next Swing ability.
Video posted is from @ohganot is during patch 1.6.
