### ISSUE TITLE
Hardened Stone Band shouldn't be a world drop

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#2308]
This ring should only drop from Avalanchion in Elemental Invasions.

Source: http://web.archive.org/web/20060307021428/http://wow.allakhazam.com:80/db/item.html?witem=18674

**Comment by Kolmarwow** [comment]
Same with a few other similar items that are supposed to be elemental invasion specific. 

[Frigid Ring](http://web.archive.org/web/20051130220215/http://wow.allakhazam.com:80/db/item.html?witem=18679) should only drop from Princess Tempestria 

[Elemental Ember](http://web.archive.org/web/20070919125428/http://wow.allakhazam.com:80/db/item.html?witem=18672) should only drop from Baron Charr

And the [Zephyr Cloak](http://web.archive.org/web/20071030081118/http://wow.allakhazam.com:80/db/item.html?witem=18677) should only drop from the Windreaver, though I think that this one is working as intended.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
