### ISSUE TITLE
Tarantulas in Loch Modan have too much health

### ISSUE THREAD

**Issue by sadfx** [elysium-project/server#2311]
"Tarantulas in Redridge Mountains has too much health" this appears to be a common thing among spiders.. 

Level 18 ones have like 800 HP..

**Comment by GuybrushGit** [comment]
There are no level 18 tarantulas. Level 14 ones were already fixed.

**Comment by BrynjaDarrow** [comment]
There are level 18 tarantulas in Loch Modan, they are called Cliff Lurkers and have indeed somewhere around 800 HP, which is way too high.

The Stonesplitter Diggers, who are close in that area and also level 18 have around 400 HP.

Proof:
http://i.imgur.com/OSPYMOM.jpg
