### ISSUE TITLE
Torn Bear Pelt WRONG Item Quality 

### ISSUE THREAD

**Issue by sadfx** [elysium-project/server#2316]
Torn Bear Pelt (http://db.vanillagaming.org/?item=11407) is a quest item and should be a common quality item, not junk.

Source: https://web.archive.org/web/20071101014044/http://wow.allakhazam.com:80/db/item.html?witem=11407

**Comment by Oudeis1447** [comment]
With that link you can clearly see that the pelt is grey prior 2007 and white after 2007 so it got change in TBC. We are not in TBC.

**Comment by some2** [comment]
Your source is from 2007 (BC).

In June 2016 (and older) it were grey.


https://web.archive.org/web/20060614131302/http://wow.allakhazam.com:80/db/item.html?witem=11407

**Comment by sadfx** [comment]
It's a quest item. Quest items are white/common. http://wowwiki.wikia.com/wiki/Quest:Torn_Bear_Pelts Added in 1.6. Stop defending errors.

**Comment by luigimannoni** [comment]
@sadfx that is not necessarily true. 
Torn Bear Pelt wasn't added in 1.6 and was in the game before the Darkmoon quest has been added, same thing goes for the Small Furry Paw item which used to be gray (later turned white in-game, and currently white on Elysium).

The change happened somewhere between Vanilla and BC, can clearly remember that but can't pin point a patch or a blue post where this was mentioned.

Either way, the request makes sense.

**Comment by sadfx** [comment]
Luigi I couldn't care less whether it was actually white or grey on retail in this content patch, it would be silly to not correct a mistake for the sake of "accuracy" when we know what route Blizzard took - they fixed it. This is not something with major gameplay implications, but it really messes with those who'd like to keep the item but use addons designed to sell junk.

**Comment by luigimannoni** [comment]
You won't go far with that attitude, son.

Since all developers are actually working for free to give you some hours of fun and I can't care less about your shitty addon selling your beloved quest items, [why don't you fix it yourself?](https://github.com/elysium-project/database/tree/master/new_progression)

**Comment by sadfx** [comment]
I was referring to idiotic comments like "With that link you can clearly see that the pelt is grey prior 2007 and white after 2007 so it got change in TBC. We are not in TBC." being silly, not that I expect any fixes.

**Comment by Maduse** [comment]
Some things was a bit cumbersome on retail and was changed later on (most often made easier) by Blizzard, but where do you draw the line on what to "fix" and how to do it? I think most people want the real deal and will accept things for how they acctually were.

**Comment by some2** [comment]
Maybe you should add a source which indicates that "Torn Bear Pelt" was a grey item at vanilla times. (As recommended in [bug reporting guidelines](https://github.com/elysium-project/server/blob/development/docs/ISSUE_TEMPLATE.md))

Otherwise, probably no one will change this.
