### ISSUE TITLE
Call pet/dismiss pet BUFFS / DEBUFFS

### ISSUE THREAD

**Issue by knasen88** [elysium-project/server#2320]
Since you literal sadists decided to remove /run PetDismiss() BEFORE FIXING THE REGULAR DISMISS PET SPELL http://db.vanillagaming.org/?spell=2641 hunters can no longer utilize any buffs at all on pets in raids due to the constant dismiss/call pet.

FIX DISMISS PET REMOVING BUFFS/DEBUFFS #470 

or lets all reroll warriors because that's appearantly the only class devs wants us to play.

**Comment by Phibs77** [comment]
> or lets all reroll warriors because that's appearantly the only class devs wants us to play.

qft.
