### ISSUE TITLE
Traveler's Backpack

### ISSUE THREAD

**Issue by kev41** [elysium-project/server#2330]
[Traveler's Backpack](http://db.vanillagaming.org/?item=4500) should turn soulbound when you use it.

I have no source for this at the moment, but I remember 100% that if you rightclick it or drag it to the bagslots you need to accept that it will turn soulbound.

Atm it is not soulbound in any kind of way, even if you have it on your bagslots since long time.

**Comment by Kolmarwow** [comment]
https://web.archive.org/web/20070813114151/http://wow.allakhazam.com:80/item.html?witem=4500

allakhazam comments from 2005-2007 seem to all say that Traveler's Backpacks have always been free of soulbinding.

**Comment by Kittnz** [comment]
Always has been free of soulbinding.

**Comment by Maduse** [comment]
I don't remember it ever beeing BOE.

**Comment by kev41** [comment]
My bad, thanks for the source @Kolmarwow
