### ISSUE TITLE
[9382] Tromping Miner's Boots

### ISSUE THREAD

**Issue by kolokotrolis** [elysium-project/server#2331]
Currently these are a world drop.According to https://web.archive.org/web/20050920034357/http://wow.allakhazam.com:80/db/item.html?witem=9382 they should only be dropping from Digmaster Shovelphlange in Uldaman with a 65% drop rate.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
