### ISSUE TITLE
Nerubian Slavemaker (3.4 instead of 3.2 Speed with Source)

### ISSUE THREAD

**Issue by Dasharius** [elysium-project/server#2334]
While Nerubian Slavemaker got buffed with Patch 2.0.x it also got it's weapon speed increased to 3.2.

The 57.2 dps version should have **3.4 Speed with 136-253 Damage** (Source below!). With the current stats Nerubian Slavemaker isn't a Endboss worthy weapon in any way and only as good as Soulstring. But even with 3.4 Speed Blizzard realized it was undertuned and with 2.0.x they patched it up to 67,5 dps. In Vanilla with 1.12 talents/spells Hunter's aren't overpowered in any way you could also consider to just fix it to 67,5 dps. Endboss loot always was something very powerful and especially Kel'Thuzad ist the last Boss in the entire Vanilla Experience. After that, it's only about TBC and it should IMO have TBC stats already. But back to my Speedfix.

Slavemaker now:
57,2 dps, 24 AP, 1% Crit
128 - 238 Damage (avg 183)
3.2 Speed

Soulstring:
60,7 dps, 16 AP, 1% Crit
123 - 229 Damage (avg 176)
2.9 Speed

Slavemaker new:
57,2 dps, 24 AP, 1% Crit
136-253 Damage (avg 194,5)
3.4 Speed

The story that hunters want a slow weapon isn't entirely true. It's more(not only) about Avg Weapon Damage and Slow weapons tend to have more Avg Weapon Damage. Around 40-50% of a Hunters overall Raid damage is based on Multishot and Aimed Shot. These skill's scale apart from RAP also 100% of Avg Weapon Damage. Faster shooting Ranged Weapons allow for a tighter Rotation Cycle. So the marginal upgrade of only 7 avg Weapon dmg is nonexistent because with Soulstring you have a faster cycle to compensate it.

The 3.4 speed version however would be better than Soulstring instead of equivalent.

Source:
http://forums.goha.ru/showthread_0_0_t77939
07.06.2006, 13:34
Nerubian Slavemaker - Xbow - 136-253, 3.40, 57.2 dps, +24 AP, +1% crit

**Comment by BrynjaDarrow** [comment]
I think buffing the damage from 57,2 DPS to 67,5 DPS (which it got in the 2.0.x patch, like you said) makes even more sense.
It seems clear that the fact that a weapon that drops from KT has lower DPS than a weapon that drops from  the 4HM was an oversight. Look at ALL the other weapons KT drops, their DPS is waaaaaaay higher than the DPS over all the other weapons that drop in Naxx & the fact that Blizz changed the DPS soon after shows that the initial 57,2 DPS were indeed a mistake.

**Comment by GuybrushGit** [comment]
It was changed to 3.2 while still in vanilla
http://wowwiki.wikia.com/wiki/Nerubian_Slavemaker?oldid=233043
http://web.archive.org/web/20061109035926/http://www.thottbot.com:80/?i=53981

**Comment by BrynjaDarrow** [comment]
Man, Blizz really didn't know what they were doing.

So they nerfed it from 1.11 -> 1.12 by making it 0.2 faster and then buffed it by 10 DPS from 1.12 -> 2.0.
This ist just next level retarded.

**Comment by Dasharius** [comment]
My link (07.Jun.2006) predates 1.11 (20.Jun.2006) by 13 days while your links
are even after 1.12 (20.Aug.2006)
wowwikia is September 2006
thottbot is in Nov 2006

So while Spells are all 1.12 even if it doesn't make any sense, item progression is considered.

I can only argue about that Blizzard changed Nerubian Slavemaker DPS with 2.0.x. I can't find (maybe my fault) any other weapon to be buffed in DPS with 2.0.x.

It also should be logical that a weapon of the last boss of Vanilla should be more powerful than anything before. I already stated this before.

So it seems that it was slightly stronger than anything else with the release of 1.11 (3.4 Speed)
Blizzard seems to have seen that it was still not good enough and wanted to change it to 67,5 dps and 3.2 speed but fucked up and only changed the speed. The weapon dps fix went live 4 months later with 2.0.x.

**Comment by Lurkkihunter** [comment]
Not only is the speed on Nerubian Slavemaker wrong, the damage / dps on Soulstring is also from 2.0 patch when they buffed all ranged weapons' dps. Correct stats: http://wowwiki.wikia.com/wiki/Soulstring?oldid=233118

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
