### ISSUE TITLE
Skeletons without correct immunities: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#234]
4 skeleton type mobs are not included in the list #124 .
These 4 mobs should have the same immunities as all other skeletons.

Original post on bug tracker here:
https://elysium-project.org/bugtracker/issue/1862
https://elysium-project.org/bugtracker/issue/1878
https://elysium-project.org/bugtracker/issue/1872
https://elysium-project.org/bugtracker/issue/1866

**Comment by shmigy429** [comment]
Updated these units immunities to the new mask at #254

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/43686-development-update-05042017/
