### ISSUE TITLE
Pet buffs removed on dismiss / pet running out off range

### ISSUE THREAD

**Issue by Tubbyqt** [elysium-project/server#2344]
Since server release this has been incorrect. In vanilla wow you kept your buffs on pet (ony + jujus + raid buffs) if you decide to dismiss pet and then recalling it.
People went around the problem by using the instant pet dismiss since it kept buffs, as it should be.

However that macro is now gone and the issue still remains, pets should keep buffs after dismiss.
Can some GM at least reply about the topic? 
The issue has been since launch it is about time that you look into the problem......

https://www.reddit.com/r/ElysiumProject/comments/6wynrh/hunter_pets_losing_buffs/

**Comment by Haiwuu** [comment]
https://github.com/elysium-project/server/pull/2324

Its being addressed in the future hopefully

**Comment by thepparker** [comment]
Duplicate
