### ISSUE TITLE
ZG coins

### ISSUE THREAD

**Issue by smkrus** [elysium-project/server#2345]
Suspect imbalanced drop rates of some ZG coins.

**Comment by Phoosy** [comment]
https://github.com/elysium-project/server/blob/development/docs/CONTRIBUTING.md

**Comment by smkrus** [comment]
They should drop in equal rates... suspect they do not. Can you check into it... that simple?

**Comment by Mostprovidedlinks** [comment]
Can someone check if drops are correct ty
