### ISSUE TITLE
Polymorph regenerates health too fast: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#235]
BUGGED BEHAVIOR
Currently polymorph regerenates health too fast.

 CORRECT BEHAVIOR
it should only regenerate 10%/sec, should also be affected by healing reduction effects.

 SOURCES
https://youtu.be/X7HJlsZGCm8?t=15m38s - Warrior with Blood Fury debuff, ticks for 5%/sec.

https://youtu.be/VNgGCGl0_S0?t=4m24s - Ticks for 10%/sec.

COMMENTS from QAKvastskaft:
Current rate seems to be ~20-25% per sec which is very much to high

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/2468

**Comment by StadenElysium** [comment]
Addressed in https://github.com/elysium-project/server/commit/d66b716882c91e737116b4d1595ec20af9087419.

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/43686-development-update-05042017/
and https://forum.elysium-project.org/topic/44683-development-update-19042017/
