### ISSUE TITLE
Cured heavy leather stack issues #1881

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#2365]
First of all, thank you for taking the time to report this issue.

Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. You should open a ticket
in game and wait for the response of a gamemaster. They may redirect you to this
bug tracker if they believe there's a server issue that they cannot help you
with.

Before writing your report, please do read and consider the following points to
increase the quality of your report.

- Search the issue tracker for open and closed issues before opening a new
  issue. You may be able to contribute additional facts by commenting on
  existing issues instead of adding extra noise in a separate issue.

- http://www.wowhead.com/ and http://db.vanillagaming.org/ are not valid sources
  for quests, items etc., instead, please use archived versions of
  http://wow.allakhazam.com or http://www.thottbot.com through
  https://archive.org/.

- Validate the date and time of the archived sources to a certain patch. The
  patch release dates can be found on the corresponding WoWWiki article, as
  found at http://wowwiki.wikia.com/wiki/Category:World_of_Warcraft_patches.

- Videos are valid if and only if the footage contains a timestamp or
  information that confirms the time it was recorded. Date of upload is NOT
  valid and does not confirm when it was shot.

- Read the Effective Bug Reporting article at
  https://github.com/elysium-project/server/blob/development/docs/CONTRIBUTING.md
  which covers these points and more.

Once you've read this message, delete it and write your report below.

--

Write your report here

Correct relating to what? Evne if it is correctly implemented the way Blizzard did it back in the days it still makes no sense: Cured light hides 20 stacks, cured medium hides 20 stacks, cured heavy hide 10 stacks(?!) cured thick hide 20 stacks cured rugged hide 20 stacks. Isn't this kinda odd...? Don't you think maybe Blizzard got it wrong there or one of the databases is wrong here? I don't want to argue and go on your nerves. I'm just pointing out the curious irregularity ;)

**Comment by Phatcat** [comment]
https://web.archive.org/web/20060526181918/http://wow.allakhazam.com:80/db/item.html?witem=4236

https://web.archive.org/web/20060827205947/http://wow.allakhazam.com:80/db/item.html?witem=4233

You're right, indeed it lists it as 10-stackable while the others seem to be stackable in 20s... Either indeed it is an error on blizzards part, in which, what's the policy elysium? Leave it? - or it may be intentional in which case I guess the hint as to why you can't carry as many of them is in the name.

**Comment by Phatcat** [comment]
Also everything above the -- line in the issue report is supposed to be deleted, you're not supposed to include the 'message to the reporter', in the report..

**Comment by Phatcat** [comment]
I should learn to double check before doing a comment; they are all supposed to stack in 10s before a certain patch, here's a link showing medium hides only in 10 stacks as well; https://web.archive.org/web/20060114185744/http://wow.allakhazam.com:80/db/item.html?witem=4233

the question now becomes, in which patch did this change?

**Comment by Phatcat** [comment]
before patch 1.7.0 cured rugged hides only stacked 5; http://wowwiki.wikia.com/wiki/Patch_1.7.0

        Cured Rugged Hides now stack to 10 instead of 5. 

I found it, it was in patch 1.11 they went from 10 to 20; http://wowwiki.wikia.com/wiki/Patch_1.11.0

        Stack sizes have been updated:
        Stacks of 20
        Leather (Light, Medium, etc.)
        Cured Hides (Light, Medium, etc.)
        Shards (Small Brilliant, etc.)
        Enchanting Dusts (Strange, Illusion, etc.)
        Flash Powder
        Rogue Poisons (Instant, Crippling, etc.)
        Rogue Poison Reagents (Essence of Pain, Deathweed, etc.) 

        Stacks of 10
        Hides (Light, Medium, etc.)

**Comment by Phatcat** [comment]
@shenna-elysium - This here is for you since this is itemization stuff.

**Comment by Pisshead** [comment]
Oh ok sorry about including the text of the template. I must have overread that. Which patchi s running currently on Elysium? Isn't naxxramas the newest? like 1.13 or something. Thanks for everything

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
