### ISSUE TITLE
Fire Damage Radius

### ISSUE THREAD

**Issue by Meiji1993** [elysium-project/server#2366]
Radius of damage from campfires, braziers etc. worldwide is too large. NPCs can be seen safely standing within that fire radius and not taking damage, whereas players get hit even when they are standing a fair distance away.

Correct behaviour is to only cause fire damage to the character if they are standing directly on top of the fire.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
