### ISSUE TITLE
Arcane Concentration Issue

### ISSUE THREAD

**Issue by Theavskum** [elysium-project/server#2367]
Im having issues with with proccing arcane concentration on my mage with blizzard spell. I am the only one ive heard about whos had this issue. i can proc arcane concentration with the activation of blizzard, but i cannot procc it with the hits from blizzard. this completely deletes my ability to aoe farm which mages are supposed to do. i wrote a ticket but i was asked to report it in here instead. please respond to me. ive been having this issue since launch.

**Comment by Haiwuu** [comment]
If  you have any evidence of arcane concentration proccing per hit, please present it, the spell was changed to per cast.

**Comment by Theavskum** [comment]
http://db.vanillagaming.org/?spell=12577

"Gives you a 10% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%"

everyone else i talk to can proc it off blizzard, thats how u aoe farm. im the only one who cant.

**Comment by GuybrushGit** [comment]
Working as intended.

**Comment by thepparker** [comment]
Periodic spells do not proc Clearcasting on tick
