### ISSUE TITLE
Heart of Wyrmthalak trinket proc rate seems to be quite low

### ISSUE THREAD

**Issue by theloras** [elysium-project/server#2370]
Heart of Wyrmthalak
Binds when picked up
Unique
Trinket	
Requires Level 56
Equip: Chance to bathe your melee target in flames for 120 to 181 Fire damage.
http://db.vanillagaming.org/?item=22321

I don't have the trinket myself but a few Paladins on Anathema have told me that it's proc rate is abysmally low in a similar fashion as Darkmoon Card: Maelstrom used to be before I got the devs to fix it:

Darkmoon Card: Maelstrom proc rate is abysmal on Elysium - RESOLVED
https://elysium-project.org/bugtracker/issue/820

**Comment by GuybrushGit** [comment]
http://web.archive.org/web/20071225161237/http://thottbot.com:80/i22321

**Comment by theloras** [comment]
@GuybrushGit - that link suggests a 2% to 5% proc rate - what is it set at currently on anathema?

**Comment by GuybrushGit** [comment]
1 ppm on dev

**Comment by QAkvastskaft** [comment]
1 ppm seems consistent with the source
