### ISSUE TITLE
Claw of the Black Drake: Missing critical strike chance (Elysium)

### ISSUE THREAD

**Issue by kyle21b** [elysium-project/server#2375]
The Claw of the Black Drake that drops from Firemaw is missing its critical strike chance.

The current stats are:
+13 str 
+7 stam

The correct stats are:
+13 str
+7 stam
Equip: Improves your chance to get a critical strike by 1%.

Here is the earliest archive i can find of the stats: http://web.archive.org/web/20060328111610/http://www.thottbot.com/?i=44756

**Comment by BrynjaDarrow** [comment]
This issue was already opened on the database directory. 

Here is my annotated version of that archive-link:
http://i.imgur.com/1NosAWp.jpg

**Comment by Maduse** [comment]
This item already has the +1% to crit in the DB. I can't see any changes recently, so maybe you need to delete your WDB folder.

**Comment by BrynjaDarrow** [comment]
It has 1% on Darrowshire, but misses it on Elysium.

**Comment by GuybrushGit** [comment]
Fixed with new progressive database.
