### ISSUE TITLE
Mindthrust Bracers, Incorrect Stats

### ISSUE THREAD

**Issue by Meiji1993** [elysium-project/server#2378]
Current stats: +9 intellect

Correct stats: -5 Stamina, +9 Intellect

**Sources:**
https://web.archive.org/web/20070510201141/http://www.thottbot.com:80/?i=11136

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/847-shadow-fang-keep-guide.html

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
