### ISSUE TITLE
Linken's boomerang never stunning/disarming: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#238]
BUGGED BEHAVIOR
Iinken's boomerang from Linken quest chain does not ever stun enemies.

 CORRECT BEHAVIOR
It should have chance to stun/disarm.

 SOURCES
Item description
http://db.vanillagaming.org/?item=11905#wh-comments

Original post on bug tracker here:  https://elysium-project.org/bugtracker/issue/1538

**Comment by StadenElysium** [comment]
Tested and it works. Proc rate is just low.

**Comment by StadenElysium** [comment]
Increased proc rate for stun to 10% based on some old comments. Not a good source of information but they're an improvement over the 3% with no backing.

https://github.com/elysium-project/server/commit/095bd19c6a521e0b928e43da1e09a1b0e432b086
