### ISSUE TITLE
Legacki in Winterspring is not there

### ISSUE THREAD

**Issue by MrRekmar** [elysium-project/server#2389]
Iam on the Quest " Are We There, Yeti" (3) and i have to scare Legacki in Everlook Winterspring but the NPC is not there or he dies instantly if he respawn.

**Comment by Spionida** [comment]
Realm would be useful

**Comment by BrynjaDarrow** [comment]
Apparently Legacki and the other goblins in this quest chain can get feared far away from their initial spawn point. 

Try riding around the vicinity while spamming the following macro. I heard she runs sometimes as far as the frozen lake...:
/script TargetByName("Legacki", true);

**Comment by Spionida** [comment]
True, gets into many places. Ticket gets her reset. Maybe a bug why she can't find her way home.
