### ISSUE TITLE
Noble Deaths (Rep bug)

### ISSUE THREAD

**Issue by stevemcdjr** [elysium-project/server#2393]
Server: Elysium PVP 
Patch: ?

The quest 'Noble Deaths' says that it gives 250 Rep to Alliance, however upon completing the quest, I noticed that it did not increase my Darnassus Reputation. I was unable to verify if I received any rep at all as I only track my Darn rep.

The Alliance Rep reward is verified by the following 
http://db.vanillagaming.org/?quest=512

**Comment by GuybrushGit** [comment]
Other private servers are not a valid source. Quest rewards Stormwind rep: http://web.archive.org/web/20070509172813/http://www.thottbot.com:80/q512

**Comment by stevemcdjr** [comment]
Fair enough. Then the blue text when you completed the quest still needs fixed to say, "+250 SW Rep" not "+250 Alliance Rep".

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
