### ISSUE TITLE
Tonk Control Console (Darkmoon Faire)

### ISSUE THREAD

**Issue by Meiji1993** [elysium-project/server#2395]
Should be located in Darkmoon Faire, both Elwynn and Mulgore.

Steam tonks do not spawn once tonk control console is opened. Control console despawns after being used once (which is incorrect, they should be permanant).

Intended action: Spawns steam tonk in your control with moves cannon and nitrous boost. Can only damage other steam tonks.

_________________________________________________________

https://www.youtube.com/watch?v=vrjIfeb0PuQ&feature=youtu.be&t=47

is an old timestamped videos proving the tonks were there and showing them moving and using the cannon.

The objects that should summon them are already in the game, however upon being clicked do not summon the tonk under your control. Object is:
http://www.thottbot.com/spell=45257/using-steam-tonk-controller

note it "summons: steam tonk"
which shows its abilities here:
http://www.thottbot.com/npc=19405/steam-tonk#abilities

I am aware that the last link has been merged and the 2.2.0 "added" patch listed, however the first video I linked pre-dates that and shows they were in game at the faire (note, the controllers spawn at both goldshore and thunderbluff locations when faire is on).

Hopefully these links have enough information about auras and abilities.

____________________________________________________________

1 ::: How to Obtain the device
Is it working as intended?

2 ::: Functionality
Unlimited Use or Limited (if so how many)
What's the cooldown to place a new Steam Tonk

3 ::: Stats
Health of the steam tank
Damage (of its abilities)

4 ::: Cooldown timers
Of various abilities, is it currently blizzlike?
If we view the 2006 source http://wow.allakhazam.com/forum.html?forum=21&mid=1141900110220338669&h=50 we get a good idea about these tonks. Below is summed up all the information I could gather on the website.

You obtain the tonk by clicking the Tonk Control Console. This controller opens up and presents joysticks.
https://www.wow-freakz.com/img/screenshots/wowhead.php?id=97482&s It looks exactly like this and the source describes it this way.

i found a Tonk Control Console. it looked like a small silver box with gold trim. activating it opened up a small joystick and control panel, and changed my point of view to what looks like a miniature steam tank!
The consoles should just be standing around while the event is in town. Anyone can use them and they are permanent. On our website, we have 14 locations which mean 14 possible players can control the tonks at one time.

The new (as of Patch 1.10) Dwarven-made Steam Tonks of the Darkmoon Faire are a huge success. Players can get to a control panel anywhere on the faire, and control a little, steam tank like tonk. With this Tonk, you can only attack other Tonks, not players. In short, Tonks are a cross between the safety of a duel and the multiplayer madness of a battleground. Note: They dismiss your pet when used.
After clicking the the controller you begin to control your tonk. If you tonk dies or you cancel then the tonk explodes. You are back to your character and receive a three-second stun debuff.

Tonk HP = 200. Tonk mana = 100.

Each tonk has three mandatory abilities and one randomly generated ability. Click the links for more information on their cooldowns etc.

Every tonk has these abilities.
- Mortar. Fires a mortar which lands 25 yards away dealing 35 to 46 damage to all tonks within 5 yards.
- Cannon. Fires a cannon round at the nearest tonk in front of you within 20 yards. Deals 18 to 23 damage.
- Nitrous Boost. 10 mana per second. Increases movement speed by 50%.

The fourth random ability can be one of the following:

- Drop Mine. Deploys a Tonk Mine. Mines take 3 seconds to arm and deal 35 to 46 damage to all tonks in a 2 yard radius once triggered.
- Activate MG Turret. Automatically fires a shot at the nearest enemy tonk within 10 yards every 1 sec, dealing 2 to 5 damage per shot.
- Flamethrower. 10 mana per second. Deals 18 to 23 damage every 1 sec to all tonks in front of you within 5 yards. Also slows movement to 20% and deals 5 damage per second for 2sec.
- Shield Generator. Protects you with a mana shield which can absorb up to 50 damage. Two points of mana are drained per point of damage taken.

We know these are correct as the 2006 comments explain about these abilities, confirming they exist in 2006 and some information on how they work and the damage they deal.

________________________________________________________________

I've reported this bug to every vanilla server I've been a part of for years in the hope that through various projects' efforts one day I'll be able to play with these on a vanilla server again. They were a big part of the faire for me and many others, and were extremely fun.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
