### ISSUE TITLE
Deviate Fish HoT , Razorlash Root,  Diamond Flask and bloodfang bonus set should scale at 100% healing

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#2396]
(6) Apply Aura #8: Periodic Heal is known to benefit from + healing
http://db.vanillagaming.org/?spell=15229 (jamaz's video shows it scaling at 100% over 15 seconds)

1. The HoT from Deviate Fish should be affected by 25% per 3 second tick 
http://db.vanillagaming.org/?item=6522

http://wowwiki.wikia.com/wiki/Deviate_Fish
https://wow.gamepedia.com/Deviate_Fish
Rejuvenation - rank 4 of the druid buff by the same name, heals your character by 45 points every 3 seconds for 12 seconds.

The reason it should be affected by healing is mostly because the heal is thesame as crystal restore which is a 100% coefficient over 15 seconds shown in Jamaz's video and second because druid rank 4 rejuvenation also scales at 100% overtime.

Jamaz video
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=5m45s
https://github.com/elysium-//issues/603

---------

2. Razorlash Root (this is the same as crystal restore)

http://db.vanillagaming.org/?item=17747
and should go 10% on coefficient per second

---------------------------

3. Diamond Flask and the bloodfang set have thesame heal aura
http://db.vanillagaming.org/?spell=23580
http://db.vanillagaming.org/?spell=24427

All of their healing over time are identical to crystal restore and should benefit from +healing

Please fix

Jamaz's video is a good source which shows that
6) Apply Aura #8 HoTs are affected by +healing

Second source states on multiple pages that deviate fishes HoT is rank 4 rejuvenation meaning that scales too. The others are identical.

Note: This does not apply to channelled spells. Jamaz video proves Periodic Heal scales only.

**Comment by GuybrushGit** [comment]
No sources + 500 title changes. Another great bug report. 👌

**Comment by Mostprovidedlinks** [comment]
Sources show they are identical healing spells and all work thesame way.

Are we going to throw away the fact that mark of the wilds has thesame spell type as buffs that cant stack with resistance potion. While it says on wowikki it does stack with resistance potion.

Elysium chose to prevent it stacking because of thesame spell aura type. 

All of these items in the database have thesame non channelled HoT as crystal restore 6) Apply Aura #8 which benefits from healing in Jamaz video.

There if we dont accept that. Change mark of the wild so it stacks please or fix this.

**Comment by Mostprovidedlinks** [comment]
Jamaz's video is a good source which shows that
6) Apply Aura #8 HoTs are affected by +healing

Second source states on multiple pages that deviate fishes HoT is rank 4 rejuvenation meaning that scales too. The others are identical.

**Comment by Mostprovidedlinks** [comment]
Yes I change the title for your needs. To make it easier for people to read. Its not intended to be bad.

**Comment by Mostprovidedlinks** [comment]
I had to add the other items too which is why I made title changes. I bothered adding them so people would be less confused because I care about others.

**Comment by Mostprovidedlinks** [comment]
I could of not changed the title and made it harder for you to read. Youd be thinking. Why are all these items here? When he just said one of them

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit please guybrushgit if you can help put these in misc too thanks

**Comment by sauronn** [comment]
Nice report, ty

**Comment by Itembugs** [comment]
All have identical effects

**Comment by Mostprovidedlinks** [comment]
@guybrushgit the source is jamaz's video 

All those items have thesame spell

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit the source is jamaz's video

All those items have thesame spell and we already know rank 4 rejuvenation which has a 100% coefficient
Is thesame spell from a druid just as shadow bolts from oils and trinkets are affected by spell damage

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit the source is jamaz's video

All those items have thesame spell and we already know rank 4 rejuvenation which has a 100% coefficient
Is thesame spell from a druid just as shadow bolts from oils and trinkets are affected by spell damage


yum yum fish

Posted: Oct 22nd 2007 11:44am | IP: Logged |  Reply to this

Icetongue

8 posts

Score: Decent 

Eating a deviate fish will have a random effect on your character. Possible effects include: 

* Healthy Spirit - increases your character's spirit by 5 points for 30 minutes. 
* Invigorate - instantly heals your character 383 to 517. 
* Party Time! - a magic debuff that causes the character to perform random emotes for 2 minutes. Your character will /clap, /cheer, /chicken, /lol, or /dance every 10-15 seconds, possibly interrupting spells or other actions. 
* Rejuvenation - rank 4 of the druid buff by the same name, heals your character by 45 points every 3 seconds for 12 seconds. 
* Shrink - a curse debuff that reduces your character's apparent size, as well as their strength and stamina, for 2 minutes. 
* Sleepy - a magic debuff that sleeps your character for 30 seconds.

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit the source is jamaz's video

All those items have thesame spell and we already know rank 4 rejuvenation which has a 100% coefficient
Is thesame spell from a druid just as shadow bolts from oils and trinkets are affected by spell damage

Proof
http://web.archive.org/web/20071229154006/http://wow.allakhazam.com:80/db/item.html?witem=6522

Posted: Oct 22nd 2007 11:44am | IP: Logged |  Reply to this

Icetongue

8 posts

Score: Decent 

Eating a deviate fish will have a random effect on your character. Possible effects include: 

Healthy Spirit - increases your character's spirit by 5 points for 30 minutes. Invigorate - instantly heals your character 383 to 517. Party Time! - a magic debuff that causes the character to perform random emotes for 2 minutes. Your character will /clap, /cheer, /chicken, /lol, or /dance every 10-15 seconds, possibly interrupting spells or other actions. Rejuvenation - rank 4 of the druid buff by the same name, heals your character by 45 points every 3 seconds for 12 seconds. Shrink - a curse debuff that reduces your character's apparent size, as well as their strength and stamina, for 2 minutes. Sleepy - a magic debuff that sleeps your character for 30 seconds.

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit the source is jamaz's video

All those items have thesame spell and we already know rank 4 rejuvenation which has a 100% coefficient
Is thesame spell from a druid just as shadow bolts from oils and trinkets are affected by spell damage

Proof
http://web.archive.org/web/20071229154006/http://wow.allakhazam.com:80/db/item.html?witem=6522

Posted: Oct 22nd 2007 11:44am | IP: Logged |  Reply to this

Icetongue

8 posts

Score: Decent 

Eating a deviate fish will have a random effect on your character. Possible effects include: 

Healthy Spirit - increases your character's spirit by 5 points for 30 minutes. 
Invigorate - instantly heals your character 383 to 517. 
Party Time! - a magic debuff that causes the character to perform random emotes for 2 minutes. Your character will /clap, /cheer, /chicken, /lol, or /dance every 10-15 seconds, possibly interrupting spells or other actions. 
Rejuvenation - rank 4 of the druid buff by the same name, heals your character by 45 points every 3 seconds for 12 seconds.
Shrink - a curse debuff that reduces your character's apparent size, as well as their strength and stamina, for 2 minutes. 
Sleepy - a magic debuff that sleeps your character for 30 seconds.

**Comment by connormcgregor** [comment]
@GuybrushGit how does he not have any sources? Hes linked Rejuv and crystal rest sources

**Comment by Mostprovidedlinks** [comment]
There's no need for others to scale since those classes don't use heal gear actually

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit if a video showed that aura to work from +healing, how can we ignore other items with thesame aura? They are thesame and should be affected by +healing.

**Comment by Itembugs** [comment]
@guybrushgit 
krasher on 02/12/2007 (Patch 2.0.6)
This trinket benefits 100% from +healing gear. If you equip a +200 healing mace, you will get 209 health per tick. Equip a set of pally gear with +700 healing and you'll heal over 14k HP each time you use it.

As you can see guybrushgit all (6) apply aura 8 HoTs scale with healing through to tbc from jamaz's video

**Comment by Itembugs** [comment]
@guybrushgit http://db.vanillagaming.org/?item=20130#wh-comments

Wowhead comment

**Comment by Itembugs** [comment]
http://db.vanillagaming.org/?spell=18957 should also scale with healing due to their spell aura

**Comment by connormcgregor** [comment]
(10) shouldnt scale that we know

**Comment by Itembugs** [comment]
@GuybrushGit http://db.vanillagaming.org/?item=20130#wh-comments

Wowhead comment

http://db.vanillagaming.org/?spell=18957 http://db.vanillagaming.org/?item=6898
should also scale with healing due to their spell aura

http://db.vanillagaming.org/?item=1970 also since its rank 1 rejuv stated in comments

**Comment by Itembugs** [comment]
@GuybrushGit http://db.vanillagaming.org/?item=20130#wh-comments

Wowhead comment

http://db.vanillagaming.org/?spell=18957 http://db.vanillagaming.org/?item=6898
should also scale with healing due to their spell aura

http://db.vanillagaming.org/?item=1970 also since its rank 1 rejuv stated in comments

http://db.vanillagaming.org/?item=6898

All of these should scale with +healing

**Comment by Itembugs** [comment]
@GuybrushGit http://db.vanillagaming.org/?item=20130#wh-comments

Wowhead comment

http://db.vanillagaming.org/?spell=18957 http://db.vanillagaming.org/?item=6898
should also scale with healing due to their spell aura

http://db.vanillagaming.org/?item=1970 also since its rank 1 rejuv stated in comments

http://db.vanillagaming.org/?item=6898

All of these should scale with +healing 


http://db.vanillagaming.org/?item=16768#wh-comments
