### ISSUE TITLE
Lucifron not applying magic debuff: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#240]
BUGGED BEHAVIOR
Lucifron not performing his magic debuff to raid members.

 CORRECT BEHAVIOR
Lucifron performs a magic and curse debuff to all players within 40 yards.

 SOURCES
Youtube link

COMMENTS from QAKvastskaft:
Likely caused by commit: #43 due to rewrite of Lucifron included in commit 

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/3885

**Comment by Vivenmort** [comment]
It's not just Impending Doom, he also fails to cast Shadow Lash, his shadow damage nuke that hits everyone within 20 yards. If you look on Legacylogs, no recent logs from these servers will have any damage taken from Shadow Lash regardless of fight length.

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/44683-development-update-19042017/
