### ISSUE TITLE
Hunter Pet able to track target that stealthed when being chased

### ISSUE THREAD

**Issue by Pmt112** [elysium-project/server#2401]
I ran into this a few times, running away from hunters as druid their pets were able to target and attack me if I manage to run far enough away, become out of combat, stealth, even if I have no debuff or anything that makes me visible (no flare etc) the pet still knows where I am reaches me and attacks me => you lose stealth, hunter catches you anyway (it's hard to run away from a hunter in the first place and get to this situation, kinda needed for druid to run away)

**Comment by GuybrushGit** [comment]
Blizzlike. Changed in TBC.
