### ISSUE TITLE
Princess Theradras not spawning in.

### ISSUE THREAD

**Issue by Kajjan112** [elysium-project/server#2418]
Hi, i've been running Maraudon for quite abit (60+ runs) but have only ran into  this probelm 2 times, where Princess Theradras hasn't spawned in. They've been completely new runs as i always kill another boss inbefore princess and a boss after and both these times  those two bosses have been there but not Princess. 
Also tried /target Princess without any luck.
The two times this happened is however within the last 10 runs, so might be due to some change/fix that have happened.

**Comment by Kajjan112** [comment]
Also, this is on Elysium PVP.

**Comment by thepparker** [comment]
There's a known issue with certain dungeons not resetting properly after 2 hours (some bosses have a much longer respawn time than others), you need to make sure you manually reset after your last run.

**Comment by Kajjan112** [comment]
The other bosses respawned from the last run. It was only Theradras. That is a seperate issue, guaranteed.
