### ISSUE TITLE
Bristleback Thornweaver's Entangle Root is uninterruptable despite not being Immune: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#242]
BUGGED BEHAVIOR
Bristleback Thornweaver casts Entangling Roots, Shaman casts Earth Shock, Shaman gets rooted

 CORRECT BEHAVIOR
Bristleback Thornweaver casts Entangling Roots, Shaman casts Earth Shock, Entangling Roots gets interrupted

 SOURCES
Logic? I'm seriously bad at this. Earth Shock is supposed to interrupt casting unless the target is Immune.

COMMENTS from QAKvastskaft:
Interrupts should be able to work on this mob.

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/3882

**Comment by GuybrushGit** [comment]
This is not a bug, the spell they use (12747) is not the same spell as druid Entangling Roots. 
Its a non-mana ability and according to its interrupt flags its immune to interrupts.

**Comment by QAkvastskaft** [comment]
Ok, but then is it a bug that the client does not show the immune tag when a spell itself is immune to interrupt? I know this message works when a mob is immune to effects.

**Comment by GuybrushGit** [comment]
Not sure but I don't think so. 
Looking at the possible combat log messages I dont see anything for "Spell X is not interruptable" or similar, only "Mob Y is immune":
http://et.worldofwarcraft.wikia.com/wiki/WoW_constants
http://et.worldofwarcraft.wikia.com/wiki/WoW_Constants/Spells

**Comment by thepparker** [comment]
Some spells can be immune to interrupts despite the NPC not being immune to silence effects
