### ISSUE TITLE
Titanic Leggings.

### ISSUE THREAD

**Issue by Deathmisa** [elysium-project/server#2422]
My character who got transferred from Oll Elysium server to the anathema realm had titanic leggings. When the transfer happened my titanic leggings rerolled into http://db.vanillagaming.org/?item=18380. 
I have this item which was previously Titanic Leggings (http://db.vanillagaming.org/?item=22385) but it has a <Made by> tag which proves it. Also Eldritch Reinforced legplates cannot be crafted, its an item dropped by Prince Toltheldrin in Dire Maul west (http://db.vanillagaming.org/?npc=11486). So the thing is , when patch 1.10 came out the item still stays the same. Could I possibly get the item or at least the mats that I worked so hard to farm in the past? Also i've spoken to gm's many times about this (https://cdn.discordapp.com/attachments/268807339136516096/329443682770092052/unknown.png). 
Also this is how the item looks : https://prnt.sc/ghl75m 
Thanks in advance, waiting for your responce, a gm reccomended me to post here instead of making more tickets.

**Comment by thepparker** [comment]
You'll have to create a thread on the support forums for further assistance from a high level GM. I'm unsure how we are handling these cases, and it's not really relevant to server development, so it's best to get in contact with them.
