### ISSUE TITLE
Minor wizard oil

### ISSUE THREAD

**Issue by ollbor75** [elysium-project/server#2443]
The minor wizard oil from enchanting does not work. 
it just says. the spell is not availible to you.
when you try to use it

**Comment by Haiwuu** [comment]
available at a later patch, disabled until that point.

**Comment by Mostprovidedlinks** [comment]
@Haiwuu which patch is that? 1.12?

**Comment by croseis** [comment]
Mee too wtf man??? Its fixet u?

**Comment by ollbor75** [comment]
naah it comes in later patch
