### ISSUE TITLE
Wrong aggro radius of BRD mobs Anvilrage Footsman and Anvilrage Guardsman

### ISSUE THREAD

**Issue by gustanoid** [elysium-project/server#2445]
Here is the video from 2006 - https://www.youtube.com/watch?v=HQpoksHqVig
on 0:56 you can see rogue activating gear without pulling any mobs around. I cant do that on elysium, mobs aggro radius is too high I aggro both packs aroung with lvl 60 char when trying to do the same.(im tauren druid)

**Comment by BrynjaDarrow** [comment]
I have done this a million times with my rogue and it always worked.

**Comment by gustanoid** [comment]
maybe its because of taurens bigger hitbox. Just try it as tauren, you will always pull mobs

**Comment by gearselysium** [comment]
You haven't presented any evidence that this should be possible as a tauren druid.

**Comment by gustanoid** [comment]
just tried it with noggenfogger suze reduction and it worked. Kinda stupid it affects a hitbox
