### ISSUE TITLE
[Elysium PvP] Rosewine Circle - No Stats whatsoever

### ISSUE THREAD

**Issue by Largen-in-Charge** [elysium-project/server#2447]
The item: Rosewine Circle has no stats. For some people it displays the stats +7 agi +16 spirit, however when the item is equipped the character's states do not change. According to https://wow.gamepedia.com/Rosewine_Circle and http://db.vanillagaming.org/?item=13178 the Rosewine Circle should have: equip restores 5 mana per 5 sec and  equip: increases healing by 29.

There was a closed ticket on this earlier on Elysium (https://github.com/elysium-project/server/issues/1349) and one that is still open on Anathema (https://github.com/elysium-project/server/issues/926).

**Comment by 0vertime** [comment]
29 healing is patch 1.10, which is Anathema.

**Comment by GuybrushGit** [comment]
Same as https://github.com/elysium-project/server/issues/926
