### ISSUE TITLE
Judgement of Justice doesnt work

### ISSUE THREAD

**Issue by auren94** [elysium-project/server#2448]
This prevents a player from going above their normal run speed. Thus, for instance, a Druid who is affected by the Judgement will not go any faster than the normal run speed if they shift into Travel Form, a Rogue who uses Sprint will receive no speed boost, and any player riding a mount will receive no speed bonus from doing so, but in elysium do nothing.

**Comment by Mostprovidedlinks** [comment]
I'm 99% sure this was in tbc

**Comment by Mostprovidedlinks** [comment]
There's always frost oil/icy enchant combo which is better since it procs more

**Comment by auren94** [comment]
http://paladin-guide.blogspot.com.es/2005/12/judgements.html?showComment=1284531684925&m=1#c3254587756552912509  here 2005 anonymous comment : Anonymous11:21 PM
The Judgement of Justice also works as a speed buff de-buffer.. On players, they are using like sprint (rouge) it cancels out their speed gain. Not just only on rouges, but all players. 
I was also a player of vanilla, I have the game in my room as a trophy

**Comment by GuybrushGit** [comment]
>As of 2.0 version of the game, this ability affect players as well. It limit a player's speed to a maximum speed of 100% running speed
>https://wow.gamepedia.com/index.php?title=Judgement_of_Justice&oldid=403169

That blogpost is from 2005 but the comment is from 2007 or later. The comment isnt there yet in this archive from 2007:
http://web.archive.org/web/20071018022012/http://paladin-guide.blogspot.com:80/2005/12/judgements.html
