### ISSUE TITLE
Costumes (Noggenfogger Skeleton, etc...) and Druid Forms

### ISSUE THREAD

**Issue by WobLight** [elysium-project/server#245]
# Bugged Behavior

When shapeshifting between forms (Cat, Bear, Travel, Moonkin), Costumes such as the skeleton from Noggenfogger's Elixir are removed from the druid even though the buff remains. Relogging temporarily fixes the issue until you shapeshift again then it is lost.

# Correct Behavior

All costumes should remain on druids during shapeshifting despite the form.

# Sources
1. https://www.youtube.com/watch?v=LrljwQrM3uE - Starting at 3:34 mins, The noggenfogger skeleton costume remains through multiple shapeshifts.

2. Original Source from 2006 - https://www.warcraftmovies.com/movieview.php?id=15011

3. https://www.youtube.com/watch?v=ScE8shXpz4Y - Starting at 15:15 mins, (Similar situation to `1`).

4. Original Source from 2006 - https://www.warcraftmovies.com/movieview.php?id=29936

# [bug tracker](https://elysium-project.org/bugtracker/issue/389)

**Comment by WobLight** [comment]
#217

**Comment by QAkvastskaft** [comment]
Also found here: https://elysium-project.org/bugtracker/issue/389

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/44683-development-update-19042017/
