### ISSUE TITLE
Cenarion Hold nature resistance recipes missing from Mishta

### ISSUE THREAD

**Issue by Spaztick** [elysium-project/server#2450]
On [the WoW wiki under Professions](http://wowwiki.wikia.com/wiki/Patch_1.11.0) lists the CH rep NR recipes released for patch 1.11.0, currently absent from Mishta.

[An archive of allakhazam](http://web.archive.org/web/20060621204103/http://wow.allakhazam.com:80/news/sdetail7557.html?story=7557) shows the same.

[Screenshot of Mishta](http://i.imgur.com/wEPeob3.jpg) showing the herb bag in place but lacking the rest.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/54751-anathema-updates-20092017/
