### ISSUE TITLE
17 days sickness

### ISSUE THREAD

**Issue by Rungeirl223** [elysium-project/server#2465]
Please remove my 17 days sickness on my hunter Pakave.

**Comment by GuybrushGit** [comment]
Go to a Spirit Healer and take rez sickness again.

**Comment by Spionida** [comment]
Die, or in game ticket and wait for a GM

**Comment by Mostprovidedlinks** [comment]
This res sickness thing is stupid. Cant belive it hasnt been fixed.
Some people dont farm so eventually they will get to 0 durability twice as fast because of it..

**Comment by thepparker** [comment]
Dupe
