### ISSUE TITLE
Patch 1.11 Regression: T0.5 Boss in DM:E spawns without performing any events

### ISSUE THREAD

**Issue by Forest-runklebc** [elysium-project/server#2466]
Running DM:E and we pulled Alzzin the Wildshaper, immediately on the pull Isalien and her bird companion spawned without having done any T0.5 quests to spawn them.

**Comment by Forest-runklebc** [comment]
https://clips.twitch.tv/AgileBombasticAlfalfaKreygasm

**Comment by Cabro** [comment]
This is true for all D2 bosses. LBRS, just did Scholo earlier, i assume Strat is the same...

**Comment by thepparker** [comment]
Should be fine now
