### ISSUE TITLE
Timmy the Cruel spawns too early.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#2473]
Right now it's scripted to spawn after you kill the 3 NPCs on the stairs leading to the scarlet building.
It is wrong, it should spawn after you kill all NPCs in that courtyard.

**Comment by martinjlowm** [comment]
Partly fixed by #2512. I couldn't find any source that shows that all mobs must be dead before he spawns. However, I did fix his spawn location and made him move around the courtyard.

**Comment by Cabro** [comment]
https://youtu.be/RmMI-abhyi8?t=6m20s
https://youtu.be/uq_1SzK_RfA?t=5m9s - proof there shouldn't be skeletons in Timmy's courtyard. Also Timmy's correct patrol path.
https://youtu.be/fcgvHPgF_ww?t=4m12s - here you can see ravaged cadaver ressing, similar to scholo mobs, not scripted yet on strat.
https://youtu.be/8O56rBuNB4A?t=1m37s - here you can see that the 3 postmen don't spawn on top of you when you open the mailboxes to get instagibbed, but instead they spawn on the opposite side of the road. Same is true for Malown.
https://youtu.be/8O56rBuNB4A?t=2m36s - another one with timmy spawn and patrol, yell on aggro etc. notice no mobs left in the courtyard, again.

**Comment by martinjlowm** [comment]
While these sources are from TBC and onwards (except one) I find them reliable. I can't think of any reason to why it should have changed since Vanilla.

Regarding skeletons, as I remember it, the Scarlet NPCs fight them. Obviously that's not what happens right now.
