### ISSUE TITLE
1.11 Majordomo Executus chest did not spawn

### ISSUE THREAD

**Issue by 0vertime** [elysium-project/server#2475]
title

**Comment by strudelkuchen** [comment]
^ can confirm (Anathema)

**Comment by Spionida** [comment]
In-game ticket with [evidence](https://forum.elysium-project.org/topic/47242-boss-looting-failures/)

**Comment by Mostprovidedlinks** [comment]
Pls fix

**Comment by raqquelgit** [comment]
Can confirm that the chest did not spawn again tonight in our raid as well. Pls fix.

**Comment by strudelkuchen** [comment]
Happened again.

**Comment by dashess** [comment]
happening for 2 weeks now

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/54751-anathema-updates-20092017/
