### ISSUE TITLE
Report: Unstoppable Force should have a knock-back prior to patch 1.7, not a stun

### ISSUE THREAD

**Issue by gearselysium** [elysium-project/server#2478]
**Confirmed**

Patch 1.7.0 (patch date:2005-09-22): The Unstoppable Force now has a short duration stun instead of a knock-back effect, and the stun will occur less frequently. 

Need PPM data for knock-back effect.

**Comment by gearselysium** [comment]
Spell ID for knock-back component is 23699

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
Concurrently with 1.7 so no one gets to see it :)
