### ISSUE TITLE
help me account issue

### ISSUE THREAD

**Issue by SEalguy** [elysium-project/server#2481]
I got hacked awhile back and lost everything.  never have been able to figure out 2 factor aurthorization.  I have tried today to just make it work and i go to login to see if it worked and my account was closed.  i am very unhappy because when i reported my account hacked instead of an apology like blizzard would have done i was told i was lucky that i wasn't banned!!!!! all because the hackers use the account to advertise and was told i couldn't be helped.  i would like my account back i can verify i am the owner.  im still confused on how to get the 2 factor working.  please help me i want to play.

**Comment by Haiwuu** [comment]
This is not the place for account recovery

**Comment by Spionida** [comment]
Your account was hacked because it was not secure. However, a bugs tracker is not the place to be. [This forum](https://forum.elysium-project.org/forum/474-account-website-forum-related-issues/) is the place to go,
