### ISSUE TITLE
Hunter. Improved Concussive Shot - stun effect should not be resisted prior to patch 1.7

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/server#2484]
As title says.
Proof:
http://wowwiki.wikia.com/wiki/Patch_1.7.0
Improved Concussive Shot - The stun effect can now be resisted.

**Comment by Crusaderz** [comment]
Also right now it acts like it's a spell while it should be physical with a small resist chance. Why it's matter? Cuz in pvp against higher level targets imp. concussive shot proc resists all the time.

**Comment by Sabre142** [comment]
Spells are all set to their final patch 1.12.1 effects. This is intended.

**Comment by Mostprovidedlinks** [comment]
Yes please keep it the way it is in 1.12.1

**Comment by thepparker** [comment]
Class spell mechanics are in their 1.12 state
