### ISSUE TITLE
James Hyal

### ISSUE THREAD

**Issue by gmak21** [elysium-project/server#2488]
Hello, 

As I have completed the James Hyal quest (First Part), I expected that I would take the next quest of this chain. However, it was said that "you don't meet the requirements for this quest". 

How can I fix this?

Kind regards.

**Comment by kampeador** [comment]
Have you completed a quest **They Call Him Smiling Jim** before?
They exclude each other.

**Comment by gmak21** [comment]
I think yes.. Now what can I do?

**Comment by thepparker** [comment]
Nothing, you have completed the available quests from this chain
