### ISSUE TITLE
Draconic For dummies (chapter III)[Anathema]

### ISSUE THREAD

**Issue by Shokar** [elysium-project/server#2493]
Draconic For dummies (chapter III) [Item](http://db.vanillagaming.org/?item=21105) Either not dropping at all or the drop chance is too low.

After killing around 200~ [Hederine Slayer](http://db.vanillagaming.org/?npc=7463)
and [Hederine Initiate](http://db.vanillagaming.org/?npc=7461)
the item still did not show up.
The drop rate should be around 6% [Source](http://wowwiki.wikia.com/wiki/The_Scepter_of_the_Shifting_Sands_quest_chain)

**Comment by kozhin2012** [comment]
i see Draconic For dummies in undersity.
![image](https://user-images.githubusercontent.com/13003071/30252863-da85ffd6-968a-11e7-86e5-43e16ae839c4.png)
