### ISSUE TITLE
Hunter Pet generates aggro without attacking (might be spirit bond bug)

### ISSUE THREAD

**Issue by lequintal69** [elysium-project/server#2496]
As title says, hunter pet generates important aggro while beeing idle. I have spirit bond so it might be it. (pet is full life so spirit bond is not regenerating him any life)

**Comment by macropus9** [comment]
Don't know if it's a bug, but yes, spirit bond is the cause of that.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
