### ISSUE TITLE
Quest "This Is Going to Be Hard" summoned NPC can be summoned multiple times to farm Elemental Earth.

### ISSUE THREAD

**Issue by Vahapet** [elysium-project/server#2497]
Quest ID 778. NPC ID 2919.

Earth Elemental Fam'retor Guardian, spawned by this quest can be summoned multiple times by picking up and abandoning the quest and being abused by players to farm Elemental Earth in bulk.

The decision should be to remove any other loot than quest items from it, preventing people from abusing it.

**Comment by gearselysium** [comment]
Hi Vahapet, please report any players you see abusing this via an in-game ticket so GM's can action as well.

**Comment by Sabre142** [comment]
Can this crash the server if too many are spawned? Also can a mage abuse it for AoE exp?

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
