### ISSUE TITLE
AI scripts operate inconsistently

### ISSUE THREAD

**Issue by martinjlowm** [elysium-project/server#2499]
Inconsistent behavior of AI scripts have shown to occur for #2080 and #2475 where it appears as if the scripts are interrupted before functions are meant to terminate. #2475 proves that https://github.com/elysium-project/server/blob/e1a3901ed8ad05ae1bda111dfc241274c02a1bcc/src/scripts/eastern_kingdoms/burning_steppes/molten_core/boss_majordomo_executus.cpp#L188-L197

can fail to spawn the chest at Majordomo. The video proof of #2475 clearly shows that Majordomo performs the correct actions (lines 188-192) before the chest should be spawned. The only obvious culprit, looking at the Majordomo code, is that `m_pInstance` is null which shouldn't be the case.

As for the event for Warchief's Blessing (#2080), it sometimes fails to start, even after the 6 hours cooldown. Either
https://github.com/elysium-project/server/blob/e1a3901ed8ad05ae1bda111dfc241274c02a1bcc/src/scripts/kalimdor/orgrimmar/orgrimmar.cpp#L741-L745 fails to trigger `StartBlessingEvent()` or the state machine in `UpdateAI()` is flawed.

These issues appear to only occur at high population, which makes it difficult to track down in a development environment. I suggest to add temporary debug messages to those scripts for production to trace the behavior when the scripts "break".

**Comment by kampeador** [comment]
Your observations are wrong.
1. There are some issues in Majodomo script, like missing sounds and wrong texts, but chest mechanic works fine. Game object depends on event 162. Make sure that "**WowPatch**" option in your server config is 2 or higher and event:162 is NOT disabled in **game_event** table. Then login, use a gm command **.event list** and you will see that event 162 is active.

2. Warchief's Blessing event logic is wrong. UpdateAI() will not be called if map cell is unloaded, timer will also stop. If there are no players near Thrall, then cooldown will last forever or until server restart. Triggers need to be balanced and all required map cells need to be loaded during the event, to ensure that all players and NPCs receive a buff. Herald of Thrall spawn position is not Blizzlike, etc.
I've planned to rewrite it completely, but currently have no free time. I'll return to this problem later.

**Comment by martinjlowm** [comment]
I'm glad!

Regarding the Majordomo problem though, it might be a bad config. It occurred on Anathema which should have event 162 active. For obvious reasons, I cannot confirm that it is the case.

I might take another look at the Warchief Blessing issue. If what you are saying is correct, which sounds probable, the issue should be easy to reproduce.

**Comment by martinjlowm** [comment]
This issue has shown not to be relevant. Closing.
