### ISSUE TITLE
Blade of Eternal Darkness does not have an ON USE ability

### ISSUE THREAD

**Issue by volkain5** [elysium-project/server#250]
BUGGED BEHAVIOR
Blade of Eternal Darkness (item ID=17780) currently has no stats or on use.
 CORRECT BEHAVIOR
Item should have an on use ability with a 1.5 second cast time and a 30 second cooldown The effect is named Engulfing Shadows.
Spell ID: http://db.vanillagaming.org/?spell=27860
 SOURCES
http://wow.gamepedia.com/Blade_of_Eternal_Darkness According to gamepedia: "The dagger was changed in Patch 1.10.0. Previously, the proc was an "On Use" ability with a 1.5 second casts and a 30 second cooldown." if we look at the changelog for the item: "Patch 1.10.0 (2006-03-28): The On Use ability on the Blade of Eternal Darkness has been changed to an On Equip triggered effect with a chance to occur on any damage spell. Patch 1.8.0 (2005-10-10): Blade of Eternal Darkness now has an appropriate minimum level. Patch 1.2.0 (2004-12-18): Added." a quick google of the issue will bring up a forum post "I remember reading that nostalrius broke it while they were changing it between the old on use effect and the chance on hit effect but I haven't seen anything about it since." there was no official response to this.

**Comment by volkain5** [comment]
Spell ID: http://db.vanillagaming.org/?spell=27860

**Comment by m-laniakea** [comment]
Have you actually right-clicked the item?

You're not seeing the text for its on-use ability, because the text for that spell was removed sometime after Patch 1.9.

**Comment by volkain5** [comment]
oh my it would appear that you're right. thank you for clarifying that I will remove this
