### ISSUE TITLE
my sickness is bugged 

### ISSUE THREAD

**Issue by guipvalenta** [elysium-project/server#2502]
hello my name is guipvalenta would have like you to remove this debuff from me please it is a sickness of 18days that must have bugged since I did not enter the server a while ago because my pc gave an error and I was out of money to fix it so I personally for you Please remove this sickness from me please

**Comment by Mostprovidedlinks** [comment]
Is there any way to have this fixed so the res sickness problem doesnt reoccur? Thanks

**Comment by Spionida** [comment]
Die, and it resets

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
