### ISSUE TITLE
(Thorium) Shield Spike incorrect damage

### ISSUE THREAD

**Issue by fidbugs** [elysium-project/server#2503]
Thorium shield spike damage is incorrect. It seems that it is affected by armor reduction and it is not randomized as tool tip suggests. That being said i suppose it is same with all shield spikes(mithril, iron, etc.).

Every time you reequip shield with attached shield spike damage changes and remains constant until next removal and equipping. For instance - you equip shield, it will roll random number and you will be dealing that amount of damage until you reequip shield, and after that it again gives you certain amount of damage you will do on block.  Damage is not randomized/rolled between 20-30 on every block you make.

Second part of issue is that damage done is affected by armor of target or by some sort of reduction mechanism - as i am unable to get damage(with current mechanic) between 20-30, from what i have tested it goes from 11-21 - which shows some kind of reduction.

There is no mention of such reduction involved with spikes damage on thottbot or allakhazam. It clearly states multiple times that damage is 20-30. Also video material shows no such reduction.

Recepie: Thorium Shield Spike

http://web.archive.org/web/20071114220407/http://thottbot.com:80/i12692

http://web.archive.org/web/20080116012439/http://wow.allakhazam.com:80/db/item.html?witem=12692&locale=enUS;source=live

Thorium Shield Spike

http://web.archive.org/web/20070504065243/http://wow.allakhazam.com:80/db/item.html?witem=12645&locale=enUS;source=live

http://web.archive.org/web/20071114220402/http://thottbot.com:80/i12645

I suppose randomization of damage on hit is obvious and self-explanatory based on tool tip description.

Video evidence tho from TBC, it confirms correct mechanics since no change to item(or whole family of items, spikes) has been made made.

https://www.youtube.com/watch?v=lJVVU1En3Bg

**Comment by Mostprovidedlinks** [comment]
Agree to this
