### ISSUE TITLE
Rez Sickness Timer Extended 

### ISSUE THREAD

**Issue by maatheru** [elysium-project/server#2509]
Write your report here
I'm not terribly sure if the issue has been reported, or if others have experienced it at all, but I had to log off just after dying, so I had rez sickness. I haven't played on my character in a few weeks and just came back to an 18 day long rez sickness timer. The character is Maatheru on the realm Darrowshire. 
Thanks in advance if you're able to do anything for it.

**Comment by GuybrushGit** [comment]
Take rez sickness again and it will overwrite the long one.

**Comment by Spionida** [comment]
I.E. Die

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
