### ISSUE TITLE
Oozing Bag

### ISSUE THREAD

**Issue by kozhin2012** [elysium-project/server#2511]
http://db.vanillagaming.org/?item=20768#contains
I kill 200+ slimes in Un'Goro Crater and Eastern Plaguelands but bag not droped.
drop == 0% ?
Server elysium pvp.

**Comment by watapus** [comment]
Looks like it's a 3% drop rate for Rotting Sludge in the database.

**Comment by QAkvastskaft** [comment]
Current drop rates are around ~2-3% from most high level slimes
