### ISSUE TITLE
Improved Concentration Aura Bug

### ISSUE THREAD

**Issue by Shaniquanda** [elysium-project/server#2513]
When specced 3 points into improved concentration aura in the paladin prot tree, you are supposed to "gain 15% chance to resist silence and interrupt effects." The 15 percent resist to silence works which I tested dueling a mage and having him counter spell me on cool down. I resist the counter spell from time to time. The 15 percent resist to interrupt effects however does not work. I dueled a rogue and asked him to kick me while casting on cool down. After about 50 kicks or more I did not resist a single one. Nor have I resisted a pummel or kick for the past 6 months of playing on my paladin which leads me to believe that the improved concentration aura talent is bugged.

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit  can you check this ty
