### ISSUE TITLE
Able to proc clearcasting by casting Ice Barrier

### ISSUE THREAD

**Issue by redial2** [elysium-project/server#2514]
Since the server shutdown / maintenance on 10 Sept 2017 EST I have been able to proc clearcasting by casting ice barrier.

https://cdn.discordapp.com/attachments/343549167286616064/356549960298135564/unknown.png

http://prntscr.com/gjju4l

http://prntscr.com/gjk0xn

I've tried mana shield and the various wards, but those seem uneffected at the moment.

This is taking place on Elysium.

**Comment by NeyaElysium** [comment]
had it proc of "Fire Ward" and "Remove Decurse" aswell.

http://imgur.com/a/du1aj

**Comment by Phoosy** [comment]
This has already been reported and confirmed. https://github.com/elysium-project/server/issues/1868

**Comment by redial2** [comment]
No, it isn't Phoosy, it's a completely new issue. Clearcasting is now proccing even when non damage spells are cast; we've provided three example spells in this ticket.

Please read tickets before dismissing them.

**Comment by Phoosy** [comment]
I had copy/pasted the wrong link as I had both the issue I linked and the one I was trying to refer to open as tabs. I will correct that momentarily.

**Comment by Phoosy** [comment]
Recorrection: see thepparker's comment in this issue report. My link stands but not for the reason in the original issue report.

>Just to be clear, the confirmed issue here is that free casting and not hitting anything procs Clearcasting, NOT that Blizzard does not have a chance per tick. AM and Blizzard do NOT have a chance to proc each tick.

**Comment by redial2** [comment]
That still seems to be a different issue, as now new non-damage spells are proccing clear casting

**Comment by redial2** [comment]
Look, before the  maintenance, I had never once in my life procced clearcasting off an ice barrier. Not one single time. Now, it's happening about 10% of the time. I like that, but it's definitely a bug.

**Comment by Phoosy** [comment]
If freecasting and not hitting anything is proccing a spell it would be sensical to note that spells that don't normall 'hit' anything like Ice Barrier would also proc clearcasting in the current state of the spell functionality.

**Comment by GuybrushGit** [comment]
Doesn't happen in dev.

**Comment by NeyaElysium** [comment]
This is now live on Elysium. Just had CC procc off Icebarrier.

**Comment by QAkvastskaft** [comment]
See: #2461
