### ISSUE TITLE
Deathsworn Captain not respawning in Shadowfang Keep

### ISSUE THREAD

**Issue by ryancheung** [elysium-project/server#2521]
NPC entry 3872
He is a rare mob.

**Comment by GuybrushGit** [comment]
Should he? He's a boss.

**Comment by Phoosy** [comment]
He's not a boss.
http://web.archive.org/web/20071111060434/http://wow.allakhazam.com:80/db/mob.html?wmob=3872&locale=enUS;source=live

Date is in TBC era but comments go way further back.

**Comment by ryancheung** [comment]
"Ive entered shadowfang keep 1002 times in the past year. I have killed him 702 times and received the Assassin's blade 105 times according to my loot manager. This bad boy has gone up in value each day since its arival in the game."

**Comment by Phoosy** [comment]
By no data, I mean that there is no data that he is or is not spawning _on Elysium Project servers_.

**Comment by ryancheung** [comment]
The elysium database shows he is not spawning.
