### ISSUE TITLE
Mage "Ice Armor" Spell Bug

### ISSUE THREAD

**Issue by arhimas** [elysium-project/server#2523]
Good morning. First of all I would like to congratulate you for your great work with Elysium. On the other hand I noticed that the spell "Ice Armor" Rank 1, should increase my Armor 377, but It only increases 290. Is that normal?.

Thanks in advance.

**Comment by Sabre142** [comment]
Working as intended.

http://web.archive.org/web/20050215110853/http://wow.allakhazam.com:80/db/spell.html?wspell=7302

Delete WDB folder.

**Comment by QAkvastskaft** [comment]
Ice armor rank 1 gives the correct amount of armor with and without the talent:
https://i.imgur.com/3FchVHv.png
Without talent 290
With talent 377 (The icon still says 290)
