### ISSUE TITLE
[Engineering] BKP Impact Shot

### ISSUE THREAD

**Issue by LucasAvis** [elysium-project/server#2524]
Server - Anathema
Profession Bug - Engineering
Schematic - BKP Impact Shot, trained by the trainers.
Issue: Trained BKP Impact Shot, wrong tooltip item, schematic ended up not trained and not in the lists. Can still be trained by new engineers. 

![image](https://user-images.githubusercontent.com/31852022/30274949-714d68b6-96f7-11e7-9d6b-72d6ecce6094.png)
![image](https://user-images.githubusercontent.com/31852022/30274963-7f36c51c-96f7-11e7-9363-75441b9e8b68.png)

Solution: Found on another github and server, maybe can be implemented here?
 https://github.com/TrinityCore/TrinityCore/issues/15931

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
