### ISSUE TITLE
Azuregos' Magic Shield is dispellable

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#253]
Azuregos' ability **Magic Shield*** is currently able to be dispelled with Dispel Magic. 

*SPELL_REFLECT = 22067
https://github.com/elysium-project/server/blob/19e7622bd3f3d2c0b1bfe65892f25d035b9e222b/src/scripts/world/boss_azuregos.cpp

Dispel Magic effectively allows to bypass the mechanic entirely. Casters should not be able to cast spells on him while the Magic Shield buff is up. 

Magic Shield effect : http://db.vanillagaming.org/?spell=22067

Reflection
Instant
Gives the caster 100% chance to reflect harmful spells for 10 sec.
	Buff
	
Spell Details
	
Duration 	10 seconds
School 	Physical
Mechanic 	n/a
Dispel type 	Magic
Cost 	None
Range 	0 yards (Self Only)
Cast time 	Instant
Cooldown 	n/a
Effect #1 	(6) Apply Aura #28: Reflect Spells %
Value: 100 

Even though it says the buff is of Magic type, casting Dispel Magic on the creature while the buff is active should result in the effect Dispel Magic being reflected to its caster.

As for sources : 
- Current behavior > I believe this can be tested by QA for confirmation. Can provide proof if unable to reproduce. 
- How it should work > In every retail video of Azuregos, the **Magic Shield lasts for its entire duration**. It never gets dispelled in vanilla, because it is supposed to reflect any kind of targeted spell. There is no comment/guide that suggests dispelling the Magic Shield over the course of several patches and expansions.

The only way to remove Magic Shield came late on with an aoe dispel (Mass Dispel). Targeted spells such as Dispel Magic should be reflected.

**Comment by QAClayton** [comment]
Confirmed magic reflect should not be dispellable.
