### ISSUE TITLE
Gamon drops high level greens

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#2538]
Drops greens ranging from level 5 to 59. http://db.vanillagaming.org/?npc=6466#drop:0-3-13+1 page here should be the same for this server.

Obviously this is an error and he should only drop greens around his own level. Source: http://web.archive.org/web/20050524021602/http://wow.allakhazam.com:80/db/mob.html?wmob=6466

**Comment by GuybrushGit** [comment]
Can't reproduce in dev.
