### ISSUE TITLE
Shaman totems purge paladin blessings off horde, they should stack instead

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/server#2541]
mana regen shaman totem removes blessing of wisdom when cast on a mind controlled horde

Tranquil Air Totem removes blessing of salvation when cast on a mind controlled horde

agility , strength and windfury totem removes blessing of kings and blessing of might when cast on a mind controlled horde
https://youtu.be/rILJMDWCkiA

Proof:
here it says they stack
http://wowwiki.wikia.com/wiki/Tranquil_Air_Totem

http://www.winterwolves.org/forum/index.php?/topic/9209-terestian-illhoof-strategy-guide/
I have souces showing stacking existed in 2007 march tbc (4 months before vanilla)

tbc july 2007
http://www.mmo-champion.com/threads/601478-Questions-about-Tranquil-Air-and-Blessing-of-Salvation-on-shamans

---- 

date nerfed
http://wowwiki.wikia.com/wiki/Mana_Spring_Totem

In 2009 hey were nerfed

Patch changes

 Patch 3.1.2 (2009-05-19): Greater Blessing of Wisdom now grants 92 mana per 5 seconds to prevent being overwritten by Mana Spring Totem.
 Hotfix (2009-04-23): "Greater Blessing of Wisdom and Mana Spring Totem will no longer stack as intended. [1]" 
 Patch 3.1.0 (14-Apr-2009): Now provides the same mana benefit as a paladin's Blessing of Wisdom to the entire party or raid, but is exclusive with that effect.
Patch 3.0.2 (14-Oct-2008):Totem duration increased from 2 to 5 minutes.
Patch 2.3.0 (13-Nov-2007): The mana restored by the totem increased by roughly 50%.
Patch 1.11.0 (20-Jun-2006): Mana cost reduced.

If it was nerfed in april 2009, im sure it existed in vanilla and tbc since it existed in march 2007 tbc

**Comment by notpentadactyl** [comment]
Your source is from 2008, try to find something from around 2006.

**Comment by Mostprovidedlinks** [comment]
I found sources from mid tbc july 2007
http://www.mmo-champion.com/threads/601478-Questions-about-Tranquil-Air-and-Blessing-of-Salvation-on-shamans

**Comment by Itembugs** [comment]
http://wowwiki.wikia.com/wiki/Mana_Spring_Totem

In 2009 they were nerfed not to stack

**Comment by Itembugs** [comment]
http://wowwiki.wikia.com/wiki/Mana_Spring_Totem

In 2009 hey were nerfed 

Patch changes

 Patch 3.1.2 (2009-05-19): Greater Blessing of Wisdom now grants 92 mana per 5 seconds to prevent being overwritten by Mana Spring Totem.
 Hotfix (2009-04-23): "Greater Blessing of Wisdom and Mana Spring Totem will no longer stack as intended. [1]" 
 Patch 3.1.0 (14-Apr-2009): Now provides the same mana benefit as a paladin's Blessing of Wisdom to the entire party or raid, but is exclusive with that effect.
Patch 3.0.2 (14-Oct-2008):Totem duration increased from 2 to 5 minutes.
Patch 2.3.0 (13-Nov-2007): The mana restored by the totem increased by roughly 50%.
Patch 1.11.0 (20-Jun-2006): Mana cost reduced.

**Comment by Itembugs** [comment]
https://www.google.com.au/search?ie=UTF-8&client=ms-android-hms-vf-au&source=android-browser&q=2009+totems+blessings+dont+staxk&gfe_rd=cr&dcr=0&ei=FAO4Wf-rCrPM8geD3LvIBw

Every site on this link shows it was nerfed in wotlk

**Comment by Itembugs** [comment]
https://www.google.com.au/search?ie=UTF-8&client=ms-android-hms-vf-au&source=android-browser&q=2009+totems+blessings+dont+staxk&gfe_rd=cr&dcr=0&ei=FAO4Wf-rCrPM8geD3LvIBw

Every site on this link shows totems and blessings are nerfed in wotlk and dont stack

**Comment by Itembugs** [comment]
Sources say it existed in tbc

**Comment by Itembugs** [comment]
Sources say it existed in mid 2007

Sources say nerfed in 2009

https://www.google.com.au/search?ie=UTF-8&client=ms-android-hms-vf-au&source=android-browser&q=2009+totems+blessings+dont+staxk&gfe_rd=cr&dcr=0&ei=FAO4Wf-rCrPM8geD3LvIBw

Every site on this link shows totems and blessings are nerfed in wotlk and dont stack

**Comment by Itembugs** [comment]
http://www.winterwolves.org/forum/index.php?/topic/9209-terestian-illhoof-strategy-guide/

Says stacking existed in 2007 march tbc

Vanilla was r months before that 

Im sure they stacked.

Why would they be nerfed in 2009 then?

**Comment by Itembugs** [comment]
Sources say nerfed in 2009

https://www.google.com.au/search?ie=UTF-8&client=ms-android-hms-vf-au&source=android-browser&q=2009+totems+blessings+dont+staxk&gfe_rd=cr&dcr=0&ei=FAO4Wf-rCrPM8geD3LvIBw

Every site on this link shows totems and blessings are nerfed in wotlk and dont stack

   

http://www.winterwolves.org/forum/index.php?/topic/9209-terestian-illhoof-strategy-guide/

Says stacking existed in 2007 march tbc

Vanilla was 4 months before that

Im sure they stacked.

Why would they be nerfed in 2009 then?
