### ISSUE TITLE
Drape of Unyielding Strength Cannot finish! Because NPC has disappeared for several days. When will it be fixed?

### ISSUE THREAD

**Issue by lidaku789** [elysium-project/server#2543]
Drape of Unyielding Strength Cannot finish! Because NPC has disappeared for several days. When will it be fixed?

**Comment by Itembugs** [comment]
Hope it gets fixed

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/54751-anathema-updates-20092017/
