### ISSUE TITLE
Mishta (in CH) Missing Many Tailoring Patterns

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#2544]
On Anathema 1.11 Mishta is supposed to sell 4 new Tailoring Patterns:

Gaea's Embrace: http://db.vanillagaming.org/?item=22773
Sylvan Crown: http://db.vanillagaming.org/?item=22773
Sylvan Shoulders: http://db.vanillagaming.org/?item=22772
Sylvan Vest: http://db.vanillagaming.org/?item=22774

Source: "Four new nature resist cloth armor recipes have been added to the merchants at Cenarion Hold for those with high Cenarion Circle reputation."-http://wowwiki.wikia.com/wiki/Patch_1.11.0

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/54751-anathema-updates-20092017/
