### ISSUE TITLE
Artisan Fishing Trainable Without Quest (H)

### ISSUE THREAD

**Issue by Phoosy** [elysium-project/server#2548]
Reference: http://web.archive.org/web/20110623205915/http://www.elitepvpers.com/forum/wow-guides-templates/69481-full-fishing-guide-1-300-a.html

Currently, it appears that Katoom the Angler (http://db.vanillagaming.org/?npc=14740) will teach Horde players Artisan Fishing (I'm guessing this is DUE to VG's info stating he can train it). This should not be the case, as Artisan fishing is only supposed to be available from Nat Pagle (http://db.vanillagaming.org/?npc=12919) after completing his quest Nat Pagle, Angler Extreme  (http://db.vanillagaming.org/?quest=6607) (which is available to both H and A).

**Comment by RealZarkom** [comment]
![wowscrnshot_091717_001706](https://user-images.githubusercontent.com/31869461/30519880-5f8a5b30-9ba1-11e7-864d-09e90644302a.jpg)


dont take my fishing skill away pls. I reported the issue as soon as i found it^^

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
