### ISSUE TITLE
Incorrect price and riding skill requirement of Alterac Valley reputation mounts 

### ISSUE THREAD

**Issue by Wrata4163** [elysium-project/server#255]
Copy/pasted from original report: https://elysium-project.org/bugtracker/issue/2267

BUGGED BEHAVIOR
The AV mounts Horn of the Frostwolf Howler (horde) and Stormpike Battle Charger (alliance) cost 90g and require 150 riding. This is a (partial) later change from 1.12.1.

CORRECT BEHAVIOR
Both mounts cost 800g (640g at exalted) and require no riding skill. In 1.12.1 it should cost 10g and require 150 riding skill.

SOURCES
Correct prices and riding skill requirements from the versions currently live on all realms:

https://web.archive.org/web/20060427210350/http://wow.allakhazam.com/db/item.html?witem=19029

https://web.archive.org/web/20060527020825/http://wow.allakhazam.com/db/item.html?witem=19030

https://web.archive.org/web/20050730083407/http://www.thottbot.com/?i=40565

https://web.archive.org/web/20051214025306/http://www.thottbot.com/?i=40560

Blue post detailing the 1.12.1 mount cost and skill changes:

http://blue.mmo-champion.com/topic/39485-patch-1121-riding-skill-changes/

**Comment by GuybrushGit** [comment]
IMO mount prices should be left in its current state. 
Its not just AV mounts, all mounts and training prices varied a lot from patch to patch. If they did patch accurate prices then we could just buy the skill when the mounts are expensive and the skill cheap, wait 1 patch and buy the mount when the prices flip around.

People back then didn't know the prices would switch since it wasn't announced, if they were to implement this people would just abuse it and get epic mounts for 1/10 of the price.

**Comment by Wrata4163** [comment]
There never was a time, in Vanila WoW, where you could get epic mount for 1/10 of the price.

The prices and requirements changed once with 1.12.1 patch. The cost swap that you are talking about happend with release of 3.0 patch at the end of TBC when they swaped prices of riding skill and mounts due to achievements for collecting mounts which was intended to be massive gold sink(oh boy and it was and still is).

But during vanila there were no such changes.

AV mounts were a bit cheaper compared to racial mounts(640g vs 810g) but you had to spend  time in AV to get exalted, and that was the reason why it was cheaper and didn't require ANY riding skill. This was changed in 1.12.1 to require 150 riding skill and cost of 10g. This was done in order to make it cheaper to swap out epic mounts. And by that time there were a lot of them. And this change actualy made the AV mount obsolete since it required you to pay same money for skill as your racial mount (720g) and you had to spend time in AV to get the exalted rep. And even if you already had exalted, it would be just a little bit bit cheaper than racial mount and still more expensive than original price.

**Comment by Wrata4163** [comment]
+1 for closing without response...

**Comment by thepparker** [comment]
See https://github.com/elysium-project/server/pull/1321
