### ISSUE TITLE
Field-Duty quest

### ISSUE THREAD

**Issue by kallenavn** [elysium-project/server#2555]
The Field duty quest starts, but nothing spawns..Krug Skullsplitter will yell "Something is coming!" "Shai, Merok! To my side!" "Strength and Honor!" but then...nothing happens..It has been like this for a long time, and it prevents us from finishing the field duty papers.. Please help out with this.
I see fixes has been done 12days ago (https://github.com/elysium-project/server/pull/2348) , I don't get how this cruical thing wasnt fixed, but maybe people havent reported it.
Thank you for your time, once again!

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55357-anathema-updates-27092017/
