### ISSUE TITLE
[Elysium PVP] 09-13-2017 Gurubashi Event still doesn't work!!

### ISSUE THREAD

**Issue by merlsti** [elysium-project/server#2557]
Issue is as the title says.
Below a link of a 2 min long video proof. Captured today from 14:59 ST to 15:01 ST:
https://www.youtube.com/watch?v=iH4gOgcK6co&feature=youtu.be

**Comment by thepparker** [comment]
The patch on Elysium was reverted due to unforeseen issues, we should have them resolved by next week's maintenance

**Comment by merlsti** [comment]
Thanks for a quick response.
