### ISSUE TITLE
Elysium Quest - Message to the Wildhammer

### ISSUE THREAD

**Issue by Nimeto** [elysium-project/server#2558]
The Quest should be given by Otho Moji'ko (Cooking Supplies) in Revantusk Village, but when i talk to him it just open up the buy/sell window, cant accept quest.
It was added on patch 1.5 and should be acceptable for level 44 and up (im 46).
I already deleted WDB folder but cant accept it.

**Comment by lovemonkeyz** [comment]
https://github.com/elysium-project/server/issues/1627

Existing issue, already reported.
