### ISSUE TITLE
Consecrated Sharpening Stone should last for 1 hour. (only last for 30 mins atm)

### ISSUE THREAD

**Issue by dabadoo** [elysium-project/server#2566]
On Anathema Consecrated Sharpening Stone is only active for 30 mins when it should last for 1 hour.

http://db.vanillagaming.org/?item=23122
https://web.archive.org/web/20070522002650/http://wow.allakhazam.com:80/db/item.html?witem=23122

I have only been able to find sources that state the buff should last for a hour.

Once the scourge invasion is over these will no longer be farmable so it would be nice to have them work properly for naxx.

Blessed wizard oil is possibly also affected by the same bug, but I have not tried checking myself.

**Comment by Lurkkihunter** [comment]
http://wowwiki.wikia.com/wiki/Consecrated_Sharpening_Stone?oldid=195538   wowwiki says the same

**Comment by GuybrushGit** [comment]
Its a retail bug still that they never fixed: http://www.wowhead.com/spell=28891/consecrated-weapon

The tooltip says 1 hour but the spell data says 1800 secs (30 mins). Hard to tell what they intended but every other stone is 30 mins.

**Comment by dabadoo** [comment]
Is it not possible that sites like wowhead just assumed 1800 secs since like you said every other stone last that long?

The consecrated stones are clearly different from other sharpening stones since you can only hold a max of 20 and the mats are only farmable during the scourge invasion. It seems reasonable to assume that blizzard did intend to make them last longer than ordinary sharpening stones.

It also seems strange that if the stones only lasted for 30 mins, someone, somewhere surely would have commented that the tooltip didn't match the actual duration.

**Comment by GuybrushGit** [comment]
That data is not assumed its extracted from the client.

**Comment by gemt** [comment]
We will not fix this. As GuyBrush has explained, this is a bug from the client files. If someone would be able to find a vanilla video/screenshot showing it with >30 min remaining duration the duration could be changed. In that case, please open a new report.
