### ISSUE TITLE
Deleting WDB folder doesn't fix the problems

### ISSUE THREAD

**Issue by Articled** [elysium-project/server#2571]
So my Boreal Mantle [http://db.vanillagaming.org/?item=11782]() instead of +8 Inte, +5 Stam +29 Frost Spellpower has +10 Frost Res and +29 Spellpower. 

I tried deleting the WDB folder so the casche of the game will reset but it didn't work. I am open for suggestions. 

PS. There might be problems in other parts of the game I didn't notice.

**Comment by GuybrushGit** [comment]
Server? If Elysium its not a bug.

**Comment by Articled** [comment]
Elysium. So the item changes in later patch?

**Comment by GuybrushGit** [comment]
Yes
