### ISSUE TITLE
Spineshatter missing 5 defense

### ISSUE THREAD

**Issue by Xenoq** [elysium-project/server#2573]
--

Elysium Patch 1.6
Spineshatter was introduced in bwl patch as a drop from razorgore, currently it has no defense, but it was introduced with 5 defense and never lacked it.

Other stats are correct, just lacking 5 defense.

**Comment by henkethebenke** [comment]
This is the earliest info I can find using archive.org:
[Thottbot 19 July 2006](https://web.archive.org/web/20060719171315/http://www.thottbot.com:80/?i=40784)
[Allakhazam 12 February 2006](https://web.archive.org/web/20060212091836/http://wow.allakhazam.com:80/db/item.html?witem=19335)

Both have 5 defense added. But I remember it lacking defense back on Nostalrius. Maybe they had a reason for this.

**Comment by Infiren** [comment]
+1

**Comment by GuybrushGit** [comment]
Fixed with new progressive database.
