### ISSUE TITLE
Mage issues

### ISSUE THREAD

**Issue by tinkernut21** [elysium-project/server#2574]
First of all, thank you for taking the time to report this issue.

Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. You should open a ticket
in game and wait for the response of a gamemaster. They may redirect you to this
bug tracker if they believe there's a server issue that they cannot help you
with.

Before writing your report, please do read and consider the following points to
increase the quality of your report.

- Search the issue tracker for open and closed issues before opening a new
  issue. You may be able to contribute additional facts by commenting on
  existing issues instead of adding extra noise in a separate issue.

- http://www.wowhead.com/ and http://db.vanillagaming.org/ are not valid sources
  for quests, items etc., instead, please use archived versions of
  http://wow.allakhazam.com or http://www.thottbot.com through
  https://archive.org/.

- Validate the date and time of the archived sources to a certain patch. The
  patch release dates can be found on the corresponding WoWWiki article, as
  found at http://wowwiki.wikia.com/wiki/Category:World_of_Warcraft_patches.

- Videos are valid if and only if the footage contains a timestamp or
  information that confirms the time it was recorded. Date of upload is NOT
  valid and does not confirm when it was shot.

- Read the Effective Bug Reporting article at
  https://github.com/elysium-project/server/blob/development/docs/CONTRIBUTING.md
  which covers these points and more.

Once you've read this message, delete it and write your report below.

--

Write your report here
Hello I have noticed clearcasting no longer does what it used to do in vanilla, it used to be able to proc from each hit with arcane explosion, so if you hit more mobs with it, it was a higher chance to proc. I used to play mage in vanilla and i know what i am talking about. And also clearcasting was able to proc from any of the arcane missle hits. The talent literally says it can proc from each spell hit and that is exactly how it was back then. I am not sure who convinced you guys that it was a 10% from each spell cast but this is wrong. I remember how it was back then and I am telling you that the recent nerf to the ability was not in the orginal game. Please fix this mage issue and return it to the way it was supposed to be.

**Comment by Haiwuu** [comment]
Post proof.

**Comment by Sabre142** [comment]
At least delete the wall of text first

**Comment by thepparker** [comment]
Incorrect, please see https://www.youtube.com/watch?v=3O_pNDc73MM&feature=youtu.be&t=819. For more information, consult https://github.com/elysium-project/server/issues/1868
