### ISSUE TITLE
[Elysium]Missing Thorium Brotherhood reputation repeatable quests

### ISSUE THREAD

**Issue by avenflar** [elysium-project/server#2579]
The following repeatable quests for the Thorium Brotherhood are missing from the game : 
https://wayback.archive.org/web/20051224153908/http://wow.allakhazam.com:80/db/quest.html?wquest=8241

https://wayback.archive.org/web/20051214043541/http://wow.allakhazam.com:80/db/quest.html?wquest=8242

They're supposed to be given by https://wayback.archive.org/web/20060208062259/http://wow.allakhazam.com:80/db/mob.html?wmob=14624 until you reach "Friendly".

**Comment by Sabre142** [comment]
Added in a later patch.

**Comment by Phoosy** [comment]
Use the search function.

https://github.com/elysium-project/server/issues/1365
https://github.com/elysium-project/server/issues/1435
https://github.com/elysium-project/server/issues/1385

Duplicate and invalid.
