### ISSUE TITLE
creating account

### ISSUE THREAD

**Issue by sdurao91** [elysium-project/server#2586]
So I went to make an account today and no email was being sent for verification so I did as told and sent via control panel.. still nothing so i tried to send a few more times and it must have timed out. now i get an error prompt saying i have asked for too many requests. How do i go about fixing this problem now

**Comment by Spionida** [comment]
Go this forum [page](https://forum.elysium-project.org/forum/474-account-website-forum-related-issues/) for advice. The lockout will wear off after an hour, approximately.
