### ISSUE TITLE
[anathema] NPC 'Number Two' way too overpowered and not blizzlike I think.

### ISSUE THREAD

**Issue by jobjorgos** [elysium-project/server#2587]
Hello, 'Number Two' is a 61 elite in Winterspring which is very hard to kill by anybody since it has the following stats:
Damage: 8000 - 8500 (Physical) (something like 3000 actual damage against me level 60 tank)
Armor: 5000
and something like 300.000 - 700.000 health? i cant see it even with addons.

It kills me in 2 hits while I am one of the best tanks around, even raids of 10 people dont have a chance to kill it. it is 61 elite but it feels like a ?? elite boss! I think he is way overtuned and that in orginal vanila this mob just hit something as 500 each hit so it could be 3 manned easily.
Because it is impossible to get 30 people for this quest, i tried to kite the boss with a hunter to everlook, there it killed all 20 goblin guards including 4-5 players and he had still 95% hp! he just one shotted all goblins, that is not supposed for a 61 elite i guess? 
right now the only way to complete the quest 'Decoy!' from where this NPC spawns, is to kite him with a hunter to thralls hall in orgrimmar. 

I have the following sources, and might not proper ones like db.vanilla.org but still they look way more realistic.

http://db.vanillagaming.org/?npc=15554
that says Number Two is: 
Level: 61
Class: Elite
React: A H
Faction: Monster
Health: 78,600
Wealth: 1
Damage: 532 - 684 (Physical)
Armor: 4,091
Model: 10133

https://web.archive.org/web/20071120150913/http://www.wowhead.com:80/?npc=15554
that says Number Two is: 
Level: 61
Classification: Elite
React: A H
Health: 78,000

Im not 100% sure that this NPC is really overtuned compared to how he was back in vanilla 12 years ago, but I guess it is the case, and would be glad if thats true it can be nerfed.
thanks in advance for looking at this!

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
