### ISSUE TITLE
[Anathema] Patch 1.11 Naxxramas - Unable to Learn Patterns from Omarion

### ISSUE THREAD

**Issue by ramangan** [elysium-project/server#2612]
In the Military Wing, Master Craftsman Omarion gives you a quest to return his handbook to Lights Hope Chapel. This opens the quest to have the epic frost resistance pieces crafted for a small fee from Lights Hope. There is also another option where you tell Omarion that you are a master leatherworker, blacksmith...etc. and you should have the option to learn these patterns from him (if you have the right rep with Argent Dawn). Currently, clicking these options does nothing.

**Comment by ramangan** [comment]
This is now fixed.

**Comment by gemt** [comment]
Fixed with hotfix patch on Monday 18th September 19:00
