### ISSUE TITLE
bubble hearth is still bugged - being hit while bubble hearthing

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#2614]
I end up bubble hearthing and Im still hit for 2 massive hits by the npc when I arrive at the inn keeper. I guess it was never fixed.

https://youtu.be/cDCM_rrbzmk (sorry for the language)

Can someone please fix it. It caused me to fly outside stormwind from hearthing from tarren mills flight master  https://github.com/elysium-project/server/issues/1446 (same report)

This is what would happen if you die when you bubble hearth https://www.youtube.com/watch?v=5F8XAOV-X9I

**Comment by Mostprovidedlinks** [comment]
Also I forgot to mention but that npc is neutral and is going around everywhere hitting everyone

**Comment by Mostprovidedlinks** [comment]
I took over 900 damage because of it

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit did this get fixed?

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit This still hasnt been fixed.

why close it? I just tested it today still not fixed

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit ty for adding it to prevent death teleport guy

**Comment by GuybrushGit** [comment]
Same as https://github.com/elysium-project/server/issues/1446
