### ISSUE TITLE
Reckoning talent in Paladin Protection tree broken

### ISSUE THREAD

**Issue by Jolken71** [elysium-project/server#2619]
I just recently maxed out 5/5 Reckoning just to notice it never ever triggers. I tried /sit but it does nothing (Redoubt triggered as usual). I tried getting crit as usual without /sit and Reckoning still doesn't trigger (Redoubt does as usual). Nothing of it in the combat log. No "feeling" the extra hit on the mob (I didn't do that for the earlier 1/5, 2/5 etc increments of Reckoning either). 

I spoke to another Paladin about this issue who were specced into Reckoning back in June (had now changed to Retribution because he felt Reckoning didn't do enough damage, although he tells me it actually did trigger). 

Didn't see anything of this sort on the bug tracker and never heard it on reddit or ingame. I feel like it would be a well-reported issue because it is after all a proper popular leveling talent, but alas...

Disclaimer: I hope this isn't just me completely misunderstanding the talent. If so just strike me right in the dome and call me Robin.

**Comment by Mostprovidedlinks** [comment]
which mob is hitting you? or is it a player

**Comment by Mostprovidedlinks** [comment]
I tested it and its working on anathema

**Comment by theloras** [comment]
you get no notice or "buff" when you gain a reckoning charge in Vanilla - nor does it show up in the combat log either - download the reck counter addon and enjoy 1shotting horde with it:

http://www.mediafire.com/download/3aw939ny2a1f2i2/ReckCounter.rar

**Comment by TimEsfandiari** [comment]
Jolken you have to relog, I've had this bug once before too right after respeccing but the relog fixed it.

**Comment by Mostprovidedlinks** [comment]
Can this be closed

Not a bug
