### ISSUE TITLE
Gold ore have same look as copper ore

### ISSUE THREAD

**Issue by ZeGaaL** [elysium-project/server#2621]
Hey i have a picture of the bug my gold ores look like copper ore: http://prntscr.com/gmdit3 just Look here. Small fix, but good to have correct.

**Comment by Mostprovidedlinks** [comment]
i second this fix for ah

**Comment by MarkusNemesis** [comment]
This is a client issue, not something they can fix.

Also, the icon is correct: http://db.vanillagaming.org/?item=2776
