### ISSUE TITLE
Pattern: Black Whelp Tunic Unavailable

### ISSUE THREAD

**Issue by Phoosy** [elysium-project/server#263]
NPC Amy Davenport (777) in Redridge, Lakeshire does not appear to sell the Pattern: Black Whelp Tunic (20576). She is supposed to offer a Limited Supply of 1 per 'refresh'. Per my sources, it appears to have been referenced as far back as launch (Archive date May 10, 2007 and post made ~18 months prior ~= Nov 2005), so it definitely is not patch-locked.

Source: https://web.archive.org/web/20070703105313/http://www.thottbot.com/c777
Source2: https://web.archive.org/web/20060114201119/http://wow.allakhazam.com/db/item.html?witem=20576

**Comment by slacker3007** [comment]
http://wowwiki.wikia.com/wiki/Pattern:_Black_Whelp_Tunic
Patch 1.8.0 (10-Oct-2005): Added.

**Comment by Phoosy** [comment]
Welp I'm a yuge dumb cat. Closing this.
