### ISSUE TITLE
Cat Carrier (White Kitten) Not Limited Supply

### ISSUE THREAD

**Issue by Phoosy** [elysium-project/server#264]
It appears Lil Timmy (8666) in Stormwind offers unlimited Cat Carrier (White Kitten) (8489) when he should only be offering 1 per respawn.

**Comment by shmigy429** [comment]
Are there any similar time restocking items, working correctly, that I could compare it to? But yeah, you are right, Timmy (8666) is selling an unlimited amount of these Cat Carriers (8489).
