### ISSUE TITLE
Druid talent - heart of the wild Intel boost not working

### ISSUE THREAD

**Issue by smiless** [elysium-project/server#2642]
Hello guys,

I would like to report the following bug related to the talent `Heart of the Wild` which is supposed to increase the intel by x% percent.
It seems he doesn't as you may see in the following screen, 
I have `77 intel + 1` but I don't have any stuff with an intel bonus so I suppose the +1 come from nowhere

Currently this talent is supposed to improve my intel by 16%. Correct me if I'm wrong but the bonus should be near 12, so ~89 instead of 78.

Moreover when I shapeshift, the bonus related to the shape increase with the correct value, so it's seems only intel is affected.

![wowscrnshot_091917_122718](https://user-images.githubusercontent.com/7648231/30589160-9de0d780-9d39-11e7-93f4-18021545ce7b.jpg)
![wowscrnshot_091917_122707](https://user-images.githubusercontent.com/7648231/30589161-9de27c16-9d39-11e7-9c3f-7a637a8ca5cd.jpg)

After cleaning my cache, I got `78 intel`  with no bonus as you may see  (no stuff and no addons this time)

![wowscrnshot_091917_130121](https://user-images.githubusercontent.com/7648231/30589528-1bf9c69e-9d3b-11e7-9551-7a1f359008d0.png)
![Uploading WoWScrnShot_091917_130125.png…]()

**Comment by adura90** [comment]
Basically, the answer is that the bonus is added ONLY to your base intellect. It is not added as a bonus (in green).

**Comment by QAkvastskaft** [comment]
Invalid:
Talent works on internal test realm, there is no bonus only a change of the base (white) int
