### ISSUE TITLE
Viper Sting shouldnt drain druids mana while shapeshifted

### ISSUE THREAD

**Issue by gustanoid** [elysium-project/server#2647]
"Viper sting will not drain mana from Druids while they are shapeshifted." - Patch 1.5.0 released on 06/07/2005 - http://web.archive.org/web/20061110080240/http://www.worldofwarcraft.com/patchnotes/patch-05-04-19.html

"Viper Sting - This spell can no longer be used on warrior and rogue targets. In addition, while it can be used on a druid target at any time it will only drain mana when the druid is in caster form." - Patch 1.4.0 released on 05/05/2005 - http://web.archive.org/web/20061110080240/http://www.worldofwarcraft.com/patchnotes/patch-05-04-19.html

**Comment by Fiskehatt** [comment]
I think it is currently working as intended; draining your mana in both Travel and Aquatic form (where you have mana instead of energy or rage) and not draining in Cat or Bear form.

### Source
http://darksoda.com/blog/?cat=3 quotes a post on the WoW forums on 2006-07-14 - patch 1.11.2(?):

> Viper sting will not drain your mana if you are in cat or bear form. However innervate will regenerate you mana while you are in cat or bear form.

**Comment by GuybrushGit** [comment]
Most likely a case of misleading patch notes. Travel form has a mana bar it should be able to lose it.
