### ISSUE TITLE
[1.11] Can't enter Hall of Legends without currently being rank 6+

### ISSUE THREAD

**Issue by 0vertime** [elysium-project/server#2648]
Use to be able to enter with highest rank, after naxxramas patch you can't do that anymore. 
Now it's requiring you to be at least Stone Guard.

in-game: https://i.imgur.com/cIOWLYs.jpg

Was possibly already broken with AQ 1.9 patch.

**Comment by Brainzy** [comment]
It is how it was in vanilla. https://github.com/elysium-project/server/issues/761

**Comment by 0vertime** [comment]
It was changed on Nostalrius specifically. Elysium did blizzlike way.
