### ISSUE TITLE
Elysium - Bug- Item - Scouting Tunic of Quality +7 damage don't work.

### ISSUE THREAD

**Issue by Towarese** [elysium-project/server#2657]
Hello,

I want repport a bug : 

**Scouting Tunic of Quality +7 damage don't work.**

I'm druid 29 and i have too the "Magician Staff of Quality" and he is work.

Can you repar the bug from Scouting Tunic of Quality please?

Thank,

Towarese.

**Comment by lovemonkeyz** [comment]
There's no "Of quality" item affix in Vanilla, what are you talking about? 

One attribute suffixes
of Strength: Strength
of Agility: Agility
of Stamina: Stamina
of Intellect: Intellect
of Spirit: Spirit
of Blocking: Block rating (and strength)
of Eluding: Dodge rating (and agility)
of Defense: Defense rating
of Regeneration: Health regen
of Concentration: Mana regen
of Power: Attack Power
of Marksmanship: Ranged Attack Power
of Healing: Adds to +healing (and spell damage)

Two attribute suffixes
of the Tiger: Strength and Agility
of the Bear: Strength and Stamina
of the Gorilla: Strength and Intellect
of the Boar: Strength and Spirit
of the Monkey: Agility and Stamina
of the Falcon: Agility and Intellect
of the Wolf: Agility and Spirit
of the Eagle: Stamina and Intellect
of the Whale: Stamina and Spirit
of the Owl: Intellect and Spirit

**Comment by Phoosy** [comment]
You've duplicated your report, but seeing as how the other issue has more info on it this one should be closed.
