### ISSUE TITLE
Can delete

### ISSUE THREAD

**Issue by Derpyous** [elysium-project/server#2659]
Can delete

**Comment by ItsmeAga** [comment]
it gives the correct attackspeed bonus, attackspeed % works different than you think. For example 100% attackspeed does not reduce the swing timer to 0. Instead speed is increased like this 1/(1+0.3) for 30% faster attackspeed, which exactly matches the numbers you posted above

**Comment by Derpyous** [comment]
Cool. I stand correct :)
