### ISSUE TITLE
NPC Geologist Larksbane (15183) does not belong to her faction (Cenarion Circle)

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#266]
NPC Geologist Larksbane (15183)* should be a member of the Cenarion Circle faction.

*http://db.vanillagaming.org/?npc=15183

As such, the npc can be attacked and killed by players if they chose to be "At War" with Cenarion Circle.

Current state of the NPC : http://imgur.com/a/xHYS8
No faction and if "At War" with Cenarion Circle, displays "Invalid Target" error message.

**Comment by StadenElysium** [comment]
This was done intentionally on Anathema to prevent her from being kited away from her spawn and dumped in random locations. It's a temporary fix until:
1) Guards defend NPCs from being attacked
2) NPCs return back to the original spawn points rather than getting stuck.
