### ISSUE TITLE
Twilight Cultist's not dropping gear/texts anymore.

### ISSUE THREAD

**Issue by Mosquito10** [elysium-project/server#2665]
Been killing the Twilight Cultists in Silithus for over 2 hours. I haven't gotten a single gear piece, nor any texts off them. Is it possible that this is bugged?

Greetings

**Comment by Drabic** [comment]
also faced this problem

**Comment by Weywu** [comment]
still no drops, bump

**Comment by QAkvastskaft** [comment]
See: #1588
