### ISSUE TITLE
Your system deranked me

### ISSUE THREAD

**Issue by Polnoch21** [elysium-project/server#2666]
Hello,

first of all, I have been ranking on retail vanilla and as well on several private vanilla servers and according to my knowledge and experience, when you do not pvp for a week,which practically means that you get less than 15 hks in that specific week, it means that you freeze and you are not considered as a person who did pvp, therefore you stay the same rank and % as you were.

And basically what happened to me is that I played to lot for couple of weeks so I could achieve rank 10 alone. Once I got this rank, I felt like I need to take a break for a week or two and focus on another things like running dungeons, leveling professions and farming gold. And thats what I did last week, I did no pvp, I have 0 hks and 0 honor for last week, I did avoid all possible encounters and several times I even had to surrender to lvl 60 horde killing me to be sure I do not get any hks. And what happened is that I deranked to rank 9 and 50% even tho I have 0hks and 0 honor last week. I have already talked with GM and he told me to report this issue here. I would really apprecite if I can get my rank back or atleast to get some kind of explanation because this is not how the vanilla pvp system should work. Thank you. My character is Polnoch.

**Comment by Nelythia** [comment]
It never worked like that.
It did actually happen like this if you were banned on Nostalrius, you could get yourself banned for even just 1 day and it freezes you for that week.

Other than that, not supposed to do that and never was supposed to do it

**Comment by Polnoch21** [comment]
Nelythia thank you for your reply. So you are sure you would actually derank even though not paricipating in pvp at all? It was not like that on ED but it is possible it was like that on retial even though I remember it differently.

**Comment by Nelythia** [comment]
I am very sure, yes.
