### ISSUE TITLE
The Missing Courrier

### ISSUE THREAD

**Issue by Halshugning** [elysium-project/server#2670]
Hi. I had trouble for the quest "The missing courrier" in Feralas. I'm supposed to find a wrecked boat on the shore, and so do I had, but when I click on it, nothing happens. Can you help, please ? :)

**Comment by brotalnia** [comment]
You clicked the wrong boat. The one you need is in the water, not on the shore.

**Comment by Cabro** [comment]
Both of them should complete the quest. Check wowwiki :)

**Comment by Halshugning** [comment]
You was right about the underwater boat. Shame on me. Thanks !
