### ISSUE TITLE
Triage quest cause server crash

### ISSUE THREAD

**Issue by mpfans** [elysium-project/server#2672]
https://github.com/elysium-project/server/commit/a35859c2694e697f37c21ce174aef66a23bb796d

quest id: 6622

get this quest,and the quest failed..the server crash

**Comment by brotalnia** [comment]
No check if pPlayer is nullptr here -> https://github.com/elysium-project/server/blob/a35859c2694e697f37c21ce174aef66a23bb796d/src/scripts/world/npcs_special.cpp#L496

**Comment by thepparker** [comment]
Resolved in dev branch. Neither changes are live.
