### ISSUE TITLE
[Harvest Fest] Typo at 'Monument to Grom Hellscream'

### ISSUE THREAD

**Issue by Nelythia** [elysium-project/server#2674]
The seasonal quest 'Honoring a Hero' for the Horde sends you to the Demon Fall Canyon in Ashenvale to give tribute to Grom Hellscream.
The quest works properly and as intended, however the Monument to Grom Hellscream has a little typo or encoding issue, as it makes out of a ' a ?
https://i.imgur.com/BZ0wYZP.jpg

**Comment by brotalnia** [comment]
Confirmed, I'll fix it soon.

**Comment by Nelythia** [comment]
Closing it myself since it got fixed.
