### ISSUE TITLE
Juju's should currently not be available on Elysium-PVP

### ISSUE THREAD

**Issue by carn222** [elysium-project/server#268]
The quest to obtain the various Juju's wasn't added until 1.11.1, and like the oils, should be removed until that time.

http://wowwiki.wikia.com/wiki/E%27ko
http://www.wowhead.com/quest=4801/frostsaber-eko

**Comment by StadenElysium** [comment]
Wowhead is not a reliable source for vanilla data. Marking as invalid without additional evidence.

**Comment by carn222** [comment]
Doesn't that make it clear that she shouldn't be in Winterspring?

**Comment by StadenElysium** [comment]
Yes, although that's not what this issue was about.

**Comment by carn222** [comment]
Shall I make another one about moving her back to Orgrimmar then?

**Comment by martinjlowm** [comment]
You can refer to https://web-beta.archive.org/web/20070815125842/http://wow.allakhazam.com:80/db/mob.html?wmob=10307 :)
