### ISSUE TITLE
"Long Forgotten Memories" quest 22.09.2017 Anathema

### ISSUE THREAD

**Issue by Francheskoo** [elysium-project/server#2686]
Greetings! 

After grabbing quest from Anachronos to locate crystalline tear and click it near AQ gates quest opens but when you click "Complete quest" just nothing happens.

P.S. I've already tried to delete WDB folder, abandon quest and take it again from Anachronos but it doesn't help.
screenshot here https://imgur.com/a/tM5FS

Best regards!

**Comment by QAkvastskaft** [comment]
See: #2467
