### ISSUE TITLE
Witch Doctor Mau'ari should be in Orgrimmar on Eyslium-PVP

### ISSUE THREAD

**Issue by carn222** [elysium-project/server#269]
In the current patch on Elysium, Witch Doctor Mau'ari should be placed in Orgrimmar, rather than Everlook

https://web-beta.archive.org/web/20070815125842/http://wow.allakhazam.com:80/db/mob.html?wmob=10307

http://wowwiki.wikia.com/wiki/Patch_1.7.0

**Comment by martinjlowm** [comment]
Here's a (not very reliable) source stating her position to be (36,81): http://wow.gamepressure.com/npc.asp?ID=2419

**Comment by m-laniakea** [comment]
Belongs in https://github.com/elysium-project/itemization
