### ISSUE TITLE
[Multiple Judgement Stacking Persisted Throughout Vanilla] *Undeniable Proof Here*

### ISSUE THREAD

**Issue by Hyperial** [elysium-project/server#2696]
Hi and thank you for looking into this.

As per the guideline set forth by your staff I am linking below the evidence that multiple rankings of the same type of judgements were in game through out all of Vanilla and till at the very latest 2.4 patch in BC.

http://wowwiki.wikia.com/wiki/Patch_2.4.0

You can Alt+F the word "judge" for quick reference.

When I looked at the most recent patch notes I was in shock to find this inaccurate implementation when I strongly recall waiting for and making use of the multiple ranks post ZG when I was able to make use of A few open debuff slots as a retribution paladin.

The guide lines mentioned to use sites like wowwiki as a resource well here it is.

Please bring back multiple ranked judgements.

Thank you.

**Comment by Phoosy** [comment]
You're misreading the note entirely as that one has already been referenced before. You're reading it as "we're no longer showing multiple icons for a debuff because it's redundant" when you should be reading it as "we're no longer showing multiple icons for a debuff because it's giving false information."

To quote myself when this was brought up last time:

> This clearly says "There should not be the visual appearance of differing ranks of Judgements applying on a target", which the means by extension "This isn't actually applying twice and it was a visual bug. If it were applying in both instances, we should show it to you as we should be showing you all the applied debuffs on a target because that is the basic design of this game, but since it's not actually applying we're not going to show it to you like it is."

I do not know how you're getting "Multiple ranks of a Judgement can be applied to the same target" out of "it wasn't intended to display multiple ranks of the debuff for this Judgement"

**Comment by Hyperial** [comment]
#Phoosy Are you suggesting that this bug did not exist on retail vanilla? or that multiple ranks were just showing and not actually attributing to damage? This isn't an attempt to convince by attrition.

I just literally looked through every patch update since 1.1 and there was no fix for the "bug" that actually brought about the stacking judgements.

In the post made by Imba he links a quote off a Alakazam site from a random player named Cathela who states "quote" 

Quote:
Multiple paladins can stack different ranks of the judgements on the same mob. The last time my raid group killed Ragnaros we didn't have enough priests to do AoE heals on the rogues, so the three paladins in the melee groups coordinated different ranks of Judgement of Light on him, and the rogues and dps warriors ended up healing themselves a lot.

**Reportedly** ??  this was nerfed in the 1.8 patch so that now you can only have one rank each of JoW and JoL on a monster, **though I haven't had a chance to confirm this.** WTF?? rly?

Also, there's apparently some kind of aggro screwup when JoL and JoW proc since the patch. Not sure if this has been hotfixed or not. " end quote.

The guy said he hasn't confirmed. Yes this was a known bug that was never fixed, I was there and looking through the source code this existed. Again, I am not trying to debate with you or engage you in anyway. If anyone sifts through every patch you won't find anything about finding a fix to the judgements actually stacking and adding to damage.

**Comment by thepparker** [comment]
This has been discussed many times. Look at the existing issue reports and see the reasoning why this is a bug and is no longer a feature on this server.
