### ISSUE TITLE
NPC Melee Dodge Chance

### ISSUE THREAD

**Issue by malekoydaerb** [elysium-project/server#2698]
Dodge
Dodge
Dodge
Miss
Dodge
Dodge
308
Dodge
Dodge

this is what my combat text looks like on average of late. per like every guide i've ever seen or read, and per the "reserach" of the guy who changed the weapon skill formula a month ago; npc dodge chance should be 5.6%. there is clearly something wrong when i as a fury war running 309 weapon skill and 13% hit am getting continuous dodges with yellow attacks back to back to back. can someone who knows this code please go in and check on the melee hit tables, because something is very broken and has been for about a month...

**Comment by BrynjaDarrow** [comment]
I just checked the stats of several DPS warriors from several raids on Elysium/Darrowshire/Anathema on Legacy Logs and I can't find anything unusual about the dodge percentage. It's almost always between 5-7%.

**Comment by gemt** [comment]
This report is not extremely helpful without some logs/screenshots/video. If you truly believe there is something wrong, please make a new issue with some of that. Have personally not had any issues with this either.
