### ISSUE TITLE
My voidwalker has hunter pet spell ... 

### ISSUE THREAD

**Issue by Khozak** [elysium-project/server#2699]
Hi, my problem is my voidwalker, he has hunter pet spell max lvl he cant use this but this spell block my book for learning his spell this said your pet can't learn any spell. I dont want delete my warlock just for that so i need help this ruin my gameplay

**Comment by Khozak** [comment]
its is open need answer plz this ruin my gameplay

**Comment by QAkvastskaft** [comment]
Please see: #2736 for possible solution
