### ISSUE TITLE
[Quest] A Hero's Reward

### ISSUE THREAD

**Issue by Xantium995** [elysium-project/server#271]
Currently, the quest A Hero's Reward (id 7486) is not obtainable after completing Hands of the Enemy (id 6824), which is I believe the only requirement to unlock the last quest.
This quest, given by Duke Hydraxis, has been added to the game as part of patch 1.3.
I haven't found any reputation requirements for this quest, so I suppose it should be pickable with the Honored reputation level.

http://db.vanillagaming.org/?quest=7486
http://wow.gamepedia.com/Quest:A_Hero%27s_Reward

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
