### ISSUE TITLE
Long Forgotten Memories doesn't complete

### ISSUE THREAD

**Issue by Kraggenlord** [elysium-project/server#2711]
Before Naxxramas released the crystal in front of the AQ gates didn't spawn.

When I went there today I noticed that it actually spawns now so I went up and clicked on it. When I clicked on it, this is what I recieved: https://i.imgur.com/g6pMeeT.png

I tried clicking on complete quest but it would not complete or show me the supposed cutscene, whether it should play the cutscene before or after the quest completes. I deleted my WDB folder and deactivated all my addons and tried again but it still did not work. As far as I know, Anachronos doesn't give you a quest item to use during the quest as well so I shouldn't be missing anything in order to complete the quest.

Here is a video showing what happens: https://www.youtube.com/watch?v=eW0J0yL7nS0

This experience was the same with or without addons, before and after I deleted my WDB folder.

**Comment by QAkvastskaft** [comment]
See: #2467
