### ISSUE TITLE
Kel'Thuzad mind control issues

### ISSUE THREAD

**Issue by ironmilk** [elysium-project/server#2712]
In Kel'Thuzad combat, the player is released from the mental control and will cancel the combat status and will not immediately enter combat, causing the healer to resurrect other dead players.

**Comment by ImperfectCell** [comment]
@ironmilk hey ironmilk, does lich king talk? on anathema? do u hear him talk to keltuzad or no?

**Comment by gemt** [comment]
Thanks for the report. It should no longer be possible on Wednesday.
