### ISSUE TITLE
s

### ISSUE THREAD

**Issue by ImperfectCell** [elysium-project/server#2719]
Working as intended

**Comment by Mostprovidedlinks** [comment]
PPM as an expression of flat proc rate.
Mace has 2,3 sec swing time
That's ~26,8 swings per minute
2/26 = ~8%
Proc rate. Where 2 is PPM value(edited)

**Comment by ImperfectCell** [comment]
I think it was fixed in recent update. Not 100% Going to test it again

**Comment by ImperfectCell** [comment]
Still not 8% chance. Tested it
