### ISSUE TITLE
Loatheb "skipping" Inevitable Doom

### ISSUE THREAD

**Issue by Whiskra** [elysium-project/server#2720]
It appears that Loatheb will sometimes "skip" an Inevitable Doom, and not a single player in the raid gets the debuff when they should be. This makes the fight a lot easier obviously, since the damage from the skipped Inevitable Doom is gone all together. This can be seen in multiple kill videos such as
 
https://www.youtube.com/watch?v=lSE0UJ_trug (3:25, 4th Inevitable Doom skipped),
https://www.youtube.com/watch?v=EXgqgDMoj9w (5:10:00, 6th Inevitable Doom skipped), and https://www.youtube.com/watch?v=YdBwiAX8VT0 (1:07:15, again 4th Inevitable Doom skipped). 

This appears to be random, as in other attempts, Loatheb might not have skipped a single Inevitable Doom (example at 1:04:00 in last video linked, previous attempt resulting in a wipe). The cause for this is unknown to me, though I suspect it has something to do with the renewal of Poison Aura somehow perfectly aligning with the next Inevitable Doom, which somehow cancels out the Doom in favor of the Poison Aura as both are lined up to be cast at the exact same time.

**Comment by gemt** [comment]
Thanks for the report. Believe I have found the issue and the fix should be live on Wednesday.
