### ISSUE TITLE
[Bloodsail Buccaneers] Quest: Dressing the Part

### ISSUE THREAD

**Issue by Nelythia** [elysium-project/server#2726]
The quest Dressing the Part - http://db.vanillagaming.org/?quest=9272 & http://wowwiki.wikia.com/wiki/Quest:Dressing_the_Part - is not available at Fleet Master Firallon upon reaching Neutral with the Bloodsail Buccaneers.

Issue was noticed by me during my Bloodsail Buccaneers reputation grind on Darrowshire.
Screenshot: https://i.imgur.com/I7LIJrw.jpg

As WoWWiki mentions the required reputation to be eligible for accepting this quest is at least Neutral, or any higher status with them.

It is likely that the quest in order to achieve the Bloodsail Admiral's Hat - http://db.vanillagaming.org/?quest=4621 - is not ingame either as of yet.
I am unable to confirm as I am not friendly at this time.

**Comment by druidish** [comment]
Darrowshire is on patch 1.8. This quest was added in 1.10 going off the quest ID and corresponding item IDs.
