### ISSUE TITLE
Anathema: Bugged bow for sale at "The Sepulcher" bowyer vendor.

### ISSUE THREAD

**Issue by Sedrivud** [elysium-project/server#2732]
45.0 39.4 are exact coords.

Happened at 4:57AM EST, 9-24.

Attempting to relog and fix the problem, that below happened.

![wowscrnshot_092417_050623](https://user-images.githubusercontent.com/32237456/30781140-f4906a12-a0e7-11e7-916b-418629fab70e.png)

It can be fixed by simply destroying the bow or selling back to vendor. Nonetheless though, the root of the problem, which is the bow, is still bugged obviously. You just simply cannot buy/use it.

![wowscrnshot_092417_051727](https://user-images.githubusercontent.com/32237456/30781179-70e02da0-a0e8-11e7-83e5-6d1dc9368ba0.png)

**Comment by QAkvastskaft** [comment]
Cannot reproduce on test realm

Does the issue persist after deleting the WDB folder?
Please see https://forum.elysium-project.org/topic/47488-the-wdb-folder/ for more info

**Comment by Sedrivud** [comment]
All's fine..
I'm sure any regular WoW player would've known to do that, the moment they noticed the missing item name. 
Nabness is strong within me but we all start somewhere. 🤓
