### ISSUE TITLE
Crowd control duration working incorrectly

### ISSUE THREAD

**Issue by Narzilx** [elysium-project/server#2738]
After testing at the start of Elysium and further testing recently, all CC that lasts over 12 seconds is using the patch 2.0.1 formula as it was on early Nostalrius.
I have never seen a CC last over 12 seconds, and that comes from someone that ranked to rank 13.
This should be changed to how patch 1.2.0 works with a heartbeat system on CC.

Refer to this post: https://forum.nostalrius.org/viewtopic.php?f=25&t=378

**Comment by Mostprovidedlinks** [comment]
True

**Comment by GuybrushGit** [comment]
Break time is currently a logarithmic scale with 50% break chance at 12 seconds and 100% at 15 seconds.

**Comment by thepparker** [comment]
All PvP CC duration is affected by heartbeat resists, with the conditions Guybrush has mentioned
