### ISSUE TITLE
Spells that are shield/absorb type have 0 threat, when they should have threat.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#2742]
For example priest's shield has 0 threat from what i noticed, when it should be a percentage of the amount absorbed.

**Comment by GuybrushGit** [comment]
>Tests have concluded that Power Word: Shield causes approximately half as much threat as healing for the same amount. So threat-wise Power Word: Shielding for 1000 is roughly equivalent to healing for 500. However, the spell does not cause any threat, if cast before you or your target are in combat.
>https://wow.gamepedia.com/index.php?title=Power_Word:_Shield&oldid=317147

**Comment by Cabro** [comment]
Yes, i wasnt fully clear. I didnt say you should get threat when the damage you take is absorbed, but how much the shield absorbs in the moment of the cast.
My bad for that. Is it working like this on the server? It doesnt seem to be giving threat to the caster, or i could just be wrong.

**Comment by Cabro** [comment]
I see the fix, happy to see it being worked on.
However, it's all spells that have the same functionality (absorb trinkets, T3 procs etc.).
I ask you kindly to fix them all!

**Comment by GuybrushGit** [comment]
Give sources then. Threat addons have threat for PWS but not the others.

**Comment by Cabro** [comment]
It seems you are right, saw the Ice Barrier tag with "generate no threat", seems only PW:S is the one that gives threat on cast, indeed.
+1

**Comment by GuybrushGit** [comment]
Not having the no threat flag is not enough to change it, there are plenty of no threat spells that don't have it.  
There's no mention any target_self absorb generating threat. PWS is the only absorb that can be cast on anyone.

**Comment by Cabro** [comment]
Ok then!
