### ISSUE TITLE
mindcontol +blessing of protection bug

### ISSUE THREAD

**Issue by showabug** [elysium-project/server#2743]
Currently, in warsong gulch you can use mindcontrol + blessing of protection on enemy flag carrier to force him to drop the flag. This isn't working as intended as blizzard fixed this bug in patch 1.7:
Offensive use of damage immunities no longer causes the flag to drop in Warsong Gulch.
http://wowwiki.wikia.com/wiki/Patch_1.7.0

**Comment by TimEsfandiari** [comment]
#RetPrio
