### ISSUE TITLE
Channeled heals/hots don't heal if you are at 100% hp.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#2744]
Title.

**Comment by Fiskehatt** [comment]
Any proof that they should?

When you look at the following videos, you can see that after the druids have cast Regrowth and Rejuvenation on themselves, the HOTs do not heal until they lose health:

https://www.youtube.com/watch?v=TOX3jMJWhQQ#t=03m28s (3:28)
https://www.youtube.com/watch?v=d_m4lVmyDsc#t=0m36s (0:36)

**Comment by Cabro** [comment]
Seems you are right!
Closing.
