### ISSUE TITLE
Blasted lands buffs not stacking with Spirit of Zanza

### ISSUE THREAD

**Issue by dabadoo** [elysium-project/server#275]
Not sure about the other flask from ZG but spirit of zanza is not stacking with:

http://db.vanillagaming.org/?item=8410

http://db.vanillagaming.org/?item=8412

I've heard other blasted lands buffs doesn't stack either but i haven't tested those myself.

**Comment by StadenElysium** [comment]
This should be the correct behaviour.

**Comment by StadenElysium** [comment]
This was updated a while ago but if there's any evidence that it's incorrect (quite possibly is), that would be appreciated.

**Comment by dabadoo** [comment]
I just tested it on Anathema. I started by popping the zanza flask followed by roids. The roids buff removes the zanza flask buff.

**Comment by slacker3007** [comment]
not 100% confirmed, but here is guide from 2006, buffs should stack http://wow.allakhazam.com/forum.html?forum=243&mid=116255807757703971

**Comment by PlaskED** [comment]
Vague at best, as much as I'd like it to stack this isnt feenix x)

**Comment by QAClayton** [comment]
At this point it is going to be left As is unless we can find more evidence proving otherwise. Thank you.
