### ISSUE TITLE
[Elysium]Mind Vision issue

### ISSUE THREAD

**Issue by ragevayne** [elysium-project/server#2750]
-- EDITED

Thanks for the report, we are looking into it.

**Comment by ragevayne** [comment]
![wowscrnshot_092417_213632](https://user-images.githubusercontent.com/5481254/30789073-eab56cac-a170-11e7-8e0b-50a96171b5f9.jpg)

**Comment by GuybrushGit** [comment]
Thanks for the report, we are looking into it.
