### ISSUE TITLE
[Anathema] Zul'Gurub High Priest/Priestess drops incorrect number of items

### ISSUE THREAD

**Issue by delebota** [elysium-project/server#2752]
As of 1.11 the priests (Jeklik, Venoxis, Mar'li, Thekal, Arlokk) are supposed to drop 2 items and an armor token. They currently only drop 1 item and an armor token.

Quote: "After careful consideration we have decided to add an additional loot table to the High Priests of Zul'Gurub. Players should now see two items in addition to the tokens when slaying these bosses."

Source: http://wowwiki.wikia.com/wiki/Patch_1.11.0

**Comment by thepparker** [comment]
Dupe #2793
