### ISSUE TITLE
[Gothik] Spectral Trainee, Spectral Horse damage

### ISSUE THREAD

**Issue by smkrus** [elysium-project/server#2753]
Suspect Spectral Trainee (melee) and Spectral Horse (Stomp) are doing overtuned damage.
Current Spectral Trainee melee 1.8k on rogue and Horse Stomp is 3-3.5k
This video shows stomp doing nearly no damage (60-80).
https://youtu.be/BzyD8HYKBrg?t=180
This video shows Spectral Trainee vs rogue hit 345, crit 728
https://youtu.be/awjalG130fc?t=261

**Comment by gemt** [comment]
It, and some other incorrect damage values have been fixed and should be live after maintenance tomorrow.
