### ISSUE TITLE
cant long into elysium at all :( 

### ISSUE THREAD

**Issue by smokadaweeds** [elysium-project/server#2756]
First of all, thank you for taking the time to report this issue.

Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. You should open a ticket
in game and wait for the response of a gamemaster. They may redirect you to this
bug tracker if they believe there's a server issue that they cannot help you
with.

Before writing your report, please do read and consider the following points to
increase the quality of your report.

- Search the issue tracker for open and closed issues before opening a new
  issue. You may be able to contribute additional facts by commenting on
  existing issues instead of adding extra noise in a separate issue.

- http://www.wowhead.com/ and http://db.vanillagaming.org/ are not valid sources
  for quests, items etc., instead, please use archived versions of
  http://wow.allakhazam.com or http://www.thottbot.com through
  https://archive.org/.

- Validate the date and time of the archived sources to a certain patch. The
  patch release dates can be found on the corresponding WoWWiki article, as
  found at http://wowwiki.wikia.com/wiki/Category:World_of_Warcraft_patches.

- Videos are valid if and only if the footage contains a timestamp or
  information that confirms the time it was recorded. Date of upload is NOT
  valid and does not confirm when it was shot.

- Read the Effective Bug Reporting article at
  https://github.com/elysium-project/server/blob/development/docs/CONTRIBUTING.md
  which covers these points and more.

Once you've read this message, delete it and write your report below.

--

Write your report here

my toon name on elysium server can not log in. i can log into anyother of your wonderful servers but not the one i have started playing on. im a new player here and have taken all the steps to try to fix it. i have deleted all folders wtf ect.. i lagged out when starting a quest right at the starting point for the undead horde warlocks. i had to kill a npc at the fence. game lagged and i was stuck like i had zero internet and was forced to hard shut down wow from my task manager. im thinking maybe im stuck in limbo or something? ive tried everything please help. 
toon name is : Pissfire
realm; Elysium

**Comment by BrumbaerEly** [comment]
Hi all,

I hade the same issue about 2 hours ago - lag in Deadmines, disconnect, and no luck reconnecting to Elysium since. The other realms work fine. I double-checked the game files to no luck.

Your help is appreciated!
If it helps, my characters name is Brumbaer

**Comment by Mantheon** [comment]
I also have the same issue about 2 hours ago. I D/C in stormwind and haven't been able to reconnect since then. It is only Elysium that I cannot log into.

Character Name - Mantheon

**Comment by Spionida** [comment]
[Forum business](https://forum.elysium-project.org/forum/475-other-issues/)
