### ISSUE TITLE
Scholomance Mini-Boss loot.

### ISSUE THREAD

**Issue by Faithbringer** [elysium-project/server#2766]
Recently i have looted Deathbone Legguards and Gridle from Scholomance mini bosses.Their rarity and stat values are not up to date with Blackwing Lair patch.Scholomance loot got 20+ items upgraded (stats/rarity) on patch 1.4.0.
Patch 1.4.0 was released 05 May 2005.
Patch 1.6.0 was released 12 July 2005.
Source : WoWWiki.
http://wowwiki.wikia.com/wiki/Patch_1.4.0
http://wowwiki.wikia.com/wiki/Patch_1.6.0

**Comment by brotalnia** [comment]
The Deathbone items were updated in 1.10.
https://web.archive.org/web/20060726034435/http://wow.allakhazam.com:80/db/itemhistory.html?witem=14620
