### ISSUE TITLE
[1.11] AQ40 Arygos not offering teleport

### ISSUE THREAD

**Issue by fgsfdss** [elysium-project/server#2771]
1.11 patch notes:

> Arygos in the Temple of Ahn'Qiraj will now offer to teleport players to the following places given the following conditions have been met:
> 
> -   If the Twin Emperors have been defeated, Arygos will teleport players to their lair.
> -   If Ouro has been defeated, Arygos will teleport players to the chamber where the dragons are being held prisoner.
> -   Arygos will not teleport players that are in combat. 

Currently Arygos still does not offer any teleport option if these requirements are met.

**Comment by GuybrushGit** [comment]
Andorgos not Arygos.

**Comment by brotalnia** [comment]
Working fine on development branch.

**Comment by fgsfdss** [comment]
Taken straight from https://web.archive.org/web/20060703095628/http://www.worldofwarcraft.com/patchnotes/patch1p11.html, I assume Blizzard made the typo as I was also sure it's Andorgos. 
However my guildie went to check up for the third time just now, on both just to be sure it wasn't misplaced due to the confusing patch notes. Even though we have killed Ouro, he is unable to speak with Andorgos at all, and Arygos only offers the Armament quest.

**Comment by brotalnia** [comment]
It will be resolved once realms are switched to the new progression db. Most likely the update for their gossip options wasn't applied properly. This is working perfectly on the development branch, i just checked.
