### ISSUE TITLE
voidwalker spell error

### ISSUE THREAD

**Issue by Khozak** [elysium-project/server#2777]
Hi, my problem is my voidwalker, he has hunter pet spell max lvl he cant use this but this spell block my book for learning his spell this said your pet can't learn any spell. I dont want delete my warlock just for that so i need help this ruin my gameplay i have try so many idea with you and doesnt work .. i want play my walock :(

**Comment by Spionida** [comment]
Closed prematurely artier. he has downloaded a new client/WDB delete etc.

**Comment by Khozak** [comment]
already done and doesnt work

**Comment by Spionida** [comment]
I know. I advised you to do it  :)

**Comment by Khozak** [comment]
oh

**Comment by Khozak** [comment]
hmmm im not sure what you say lol you said me to dl a new client ?

**Comment by Khozak** [comment]
so just for you know i have install wow on my laptop and this not change my warlock has hunter pet spell
