### ISSUE TITLE
Honor issue on Anathema

### ISSUE THREAD

**Issue by mdouchie** [elysium-project/server#2785]
Hello,

Firstly, excuse me for my bad engish. I'll do my best to be understandable.

I got some rank issues. On my character, in the pvp page, it is written that I did 4000 honors last week.. but actually I did more or less 35000 (same than the week before). So my rank should be "Blood Guard" (like it is written in my Highest Rank) and not Stone Guard anymore. I think it just counted the honor points of yesterday and not the entiere week.

Sorry for been capricious but i don't play every day so a rank takes me ages :)

Best regards and thanks a lot for you job.

Maxime

**Comment by Goida** [comment]
Same problem here, after the server restart the honor panel in character info shows as if I had no pvp activity last week at all, and that is a lie. Instead of getting rank 7 my rating points simply decayed within the current rank 6. Best regards and everything.

**Comment by JosipbrozElysium** [comment]
We're aware of this issue. Working on it.

Best regards!

**Comment by thepparker** [comment]
RP was restored following an error causing the calculation to be performed twice
