### ISSUE TITLE
Elysium - getting more DH than intended

### ISSUE THREAD

**Issue by Sakuragi85** [elysium-project/server#2786]
Yesterday me and some guildies were doing some Outdoor PvP Action and we raided Kargath. While doing that we accidentally killed a civilian, thus giving us a DH. After today's maintenance however I saw that i got 2 DHs instead of one. I checked my honor tab just an hour before the server shutdown and i only had 1 DH. 
A GM told me to delete WTB and WTF and if it didnt help to post it here. Any possibility to get my RP back from that lost 2nd DH? I think it screwed up my ranking since I would have gotten R6 without it.

**Comment by JosipbrozElysium** [comment]
We're aware of this issue. Honor calculation has doubled this week for an unknown reason.

Best regards!
