### ISSUE TITLE
Anathema AQ40 C'thun Teleport 1.11 

### ISSUE THREAD

**Issue by lanstroem** [elysium-project/server#2792]
Still no teleport:
http://wowwiki.wikia.com/wiki/Patch_1.11.0
Arygos in the Temple of Ahn'Qiraj will now offer to teleport players to the following places given the following conditions have been met:
If the Twin Emperors have been defeated, Arygos will teleport players to their lair.
If Ouro has been defeated, Arygos will teleport players to the chamber where the dragons are being held prisoner.
Arygos will not teleport players that are in combat.

**Comment by QAkvastskaft** [comment]
See #2771
