### ISSUE TITLE
URGENT NOTIFICATION: Serverwide Mailbox breakdown

### ISSUE THREAD

**Issue by Beheader** [elysium-project/server#2796]
[27/09/2017 23:50 Server Time]
Some items are getting turned into a letter when mailed, the item is lost and sent, but only a letter is received. I sent 2x3 dream dust from an alt, BUT our guildbank Plebsbank lost a Flask of the Titans to this. Will the items be refunded?

This is global serverwide, seeing various players with the same problem.

**Comment by kallith** [comment]
Can confirm, lost 30stonescale oil and 22 fire oil

**Comment by Soulwing666** [comment]
can confirm, lost stacks of enchantment mats: brillian shards, illusion dust, eternal essences and several gems of various kinds. basically everything that dropped in 3 raids today and got looted and disenchanted.

**Comment by Soulwing666** [comment]
GM adviced to delete WDB and WTF folder and disable all addons, did not work - the mails are still empty.

**Comment by keaarori** [comment]
As of Discord this is being worked on, would expect a hotfix quickly.

**Comment by QAkvastskaft** [comment]
This issue has been resolved
