### ISSUE TITLE
Guild Charter Issues.

### ISSUE THREAD

**Issue by Urya** [elysium-project/server#2798]
I purchase a Guild Charter but when I right click on it no details appear. I have deleted my WTF/WDB and have turned off all add-ons to see if it would fix the issue but it did not. I then turned to trying to delete and buy another charter. After doing this 4 times it still gave me the same Issue. I am unable to see the details of my charter nor am I able to let players sign it because of this. :( I will appreciate it if this issue is resolved I appreciate you reading this have a nice day.

**Comment by Leozcol** [comment]
Same problem here, the Guild Charter purchased can't be clicked and the item have no details.

This is the normal behavior when you put the mouse over a item (the blue soup):

![1](https://user-images.githubusercontent.com/32372163/30986357-be86071e-a458-11e7-9faf-5507223e0d6f.png)

And this is the behavior when you put the mose over the Guild Charter (nothing happen):

![2](https://user-images.githubusercontent.com/32372163/30986373-cd1e19e2-a458-11e7-8c6d-16f3931eb694.png)

**Comment by Urya** [comment]
Yes I have been wanting to form my own guild but I am unable to do so because of this Issue I hope it is looked at soon. :(

**Comment by Spionida** [comment]
Realm?

**Comment by Leozcol** [comment]
Realm: Elysium
Character: Drakkenh
Side: Horde

**Comment by Spionida** [comment]
To confirm, there are large numbers who have an unresponsive guild charter

**Comment by supasteed** [comment]
yeah same thing happening for me today too
