### ISSUE TITLE
New Combat bug with update ANATHEMA

### ISSUE THREAD

**Issue by lanstroem** [elysium-project/server#2801]
The new update with     Bosses and creatures that should put the zone in combat now have a pulsing combat aura.

has created combat bugs, currently unable to leave combat after a C'thun wipe, combat bug followed several members in the raid to naxxramas. Tried reseting AQ, re-forming raid and re-setting naxxramas.

Still several players in Combat.

**Comment by GuybrushGit** [comment]
https://github.com/elysium-project/server/pull/2794

**Comment by thepparker** [comment]
Should be resolved as of yesterday
