### ISSUE TITLE
Incorrect loot permissions when bags are full

### ISSUE THREAD

**Issue by StadenElysium** [elysium-project/server#281]
If a player wins an item through rolling and their inventory is full, the item is made available for anybody to loot. The item should be locked, only allowing the winner to loot it.

**Comment by TNadal** [comment]
i may be mistaken, but i recall this being the norm in classic? once the roll / distribution happened, full bags  or inability to loot (unique item or full bags for example) left it on the corpse for anyone to loot.

**Comment by StadenElysium** [comment]
This is based on my recollection too but any evidence either way would be good. Perhaps it was changed in TBC?

**Comment by TNadal** [comment]
the audio files for 'that would be stealing' was added in 2.0, so i believe the looting was changed then? i'm not finding anything definitive either way though.

**Comment by Warkdev** [comment]
The loot mechanism is indeed that assigned loot are left "free-for-all" if you release the loot window from the assignee.

**Comment by thepparker** [comment]
Yea, should be FFA if bags are full or you open and then close the loot window, leaving items behind.

**Comment by Cabro** [comment]
The thing with opening and then closing the loot window making the items FFA should only apply to items that are BELOW the loot threshold. And in any case not when you WIN an item, it should be locked until you loot it OR change manually to FFA.
Do you guys have any proof it would change to ffa if you had full bags? This is the worst case of denial so far.

**Comment by Maduse** [comment]
I can't recall that ever happening where someone won a roll on an item but someone else was able to loot it so this seems like an obvious bug to me.

Only items that wasn't rolled on but was assigned to someone through group loot for example would go FFA if that person decided to open the loot window but then not loot those items.
