### ISSUE TITLE
Voidwalker error spell

### ISSUE THREAD

**Issue by Khozak** [elysium-project/server#2811]
Well this is my 3 issue for same bug ...   . Hi, my problem is my voidwalker, he has hunter pet spell max lvl he cant use this but this spell block my book for learning his spell this said your pet can't learn any spell. I dont want delete my warlock just for that so i need help this ruin my gameplay i have try so many idea with you and doesnt work.
![bug warlock](https://user-images.githubusercontent.com/32212330/30981893-c56219c4-a453-11e7-92e6-c431e046d77d.png)

so many time i have this error you say me solution i trying delete WDB clear cache i have dl 3 new client doesnt work i have try to load wow on my laptop and its ame he has hunter pet spell and after you give 1 solution you stop trying to help me ... 9 day i have this problem 

ps: sorry for my bad english im try my best.

**Comment by brotalnia** [comment]
I don't think there even is a gm command to unlearn pet spells.

**Comment by Spionida** [comment]
[voidwalker spell error #2777](https://github.com/elysium-project/server/issues/2777)

[Voidwalker error spell #2736](https://github.com/elysium-project/server/issues/2736)

**Comment by Khozak** [comment]
stop said me same idea its doesnt work .... find new plz
