### ISSUE TITLE
Are We There Yeti? Chain Quest - Quixxil NPC Bug (Un'Goro Crater @ Marshal Refugee) - Unreachable Place

### ISSUE THREAD

**Issue by Priestigeous** [elysium-project/server#2819]
Quest NPC "Quixxil" - Un'Goro Crater(Marshal Refugee) for chain quest " Are We There Yeti?" is stuck in an unreachable place and can't use the quest item on him. Please fix it asap.

- Priestigeous from Darrowshire
<Is Probably Stoned>

**Comment by BrynjaDarrow** [comment]
This issue has already been fixed, but was not yet implemented on Darrowshire & Elysium.

#2400

**Comment by berillis** [comment]
Do you mean this update is still not on Elysium/Darrowshire? https://elysium-project.org/updates/2017-09-08

**Comment by BrynjaDarrow** [comment]
Yes.

**Comment by brotalnia** [comment]
This is fixed, just not on all live realms yet.

**Comment by Priestigeous** [comment]
Thanks for the quick fix.
