### ISSUE TITLE
Not able to complete Weapons of Choice 

### ISSUE THREAD

**Issue by ciubhran** [elysium-project/server#2822]
Got all 3 items on my character, the quest log says I have each item, but when I go to the NPC the quest marker above his head is still greyed out and he wont recognize that I have the items.

**Comment by Spionida** [comment]
[Can not turn quest in](https://forum.elysium-project.org/topic/47571-can-not-turn-quest-in/)  if that fails, in-game ticket

**Comment by GuybrushGit** [comment]
If you remember what you did to cause this, post here: https://github.com/elysium-project/server/issues/1977
