### ISSUE TITLE
No rep for kills -Ravenholdt reputation (Also centaurn clan in Desolace)

### ISSUE THREAD

**Issue by Avlli** [elysium-project/server#2823]
Simply as Titel.
After killing mobs i do not get any reputation. Any solution ?

**Comment by Nelythia** [comment]
Hey!
Doing the big rep grind too, I see.

Ravenholdt rep was only grindeable with kills until honored starting in TBC, as syndicate mobs do not give + reputation towards Ravenholdt in vanilla.
If you want to reach exalted with Ravenholdt, you need to buy 2800 Heavy Junkbox total.

Which clan are you grinding? Gelkis or Magram?
You can actually grind both to honored 11999 (capped) in vanilla (max is revered ~230 with quests).

**Comment by GuybrushGit** [comment]
>As of patch 2.3.0, killing NPCs affiliated with the Syndicate gives you Ravenholdt reputation.
