### ISSUE TITLE
[Quest] Vorsha the Lasher

### ISSUE THREAD

**Issue by UltraNic** [elysium-project/server#285]
Quest "Vorsha the Lasher" is buggy, you can start it at Muglash in Ashenvale, you need to escort him to a brazier and he tells you to put out the fire. You can click on the brazier but nothing happens. After several minutes Murglash gets impatient and despawns. After that the quest is marked as "failed".

**Comment by FractalCabush** [comment]
Can confirm this happened to me when i was leveling, tried multiple times

**Comment by shmigy429** [comment]
Yup, happened to me as well; abandoned that sucker and moved on. Right clicking did not extinguish the bracer; possible that the brazier isn't resetting as fast as he returns to start the quest over?
