### ISSUE TITLE
+Horde or +Alliance reputation quest gains DONT work

### ISSUE THREAD

**Issue by lequintal69** [elysium-project/server#291]
http://db.vanillagaming.org/?faction=67
http://db.vanillagaming.org/?faction=469

all those quests that should give +horde or +alliance reputation actually gives no reputation at all

needs to be scripted so it gives reputation to corresponding factions

**Comment by lequintal69** [comment]
http://db.vanillagaming.org/?quest=6804#wh-comments  didnt give any rep, even tho he technically gives +250 reputation to each horde faction, and not +horde reputation (which gives the same result).

**Comment by JosipbrozElysium** [comment]
Will close in favor of #653 (as this one is a little bit more detailed)

Best regards!
