### ISSUE TITLE
Whipper root and Night Dragon's Breath cd DONT work as intended

### ISSUE THREAD

**Issue by lequintal69** [elysium-project/server#292]
Atm, they only seem to  work if potions are not on cooldown. As such, it pratically shares a cooldown with potions without displaying it. You are forcing to use whipper/ndb BEFORE potion to make it work, which is not really practical in many situations

Sources: countless videos of pvpers using those items and potions in various orders.

Also:
 

http://web.archive.org/web/20070113142147/http://wow.allakhazam.com/news/sdetail7557.html?story=7557

We have re-evaluated the mechanics of consumable items in the game and concluded that these should work in a more intuitive manner. As such, most items that can not be equipped with right click abilities have been streamlined into one of three categories. Using an item of a particular category will trigger a shared cooldown among all other items in the same category. The categories break down as follows with category cooldowns as listed.
Potions 2 minutes: This includes items such as Health Potion, Mana Potion, Invisibility Potion and Mighty Rage Potion.
Aggressive 1 minute: This includes items such as explosives, Really Sticky Glue and Discombobulator Ray.
Non-Aggresive 2 minutes: This includes items such as Healthstone, Night Dragon's Breath, Whipper Root Tuber and Target Dummy.

**Comment by StadenElysium** [comment]
Should be fixed in the next update.
