### ISSUE TITLE
[Darrowshire] Hero of the Stormpike/Frostwolf can't be accepted (v2)

### ISSUE THREAD

**Issue by Kolmarwow** [elysium-project/server#2949]
So the original version of this issue ( https://github.com/elysium-project/server/issues/2068 ) was closed with the "Invalid" tag with no reason given. I have no idea what's invalid about this, so i'm going to remake this in more detail, please leave a reason in the comments if you're going to close this again.

So currently on Darrowshire, you need to kill Korrak the Bloodrager to grab the quest related to the Ice Barbed Spear, where as on Elysium you simply have to kill the leader of the opposite faction (or in other words win an alterac valley game). This was intentional as stated by pparker here https://github.com/elysium-project/server/issues/1576

"Due to a mishap in the original deployment of 1.5 on Elysium and the Korrak rewards, we opted to add the "Hero of the Frostwolf"/"Hero of the Stormpike" quests earlier, with the associated rewards. The Korrak quest no longer rewards the items, much the same as retail once Blizzard introduced the aforementioned quests."

Note the "we opted to add the "Hero of the Frostwolf"/"Hero of the Stormpike" quests **earlier**" part. That implies they were supposed to be eventually added later on. Well, as you can see in my original version of the issue, these quests were added in 1.8. Darrowshire is on 1.8 at the moment, so it should have these quests available.

**Comment by thepparker** [comment]
The Hero quests will be available come when 1.9 is released on Darrowshire. Initially it was planned to only have Korrak rewards available since we are using a pre-nerf version of Alterac Valley, however we realise that it can be troublesome to a) get games of AV going, and b) Kill Korrak on low population servers, when games are only on during the weekends.

**Comment by Kolmarwow** [comment]
I see, thanks for the response!
