### ISSUE TITLE
Notched Shortsword of Agility - OP Random Enchantment

### ISSUE THREAD

**Issue by Rushmoose** [elysium-project/server#2952]
![img](https://thumb.gyazo.com/thumb/1200/_89f6a3f30e93eaf255cc0b9282c3fea7-png.jpg)
Bug? "+46 Agility" Level 5

**Comment by Haiwuu** [comment]
Unless you've actually seen that item and confirmed it gives +46 agility, it is more than likely not a real item

**Comment by GuybrushGit** [comment]
People can modify item links to show whatever.
