### ISSUE TITLE
Druid Tier 3: 2 & 6 Set Bonus

### ISSUE THREAD

**Issue by Serqin** [elysium-project/server#2953]
6 set: Initial cast of regrowth isn't applying the buff, only the ticks. 

2 & 6 set: Neither are working when ticking on a full health target. 

Videos showing 2 set working on full health targets: 

https://youtu.be/jPQ9ixJOB0k?t=210
At around 3:35 you can see that he has full health and still receives mana from Rejuv

https://youtu.be/9-6K-IDhOdA?t=326
At around 5:29 you can once again see him gain 60 mana from Rejuv while at full health.

**Comment by thepparker** [comment]
(For my own confirmation): 3:35, no rejuv tick on SCT but mana refund procs. All positive periodic effects should probably proc on 'ticks', regardless of whether any healing is actually dealt.

**Comment by Serqin** [comment]
You see the Rejuv timing out, it disappearing being the "final tick" from what I can gather.

**Comment by QAkvastskaft** [comment]
Fixed applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/

**Comment by sapylla** [comment]
@QAkvastskaft hey sorry if im being stupid but if the fix was applied it was done on the wrong server .
On Anathema (where we have 6t3 to test it) both bonuses function incorrectly as the original poster @Serqin  said .
