### ISSUE TITLE
Execute Icon isn't available under Macro Icons

### ISSUE THREAD

**Issue by Farodsbro** [elysium-project/server#2957]
The icon for the Warrior ability "Execute" doesn't exist in the macro icon list. That is all. Has been this way for a few patches (before Naxx patch). Anathema server.

**Comment by Nelythia** [comment]
Macro icons are stored client side, not server side.
I have all my macro icons up to WoD because I just copied the macro files of retail over here, since I do like some icons from later expansions.

You should just look for the file or delete the whole folder to refresh it

**Comment by BBCnewstoday** [comment]
You can manually change icon in WTF/Account/ACCNAME/Macro-cache
Just change icon name to Execute("inv_sword_48")
eg:
MACRO 1 "my macrosname " Ability_Hunter_SniperShot to MACRO 1 "my macrosname " inv_sword_48
