### ISSUE TITLE
Guiding Stave of Wisdom

### ISSUE THREAD

**Issue by Allerius** [elysium-project/server#2963]
The Item "Guiding Stave of Wisdom" dropped by Emperor Thaurisan is supposed to have +53 Heal from Effects and Spells in Addition to his stats but it ain't shown.
I wrote a ingame ticket and a gm replied to me that it should be ingame on this Server and that it is a visual bug, please fix it or if it's not only visual then please add the +53heal on it.

**Comment by binary909** [comment]
The +53 healing was not added until patch 1.10, Anathema and Darrowshire are the only server that should have this item patch, you didn't bother to specify the server you are playing on. 
You also did not provide any sources to backup your claim, memory or opinion is not a valid source.

Progressive patch itemisation is in place therefore on Elysium this item is in a state before it had the +53 heal.

Source:

http://web.archive.org/web/20060415051030/http://wow.allakhazam.com/db/item.html?witem=11932

**Comment by Allerius** [comment]
My only source was that when I asked a GM via Ticket he told me that it should be in so I believed it, thanks for the clarification though

**Comment by BrynjaDarrow** [comment]
Darrowshire is only on 1.8 @binary909
