### ISSUE TITLE
Intellect buff capped out at lvl 39 (Twink)

### ISSUE THREAD

**Issue by greenlipskins** [elysium-project/server#2975]
Hi,
I'm noticing a cap for intellect being buffed at level 39 with pots/scrolls/class buffs.  It seems after just using an elixir of greater intellect potion (+25int), the mage buffs or int scrolls don't work or stack with the intellect potions like they're supposed to (worked at lvl 29 for me).  Buffs from intellect sources only cap out at highest buff applied (in my case +25 from int potion), which is extremely low at lvl 39 and should be able to be raised higher by working in conjunction with intellect mage buffs and scrolls.  Only +25 intellect (elixir of greater intellect) being applied from intellect sources defeats the purpose buying intellect elixirs since then it makes mage int buffs/int scrolls completely obsolete.

Thanks,
In game character name- Schaefer (Lvl 39 druid twink)

**Comment by druidish** [comment]
This is how attribute buffs work in general for vanilla. Only a select few stack with each other.

https://web.archive.org/web/20060718093512/http://wow.allakhazam.com:80/db/item.html?witem=9179

**Comment by GuybrushGit** [comment]
AI doesn't stack with greater intellect.
