### ISSUE TITLE
Blood Parrot of "Bloodsail Admiral's Hat" too big (Possible Fix included)

### ISSUE THREAD

**Issue by Nelythia** [elysium-project/server#2980]
Currently the Blood Parrot is way too big: https://i.imgur.com/XwE4hOj.jpg
Compared to: https://web.archive.org/web/20060820073540/http://wow.allakhazam.com:80/db/item.html?witem=12185

I don't know how to make a proper pull request. Fix should be:
UPDATE `creature_template` SET `scale`=0 WHERE `entry`=11236;

**Comment by GuybrushGit** [comment]
Not big enough.

**Comment by brotalnia** [comment]
Fixed in https://github.com/elysium-project/server/commit/f04bae8c62f5e6822980220d1f4da470e1a3c209.
