### ISSUE TITLE
Dragon's Call Proc isn't working properly

### ISSUE THREAD

**Issue by Allerius** [elysium-project/server#2987]
Today I got my Dragons Call from the Shade of Eranikus in ST after dozens over dozens of runs but I noticed that the Emerald Dragon Whelp it spawns :http://www.wowhead.com/npc=8776/emerald-dragon-whelp, isn't working properly, it does spawn it but instead of using its spell: http://www.wowhead.com/spell=9591/acid-spit, it just autohits in meele and follows the target.
Please fix this as soon as possible because I just started on this Server to Play with this sword and now after 103 sunken temple runs I got my first and it isnt working properly:( 
Please I beg you fix this

**Comment by Allerius** [comment]
altough wowhead isn't a viable source else, the comments on it from vanilla are: 

By Dread (4,133 – 1·11·31)  on 2006/11/05 (Patch 1.12.2)   

This drops of the final boss in ST, Shade of Erakinus.

It has a very low drop chance but it's a pretty good weapon.

Info about the Chance on hit:

You summon one whelp at a time, but you can only have up to 3 whelps summoned at one time. Their attack is shooting green bolts at an enemy, which take about 2-3 seconds to cast and it's cooldown is roughly two seonds. Each bolt does about 280 damage (fighting a level 52 monster) and during the duration of the summon, it casts about 3 of these bolts, making the final damage around 840.
http://www.wowhead.com/item=10847/dragons-call#comments
please fix this weappon proc, it's the reason which brought me to this great Server and made me invest hundreds of hours into it:(

Instead of attacking as above mentinoned they just autohit in meele for 5-8dmg

**Comment by QAkvastskaft** [comment]
See #1803
