### ISSUE TITLE
anyone can share vmaps & mmaps files?

### ISSUE THREAD

**Issue by hzdlive** [elysium-project/server#3]
anyone can share vmaps & mmaps files?

**Comment by hzdlive** [comment]
i try do vmapextractor. but it error:

Extracting World\wmo\Dungeon\AZ_Karazahn\Karazhan.wmo
No such file World\wmo\Dungeon\AZ_Karazahn\Karazhan.wmo.
Couldn't open RootWmo!!!

and


Extracting World\Wmo\Kalimdor\Buildings\Nightelfmoonwell\Dsnightelfmoonwellornate.wmo
Extracting <Empty>\Kl_Onyxiaslair.wmo
No such file <Empty>\Kl_Onyxiaslair.wmo.
Couldn't open RootWmo!!!
Extracting World\Wmo\Transports\Blackcitadel\Blackcitadel.wmo
Warning: Some models could not be extracted, see below
Could not find file of model World\Generic\Quilboar\Passive Doodads\Leantos\Razorfen_Leanto03.m2
A few of these warnings are expected to happen, so be not alarmed!
Done!

Extract for VMAPz04. Work complete. No errors.

**Comment by Kittnz** [comment]
I think @r00ty-tc will PR something soon.

**Comment by r00ty-tc** [comment]
Yeah, I'm not sure when I'll get the chance to though. One of the main problems is that in one of the extractor files, the mpq file extensions are caps when they shouldn't be (or the other way around). That stops it opening the MPQs needed to extract.

But that's not the only problem. You also need to fetch an old version of the extractors to produce the dir_bin file. IMO the vmap extractor here needs to have that code added. But, I don't really have time to right now.

What you can probably do is build the extractors and follow the guide as per the repo I put up. Do the extraction then switch to this branch and build the server for now.

**Comment by Kittnz** [comment]
Let's see what the elysium staff brings to the table first @r00ty-tc .

**Comment by jzcxw** [comment]
@r00ty-tc We can't get the extractors to even complie at the moment..Tried alot of mango extractors but they all seem to fail or have missing files.

**Comment by r00ty-tc** [comment]
I know, I spent a day or so fixing it on the (cough) other version. Luckily the one I worked on, is the same branch this is based on. So someone might for example look at my repos, see the one that looks about right, look at the branch that is clearly relevant, look at the (hopefully obvious) commit of the 4 that includes the corrections and might be able to use my hacked solution in the meantime.

There's also a caveat. To make it properly work (including transport mmaps) you're still going to need to compile AT LEAST the vmap extractor from the specific mangos-zero commit I mention on that other repo and follow the order I say to do things. It is possible to make a working full set of maps, vmaps and mmaps. It's just not easy right now. It needs to be fixed here too though, and not the hacky version I did quickly to get it running.

**Comment by jzcxw** [comment]
@r00ty-tc I tried it on your branch.. all the extractors vcxproj are not linked proper and will fail :( For example in VmapExtractorVC100. bzip2 and zlib will not load their projects as their directory in the project is incorrect.

**Comment by r00ty-tc** [comment]
Ah. I never made extractors in windows. I ran on linux. Mainly because I have a more powerful server than desktop. 

You see I changed the cmakes. So you just use those to rebuild vs projects in cmake. Again I've not tried it. 

Or setup debian /Ubuntu vm just for extraction.

**Comment by mewsian** [comment]
Windows or linux binaries with an extract script like cmangos would be much appreciated. I'm giving up on extraction for now after spending hours fighting visual studio

**Comment by basedxx** [comment]
I have had mmaps and vmaps completely extracted since last week. Compiling the movement extractor on linux requires you to edit the cmake list file and add pthread and ACE library to link with. I could upload them all somewhere?

**Comment by jzcxw** [comment]
@basedxx Thank you for sharing but my the console output errors saying it is expecting an older generation (3) of mmtile instead of (4)

**Comment by basedxx** [comment]
@jzcxw These are v3 maps built with the Nost generator and they load fine for me without error.

**Comment by jzcxw** [comment]
@basedxx Hmm.. maybe it is due to my vmaps and maps are not made from nost gens. I can't get any gen to complie on Windows :/

**Comment by jzcxw** [comment]
@basedxx Okay I managed to get ad.exe to compile and I'm using your MMAP files but I still have multiple errors and a crash at the very end. 
MMAP:loadmap: Could not open mmtile file './mmaps/0010731.mmtile'
MMAP:loadmap: Could not open mmtile file './mmaps/0010831.mmtile'
Movemap.cpp:173: Error: Assertion failed in MMAP::MmapManager::Loadmap failed: data

**Comment by boom8866** [comment]
@basedxx Thank you for sharing, VMap can share it?

**Comment by boom8866** [comment]
![6f7e1cddgh owp8pvtpx6](https://cloud.githubusercontent.com/assets/16046064/23830635/6beda58a-074a-11e7-97a1-f92aca73dba9.png)

**Comment by r00ty-tc** [comment]
You do get a load of those messages, even with working mmaps because their core loads all maps in at startup. 

You can check if it's working. Just make an undead caster. Run inside one of houses with the zombies outside,  Cast at one outside run behind the wall. If it comes through the wall they're not working. If it runs through the door, and changes direction to come at you, they work.

**Comment by r00ty-tc** [comment]
As for binaries. If I upload my linux binaries they might not work for you. But I'll certainly try. On windows I didn't compile extractors yet. Only copied existing maps from linux to windows.

**Comment by hzdlive** [comment]
@r00ty-tc I use debian os, can you upload your binaries files(ad, vmapextractor, vmap_assembler, MoveMapGen,)? i try it .

**Comment by r00ty-tc** [comment]
I compiled them on debian 9. I'm out now but will upload a bit later.

**Comment by jzcxw** [comment]
Made some progress.. Now mmaps onlys error is

```
7>     Creating library E:/Server/Ani/core/build/contrib/mmap/Release/MoveMapGen.lib and object E:/Server/Ani/core/build/contrib/mmap/Release/MoveMapGen.exp
7>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: void __cdecl Log::outInfo(char const *,...)" (?outInfo@Log@@QAAXPBDZZ) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
7>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static class Log & __cdecl MaNGOS::Singleton<class Log,class MaNGOS::SingleThreaded<class Log>,class MaNGOS::OperatorNew<class Log>,class MaNGOS::ObjectLifeTime<class Log> >::Instance(void)" (?Instance@?$Singleton@VLog@@V?$SingleThreaded@VLog@@@MaNGOS@@V?$OperatorNew@VLog@@@3@V?$ObjectLifeTime@VLog@@@3@@MaNGOS@@SAAAVLog@@XZ) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
7>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static char const * __cdecl ObjectGuid::GetTypeName(enum HighGuid)" (?GetTypeName@ObjectGuid@@SAPBDW4HighGuid@@@Z) referenced in function "public: char const * __thiscall ObjectGuid::GetTypeName(void)const " (?GetTypeName@ObjectGuid@@QBEPBDXZ)
7>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static class World & __cdecl MaNGOS::Singleton<class World,class MaNGOS::SingleThreaded<class World>,class MaNGOS::OperatorNew<class World>,class MaNGOS::ObjectLifeTime<class World> >::Instance(void)" (?Instance@?$Singleton@VWorld@@V?$SingleThreaded@VWorld@@@MaNGOS@@V?$OperatorNew@VWorld@@@3@V?$ObjectLifeTime@VWorld@@@3@@MaNGOS@@SAAAVWorld@@XZ) referenced in function "public: void __thiscall VMAP::VMapManager2::releaseModelInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?releaseModelInstance@VMapManager2@VMAP@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
7>E:\Server\Ani\core\bin\Release\MoveMapGen.exe : fatal error LNK1120: 4 unresolved externals
```

**Comment by brotalnia** [comment]
@jzcxw I get the same crash error as you with the mmaps posted by @basedxx .

**Comment by r00ty-tc** [comment]
@hzdlive head over to my repo and look at releases. Give it a go. I tried on Ubuntu 14.04 from D9 and had some issues with glib etc. So, it's not assured it will work.

**Comment by r00ty-tc** [comment]
@jzcxw for that issue I pulled an almighty hack. But it compiled and built mmaps.

https://github.com/r00ty-tc/NostalriusFixed/commit/a293650f6eb8290563384e72521762fc9518a8d2#diff-29425d92e48e18502defa76c493a6595R314

Change it back after building mmapextractor! :)

**Comment by basedxx** [comment]
@boom8866 If you start with the run-mangosd script the 'could not load' list disappears. Either way they get loaded and you can see in game!

**Comment by jzcxw** [comment]
@r00ty-tc Doing that only removed one error. Still will not complie

```
4>     Creating library E:/Server/Ani/core/build/contrib/mmap/Release/MoveMapGen.lib and object E:/Server/Ani/core/build/contrib/mmap/Release/MoveMapGen.exp
4>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: void __cdecl Log::outInfo(char const *,...)" (?outInfo@Log@@QAAXPBDZZ) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
4>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static class Log & __cdecl MaNGOS::Singleton<class Log,class MaNGOS::SingleThreaded<class Log>,class MaNGOS::OperatorNew<class Log>,class MaNGOS::ObjectLifeTime<class Log> >::Instance(void)" (?Instance@?$Singleton@VLog@@V?$SingleThreaded@VLog@@@MaNGOS@@V?$OperatorNew@VLog@@@3@V?$ObjectLifeTime@VLog@@@3@@MaNGOS@@SAAAVLog@@XZ) referenced in function "public: void __thiscall ByteBuffer::appendPackGUID(unsigned __int64)" (?appendPackGUID@ByteBuffer@@QAEX_K@Z)
4>vmap.lib(VMapManager2.obj) : error LNK2019: unresolved external symbol "public: static char const * __cdecl ObjectGuid::GetTypeName(enum HighGuid)" (?GetTypeName@ObjectGuid@@SAPBDW4HighGuid@@@Z) referenced in function "public: char const * __thiscall ObjectGuid::GetTypeName(void)const " (?GetTypeName@ObjectGuid@@QBEPBDXZ)
4>E:\Server\Ani\core\bin\Release\MoveMapGen.exe : fatal error LNK1120: 3 unresolved externals
```

**Comment by r00ty-tc** [comment]
@jzcxw I'm going to look at making it compile on windows. I used the older leaked version with my changes and could get it to build. But, I didn't sit down and spend time to make a "clean" fix. Looking at here. They seem to have included mmap gen in the main cmake as an option to build.. So maybe that's the solution. I dunno.

**Comment by jzcxw** [comment]
@rooty-tc that is what I'm doing ATM. Both individually and in the main it reports the same error for my end now.

**Comment by mewsian** [comment]
@r00ty-tc thanks much for sharing your binaries. With some library work I got them running on Debian 8 (had to symlink an older version of ACE lib and drop a newer version of libc++ in the run dir but seems to work fine). I'm also using your writeup from your repo for the order of execution for these programs.

If I get the server running I might write a full guide for debian build because there are so many problems right now.

**Comment by r00ty-tc** [comment]
Well, that's pretty much all there is to it.

1: Compile the core (works with little or no changes right now). This repo of course.
2: Extractors are a problem, but yeah if you can use those binaries I managed to get working and you use that order, it should work out fine (don't use the python thing to multi core the mmap, it won't build the transport mmap tiles). So yeah you'll sit through 12+ hours of mmap extraction.
3: Run the main SQL scripts to build logon/char/log DBs. Run the world DB SQL from the release on this repo to make world DB. Run the migrations on world/logs accordingly.
4: Configs
5: Add realm to realmlist
6: run realmd/mangosd

Up and running.

I have noticed some pathing oddities in deathknell. Not sure what the deal is and whether they happened on Nostalrius/Elysium.

**Comment by hzdlive** [comment]
@r00ty-tc when i ran vmapextractor, error:./vmapextractor: error while loading shared libraries: libmpq-0.4.2.so: cannot open shared object file: No such file or directory

**Comment by jzcxw** [comment]
Very odd. Using the MMAPS provided by @basedxx the core crashes on startup
```
Mon Mar 13 01:57:05 MPST 2017
Tue Mar 14 02:49:03 MPST 2017
MMAP:loadMap: Could not open mmtile file './mmaps/0015530.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015630.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015730.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015830.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0015930.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016030.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016130.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016230.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0016330.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010031.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010131.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010231.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010331.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010431.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010531.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010631.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010731.mmtile'
MMAP:loadMap: Could not open mmtile file './mmaps/0010831.mmtile'
E:\Server\Ani\core\src\game\Maps\MoveMap.cpp:173: Error: Assertion in MMAP::MMapManager::loadMap failed: data
<error loading dbghelp.dll>
```

**Comment by mewsian** [comment]
Up and running finally. @r00ty-tc are you able to reproduce your problem in deathknell? Line of sight seems to be working on my copy

**Comment by jzcxw** [comment]
@mewsian Able to share the extracted files?

**Comment by beijixian** [comment]
hi everyone
 after patch @r00ty-tc patches  vmapextractor is run on Debian:jessie amd64 ,but the Buildings cannot Converting to vmaps with vmap_assembler. 
Finally，i found another way to fix it .i use the old mangos tools @Kittnz (https://github.com/Kittnz/ZeroServer) to generate Buildings Folder on win，then use Linux vmap_assembler and MoveMapGen。it is works。
the core crashes on startup still some mistakes

**Comment by zoinoia** [comment]
nope, still no vmaps and mmaps ...

**Comment by falzard** [comment]
Why he closed it?

**Comment by brotalnia** [comment]
He lost hope :D

**Comment by falzard** [comment]
we should open a new issue

**Comment by r00ty-tc** [comment]
I think the issue is that, it's a legal no-no to publish the extracted maps themselves, hence why I've not responded to requests. Any new issue should be specifically about any issues remaining for running the extractors yourself.

**Comment by falzard** [comment]
It's not like people answering in the comments are affiliated with elysium. or are you?
If you're not then you can safely publish them (and maybe elysium team will delete the link but at least we will get them :D)

**Comment by r00ty-tc** [comment]
I'm affiliated with another project, where we won't give out maps based on the game client. So, same effect really :P

**Comment by fatalmatt** [comment]
@r00ty-tc well maybe upload the compiled extractors that you used ?

**Comment by mewsian** [comment]
@fatalmatt he did: https://github.com/r00ty-tc/NostalriusFixed/releases

**Comment by fatalmatt** [comment]
@mewsian alright ill try em out >_> ty
