### ISSUE TITLE
Sandworm Meat droprate bugged?

### ISSUE THREAD

**Issue by Jakobud** [elysium-project/server#3015]
According to the database, Sandworm Meat has an approximate 39.9% droprate from the worms in Silithus. But I just finished farming about 30 of them and not a single meat has dropped.

Item #: 20424
Drops from npcs: # 11740 or # 11741

I know that this meat does definitely drop if you have a quest from Cenarion Hold where you have to go get the meat and you get a nice food recipe in return. But then after turning in the quest, it seems I cannot get the meat to drop.

I can't tell in the database if something drops only during a quest or not. Is there a way to tell? Has anyone previously reported this?

Thanks,

**Comment by BrynjaDarrow** [comment]
Which server do you play on?

**Comment by Jakobud** [comment]
Elysium PVP

**Comment by Jakobud** [comment]
Also, the quest that you get in Silithus to learn the recipe is: # 8313

**Comment by Jakobud** [comment]
On a side note, the follow-up to this quest is # 8317 and it is not offered by the NPC after completing # 8313. Maybe both of these issues are linked.

**Comment by Jakobud** [comment]
Okay so I just saw this #666. Perhaps the Sandworm Meat is not in the game until that progression 1.8 patch hits?

**Comment by Sylvestersnr** [comment]
Yes, just like BrynjaDarrow mentioned

**Comment by Jakobud** [comment]
Oh I totally didn't see that. Thank you. It's kind of weird that you are able to get the recipe for this before 1.8.
