### ISSUE TITLE
[The Eye of Nerub] 132G Vendor price

### ISSUE THREAD

**Issue by lanstroem** [elysium-project/server#3026]
Unable to locate original vendor price but does not feel legit.

**Comment by Oudeis1447** [comment]
https://web.archive.org/web/20070108104754/http://wow.allakhazam.com:80/item.html?witem=23039

I cannot find anything sooner, that still technically before TBC and the price say 11g37s47c

**Comment by Pigmoth69** [comment]
Hi! I found some information about this too. I dont think the 132G is the right value too... 

http://wowwiki.wikia.com/wiki/Loatheb_(original) - Scroll to find the item and its info
http://wowwiki.wikia.com/wiki/Loatheb_(original)?oldid=1695192 - This is the 2008 version when it was created.

**Comment by brotalnia** [comment]
This has already been fixed in https://github.com/elysium-project/server/commit/b8f6a1e8d9c7e1fa4c6e4e92404f87d479684c95.
