### ISSUE TITLE
Totems should not be affected by silence

### ISSUE THREAD

**Issue by SnekySnake7** [elysium-project/server#3034]
A bug/oversight that many people don't even seem to notice is that totems are not spells and should not be affected by silence. It was not this this at any point in vanilla, and the earliest mention of this being changed in the official game is in November 27, 2012(Mists of Pandaria patch 5.1.0). http://wowwiki.wikia.com/wiki/Patch_5.1.0

Shaman

    All totems are now considered spells, and summoning totems can be prevented by silencing effects. Searing Totem, Magma Totem, and Fire Elemental totems fall into the Fire school, while all other totems fall under the Nature school.

I just got done doing the satyr horns quest in Ashenvale, and the Satyrs' silence was stopping me from placing totems.

**Comment by connormcgregor** [comment]
Agree with this. They shouldn't silenced

**Comment by QAkvastskaft** [comment]
Looking at the 3.0.2 patch notes we can see the following: 
"All totems are now considered on the "Physical" school, and no longer magical spells."
I would say this is Invalid
You would have to find a better source stating that totems can be cast while silenced during vanilla
