### ISSUE TITLE
"The Missing Diplomat" and "You Scream, I Scream..."

### ISSUE THREAD

**Issue by Musing63** [elysium-project/server#3046]
2 quests is no end NPC-s
The Missing Diplomat - this part "http://db.vanillagaming.org/?quest=1246" (Speak to Dashel Stonefist in Stormwind.)
You Scream, I Scream... - no end NPS (boy) too
fix plz

**Comment by Spionida** [comment]
Dashel Stonefist has been temporarily removed

You Scream, I Scream - not Children's Week.

**Comment by GuybrushGit** [comment]
https://github.com/elysium-project/server/issues/3033
