### ISSUE TITLE
[Elysium] Quest: Hero of the Frostwolf cant be picked

### ISSUE THREAD

**Issue by Rogmul** [elysium-project/server#3048]
When u deliver the quest "[The Battle for Alterac](http://db.vanillagaming.org/?quest=7142)" the npc "[Voggah Deathgrip](http://db.vanillagaming.org/?npc=13817)" 
does not give you the next quest ["Hero of the Frostwolf"](http://db.vanillagaming.org/?quest=8272).

Can anyone else confirm this issue?

**Comment by Noerlem** [comment]
Completed both Korrak quest and The Battle for Alterac. At this moment neither quest gives rewards or followup quest

**Comment by brotalnia** [comment]
The quests Hero of the Frostwolf/Stormpike are set to disabled in the database. I was told that AV will remain in a pre-nerf state so those quests should be disabled, since they are a replacement of the Korrak quests.

**Comment by Noerlem** [comment]
But at the current time neither the korrak quest or The Battle for Alterac rewards you with the weapons. Which seems to be unintented

**Comment by brotalnia** [comment]
It should be solved when the new progressive database goes live. The old db that was in use until now is a big mess and many things are broken or missing there. The Korrak quests should have the correct rewards after the realms are updated, but if you've done it already you'll probably need help from a GM to reset your quest status and let you do it again.

**Comment by Kazirraa** [comment]
The Korrak quest originaly didn't reward Cold Forged Hammer (mp5 mace). If they delete The Hero of Frostwolf from the game, many people will have item which is no longer available in the game - i think that's not fair.

**Comment by Lord-Travi** [comment]
This issue has already been posted: https://github.com/elysium-project/server/issues/2997

The GMs I have talked to said this is a bug and they are aware of the issue. At this patch the AV win the hero quests award the items.

Tbh I don't even think they are working on it. I posted 4 days ago. Maybe if enough people complain they will fix this.

**Comment by Gnockz** [comment]
I just made an Account to push here and make it look atleast abit more important ;)
Waited 2 Weeks for my win, to get pre-bis =(

**Comment by Rogmul** [comment]
So there is an estimated time to fix this issue or any developer involved? we want av quest reward...

**Comment by Lord-Travi** [comment]
There is no ETA, they don't care.

**_Really_** sucks.

**Comment by Gnockz** [comment]
It's kinda comforting me that next weekend will be AV-Weekend (right?) and more ppl will complete the quest.
That's the very last point where it might get attention and they do have to care.

**Comment by berillis** [comment]
As the staff has said, the fix will come in the next patch, which is, for Elysium, Saturday. So 3 more days. There are plenty of drops from normal dungeons which are better than the rewards from an AV win.

**Comment by Kazirraa** [comment]
Well, i don't know other example of "mana per 5" weapon than Maraudon Princess dagger. Mace is Pre-Bis for many people.

**Comment by berillis** [comment]
"Lorespinner" dagger from the DM quest "Lethrendis's Web" has even better stats and the same amount of mp5 as the AV hammer. It probably is even easier to get. Also Hammer of the Grace from BRD boss Seven Dwarves is about equal if not better than the AV hammer. Mace is definitely **not** Preraid BIS for any class.

**Comment by Gnockz** [comment]
"It's gonna be fixed on Saturday" i take your word, dude.

For me it was the x-bow as Pre-Bis as hunter.

I didn't see any 'next Saturday fix' but i may have gotten something wrong. I can wait 3 days ;)

**Comment by mogginho** [comment]
Been trying to win an AV since lvl 51, tonight it happened and I couldn't get the Ice Barbed Spear -_-

I hope this gets fixed.

**Comment by KingKC612** [comment]
What wand is better pre raid for mages?

**Comment by H4WKgg** [comment]
Spent all week in AV trying to get the prebis Xbow and when I finally win shit's broken. fml

**Comment by Likelyow** [comment]
This issue seems fixed now.
