### ISSUE TITLE
World Server Crash at Shutdown

### ISSUE THREAD

**Issue by brotalnia** [elysium-project/server#305]
On Windows mangosd appears to crash every time it is shutdown. This includes restarts too.

![ezgif-1-8650a9a44e](https://cloud.githubusercontent.com/assets/6519171/24785475/c7e02d96-1b62-11e7-9882-549a35ed7d2d.gif)

It seems to save everything fine, but it should not throw a crash error on shutdown.

**Comment by Kittnz** [comment]
Windows XP? ;)

**Comment by brotalnia** [comment]
This is Windows 7 with the Luna theme to make it look like XP.

**Comment by brotalnia** [comment]
After some googling, it turns out they had the same issue on mangoszero, but after applying their fix it doesn't seem to work, i still get the crash error.

https://www.getmangos.eu/bug-tracker/mangos-zero/0-archived-reports/Crash-on-shutdown--restart-r879/

https://github.com/mangoszero/server/commit/a13b03a91a5186d1bc6a33e02d388a0f9e23367b

**Comment by WobLight** [comment]
Can anyone test whether it happens on this branch? https://github.com/WobLight/server/tree/map_threading
There's some rework to threads and shutdown, this might be solved as side effect.

**Comment by martinjlowm** [comment]
Assuming it's related, on MacOS, I can confirm the process segfaults on Ctrl-C. I don't know if the "stopped working" dialog is Windows' way of handling segmentation faults. Try to run the process through a debugger and have a look at the stack trace when the process fails.

**Comment by WobLight** [comment]
Warning while debugging this issue: that issue was present in release mode, so following issues are to be ignored (they're present only when debugging):
- index out of range: appy c1dfe1fd15932285dae8458cb64eefbdb7383a5a
- invalid handle: ignore those
