### ISSUE TITLE
Noxxion is untargetable and unlootable after being killed

### ISSUE THREAD

**Issue by t00n** [elysium-project/server#3050]
Just got an bug with Noxxion in Maraudon being untargetable and unlootable.

Happened on Darrowshire, patch 1.8

We were 3 in the instance : warrior, rogue and shaman, lvl 60. We killed Noxxion, then Noxxion's spawns spawned, we killed them and Noxxion's corpse was untargetable, unlootable although we could see it (see the bubbles from lootable corpses).

**Comment by QAkvastskaft** [comment]
See: #2995
