### ISSUE TITLE
Betrayal from Within (Kuz not respawning)

### ISSUE THREAD

**Issue by bschult** [elysium-project/server#3051]
Kuz is not respawning in The Barrens. Quest is Betrayal from Within

**Comment by Spionida** [comment]
Server?

**Comment by bschult** [comment]
Elysium

**Comment by Spionida** [comment]
Kuz is up and about on Elysium

**Comment by bschult** [comment]
I'm here now. I'll be here until he spawns.

**Comment by bschult** [comment]
Spawned. TY
