### ISSUE TITLE
Flayed Demon Skin [Anathema]

### ISSUE THREAD

**Issue by Nahkatatti** [elysium-project/server#3053]
The item "Flayed Demon Skin" provided for the quest "The Corrupter" is not dropping from the Burning Blades in Thunder Axe Fortress - Desolace.

I can confirm that I did get the item with 2 of my friends in less than 10 kills on my other character. However this was before the Scourge invasion update.

Spent 2 hours killing the Burning Blade npc's and I would like to believe that I did kill every single one of them at least once. I do realize that the drop rate of the item is supposed to be 2%; but I find it highly unlikely for me to be this unlucky. Especially when other people have reported this recently for other servers.

If anyone has been able to receive the item AFTER the recent Naxxramas updates please comment and I will go back to confirm this.

**Comment by brotalnia** [comment]
This item has a 2% chance to drop from the following creatures:

> 4663 - Burning Blade Augur
> 4664 - Burning Blade Reaver
> 4665 - Burning Blade Adept
> 4666 - Burning Blade Felsworn
> 4667 - Burning Blade Shadowmage
> 4668 - Burning Blade Summoner
> 4705 - Burning Blade Invoker
> 13019 - Burning Blade Seer

It only drops for Horde characters.
