### ISSUE TITLE
The Missing Diplomat - missing NPC.

### ISSUE THREAD

**Issue by AshixBorden** [elysium-project/server#3054]
The NPC in Stormwind for 'The Missing Diplomat' does not spawn at all. Name of the NPC is Dashel Stonefist in Old Town, Stormwind. He should be in the center of Old Town but after checking several times over 12 hours, he does not seem to spawn.

**Comment by brotalnia** [comment]
This npc was disabled on purpose because of issues with his script. He will be back after the next update.
