### ISSUE TITLE
chat log doesn't work 

### ISSUE THREAD

**Issue by Twelion** [elysium-project/server#3058]
I can't talk in all chats : say , general , trade and even the emotes.
I tried on other characters but it seem only my rogue seem to have this a problem.
I hope you help me out and fix the bug.

greeting Twelion

**Comment by QAkvastskaft** [comment]
Try following this: https://forum.elysium-project.org/topic/54832-chat-not-showing-reset-it/

**Comment by Twelion** [comment]
It's working again, thank for the tip mate :)
