### ISSUE TITLE
Rogue Talent ''Setup'' spell resist component non-functional

### ISSUE THREAD

**Issue by fgt1234** [elysium-project/server#3062]
''Setup'' still doesn't work properly, the dodge part was fixed and it works, however, it doesn't add combo points in spell resists, not versus mobs nor players, it completely lacks this element.
![wowscrnshot_100817_122415](https://user-images.githubusercontent.com/32611073/31319616-80169704-ac6f-11e7-8649-554bdaf73708.jpg)

**Comment by QAkvastskaft** [comment]
This talent works fine for both dodge and resist on the PTR: https://i.imgur.com/dWft3hR.png
