### ISSUE TITLE
Majordomo Executus' adds have extra ability, when they shouldn't.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#3063]
http://wowwiki.wikia.com/wiki/Majordomo_Executus
http://wowwiki.wikia.com/wiki/Flamewaker_Healer
http://www.wowhead.com/npc=11663/flamewaker-healer#comments
The healers shouldn't have the Dark Mending ability. I know it's hard to grasp, but the healers shouldn't heal on this fight.

**Comment by lovemonkeyz** [comment]
I didn't notice them using Dark Mend today. Are you sure you're not thinking of Sulfuron? His adds have Dark Mending.

Anyhow, wowhead/wowwiki isn't accepted sources as they do guarantee validity.

**Comment by Dalleren** [comment]
Wowwiki is not a reliable source.

The Wowhead source is related to patch 3.0.3.

**Comment by ohganot** [comment]
http://www.tentonhammer.com/guides/mc-boss-guide-boss-9-majordomo-executus

Guide from 2005 stating that healers can heal.

**Comment by Cabro** [comment]
You guys are right!
