### ISSUE TITLE
BOSS Lady Jaina Proudmoore <Ruler of Theramore>

### ISSUE THREAD

**Issue by insistgood** [elysium-project/server#3064]
Kill successfully BOSS Lady Jaina Proudmoore <Ruler of Theramore>  There is no money drop and reward , Hopefully the technicians will be able to fix it .Thank you very much.

**Comment by brotalnia** [comment]
She is also not scripted properly. There are a number of abilities she should use in combat.

**Comment by insistgood** [comment]
When will it be ready? Do you have a specific timetable?

**Comment by kampeador** [comment]
Full Theramore isle is just a big placeholder.

**Comment by brotalnia** [comment]
Fixed in https://github.com/elysium-project/server/commit/deea4ac91268b762853c8370db3fdeb3dfe1337f.

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
