### ISSUE TITLE
Darkmoon faire gone too early Anathema

### ISSUE THREAD

**Issue by vindruvor** [elysium-project/server#3065]
https://imgur.com/a/pWHmX

On this picture above you can see that Darkmoon faire is gone from Mulgore at 23:25 (this is when I got here), and from what I understand it should be here until 23.59. The darkmoon faire started 1 october in Mulgore and should end today (sunday 9th october 23.59).

**Comment by kevmodrome** [comment]
Darkmoon Faire was in Elwynn Forest this week.

**Comment by vindruvor** [comment]
kEK
