### ISSUE TITLE
Dragon's Call

### ISSUE THREAD

**Issue by AnafNatan** [elysium-project/server#3066]
Hello,

I'm a hardcore PvP player on wow for over ten years and throughout all expansions and me and my team work on min/max. PvP setups, for one particular setup the Sword >Dragon's Call< from ST is needed so we got two. 
The problem is, though the Dragons get spawned up to three times per sword they don't cast their usual spell Acid Spit which was implemented from the start of vanilla retail instead they engage in meele and don't stay at range to cast their spell.

The Usual damage was around 230-280 Nature per hit from Acid spit on a 2-3sec cast time usually shooting 3 bolts over the 10 sec span meaning 690-840 Nature Damage in total per summoned Whelp / Now it only does around 5-7 Physical Damage with a 1,6-2sec hit timer making the total damage around 25-35ish per summoned Whelp with the occasional Critical hit.

Please fix this Proc asap because atm the Whelps don't even do 5% of the Damage they should do, they do it as Physical therefore engaging in meele and making it even bad in a pve scenario

**Comment by kevmodrome** [comment]
Found a source that confirms some of the information: 
"The whelp is level 55, has 1500 health, and has a ranged attack which does 200-250 points of nature damage."-http://wowwiki.wikia.com/wiki/Dragon%27s_Call?oldid=330276

Not sure which spell is the correct one though. Looking at Wowhead the spell used in the current game is 9591 which corresponds to this spell: http://db.vanillagaming.org/?spell=9591. That very low  when looking at the information about the it being able to do a ranged attack that does 200-250 damage. Does it have a DoT component maybe?

**Comment by AnafNatan** [comment]
http://db.vanillagaming.org/?spell=20657 Should be its the same one just with a higher value - it doesn't have a dot component just hits for around 200-250

**Comment by QAkvastskaft** [comment]
See: #1803
