### ISSUE TITLE
Missing in Action and A Daughter's Love - Bugged quests

### ISSUE THREAD

**Issue by StageIII** [elysium-project/server#3069]
A couple quest bugged for me on Elysium.

Missing in Action - http://db.vanillagaming.org/?quest=219
Followed Corporal Keeshan to the end,spoke with Marshal Marris,selected the reward,but when I clicked 'Complete',nothing happened.

A Daughter's Love - http://db.vanillagaming.org/?quest=231
After turning in The Daughter Who Lived(http://db.vanillagaming.org/?quest=229) ,the quest window for the next part closed as she walked away,now I'm unable to interact with Watcher Ladimore there is a grey exclamation mark on top of her.

**Comment by sadfx** [comment]
Would like to add that Missing in Action is bugged in another way - Corporal Keeshan is supposed to start running once you get to the big slope leading down to Lakeshire, currently he walks the entire way.

Source: Any video ( https://youtu.be/zTES02HAe9w?t=573 bad quality, TBC but any Vanilla video would show the same thing as it wasn't changed)

**Comment by Spionida** [comment]
Probably means that you are too low a level.

**Comment by Cabro** [comment]
Most likely they have some wrong quest level requirements.
