### ISSUE TITLE
Encrypted Twilight Texts don't drop on Anathema 

### ISSUE THREAD

**Issue by Ausser** [elysium-project/server#3085]
Pretty sure I don't need to provide proof that they should be dropping on a server with Naxxramas out.

**Comment by Jbladevr** [comment]
same here... tried to do quests but nope... Killed 100 mobs not a single text nor the set item for the dukes.

**Comment by Ausser** [comment]
Don't worry, the devs are ignoring this issue because apparently not being able to get CC rep is not a big deal.

**Comment by QAkvastskaft** [comment]
See: #1588
