### ISSUE TITLE
First aid quest in Theramore for Alliance Bugged can't learn any new bandages.

### ISSUE THREAD

**Issue by Gibbonsd65** [elysium-project/server#3087]
I got my First Aid up to 225 and once I hit 35 I went to Theramore to do the First aid quest to get Artisan First aid. I completed the quest and received Artisan First aid but then the guy would not let me train for the new bandages.

**Comment by sadfx** [comment]
You need 240 skill to learn Heavy Mageweave Bandage

**Comment by GuybrushGit** [comment]
Taught at 240.
