### ISSUE TITLE
Magic Dust duration

### ISSUE THREAD

**Issue by Hrisiqk** [elysium-project/server#31]
http://db.vanillagaming.org/?item=2091

does not apply its full duration of 30 seconds, it only aplies the effect for about 10 seconds.

The nerf on that item comes 2 expansions later.
http://wow.gamepedia.com/Magic_Dust

Video proof: https://youtu.be/BvID_UBNKYI

**Comment by csundlof** [comment]
That video is not proof that it is supposed to be 30 seconds.

**Comment by nikolay510** [comment]
I think that's because of heartbeat mechanic. Same as Sap and Polymorph, there's always a possibility of break.

**Comment by GuybrushGit** [comment]
Tested this, lasted the full 30 secs.

**Comment by m-laniakea** [comment]
As with most CC spells, it affect Players differently.
