### ISSUE TITLE
[UBRS] Doomrigger's Coffer is not existing. Quest can't be completed.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#3104]
http://db.vanillagaming.org/?quest=4764 can't be completed since the coffer is not present.

**Comment by GuybrushGit** [comment]
Chest exists in dev.

**Comment by Cabro** [comment]
In dev, not in live. I went there earlier, no chest.

**Comment by Cabro** [comment]
Was earlier and it was there... I'm confused.
