### ISSUE TITLE
1.12 World PvP Additions

### ISSUE THREAD

**Issue by Meiji1993** [elysium-project/server#3108]
**Wrong Patch, my bad.**

> "1.12.0 
> World PvP
> 
> The stage is set for intense, objective-based land battles as Horde and Alliance vie for control over important strategic positions and resources around Azeroth. Head out for Silithus and Eastern Plaguelands to engage the enemy on the field! "

Towers and Silithyst Collector are not present on Anathema.

You should be able to capture towers in EPL with various effects such as an extra graveyard, health buff, PvP guards etc.

Players should be able to collect and fight other players for silithyst, which can be turned in at the respective horde and alliance bases in the zone. This gives reputation increases, a small amount of honor and a 5% melee and spell damage buff.

http://wowwiki.wikia.com/wiki/The_Silithyst_Must_Flow
http://wowwiki.wikia.com/wiki/World_PvP
http://wowwiki.wikia.com/wiki/Crown_Guard_Tower
http://wowwiki.wikia.com/wiki/Eastwall_Tower
http://wowwiki.wikia.com/wiki/Northpass_Tower
http://wowwiki.wikia.com/wiki/Plaguewood_Tower

**Comment by brotalnia** [comment]
Anathema is at 1.11.

**Comment by Meiji1993** [comment]
That would explain a lot. Sorry lmao.
