### ISSUE TITLE
sewer beast only spawning in one location

### ISSUE THREAD

**Issue by ImperfectCell** [elysium-project/server#3109]
http://db.vanillagaming.org/?npc=3581

I cant seem to see the sewer beast at the keep. Has this been fixed?

**Comment by sadfx** [comment]
A lot of mobs with multiple spawns are only spawning in one location, especially those who patrol like Bhag'thera, Tideress and many others.

**Comment by Cabro** [comment]
Also a lot of rare mobs only have 1 spawn location.
