### ISSUE TITLE
Honor ranking?

### ISSUE THREAD

**Issue by Alzion123** [elysium-project/server#3113]
Basically i collected 30k honor last week, expecting to reach rank 6 pvp minimum, but ive only gone up from lvl 2 (previous level) to 75% through lvl 3?

**Comment by GuybrushGit** [comment]
You can't go from rank 2 to rank 6 in a single week.

**Comment by Alzion123** [comment]
-.- i originally asked the gm was it a bug, he said yes, go to the forums, post it in there, is it a bug, yes, send me to a different sub section of the forum, ask there, is it a bug, says yes, sends me here, tell you its a bug, you say nope.... >.<

**Comment by Gnockz** [comment]
I think you can't pass more then one rank in a week, system doesn't work this way.

**Comment by thepparker** [comment]
The cap is 2 ranks in a single week of calculations. How much RP you gain is entirely dependent on what everyone else who PVPed that week attained.
