### ISSUE TITLE
Jujus should be removed for alliance until 1.10

### ISSUE THREAD

**Issue by kvalitet** [elysium-project/server#3121]
From my research, Jujus should not be available for Alliance before 1.10 - even though the NPC was moved earlier.
"Juju (Horde-Only)
Witchdoctor Mau'ari in the Valley of Spirits in Orgrimmar (being relocated to Everlook in Patch 1.7) will give you Juju items when you bring her E'ko, which you can sometimes get from creatures throughout Winterspring."
Revision as of 18:08, March 25, 2006
http://wowwiki.wikia.com/wiki/Useful_zone-specific_buffs?oldid=110864

"Juju
Jujus are now available also for Alliance. Witchdoctor Mau'ari is in Everlook will give you Juju items when you bring her E'ko, which you can sometimes get from creatures throughout Winterspring."
Revision as of 11:55, April 15, 2006
http://wowwiki.wikia.com/wiki/Useful_zone-specific_buffs?oldid=120501

Between these two dates you have the patch 1.10:
"Patch 1.10 | 28 March 2006"
http://wowwiki.wikia.com/wiki/Patches/1.x

As you can see the change is obviously made between these two dates - aswell as refering to the move in 1.7 that did NOT open it up for alliance. Juju should not be available in this patch for alliance at all. Considering you are now making an effort to sort the item progression, this is something that should be looked into.

I have also looked at numerous old videos of pre 1.10 AQ40/BWL runs on alliance without finding a single one with jujus before we reach that patch.

Not entirely sure how much evidence is needed as this seems clear, but if more proof is needed i'll try to find it!

**Comment by kampeador** [comment]
You are right.

**Comment by bgfds** [comment]
https://i.imgur.com/3Xw8Kbo.png

Juju Escape - 50% dodge?

**Comment by fgsfdss** [comment]
Juju escape did indeed seem to have 50% dodge until a certain patch:
https://web.archive.org/web/20041105015244/http://wow.allakhazam.com:80/db/item.html?witem=12459

Only evidence of a change I could find is a vague thottbot comment stating it is "broken in patch 1.6":
https://web.archive.org/web/20070321114621/http://www.thottbot.com:80/?i=6909

**Comment by kampeador** [comment]
There were alot of changes with NPC placement.
For example: Storm Shadowhoof, which is standing next to Witchdoctor Mau'ari was in Felwood, Bloodvenom Post.

**Comment by Dasharius** [comment]
So Alliance hunters would lose straight 40 AP. Thing is Winterfall Firewater gave AP instead of MeleeAP until Patch 1.11. If you change the Juju Buff until 1.10 then you should also change the Firewater we were able to use until then.

Problem is then that in-game tooltips are hardcoded into the client. So you couldn't change the firewater because you don't want to "confuse" people. This would be a custom hunter nerf.

http://web.archive.org/web/20060614014938/http://www.thottbot.com:80/?i=38651

**Comment by Sylvestersnr** [comment]
using wowwiki
haha good meme

**Comment by Aleksxz** [comment]
RIP Alliance DPS ^^

**Comment by thepparker** [comment]
Alliance were given Jujus eventually for obvious balance reasons. While we try to emulate Blizzlike progression as much as possible, we also include many balance and mechanic changes earlier than they were introduced in retail. I believe this is one of those cases,

**Comment by Omarthegreatone** [comment]
> Alliance were given Jujus eventually for obvious balance reasons. While we try to emulate Blizzlike progression as much as possible, we also include many balance and mechanic changes earlier than they were introduced in retail. I believe this is one of those cases,

How about removing the cooldown for WCB when we are talking about the balance and mechanics that are not blizzlike.
