### ISSUE TITLE
Cant get "hero of stormpike" quest

### ISSUE THREAD

**Issue by Metaknightt** [elysium-project/server#3139]
I completed "the battle of alterac" quest, and the quest giver does not give me the follow up quest.

**Comment by Dildus** [comment]
Same here.

**Comment by KingKC612** [comment]
I completed both the korrak kill quest and the battle of alterac and no follow up as well.

**Comment by Gnockz** [comment]
There are 2 tickets open already open for this issue.
TLDR: GM has no solving idea yet/expects it to be fixed with next patch/database.

Hope guys :D

**Comment by KingKC612** [comment]
I don't get how it just breaks because I know it worked two weeks ago

**Comment by Metaknightt** [comment]
![2017-10-13 01_45_54-cant obtain _hero of stormpike_ quest - in-game issues - elysium project](https://user-images.githubusercontent.com/32745250/31524194-559204d6-afb8-11e7-8e74-f8663782c225.png)

**Comment by thepparker** [comment]
Duplicate
