### ISSUE TITLE
Darkmoon Card: Blue Dragon wont proc on many insant-cast spells.

### ISSUE THREAD

**Issue by Vivenmort** [elysium-project/server#314]
I've yet to compile an exhaustive list, but I am almost certain that Blue Dragon will not proc on Renew, Rejuvenation, Power Word: Shield Abolish Poison/Disease, Remove Curse, and Dispel Magic. I have done upwards of 1000 casts of these spells without a single proc.

This source confirms that this is not how the trinket worked in Vanilla, where you can clearly see it proccing from a Rejuvenation cast: https://www.youtube.com/watch?v=E1zZrldAz0A&feature=youtu.be&t=5m44s

There are also multiple WoWhead comments for the trinket directly referencing the fact that it procs from spells like Renew and Rejuvenation, and even wanding and crafting items: http://db.vanillagaming.org/?item=19288#wh-comments

**Comment by Phoosy** [comment]
Source https://elysium-project.org/bugtracker/issue/3384
Original Report:
> **BUGGED BEHAVIOR**
> Tested over 400 casts of renew rank 1 on self, no proc
> Tested 100 casts of renew rank 1 on self, while removing buff before refreshing, no proc
> Tested 100 casts of renew rank 6 on self, no proc
> Tested 100 casts of renew rank 1 on friendly NPC, no proc
> Tested lesser heal rank 1 on self, proc'd on 8th cast
> Tested holy nova rank 1, proc'd on 51st cast
> Tested 200 casts of inner fire rank 1, no proc
> Conclusion: Spellcasts that give a buff do not proc the card
> **CORRECT BEHAVIOR**
> According to item description, all spellcasts should have a chance to proc

Post 1:
> Doesn't work for Druids either. 1000 casts of Rejuvenation and Abolish Poison also failed to proc.
> 
> Here's a source clearly showing it proccing on a Rejuvenation. It procs again from Faerie Fire at 3:14: https://www.youtube.com/watch?v=E1zZrldAz0A&feature=youtu.be&t=5m44s
> 
> Literally just has to be coded as "hey, you broke 5 second rule mana regen rule again? chance to proc".

Post 2:
> Factual inaccuracy. Doesn't proc from Faerie Fire in that video, but it does in this one @ 3:14 and another rejuvenation proc @ 1:42:
> 
> https://www.youtube.com/watch?v=Onv-9Y0CBh8&feature=youtu.be&t=1m42s
> 
> This bug also appears to be common on private servers, players have mentioned the same bug for Kronos. May be a part of the Mangos core.
> 
> https://www.reddit.com/r/kronos2wow/comments/4wsvbp/darkmoon_card_blue_dragon_bugged/
> 
> Finally, further research based on WoWhead comments seems to suggest that it can even proc from crafting items or shooting your wand, if those can be trusted. The same comment also specifically mentions it being good for decursing, which it certainly wouldn't be if it didn't proc off of things like Abolish Poison/Disease or Remove Curse/Dispel Magic. Search for the comment by "Traven".
> 
> http://db.vanillagaming.org/?item=19288#wh-comments

**Comment by GuybrushGit** [comment]
A few relevant comments from https://web.archive.org/web/20070521180650/http://www.thottbot.com:80/i19288

>It does not proc off of wands. This was changed in a recent patch. 

>Sometimes the card procs when I am not fighting because I have low mana. However, it doesn not do anythign to help regen out of combat, as innervate does (400% increased regen rate). 

>I was led to believe that Blue Dragon procs on wands and even a TICK of a renew, but this is FALSE. It does, however, proc on in the initial cast of a renew, as well as other instants such as shield, inner fire, fortitude, etc.

>I know Shamans have less Spirit, but the Card can be proc by setting totems right after 1.10 and its nice in Combo with 'Lesser Healing Wave'. 

>also it pwns in dispell fights, when you need to dispell magic, abolish disease or spam heal spells most of the fight time

>  This also applies to innervate. If you stay in the 5-second rule with innervate, it quintuples your normal regen, then multiplies that by 1.3

I seems like it used to proc on every spell cast including wands and crafting and it was later changed to only proc on mana based spells.

**Comment by birdayz** [comment]
Hi,
i am willing to work on this issue, but i have to be pointed into the right direction.
In Spell.dbc ID 23688, it is configured to proc on
```
PROC_FLAG_CAST_SPELL	On spell cast
PROC_FLAG_CRIT_SPELL	On spell critical hit
```
Indeed, after testing it locally (artificially set proc rate to 100 percent), i can confirm that it only procs from casted spells, but not from instants.

However, apparently PROC_FLAG_CAST_SPELL does (intentionally? idk) not proc on instants, like dispel or prayer of fortitude.

Is there a flag for proccing from instants ? Or how is this typically handled ?

**Comment by brotalnia** [comment]
These parts of the code may or may not be relevant:
https://github.com/elysium-project/server/blob/68935cb784738a1c6e9a1f37cbd6707633c11dbe/src/game/Spells/SpellMgr.cpp#L1633
https://github.com/elysium-project/server/blob/400cb2d64ed0c1c0598ce0867314d38e47fb2103/src/game/UnitAuraProcHandler.cpp#L1091
https://github.com/elysium-project/server/blob/095bd19c6a521e0b928e43da1e09a1b0e432b086/src/game/Spells/SpellEffects.cpp#L1782

**Comment by GuybrushGit** [comment]
@birdayz sorry didnt see your comment! I was working on it as well and already submitted a solution

**Comment by birdayz** [comment]
Looks nice! I was about to add a new flag because the current flags don't cover this case.

**Comment by GuybrushGit** [comment]
Related patch notes:
>Darkmoon Fair Card Blue Dragon: This item will no longer trigger from using any ability which does not cost mana.
>http://wowwiki.wikia.com/wiki/Patch_1.11.0

>Item use can no longer trigger the effect on the Five Thunders set or the Darkmoon Card: Blue Dragon trinket.
>http://wowwiki.wikia.com/wiki/Patch_1.10.0

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
