### ISSUE TITLE
Ring of Defense not adding stated defense value

### ISSUE THREAD

**Issue by bdebowski** [elysium-project/server#3163]
Ring of Defense states the following stats for me: (when mousing over the item)

20 armor
requires level 17
Equip: Increased Defense +6

However, when I equip the ring my character's defense value goes up only by 4.

I realize there are some tickets pertaining to problems with defense stats and that some changes have been made.  I did not see anything mentioned about this ring in particular.

**Comment by Kolmarwow** [comment]
your cache is outdated, delete the WDB folder in your WoW files.

**Comment by QAkvastskaft** [comment]
http://wowwiki.wikia.com/wiki/Patch_1.7.0
Blizzard reduced the amount of defense on items by ~33%
