### ISSUE TITLE
Dragonscale Sets - no bonus - intended or bug?

### ISSUE THREAD

**Issue by goldengrif** [elysium-project/server#3178]
As of the patch today, the set bonus for Black Dragonscale is not active, nor does the gear show the set bonus. 

Another post mentions the set bonus, but it would be a retroactive downgrade from what was applied early for prior patches. If you are retroactive downgrading, there should be an announcement, as removing all dragonscale set bonuses effectively nullifies an entire profession.

**Comment by QAkvastskaft** [comment]
These come out with patch 1.8:
http://wowwiki.wikia.com/wiki/Patch_1.8.0
