### ISSUE TITLE
10-19 Warsong Gulch is disabled

### ISSUE THREAD

**Issue by Captmurrica** [elysium-project/server#3179]
--

Players who are level 10-19 cannot queue for Warsong Gulch. The button is missing and WSG Battlemaster NPC is behaving like the AB and AV Battlemasters for all players level 10-19, when last patch it was allowing queues for WSG. I think this is a programming error due to the new patch 1.7 on the Elysium servers that came out today. In actual Vanilla these players couldn't queue till patch 1.8 I believe. So this ZG patch ended up disabling WSG for players levels 10-19. But the bracket could queue before on the previous BWL patch. So it's not fair for players like me who play solely for the WSG 10-19 bracket. It was already previously enabled.

**Comment by storkfan** [comment]
+1

**Comment by brusslord** [comment]
thought it was just me :(:(

**Comment by LIMOUS1NE** [comment]
+1.. please fix this :C

**Comment by koyashi** [comment]
+1

**Comment by Terranzin** [comment]
Hello,

Thanks for reporting this issue. I´m closing this issue, you can follow the new one at https://github.com/elysium-project/bug-tracker/issues/30
