### ISSUE TITLE
Can't learn Poison spec

### ISSUE THREAD

**Issue by denn167** [elysium-project/server#3184]
Greetings all,

I have a rogue by the name of Xeneration although I have a bit of an issue on which I already tried to contact a GM about it and tried his solution to no help since he couldn't help me he suggested to post the issue here so here comes the issue.
I am trying to learn the poisons for a rogue since this is a ability that's basically required for a assasination rogue to be used by. However I have yet to still get the quest even after I hitted 42 I did looked at the quest giver that's supposed to give it but he doesn't give anything to me and only says hello.
Now I also see I have in my bag an quest item which sends me to ravenhold but I already done this and when I click on it it's saying you are already on this quest on which I am not anymore due to me having it completed. Could this be the source of my issue?

**Comment by sadfx** [comment]
The Ravenholdt q isn't the one that gives you Poisons..

This q is what you need..http://db.vanillagaming.org/?quest=2360

**Comment by denn167** [comment]
The issue is the guy called Matthias shaw doesn't give me any quests

**Comment by sadfx** [comment]
In that case it's more likely that you started it and abandoned the chain in Westfall or something. I've done the quest on 5 or more characters on Elysium.

**Comment by denn167** [comment]
Alright i'll be looking at the places where the quest is supposed to be continued however isn't there a way the q line can be restarted or something?

**Comment by sadfx** [comment]
If you haven't completed any of the quests and for whatever reason you can't get the quest, then maybe GMs will assist you.. Idk

**Comment by thepparker** [comment]
I can only imagine that you are only a later part of the chain. Try speaking to Agent Kearnen near Klaven's Tower.
