### ISSUE TITLE
Green lens crafting incorrect variants (Random enchant variants)

### ISSUE THREAD

**Issue by sknnbones** [elysium-project/server#320]
Green Lens, a headpiece crafted by engineers has "Random enchants" upon craft.
# Current Stats
_of Intellect† +24-25 Intellect_

_of Stamina† +24-25 Stamina_

_of the Whale† +15-16 Spirit, +15-16 Stamina_

_of the Owl† +15-16 Intellect, +15-16 Spirit_

_of the Eagle† +15-16 Intellect, +15-16 Stamina_

Are the variants pre-patch 1.3.0

# Correct Stats

As of patch 1.3.0 they should no longer be able to be crafted, only these variants should appear:

_of Concentration +10 mana every 5 sec._

_of Regeneration +6 health every 5 sec._

_of Arcane Resistance +24-25 Arcane Resistance_

_of Fire Resistance +24-25 Fire Resistance_

_of Frost Resistance +24-25 Frost Resistance_

_of Nature Resistance +24-25 Nature Resistance_

_of Shadow Resistance +24-25 Shadow Resistance_

_of Shadow Wrath +34-36 Shadow Spell Damage_

_of Frozen Wrath +34-36 Frost Spell Damage_

_of Arcane Wrath +34-36 Arcane Spell Damage_

_of Nature's Wrath +34-36 Nature Spell Damage_

_of Fiery Wrath +34-36 Fire Spell Damage_

_of Holy Wrath +34-36 Holy Spell Damage_

_of Healing +28-29 Spell Damage_

 # SOURCES
http://wowwiki.wikia.com/wiki/Green_Lens

**Patch 1.3.0** (07-Mar-2005): Green Lens now requires more ingredients to make, but has special effects rather than just stats on it.

Sub-text:

Up until Patch 1.3.0 'Stat Lenses' were able to be created. Stat lenses include: of Intellect, of Stamina, of the Whale, of the Owl, and of the Eagle variations.

### In Patch. 1.3.0, the ability to create these lenses was removed though all items created before the patch remained in-game. 

Therefore, Stat Lenses are incredibly rare and valuable to 39 twinks and collectors.

**Comment by sknnbones** [comment]
Current recipe uses the correct ingredients to make.

**Comment by Solipsismic** [comment]
Yes, the Ingredients required to make it have been increased, but the Itemization Affixes are still the same. RIP

**Comment by sknnbones** [comment]
The recipe already was coded with the newer ingredients required, so that doesn't need to be addressed, however, stat variants are still craftable and spellpower/etc are not.

**Comment by Solipsismic** [comment]
But the 'of Stamina' variant is supposed to not be cradtable anymore.

**Comment by Solipsismic** [comment]
The 'of Stamina' Affix is supposed to be no longer craftable.

**Comment by sknnbones** [comment]
Of stam, of int, of spr, of falcon, of owl, of whale are all still craftable. I have yet to craft any spellpower/mp5/hp5/elementaldmg variants.

**Comment by thepparker** [comment]
Wrath suffixes are added in 1.4
