### ISSUE TITLE
Vanquisher Sword has incorrect stats

### ISSUE THREAD

**Issue by sknnbones** [elysium-project/server#321]
# Current Stats

**Vanquisher's Sword**

_Binds when picked up_

One-hand Sword

41 - 76 Damage

Speed 2.20

(26.6 damage per second)

Durability 90 / 90

Equip: +16 Attack Power.

# Correct Stats

**Vanquisher's Sword**

_Binds when picked up_

One-hand Sword

46 - 86 Damage

Speed 2.20

(30.0 damage per second)

Durability 90 / 90

Equip: +28 Attack Power.

 # SOURCES
http://db.vanillagaming.org/?item=10823

http://wowwiki.wikia.com/wiki/Patch_1.3.0

**_"Vanquisher's Sword and Amberglow Talisman, the rewards for the quests Bring the Light (Alliance) and Bring the End (Horde), have been upgraded to be rare instead of uncommon."_**

http://wowwiki.wikia.com/wiki/Vanquisher%27s_Sword

Changelog {only one patch is ever mentioned for this item in vanilla}(1): 
**Patch 1.3.0** (07-Mar-2005): Vanquisher's Sword has been upgraded to be rare instead of uncommon.

**Comment by thepparker** [comment]
Repost in https://github.com/elysium-project/database if it is still an issue
