### ISSUE TITLE
Long Forgotten Memories - not beeing able to complete, Anathema

### ISSUE THREAD

**Issue by fidbugs** [elysium-project/server#3214]
This quest is can not completed. When you come to the red crystal, window pops up, but clicking complete does nothing. Tried cleaning WDB/WTF, loading with no addons, dropping quest than retaking it - nothing works, still cant complete.

**Comment by Terranzin** [comment]
I´ve moved this to our new bug tracker, follow it here: https://github.com/elysium-project/bug-tracker/issues/41
