### ISSUE TITLE
Brutal Armor Quest

### ISSUE THREAD

**Issue by Frooger776** [elysium-project/server#3221]
So after reviewing articles online I have yet to find anything seeing a bug related to the Brutal Armor Quests for level 20 warriors. I am currently a level 21 undead warrior and have found all required items to turn in the quest. In my quest log it says complete, but when I go to turn it in to Firegaze he has a greyed out question mark and it does not allow me to turn it in. I've tried reloading, turning addons off, even banking and unbanking nothing is working. 

any help would be appreciated.

**Comment by xniko** [comment]
[Someone had a similar issue](https://github.com/elysium-project/server/issues/1447) that they solved, check the comments under the issue and see if it could help you as well.

**Comment by Frooger776** [comment]
Tried many ways those threads explain. None worked thank you for the post though

**Comment by Terranzin** [comment]
I´ve moved this to our new bug-tracker: https://github.com/elysium-project/bug-tracker/issues/44
