### ISSUE TITLE
Mokvar missing

### ISSUE THREAD

**Issue by LordStannis** [elysium-project/server#3223]
Hi there, i was trying to start a chain quest to upgrade my magister set to the sorcerors one, but the NPC that starts the questline is missing..
Here is the link for the first quest of the line: http://db.vanillagaming.org/?quest=8915
And here is the link for the NPC: http://db.vanillagaming.org/?npc=16012
thanks

**Comment by brotalnia** [comment]
What realms is he missing on? This npc was added in patch 1.10.

**Comment by LordStannis** [comment]
i'm on elysium, yesterday was last time i went to check and he was still not there :(

**Comment by brotalnia** [comment]
Both the quest and npc you linked have their minimum patch set to 1.10, why do you believe they should be available earlier than that? Elysium's content is on 1.7 currently.

The official patch notes seem to indicate that 1.10 is indeed the patch in which they were added.
https://github.com/elysium-project/database/blob/master/new_progression/Patchnotes%20%28ALPHA%20to%201.12.1%29.txt#L1670

The allakhazam page of the quest and npc also indicate that they were added in 1.10.
https://web.archive.org/web/20070104161735/http://wow.allakhazam.com:80/db/quest.html?wquest=8915
https://web.archive.org/web/20071028183445/http://wow.allakhazam.com:80/db/mob.html?wmob=16012

It even says this on the quest page:
> Added: Mar 29th, 2006

Which is the release date of the 1.10.0 patch.
