### ISSUE TITLE
Alterac Spring Water buff (10 spirit) is overwriting max rank Divine Spirit (40 spirit). 

### ISSUE THREAD

**Issue by ThousandLakes** [elysium-project/server#3228]
I'm assuming this is a bug because spirit scrolls and lower ranks of Divine Spirit don't overwrite max rank Divine Spirit. Instead, they trigger the 'a more powerful spell is already active' message. This is a big problem because as a priest it renders Divine Spirit unusable on yourself.

**Comment by Terranzin** [comment]
I´ve reviewed your reported issue and manage to reproduce the same error.

**Use-case:**
- Used Alterac Spring Water (Id: 23698) _Spell triggers on ID: 23697_ 
- Spring water buff is applied on character.
- Used Divine Spirit (ID: 27841).
- Divine spirit is correct applied - Spring water buff gets overwritten by a stronger buff.
- Used Alterac Spring Water, the stronger effect which is in this case Divine Spirit gets removed and instead changed to Spring water spell effect.

**Comment by Terranzin** [comment]
This issue has been closed on this tracker, you can follow the issue here https://github.com/elysium-project/bug-tracker/issues/28
