### ISSUE TITLE
Rogue "Shattered Salute" class quest is bugged and cannot be finished

### ISSUE THREAD

**Issue by tolga-dede** [elysium-project/server#3229]
Got quest but upon clicking "Coplete Quest" button nothing happens. Please help this because i believe this is rogue poison quest...

Forgot to mention: I didn't get the pipe item when to use performing the salute.

**Comment by Terranzin** [comment]
Hello,

I´ve moved this issue into our new bug-tracker, please follow it here: https://github.com/elysium-project/bug-tracker/issues/38
