### ISSUE TITLE
BRD Thorium Brotherhood: Recipe: Transmute Elemental Fire

### ISSUE THREAD

**Issue by Woodstalker** [elysium-project/server#3245]
I write this in a GM ticket:
     Hi GM,
     i got a little question:
     "Recipe: Transmute Elemental Fire" should be available with the version of this server, but it is not.
     The prescription is not available or am I too stupid to get it?
     When is the prescription available on the server, is it foreseeable?
     Kind Reguards

After that i become the info that i have to report that here.
So plz put the "Recipe:Transmute Elemental Fire" to the place where it belongs, thanks

**Comment by Fleisher** [comment]
Hello,
Recipe; Transmute Elemental Fire was added in 1.9 Patch therefore it is unavailable on Elysium realms.

Report denied.d

**Comment by Woodstalker** [comment]
But the patch 1.9 is coming in Dezember 2017... so?
