### ISSUE TITLE
Kim'jael Indeed!

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#3250]
Hi guys

This quest is bugged because one item doesn't drop although all items should drop with an 100% chance. I think it's the Wizzlegoobler that isn't to be found in any of the boxes the items are supposed to  be in.

**Comment by Fleisher** [comment]
Items are not 100% drop chance as stated in multiple sources available. Report closed.

**Comment by Pisshead** [comment]
I opened 1 Box and three of the needed Items came out, so something must be wrong anyway... And after that I opened another 10 to 20 boxes and the last item did NOT drop... Now You tell me there is everything fine with that quest...
