### ISSUE TITLE
Warlock Talent "Shadow burn" in "Destruction" tree doesn't work

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#3251]
Hi guys.

After I killed a mob (that gives XP) with my "shadow burn" it shoiws in the loot chat that it generated a soul shard and I can also see the icon dropping into my soulshard bag or any bag for that matter, but after that it disapears. If I generate soul shards with drain soul there is no such problem.

Greez

Pisshead

**Comment by Fleisher** [comment]
Tested on the PTR - Shadowburn provides Soul Shard on mob/player that grants XP to your level. Report denied.

**Comment by Pisshead** [comment]
Yep my bad. I dind't realize the spell consumes one shard
