### ISSUE TITLE
Blasted Lands: Quests of the two blood elves

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/server#3252]
hi guys

These quests should appear with blue question marks after you finished them the first time, due to them being repeatable. In Feralas it's the other way around with the goblin. They are from the beginning with blue question marks inatead of being a yellow exclamation point first.

**Comment by Terranzin** [comment]
Hello,

We´re closing this bug tracker, you can follow your issue at https://github.com/elysium-project/bug-tracker/issues/29

**Comment by twink** [comment]
Need list of quests.
