### ISSUE TITLE
Particular item bonus problem?

### ISSUE THREAD

**Issue by Dachops** [elysium-project/server#3254]
Hello all I am trying to find info on a particular item bonus.  "Adds 3 lightning damage to your melee attacks."

I have gathered an item called Storm Gauntlets: +3 lightning damage

I have heard there was a strategy pertaining to the Kazzak necklace Blazefury Medalion (+ 2 fire damage) where you could potentially stack spell power and it would increase the number accordingly.

Currently with the gloves they already seem broken? The gloves themselves grant 3 lightning damage but also give 21 nature damage to your spells and effects, that should already make the base damage of the gloves at least higher than the base 3 damage no?

In some research I have found or heard others say this should work with the game mechanics.

Whether things are working as intended or no I just wanted to find out if this theory works with the necklace still and if these gloves should act the same. Possibly work some gm in game magic with the two items and some sp gear and see how it goes? 

Thanks!

**Comment by Fleisher** [comment]
Hello,
Items that have certain proccs like two mentioned by the reported are not meant to scale with spell damage.

Closed.
