### ISSUE TITLE
Shimmering Flats Ooze Covered Mithril Deposit not working

### ISSUE THREAD

**Issue by damagepy** [elysium-project/server#3257]
In Shimmering Flats at southwest silithid (69,85) area the Ooze Covered Mithril Deposits give nothing (only skill on first try) no loot at the end of mining and can try to mine forever, nothing happens, its the same with all mithril deposit here, silver ones work fine

**Comment by damagepy** [comment]
thanks, now they working

**Comment by WardenElysium** [comment]
Closed.
