### ISSUE TITLE
Unable to Invite Guild Members

### ISSUE THREAD

**Issue by Barthas-Nighthaven** [elysium-project/server#3259]
After Reaching 321 Members all members that have invite privileges in the guild, are unable to invite future members.

After inviting a character, the character is stuck pending guild invitation acceptance. The pending status lasts for an open ended amount of time. Character currently affected by the pending invite is "Reddot", a Dwarf Hunter. I placed the invite to him hours(+3) ago and he is still pending invite. 

Realm : Nighthaven PvP
Guild : Venerated
Members : 321

**Comment by Zaitsev11** [comment]
321 is the max limit as defined on line 42 in the following file:
https://github.com/elysium-project/server/blob/development/src/game/Guild/Guild.h
