### ISSUE TITLE
NPC doesn't teach Ultrasafe Transporter: Gadgetzan (engineering) schemetics properly

### ISSUE THREAD

**Issue by damagepy** [elysium-project/server#3260]
Tanaris/Gadgetzan, NPC: Jhordy Lapforge
He is next to the Gadgetzan teleporter, and supposed to teach the schematics (for 260+ gnome engineers) but after selecting the conversation:
"I must build a beacon for this marvelous device!" it does the "learning" effect but the schematics is not added (Ultrasafe Transporter: Gadgetzan) so we can't build it. Can choose the conversation many times, same effect...
Happened to other engineers too, and its one of the reason I chosen gnome engi :)
"spell": http://db.vanillagaming.org/?spell=23489
the item: http://db.vanillagaming.org/?item=18986
if can't be fixed, then can I contact a GM to give the actual item and remove the mats from the inventory?

**Comment by Terranzin** [comment]
I´ve moved your issue to our new bug-tracker, https://github.com/elysium-project/bug-tracker/issues/43
