### ISSUE TITLE
/who and who tab does not work properly.

### ISSUE THREAD

**Issue by Midnatt** [elysium-project/server#3262]
Using /who command or via the Who tab, and searching for specific classes or guilds It doesn't show It._
Example: I write "mage" in the who window, It prints all characters with "mage" in the name, not the classes itself or characters in the specific guild Im searching for.

**Comment by Terranzin** [comment]
Hello,

I´m closing this issue and moving it to the new bug tracker, you can follow the process here: https://github.com/elysium-project/bug-tracker/issues/37
