### ISSUE TITLE
Priest Talent - Spirit Tap 

### ISSUE THREAD

**Issue by Catlynjenner** [elysium-project/server#3263]
Issue is when 5/5 of Spirit Tap is selected it gives 100% chance to proc Spirit Tap.  While in a group however, and killing mobs that would and in this case do, because i'm still leveling. It doesn't proc the 100% chance of Spirit Tap. Usually seems to be an issue with mobs that are elites that I group for and non- elites seem to proc Spirit Tap in a group.

TL:DR - Spirit Tap isn't proc'ing 5/5 when in a group killing elites

**Comment by Terranzin** [comment]
Hello,

I´m closing this issue and reopened it in our new bug-tracker, you can follow the progress here: https://github.com/elysium-project/bug-tracker/issues/31
