### ISSUE TITLE
Darrowshire paladin deal of crusader 

### ISSUE THREAD

**Issue by paparouge** [elysium-project/server#3265]
Seal of crusader tool tip states 40% weapon sod increase but is only doing 30%

Using blue glittering axe wpn spd 1.8 should be 1.08 but is showing 1.26 which is a 30% increase not 40%

**Comment by Terranzin** [comment]
Thanks for reporting this issue, i´ve moved the issue to our new bug-tracker. https://github.com/elysium-project/bug-tracker/issues/42
