### ISSUE TITLE
Incorrect stats on ring

### ISSUE THREAD

**Issue by furyen** [elysium-project/server#3266]
Hi,
I got this quest reward ring https://i.imgur.com/hEOsObh.png

When I equip it though I don't get the stats it says I should but I get 2 stamina and 5 spirit only. GMs directed me here. Can you help?
Character name - Prychka
Thanks

**Comment by Terranzin** [comment]
Please add this issue to following bug-tracker. https://github.com/elysium-project/bug-tracker/issues
