### ISSUE TITLE
Orc racial talent Blood Fury

### ISSUE THREAD

**Issue by zacharyzhang89** [elysium-project/server#3268]
In the PTR server. I tested a Orc rogue. With T2 gears on the Blood Fury only gives about 18% of the AP, which should be 25% AP as described in the tooltips of Blood Fury. 
With no gear on the character. The Blood Fury give 25% of the AP, which is correct. So there should be some AP from the gears or enchants are not being counted in the Blood Fury spell. 
I propose to check whether the Blood Fury counts the agi, str, AP comes from the gears and enchants, including crusader.
Thank you

**Comment by Navashed** [comment]
Confirmed and added to the new bug tracker: https://github.com/elysium-project/bug-tracker/issues/105
