### ISSUE TITLE
 Flurry activates on ranged critical hit: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#327]
BUGGED BEHAVIOR
When you land a critical hit with a ranged weapon flurry activates. The talent clearly states "melee critical hit".

 CORRECT BEHAVIOR
Flurry should only activate on melee critical hits.

 SOURCES
Me?

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/2161

**Comment by QAkvastskaft** [comment]
Might not really be confirmed. Seems to be some confusions with the tags/comments. Gonna recheck during today

**Comment by Unknown-as-Captain** [comment]
I can secondhand confirm this, happens commonly when doing ranged pulls with a gun/bow, but I have no proof right now.
