### ISSUE TITLE
Tarren Mill Quests - [32] Battle of Hillsbrad + [28] Elixir of Agony bugged

### ISSUE THREAD

**Issue by zeetto** [elysium-project/server#3271]
Hello Project Elysium
First of all, great job on the server it works wonders and is great fun to play with my wife, the old WoW Vanilla that we know. 
Regarding the quests in Tarren Mill by the name [32] Battle of Hillsbrad and [28] Elixir of Agony. They're chain quests and has a quest where you need to visit Undercity, to get some awesome loot at the end. We were lvl 24 when we completed the last quest for [28] Elixir of Agony where the minimum requirements are 24, when we accepted the second quest, it just gave the error "you don't meet the requirements for that quest" and then the questgiver just can't give us the quest again. The same happened for the end quest for [32] Battle of Hillsbrad the minimum requirements is 19 and we were 26 when the same error turned up. We really looked forward to the gear from both quests, and to get further in the game. But nothing more happens for us now at Tarren Mill, before we get to lvl 30, because of theese bugs. Didn't record the time, for the first bug, but it was 21-11-2017 around 20:00 and the [32] Battle of Hillsbrad bugged out at 22-11-2017 around 14:30 (GMT+1) 

Elixir of agony quest 2 : https://web.archive.org/web/20070115075212/http://www.thottbot.com:80/?qu=513
Battle of Hillsbrad questline, (the end quest bugged) : 
https://web.archive.org/web/20060428113930/http://www.thottbot.com:80/?s=battle+of+hillsbrad 

Please write back ASAP :) <3 
BTW good job!

**Comment by zeetto** [comment]
The quest requirements are somehow set to lvl 30 now.

**Comment by Navashed** [comment]
Confirmed and moved to the new bug tracker:

https://github.com/elysium-project/bug-tracker/issues/110
https://github.com/elysium-project/bug-tracker/issues/111
