### ISSUE TITLE
Find OOX-09/HL! Not working

### ISSUE THREAD

**Issue by zelronking** [elysium-project/server#3273]
The Quest Find OOX-O9/HL! isn't working. The distress beacon says the level requirement is 43, but it says "you do not need the requirements for that quest" when i try to start. This is apparently a long-standing issue (more details here: https://forum.elysium-project.org/topic/46345-oox-09hl-distress-beacon-you-dont-meet-the-requirements-for-that-quest-bug/)

**Comment by Seebaby** [comment]
Fix Quest level ist false 



DELETE FROM `creature_questrelation` WHERE `quest` = 485;
DELETE FROM `gameobject_questrelation` WHERE `quest` = 485;
UPDATE `item_template` SET `StartQuest`=0 WHERE `StartQuest` = 485;
UPDATE `item_template` SET `startquest`=485 WHERE `entry` = 8704;
DELETE FROM `creature_involvedrelation` WHERE `quest` = 485;
DELETE FROM `gameobject_involvedrelation` WHERE `quest` = 485;
INSERT INTO `creature_involvedrelation` (`id`, `quest`) VALUES (7806, 485);
UPDATE `creature_template` SET `npcflag`=`npcflag`|2 WHERE `entry`=7806;
REPLACE INTO `quest_template` (`entry`, `Method`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `Type`, `RequiredClasses`, `RequiredRaces`, `RequiredSkill`, `RequiredSkillValue`, `RepObjectiveFaction`, `RepObjectiveValue`, `RequiredMinRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepFaction`, `RequiredMaxRepValue`, `SuggestedPlayers`, `LimitTime`, `QuestFlags`, `SpecialFlags`, `PrevQuestId`, `NextQuestId`, `ExclusiveGroup`, `NextQuestInChain`, `SrcItemId`, `SrcItemCount`, `SrcSpell`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqSourceId1`, `ReqSourceId2`, `ReqSourceId3`, `ReqSourceId4`, `ReqSourceCount1`, `ReqSourceCount2`, `ReqSourceCount3`, `ReqSourceCount4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOId4`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `ReqCreatureOrGOCount4`, `ReqSpellCast1`, `ReqSpellCast2`, `ReqSpellCast3`, `ReqSpellCast4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewOrReqMoney`, `RewMoneyMaxLevel`, `RewSpell`, `RewSpellCast`, `RewMailTemplateId`, `RewMailDelaySecs`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `StartScript`, `CompleteScript`) VALUES (485, 2, 47, 43, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 836, 8704, 1, 0, 'Find OOX-09/HL!', 'You have uncovered some sort of strange, egg-shaped device made from metal.  Fiddling with one of its knobs springs the egg to life, as it opens up into some sort of gnomish robotic contraption!  A voice from inside the robotic egg crackles to life.$B$B"My name\'s Oglethorpe Obnoticus, and my homing robot has crashed!  I will reward you for its recovery; please take this beacon to the robot!"$B$B"I now have computed the coordinates of the robot for you; it crashed at the head of the river near Skulk Rock!"', 'Take the distress beacon to Oglethorpe\'s homing robot at the head of the river in the Hinterlands, near Skulk Rock.', 'You place the egg... distress beacon... inside the chicken... homing robot.$b$bHums and whirs are heard from inside the robot as it struggles to stand up. After the robot comes to life, Oglethorpe\'s voice is heard once more, but now from inside the robot:$b$b"OOX-09/HL is working at least, but it needs major repairs! It is much too heavy for you to carry it... but I think I have an idea. Are you up for watching over it some more?"', 'You appear to have uncovered the wreckage of... a robotic chicken? The voice from within the egg crackles to life again:$b$b"Yes, excellent work! This is indeed my homing robot, though my sensors indicate that it needs a jump start before it can fly back to Booty Bay for repairs. Go ahead and place the beacon inside the rover - the beacon will take care of the rest!"', '', '', '', '', '', 8704, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 87, 21, 0, 0, 0, -250, 250, 0, 0, 0, 0, 3750, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

**Comment by Navashed** [comment]
Reproduced.

Quest 485 - Find OOX-09/HL! requires level 46.
Item 8704 - OOX-09/HL Distress Beacon claims it requires level 43.

Almost certainly Quest 485 should require level 43. However I have been unable to find definitive proof of this from an old database.

**Comment by Terranzin** [comment]
We´re moving this issue into our new bug tracker, you can follow the process there: https://github.com/elysium-project/bug-tracker/issues/104
