### ISSUE TITLE
Quest:A Dark Threat Looms (7) bugged

### ISSUE THREAD

**Issue by VictorAnderfelt** [elysium-project/server#3274]
--

Quest: A Dark Threat Looms (7) (in Loch Modan)
When accepting the last quest in the quest chain, given from the explosive keg, the quest disappears and cannot be taken from the keg. 2017-11-24

**Comment by Terranzin** [comment]
Hello, we´ve moved this issue to our new bug tracker, please follow it there
https://github.com/elysium-project/bug-tracker/issues/100
