### ISSUE TITLE
Quest malfunction: Ledger from Tanaris

### ISSUE THREAD

**Issue by jontehack** [elysium-project/server#3276]
--

Write your report here
There is a issue regarding the quest "Ledger from Tanaris" id: 4450, where the quest cannot be turned in, 
Even if all item's is in inventory, doing the add to bank and take out trick do not work, neither do a wdb update, or any reset. 
Please have a look at this, since i know alot of people are having problems with this1

**Comment by Navashed** [comment]
Unable to reproduce.

Quest 4450 - Ledger from Tanaris was handed in with no problems to NPC 5411 - Krinkle Goodsteel upon satisfying completion criteria.
