### ISSUE TITLE
Darrowshire: Alliance Quest Wounded Ancients

### ISSUE THREAD

**Issue by kcharles67** [elysium-project/server#3278]
It seems that the quest Wounded Ancients acquired from Kaela Shadowspear seems to be missing.

**Comment by Navashed** [comment]
Unable to reproduce.

Quest 1084 - Wounded Ancients is offered as a follow-up to Quest 1083 - Enraged Spirits.

![620b3f0436e3ac8167f777534b463360](https://user-images.githubusercontent.com/2709545/33349523-7dbbbc0c-d468-11e7-93f3-b50f64084766.jpg)
