### ISSUE TITLE
Quest: Cuergo's Gold isn't repeatable

### ISSUE THREAD

**Issue by Gnomercey** [elysium-project/server#3279]
Quest Cuergo's Gold isn't repeatable. Blizzlike it should be repeatable. When i click on a new map after u finish quest it says "You're already on this quest. Can't see quest in quest log, got the chest from last quest so it should be completed.

**Comment by Navashed** [comment]
Confirmed and added to the new bug tracker: https://github.com/elysium-project/bug-tracker/issues/108
