### ISSUE TITLE
data files generated by extractors cannot startup server core

### ISSUE THREAD

**Issue by defsky** [elysium-project/server#3280]
when I compile the core and extractors , I extract the data files by extractors (ad vmapextractor vmap_assembler MoveMapGen).
But when startup mangosd, errors bring out.

**error log:**
VMap file '/elysium/wowserver/data/vmaps/000.vmtree' is missing or point to wrong version vmap file, redo vmaps with latest vmap_assembler.exe program
Correct *.map files not found in path '/elysium/wowserver/data/maps' or *.vmtree/*.vmtile files in '/elysium/wowserver/data/vmaps'. Please place *.map and vmap files in appropriate directories or correct the DataDir value in the mangosd.conf file.
[root@centos65 bin]# ls /elysium/wowserver/data/vmaps/000.vmtree -l
-rw-r--r--. 1 root root 13109 11\u6708 26 16:54 /elysium/wowserver/data/vmaps/000.vmtree

**vmapextractor error log:**
[root@centos65 tools]# ./vmapextractor -l -d ~/World\ of\ Warcraft\ 1.12_chs/Data
Unable to open LOS Modificators.
Extract for VMAPz04. Beginning work ....

Game path: /root/World of Warcraft 1.12_chs/Data/
Opening data files from data directory.
Scanning patch levels from data directory.

Opening /root/World of Warcraft 1.12_chs/Data/patch.MPQ
Opening /root/World of Warcraft 1.12_chs/Data/patch-2.MPQ
Read LiquidType.dbc file...Done! (5 LiqTypes loaded)
Extracting WORLD\wmo\PvP\Buildings\CTF\CTFOrc_A.wmo
Extracting World\wmo\Azeroth\Buildings\DuskwoodAbandoned_HumanTwoStory\DuskwoodAbandoned_HumanTwoStory.wmo
No such file.
Could not open all Group file for: DuskwoodAbandoned_HumanTwoStory.wmo
Extracting World\wmo\Azeroth\Buildings\Duskwood_Barracks\duskwood_barracks.wmo
No such file.
Could not open all Group file for: duskwood_barracks.wmo
Extracting World\wmo\Azeroth\Buildings\Duskwood_Blacksmith\Duskwood_Blacksmith.wmo
Extracting World\wmo\Azeroth\Buildings\Duskwood_HumanTwoStory\Duskwood_HumanTwoStory.wmo
No such file.
Could not open all Group file for: Duskwood_HumanTwoStory.wmo
Extracting World\wmo\Azeroth\Buildings\Duskwood_Inn\Duskwood_Inn.wmo
No such file.
Could not open all Group file for: Duskwood_Inn.wmo
Extracting World\wmo\Azeroth\Buildings\Duskwood_TownHall\Duskwood_TownHall.wmo
No such file.
Could not open all Group file for: Duskwood_TownHall.wmo
Extracting World\wmo\Azeroth\Buildings\Duskwood_TownHall_NoWall\Duskwood_TownHall_NoWall.wmo
No such file.
Could not open all Group file for: Duskwood_TownHall_NoWall.wmo
Extracting World\wmo\Azeroth\Buildings\GuardTower_Ruined\RuinedHumanGuardTower01.wmo
Extracting World\wmo\Azeroth\Buildings\HumanTwoStory\HumanTwoStory.wmo
No such file.
Could not open all Group file for: HumanTwoStory.wmo
Extracting World\wmo\Azeroth\Buildings\Human_Barracks\Human_Barracks.wmo
Extracting World\wmo\Azeroth\Buildings\Moonbrook_HumanTwoStory\Moonbrook_HumanTwoStory.wmo
No such file.

**compile steps:**
1. cmake ../source/server/ -DPREFIX=/elysium/wowserver -DUSE_EXTRACTORS=1 -DUSE_UTILITY=1
2. make 
3. make install

**Comment by Terranzin** [comment]
Hello,

We´re do not supply support how to host your own server, you´ll need to figure this information out for yourself I´m afraid.
