### ISSUE TITLE
Druid level 14 Cure Poison quest "Lessons Anew" not available on Elysium: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#329]
BUGGED BEHAVIOR
Did not receive mail from Turak Runetotem to begin the "Lessons Anew" quest to open up the questline to learn Cure Poison. This should have happened at level 14, but I am now 20 and have never been given the quest. It is also not available in TB from him directly. I have completed the prerequisite quest "Heeding the Call".

 CORRECT BEHAVIOR
At level 14, druids should receive mail from Turak Runetotem to being the "Lessons Anew" quest.

 SOURCES
http://db.vanillagaming.org/?quest=6126

COMMENTS from QAKvastskaft:

Good catch @Druidia, you are correct. The 2 quests from Pala and Gart are not properly working as pre-quests for Lessons Anew.

Quest id: 5927 from Gart Mistrunner
Quest id: 5928 from Innkeeper Pala
Should, when completed, make quest id: 6126, available.

The bug present can also be seen here.

Quest 5926 (http://db.vanillagaming.org/?quest=5926) opens Lessons Anew 
Quest 5927 (http://db.vanillagaming.org/?quest=5927) does not open Lessons Anew
Quest 5928 (http://db.vanillagaming.org/?quest=5928) does not open Lessons Anew

(http://db.vanillagaming.org/?quest=6126)

This likely affect all realms but tested on 1.9 QA realm

Original post on bug tracker here:  https://elysium-project.org/bugtracker/issue/1744

**Comment by GuybrushGit** [comment]
Lessons Anew does not require Heeding the Call:
http://web.archive.org/web/20070510113425/http://www.thottbot.com:80/q6126

What requires is Moonglade: 
http://web.archive.org/web/20070322102409/http://www.thottbot.com:80/q5922

**Comment by m-laniakea** [comment]
Fixed.
