### ISSUE TITLE
NPC Thrash spell OP

### ISSUE THREAD

**Issue by Fr4nsson** [elysium-project/server#33]
Update: Made a pull request, thank you brotalnia for the help.

NPCs that has the Thrash spell should not allow the player to issue it manually, like the scarlet monks for example. Fix down below.

https://github.com/elysium-project/server/pull/36/commits/3812027de1a845a8c9e243c3f865d85838a865f7

**Comment by StadenElysium** [comment]
Accepted, thanks.

**Comment by bdebaere** [comment]
I don't really understand this commit.
http://www.wowhead.com/npc=4540/scarlet-monk mentions 2 controlled spells, one of which is 3391.

Can anyone enlighten me? :)
