### ISSUE TITLE
Untrained weapons showing as usable: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#331]
BUGGED BEHAVIOR
Essentially, some weapons show up as usable, meaning white text instead of red, despite being untrained/unusable.

 CORRECT BEHAVIOR
Untrained/unusable weapons should show up as being unusable, meaning red text.

 SOURCES
http://imgur.com/a/Fny5y

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/827

**Comment by thepparker** [comment]
The only way I could replicate this is by giving myself the weapon skill and then removing it, which shouldn't be happening. 

Weapons aren't meant to have skill or spell requirements listed on them (which is what is seen with 2H maces/axes), and the issue disappears with a relog. We could add a skill requirement to all weapons (the current requirement on 2H maces/axes is to facilitate the shaman 2H talent), however you can see in past videos of players looting items that no skill requirement is listed. Only the weapon type or hand type is red to indicate that it cannot be used.

For some reason players are being sent incorrect weapon and armour proficiencies... more investigation to come.
