### ISSUE TITLE
Blind consumes ranged ammunition and provides ranged weapon skill

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#336]
Bugged behavior : 
The rogue ability Blind is consuming Blinding Powder as intended but also ranged ammunition (equipped bullets/arrows) upon cast.

It is also able to provide bow/gun/crossbow weapon skill each time it is used.

Correct behavior : 
Blind should only consume Blinding Powder and not provide ranged weapon skill.

The issue might be related to how Blind was changed, first in 1.10 and then during TBC. 

References just for information : 

- In vanilla, Blind is supposed to be a simple ranged attack after patch 1.10*.
_*Patch 1.10 (3/28/06) : "Blind - Now considered a ranged attack. It can no longer be dodged or parried."_

Sources for Blind behavior prior to patch 1.10 : http://www.shadowsongeurope.com/forum/archive/index.php/t-10844.html (copy/pasting for convenience)
_"Abberare 18-02-2006, 01:06 AM
Improve the hit chance of blind, wasting Fadeleaf on Hunter/lock pets that parry/dodge it makes me sad :("_
_"Copis 18-02-2006, 01:12 AM
Yep went to blind a silithid bug today so I could bandage up. Naturally it *parries* the powder then crits me dead."_

- In TBC, it was changed to a ranged physical attack.
_Patch 2.3.0 (11/13/2007) : "Blind is now a physical (no longer a poison) attack. Reagent requirement removed. Now shares the same diminish category as Cyclone and is now diminished in PvE as well as PvP."_

**Comment by Ripper007** [comment]
This is an old one, probably linked to MaNGOS, Nost had it, old Elysium PVP had it.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
