### ISSUE TITLE
Garr adds don't die after getting Massive Eruption casted on them.

### ISSUE THREAD

**Issue by Aklol** [elysium-project/server#339]
Garr adds when below 50% are supposed to have a chance to get casted on them by Garr "Massive Eruption" (spell id 20483). This is supposed to explode the add, killing it, and cause massive damage and knock back every player in a 30 yard radius.

In this video, you can see Massive Eruption get casted on the Skull target, and the Skull does not die:

https://clips.twitch.tv/VivaciousHeartlessNewtKevinTurtle

**Comment by Oudeis1447** [comment]
Can we have prove that Garr ever used that skill to begin with? I see no trace of it in any guide and my memory as a vanilla warlock.
http://wowwiki.wikia.com/wiki/Garr
