### ISSUE TITLE
Many humanoids in arathi highlands and hillsbrad is missing spells when MC'd and have wrong stats

### ISSUE THREAD

**Issue by Fr4nsson** [elysium-project/server#34]
Update: Made a pull request with the changes.

Many of the npc's have their stats and spells wrong. Fix down below.

https://github.com/elysium-project/server/pull/37/commits/453293d197d3453b9fca1229e4d80cc84b68ca32

**Comment by AndersSahlin** [comment]
For yourself and future readers, this is how you create a pull request from the web interface:

1) fork this repository and give it a topical name, for ex. "ah-humanoids" 
2) edit or add source files in your fork: 
https://help.github.com/articles/editing-files-in-your-repository/
https://help.github.com/articles/creating-new-files/
3) create a pull request from your fork: 
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
4) delete your fork after the PR has been merged (optional): https://github.com/blog/1335-tidying-up-after-pull-requests

Hope this helps!

**Comment by Fr4nsson** [comment]
Thanks gonna look into it.
