### ISSUE TITLE
Missing outcomes from Savory Deviate Delight on Zeth'Kur and Elysium

### ISSUE THREAD

**Issue by Aklol** [elysium-project/server#340]
Credit to Elysium Bugtracker submission.

BUGGED BEHAVIOR
Savory Deviate Delight currently only has two outcomes. Pirate or Ninja.

CORRECT BEHAVIOR
Prior to patch 1.6 (BWL), Savory Deviate Delight had a few more possible outcomes. To be more' specific, consuming a Savory Deviate Delight had a chance to trigger one of the following spells:

Yaaarrrr - Pirate form for 60 minutes.
Flip Out - Ninja form for 60 minutes.
Oops - Goo form, causing 600 aoe threat and increasing damage taken by 50% for 10 seconds.
Cowardice - 5 second fear on application, 10minute dispellable debuff that randomly fears you while in combat.
Fake Death - Feign death for 5 minutes. Cancelled upon moving.
Rapid Cast - 100% spell haste for 120 seconds.
? - Instantly gain 50 rage upon use.

SOURCES
http://web.archive.org/web/20060216123455/

http://wow.allakhazam.com/db/item.html?witem=6657

http://wayback.archive.org/web/20080330035929/http://thottbot.com/s8215

http://wayback.archive.org/web/20071116063537/http://thottbot.com/i6657

https://www.youtube.com/watch?v=t2AhJvTqjHg - Video of a mage using Rapid Cast vs Ragnaros in may of 2005.

https://www.graffe.com/forums/showthread.php?32998-Mage-DPS-Fishing-and-Cooking - Discussion among casters in a guild in 2005, also confirming it was removed in 1.6 (13th of july 2005)

Spell IDs:

http://db.vanillagaming.org/?spell=8215 Rapid Cast

http://db.vanillagaming.org/?spell=8223 Oops

http://db.vanillagaming.org/?spell=8224 Cowardice

http://db.vanillagaming.org/?spell=8225 Run Away (Cowardice Fear)

http://db.vanillagaming.org/?spell=8226 Fake Death

**Comment by GuybrushGit** [comment]
Implemented here: https://github.com/GuybrushGit/server/commit/b2b21fe165b38a54c2daa61a3b54dbd29dcc1be0

But need opinions on what to do about the Rapid Cast, keep the blizzlike 50% making a level 20 food the best consumable in the game? Nerf it down to 10%?

**Comment by Attero** [comment]
Looking at the [current dps](http://realmplayers.com/RaidStats/Ranking.aspx?Bosses=00010203040506070809&realm=Ely) on Elysium, top melees are doing about 150% of top casters damage.

The hard cap for damage benefit of Haste on Shadowbolt/Frostbolt is 66% haste, or 1.5second casts. Anything above that only gives mobility. Add to that absolutely absurd manaproblems, and the required countermeasures and you will have casters and melee on about equal footing in PvE. 

Playing as a caster on vanillaservers you have been forced to for years accept that you will NEVER beat a good melee. This is a Blizzlike fix that changes that and equalizes the upper limit for dps across roles.

The effect on content difficulty, and PvP, is trivial. The drawbacks are simply too severe. On average you will turn into an ooze once and you will get feared once per successful Rapid Cast, but it will take stacks of Deviates (Which will presumably skyrocket in price), and you will doubtlessly sit through TONS of fears praying to god you dont pull something.

Keep the 100%.

**Comment by thepparker** [comment]
I think the point of it is to be broken, hence the removal at a later stage :D

**Comment by Aklol** [comment]
You could say the same thing about a lot of things that are currently enabled on the server. This change will keep casters on the same level as melee until 1.6.

**Comment by Cwis3man** [comment]
Pretty sure the deviate change came after 1.6 as a hotfix. We were using deviates to fear ourselves through Vaels bugged gate the first few weeks of BWL until the gate was fixed.
