### ISSUE TITLE
Mind control channel buggy

### ISSUE THREAD

**Issue by Silverlash** [elysium-project/server#347]
Ulike other spell , the channel breaks ,the channel bar breaks too ( channel bar disappeare).

in pvp term, the mind control channel bar doesn't gone, once it's been intercepted by kick, cc, stun, and etc. the channel bar and the visual channel action keeps progressing until the spell is completed. ( actually it's not)

which is annoyed, usually I stand idly for 2 sec, because the spell is visually successful spelled, but actually has been intercepted.

Plus MC interception also cause casting stuck problem, need esc twice or once before casting another spell.

**Comment by anubizkai** [comment]
Correct behavior should be:
the channel breaks ,the channel bar breaks too ( channel bar disappears) The next spell should be able to cast instantly without cast stuck , once Mc has been intercepted
