### ISSUE TITLE
Wrath of Ragnaros spell should be resistable, but is not.

### ISSUE THREAD

**Issue by Maxvla** [elysium-project/server#348]
BUGGED BEHAVIOR
Ragnaros is supposed to Knockback Tanks when they don't resist Wrath of Ragnaros. But when you have 250+ fire resistance it is unlikely that he knockbacks the tank. In vanilla a common tactic was to have 2 fire resistance tanks standing next to Ragnaros tanking him. When one of the tanks was knocked back the other one took over and tanked him. The chance that both got knocked backed was extremely low, but it could happen. (Depending on the fire resistance)

CORRECT BEHAVIOR
Tanks/Meeles will resist Wrath of Ragnaros depending on fire resistance value.

SOURCES
http://wowwiki.wikia.com/wiki/Ragnaros_(tactics) quote: "Melee DPS should back out of melee range and only resume attacks once they are sure the MT or OT has aggro. Most melee deaths occur by melees engaging too fast -- after the MT fails a resist and gets knocked back but before the OT engages."

Proof posted in 2006 (pre-BC) - https://www.youtube.com/watch?v=zrzTPbbEPu4

The video linked shows 2 tanks resisting 10 of 11 Wrath of Ragnaros casts. Logs from my guild for 4 Rag kills show 24 Wrath of Ragnaros casts on our 2 fire resistance capped tanks with 0 resists.

This bug leads to excessive Magma Blast casts instantly killing raid members.

Originally posted on bug tracker: https://elysium-project.org/bugtracker/issue/3736

**Comment by Slicy** [comment]
I believe Wrath of Ragnaros was made resistable in 1.5 (but don't quote me on that, need to dig the sources). The intent is to keep pre-nerf raiding encounters here if I understood correctly.

**Comment by PlaskED** [comment]
He's pre nerf. Your sources are not.

**Comment by Maxvla** [comment]
When was this nerf? Please cite your source.

Please look at these videos and comments -

The world first video (April 25 2005) shows his melee hit box is massive and doesn't seem to use Wrath of Ragnaros at all since the melee attack the entire time. If Wrath of Ragnaros was being cast and wasn't resistable melee would be dying constantly between tank swaps. It could be they are out-ranging Wrath of Ragnaros. - https://www.youtube.com/watch?v=Br1hXGXJ7Tg

A video from June 7 2005 shows main tank tanking Ragnaros the entire fight, he is never knocked back. There is no add-on tracking the knockback, but it does exist because at the very beginning they talk in voice comms about someone resisted knockback. - https://www.youtube.com/watch?v=6G1pR2MDvyM

A video from July 22 2005 shows main tank resisting multiple Wrath of Ragnaros casts. The off tank (to the right of the main tank) does not resist the first few. They even discuss it in voice comms 'yes another resist'. Both tanks are close to the boss, instead of at max melee range like the first videos. - https://www.youtube.com/watch?v=VhTUrErPQeA

After seeing multiple very early kills I've noticed Blizzard had Ragnaros' melee hit box very large, large enough that I think you could avoid Wrath of Ragnaros entirely, just by being max range. At some point Blizzard changed the hit box, but not soon. This makes it difficult to find early kills showing knockbacks, resisted or not. I have found evidence showing Wrath of Ragnaros was resistable as early as June 7th 2005, just 43 days after the world first ragnaros kill. I have not found any evidence supporting Wrath of Ragnaros not being resistable.

**Comment by Maxvla** [comment]
I think I have found what is being misunderstood. 

In patch 1.5 it states this:

"The eruptions from the lava in Ragnaros's Lair will now always happen while Ragnaros is in combat. However, these lava eruptions occur less frequently, do less damage, and the damage they inflict is now resistible."

This is in reference to the ability Lava Splash, not Wrath of Ragnaros. Note it specifically mentions lava, and is a randomly occurring environmental effect. Wrath of Ragnaros is a spell Ragnaros casts himself.

**Comment by Aklol** [comment]
you do have a chance to resist it on this server:

https://clips.twitch.tv/EnjoyableSecretiveDogRickroll

however, it's not very often.

**Comment by Maxvla** [comment]
Perhaps the spell isn't checking against fire resist, and just using general resist? There should be a very low chance of not resisting it, not the other way around, if you have 315 fire resist equipped.

**Comment by Comfarol** [comment]
I'm a tank healer for our guild on Elysium and our tanks have something like 280 fire resist and we've been killing rag for 2 months, I don't think they have resisted the knock back once. This definitely needs to be looked at.

**Comment by bilboswagens** [comment]
I'm tanking on Anathema, with buffs, Fire Resistance Totem (which is bugged, only giving +33 instead of +60 as indicated by the tool tip), gear, etc... all of our tanks are 315+ on FR. We've been tanking him every week for about two months and between all of the encounters over those months, I've only resisted **ONE** knockback, and none of the other tanks have. I'm half convinced it was a "bug" and he didn't cast Wrath of Ragnaros that timer (didn't check the log.) Other than that, every time Big Wigs says there will be a knockback, we're knocked back, no matter how much FR we stack.

**Comment by Maxvla** [comment]
@bilboswagens

The issue seems to be fixed. It was elemental resistance for binary spells with knockbacks that were not set up correctly.

Also I doubt your totem is truly bugged. The resistance gained from sources like mark of the wild do not stack, so this is probably what you are seeing.

**Comment by bilboswagens** [comment]
Alright, skipping over the totem part -- we're still not getting resists on the knock up. @Maxvla

**Comment by Comfarol** [comment]
Is this issue resolved now? Our tanks still getting knocked back. Going to MC tonight so will know for sure if it's working.

**Comment by bilboswagens** [comment]
@Comfarol we're still being knocked back on a weekly basis. I sometimes get up to 364 FR and still never resist a knock back. 

In fights like Firemaw in BWL, the FR I wear, anything above 315 is enough to frequently resist the stacking Debuff  Flame Buffet, and actually have stacks stimply fall off while I'm tanking him. It makes the fight much more manageable with enough FR gear. 

The same cannot be said for Rag still. =/

**Comment by Comfarol** [comment]
Hey buddy, Last weeks MC clear on Elysium our tank only got knocked back once and resisted all the others, so i'd say its working.

**Comment by Maxvla** [comment]
This does seem fixed after 2 kills with only 1 non-resist on tanks. Thank you devs.
