### ISSUE TITLE
Priest talent 'Inner Focus' not working correctly?

### ISSUE THREAD

**Issue by Fr4nsson** [elysium-project/server#35]
After killing 100 mobs with and without buff it seems like its not doing anything with the +25% chance to crit to shadow school, the mana reduction part works tho.

**Comment by Rezlind** [comment]
I tested this matter on a server and didn't note a significant increase in percent change for critical hit when using this talent skill. Need to investigate further.

**Comment by shnibble** [comment]
I've noticed this as well, although I haven't done any formal testing. I grinded for 3 levels over the course of a few days a few weeks back and never noticed any significant increase in crits that whole time.

**Comment by brotalnia** [comment]
I did some testing and Inner Focus is working properly. Here's what i did.

I set my spell critical chance to 75%, then made a macro with this:
.cooldown
/cast Inner Focus
/cast Lesser Heal

Without the macro, i need to cast Lesser Heal about 3-4 times before it doesn't crit. When using Inner Focus the spell crits every single time, so it does indeed increase my critical chance by 25% up to a total of 100% from 75%. I spammed the macro with Inner Focus for 5 minutes straight, and there was not a single time that it did not crit. You can also verify that the SPELLMOD_CRITICAL_CHANCE effect is being applied, by making a new entry in spell_effect_mod and increasing EffectBasePoints to 100 for EffectIndex 1 which will guarantee that you crit every time when using Inner Focus.

**Comment by Fr4nsson** [comment]
Brotalnia, yes it works with holy, but its not applied to shadow school it seems, i failed to specify in my topic.

**Comment by FractalCabush** [comment]
I have never had any extra crit chance for shadow school spells, do i check the db for flags on this ability or the code?

**Comment by GuybrushGit** [comment]
Tested with breakpoints. The crit is added to shadow spells.
