### ISSUE TITLE
In Dreams quest event requiring GM reset

### ISSUE THREAD

**Issue by shmigy429** [elysium-project/server#358]
Tried and failed completing this quest many times now, [In Dreams](http://db.vanillagaming.org/?quest=5944); it can be completed successfully but, if someone fails the quest [Highlord Taelan Fordring](http://db.vanillagaming.org/?npc=1842) can become un-interactable at 1 hp outside the tower where [Isillien ](http://db.vanillagaming.org/?npc=1840) 'Kills' him and will stop respawning requiring GM intervention. 

It looks like GM's can force respawn him and the event/escort will become available until someone else fails the quest.

**Comment by CrshOverride** [comment]
Starting today (5/2), Taelen no longer even makes it to the tower. Upon reaching the gates of Hearthglen, he bugs out and gets stuck in place.

![screenshot 2017-05-02 15 21 01](https://cloud.githubusercontent.com/assets/791698/25644708/293d687a-2f76-11e7-9e97-1a15e4f6bb34.png)

**Comment by thepparker** [comment]
Please make a new issue if there are still problems with the In Dreams event
