### ISSUE TITLE
Darrowshire - Alterac Valley - issues with horde NPCS - archers in Frostwolf Towers

### ISSUE THREAD

**Issue by Ripper007** [elysium-project/server#361]
There is an issue with the horde archers in Frostwolf towers. They despawn as soon as Frostwolf graveyard is conquered by alliance.  Even if the Frostwolf Graveyard is recapped, the archers do not respawn. 
 https://postimg.org/image/romd4s31j/ - the screen cap is right after the capturing of graveyard - the towers were capped by alliance rogues.

**Comment by Ripper007** [comment]
Frostwolf Bowman ( id13359)

**Comment by Kittnz** [comment]
They should not respawn after a recap. I think this is blizzlike.

**Comment by Ripper007** [comment]
I think you misunderstood, the bowmans are linked to the Frostwolf Graveyard and that is not blizzlike. I was talking about the recapping of the graveyard. They should respawn every 2 min if killed as long as the tower isn't destroyed.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
