### ISSUE TITLE
Twilight Avenger is not using its spells appropriately

### ISSUE THREAD

**Issue by Mango-Ray** [elysium-project/server#385]
Creature ID 11880 (Twilight Avenger)
Spell ID 8599 (Enrage)
Spell ID 8602 (Vengeance)
________________________________________
Current Behavior:  Enrage is not used. Vengeance is used on initial aggro and maintained until death.

Correct Behavior: Enrage is used when health falls below 50%. Vengeance is used when any Twilight npc, excluding twilight avengers, dies nearby the NPC while in combat with a player.

Sources: use of Enrage when brought below 50%, as well as vengeance not being spammed.
https://youtu.be/9AVaUlnm5Ps?t=17s  (Nov,17,2006)
https://youtu.be/jztrwYvTK70?t=1m  (Oct,1,2006)

I have no reliable source for how/when Vengeance is actually used, though the concept of "Avenger" and "Vengeance" makes it pretty clear that it should work as mentioned above. Looking forward to these getting fixed as they are incredibly powerful and have high movement speed from the Vengeance buff.

**Comment by sipertruk** [comment]
In this video they don't cast Vengeance when the Twilight Prophet dies.
https://www.youtube.com/watch?v=nO6b852IJWc&t=1m
