### ISSUE TITLE
Lay on Hands: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#395]
BUGGED BEHAVIOR
Heals the target to full health regardless of healing reduce debuff on the target or not.

 CORRECT BEHAVIOR
When the target of lay on hands has Mortal Strike debuff -50% healing taken, Lay on hands should heal for half the healing amount (the paladins maximum health -50%)

All heals are affected by Healing reduce debuffs, none are unnaffected.

 SOURCES
http://wowwiki.wikia.com/wiki/Lay_on_Hands

It was never changed in WoW, it has always been affected by Mortal Strike and Wound Poison and such abilities.

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/3698

**Comment by sknnbones** [comment]
Does troll priest racial spell work? It seemsto apply 20% healing debuff to monsters correctly.

**Comment by taurenrogue** [comment]
LOH also heals targets to max hp instead of paladins max HP...
Example: LOH on a city boss = boss full hp instead of getting healed for 4-5k hp that the paladin has as max...

**Comment by brotalnia** [comment]
@taurenrogue That's not true, i just tested it. The amount healed is equal to the paladin's health, not that of the target.

![loh heal](https://cloud.githubusercontent.com/assets/6519171/25169151/a90c3fd2-24ee-11e7-9cfe-765acd6f1cf2.jpg)

You can even see in the code that it takes the caster's health.
https://github.com/elysium-project/server/blob/development/src/game/Spells/SpellEffects.cpp#L3947
