### ISSUE TITLE
Major reputation bug

### ISSUE THREAD

**Issue by Polims** [elysium-project/server#396]
If you get Alliance rep increase you actually dont get any rep at all. You can check on couldron questline and Alas, Andorhal in WPL. I was playing Ally, but worth checking out Horde too.

How it should work:
You should get rep increase with all your factions

**Comment by Solipsismic** [comment]
yeah I wanted to get the Ivory Raptor as Undead but I wasn't able to get rep while leveling so RIP dreams

**Comment by martinjlowm** [comment]
Either way, you cannot get exalted with Darkspear Trolls prior to 1.4. Only Orgrimmar and Thunder Bluff is possible.

**Comment by lequintal69** [comment]
https://github.com/elysium-project/server/issues/291

please, check bug tracker first before posting duplicates..

**Comment by m-laniakea** [comment]
Duplicate.
