### ISSUE TITLE
[Quest] The Stones That Bind Us - stones take 15min to respawn

### ISSUE THREAD

**Issue by Cyb3rl1nk** [elysium-project/server#397]
Server: Darrowshire

The stones that need to be destroyed in order to kill the Servants take 15mins to respawn, where as the Servants themselves take only a few minutes. The stones respawn rate need to be closer in line with that of the Servants.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
