### ISSUE TITLE
Excuse me, master branch don't compile in Debian 9 64 Bits

### ISSUE THREAD

**Issue by Locario** [elysium-project/server#40]
Hi, i have this errors, i don't know how can solve it, need some help please:

`[ 14%] Building CXX object src/realmd/CMakeFiles/realmd.dir/AuthSocket.cpp.o
In file included from /root/server/src/realmd/AuthSocket.cpp:25:0:
/root/server/src/shared/Auth/Hmac.h:43:18: error: field ‘m_ctx’ has incomplete type ‘HMAC_CTX {aka hmac_ctx_st}’
         HMAC_CTX m_ctx;
                  ^~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /usr/include/openssl/hmac.h:15,
                 from /root/server/src/shared/Auth/Hmac.h:23,
                 from /root/server/src/realmd/AuthSocket.cpp:25:
/usr/include/openssl/ossl_typ.h:102:16: note: forward declaration of ‘HMAC_CTX {aka struct hmac_ctx_st}’
 typedef struct hmac_ctx_st HMAC_CTX;
                ^~~~~~~~~~~
src/realmd/CMakeFiles/realmd.dir/build.make:62: fallo en las instrucciones para el objetivo 'src/realmd/CMakeFiles/realmd.dir/AuthSocket.cpp.o'
make[2]: *** [src/realmd/CMakeFiles/realmd.dir/AuthSocket.cpp.o] Error 1
CMakeFiles/Makefile2:504: fallo en las instrucciones para el objetivo 'src/realmd/CMakeFiles/realmd.dir/all'
make[1]: *** [src/realmd/CMakeFiles/realmd.dir/all] Error 2
Makefile:127: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
root@debian:~/server/src# `

Thanks all

**Comment by iNDRLM** [comment]
whats your openssl version?

**Comment by Locario** [comment]
Thanks for response.

I have libssl1.1 and libssl1.0.2

**Comment by iNDRLM** [comment]
try downgrading, I had compile issues with 1.1+ openssl branches but reverted to an older 1.0.1t and it compiled no probs

**Comment by r00ty-tc** [comment]
All the current emu cores (to my knowledge) require OpenSSL1.0 and NOT 1.1. There's some older crypto functions used by the login process, that were removed in 1.1.

**Comment by Locario** [comment]
I will switch to Debian 8, Another guy have forked repo and compiles fine in Debian 8
