### ISSUE TITLE
More skeletons missing immunitites: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#407]
The following skeleton type mobs are missing the correct immune mask: 

MechanicImmuneMask = 213521

List:

- Commander Felstrom id: 771
- Rattlecage Soldier id: 1520
- Darkeye Bonecaster id: 1522
- Ravenclaw Champion id: 1869
- Hand of Ravenclaw id: 1870
- Eliza's Guard id: 1871
- Ravenclaw Guardian id: 1973
- Ravenclaw Regent id: 2283
- Puppet of Helcular id: 2946
- Splinterbone centurion id: 7346
- Dark Caster id: 8526
- Risen guard id: 10489
- Lord Darkscythe id: 10826
- Cauldron Lord Malvinious id: 11077
- Conquered Soul of the Blightcaller id: 12208
- Cauldron Lord Razarch id: 11076 (updated)

**Comment by shmigy429** [comment]
> Cauldron Lord Razarch id: 13197

I'm seeing him as 11076, PR should be up soon.

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/47461-development-update-24052017/
