### ISSUE TITLE
Fix for Thunderfury PPM

### ISSUE THREAD

**Issue by PlaskED** [elysium-project/server#41]
Proposed fix for (bug https://elysium-project.org/bugtracker/issue/3649)
https://forum.elysium-project.org/topic/41454-buff-thunderfury-the-not-so-legendary-weapon/

`UPDATE item_template SET spellppmRate_1 = 7.8945 WHERE entry = 19019;`

Considering there is nothing in itemization patches that alters PPM of Thunderfury it could be applied with a migration instead of adding it to itemization patches. Depends on if Elysium wants to alter it between patches or not. Current PPM of Thunderfury is 5.24 which is stock mangos (Source: Elysium world database, item_template). 

I'll hold with making a pull request for now.

**Comment by henkethebenke** [comment]
+1

I like the argument about the PvP weapons.

**Comment by PlaskED** [comment]
This has been fixed. Issue closed here and on bugtracker.

**Comment by PlaskED** [comment]
Broken again. Procrate is back to stock mangos.

**Comment by m-laniakea** [comment]
Belongs in itemization. Thunderfury changed throughout the timeline.

**Comment by PlaskED** [comment]
It does but you need to make a decision of how it should be itemized. Unless you want Thunderfury wielders to do it (which I'd gladly would)
