### ISSUE TITLE
Multiple Weapons' Drain Life Chance on Hit procs are scaling at only 43% of spell damage when they should scale at 100%: CONFIRMED

### ISSUE THREAD

**Issue by theloras** [elysium-project/server#426]
_**BUGGED BEHAVIOR**_
https://cdn.discordapp.com/attachments/253215035613118467/268588507734343680/drain_life.jpg

_**CORRECT BEHAVIOR**_
Xolkar 20/0/31 Paladin PvP - https://youtu.be/Pk_kHHI0t4o?t=95 - Uploaded on Aug 13, 2006 - Xolkar is using Neretzek, The Blood Drinker which has a Chance on hit: Steals 141 to 164 life from target enemy. You see it proc for 571 Life Drain when he pops his ZHC trinket.

https://cdn.discordapp.com/attachments/253215035613118467/260318343112818689/Neretzek_The_Blood_Drinker.jpg

**_SOURCES_**
Ancient Hakkari Manslayer Binds when picked up One-hand Axe 69 - 130 Damage Speed 2.00 (49.8 damage per second) Durability 105 / 105 Requires Level 60 Chance on hit: Steals 48 to 55 life from target enemy.

By thantik on 09/14/2006 (Patch 1.12.0) The chance on hit for this axe IS affected by dmg/healing, in turn actually giving you a 200% bonus from it, as the dmg portion is directly affected as well as the heal. (i.e. if you have 400dmg/heal this axe will proc for 448-454dmg, and heal you for that much as well.)

Other items which have a similar proc to them are also affected in this manner.

http://db.vanillagaming.org/?item=19852#wh-comments

Skullflame Shield Binds when equipped Off Hand Shield 2256 Armor 40 Block +10 Fire Resistance +10 Shadow Resistance Durability 120 / 120 Requires Level 54 Equip: When struck in combat has a 3% chance of stealing 35 life from target enemy. Equip: When struck in combat has a 1% chance of dealing 75 to 126 Fire damage to all targets around you.

By Kataya on 12/20/2009 (Patch 3.1.3) Scales with spell power, just tested this out on my 80 ret paladin with 1600 spell power, the drain life procced for 1586 shadow damage, healing me for that amount, not sure if this would be more useful than a 245+ shield I have from raiding for soloing low dungeons.

By Algrumm on 07/26/2010 (Patch 3.1.3) Picked this up on my shaman for fun to try out the proc: The fire proc doesn't scale with SP, the lifesteal one does. Lifesteal scales 100% with spellpower.

http://db.vanillagaming.org/?item=1168#wh-comments

Demon Forged Breastplate Binds when equipped Chest Plate 597 Armor +12 Stamina Durability 135 / 135 Requires Level 52 Equip: When struck has a 3% chance of stealing 0 life from the attacker over 4 sec.

By Tristantio on 03/22/2007 (Patch 2.0.10) Currently it is affected by +spell damage (patch 2.0.1) in the same way any drain life spell is (the bonus +spell damage is halved between the +damage and the health restore components).

My paladin with 300 spell damage ends up draining around 270 life from a target when this procs. Amazing chest piece for AoE grinding as a paladin. http://db.vanillagaming.org/?item=12628#wh-comments

Wraith Scythe Binds when picked up Main Hand Axe 57 - 106 Damage Speed 2.20 (37.0 damage per second) Durability 90 / 90 Requires Level 51 Chance on hit: Steals 45 life from target enemy.

By manden on 12/05/2006 (Patch 2.0.1) This weapon does, just like the Ancient Hakari Manslayer, scale 100% with +dmg/heal. Meaning a shaman or paladin could get a very nice damage output, by gathering some spelldamage.

http://db.vanillagaming.org/?item=11920#wh-comments

Fist of the Damned Binds when picked up One-hand Mace 42 - 80 Damage Speed 1.90 (32.1 damage per second) Durability 75 / 75 Requires Level 49 Chance on hit: Steals 30 life from target enemy.

By licker on 12/11/2007 (Patch 2.3.0) With 270 spell dmg on my twink, and this offhand, it procs for about 300 on average. With Zerker and buffs, ive hit 400 lifesteals. Best Twink offhand for a shammy period. With new PTR changes, having a quick offhand with Flametongue will grant a MS type debuff, thus still sustaining the best offhanfd DW Shammy wep.

http://db.vanillagaming.org/?item=10804#wh-comments

Shadowstrike Binds when picked up Two-hand Polearm 147 - 221 Damage Speed 3.10 (59.4 damage per second) Durability 120 / 120 Requires Level 58 Chance on hit: Steals 100 to 181 life from target enemy. Use: Transforms Shadowstrike into Thunderstrike. (cooldown 1 min)

By darkwarrior42 on 06/12/2009 (Patch 3.1.3) Ok, useful as a serious weapon? not so much.

But is anyone else wondering why spell power affects the proc? When I use it on my holy pally, the proc hits for about 1700 (and I heal for the same amount, before divinity).

http://db.vanillagaming.org/?item=17074#wh-comments

Neretzek, The Blood Drinker Binds when picked up Two-hand Axe 202 - 303 Damage Speed 3.70 (68.2 damage per second) +21 Strength +16 Stamina Durability 120 / 120 Requires Level 60 Chance on hit: Steals 141 to 164 life from target enemy.

By Fox24 on 11/26/2009 (Patch 3.1.3) Confirmed, got it running with a few lower guildies in a moment of boredom, took it as no one else wanted it, i just tested it as a ret pally with 854 SP and it NO LONGER SCALES WITH SPELL POWER /sad panda

http://db.vanillagaming.org/?item=21856#wh-comments

Corrupted Ashbringer Binds when picked up Unique Two-hand Sword 259 - 389 Damage Speed 3.60 (90.0 damage per second) -25 Stamina Durability 120 / 120 Requires Level 60 Equip: Inflicts the will of the Ashbringer upon the wielder. No description: 28414 Equip: Improves your chance to get a critical strike by 2%. Equip: Improves your chance to hit by 1%. Chance on hit: Steals 185 to 216 life from target enemy. "Blade of the Scarlet Highlord"

http://db.vanillagaming.org/?item=22691#wh-comments

Original CONFIRMED post on bug tracker here: https://elysium-project.org/bugtracker/issue/1287

**Comment by Mostprovidedlinks** [comment]
Has this been fixed yet
