### ISSUE TITLE
Onyxia deep breath probability is too high

### ISSUE THREAD

**Issue by schmidm77** [elysium-project/server#430]
**Bugged Behavior**
Currently, the probability of Onyxia choosing to move left, right, or forward (causing a deep breath) is a random number from 0 to 2 (.33 probability of each).

**Correct Behavior**
The probability of moving left or right should be .35 each. The probability of a deep breath should only be .3

**Sources**
The official BradyGames World of Warcraft Dungeon Companion (Jul 11, 2006)

**Comment by GuybrushGit** [comment]
http://i.imgur.com/t0w45Ue.png

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
