### ISSUE TITLE
AQ40: Twin Emperors scripting - Emperor Vek'nilash is immune to Holy school attacks

### ISSUE THREAD

**Issue by theloras** [elysium-project/server#435]
As referenced by @GuybrushGit in https://github.com/elysium-project/server/issues/422

_Vek is currently immune to holy but its not from any spell, its being handled in the script. Should be a quick fix._

**EVIDENCE:**
The Temple of Ahn'Qiraj Boss Guide - Od Studios
Jul 26, 2006

_"Both emperor’s are susceptible to holy damage, so you can also Holy Shock and Smite Vek’nilash."_

http://webcache.googleusercontent.com/search?q=cache:2qZVIXpurDEJ:www.odstudios.com/2006/07/26/temple-ahnqiraj-boss-guide/+&cd=10&hl=en&ct=clnk&gl=ca

- Emperor Vek'nilash: Swings a big sword, immune to all magical damage (except holy).
- Another interesting fact is that while Emperor Vek'nilash is immune to most magic damage, he is not immune to Holy school attacks.
- The holy wand from Blackrock Depths, Wand of Eternal Light, can also do damage to Emperor Vek'nilash.
http://wowwiki.wikia.com/wiki/Twin_Emperors

_Twin Emperors 2-man Priest & Paladin_
https://www.youtube.com/watch?v=Q6OCGHo79UE

**Comment by StadenElysium** [comment]
Fixed for when AQ launches.

**Comment by theloras** [comment]
awesome - thank you so much A++

:)
