### ISSUE TITLE
Spell damage / healing

### ISSUE THREAD

**Issue by taurenrogue** [elysium-project/server#436]
**There is no downranking penalty for spells learned at lvl 19 and below**

So for example a rank 2 healing touch has a cast time of 2 seconds and is learned at level 8. The coefficient should be calculated as follows: (1.5/3.5)x(1-(20-8)x0.0375) = 0.42857 x 0.55 = 0.23571, instead what we have is 0.42857 (without the x 0.55) part ... P.S. this also happens with DAMAGE spells so spells like rank 1 frostbolt do ~40%+ more damage than the expected value depending on SP of the caster.

**ALL ranks of all heals are slightly "overpowered"**

There's something wrong with coefficient calcs, bonus healing math or base healing values of spells in the database, because literally every direct heal I tested does more healing than theorycraft + my own math suggest. First I thought the % healing increase talents (like shaman purification talent for example) are being miscalculated, but after respecing and reloging the issue persisted, and all heals (above level 20) do 50-200 too much healing, this also seems to be happening with some damage spells. The most weirdly broken ones seem to be flamestrike (doing way too much damage) and healing stream totem doing ~4x the expected healing per tick...

Sources to how this should work: http://wowwiki.wikia.com/wiki/Spell_power?oldid=366786 & theorycraft addon

**Comment by taurenrogue** [comment]
forgot to mention testing was done ~20 days ago and this is just a repost to this issue tracker...

**Comment by GuybrushGit** [comment]
Just tested this with multiple spells and the penalty is being properly added.

What could be wrong is the base coefficient of some spells. 
Healing Touch r1 for example is set to 100% before the penalty, 28.75% after.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
