### ISSUE TITLE
Quest: A Hero's Reward not in game (elysium/zeth'kur)

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#438]
http://db.vanillagaming.org/?quest=7486

Added in Patch 1.3

Rings rewarded from this quest aren't in game either

Sources:
http://web.archive.org/web/20050309031436/http://www.worldofwarcraft.com:80/patchnotes/patch-05-07-04.html
http://wowwiki.wikia.com/wiki/Quest:A_Hero%27s_Reward

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/

**Comment by gonor** [comment]
They said it is fixed, but the quest is still not available on ZK.
