### ISSUE TITLE
BlockProtection addon not working

### ISSUE THREAD

**Issue by Sundrix** [elysium-project/server#443]
What's up peoples

I got an addon called BlockProtection (poorly named) which automatically removes Divine Protection buff from Paladin.

This was working perfectly on Anathema up until last night's patch

Were there LUA changes? How can I fix?

Thanks so much for any advice or help

EDIT: Added link to addon: http://s000.tinyupload.com/?file_id=06387466756470844508

**Comment by theloras** [comment]
omg i spit my coffee out when i saw this lololol
