### ISSUE TITLE
PvP Quest Type level limit is wrong.

### ISSUE THREAD

**Issue by Sinn** [elysium-project/server#462]
if (pQuest->GetType() == QUEST_TYPE_PVP && pQuest->GetQuestLevel() && pQuest->GetQuestLevel() < getLevel())

Is being used to limit up to the quest level, when after researching I cannot find any reference for this.
http://wowwiki.wikia.com/wiki/Quest

The patches do not mention ANYTHING like this.
"These quests require players complete them while flagged for PvP and usually in a PvP battleground or zone. These quests can also be a variant of a daily quest which may be tied to a specific battleground or can be very tedious and often are ignored by PvP oriented players."

This seems to require the player to be tagged as pvp for credit, interact with quest game objects, and mobs drop items for this quest. The first step is to remove this sin this is wrong, and there is no data to back up this claim, and if there is please share. 3 hours of searching I did not found ANY claim regarding this.

**Comment by Sinn** [comment]
On WoWHead comments:
Level a bit if this quest is giving you some trouble. I didn't get to it until I hit level 51 and these high elves were dropping like flies. They're all over the lodge, in front of it, in it, and on both sides. As was stated above go to UC and get the "Lines of Communication" quest. There's one set of documents in the building, one on a hill to the west and then one next to the water. Burn them and slaughter the elves along the way and even help out the poor troll. All the elves have cloth and silver on them to. 

Ignore the PvP marking as well. It's not in my quest log and I didn't run into any other players save ones doing the escort. Patch 2.4.2 Cant find a patch before this changing quest behaviour.

**Comment by thepparker** [comment]
Unfortunately, absence of evidence is not evidence of absence
