### ISSUE TITLE
Swing timer issue

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#463]
Bugged behavior:
If you have a weapon with a lower attack speed than the cast speed of a spell your casting, you will get a free attack between each cast if your in range of the target.

Correct behavior:
When casting a spell with cast time you should not get "free" melee attacks if standing in melee range of the target

Picture of 2.4 attack speed and Frostbolt spam http://i.imgur.com/PgEqUsx.png
Picture of 2.9 attack speed and Frostbolt spam http://i.imgur.com/k4FO01X.png

**Comment by nikolay510** [comment]
There's also slam+autoattack "issue". You could time your slam and get free attack just like in your pics. But it was shadowfixed recently. Maybe its related issues?

**Comment by QAkvastskaft** [comment]
Spells with cast time resetting swing timer
"While Slam is without a doubt a good ability, being spell with casting-time, it resets the swing timer of your weapon, and therefore you would rather use an Instant Ability like Whirlwind, Bloodthirst or Mortal Strike, if you have access to them."
from: http://wowwiki.wikia.com/wiki/Slam?oldid=384287

**Comment by ohganot** [comment]
Some discussion: http://www.mmo-champion.com/threads/906942-Does-casting-stop-auto-attacks

**Comment by Cabro** [comment]
Also it should work for NPCs in the same way!!

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
