### ISSUE TITLE
Tome of Valor issue: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#466]
BUGGED BEHAVIOR
I failed the tome of valor quote so I abandoned it in attempt to reset it and now I can get get it from Duthorian Rall again. I don't even have the option to talk to him :( please help. What do I do to make it reset?

 CORRECT BEHAVIOR
Need to be able to reset it

 SOURCES
I play the game

Comments from QA
Tested: quest=1649, item=6776. Item is removed from bag once quest is "Accepted" but it should remain until the quest is "Rewarded".

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/1673

**Comment by GuybrushGit** [comment]
I dont see the issue, you dont need the tome to retry the quest.
If you fail to keep Daphne alive just abandon the quest and talk to her again.

**Comment by QAkvastskaft** [comment]
I do not know either, it was confirmed by QAVyallas and he has since left the team. I can re-check it at a later date
