### ISSUE TITLE
Several copies of one npc: Pilot Xiggs Fuselighter - Azshara

### ISSUE THREAD

**Issue by Nowhereman23** [elysium-project/server#468]
Several copies of one npc: Pilot Xiggs Fuselighter - Azshara
At location 78.91

Related to quests: 
"Arcane Runes" (turning in quest)
"Return to Tymor" (new quest)

Also: The item "Standard Issue flare Gun" that is used to summon the npc to the helipad (summon an airplane with xiggs that then land,  if I remember), is not working. And probably just summons more and more npc's everytime someone go there and use the flare gun.  I am not sure about if that is why there is many copies though.

**Comment by GuybrushGit** [comment]
@QAkvastskaft this happens because the NPC is set to despawn in 2.5 hours, should it be lowered to something like 5 minutes?

**Comment by QAkvastskaft** [comment]
5 minutes should be plenty of time for people to use the mob.
