### ISSUE TITLE
health points of targets are incorrect (100/100)

### ISSUE THREAD

**Issue by ChazyTheBest** [elysium-project/server#471]
I don't know why but when I connect to this server my target's health points are incorrect, it's displaying 100/100 instead of the actual heal points.

It's not a client problem (neither the LUA addon), I checked in another vanilla server and I can see the actual/real health points.

So why is the elysium core not sending the correct values to the client?

**Comment by Cgbd42** [comment]
Cause it's how it was done back on vanilla.

**Comment by ChazyTheBest** [comment]
Oh, I thought it was a bug.

Anyways, any chance on implementing it here? It doesn't affect anyone who doesn't want it, as the original UI doesn't show anything, and Addons (like LUA) have options to enable/disable the numbers and show only %.

**Comment by Cgbd42** [comment]
You can use mobinfo 2 as addon if you want to see hp. 

I guess it will not be changed server side, cause it's working as intended.

**Comment by ChazyTheBest** [comment]
Yes, I've heard of that addon, and I know it's not accurate. I'd prefer not to.

Yes, it's working as intended, but there are other several changes to things that are neither blizzlike but were implemented, so why not this?
