### ISSUE TITLE
target dummy not blizzlike

### ISSUE THREAD

**Issue by lequintal69** [elysium-project/server#478]
Target Dummy, Advanced Target Dummy and Masterwork Target Dummy (didnt try that one myself)  are at the moment lvl 1. They get killed in 1-3 hits.

correct behaviour:
the 3 dummies should have different stats :

LVL: All target dummies have the following levels (20, 40, 60) starting with the simplest to the most complex  (1.12 comment  http://db.vanillagaming.org/?item=16023#wh-comments)

Health: couldnt find 1.12 stats, but there is a comment from 3.3 patch:
Target Dummy has: 772 HP
Advance Target Dummie has: 2672 HP
Masterwork Target Dummie has : 5228 HP
http://db.vanillagaming.org/?item=16023#wh-comments

Im not sure if their health total changed before cata

**Comment by GuybrushGit** [comment]
You're right that they're currently too weak, but I'm not so sure about those cata numbers.

>So how much hp does theese have? Can they take a punch or are they wasted on a few sec?
>Not sure exactly, but mine lasted long enough just now to take the hits from two 38 tigers while I cast heal on myself.
>https://web.archive.org/web/20061230202637/http://www.thottbot.com:80/?i=10635

I'd say thats more around 300-400 hp, nowhere near 2672.
