### ISSUE TITLE
World Database is empty?

### ISSUE THREAD

**Issue by fatalmatt** [elysium-project/server#48]
Hey there, I was looking to help develop the source code for the server. But I cannot start up the server because the World database that you guys supplied on Github is completely empty? I would understand why characters + realmd would be empty for privacy reasons. But the World Database data is literally needed to run the server. I was wondering if you guys could upload the full world database?

**Comment by PlaskED** [comment]
It was up but got taken down due to DMCA

**Comment by fatalmatt** [comment]
I closed this issue after I was given a link to the full world DB.
Here it is: https://github.com/elysium-project/server/releases
