### ISSUE TITLE
Gnomish Cloaking device not blizzlike

### ISSUE THREAD

**Issue by lequintal69** [elysium-project/server#480]
Bugged state: any cast (spell, aimed shot) removes the invisibilty straight away

Blizzlike way:
You should be able to casts spells and see players while invisible.

Source: Vurtne 3 (first scene, cast pyroblast), Gameking 2 (last scene, mounting up to escape)
https://youtu.be/c4bgggKMvQU?t=1m3s   pyroblast
https://youtu.be/gJjZn5qxlNY?t=20m43s   mount

Both videos from after Mage Talent tree revamp which was 1.11.

To clarify. Gnomish Cloaking Device allows you to start a spellcast without losing invisibility.
When you finish a spellcast,(magical spell, aimed shot, mount),  the invisibility drops.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/

**Comment by WobLight** [comment]
weird, according to patch 1.10 changelog:
`Stealth and Invisibility effects will now be canceled at the beginning of an action (spellcast, ability use etc...), rather than at the completion of the action. `
