### ISSUE TITLE
Un'Goro Slime sample drop rate too low

### ISSUE THREAD

**Issue by binary909** [elysium-project/server#484]
Un'Goro Slime Samples are supposed to drop from "slimes or oozes" in Un'Goro crater. For quest 
http://db.vanillagaming.org/?quest=4294

The comments on wow-head and vanilla-DB show a 100% drop rate for Un'Goro Slime Sample from monsters: 
http://db.vanillagaming.org/?npc=6556#drop
http://db.vanillagaming.org/?npc=6557
http://db.vanillagaming.org/?npc=6559

(There are other ooze monsters in Un'Goro that I don't have the ID for)

None of the aforementioned monsters have a very high drop rate for the item I mentioned, must be 20% or less.

**Comment by m-laniakea** [comment]
Public databases such as these should be used as a guide, not as an accurate source of how our server works. Our QA team has spent a lot of time on getting things right, and the drop rate _not_ being 100%, is one of them.
