### ISSUE TITLE
Voidwalker's sacrfice doesn't work oftentimes since recent patches.

### ISSUE THREAD

**Issue by lelelelelelbugs** [elysium-project/server#487]
the  voidwalker's shield only pops maybe 50% of the  time (rough estimate)
it doesn't have  anything to do with outside circumstances, it's just  the very skill that's bugged. the voidwalker can be standing freely (no cc, full hp and mana) next to me and spamming sacrfice will accomplish nothing

experienced it myself, experienced it on enemies once (i can't believe  that high rank warlock forgot he can pop a shield in a fierce duel...)
it might be connected also the the fact that if owner's cc'd it doesnt pop, but it should and it did before, because sacrfice is a voidwalker's skill unlike for  example, demonic sacrfice, which is a warlock's skill

**Comment by thepparker** [comment]
Can't replicate, I have no issues sacrificing while stunned or having any form of CC on me. Can do it if I manually use the pet action or use a /cast macro
