### ISSUE TITLE
Arcanite Dragongling broken 

### ISSUE THREAD

**Issue by StadenElysium** [elysium-project/server#490]
Apparently damages itself with its own Flame Buffet.

**Comment by Fyllhund** [comment]
xD, i'll fix it.

**Comment by Jonathanfy** [comment]
xD, I'll fix it when I get home.

**Comment by Teadrinker1234** [comment]
It is happening on darrowshire too. Please fix!!!

**Comment by strudelkuchen** [comment]
Still broken.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
