### ISSUE TITLE
Stratholme "Large Mithril Bound Chest" - Can't open it.

### ISSUE THREAD

**Issue by Nicko11** [elysium-project/server#491]
Get failed attempt no matter what i do, this is surely a bug.

153469 is the object ID.

And yes i am a rogue with 300 lockpicking, so i should be able to open it.

Regards,
Nicko.

**Comment by GuybrushGit** [comment]
This chest has a requirement, can only be opened if the Ghoul Ravener next to it is dead.

**Comment by Nicko11** [comment]
Thank you for the quick reply! I'm feeling stupid, literally just skipping that goal each time and then it is the solution to all of it...

Cheers.
