### ISSUE TITLE
Keyring is not storing Blacksmithing Skeleton keys on my Character

### ISSUE THREAD

**Issue by chevas** [elysium-project/server#492]
I've made several Truesilver Skeleton keys, but they do not store in my keyring or bag and I cannot use them (in places like Gordok Inner Door Tribute) or anywhere.

As soon as they are made, they disappear.

This happens on Edgemorn, alliance, anathema server.

**Comment by GuybrushGit** [comment]
What I believe happened here:
OP crafted the keys when he had a full keyring.
The keys got placed in a hidden slot 13, keyring only shows up to 12.
Now every key that he crafts stacks on top of the hidden keys.

You need to clear up space in your keyring and then either ask a GM to delete those keys or craft enough for the hidden stack to reach 20.

**Comment by Vivenmort** [comment]
This exact same problem occured with my guildmaster. Crafted a key with a full keyring and it disappears.

**Comment by chevas** [comment]
I freed up 4 slots, ran the macro and it picked up a key that was hidden (prison cell key—which I need to keep), but none of the truesilver keys I crafted. I have 3 key slots open, I made another set of truesilver keys (it crafts 2 at a time) and they disappeared / never showed up. I still have 3 key slots open.

**Comment by thepparker** [comment]
Have you checked slots beyond 13? try 14, 15, etc.

**Comment by chevas** [comment]
That worked! It was on a deeper slot.

**Comment by thepparker** [comment]
Client only renders so many keyring slocks
