### ISSUE TITLE
Deathknell Trainers

### ISSUE THREAD

**Issue by felikthekid89** [elysium-project/server#499]
The mage trainer, Isabella, is completely gone on the Zeth'Kur server is gone, as are multiple other NPCs in Deathknell.  Also, there is a cluster of NPCs in the inn that makes it near impossible to interact with.  Unable to submit screenshots due to a weird file called tga.

**Comment by StadenElysium** [comment]
We're aware of this issue and aim to have it resolved as soon as possible. Thank you.
