### ISSUE TITLE
Mage talent Magic Absorption is not working

### ISSUE THREAD

**Issue by Brainzy** [elysium-project/server#501]
This part is not working: " and causes all spells you fully resist to restore 5% of your total mana. "

http://imgur.com/a/jnAxQ

Easy to reproduce. It did work before, not sure when it stopped.

**Comment by GuybrushGit** [comment]
Maybe related to https://github.com/elysium-project/server/pull/351/files. I'll look into it.

**Comment by Homtau** [comment]
same issue on me.  it stopped at 4/19/2017 :)

**Comment by m-laniakea** [comment]
Fixed.
