### ISSUE TITLE
Witch Doctor Unbagwa (Zeth'Kur)

### ISSUE THREAD

**Issue by alfredjarry** [elysium-project/server#508]
Witch Doctor Unbagwa in Stranglethorn Vale is currently bugged on Zeth'Kur. He has been bugged this way for at least a day. He is standing in the wrong spot (outside cave) and is not available to click on for someone with Stranglethorn Fever quest. Probably just needs to be respawned. Thank you.

**Comment by QAkvastskaft** [comment]
Get in contact with a GM for help with resolving this issue: 

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you

**Comment by alfredjarry** [comment]
Thanks a lot.
