### ISSUE TITLE
Weapon [Hurricane] Missing its Proc

### ISSUE THREAD

**Issue by omniusaspirer** [elysium-project/server#513]
https://forum.nostalrius.org/viewtopic.php?f=38&t=12943

"Ranged Elemental Damage: Our ranged combat system does not allow a ranged weapon to do a mix of Elemental (Fire, Frost, Arcane, etc.) and Physical damage. Many ranged weapons existed which were listed as doing Elemental damage and did not function properly (the damage was dealt, but was treated as Physical). All of those weapons have been changed to deliver the Elemental damage as a chance on hit effect. Hurricane was previously changed this way in 1.11. The following ranged weapons are also fixed in 1.12: Bow of Searing Arrows, Dwarven Hand Cannon, Heartseeking Crossbow, Dark Iron Rifle, Galgann's Fireblaster, Quillshooter, Shell Launcher Shotgun, Venomstrike, and Verdant Keeper's Aim."

As per this forum thread and 1.12 patch note- Hurricane is missing its proc entirely. It was presumably removed for itemization reasons, but it's an absolute waste to keep it how it is presently and leave all these other ranged weapons mentioned in their fixed 1.12 state. The change to a proc is not increasing the weapons damage, it's simply allowing it to give the same damage it was always supposed to (albeit a bit spikier). The current state of this weapon never existed at any point during retail.

Relevant links:
http://db.vanillagaming.org/?item=2824

And its proc:
http://db.vanillagaming.org/?spell=29501

@GuybrushGit Please be the champion of my heart and let me experience my needler in full glory. <3

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
