### ISSUE TITLE
Arcane Shot Incorrect Spellpower Coefficient (0% Currently)

### ISSUE THREAD

**Issue by omniusaspirer** [elysium-project/server#514]
As per this thread: 

https://forum.nostalrius.org/viewtopic.php?f=6&t=10688&start=10

Arcane shot should be scaling at 42.85% of spellpower. This is well documented, and the AQ set gives spellpower and arcane shot bonuses for this reason. It presently has zero spellpower scaling whatsoever (at ranks up to 7, the furthest I could test)

Mechanically, arcane shot is working as intended as far as I can tell but at some point in the transition between Nostalrius servers and Elysium the spell seems to have lost its spellpower scaling. Mechanically it should be functioning as any other shot when determining hit/crit/etc (which it is), but it seems to have lost its spellpower scaling in the process.

**Comment by lequintal69** [comment]
what about attackpower scalling? been a recurrent question on privateservers, but i couldnt find anything

**Comment by GuybrushGit** [comment]
Doesn't scale with AP:
>Since Patch 2.0.1 Arcane Shot scales with the Hunter's Ranged Attack Power, causing it to become a viable shot in both PvE and PvP situations. 
>http://wowwiki.wikia.com/wiki/Arcane_Shot?oldid=845014

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
