### ISSUE TITLE
Mend Pet Incorrect Spellpower Coefficient (50% currently)

### ISSUE THREAD

**Issue by omniusaspirer** [elysium-project/server#515]
As per this thread:

https://forum.nostalrius.org/viewtopic.php?f=6&t=10688&start=10

Mend Pet should be scaling at 100% of spellpower, and is currently only scaling at 50% in my tests (Rank 6, + 20 spellpower- only 10 healing added (2 per tick). This is reiterated all over the internet, so if you need further verification for whatever reason I'll hunt it down.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
