### ISSUE TITLE
Volley Incorrect Spellpower Coefficient (0% Currently)

### ISSUE THREAD

**Issue by omniusaspirer** [elysium-project/server#516]
As per this thread:

https://forum.nostalrius.org/viewtopic.php?f=6&t=10688&start=10

Volley should be scaling at 33% of spellpower. It's presently scaling at 0%. This is verified in several places online, so if further evidence is required I can find it.

**Comment by GuybrushGit** [comment]
Should be 1/3/6 = 5.55%

**Comment by omniusaspirer** [comment]
Per tick, yes. 33% because AoE divided over the 6 ticks because channeled- 5.55%.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
