### ISSUE TITLE
Quest: "Uncovering Past Secrets" missing

### ISSUE THREAD

**Issue by Grookshank** [elysium-project/server#517]
On the chain starting with: The New Frontier (http://db.vanillagaming.org/?quest=1000) the quest Uncovering Past Secrets (http://db.vanillagaming.org/?quest=6845) is missing. The chain jumps from Umber, Archivist (http://db.vanillagaming.org/?quest=6844) directly to Under the Chitin Was... (http://db.vanillagaming.org/?quest=1185) w/o the above reward quest in between.

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
