### ISSUE TITLE
Amulet of the Darkmoon still rare quality, should be epic

### ISSUE THREAD

**Issue by elboaf** [elysium-project/server#518]
it looks like patch 1.7 is live, but i noticed that my Amulet of the Darkmoon was not upgraded to the epic quality version. can this be corrected by a GM, or is this item expected to be buffed in a later patch ? everything i find online suggests this item was buffed in patch 1.7

￼ Patch 1.6.0 (2005-07-12): Added.
￼ Patch 1.7.0 (2005-09-22): The Amulet of the Darkmoon has had its stats improved and is now Epic (purple).

source:
http://wow.gamepedia.com/Amulet_of_the_Darkmoon

**Comment by Vivenmort** [comment]
Yep. Had this sucker waiting in the bank, and yes, I've cleared my WDB. Just wasn't touched,

**Comment by StadenElysium** [comment]
Fixed.
