### ISSUE TITLE
[Darrowshire] Missing Quest NPC´s at Yojamba Isle for ZG Set Items

### ISSUE THREAD

**Issue by Sakatoro** [elysium-project/server#524]
Following Quest NPC´s are not Ingame on Darrowshire:

Al'tabim the All-Seeing (http://db.vanillagaming.org/?npc=14903)
Maywiki of Zuldazar (http://db.vanillagaming.org/?npc=14904)
Jin'rokh the Breaker (http://db.vanillagaming.org/?npc=14902)
Falthir the Sightless (http://db.vanillagaming.org/?npc=14905)
Without these NPC´s we can not get the ZG Set Items.

For Example, the NPC Falthir the Sightless should give me as a Rogue the Quest http://db.vanillagaming.org/?quest=8063.

I am friendly at Zandalar Tribe and have the Quest Item Primal Hakkari Armsplint (http://db.vanillagaming.org/?item=19717) but it is not possible to qet the quest and quest reward.

**Comment by Sakatoro** [comment]
Still waiting for these NPCs :(

**Comment by maxasker** [comment]
Still waiting for these NPCs :(

**Comment by rich0dify** [comment]
No love for Darrowshire. Even us PvE carebears can't get PvE gear.

**Comment by StadenElysium** [comment]
These NPCs will spawn tomorrow.
