### ISSUE TITLE
[Darrowshire] Rank 14 weapons got nerfed with ZG patch.

### ISSUE THREAD

**Issue by Tehgenesis** [elysium-project/server#526]
After ZG patch was applied on Darrowshire, all rank 14 weapons were nerfed. 
For instance, 1h weapons have 49.7 dps, however, they are supposed to have 59.5 dps. 

This issue occurred on April 26, after ZG had been applied on Darrowshire.

**Comment by StadenElysium** [comment]
Already fixed.
