### ISSUE TITLE
[AQ] Twin Emps teleport threat too high.

### ISSUE THREAD

**Issue by GuybrushGit** [elysium-project/server#529]
After teleporting the twins do a certain amount of threat to the nearest player.
Currently its at 10k: https://github.com/elysium-project/server/blob/development/src/scripts/kalimdor/silithus/temple_of_ahnqiraj/boss_twinemperors.cpp#L329

This video guide says its around 3k:
https://www.youtube.com/watch?v=nHXfSDVX_ZA&feature=youtu.be&t=1m19s

KTM addon estimates 2k:
https://github.com/ericraio/vanilla-wow-addons/blob/8f6feb94325135c090a891e5d81f0f760c4371e8/k/KLHThreatMeter/Code/KTM_Bosses.lua#L468

Forum post claims 3k:
>4) The Warlock opens fire, using high-damage high-aggro spells to overcome the 3000 aggro the Warrior already has.
>http://www.lurkerlounge.com/forums/archive/index.php?thread-3970.html

**Comment by PlaskED** [comment]
Its correct, it definetly was around 2-3k at release so u can Close this
