### ISSUE TITLE
Extractors on Debian

### ISSUE THREAD

**Issue by Cylae** [elysium-project/server#53]
`gcc version 4.9.2 (Debian 4.9.2-10)`

Branch : Giperion

`Scanning dependencies of target mapextractor
[ 21%] Building CXX object contrib/extractor/CMakeFiles/mapextractor.dir/dbcfile.cpp.o
[ 21%] Building CXX object contrib/extractor/CMakeFiles/mapextractor.dir/mpq_libmpq.cpp.o
[ 21%] Building CXX object src/shared/CMakeFiles/shared.dir/Database/SQLStorage.cpp.o
[ 21%] Building CXX object contrib/extractor/CMakeFiles/mapextractor.dir/System.cpp.o
[ 21%] Building CXX object contrib/extractor/CMakeFiles/mapextractor.dir/loadlib/loadlib.cpp.o
[ 21%] Building CXX object contrib/extractor/CMakeFiles/mapextractor.dir/loadlib/adt.cpp.o
[ 21%] Building CXX object contrib/extractor/CMakeFiles/mapextractor.dir/loadlib/wdt.cpp.o
Linking CXX executable mapextractor
../../dep/libmpq/liblibmpq.a(extract.c.o): In function `libmpq__decompress_zlib':
extract.c:(.text+0x106): undefined reference to `inflateInit_'
extract.c:(.text+0x121): undefined reference to `inflate'
extract.c:(.text+0x133): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
contrib/extractor/CMakeFiles/mapextractor.dir/build.make:213: recipe for target 'contrib/extractor/mapextractor' failed
make[2]: *** [contrib/extractor/mapextractor] Error 1
CMakeFiles/Makefile2:476: recipe for target 'contrib/extractor/CMakeFiles/mapextractor.dir/all' failed
make[1]: *** [contrib/extractor/CMakeFiles/mapextractor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX static library libshared.a
[ 21%] Built target shared
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

`

**Comment by Cylae** [comment]
I found this, this is maybe related : http://stackoverflow.com/questions/25233559/how-to-use-cmake-find-package-with-a-local-copy-of-the-package

**Comment by m-laniakea** [comment]
Outdated issue
