### ISSUE TITLE
Mage's talent: Magic Absorption, it doesn't work on me.

### ISSUE THREAD

**Issue by Homtau** [elysium-project/server#533]
i cannot get any mana through resict.
[http://i4.buimg.com/592786/15fd301155c64a4f.jpg](url)

Realm: Elysium

**Comment by GuybrushGit** [comment]
Dupe: https://github.com/elysium-project/server/issues/501

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
