### ISSUE TITLE
Command table empty?

### ISSUE THREAD

**Issue by Locario** [elysium-project/server#54]
Hi there.

I used world small file from sql folder to populate a new db for core, then i apply full world db + migrations, i noticed there is commands as .die and .levelup not working, i'm doing something wrong?

Also i tried to import that table "command" from MaNGOS Zero Core and DB, but still not working, "there is not such command" error.

Can anyone help me please?

**Comment by PlaskED** [comment]
You need to set your account to correct GM level in account and account_access else you cannot use the restricted commands. As you surely can understand, it wouldnt be a good idea to let anyone use these commands.

**Comment by Locario** [comment]
i done "account set gmlevel USER 3 1" same problem.

Repeat, my "command" table it's empty

**Comment by EinBaum** [comment]
You need gmlevel 6.

**Comment by Locario** [comment]
Really tnx @EinBaum !!!!!

**Comment by fatalmatt** [comment]
yeah they have 7 different ranks for players: 
    SEC_PLAYER                       = 0,
    SEC_MODERATOR             = 1,
    SEC_MODERATOR_CONF  = 2,
    SEC_GAMEMASTER           = 3,
    SEC_BASIC_ADMIN           = 4,
    SEC_DEVELOPPER             = 5,
    SEC_ADMINISTRATOR      = 6,
    SEC_CONSOLE                  = 7
