### ISSUE TITLE
[AQ20] Ossirian Crystals

### ISSUE THREAD

**Issue by Seagulls** [elysium-project/server#543]
The crystals on Ossirian do not properly reduce his enrage so he always hits for 300% damage.

**Comment by ryancheung** [comment]
#411

**Comment by djlewt** [comment]
Ran 5/3/2017, Ossirian pulled to first crystal, click crystal, it comes up as usual but does not zap Ossirian, the 300% damage stays up and he gets no debuff so it's not triggering at all.  Tried 3 times and got the same result.
