### ISSUE TITLE
Celestial Orb on Elysium PvP should have its mana regeneration effect

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#545]
On the Allakazam page:

Feb 2nd 2005
By: Braena
"I dunno if this quest was changed or not, but I completed it yesterday (2/1/05) and it had an additional ability "Use: restore 400 - 1200 mana" self only with a 30 minute cool down."

This means that the orb had its mana regen effect by at least Feb 2nd 2005, which was before Patch 1.3. The stats should therefore not change but only have the on-use effect added.

Sources:
http://web.archive.org/web/20050221215754/http://wow.allakhazam.com:80/db/item.html?witem=7515 -
second comment

http://web.archive.org/web/20050507235040/http://www.worldofwarcraft.com:80/patchnotes/patch-05-04-08.html - Patch 1.4: "The Celestial Orb and Robe of the Archmage will no longer trigger the cooldowns of a Mage's mana gems. Mana gems are now on their own unique cooldown category." 
This note shows that its effect existed in at least patch 1.3.

**Comment by sknnbones** [comment]
# additional sources confirming

http://vanilla-wow.wikia.com/wiki/Celestial_Orb

> Patch 1.4.0 (patch date:2005-05-05): No longer triggers the cooldowns of a Mage's mana gems. Mana gems are now on their own unique cooldown category.

**Comment by Brodda** [comment]
Fix please

**Comment by Sabre142** [comment]
It has it now in 1.4 so I'll close this.
