### ISSUE TITLE
[Darrowshire] Ressing as Warlock with Demonic Sacrifice in a BG costs a shard

### ISSUE THREAD

**Issue by nukul4r** [elysium-project/server#546]
I have Demonic Sacrifice up and die in AV. Now I res at a graveyard, and my pet spawns as well (it's the correct pet which I sacrificed before). However, this costs me a Soul Shard (if I sacrificed a pet other than the imp). Once I run out of Soul Shards, I will not get my pet back (unless it's the imp) upon ressing.

Expected: Getting the pet back after dying with DS up should not cost a Soul Shard.

**Comment by Cgbd42** [comment]
http://wowwiki.wikia.com/wiki/Patch_1.5.0 : "Spirit Guides in Battlegrounds will now resurrect your last Imp, Voidwalker, Succubus or Felhunter. If the Doomguard or Infernal were the last active pet or the previous pet was killed before the Warlock, an Imp will be summoned."
