### ISSUE TITLE
[Darrowshire ZG] Head/Legs enchant quest only uses 1 of the 3 materials required for it

### ISSUE THREAD

**Issue by Kolmarwow** [elysium-project/server#547]
Normally you would need a Primal Hakkari token, an Arcanum from Dire Maul and a Voodoo Doll to complete the quest as seen here: http://nostalri.us/zgenchants.php

But at the moment its bugged and only requires you to have the voodoo doll to turn in the quest & get an enchant, making it far too easy to get the enchants at the moment.

**Comment by Seviren** [comment]
I can confirme that I went with 2 Librams 2 dolls and 2 tokens and only the dolls consumed (not that the remains have any real valye tbh).

**Comment by Vivenmort** [comment]
I hope this information helps isolate the issue.

I actually got my enchant about 12 hours before the impromptu reset of ZG after Jin'Do was fixed to actually drop his full and correct loot table.  It consumed all three of my mats correctly. The very next ZG raid after that reset, my guild "discovers" this. So something you changed when you fixed Jin'Do must have gotten messed up.

**Comment by Vivenmort** [comment]
Recently there has been a brute force fix that has been implemented until the issue is fully resolved I presume. You can no longer accept the quests at all. Some people speculated that they simply raised the level requirement to 61.

**Comment by StadenElysium** [comment]
Fixed.
