### ISSUE TITLE
Item: Shadowcraft Boots : CONFIRMED

### ISSUE THREAD

**Issue by Damienrantoanison** [elysium-project/server#548]
Shadowcraft Boots stats are broken instead of (+3agility +9stamina) it should be (+21agility +9stamina).
source : [http://db.vanillagaming.org/?item=16711](url)

**Comment by Phoosy** [comment]
Vanillagaming's DB is not accurate for a patch-by-patch implementation of item properties. However, in this specific instance, you are correct that the item values are not accurate.

Prior to Patch 1.3, Shadowcraft boots were +21INT/9STM. Patch 1.3 buffed them to be 21AGI/9STM, as referenced here in both the data and the comments collected: https://web.archive.org/web/20060216134927/http://wow.allakhazam.com:80/db/item.html?witem=16711
Calling for CONFIRMED tag. =)

**Comment by ssishtar** [comment]
funny thing is that the boots seem to give 42 AP, even with 3 agi.
