### ISSUE TITLE
Blood Elf Reclaimer Wrong heal spell? 

### ISSUE THREAD

**Issue by TNadal** [elysium-project/server#549]
On Darrowshire: the blood elf reclaimers for the quest "Betrayed" ( http://db.vanillagaming.org/?npc=6199 ) are healing to full on a 1.5 second cast, and using a HoT that's ticking for 15-20% of their life.

everything i can find says they should be healing for 400-500, and a hot of ~30hp/3 not 2k and 300+/3

**Comment by Kridx** [comment]
http://wowwiki.wikia.com/wiki/Blood_Elf_Reclaimer the source TNadal forgot to link :')
