### ISSUE TITLE
Can't complete last quest in Battle of Hillsbrad quest chain!

### ISSUE THREAD

**Issue by Mustavus** [elysium-project/server#557]
After completing the quest in Tarren Mill from killing the dwarves down in Dun Garok for the last quest in the Battle of Hillsbrad chain, the NPC who gives the quest is High Executor Darthalia.

As soon as I turned in the quest and the next one came up for a split second and just disappeared. I was able to see for a split second which loot I will get for completing the quest and I saw the pants it drops. Such a good upgrade for me being lvl 28 with rfc pants still. 

Basically, it just disappeared on me and I ran to Undercity any ways just to see if it just messed up for a second... I talk to Varimathras and he has nothing to give me....

So I think.. maybe I just didn't accept the quest in Tarren Mill?

I fly back and check back to High Executor Darthalia, and she has a grey exclamation mark over her head and i cant even interact with her. shes just a NPC that stands there... I am very confused as to whats happening. 

I really would like my XP and those Sacred Burial Trousers. Please help?

https://vanilla-twinhead.twinstar.cz/?quest=550

That's the quest in question. I don't eve have it in my quest log...

**Comment by QAkvastskaft** [comment]
A grey question mark means that you are to low level, try again in a few levels and see if the quest is available then.

**Comment by StadenElysium** [comment]
Requires level 30.
