### ISSUE TITLE
Two Shadow Word Pain on one Target

### ISSUE THREAD

**Issue by killerduki** [elysium-project/server#558]
Originally https://elysium-project.org/bugtracker/issue/2610

 Bugged Behavior

im in maraudon with a 2nd shadow priest and we can add just one shadow word pain on the same target.

Correct Behavior

1 Shadow Word Pain can be put on a mob by each priest EX: 3 Priests in group, up to 3 Shadow Word Pains should be able to stack on a mob.

Evidence
https://www.youtube.com/watch?v=C8MRqz98kyY#t=99

This require Fix , it is gamebreaking , tested with low lvl and high lvl priest shadow word pain , doesn't stack Same thing happen with Holy Fire too (Priest holy spell)

https://www.youtube.com/watch?v=yAmXZPuS7L0
Uploaded on Oct 22, 2006

You can see 40 Priests stacking Shadow word Pains on Onyxia

affecting dearly shadow priest class/spec and is Game Breaking

**Comment by sipertruk** [comment]
I can confirm.
You can put as much as sw:pain of the same rank, but if you use a different rank after, it becomes exclusive and only the last applied one remains.

**Comment by killerduki** [comment]
It is really bad for leveling and dungeon Shadow Priests.

**Comment by QAkvastskaft** [comment]
Confirmed
Also related: https://elysium-project.org/bugtracker/issue/1367

The debuff stacking part of the code should allow for 2 people to put different ranks of a debuff on the same target. They should still be limited to 1 copy of said debuff each, however.

**Comment by sipertruk** [comment]
I've been looking into it and into aura overlapping in general.
Curse of agony is also affected, a different rank removes the curse from another player.
Blessings, for some you can replace high rank with lower one. 
The spell_group table need cleaning, it contains many groups mixing blessings and totems spells (from trinity ?)
Many non dot debuff shouldn't overlap, example hamstring and piercing howl (both 50% slowing), one should replace the other, so we need some code to compare effects.
I'm trying to put this together.

**Comment by killerduki** [comment]
@sipertruk  speaking about debuffs ,you should exclude paladin judgements , it has been confirmed already that they should stack different ranks .

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
