### ISSUE TITLE
Nat Pagle's Broken Reel Cooldown is wrong

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#561]
The Nat Pagle spell hit trinket (http://db.vanillagaming.org/?item=19947) is currently not using the correct cooldown. As it is now it's on a 2 minute cooldown but should be on a 1.25 minute one.

source:
- http://www.wowhead.com/item=19947/nat-pagles-broken-reel#comments:id=4389

**Comment by StadenElysium** [comment]
Appears to have the correct cooldown already but you'll see it being rounded up to 2m on the UI.

I'll leave this open for if you have any further comments.

**Comment by kevmodrome** [comment]
That explains a lot. Thanks for the reply. Should have checked that with a timer I guess. You can close it
