### ISSUE TITLE
Viscidus dies if you kill all the Globs or DPS him down

### ISSUE THREAD

**Issue by Hosq** [elysium-project/server#563]
Viscidus should only die to Shatter
Source1
https://youtu.be/XRRE4EM9yT0?t=292
Can clearly see all Globs dying and viscidus spawning with 1% and only dying when shattered again
Source2
https://youtu.be/SCZWtBTlORg?t=88
Video is from WoD but shows that you cant just DPS him down he only dies once shattered

**Comment by StadenElysium** [comment]
Current behaviour is that he dies after shatter if he's <=5% HP. He can't be killed without the shatter.

We're aware of the issue with all of the globs being killed though

**Comment by StadenElysium** [comment]
Fixed in last core update.
