### ISSUE TITLE
[Bug]: Swiftmend does not heal for the correct amount

### ISSUE THREAD

**Issue by Lorilay2** [elysium-project/server#568]
Since the spell coefficient overhaul, Swiftmend has not been healing for the correct amount on Regrowth. "Heals for an amount equal to 12 seconds of Rejuvenation or 18 seconds of Regrowth." This is 4 ticks and 6 ticks, respectively.

As you can see, Swiftmending Rejuvenation heals for the correct amount (1485; 4 * 371 = 1485): http://imgur.com/ZzUAKdF

However, Swiftmending Regrowth is not healing for the correct amount (1055; 6 * 211 = 1266): http://imgur.com/AmMfkx2

Based on my experience on the Rebirth server, it's likely that Swiftmend is missing one tick of Regrowth (1266-211=1055). Rebirth had a similar bug affecting both Rejuv and Swiftmend.

Reference: https://www.youtube.com/watch?v=d9Go49UMq9U&feature=youtu.be&t=4m29s
4:30 - Rejuv tick for 437, Swiftmend heal for 1746 (there is no swiftmend on Regrowth in this video, but there's nothing in either its tooltip or its usage in my experience on here and on retail to indicate that it should not heal for 6 ticks (18 seconds) of regrowth.

**Comment by GuybrushGit** [comment]
Its not related to the coefficient overhaul its a bug in the code, ill take care of it.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/

**Comment by Lorilay2** [comment]
Confirmed fixed on live.
