### ISSUE TITLE
Darrowshire - Alterac Valley - Some alliance NPCs no longer drop blood if upgraded

### ISSUE THREAD

**Issue by Ripper007** [elysium-project/server#573]
Alliance NPC's in Alterac Valley,  once upgraded no longer drop Stormpike Soldier's Blood (id 17306) , like Seasoned or Champions Sentinels ( id13327 and 13427) and others several npcs ( 13325, 13426, )

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
