### ISSUE TITLE
[AQ40 Anathema] Imperial Qiraji Regalia/Armaments quest not repeatable.

### ISSUE THREAD

**Issue by Imbaslap** [elysium-project/server#574]
**quest=8789
quest=8790
item=21232
item=21237**

**Imperial Qiraji Armaments and Imperial Qiraji Regalia should be repeatable, according to multiple archived sources from 2006.**

(https://web.archive.org/web/20070121083657/http://wow.allakhazam.com/db/quest.html?wquest=8789)

> "Start:	Arygos
> Category:	Ahn'Qiraj
> Attain:	60
> Level:	60
> Repeatable:	Yes"
> 
> "Quest IS repeatable, and anyone who says it isn't obviously has no idea, Draenor EU server... Gwed in guild Shinasu has 2 daggers............. 
> end of story"

> "It is repeatable. 
> Dualwielding the war axe atm"
> 
> "its is repeatable u retard 
> but taking shield + axe would be just plain stupid"
> 
> "I have seen rogues duel wielding the daggers so yes it must be repeatable."

(https://web.archive.org/web/20070209214450/http://wow.allakhazam.com/db/item.html?witem=21237)

> "yes, it's repeatable."

(https://web.archive.org/web/20061201165726/http://wow.allakhazam.com/db/quest.html?wquest=8790)

> "Start:	Merithra of the Dream
> Category:	Ahn'Qiraj
> Attain:	60
> Level:	60
> Repeatable:	Yes"

(https://web.archive.org/web/20060918145902/http://www.thottbot.com/?qu=8789)

> "I saw a rogue on my server, Elune, dual-wielding the daggers. 
> Trevear 
> NE Rogue 
> Elune"
> 
> "pretty sure u can repeat it. Ive seen a rogue with 2 of the daggers"
> 
> "I duel wield the axes. A rogue guildie has duel of the daggers too. It is repeatable just like the guy above me said. They pwn j00"

(https://web.archive.org/web/20070301083803/http://www.thottbot.com/?qu=8790)

> "The quest is repeatable. Can pick up both staves if your guild has that much ore to spare and you have a second regalia."

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
