### ISSUE TITLE
Woodland protector quest text 2: Confirmed

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#576]
The quest completion text for quest woodland protector is wrong.
quest id = 458
Correct text is: 

"I see you found me, young <race>. Melithar is a wise Druid to have sent you."

http://i.imgur.com/Y7jwDvD.png

**Comment by m-laniakea** [comment]
The same `%C` instead of `Druid` issue.

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/47461-development-update-24052017/
