### ISSUE TITLE
Felcloth bag cannot be learned

### ISSUE THREAD

**Issue by Stence** [elysium-project/server#580]
Felcloth bag is a pattern that can be learned by tailors who are above a particular level (somewhere I read 285, but I cannot confirm). This pattern was made available to players in patch 1.9. Instead learning the pattern via an item drop like Core Felcloth bag, the pattern is learned via an interactive world object similar to the way the repair bot is learned by engineers in Blackrock Mountain. The object spawns when you kill Jandice Barov in Scholomance. See: http://i.imgur.com/P8TrXRN.png

However you cannot interact with this object whatsoever even with 300 tailoring. I killed Jandice on March 6th when the server was patched to 1.9. I do not know if it has been fixed since then but I have not seen anyone talk about this particular soulshard bag so I assume it was never fixed.

The object ID is 21341 and the spell ID for learning the recipe is 26089.

Sources: 
http://wowwiki.wikia.com/wiki/Felcloth_Bag
http://db.vanillagaming.org/?item=21341
http://db.vanillagaming.org/?spell=26089
https://elysium-project.org/news/the-winds-of-war-are-blowing?page=5

**Comment by Manaci** [comment]
It has been fixed

**Comment by Stence** [comment]
Thank you
