### ISSUE TITLE
Portal Seeker, missing

### ISSUE THREAD

**Issue by DirtMonster** [elysium-project/server#582]
Been hunting the mob called Portal Seeker for the past 2 days now, right where he should be in the Blasted Lands. All information gathered from other sources tell me the spot I am at is the correct one (Coords being 46,35), and that he should show without any event taking place, or any form of action being taken. A standard mob with a standard respawn, in other words. 

Sent a ticket regarding it, and got the response to post a note about it here.
He's the single source of the Leatherworking pattern Heavy Scorpid Vest, and I want it, badly.

Kind Regards, 
Dirtmonster.

**Comment by Ripper007** [comment]
NPC map is not available. NPC is maybe spawned by a script.  Just saying
