### ISSUE TITLE
Darrowshire - Zandalarian Hero Charm not working properly

### ISSUE THREAD

**Issue by corrtarr** [elysium-project/server#585]
The stacks applied by the Zandalarian Hero Charm should be decreasing with each heal cast but it isn't. It stays at 12 for the complete duration of the buff.

**Comment by GuybrushGit** [comment]
Tried a couple of heals and the stacks dropped, which heals are you using?

**Comment by corrtarr** [comment]
It was a guildmate of mine who recognized the issue. As he is Paladin I have no idea which spells he used. It occurred to us during our BWL raid yesterday evening.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
