### ISSUE TITLE
Quest: "Are we there, Yeti?" Part 2, in Winterspring. Drops is missing.

### ISSUE THREAD

**Issue by Nowhereman23** [elysium-project/server#589]
The first part is working. Getting 10 hides from yetis. 
The second part, asks for 2 "Pristine Yeti Horne", from the mobs "Ice Thistle Patriarch" or "Ice Thistle Matriarch".

I have farmed for one hour, with no drop. I have also abandoned and retake the quest, and it did not work.

**Comment by kevmodrome** [comment]
I'm not surprised you haven't gotten a drop for one hour. It does drop - it's just that the drop chance is very low - the one on db.vanillagaming.org is, as far as I know, not correct. It should be very low. Keep on killing the mobs.

**Comment by Nowhereman23** [comment]
Ok! Thanks for reply. I will keep trying and reply when it finally drops.

**Comment by Nowhereman23** [comment]
I have now farmed for the quest again. After 30 minutes this time, a yeti dropped the first item. Then the second mob after that kill, I got the second drop, and the quest completed. 

The quest is not bugged, and can be closed.  (Yey, and I was a bit to fast to make a report).
