### ISSUE TITLE
Zulian Slicers proc is "often"(stated 3 times) and should be 13% (stated on youtube 2006- will upload). Zulian slicer needs to also be 100% spell damage coefficient and crit x1.9

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#593]
Zulian slicer is still not scaling at 100% spell damage or critting almost double its damage (exactly x 1.9) stated in comments.
Zulian slicer is also not proccing until 50 hits. The proc is mentioned to proc often and should be the least at 10% I have a video showing a warrior autoattacking using deepwound for 50 swings until it procced.

In 2005-2006 Vanilla the proc of Zulian slicer was mentioned to proc "Often"
http://web.archive.org/web/20071111111930/http://thottbot.com:80/i19901 
http://imgur.com/FGy0Boz
http://imgur.com/whi2OcT
They are all still waiting for TBC (TBC is 2.5 months ago on thottbot) http://imgur.com/aWa78UN

Further proof it scales with 100% damage in 2006 vanilla
http://imgur.com/a/kpCgw
http://web.archive.org/web/20070907094925/http://wow.allakhazam.com:80/item.html?witem=19901
feb 13th 2006
just got this on my paladin, and im using 5/8 judgement, it seems to gain 100% bonus from damage/healing because it hits for around 230-250 and crits for 450ish, not bad for a protection paladin (too bad im not >< just took it for skinning purposes)
On average that is 450 divided by 240 = x 1.9 = crit

Also it scales with exactly 100% spell damage
A mage saying he noticed melee swings in 400 spell damage gear gave him 475 damage hit procs (75 minimum caused from Zulian)
http://www.disciplesguild.com/forums/topic/weapon-proc-pwnage/

Weapon enchants like Icy/fiery weapon/lifestealing have procs often in their text. 
Zulian Slicer should proc  "Often" in comparison to other weapons that proc at 25% and 27% like https://elysium-project.org/bugtracker/issue/3649
http://db.vanillagaming.org/?item=19019
https://elysium-project.org/bugtracker/issue/4073
http://db.vanillagaming.org/?item=12798
Annihilator 27% proc
http://db.vanillagaming.org/?item=19170

1. "The proc on it was critting for 750~, and seems to proc quite often."

2. "the proc does crit for 750 regularly even against BC mobs."

3. "but occasionally i would hear it growl/roar with the sound of a tiger"

These need Fixes: 
increase proc rate to 13% (will link this soon) (+vanilla comment says it procs often (2 comments)
Zulian slicer must scale with 100% spell damage
Zulian slicer must spell crit x 1.9

**Comment by killerduki** [comment]
Define "often" is not 15% , it is "assumption" , you need to give correct evidence regarding proc rate , otherwise the scaling was proven according to comments that should scale 100% .

**Comment by Mostprovidedlinks** [comment]
and crit by almost double too

**Comment by Mostprovidedlinks** [comment]
Zulian slicer is still not scaling at 100% spell damage or critting double its damage.
Zulian slicer is also not proccing until 100 hits. The proc is mentioned to proc often and should be the least at 10%

**Comment by Itembugs** [comment]
Thunderfury is proccing at easily 25% and nightfall at 20%. If this item is often. It shouldnt be any lower than 10%
