### ISSUE TITLE
Goblin Sapper charge/ Demonic rune/ Dark rune crits should proc Paladin talent Reckoning and Redoubt

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#604]
http://db.vanillagaming.org/?item=20520
http://db.vanillagaming.org/?item=10646

They are not giving reckoning charges or redoubt when they crit the user
Reckoning and redoubt indicate "after being the victim of a critical strike http://db.vanillagaming.org/?talent#s
runes and sapper charge can crit http://imgur.com/a/meHGZ 

Please Fix thanks Elysium

**Comment by ImperfectCell** [comment]
I agree with him.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
