### ISSUE TITLE
Goblin sapper charge, demonic runes and dark runes should be affected by melee crit chance

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#605]
https://github.com/elysium-project/server/issues/1177
ccshiro/cc-buglist#2581
written by omniusaspire

potions are usable and read this. ccshiro/cc-buglist#2581 I cant see why runes or sapper charge should be any different especially when runes were initially affected by player spell damage gear

They should be affected by melee crit

A 2006 website that shows proof that dark runes and demonic runes affected by the players spell damage, so there is no reason why they arent affected by player crit in the same way. 
http://www.lurkerlounge.com/forums/printthread.php?tid=4252
They scaled with player +spell damage
This already proves they must be affected by player crit chance since they were affected from players spell damage

Runes and sapper charge contain these schools which are known to scale with player crit
(2) School Damage (Fire)  
(2) School Damage (Shadow) 
and they belong to
Storm gauntlets, blazefury medallion, fiery retributer, fiery plate gauntlets are items and their crit are all affected by the players crit. 
They are affected by crit just as 
http://db.vanillagaming.org/?spell=133 fireballs first effect crits is (2) and (6) dot category is not
http://db.vanillagaming.org/?spell=15851 (dragonchilli crits)
http://db.vanillagaming.org/?spell=16614 (the spell from http://db.vanillagaming.org/?item=12632)
as shown here http://imgur.com/a/DSzat

Lastly they all can proc the effect of Thick Obsidian Breastplate http://db.vanillagaming.org/?item=22196
and therefore are spells.

How do you explain Dark rune and demonic rune scaling with player spell damage when duels cant?

Mostprovidedlinks  commented 17 hours ago 

Can duels proc thick obsidian breastplate http://db.vanillagaming.org/?item=22196 like sapper charge and dark rune can? no
 Are duels considered spells that damage you so they can crit? no
 Are duel spells considered a (2) school of magic http://db.vanillagaming.org/?spell=27869 that is affected by players? no
http://db.vanillagaming.org/?spell=7266 (physical and not a magic school)
 
Fix please, just showing they are affected by players is enough proof. I have done this. Therefore they should be affected by both damage and crit

**Comment by thepparker** [comment]
Why should they be affected by spell crit chance? All items have a base crit chance depending on their effects. It's also the damage that crits, not the mana regeneration.

**Comment by Mostprovidedlinks** [comment]
Yet it is categorized as a spell

**Comment by thepparker** [comment]
Every single item in the game is a spell, every effect you have on your player is an aura. It doesn't mean they all mechanically work the same. Items don't scale with a player's crit chance.

**Comment by Mostprovidedlinks** [comment]
Storm gauntlets, blazefury medallion, fiery retributer, fiery plate gauntlets are items and their crit are all affected by the players spell crit. They have the same school of spells exactly the same as these 3 items.

These 3 items should crit according to player spell crit.

**Comment by thepparker** [comment]
That's debatable. Those items are also equippable items, not usable items.

**Comment by GuybrushGit** [comment]
Challenging a player to a duel is a spell, can duels crit?

**Comment by Mostprovidedlinks** [comment]
How do you explain Dark rune and demonic rune scaling with player spell damage?

**Comment by Mostprovidedlinks** [comment]
Can duels proc thick obsidian breastplate? no
Are duels considered spells that damage you so they can crit? no
Are duel spells considered a (2) school of magic that is affected by players? no
http://db.vanillagaming.org/?spell=7266

**Comment by Mostprovidedlinks** [comment]
#1177
ccshiro/cc-buglist#2581
written by omniusaspire


potions are usable and read this. I cant see why runes or sapper charge should be any different.
