### ISSUE TITLE
Dragonbreath Chili not scaling with 100% spell damage

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#606]
Dragonbreath Chili should scale with 100% spell damage 

Right now its only scaling around 8% damage on Elysium.

http://imgur.com/a/n1Auu (thottbot) 500-700 damage (vanilla)
It should easily be scaling at 100%.
Chili says 500-700 damage (say 700 is the crit, and do realize 500 for a level 60 in vanilla means he would of needed a minimum of 439 spell damage) He says its not even the 2.0 patch yet and its scaling which means it scales in 1.12 vanilla or before. He said he hopes it will keep scaling in when the expansion or 2.0 arrives, in addition on that link theres more proc chance and damage proof in the TBC 2 month period)

http://imgur.com/a/ssD35 (This damage comment may be of 2.0 but on thottbot it mentions it scales with spell damage before 2.0) 

350-400 spell damage gives 420 hits and 620 crits
Chili without spell damage hits 61 damage http://db.vanillagaming.org/?spell=15851

Fixes needed: It needs to be scaling at 100%

**Comment by GuybrushGit** [comment]
I seriously doubt that, nothing in vanilla scales over 100%.

**Comment by Mostprovidedlinks** [comment]
Yet the proof is right infront of you.

**Comment by killerduki** [comment]
As @GuybrushGit  nothing in Vanilla can scale higher than 100% , it was TBC expansion that invented higher than 100% .

**Comment by staplerx300** [comment]
I had an issue with the chili only lasting like 1 min tops before the buff disappeared.

**Comment by ImperfectCell** [comment]
Some devs please take a took into this thanks. This has gone unchecked far long enough.

**Comment by Mostprovidedlinks** [comment]
Still not fixed.
