### ISSUE TITLE
Skullflame shield not scaling at 100% spell damage

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#607]
Skullflame shield is stated to scale in vanilla as shown here
(If you follow the timeline 1.4 years ago is in the vanilla period for example - (TBC not out 1.1 years ago http://imgur.com/aWa78UN)
A vanilla player said 400 spell damage gave him 435 damage in total (100%) >> http://imgur.com/a/4tyuv
http://web.archive.org/web/20071109071429/http://thottbot.com:80/i1168

(skullflame shield does 35 damage with 0 spell damage)

also a wowhead comment
By thantik on 02/23/2007 (Patch 2.0.8)
If you have over 800+dmg/heal gear it will DO 875dmg, and HEAL for 875dmg...

Skullflame shield should scale at 100% spell damage

It also seems to be proccing too low. And doesn't feel like 3% since other 2% items proc more than it.

on Elysium its scaling at 43%

Please Fix thanks Elysium

**Comment by GuybrushGit** [comment]
Dupe: https://github.com/elysium-project/server/issues/426

**Comment by ImperfectCell** [comment]
I agree with him.

**Comment by Mostprovidedlinks** [comment]
It also seems to be proccing too low.
