### ISSUE TITLE
Demon forged breastplate life drain not scaling at 50% spell damage

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#608]
1.1 years ago on thottbot (Vanilla wow) it is shown to be scaling with spell damage.
http://imgur.com/a/94HFA
http://web.archive.org/web/20071114190201/http://thottbot.com:80/i12628

(TBC is not out at 1.1 years ago http://imgur.com/aWa78UN)

also we cannot take coefficients from tbc but only proof that it scaled with spell damage
It is unknown exactly how much it scaled in vanilla but it has thesame spell damage life drain as http://db.vanillagaming.org/?item=1168 and http://db.vanillagaming.org/?item=21856. And should scale at 50%

Please Fix thanks Elysium

**Comment by GuybrushGit** [comment]
None of those links say Demon Forged scales at 100%, its a periodic life drain so it should act similar to warlock drain life: 50% divided by number of ticks. Wowhead comment seems to confirm this:

> By Tristantio on 03/22/2007 (Patch 2.0.10)
>Currently it is affected by +spell damage (patch 2.0.1) in the same way any drain life spell is (the bonus +spell damage is halved between the +damage and the health restore components). 
>My paladin with 300 spell damage ends up draining around 270 life from a target when this procs. 

Those weapons you linked should be 100% yes but those are direct life steal, not periodic.
Also dupe: https://github.com/elysium-project/server/issues/426

**Comment by Mostprovidedlinks** [comment]
It doesn't matter. I am reading what the sources say.

**Comment by thepparker** [comment]
What source?

**Comment by Mostprovidedlinks** [comment]
1.1 years ago is in vanilla and someone in vanilla said it is affected by +spell damage

**Comment by ImperfectCell** [comment]
Fix thanks
