### ISSUE TITLE
Mage Talent: Permafrost bugged!

### ISSUE THREAD

**Issue by Kierwynn** [elysium-project/server#611]
BUGGED BEHAVIOR
Increases the duration of your Chill effects by 3 secs- it correct working, but decrease the target speed by 4%/7%/10% for 1/2/3 not working . Frostbolt always, at all levels this talent, reduces movespeed for 40%

CORRECT BEHAVIOR
Frostbolt reduces movespeed for 50% at lvl 3 with this talent 3/3

http://db.vanillagaming.org/?spell=12571

**Comment by Lorilay2** [comment]
Frostbolt does not apply a "chill effect." The only spells that do are Frost Armor and Blizzard (with talents).

**Comment by GuybrushGit** [comment]
Tested in dev. The 10% is being added.

**Comment by Kierwynn** [comment]
Tested in live. It is not being added.
