### ISSUE TITLE
[AQ Prophet Skeram]

### ISSUE THREAD

**Issue by Mofoleone** [elysium-project/server#617]
Let's start with the issues:

**1) **Boss can cast 2 mind controls at the same time on one platform****

True Fulfillment, which Mind Controls a target, and gives them increased damage, higher resistances, faster movement and instant-cast spells. The target also grows to an immense size, so it is easy to see who is being controlled. The effect cannot be dispelled, but targets can be sheeped, feared, stunned, or put to sleep if a Druid is in an animal [form.]
(http://wowwiki.wikia.com/wiki/The_Prophet_Skeram)

**2) **Mind control cannot be avoided on tanks if dps stay in front/closest to the boss****

Rogues: Split your rogues up through this fight to have as few on each platform as possible. The rogues should also stand inside Skeram in front of the tank. The rogues will always be mind controlled before the tank if this is done [correctly.]
The Mind Control affects the person nearest to Skeram, another way to ensure your tank never gets Mind Controlled is to have a weaponless Rogue stand underneath Skeram when he is being tanked
(http://wowwiki.wikia.com/wiki/The_Prophet_Skeram)

**3) **Skeram movement is terrible, even tho there's a tank on him, he will cast earthshocks on random targets if you try to move him****

There's not much to say about this here, you can't really use any tactics aka to move him or his copies from any platform because he will start casting earthshocks every sec, no matter how fast/slow you move.

**4) **Arcane explosion.****
**Being casted even tho there's less than 4 people around the boss.**
**Being casted in the middle of a teleport/blink to other platforms** => NOT BLIZZLIKE
This is gamebreaking, sometimes you can get 3 illusions teleport in mid cast and blow out 3x arcane explosion at the same time dealing way higher damage than it should be.

**Damage of arcane explosion is too high compared to retail vanilla values**
Arcane Explosion (1.5K, large radius). It can be interrupted. He only casts it if there are more than four people in melee range of him. Casting speed can be slowed by Curse of Tongues and Mind-Numbing Poison.
[http://wowwiki.wikia.com/wiki/The_Prophet_Skeram](url)

**5) **Way too often all 2 illusions and the boss are on the same platform, yeah that can happen but not at this rate....****

This amount of RNG has to be tuned down.

**Comment by killerduki** [comment]
> 4) Arcane explosion.
> Being casted even tho there's less than 4 people around the boss.

http://wowwiki.wikia.com/wiki/The_Prophet_Skeram?oldid=388887
**Revision as of 00:10, December 30, 2006**

As of patch 1.12, aggro rules changed. As such, Arcane Explosion is not guaranteed for 4+ people, and it could happen for less people present as well.

**Comment by Mofoleone** [comment]
Can you please not spam here, since this isn't 1.12 patch.
Thanks

**Comment by birdayz** [comment]
3) You have to taunt him when he teleports, and you are good. Not sure if that is a bug

**Comment by killerduki** [comment]
@Mofoleone  except Itemization and Progression , everything is 1.12 Patch in this server , please read server rules before you claim something.

**Comment by m-laniakea** [comment]
**1)** Not likely, would have to see some evidence. What probably happened, is you had two images on the same platform.

**2)** The MC is intended to be random. The closest being MCed first is a side-effect of  threat system behaviour after a threat wipe.

**3)** Earthshock casts are *not* random. Ask around to find out the exact mechanic.

**4)** Killerduki already explained it. All talents and spells are based on 1.12.1 mechanics.

**5)** Do the math. Assuming they blink at the same time, there's a 77.77...% chance of having at least two on one platform.

**Comment by Mofoleone** [comment]
Can people actually read the tactics that are provided here
http://wowwiki.wikia.com/wiki/The_Prophet_Skeram

and stop with bullshit spam posts?

**Comment by birdayz** [comment]
Actually you are full of BS. You should have evidence, or at least not insult those people who might work on your (non) issue.

**Comment by Mofoleone** [comment]
@birdayz 
I'm an active participant on vanilla projects for past 3 years, I've seen basically everything and know how it should work and how it shouldn't.
You don't need to be super smart to get 90% of mechanics from wowwiki since that data is ancient and everyone with any knowledge will value it more than some silly troll comments from people like Killerduki who is known troll on old feenix forums

**Comment by birdayz** [comment]
If you ever worked on "vanilla projects", you would know that wowwiki is not a credible source.
As @m-laniakea said, talents and spell are 1.12.1 - if you ever worked on a "vanilla project", you would know that the world DB is 1.12 as a baseline and all changes "downwards" are additional work, which is - as @m-laniakea said - is usually not done on elysium.
It is pretty obvious that you are just trying to get a nerf on a boss which works fine.

**Comment by killerduki** [comment]
@Mofoleone  being active on Feenix bugtracker doesn't make your correct , neither it was everything correct on that server.

If you truly want to be "Beneficial" , please use correct bug report with Evidence given from 2006 , that's the only viable source. 

Even if you use Wowwwiki , still make sure links are also from 2006 , despite wowwiki is not always accurate , the 2006 "history" is much more accurate than the actual information given in the latest date.

We all know how German from Feenix edited/modified Wowwiki regarding some bugs to fake it in Feenix abusing as "evidence".

**Comment by m-laniakea** [comment]
Closed due to insufficient evidence.

**Comment by Mofoleone** [comment]
Really try it yourself, script of skeram is on starter programmer level, no offense but it's potato.

You have issues listed but decided to ignore, gj keep up the good work

**Comment by Phoosy** [comment]
Because insulting the development team _and_ offering no credible source _and_ not posting revised code to your point that the code is 'potato' is the best way to win over the hearts and minds of your detractors.

**Comment by Mofoleone** [comment]
It's not insulting, I just wonder what kind of PTR access one can get, because whoever is testing it (outside of the devs) is not doing their job properly, you know it's true but keep living in denial and your perfect bubble.

**Comment by killerduki** [comment]
If you witness any Bug, feel free to report it.
Outside of that, yep whoever testing it can possibly do mistake, but if you feel like it , do an application to join QA team.
