### ISSUE TITLE
[QUEST] A Humble Offering

### ISSUE THREAD

**Issue by Mofoleone** [elysium-project/server#619]
http://wowwiki.wikia.com/wiki/Quest:A_Humble_Offering

Cannot be taken from NPC

http://wow.gamepedia.com/Quest:A_Humble_Offering_(Silithus)
Patch 1.8.0 (2005-10-10): Added.

**Comment by Peter2345** [comment]
Sadly you are telling half the story. But that;s the Internet...

**Comment by Pleasant-Elysium** [comment]
This quest shouldn't be available because it was added in patch 1.11.

**Comment by Peter2345** [comment]
AFAIK, it was added in 1.8. Many databases - Wowhead for example - apparently list 1.11 as that's when they started collecting data.   [Gamepedia](http://wow.gamepedia.com/Quest:A_Humble_Offering_(Silithus)  would say otherwise

**Comment by druidish** [comment]
This quest was added in 1.11. Gamepedia/Wowwiki's "Patch x.x.x (yyyy-mm-dd): Added" stubs are generally off for older content. Best to check the page history on those sites or check allakhazam/thottbot.

**Supporting Evidence**
1.11 Patch Note "Aurel Goldleaf at Cenarion Hold in Silithus has a new quest."
https://web.archive.org/web/20060415130417/http://wow.allakhazam.com:80/db/mob.html?wmob=15282

https://web.archive.org/web/20060208033741/http://wow.allakhazam.com:80/dyn/items/iname11.html

**Comment by Pleasant-Elysium** [comment]
You can thumbs down all you want but the item's code is 22725, added to the game in the same range as Naxx tokens. The Humble Offering is 9248, in the same range as the quest to turn in Naxx Tokens for gear. Neither show up on wayback archive until after Patch 1.11 was released.

Wiki's are not valid sources.

**Comment by m-laniakea** [comment]
Case closed. Thank you, Pleasant and druidish.
