### ISSUE TITLE
Defender of the timbermaw (exalted trinket) NOT WORKING

### ISSUE THREAD

**Issue by lequintal69** [elysium-project/server#62]
defender of the timbermaw http://db.vanillagaming.org/?item=21326#wh-comments is completly bugged right now.

**CURRENT BEHAVIOUR:**

-summoned minion just follows you and almost never attack (90% of the time he does nothing).
-Only twice out of 20 summons, he casted ONE single lightning bolt doing 500dmg during its entire duration, then went back to bugged state
-never heals
-has 427 hp

**CORRECT BEHAVIOR**

-should have around 500hp
-should do around 220-300 damage (dmg seen in videos ranges from 233 to 286). Can crit
-should heal when you are below 50% hp (estimated values from comments and videos).
-heal values is around 500-600 (can crit for 800-900) as seen in the video
-casting time is around 2sec
-will melee if target is immuned to nature dmg
-doesnt break CC (sheep,trap, etc)

nb: healing is top priority, meaning if you (or your pet, or someone else in your group) drop below 50% health, he should start healing until you are above 50%

**SOURCES**

http://db.vanillagaming.org/?item=21326#wh-comments comments
https://youtu.be/42QFS7qJyVo?t=5m35s (dmg, heal, crit heal, casting time)
https://youtu.be/4c4LjRjUMMs?t=22m31s (dmg, heal, casting time)
https://web.archive.org/web/20061231193841/http://www.thottbot.com:80/?i=52390  (many many comments on behaviour, check last one)

**Comment by lequintal69** [comment]
https://web.archive.org/web/20061231193841/http://www.thottbot.com:80/?i=52390

many usueful comments here aswell.
Last one is quite precise
"Average heal: (about 2 sec cast) 513hp 
Average lighting  bolt damage:  (about 2 sec cast)  264  (It seems to do more damage now, post 2.0)  
Average melee damage: 85 (against targets with essentially no armor) "

**Comment by lequintal69** [comment]
@Jonathanfy  I have seen your dragongling and cthun trinket fixes, any chance on fix for this trinket ? Would make a lot of pve and pvp tryhards happy :)

**Comment by Jonathanfy** [comment]
Y, i'll look at it

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
