### ISSUE TITLE
Poison Resistance Elixir should not have a 2 mins CD. 

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#620]
https://github.com/elysium-project/server/commit/c0e48ad6ad119f1ab22c9e550733928bc0203486

This change needs to be reverted. There was a misreading of a video source by QA that leaded to make the item have a 2 min CD shared with Potions while it never had that CD during vanilla.

The item icon of Poison Resistance Elixir is the same as Jungle Remedy, which used to be on the Potion CD while Poison Resistance Elixir wasn't.

Poison Resistance Elixir is on a 3 secs CD in vanilla. The only change/nerf made by Blizzard to the item was at 1.9 and it concerned the effect itself, not the CD.

Sources :

1. Poison Resistance Elixir, June 2006 : http://web.archive.org/web/20060613195722/http://www.thottbot.com:80/?i=13343 

2. Jungle Remedy, December 2007 : http://web.archive.org/web/20071218110449/http://thottbot.com:80/i2633 

3. 1.9 change to Poison Resistance Elixir effect :

_"Nerfed in 1.9.1 today (1/10/2006).

Old:
Elixir of Poison Resistance
Requires Level 14
Use: Target is immune to poison for 1 min and is cured of any existing poisons.

New:
Elixir of Poison Resistance
Requires Level 14
Use: Imbiber is cured of up to four poisons up to level 60"_

**Comment by thepparker** [comment]
Indeed. It is meant to be in the elixir category, so virtually no CD.
