### ISSUE TITLE
Arcane Shot / Serpent Sting not scaling with Spell Dmg

### ISSUE THREAD

**Issue by Mithedhel** [elysium-project/server#622]
Played Vanilla since start,

Arcane shot is not affected by AP and should therefore scale with 41% of Spell Dmg as any other instant spell. Serpent Sting is only scaling properly with Spell Dmg from ranks 1-7. Rank 8 is not scaling at all, and it's actually counting as a MELEE attack. You can see how shooting serpent sting will level up your melee weapon skill in game.

There are plenty of articles and hunter videos showing this as it's an intended possible build good for kiting, fun and Roleplay that brought a lot of color and richness to the game and vanilla experience.

**Comment by GuybrushGit** [comment]
https://github.com/elysium-project/server/pull/523

**Comment by Mithedhel** [comment]
This says that 9 days ago it was fixed but right yesterday I was testing how Serpent Sting Rank 8 was still scaling 0% as opposed to ranks 1 to 7. And Arcane Shot wasn't also scaling, at least in Zeth Kur.

**Comment by brotalnia** [comment]
Cause the fix is not live yet most likely. Test it on the development branch.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
