### ISSUE TITLE
Blacksmith Vargus Quests are not repeatable

### ISSUE THREAD

**Issue by ThunderyEnd** [elysium-project/server#625]
The four quests given by the NPC Blacksmith Vargus in Silithus were repeatable in retail WoW allowing players to grind for more than one of the rewards per quest.
http://wowwiki.wikia.com/wiki/Quest:Volunteer%27s_Battlegear (see Notes section of page)
http://wowwiki.wikia.com/wiki/Quest:Stalwart%27s_Battlegear

**Comment by GuybrushGit** [comment]
Source from vanilla: https://web.archive.org/web/20071029143453/http://thottbot.com:80/q8574
>In case you are wondering, yes you can  do Stalwart's Battlegear repeatedly to collect different gear.
