### ISSUE TITLE
maps error

### ISSUE THREAD

**Issue by blekkulf** [elysium-project/server#628]
I am using the maps I used with mangos-zero. Why are they not compatible with Elysium?

Map file '/home/elysium/run/bin/maps/0004331.map' is non-compatible version (outdated?). Please, create new using ad.exe program.
Correct *.map files not found in path '/home/elysium/run/bin/maps' or *.vmtree/*.vmtile files in '/home/elysium/run/bin/vmaps'. Please place *.map and vmap files in appropriate directories or correct the DataDir value in the mangosd.conf file.

**Comment by GuybrushGit** [comment]
You need to use the Elysium mmaps, other versions will not work.
