### ISSUE TITLE
MMAP:loadMap: Could not open mmtile file

### ISSUE THREAD

**Issue by blekkulf** [elysium-project/server#630]
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001433.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001533.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001633.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001733.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001833.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001933.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002033.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002133.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002233.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002333.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002433.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0006233.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0006333.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000034.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000134.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000234.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000334.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000434.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000534.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000634.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000734.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000834.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0000934.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001034.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001134.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001234.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001334.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001434.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001534.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001634.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001734.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001834.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0001934.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002034.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002134.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002234.mmtile'
MMAP:loadMap: Could not open mmtile file '/home/elysium/run/bin/mmaps/0002334.mmtile'

And so on... Anyone have a clue on whats happening here? The directory and files are OK

**Comment by brotalnia** [comment]
It always says that, you can ignore it.
