### ISSUE TITLE
Bug？？or something wrong？

### ISSUE THREAD

**Issue by 15022642542** [elysium-project/server#633]
Dear GM Team:

Greetings~

we think maybe there is something wrong with  Vanquished Tentacle of C'Thun

on one hand , HP of the Tentacle only 8

and on the other hand ，the damage of the Tentacle make is also only 1

Furthermore, as I have know from our GM Team Stodola, "It's a known bug".

https://forum.elysium-project.org/topic/45512-bug%EF%BC%9F%EF%BC%9For-something-wrong%EF%BC%9F/

Is there any plan or schedule to fix this Bug ?

when would Vanquished Tentacle of C'Thun go well？

**Comment by sknnbones** [comment]
Its in "Pull Requests" tab

#528

**Comment by sknnbones** [comment]
what that means is a fix has been submitted and its being polished and tested.
