### ISSUE TITLE
Elemental invasion event not occurring [Darrowshire].

### ISSUE THREAD

**Issue by neutrals** [elysium-project/server#634]
**Bugged Behavior**

The elemental invasion event seems not to have occurred on Darrowshire for over a month now. The event is supposed to 'respawn' after 2-3 days but no signs of it since at least the middle of April

**Correct Behavior**

The elemental invasion event re-occurs every few days at Un'goro, Silithus, Winterspring and Azshara.

**Sources**

http://wowwiki.wikia.com/wiki/Elemental_Invasions

https://web.archive.org/web/20050425002614/http://www.worldofwarcraft.com/patchnotes/patch-05-04-19.html original patch notes

"Elemental invasions are "Invasions by elementals at different locations on Kalimdor have reportedly been occurring sporadically every few days."

**Comment by Vivenmort** [comment]
As someone who farms Dreamfoil extensively in Ungoro, can confirm.

**Comment by neutrals** [comment]
bump?

**Comment by Kittnz** [comment]
Shouldn't this stop at a point?

**Comment by neutrals** [comment]
The invasion respawns every few days, yes, but it hasn't spawned in over two months.

**Comment by Teadrinker1234** [comment]
Any news on this?
