### ISSUE TITLE
Shadowcraft Boots Bugged (Zekthur)

### ISSUE THREAD

**Issue by shrogueman** [elysium-project/server#636]
Hello,

Shadowcraft boots seem to only be giving +3 atk power to a rogue so I am assuming that is is only giving +3 agility instead of the +21 agility originally intended.

Thanks

- Shrogue

**Comment by Phoosy** [comment]
Duplicate of https://github.com/elysium-project/server/issues/548, please use the search function.

**Comment by shrogueman** [comment]
Sorry. First time using github

**Comment by m-laniakea** [comment]
Duplicate.
