### ISSUE TITLE
Ranged mobs double attack when pulled: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#638]
Mobs that have a ranged attack like spear throw or similar are using their ranged attack x2 when pulled. 
This is not 100% reproducible but happens on most pulls.
After that the range attack works as intended.

Mobs affected:
http://db.vanillagaming.org/?npc=578
http://db.vanillagaming.org/?npc=2368
Likely more mobs are affected but these are the two recently tested

Correct behaviour:
Use the ranged attack only once when pulled.

**Comment by sknnbones** [comment]
Murloc hunters in Westfall as well, also, the crab pets will agro you till you zone out, regardless of dealing damage (kiting) or not.

Defias in westfall will sometimes throw two knives as well,

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/50445-development-update-19072017/
