### ISSUE TITLE
Shadowcraft boots: wrong stats (Zeth'Kur)

### ISSUE THREAD

**Issue by Mnmliq** [elysium-project/server#639]
I tried to delete WOW+all Addons(including settings) and etc. Shadowcraft boots are still broken(+3 agility and +9 stamina) . Correct stats: +21 agility and +9 stamina

**Comment by Phoosy** [comment]
Duplicate of https://github.com/elysium-project/server/issues/548, please use the search function.

**Comment by Mnmliq** [comment]
#548 :  u just tell the same and add tag "confirmed", i dont understand what this mean. I have spoken with gm, we tried to fix my boots by resending them to me (same "wrong" stats)..then GM told me to report bugg here and said "bye" to me

**Comment by m-laniakea** [comment]
Duplicate
