### ISSUE TITLE
General channels are not working for non US clients with fix

### ISSUE THREAD

**Issue by Neo2003** [elysium-project/server#64]
French, German, Spanish, English,... clients should be able to see what other write in general channels like Trade, Guild Recruitment, Local Defense...

Also in Defense channels, user rank should be displayed.

I fixed this in one commit, but can't figure out how to create a pull request.
So here it is: https://github.com/Neo2003/ElysiumFixes/commit/5ca9e94d1ecd9bb858605214d0a6f5e1c020d4d5

Basically, general channels are decoded using client locale and special names are used internally. When a message must be sent to the channel, it's decoded pet client locale to sent with the proper channel name for their localization.

Name decoding is based on AreaTable.dbc, so server must have all languages dbc to support them like this:
dbc/AreaTable.dbc <- the English one
dbc/frFR/AreaTable.dbc <- French one
dbc/deDE/AreaTable.dbc <- German one
...
You probably have them all already.

I could not use the AreaTable you moved to database since it's not localized.

Neo2003

**Comment by Neo2003** [comment]
Pull request created.

**Comment by StadenElysium** [comment]
Accepted, thanks.
