### ISSUE TITLE
Noggenfogger Elixir

### ISSUE THREAD

**Issue by Bobanhanzz** [elysium-project/server#640]
I can't buy Noggenfogger Elixir from "Marin Noggenfogger". I have done the questline for it.

**Comment by Phoosy** [comment]
Duplicate of https://github.com/elysium-project/server/issues/548, please use the search function.

**Comment by ImperfectCell** [comment]
I also hope noggenfogger can be purged. It technically should be purgable.

**Comment by thepparker** [comment]
Was temporarily removed while transforms were bugged
