### ISSUE TITLE
STV quest - Fool's Stout follow up giving quest item but not giving quest

### ISSUE THREAD

**Issue by staplerx300** [elysium-project/server#644]
http://img04.imgland.net/RZHcl2z.jpg

ignore the snide guild comments from idek who that is

**Comment by brotalnia** [comment]
You need to complete Zanzil's Secret first. This is not a bug.

**Comment by staplerx300** [comment]
I DID 

Do you not see me getting the quest item in the screenshot

**Comment by staplerx300** [comment]
Addendum: I got the quest item for the follow up because I finished the prerequisite quest that you mentioned, zanzils secret. The issue is that I got the quest item to deliver the stout to shimmering flats....without getting the actual quest. In the top right questie is telling me that there is a quest available, the one in question, which I have the item for somehow, but I was never actually given the quest to deliver it.

**Comment by brotalnia** [comment]
The quest you are expecting to get is "Zanzil's Mixture and a Fool's Stout", right? It has two required quests - "Zanzil's Secret" and "Back to Booty Bay". Did you complete them both?

http://db.vanillagaming.org/?quest=1119

**Comment by staplerx300** [comment]
is "back to booty bay" an alliance quest only? because im horde...the NPC is a dwarf so i would assume it is

still not sure whats going on here, am i dumb and missing something or is this a bug

**Comment by staplerx300** [comment]
close this @mods im just stupid

http://i.imgur.com/VRn6fJI.png

didnt do the horde equivalent that @brotalnia mentioned

**Comment by staplerx300** [comment]
nevermind AGAIN

i went to the guy in shimmering flats and he would only give me this gray level 29 quest

http://i.imgur.com/5L3Va0L.jpg

i seriously dont get it i cant get this fucking follow up no matter what i do

**Comment by GuybrushGit** [comment]
Its bugged. The quest requires the quest 621 which is alliance only, so horde currently can't get it.
