### ISSUE TITLE
Darrowshire - Stratholme encounter bugged.

### ISSUE THREAD

**Issue by Ripper007** [elysium-project/server#646]
The Cannon Master Willey (id 10997) in Stratholme encounter is bugged. If the players try to use the cannons to kill the spawning mobs, they are killed instead of NPC's.

**Comment by GuybrushGit** [comment]
This should be fixed already with https://github.com/elysium-project/server/pull/423

**Comment by Ripper007** [comment]
Unfortunately it is not. We run last night and got killed and i posted the issue after that. As a side not , I did searched for the issue but only the ones still open.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
