### ISSUE TITLE
Dark Iron bracers

### ISSUE THREAD

**Issue by Viowar** [elysium-project/server#651]
As of patch 1.6 (Blackwing Lair Patch) they should be Bind on Equip, at the moment they seem to be Bind on Pickup.  Had someone make me a pair and was instantly bound.  Realm is Anathema

Some sources I found to back this up:

http://wowwiki.wikia.com/wiki/Patch_1.6.0
http://wowwiki.wikia.com/wiki/Dark_Iron_Bracers
http://wow.gamepedia.com/Patch_1.6.0
http://wow.gamepedia.com/Dark_Iron_Bracers

I have cleared all cache etc, still shows as BOP as of 5/9/17

**Comment by Cephel** [comment]
Bump for this, they are still BoP as of 1.6.0 on Elysium

**Comment by ItsmeAga** [comment]
Still Bop on Ely

**Comment by Shoby123** [comment]
Bump

**Comment by QAkvastskaft** [comment]
Fix applied: https://forum.elysium-project.org/topic/56778-development-update-14102017/
