### ISSUE TITLE
[Darrowshire] Amulet & Orb of the Darkmoon have incorrect stats

### ISSUE THREAD

**Issue by Kolmarwow** [elysium-project/server#652]
First off, I'm aware that there's already a report of this on github, but it's 13 days old & only lists wowpedia as a source so i thought i'd make another more detailed version. I've also heard a community manager say that these necklaces are not supposed to be updated until 1.10, which is incorrect. 

official blizzard patchnotes of 1.7 from an archived version of their old domain: http://web.archive.org/web/20051103054421/http://worldofwarcraft.com/patchnotes/patch-05-09-13.html
"The Amulet and Orb of the Darkmoon have had their stats improved and are now Epic (purple)."

archived page of the Orb from Allakhazam https://web.archive.org/web/20060519122049/http://wow.allakhazam.com:80/item.html?witem=19426
"but its epic and you can get it meaning its an epic necklace outside mc or those top instances... " posted on January 10th 2006, Patch 1.10 was in March 2006 so this confirms it was epic at the very least by 1.9.

archived page of the Amulet from Allakhazam https://web.archive.org/web/20060519122145/http://wow.allakhazam.com:80/item.html?witem=19491
"This is a good necklace for an Enhancement Shaman too. Its abount 1% crit, 100hp (well needed by Shaman)and adds dps with the 10 strength. " posted on October 20th 2005, when the game was on Patch 1.8. The current version of the amulet has no strength and 7 stamina instead of 10, confirming that it was in its updated version at patch 1.8

"Druid usability: 

+0,95% crit 
+0,95% dodge 

+20 attack power (if no heart of wild, no cat form) 
+24 attack power (heart of wild, still no cat form) 
+39 attack power (no herat of wild, but cat form) 
+43 attack power (heart of wild and cat form - finally) 

120 hp (heart of wild and dire bear) 
100 hp (all else) 

So for a feral in cat form, this is in practice about 
+1% crit 
+1% dodge 
+43AP 
+100 hp "

This implies the amulet gave 19 agility, 10 stamina and 10 strength at the time this was posted (December 30th 2005) which was still patch 1.8, which confirms again that it was in its epic state in at the
 very least patch 1.8. 

That's about all. The official Blizzard patch notes say that it was updated in 1.7, and with old comments from 2005 we can find out that it was epic at 1.8 at the ABSOLUTE latest, not 1.10.

**Comment by Vivenmort** [comment]
Great research. The guy who said it was updated in 1.10 likely just assumed that because that was when a lot of dungeon loot in Blackrock Spire, BRD etc was updated. Really suprised this wasn't fixed in the latest development update.

**Comment by thepparker** [comment]
Please make an issue in the database repository if the stats are still incorrect
