### ISSUE TITLE
Faction reputation does not work properly: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#653]
BUGGED BEHAVIOR
http://db.vanillagaming.org/?faction=67
http://db.vanillagaming.org/?faction=469
all those quests that should give +horde or +alliance reputation actually gives no reputation at all

CORRECT BEHAVIOR
needs to be scripted so it gives reputation to corresponding factions

Comment from QAkvastskaft:
This also affect Steamwheedle Cartel: http://db.vanillagaming.org/?factions=169
This affect both rep gain and loss and is likely the source of not being able to lose rep with goblin factions when killing their bruisers

Original post on bug tracker here: 
https://elysium-project.org/bugtracker/issue/3000
https://elysium-project.org/bugtracker/issue/3377
https://elysium-project.org/bugtracker/issue/4096

**Comment by lequintal69** [comment]
https://github.com/elysium-project/server/issues/291

**Comment by lequintal69** [comment]
Any news on that ? it should be quick to fix, isn't it ?

**Comment by lequintal69** [comment]
@GuybrushGit

**Comment by GuybrushGit** [comment]
From what I've seen this only affects the midsummer quests and a couple of western plaguelands quests right?

**Comment by lequintal69** [comment]
Also this one http://db.vanillagaming.org/?quest=6804#wh-comments
For some reason it's not listed as +horde reputation but didnt grant the rep either way

**Comment by GuybrushGit** [comment]
That's a seperate issue, that quest just has no quest reward assigned. Do you know of any other?

**Comment by lequintal69** [comment]
Yes I think it is. 

I don't know of any other quest having the same issue
