### ISSUE TITLE
"A Lost Master" incorrect availability: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#657]
Comment from QAkvastskaft:
Quest id 986 (A Lost Master) should only be available after completion of quest id 984 (How Big a Threat?)

BUGGED BEHAVIOR
The quest "A Lost Master part 1", given by Terenthis in Darkshore is obtainable at lvl 12 without any prerequisites and displays the animation that should be displayed upon turning in the quest "How Big A Threat part 1"(Terenthis talking to Grimclaw).

CORRECT BEHAVIOR
The quest"A Lost Master part 1" must become available after the completion of "How Big A Threat part 1" in Darkshore given by Terenthis. The animation that is displayed upon acquisition of "A Lost Master part 1" should be displayed upon turning in "How Big A Threat part 1" and serve as a logical connection between the 2 quests.

SOURCES
http://db.vanillagaming.org/?quest=986#wh-comments Look at the comment section.

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/825

**Comment by brotalnia** [comment]
It appears the info you guys had was wrong. "A Lost Master" should require "How Big A Threat 2", not part 1, and the script that plays after completing the quest is wrong. It spawns a sentinel instead of the polar bear. I will fix it tomorrow and make another pull request.

Proof: https://youtu.be/_S8TMimuYxU?t=2m0s

**Comment by QAkvastskaft** [comment]
Comment from wotlk:

By Fiamma on 07/09/2010 (Patch 3.1.3)
As of the current patch (noted above) the first How Big a Threat? quest is no longer the only prerequisite for this quest.
You must also complete the second How Big a Threat? quest, at least I had to on my lvl 21 Night Elf Druid.

**Comment by QAkvastskaft** [comment]
Might be false statement however and the prerequisite has always been part 2. I guess either way is fine

**Comment by brotalnia** [comment]
It's weird that they would change the prerequisite of a lvl 20 darkshore quest in mid WotLK, and there's nothing about it mentioned in the patch notes.

http://us.battle.net/wow/en/game/patch-notes/3-1-3

**Comment by QAkvastskaft** [comment]
You are probably correct. Making the quest end event available after part 2 should be fine

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/47461-development-update-24052017/
