### ISSUE TITLE
[NPC] Deathstalker Faerleia stuck after completion of quest event

### ISSUE THREAD

**Issue by Nelythia** [elysium-project/server#658]
The NPC "Deathstalker Faerleia" ( http://db.vanillagaming.org/?npc=2058 ) in Pyrewood, Silverpine Forest which starts the quest Pyrewood Ambush ( http://db.vanillagaming.org/?quest=452 ) triggers an event where you defeat 3 or 4 waves of elite enemies, after accepting the quest.

The quest and event work fine and as they should, however after completing the event you are not able to talk to her to finish the quest and receive your rewards.

Players can fix this by going out of the house and pulling other elite mobs to her so she can get aggro and die.
After respawning she works fine again and you can deliver the quest, until someone starts the quest & finishes the event again.

**Comment by QAkvastskaft** [comment]
A fix has already been committed for this issue. It is not on the live realm yet however. #421
