### ISSUE TITLE
Druid Quest "A better ingredient" not available

### ISSUE THREAD

**Issue by eddynation** [elysium-project/server#660]
Quest Giver: Torwa Pathfinder of Un'Gorro Crater
Class: Druid
Level: 50
Realm: Anathema 

The beginning of the quest series works, Towra Pathfinder. The next quest works, Bloodpetal Poison. The next quest works, Toxic Test. The last in the series is not offered, A Better Ingredient. This has been tested by many druids, and WBD files have been deleted to no avail. ZG is realeased and the patch where the quest was implemented has also been passed.

**Comment by QAkvastskaft** [comment]
This quest was added in patch 1.10: http://wowwiki.wikia.com/wiki/Patch_1.10
"A new level 52 druid quest that takes place in Un'Goro crater has been added."
