### ISSUE TITLE
Flarecore Leggings stats in 1.6

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#665]
In Patch 1.6, Flarecore Leggings should have +53 fire damage instead of +43 spell power.

Sources:
https://web.archive.org/web/20051210133306/http://www.thottbot.com/?i=40679

8th comment down:
"The +53 Dmg gives its full benefit to 3 second and longer spells"

http://wowwiki.wikia.com/wiki/Flarecore_Leggings

Patch 1.7.0 (13-Sep-2005): Flarecore Leggings now provide a damage bonus to all spells, not just fire spells.
Patch 1.6.0 (12-Jul-2005): Added.

**Comment by ImperfectCell** [comment]
Aren't we in patch 1.9 now?

**Comment by Sabre142** [comment]
Closing as thepparker fixed it
