### ISSUE TITLE
Smoked desert dumplings Elysium realm

### ISSUE THREAD

**Issue by pel-eili** [elysium-project/server#666]
Hello there is chain quest in Silithus started by "Calandrath"   And she is supposed to teach u a cooking recipe at 2nd part of the chain. Upon completing the quest she doesn't teach u the recipe and opens the 3rd quest chain tested with 300 cooking skill.

**Comment by Nelythia** [comment]
Not a bug.

It got introduced with the AQ patch.

**Comment by pel-eili** [comment]
still a bugbecayse the quest is available

**Comment by Slicy** [comment]
It was introduced with 1.8, not AQ patch which is 1.9.

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
