### ISSUE TITLE
Illumination talent doesn't work for Holy Shock 

### ISSUE THREAD

**Issue by killerduki** [elysium-project/server#667]
**Copy from old Bugtracker** 

https://elysium-project.org/bugtracker/issue/4387

 **Bugged Behavior**

Holy Shock always cost 325 mana, crits doesn't restore mana with Illumination talent. Even under Divine Favor (100% crit).

**Correct Behavior**

Illumination. This talent is the heart of the Healerdins build. It gives you a chance of 100% to loose no mana when you crit with one of your healing spells (Flash of Light, Holy Light, Holy Shock). Actually, you should instantly restore amount of mana equal to cost of spell.

**Sources**

https://web.archive.org/web/20060305042715/http://forums.worldofwarcraft.com:80/thread.aspx?fn=wow-paladin&t=881976&p=1&tmp=1#post881976

March 5th 2006

Next patch for instance, we've made a few tweaks. Holy Shock will work with Divine Favor and Illumination.

**Comment by QAkvastskaft** [comment]
This is confirmed

**Comment by GuybrushGit** [comment]
Holy Shock is giving me my mana back when I heal, only fails when doing damage.

**Comment by QAkvastskaft** [comment]
https://youtu.be/mjFZSHqgkpw?t=162
clip of a crit with holy shock as a damage spell, it looks like it has no cost but its very hard to see.
What are your opitnions
Also picture here: http://i.imgur.com/8Si0VK4.png

**Comment by GuybrushGit** [comment]
The text for the Illumination tooltip is:
>After getting a critical effect from your Flash of Light, Holy Light, or **Holy Shock heal spell**, gives you a $h% chance to gain Mana equal to the base cost of the spell.

**Comment by m-laniakea** [comment]
Working as intended.
