### ISSUE TITLE
Cant login on my new acc

### ISSUE THREAD

**Issue by 61mud** [elysium-project/server#67]
Hello, i started a new account where I downloaded vanilla wow from your server, I then tried to log in it started with saying "connecting" about 30 sec and it said "disconnected from the server" can anybody help :)?

**Comment by brotalnia** [comment]
If you are running your own server using Elysium's core, then you need to create an account from the console.
`
account create <name> <password>`

If you are talking about connecting to the live Elysium realms, then your question is in the wrong place, but it sounds like you forgot to change the realmlist.

**Comment by 61mud** [comment]
well when i change the realm it doesn't allow me

**Comment by 61mud** [comment]
when I save the realmlist.wtf it just says that its denied

**Comment by Locario** [comment]
open «run as administrator» with notepad
