### ISSUE TITLE
Badge of the Swarmguard proc rate

### ISSUE THREAD

**Issue by Raziya-Anathema** [elysium-project/server#670]
Hello! I'm here to report a bug, I hope I'm in the right place.
https://elysium-project.org/bugtracker/issue/4413

The Badge of the Swarmguard apparently has an incredibly low proc rate on Anathema. As you can see from the videos from retail vanilla in this bugtracker thread, the proc rate is actually supposed to be much, much higher. In my own experience, and the experience of several other hunters who also have the trinket that I've spoken with, we almost never get six stacks even by the end of the use effect...

Here are the videos in case you have trouble accessing the bugtracker thread:
https://www.youtube.com/watch?v=6DQPytnxvlo
https://www.youtube.com/watch?v=8dFsuv9dta0
https://www.youtube.com/watch?v=WJWZ8jcswj0

And here is an archived thread from Thottbot where you can see a ton of comments about the high proc rate and functionality:
https://web.archive.org/web/20070510001706/http://thottbot.com/i21670

Here are a couple of notable comments:

"**Great for hunters
Score 1.2 Vote: [-] [+] by dabba, 1.1 years ago**
A guildie of mine got it, it proc almost 100% on each attack, If he multishot and hit 3 target he get 2-3 proc. Awsome whit this trinket + rapid fire after 10 sec, then FD when it is on Cd and change trinket. "

"**Proc rate and effectiveness
Score 4.4 Vote: [-] [+] by Sama[of]Warsong, 1.0 year ago**
Not sure what the proc was like before but I can confirm that as of the current patch 1.10:

- It does stack with Sunder
- The proc actually gives you a buff which can carry over from one target to another
- Considering an 80% proc rate, it stacks up almost unbelievably fast"

I hope that's enough to go off of. Thank you for looking into this!!

**Comment by GuybrushGit** [comment]
Research by Bazzil from Kronos:

https://www.youtube.com/watch?v=WJWZ8jcswj0
10 attacks = 6 stacks = 60% proc-chance

https://www.youtube.com/watch?v=6DQPytnxvlo
18 attacks = 6 stacks = 33% proc-chance

https://www.youtube.com/watch?v=8dFsuv9dta0
7 attacks = 5 stacks = 71% proc-chance

https://www.youtube.com/watch?v=5MAZkK_xdFg&feature=youtu.be&t=1m43s
11 attacks = 6 stacks = 54% proc-chance

https://www.youtube.com/watch?v=sN1K21Nth1s
from 0:59 ::: 11 attacks = 6 stacks = 54% proc-chance
from 3:29 ::: 15 attacks = 6 stacks = 40% proc-chance

https://www.youtube.com/watch?v=NRdULbB2O_I
from 1:07 ::: 11 attacks = 6 stacks = 54% proc-chance
from 4:25 ::: 13 attacks = 6 stacks = 46% proc-chance
from 9:05 ::: 9 attacks = 6 stacks = 66% proc-chance
from 12:34 ::: 16 attacks = 6 stacks = 37% proc-chance
from 16:22 ::: 8 attacks = 6 stacks = 75% proc-chance

Average proc chance: **53,6%**

**Comment by Raziya-Anathema** [comment]
Lovely! Thank you for forwarding this research, GuybrushGit!

**Comment by trueshiver** [comment]
Hello! Thank you for making this post, i was going to make it once i had the chance to record myself on Anathema with the trinket.

1. Badge of the Swarmguard does not trigger ANY internal CDs on other trinkets. Proof is in the link below. Notice at the start how popping Badge trinket does not put his other on use trinket on cooldown.

- https://www.youtube.com/watch?v=6DQPytnxvlo

2. Badge of the Swamguard should stack with Sunder armor. I could not test this since i do not have the trinket currently.

- No current source but this should be the case or the trinket renders useless.

3, The procc rate in the current state of this beautiful trinket is GARBAGE. Everybody who actually played vanilla remembers this trinket to be a beast. This trinket is BiS for hunters for a reason. Spells should also activate the proccs from this trinket. Multishotting 3 targets etc.

- Look through the videos provided and see how fast the stacks grow, and that spells also apply stacks.

**Comment by Raziya-Anathema** [comment]
Thank you for your support, Truesilver! Here's hoping this beautiful trinket gets fixed as soon as possible. :)

**Comment by GuybrushGit** [comment]
All the other mechanics are working fine, it doesnt put trinkets on cd, it stacks with sunder etc. Only the proc rate needs changing, its currently 3 PPM.
The 80% claims don't have anything backing it up. I'd suggest giving it 50% or 15 PPM, based on that research but thats up to Elysium staff.

**Comment by Raziya-Anathema** [comment]
Indeed, based on the proc averages from the videos found, 50% seems a fair chance to use. It should be changed, though! In its current state, it's utterly useless.

**Comment by trueshiver** [comment]
How do you know it stacks with sunder armor? Have you tested x-amount of white hits and compared the damage?

**Comment by GuybrushGit** [comment]
I tested on my dev server with breakpoints.

**Comment by QAkvastskaft** [comment]
15 PPM seems about right looking at the sources from Guybrush

**Comment by trueshiver** [comment]
Hello. 21 days and still no response for a 5 minute fix.

**Comment by Blutzz** [comment]
Pls fix

**Comment by trueshiver** [comment]
Simple fix yet no action.

**Comment by dabadoo** [comment]
Has the fix been applied correctly to the servers? Barely getting 4 stacks during the 30 sec duration as fury
