### ISSUE TITLE
[AQ40 Anathema] Striker's Pauldrons quest not available (Hunter tier 2.5 shoulders)

### ISSUE THREAD

**Issue by muhsogyny** [elysium-project/server#675]
The quests for the other four pieces are available but not the shoulders.
This is the quest that should be in the game from the NPC named Andorgos:
http://db.vanillagaming.org/?quest=8659

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
