### ISSUE TITLE
[Anathema AQ40] Resistance values for bosses in the Temple of Ahn'Qiraj seems to be too high.

### ISSUE THREAD

**Issue by FurioCC** [elysium-project/server#677]
**The issue:** At the current moment the resistance values for bosses in the Temple of Ahn'Qiraj seems to be too high, which is causing too many full and too high partial resists on player spells even with applied warlock curses.

This is not supposed to be the case, and the base resistance values for bosses supposed to be in the range of 75-90 at least for 4 major magic schools (Fire-Frost-Shadow-Arcane and most likely the same for Nature), and then level-difference-based resistance should be applied.

I am not sure on what current values are based on, but AQ40 and Naxxramas bosses not having any additional high resistance values was common established knowledge back in the vanilla times and veterans of vanilla private scene have researched this topic thoroughly - take a look at example of discussion on old forums https://forum.nostalrius.org/viewtopic.php?f=24&t=38226#p26995

As the proofs of bosses not having high resistance values (and thus players not needing spell penetration to overcome it) please study these sources from 2006, that was done after resistance changes in patch 1.9:

**Proof 1:** Study on resistance values, resistance mechanics and usefulness of spell penetration
https://www.graffe.com/forums/showthread.php?40025-Partial-resists-and-spell-penetration-on-lvl-61-mobs-(caster-glancing-blows)

**Proofs 2 and 3:** Topics on Elitist Jerks discussing bosses resistances and uselessness of magic penetration

https://web-beta.archive.org/web/20110124001208/http://elitistjerks.com:80/f15/t8113-spell_penetration/

http://web.archive.org/web/20080408091535/http://elitistjerks.com/f33/t7573-question_about_usefulnes_spell_penetration/

I hope this provides enough proof and helps to sort this issue.

**Comment by Slicy** [comment]
Currently, every boss in AQ40 has 75 all resistances, which is default values of mangos, quite wrong and making the content easier than it should be.

The sources you linked are indicating possible resistances values for some bosses in AQ40, Naxx which are higher than 75.

Rename the issue to : "way too low" instead of "way too high".

**Comment by kevmodrome** [comment]
The current resistances are 75. With Curses it's 0. But then there's also level based resistance which can't be mitigated. Does it matter if it's 75 or 0? I would rather see increased resistance values so that more gear is viable but that is another question.

**Comment by GuybrushGit** [comment]
Hard to tell what their current resistance is. For the AQ launch they all were given 215 but  this was lowered after the first clear.

The stock mangos values come from the official WoW Bestiary, which has all AQ bosses with 0 resistances.

**Comment by FurioCC** [comment]
I am assuming this commit https://github.com/elysium-project/server/commit/e1236c29ef04eb51431a8d2ff83f8e037c8ca29b is live. Is it not?
Can someone link me to the current values here then?

**Comment by kevmodrome** [comment]
No, that one is not live. From what I have heard from someone who talked to Staden, they lowered them all to 75. Maybe he can confirm? @StadenElysium

**Comment by StadenElysium** [comment]
Can confirm.
