### ISSUE TITLE
Gubber Blump does not teach fishing: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#679]
BUGGED BEHAVIOR
Gubber Blump in Darkshore doesn't train fishing.

CORRECT BEHAVIOR
Gubber Blump should train fishing and also offer a dialog option to get free fishing if the following is true:

Has Family And The Fishing Pole quest
Does not currently have fishing.
SOURCES
http://wowwiki.wikia.com/wiki/Quest:The_Family_and_the_Fishing_Pole http://wowwiki.wikia.com/wiki/Gubber_Blump

Comment from QAkvastskaft:
Source: http://wowwiki.wikia.com/wiki/Gubber_Blump?oldid=341627 mentions hes a fishing trainer
Also 24h after completing quest 1141 (http://db.vanillagaming.org/?quest=1141) no mail has been received.

"
By vdrej on 11/03/2008 (Patch 3.0.2)
Once you turn in his quests (I don't know if it's related to one, or the other, or both), he sends you a mail the following day. Attached to it is one shiny bauble. One. It is rather terrifically funny. Here is a transcript:
"

I guess evidence is from a later expansion but I doubt this was not present in vanilla http://db.vanillagaming.org/?npc=10216#wh-screenshots for a better view of the letter

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/3710

**Comment by brotalnia** [comment]
I found a video from 2009 and he doesn't seem to be a trainer. Maybe it's a gossip option that teaches you fishing if you have the quest? Plus trainers usually have the <Fishing Trainer> title under their name, and this guy doesn't.

https://youtu.be/nSSOfjaTiTI?t=4m25s

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/47461-development-update-24052017/
