### ISSUE TITLE
Base Dodge and Base Parry values missing from StatSystem.cpp

### ISSUE THREAD

**Issue by demundus** [elysium-project/server#684]
Base dodge values are missing for several classes. Base parry values are missing for all classes. On all other core files i referenced to make sure it wasn't just Nost/Elysium's copy (StatSystem.cpp) there are defined base values for each class, followed by the modifier logic.

https://github.com/elysium-project/server/blob/f25097a00af3b2dc44aedff4567dae399f6ab137/src/game/StatSystem.cpp#L566

Is this as intended?

**Comment by demundus** [comment]
I've since learned from http://vanilla-wow.wikia.com/wiki/Dodge (if this is to be taken as the absolute truth) That warriors, hunters, and rogs have a base dodge of 0%. So this may not be a bug, but a coding preference to leave them blank as opposed to defining them as 0%.

**Comment by killerduki** [comment]
1- Vanilla-wow.wikia.com is completely broken , mixed and unreliable source.
2- You need to give evidence with timeline of dates from 2005/6.

**Comment by QAkvastskaft** [comment]
Looking at the code everything is correct

    float value = 0.0f;    (here is the base dodge for all classes not getting another base dodge a few lines below)
    switch (getClass())
    {
        case CLASS_DRUID:
            value += 0.9f;
            break;
        case CLASS_MAGE:
            value += 3.2f;
            break;
        case CLASS_PALADIN:
            value += 0.7f;
            break;
        case CLASS_PRIEST:
            value += 3.0f;
            break;
        case CLASS_SHAMAN:
            value += 1.7f;
            break;
        case CLASS_WARLOCK:
            value += 2.0f;
            break;
    }
