### ISSUE TITLE
MACE SPEC - WRONG PROC RATE! ROGUES/WARRIORS TALENT

### ISSUE THREAD

**Issue by oosumei** [elysium-project/server#687]
Mace spec is bugged, and hasn't procced for me as a combat rogue with maces and 5/5 in the mace specialization talent.

I draw attention to the two bug tracker reports below even though they are for warriors reporting that after extensive testing the proc rate is like 0.6%.

I believe the proc spell is the same for both rogues and warriors?

https://elysium-project.org/bugtracker/issue/3274

https://elysium-project.org/bugtracker/issue/1782

Should be a quick fix if someones added a decimal point by mistake!

**Comment by GuybrushGit** [comment]
Found no issue on dev server. Chance is 6%.

**Comment by oosumei** [comment]
Could you do the same testing in live? It certainly doesnt proc
