### ISSUE TITLE
Ouro's Sandblast not working correctly

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#690]
As it currently works the sand blast ability does not seem to remove threat from the people who are hit by it. Another problem is that it does not seem to be targeting ranged (although this might be a side effect of it not removing threat from the tanks correctly). 

"Sand Blast: 3.5k - 4.5k nature damage. Frontal breath affecting 180 degrees. You can fully resist it or not, damage is not reduced/blocked because it has an incapacitating effect that makes it a binary spell. Ouro sandblasts in the direction of the person in the raid with the highest threat and being hit by the sandblast clears all threat for that person. Sand Blast is every 20-25 seconds. It has 45 yards range and can be easily outranged." - https://forums.wowace.com/showthread.php?t=6253&page=31

**Comment by StadenElysium** [comment]
It does (or did) wipe threat but we are aware of the issue with ranged targets. The fix turned out to be more complicated than originally anticipated and had to be left until after the release.

**Comment by kevmodrome** [comment]
@StadenElysium i'm not sure this is actually fixed. We didn't see any sand blast hit the ranged this reset (today) even though they were on top of the threat meters.
