### ISSUE TITLE
Elder Torntusk quest missing.

### ISSUE THREAD

**Issue by Mnuemnomnue** [elysium-project/server#691]
There's a three-quest chain pertaining to this NPC in the Hinterlands(Kidnapped Elder Torntusk!, Recover the key!, and Return to Primal Torntusk).  The first two are in-game and work, but the third, which gives some gear, is missing.  All it requires is a turn-in, so I can't imagine it'd be too troublesome to add it at some point.

**Comment by StadenElysium** [comment]
Quest works fine here. What server is this on?

**Comment by thepparker** [comment]
Quest is added in 1.4/1.5, though only the final part of the chain is being disabled due to restricted items
