### ISSUE TITLE
Edgemaster With +15 Agility Glove Enchant Displaying Incorrect Increase In Crit Chance For Warriors

### ISSUE THREAD

**Issue by tyricius** [elysium-project/server#695]
I was told by a support representative to submit my issue here. I am writing this because of a display error in my spell book with regards to chance to crit.  As a warrior, the agility to crit chance scaling is 20 agility = 1 crit. The attached image files I have provided will help show the issue. As shown in the first attachment, my crit chance without my edgemaster gloves and enchant is 20.85%. The second attachment is to show my gloves having the +15 agility to glove enchant. The third attachment
 shows my crit chance with those gloves equipped. It shows that my Crit with the gloves is 21.88% which means by equipping those gloves my crit has increased by 1.03%. +15 agility is suppose to be a + 0.75% crit increase so the proper display is suppose to be 21.6% and not 21.88%. 

![crit base](https://cloud.githubusercontent.com/assets/28658849/26015019/f2475628-3713-11e7-888b-2302d4427413.png)

![edgemaster with agility enchant](https://cloud.githubusercontent.com/assets/28658849/26015025/f79cc6d0-3713-11e7-80ec-7bca2864785f.png)

![crit with edgemaster](https://cloud.githubusercontent.com/assets/28658849/26015027/fb6c1ec8-3713-11e7-9470-532eec7f0c68.png)

**Comment by smkrus** [comment]
You gain crit at a rate of 0.04% per skill point as well.
