### ISSUE TITLE
[NPC] Mossflayer Scout "running away in fear" incorrectly

### ISSUE THREAD

**Issue by Nelythia** [elysium-project/server#699]
The NPC "Mossflayer Scout" ( http://db.vanillagaming.org/?npc=8560 ) in Eastern Plaguelands attacks you and upon arriving at your character starts to **flee** 

"Mossflayer Scout attempts to run away in fear" while he just arrived at your character and did not get damaged.

**Comment by brotalnia** [comment]
According to the wowhead comments, that's how they are supposed to work.

"They run for help as soon as they're aggroed."

"They run as they are aggroed, yes, but they stop running when they are slowed down, such as using hamstring."

**Comment by Nelythia** [comment]
I guess I should research better in the future...

Sorry everyone^^
