### ISSUE TITLE
Arcane Shot, Serpent Sting, Volley not scaling with spell damage and base damage not matching tooltip

### ISSUE THREAD

**Issue by muhsogyny** [elysium-project/server#706]
I hope this doesn't require screenshots, it would be a nuisance to upload all of them. I'm just going to post numbers with gear.

This may seem insignificant because what hunter has +spell damage on their gear?
Well, tier 2.5 for hunters has +spell damage. Those stat points are wasted if the +spell damage does not affect abilities that should scale with spell power. It's bad enough that the gear has +spell damage to begin with.

I cannot find values for the exact amount of spell damage scaling for each ability, however I can make some reasonable guesses. If someone else can confirm these values please do so.

Arcane Shot*: Probably scales like other _instant cast single-target spells_ such as Fire Blast.
Serpent Sting: Probably scales like other _single-target DOT spells_ such as Corruption.
Volley: Probably scales like other _channeled AOE spells_ like Blizzard**.

*Note that Arcane Shot is unique in that it benefits from both spell damage and the 100% bonus critical damage standard for physical-based abilities (as opposed to the 50% bonus critical damage default for spells), while also having the ranged critical strike critical hit chance of the hunter (as opposed to the spell critical hit chance).

**Note that Volley is channeled over 6 sec. while Blizzard is channeled over 8 sec.

**Tests:**
Arcane Shot (rank 8) tooltip says to do 183 Arcane damage.
Arcane Shot (rank 8) actually hits for 188 Arcane damage, with both +0 spell damage and +21 spell damage on gear. Tested it naked and with gear and does not appear to scale with agility or ranged attack power either.

Serpent Sting (rank 9) tooltip says to do 555 Nature damage over 15 sec. (111 per tick)
Serpent Sting (rank 9) actually does 570 Nature damage over 15 sec. (114 per tick) with both +0 spell damage and +21 spell damage on gear. Tested it naked and with gear and does not appear to scale with agility or ranged attack power either.

Volley (rank 3) tooltip says to do 80 Arcane damage every second for 6 sec. (480 total)
Volley (rank 3) actually deals 82 Arcane damage every second for 6 sec. (492 total) with both +0 spell damage and +21 spell damage on gear. Tested it naked and with gear and does not appear to scale with agility or ranged attack power either.

I only compared naked with gear in order to see if the deviation between tooltip and actual usage was due to agility or ranged attack power scaling. They are not supposed to scale with agility or ranged attack power, only spell damage.

**Comment by brotalnia** [comment]
Just a tip, an easy way to test if something is scaling with +spell damage is by using the .modify spellpower command. Just set it to something ridiculous like 10000 and you'll instantly know if spell power has any effect on the spell without having to equip and unequip gear. And it's easier to see how much it scales because you can set it to a round number.

**Comment by GuybrushGit** [comment]
https://github.com/elysium-project/server/pull/523

**Comment by Mithedhel** [comment]
@GuybrushGit @muhsogyny The reason why it's not matching the base damage is because you have the MM talent of +5% with ranged weapons which affects that. There's no bug there

Serpent Sting lower ranks scale with spell damage but ranks 8+ are not.

**Comment by GuybrushGit** [comment]
Tested r8 and r9 serpent, scaled correctly.

**Comment by muhsogyny** [comment]
@Mithedhel I'm 0/21/30 Survival spec, so I don't have the +5% damage with ranged weapons talent.

**Comment by thepparker** [comment]
Should be fixed
