### ISSUE TITLE
After the disconnection, the quest item "A Mysterious Message" disappeared,

### ISSUE THREAD

**Issue by CosmoBeard** [elysium-project/server#707]
I know English badly, I write through a translator
After the disconnection, the quest item "A Mysterious Message" disappeared, I dropped the quest, but I do not have it. Return me the quest and the item or give the last quest in this series http://db.vanillagaming.org/?quest=166
My nick Buddhadharma mage gnom  Elysium

**Comment by m-laniakea** [comment]
This is not the place for this.

If you still have any part of the quest that we can verify,
a GM may be able to help you.

**Comment by CosmoBeard** [comment]
How do I contact GM?
