### ISSUE TITLE
Gold and herbs are gone.

### ISSUE THREAD

**Issue by Snake305** [elysium-project/server#708]
Hello it's not that much but im new on this server and just lvl 19. I lost my 6 gold i've got from the auctionshouse by selling 15 Swiftthistle's and 5 Swiftpotions. After this ''runback'' or i don't know how you guys call it. everything is gone even my other herb materials. I hope u guys can fix it somehow. Charactername is Snakexd.
Thanks.

**Comment by sknnbones** [comment]
Nothing was saved , there will be no restoration.

**Comment by m-laniakea** [comment]
sknnbones is correct, sorry.
