### ISSUE TITLE
Lost several hours of game progress

### ISSUE THREAD

**Issue by Moomphs** [elysium-project/server#709]
After being disconnected today I have lost several hours of gameplay on my lvl 21 Mage, so XP, quest progress, items gained. Hopefully this can be resolved!

**Comment by CosmoBeard** [comment]
+1.

**Comment by queequeeg** [comment]
+1 same

**Comment by sknnbones** [comment]
as far as I am aware, there will be no restorations for items/level/gold.

Simply put, nothing saved, so they have no logs/etc to go off of, and far too many players to sift through. Sorry :/

**Comment by m-laniakea** [comment]
@sknnbones correct, sorry.
