### ISSUE TITLE
Druid aquatic form missing

### ISSUE THREAD

**Issue by SinisterMatti** [elysium-project/server#71]
On Anathema since the last patch when shifting into aquatic form druids stay in the caster form, but still have the swim speed buff and underwater breathing.

**Comment by henkethebenke** [comment]
Are you alliance or horde? Isn't [this row](https://github.com/elysium-project/server/blob/43452c0d9cdce841bef71c592a381c38fb68d37a/src/game/Spells/SpellAuras.cpp#L1982) kind of strange? I don't have a test environment working on this computer so I can't help.

**Comment by SinisterMatti** [comment]
I'm horde, and I've confirmed with other tauren druids that they're having the same issue.

**Comment by AndersSahlin** [comment]
[https://github.com/cmangos/mangos-classic/blob/master/src/game/SpellAuras.cpp#L1537](mangos) has the same model id for both factions. Not sure if that's right but at least it's better than nothing...
