### ISSUE TITLE
Lost gold and experience from this morning's rollback

### ISSUE THREAD

**Issue by Jeremy-Friedman** [elysium-project/server#710]
I (Trolipop) was sent 50g in the mail from a character named Zoups not long before the rollback. About an hour before the servers went down I opened the mail/gold and no longer have it. Zoups does not have the money he sent either. Would it be possible for this to get restored? I sent him a thank you letter shortly after opening his mail/gold if that helps with finding the thread. i also got my mage from about 75% into level 27 to about 10% into level 28. If that could be corrected as well, that would be great. Thank you (Bolipop is the mage's name)

**Comment by Zoups** [comment]
Hello I'm Zoups and can confirm I send 50g to Trolipop. I also didnt got gold back after server Rollback.

Postal.lua (wtf file) :
`Postal_To = "Trolipop"`

**Comment by sknnbones** [comment]
as far as I know, there is no recovery.

Items will not be restored.

**Comment by m-laniakea** [comment]
sknnbones said it all, sorry.
