### ISSUE TITLE
Can't complete quests

### ISSUE THREAD

**Issue by heidelbach95** [elysium-project/server#711]
As so many others i lost charater progress. The quest items dont drop for the quests i already completed. At the quest giver there is a   yellow question mark as if its ready to be turned in.

**Comment by heidelbach95** [comment]
It's all westfall quests. Gnome paw, red leather bandana og also the letter from lewis supposed to be delivered in Stormwind. 3 Quests i can't complete

**Comment by CosmoBeard** [comment]
i can't complete last quest "The Defias Brotherhood"

**Comment by m-laniakea** [comment]
This is not the place for this. 

If you still have any part of the quest that we can verify, 
a GM may be able to help you.
