### ISSUE TITLE
Darkmoon Card Maelstrom should not scale with spell damage

### ISSUE THREAD

**Issue by fidbugs** [elysium-project/server#719]
At the moment Darkmoon Card Maelstrom is scaling with bonus spell damage, when it should not. 

Screenshot shows 331 and 392 hits.

https://gyazo.com/d86c887569de6bdc74ad34d0f1c01460

Evidence from that time suggest opposite, no scaling from bonus spell damage.

Comment on allakhazm on DMC made by nmeye, regarding bonus healing and spell damage affecting, stating that that kind of mechanic was removed in patch 1.7.

http://web.archive.org/web/20071229154006/http://wow.allakhazam.com:80/db/item.html?witem=19289

https://gyazo.com/cd0ec848e603f48c61d70b9c3ba41faa

Comment made by Nirual stating that spell damage bonus on similar item with spell proc was removed in beta(as well on most other items).

http://web.archive.org/web/20071211130436/http://wow.allakhazam.com:80/db/item.html?witem=19287;source=live

https://gyazo.com/de288685e8286aeb6b5a56a4f418f53d

Patch 1.7 notes confirm this change as all item procs(and enchants) would no longer be affected by bonus healing.

http://wowwiki.wikia.com/wiki/Patch_1.7.0

It should also be noted that DMC was well known item in vanilla, if it really scaled back then with spell damage it would almost certainly be common knowledge and used by some builds that had spell damage gear - like for instance enhancement shamans and holy damage paladins. 

**To fix:**

Remove bonus spell damage scaling.

**Comment by ImperfectCell** [comment]
http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?direction=prev&oldid=368615 Scales in November 24, 2006
http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?direction=prev&oldid=339113 November 24, 2006 and beyond says it did

Sorry to rain on your parade Android 17 but sources do not agree with you. look at the date. Seems that it did scale in late vanilla 

What you are providing dates from Aug 19th 2005 and such as patch 1.7 and far before November 2006. 
You also forget that there are many spell damage scalers in Vanilla
The blood drinket, shard of the fallen star, demon forged breastplate, crystal restore, skullflame shield and so many more (maybe 40 more)

http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?direction=prev&oldid=339109 and before is when it did not scale

Prove me wrong so my tail rips off

https://www.youtube.com/watch?v=q6lln4888D8

Too bad you cant..


Youre comment was not enough to beat cell

https://www.youtube.com/watch?v=bYafdlj2P0Y

**Comment by fidbugs** [comment]
One hour old profile, just for this? Thats quite sweet :)

Ranking sources from video evidence(highest) to thottbot comment(mid) to player memory(lowest), wow wiki is as good as not having any evidence. 

But even if it were as you put it, the meaning of word "may" means possibility that is uncertain, thus proves nothing.

http://dictionary.cambridge.org/dictionary/english/may

Also there was no patch regarding vanilla content past 13th October 2006, patch 1.12.1, thus your logic of possible change in "late vanilla" based of wow wiki "_may_ be effected" makes no sense. No one would change item that has been in game from patch 1.6, thats 12th July 2005.

Regarding other items, Shard of fallen star... yes, that one did not scale either. 

I dont need to prove you anything. Bug report is here, devs will judge it all in the end.

Have a nice one!

**Comment by theloras** [comment]
Fideus - stop it already.

Darkmoon Card Maelstrom is NOT Darkmoon Card Heroism - saying the two are the same is being intellectually dishonest.

As for your evidence - this guy clearly is mixing up the two trinkets because he talks about Arcanite Champion and Crusader enchant - two spells which healed the player as does DMC Heroism

http://web.archive.org/web/20071229154006/http://wow.allakhazam.com:80/db/item.html?witem=19289

https://gyazo.com/cd0ec848e603f48c61d70b9c3ba41faa

http://wowwiki.wikia.com/wiki/Patch_1.7.0 = changes to items that HEALED not items that did DAMAGE

**Comment by killerduki** [comment]
https://cdn.discordapp.com/attachments/230437139463012353/313505107218137099/unknown.png

This comment directly goes against your "evidence" .

And as confirmation here is Wowwiki from 2006

http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?direction=prev&oldid=368615
Revision as of 08:33, November 24, 2006

**. It is known to crit and may be effected by +spell damage**

**Comment by fidbugs** [comment]
Person asks if it is affected by spell damage, other person says it was removed, even stating the patch when it happened(Darkmoon was introduced 1.6 and fix was right after 1.7). It is an undocumented change, could have easily been a silent patch. You don't expect them literally listing every item that they fixed, they just pointed out Crusader(that was introduced few patches ago). 

I never said they Maelstrom and Heroism are the same, i said similar, in the sense that they are both Darkmon Cards and have on hit effect. That comment is here as a general guide and rule of thumb to prove blizzard was aware of item procs scaling with spell damage as of early beta - where they started fixing it - all thru out whole vanilla, and item proc scaling in any way witg spell damage/healing was exception. 

Again ill repeat - we have direct statement on DMC that it does not scale, combined with general not scaling from spell damage on item procs(being removed in beta).

@killerduki 

https://cdn.discordapp.com/attachments/230437139463012353/313505107218137099/unknown.png

That comment clearly refers to different in game mechanics such as Stormstrike, BWL vulnerabilities, Power Infusion, or any other effect that increases damage done to target or done by player - they do affect spells, item procs, enchants and even poisons - yes that is true. But has nothing to do with bonus spell damage from gear. He uses _"plus"_ in that sentence as to increase effect of what he already stated, to connect his previous points to this one, word plus is used as conjunction.

http://dictionary.cambridge.org/dictionary/english/plus

Your wowwiki comment, proves nothing again.

@theloras 

As for being intellectually dishonest, you should go to your Shard of the Fallen Star report, then come back here, then go back there again - to realize what being intellectually dishonest means(posting the video in lower resolution for combat log not to be visible, and not posting combat log screenshot clearly stating opposite of what you reported), and to learn something about spell damage scaling and items. 

TBH i am disappointed how two people that lead Holy Resistance campaign that benefited paladins and benefited in general getting this server and many others close to Blizzlike - are getting so low just for one item that is clearly bugged on private servers(as well as many others items).

**Comment by ImperfectCell** [comment]
And I am disappointed Paladin at how you are bothering to report on a random unoverpowered item that gains a measly 50 damage from spell damage as opposed to a more nerf needed fear that can bug tself through stuns, incapacitates and anything. Shame on you.

https://www.youtube.com/watch?v=TOokrV2MjQY

**Comment by ImperfectCell** [comment]
"No one would change item that has been in game from patch 1.6, thats 12th July 2005."

Are the devs really going to believe you? You already made a second mistake. Since its debut in Patch 1.6.0 (12-Jul-2005) http://wowwiki.wikia.com/wiki/Nightfall_(axe) They changed Nightfalls effect from -60 resistance up until Naxxramas http://wowwiki.wikia.com/wiki/Patch_1.11.0 Shadow of the Necropolis 20 June 2006 to 15% spell damage.

**Comment by ImperfectCell** [comment]
Please change the title to Darkmoon Card Maelstrom should scalle with spell damage

**Comment by fidbugs** [comment]
It makes not much sense to argue and explain things to you, but for sake of people who read this ill address your concern.

Regarding what i said that _"No one would change item that has been in game from patch 1.6..."_ point.

With evidence i presented it is clear that procs scaling with spell damage was not vanilla thing(with few, arguable, exceptions). It was removed in early beta, and later on same policy was implemented on items that initially came to game scaling - mindset was that that kind of mechanic gives advantage to classes that have those stats on items(Shamans, Paladins) that other classes cant obtain, thus resulting in specific items being stronger on certain classes. Same logic stands behind so called PPM mechanic - that some items and procs would be stronger for specific classes if there was no such mechanic - that is called game balancing. 

Same logic goes for Nightfall improvement, it was a change that gives something useful to something that was not used. So that kind of game improvement was Blizzards way, same reason is why they removed scaling in beta and later on. Spell scaling of items and procs was not balanced.

So yes, no one would change item that was balanced - that was DMC.

Not to mention yet again, that your wowiki source has almost 0 validity, even the later revision states "and _may_ be effected by +spell damage", focus on MAY. That's 12 day difference from one that states _"but **not** being effected by +spell damage"_. It literally removes any sense from that source, more so it reinforces my claim that it does not scale.

You are clearly confusing things, and your "source" has no validity.

**Comment by killerduki** [comment]
> TBH i am disappointed how two people that lead Holy Resistance campaign that benefited paladins and benefited in general getting this server and many others close to Blizzlike - are getting so low just for one item that is clearly bugged on private servers(as well as many others items).

@fidbugs  I don't give a shit about something that should be nerf , i was 1st Paladin that insist to get Consecration AP fixed to not scale while everyone was opposite.
I am here to discuss bugs/bugreports , not here "to worry" about some item that gives 5 dps at maximum.
So please stick on reports instead your "disappointments" and at least say Thank you for bringing the Holy Resistance else you as Paladin would've been at the corner kneeling for dps.

At end of the day , stick on Topic and let this discussion don't drive your ego. 
I have over 20 Bugs to report regarding Paladins , many of them whose are still unknown for you, i don't care because they won't benefit much and is just wasting Dev time.

**Comment by fidbugs** [comment]
You have put lot of effort for someone that does not worry about 5DPS. 

But yeah, lets stick on topic, and focus on reporting bugs. And trust me you should report every bug you find, bit by bit, it will all get fixed with time. ;)

**Comment by ImperfectCell** [comment]
Im an alien bug. You'll have to report me too.

**Comment by GuybrushGit** [comment]
Very flimsy evidence for both arguments. Can't really draw any conclusions.

**Comment by killerduki** [comment]
He have no evidence about maelstrom , the only evidence he give is in regard to Sulfuron Hammer.

**Comment by fidbugs** [comment]
I don't agree that evidence is flimsy. At all, it forms strong claim based on multiple available information from vanilla period and logic of game mechanics/development.

First of all you have direct response to a question if DMC benefits off bonus spell damage, and the answer is no, even listing when it was nerfed.

Even if that by itself is not "hard" evidence, there are other information's regarding subject that combined together make a strong argument. To that list you can add:

1. comments about it being removed in beta(general remark about how item procs don't benefit from +spell damage)
2. items that most people from private community believed to be benefiting from spell damage proven that they do not benefit from it - [Sulfuras](https://github.com/elysium-project/server/issues/737), [Shard of the Fallen Star](https://github.com/elysium-project/server/issues/846)
3. same mechanic regarding bonus healing removed for items/procs/enchants with healing effects(Crusader, paladin T1) - if they did not want imbalance there, why would blizzard keep it for damage procs, why shouldn't Fiery be affected with +spell damage while DMC should?

All that together. leads to conclusion that item procs/enchants did not benefit from bonus spell damage, or at least in this case Darkmoon Card Maelstrom(to stick to bug report).

On top of that you can add this - another direct evidence. This time on both DMC and Heart of Wyrmthalak(another item mistakenly believed to be benefiting from +spell damage - they use same mask for their effect aura 42) that they are not benefiting from spell damage by paladin that uses 6/8 T2.

http://web.archive.org/web/20070331193058/http://www.thottbot.com:80/i22321

https://gyazo.com/61154ac368d44e2669c54d126ce5cf84

On the other hand you have 0 evidence that it actually benefits from bonus spell damage, other than that one revision of wowwiki post that says "may". No other evidence to was ever presented.

**Comment by killerduki** [comment]
Provide please evidence for every single item separated instead assumptions.

Anything that was not given with solid evidence should goes invalid #period.
