### ISSUE TITLE
Cannot mount in Booty Bay or on the zeppelin.

### ISSUE THREAD

**Issue by SinisterMatti** [elysium-project/server#72]
Players cannot mount in Booty Bay or on the zeppelin. They are able to ride mounts in these areas if they were already mounted. Druids are able to cast travel form in these areas still, so it is still registered as outdoor areas.

**Comment by FractalCabush** [comment]
Pretty sure thats intended

**Comment by SinisterMatti** [comment]
It wasn't like that an vanilla retail. I suppose it's possible that devs decided to deviate from bliz like for this one feature, but I can't imagine why they would.

**Comment by jsb** [comment]
Not being able to mount inside Booty Bay is the correct behavior, as far as I remember.

I don't know whether the remaining mounted is correct or a bug, though.

**Comment by SinisterMatti** [comment]
Hmm, apparently you're right about booty bay, according to this article. https://www.engadget.com/2008/08/12/mounts-now-welcome-in-booty-bay/

Do you remember if the same was true with the zeppelin though?

**Comment by fatalmatt** [comment]
Yeah you weren't able to mount on zepplins at all. Although on retail there was a bug where you could wedge yourself into the corner of the thing in the middle of the zepplin and it would allow you to mount xD
