### ISSUE TITLE
lost item : glowing shard

### ISSUE THREAD

**Issue by lazer57** [elysium-project/server#720]
Hello, i've lost an item (and a lot of xp) 2 days ago when the server crashed.

I have the quest The glowing Shard from wailing caverns but the item "Glowing Shard" disapeared after the crash.
I need it to give at Falla Sagewind at the south of crossroad.
Can you give me this item please ? This quest give a ton of xp :x

Thanks for your support

**Comment by m-laniakea** [comment]
This is not the place for this. 
If you still have any part of the quest that we can verify, 
a GM may be able to help you.
