### ISSUE TITLE
Quest: Call of Water

### ISSUE THREAD

**Issue by Boldenona** [elysium-project/server#721]
Good morning game masters I have lost my "Water of Sapta" and I can not complete the quest "Call of Water". Can you help me please, thank you very much. Character: Boldenona, server: Elysium(PVP)

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you
