### ISSUE TITLE
[Bug]Cookling

### ISSUE THREAD

**Issue by HeavenlyFury** [elysium-project/server#723]
At least twice now I have send raw sagefish to an alt in an attempt it to level cooking but once I learn the recipe and send the fish, when I go to cook the fish it gives me the error "this spell is not available to you.

**Comment by druidish** [comment]
Unless you're on Anathema the sagefish recipes will be locked until patch 1.9 (AQ).

**Comment by StadenElysium** [comment]
Intended behaviour until 1.9, as Druidish states.
