### ISSUE TITLE
Archmage Xylem not interacting

### ISSUE THREAD

**Issue by AnzoPik** [elysium-project/server#73]
Archmage Xylem not able to be interacted with in Azshara on Elysium PVP. Please fix this :)

**Comment by henkethebenke** [comment]
Iirc the level 50 class quests are not supposed to be in game until a later patch.

**Comment by FractalCabush** [comment]
On Elysium, he does not have his quests enabled, since they arrived in patch 1.7, however it might also be the case that he isnt supposed to be interactive at this point?

**Comment by FractalCabush** [comment]
A pull request is up that adds interactivity in his npc gossip :)

**Comment by FractalCabush** [comment]
henkethebenke, which server did you see the quests available on? they are not available on Ely & Zeth locally. So unless you are on Anathema (where they should be active) its not an issue
