### ISSUE TITLE
Problems with the return stone

### ISSUE THREAD

**Issue by Sadjiuss** [elysium-project/server#732]
Innkeeper does not give a new return stone. And I can not move the house. Server Elysium, character "Deviantt".

**Comment by StadenElysium** [comment]
You can get a new hearthstone by opening the innkeeper's purchasing window. Leaving this open since this isn't the correct behaviour.

**Comment by StadenElysium** [comment]
Correct and current behaviour is to receive a new hearthstone when changing your location.
