### ISSUE TITLE
Judgement of Righteousness does not triger procs correctly

### ISSUE THREAD

**Issue by fidbugs** [elysium-project/server#736]
Currently Judgement of Righteousness is not triggering all procs. Thru my testing i discovered that it does not trigger procs from trinkets , but it triggers enchants and weapon on hit procs(such as Sulfuras fireball). 

Test 1 with Heroism and Maelstrom, 200 hits:

https://gyazo.com/faeea2123190ab4c14d4c7c576a94b75

Test 2 with Maelstrom and Hand of Justice, 200 hits:

https://gyazo.com/7c31b66967088a855e378d9bc9a72950

In both tests i only procs i got are Fiery Weapon and Sulfuras fireball.

**Correct behavior:**

Judgement of Righteousness should trigger all procs - item procs, weapon procs and enchants - it is considered a melee attack by the game. 

Evidence for this comes directly from patch 1.9 notes where it clearly states:

Judgement of Righteousness - The damage of this judgement was increased significantly. _This judgement can now trigger procs._ The bonus from spell damage items has been increased slightly. 

http://wowwiki.wikia.com/wiki/Patch_1.9.0

I am unable to test any more items so cant tell what works what does not, so i ask for ability to be reviewed in code thoroughly and fixed so it is able to trigger all procs from various sources(items, enchants, food buffs?, etc.)

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
