### ISSUE TITLE
Stealth breaks in northern Feralas

### ISSUE THREAD

**Issue by SinisterMatti** [elysium-project/server#74]
Server: Anathema
Faction: Horde

On the island in the middle of Jademir Lake in Feralas (where Emeriss the world dragon spawns) stealth breaks seemingly randomly. 

I noticed this while in a raid for Emeriss. This occurred both while the boss had been pulled and when it had not. The issue does not seem to be affected by the players combat status, and the combat log does not show any effects or spells bringing the stealthed player out of stealth. I confirmed this affects both druid prowl and rogue stealth. 

The issue stops occurring about mid way between the island and the mainland. In all of my tests there were no other players in the immediate vicinity, no flares, traps, or AOEs.

**Comment by PlaskED** [comment]
Emerald dragons aura of nature will indeed break stealth.

**Comment by SinisterMatti** [comment]
Even when the dragon is not in combat and the stealth user is not affected by the debuff?
