### ISSUE TITLE
Ritual of Summoning

### ISSUE THREAD

**Issue by StadenElysium** [elysium-project/server#741]
If a player moves during summoning, they should no longer count as clicking the portal. That is, the two clickers must both be casting at the same time for the summon to trigger.

**Comment by sipertruk** [comment]
Also actually the spell is instant whenever all the uses count is reach, but there's a cast time for each of the ritual spells http://db.vanillagaming.org/?spell=7720 5s for player summoning.

**Comment by Sinn** [comment]
IRC you were channeling until all three users were simultaneously clicking.

**Comment by kevmodrome** [comment]
> IRC you were channeling until all three users were simultaneously clicking.

This is what I remember as well.

**Comment by sipertruk** [comment]
You can check cast times from when required uses count is met in videos.

Ritual of summoning, video from 2008 but I doubt blizz nerfed it : 
https://www.youtube.com/watch?v=0_QdNed2QU4
http://db.vanillagaming.org/?spell=7720 effect has 5s cast

Same with other summoning ritual effects :

Ritual of doom effect 10s
https://www.youtube.com/watch?v=ZQQVc7GY5VM
http://db.vanillagaming.org/?spell=18541

Uldaman's altar effect 5s, same mechanic
https://www.youtube.com/watch?v=SbieMm_aJ4E
http://db.vanillagaming.org/?spell=11568

**Comment by sipertruk** [comment]
It feels instant but actually there's already a cast time.
Another thing : if one of the 2 helpers cancels too soon, the spell is wasted (and the warlock pissed)
It seems logical or maybe I'm wrong?

**Comment by sipertruk** [comment]
Guybrush was asking in #295 what was the spell for the channel animation.
The real spell for the channel animation of ritual of summoning is .. ritual of summoning.
Doing the following
~~~c++
        WorldPacket data(MSG_CHANNEL_START, (4 + 4));
        data << uint32(698);
        data << uint32(60000);
        player->SendDirectMessage(&data);
        player->SetUInt32Value(UNIT_CHANNEL_SPELL, 698);
~~~
Gives that
![summoningritual](https://cloud.githubusercontent.com/assets/7644041/26758409/6aeaf262-48dd-11e7-8848-033556eb5fb9.png)
Same for ritual of doom though it's weird, both hands should be dark
![ritualofdoom](https://cloud.githubusercontent.com/assets/7644041/26758416/a46ebd34-48dd-11e7-9e5c-9abeaeb6784d.png)
I guess for this kind of spell what is needed is to not handle effects and send only the channel part of packets. Something like that.
