### ISSUE TITLE
Red Scepter Shard quest timer isn't aligned with Nef destroying the shard

### ISSUE THREAD

**Issue by chrispphillips** [elysium-project/server#742]
When doing Nefarius's Corruption last night, I had roughly 38 minutes left on the 2 hour quest timer and Nef destroyed the shard. It was right after we wiped however but nothing I can find states that you have to kill him on your first attempt unless that's an Elysium change. Also, he didn't drop the item From the Desk of Lord Victor Nefarius, instead he dropped nothing relating to the quest.

**Comment by m-laniakea** [comment]
You are correct, currently you will not be awarded the shard if you wipe in the Nefarius encounter, because the idea was to give it only to those who had a flawless run. 

Then a follow-up question for you, @chrispphillips, regarding the Note: You wiped while he was in human form, is that right?
