### ISSUE TITLE
Zero quests available in Cenarion Hold

### ISSUE THREAD

**Issue by drushk01** [elysium-project/server#746]
Arrived in Silithus and completed the breadcrumb quests: Warlords Command, and The new Frontier. Absolutely zero quests available to me (level 59 horde).

**Comment by GuybrushGit** [comment]
What server?

**Comment by shmigy429** [comment]
Make sure to do [Taking Back Silithus](http://db.vanillagaming.org/?quest=8276) first, and you need to go to Moonglade to progress The New Frontier; even then Silithus is kinda not the best questing area for leveling. I ran out of quests around 59 as well and just ground the wind elementals in the NW corner

**Comment by TNadal** [comment]
some servers will have basically _ZERO_ quests in silithus, because the quests were not active during the patch those servers are on.
