### ISSUE TITLE
Mark of The Wild Decreasing Displayed Crit % under Spells and Abilities (p)

### ISSUE THREAD

**Issue by heyguyslol** [elysium-project/server#747]
Dont know if it's actual, but when i cast mark of the wild on myself (rank 3) level 20, my crit % goes from 7.35% to 3.05%. This shouldn't be happening, if anything, it should increase my crit% because mark of the wild (rank 3) increases armor by 105 and all attributes by 4.

**Comment by StadenElysium** [comment]
Are you able to reproduce this?

**Comment by heyguyslol** [comment]
Yes. However as soon as I put a talent point into sharpened claws, the crit
percentage in my spells and abilities corrected itself to a normal value in
cat and bear form, in human form though, my crit chance is still 1.74% so
it jumps from 1.74% to 11.62% when shapeshifted... which doesn't seem right
seeing as my talents only add 6% crit chance. so that's a missing 4% that's
not being displayed correctly.

**Comment by QAkvastskaft** [comment]
You are most likely lacking in weapon skill for the weapon you are using when in the humanoid form. Get some more weapon skill and see if that improves your critical strike chance,
