### ISSUE TITLE
Ignite damage too low

### ISSUE THREAD

**Issue by quasexort** [elysium-project/server#748]
I've been noticing sometimes crits that generate the 5 stack ignite are not being counted in the ignite damage.  For example tonight I tested this with a friend and we both attacked a mob with rank 4 fireball and tried to see what the ignite damage would be vs what we expect.

We started casting on an elite mob and the first 5 crits were 999, 804, 987, 804, 975.
The first ignite tick occurred after the first 2 crits and was 359, which makes sense (999/5 + 804/5 = 360.6).
The 2nd tick occurred after the 3rd crit and was 377, no idea how it could be this value since if you include the damage from the 3rd cirt it would be 359 + 987/5 = 556.4.

The next ignite tick was 354, which occurred after the 4th crit.  It should be 556.5 + 804/5 = 717.2.
The final ignite tick was 373, which occurred after the 5th crit.  Would expect the final ignite to tick for 999 * 0.2 + 804 * 0.2 + 987 * 0.2 + 804 * 0.2 + 975 * 0.2 = 913.8.
In general the 5 stack ignite should be at least the average of the first 5 crits and then can be scaled up by curse of elements / fire vul / nightfall.

**Comment by m-laniakea** [comment]
Are you saying the total ignite damage was not around 1828 = (999 + 804 + 987 + 804 + 975)*0.4?

> the damage from the 3rd cirt it would be 359 + 987/5 = 556.4.

**No**, not always the case. If there's an Ignite tick before the next crit, that base damage must be halved, because otherwise you will do more than 40% Ignite damage.
>  359 + 987/5 = 556.4

Is actually 359/2 + 987/5 = 376.9 ~= **377**
>In general the 5 stack ignite should be at least the average of the first 5 crits

Correct. That's what it's doing currently. 

>and then can be scaled up by curse of elements / fire vul / nightfall.

Power infusion: You want the damage of your fire crits increased by 40% and then the Ignite damage increased by 40% as well?

**Comment by quasexort** [comment]
> Are you saying the total ignite damage was not around 1828 = (999 + 804 + 987 + 804 + 975)*0.4?

I'm just saying the tick damage does not reflect what it should be.  The ticks occur every 2 seconds and should be 20% of the sum of the crits that were used to generate the ignite.  So for example if you have 2 crits that do x and y damage the ignite tick will be (x + y) * 0.2.  If you have 5 crits that create a 5 stack ignite the ignite tick damage should be (x1 + x2 + x3 + x4 + x5) * 0.2, so with a 5 stack ignite the dot damage that occurs every 2 seconds is the average of the 5 crits that generated the ignite.  In my case above the 5 stack ignite tick from the 5 crits (999, 804, 987, 804, 975) was 377 when it should be (999 + 804 + 987 + 804 + 975) * 0.2 = 913.

> No, not always the case. If there's an Ignite tick before the next crit, that base damage must be halved, because otherwise you will do more than 40% Ignite damage.

> Is actually 359/2 + 987/5 = 376.9 ~= 377

Yeah but why would you half the damage?  Shouldn't the previous ignite tick carry over and the new crit damage be applied, such that you have 359 + 986/5?  

> Correct. That's what it's doing currently.

It didn't work that way for my example above.  Since the average crit from the 5 crits was 913.8, but the 5 stack ignite tick damage was 373,

> Power infusion: You want the damage of your fire crits increased by 20% and then the Ignite damage increased by 20% as well?

Power infusion shoulrdn't scale the ignite damage up because unlike curse of elements / fire vul / nightfall, power infusion is a buff on the player whereas those are debuffs on the target.  Since ignite is a dot on the target it is scaled by the debuffs on the target.  Ignite is also not a spell that a player physically casts and therefore shouldn't be affected by things like arcane power and power infusion.

**Comment by m-laniakea** [comment]
When you're carrying over the damage, you have to take into account the fact that it's being refreshed to 4s. If you already did damage on stack 2, you have to half the amount to carry the correct damage over to stack 3. 

913 damage/tick would only be the case if all 5 crits land simultaneously. Gather more fire mages, and you'll see that that is how it's working currently. Ask another fire mage if you're unsure how Ignite works, because nothing here shows me it's not working exactly as intended.

**Comment by quasexort** [comment]
My bad, I didn't play mage in vanilla but from all the fire mages videos on youtube it seemed like the ignite should work the way I was thinking.  I guess that's because the 5 stack ignites from youtube videos are generated really quick so they don't receive this cut in damage that you describe.  If that's truly how it is suppose to work then everything is fine.

**Comment by thepparker** [comment]
No, the damage is the same as it would be on Anathema.

The first tick is 184 because 893 * 0.4 / 2 * 1.03 = 184. The second crit occurs before the second tick, so we get rollover equal to the amount of the first tick BEFORE the fire vuln modifier.

Therefore, the second tick is [893 * 0.4/2 + 440 * 0.4/2] * 1.06 = 282, which is the same as the current implementation.

**Comment by thepparker** [comment]
On Anathema the damage would be the same for the first tick, however, after the second crit and rollover it would be a bit less.

We'd have 893 * 0.4 / 2 * 1.03 for ticks on the first stack.
Then after the second crit, before the second tick we'd have 
[ 893 * 0.4 / 2 + 440 * 0.4 ] / 2 * 1.06 = 188 ticks on the second stack.

I can't explain why the tick is 282 on the second stack in Vurtne's unless it is rolling the full ignite damage, or is being multiplied by the stack count

**Comment by thepparker** [comment]
http://wowwiki.wikia.com/wiki/Ignite_(old)#Known_bugs perhaps this is why he's getting the full damage - the tick is about the same time as scorch hits.

**Comment by quasexort** [comment]
It’s rolling the previous ignite damage and not halving it.
So if someone has 5 crits that a spaced out between ignite ticks it would look like this.

1st crit is for x1 damage
Ignite tick is for x1 * 0.2

2nd crit is for x2 damage
Ignite tick is for x1 * 0.2 + x2 * 0.2 

3rd crit is for x3 damage
Ignite tick is for x1 * 0.2 + x2 * 0.2 + x3 * 0.2

4th crit is for x4 damage
Ignite tick is for x1 * 0.2 + x2 * 0.2 + x3 * 0.2 + x4 * 0.2

5th crit is for x5 damage
Ignite tick is for x1 * 0.2 + x2 * 0.2 + x3 * 0.2 + x4 * 0.2 + x5 * 0.2

Any crit after this would just have the same ignite tick as long as the crit occurs before the ignite expires.

This is how it’s working for the first 2 ignite ticks seen in vurtne’s video.  Is there any evidence that the ignite should be halving?

**Comment by GuybrushGit** [comment]
In the Vurtne video he started casting scorch before ignite ticked and finished casting after. Its one of the bugs described in the wiki link above.

**Comment by GuybrushGit** [comment]
I dont think this is explained by that known bugs wiki link, his second spell was scorch, no travel time.
Could the halving mechanic be something that was only introduced with the TBC ignite changes?
Need to find more videos where this specific situation happens.

Going through the ignite thread on EJ I dont see any mention of it:
http://web.archive.org/web/20091129094603/http://elitistjerks.com:80/f15/t7471-how_do_rolling_ignites_work/

Look at post 59 for example:
>So if JohnnyFireMage (JFM) hits the boss for 10 points of damage normally, and crits for 15 points, then an ignite worth 6 points will be put on the boss
>If JFM is able to keep his ignite 1) ticking once then 2) refreshing, his damage looks like the following:
>15 + 3 (one tick of 6)
>15 + 6 (one tick of 12)
>15 + 9 (one tick of 18)
>15 + 12 (one tick of 24)
>15 + 15 (one tick of 30)

**Comment by quasexort** [comment]
That EJ thread is really good, I remember reading it back on old nost and that's what I used for my reasoning on how ignite should work.  There's no mention in that thread of the 50% roll over penalty that currently exists on Anathema.  If ignite worked the way it does here then the EJ thread would have discussions about how you need to have 5 crits occur before the first ignite tick otherwise you would suffer from losing damage by having the none 5 stack ignite tick.

**Comment by m-laniakea** [comment]
You wouldn't be "losing" damage. Fact is, that not halving the carry-over damage after a damage tick would result in doing far greater than 40% of crit damage as intended.

**Comment by quasexort** [comment]
I'm not sure I understand.  Isn't the goal to replicate the mechanics how they were in retail vanilla?

**Comment by m-laniakea** [comment]
The goal is to duplicate the feeling of the game 10+ years ago, keeping in mind the original creator's wishes and the change over the years.

**Comment by GuybrushGit** [comment]
Found more evidence: https://youtu.be/tfoC5p9xyXc?t=551

Scorch 383 crit
First tick for 77 (383 * 0.2)
Scorch 402 crit
Second tick for 157 (77 + 402*0.2)

There was no halving. On current Elysium code the second ignite would be 77/2 + 402*0.2.

**Comment by Imbaslap** [comment]
Nano is not an accurate and/or credible source to base game mechanics off of. @m-laniakea.
the price is in the pudding so to say.

**Comment by killerduki** [comment]
You guys forgot my Video :
https://forum.elysium-project.org/topic/22298-ignite/

https://www.youtube.com/watch?v=MV_hX25_8m0

**Uploaded on Oct 30, 2006**

Everything you need 100% accurate is here.

**Comment by GuybrushGit** [comment]
That video does not help in this case but thanks I guess.

**Comment by Ausser** [comment]
Killerduki that video proves you have no idea what you are talking about.

**Comment by NanoNostalrius** [comment]
Not sure how I got dragged into this but the current code for Ignite is incorrect and this report seems accurate to me. Perhaps there was some miscommunication about what I 'approved' exactly.

**Comment by m-laniakea** [comment]
@NanoNostalrius: Joined 24 minutes ago. If it's really you, send me a message.

**Comment by killerduki** [comment]
@Ausser  @GuybrushGit   In that Video you can see how actual Ignite debuffs tick,when and how , is the main reason why i posted it.

**Comment by thepparker** [comment]
Does anyone have a video with 3 crits from a single source building ignite? I think that would allow us to confirm the behaviour.

**Comment by quasexort** [comment]
https://youtu.be/SRXUTgrZOvM?t=1231
At 20:31 the mage fights a warlock and crits him 4 times.  First two crits happen pretty much at the same time for 334 (74 resisted) and 826.  First ignite tick is for 232 = (334 + 826) * 0.2.  He crits twice again for 466 and 662 (138 resisted).  The second ignite tick is 450 = (334 + 826 + 466 + 662) * 0.2.

https://youtu.be/MlPDT_O7-aM?t=390
At 6:30 the mage gets two crits for 1305 and 912.  First ignite tick is for 443 = (1305 + 912) * 0.2.  He crits again for 543.  The next two ignite ticks are for 552 = (1305 + 912 + 543) * 0.2.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
