### ISSUE TITLE
warlock epic mount chain bugged

### ISSUE THREAD

**Issue by zmajns** [elysium-project/server#752]
After delivering xorothian stardust to gorzeeki wildeyes in burning steppes, it said I don't meet the requirements for next quest - imp in a jar, and I can't even take the quest now because the exclamation mark dissapeared

**Comment by Pleasant-Elysium** [comment]
Did you complete the other prerequisite quests for Imp Delivery? Xorothian Stardust isn't the only prerequisite.

**Comment by m-laniakea** [comment]
If you're on Elysium or Zeth'Kur you will have to wait until patch 1.4.

**Comment by zmajns** [comment]
I am on darrowshire - next quest should be http://db.vanillagaming.org/?quest=7629

**Comment by TNadal** [comment]
you also have to complete the four turn in quests, the shadow power elixirs, the large bril and dark iron ore, and the black dragonscales, and then the arcanite.

you don't have to purchase the items once everything is ready, you can have a warlock that's already purchased them do the ritual. but you do have to have completed the lead-in quests. 

once all four turnin quests are done, imp delivery will be available.
