### ISSUE TITLE
Bug  report: - Warlock/Afflication Talent Tree-Drain soul

### ISSUE THREAD

**Issue by Kruchev** [elysium-project/server#753]
Bug  report: - Warlock/Afflication Talent Tree/Drain soul ----- So i've put 2 talent points in the Improved Drain Soul talent, which should give me a 100% chance when killing an enemy with drain soul to proc a buff for 10 seconds. I've tested this multiple ways (no dots, no pet, just using drain soul) and it is clearly bugged. I've tested this by killing a mob with no pet, purely using drain soul (no dots active) and it still didnt grant the buff (while the talent, if u have 2 points in it,says its a 100% chance to grant u the buff when klilling an enemy with Drain Soul)
My ingame name is Kruchev, on Elysium - horde warlock

**Comment by TNadal** [comment]
just tested, 1/2 and 2/2 both work fine.

the mob you kill must provide XP or honor, they cannot be grey. perhaps that's your issue?

**Comment by Kruchev** [comment]
That might be it. I tested this on a grey mob. I'll test it on another and post my findings. Thanks!

**Comment by Kruchev** [comment]
Alright, I've tested this on Non-Grey mobs and it indeed grants me the buff. When my pet is spawned he can deny me the buff though, i think when the pet steals the killing blow. Is this supposed to be a feature?

**Comment by thepparker** [comment]
You have to get the killing blow

**Comment by sknnbones** [comment]
Same with Spirit Tap and in PvP.

You must get FINAL damage that kills the target, for Drain Soul/Spirit Tap/On Kill effects to activate.

**Comment by Stence** [comment]
Should work. It's just a really bad talent and I do not recommend putting points into it.
