### ISSUE TITLE
PVP gear purchasing does not check for current rank, same for entering Champions Hall

### ISSUE THREAD

**Issue by Brainzy** [elysium-project/server#761]
You should only be able to purchase PVP item with appropriate rank, right now it only checks highest obtained rank not current rank.

Same applies to entering Champions Hall.

This means when new R14 weapons are added people to need to rank to 14 (rank again if they were R14 before) so they can purchase them.

**Comment by thepparker** [comment]
This is intentional behaviour to prevent the need to have hundreds of players sitting in top brackets or on high ranks.

**Comment by Tobschinski** [comment]
[12 July 2005](http://wowwiki.wikia.com/wiki/Patch_1.6.0) - Honor system reward items with a rank requirement will now require a lifetime "highest rank" of that rank, rather than requiring the character to currently have the required rank.

**Comment by Brainzy** [comment]
@Tobschinski this only applies for usage of item, there was always a check before purchasing for rank.
@thepparker Why would you need to sit on top brackets? Once you buy the item you can use it forever.

**Comment by StadenElysium** [comment]
https://github.com/elysium-project/server/pull/764

**Comment by Brainzy** [comment]
Awesome, thank you.

**Comment by thepparker** [comment]
Some items aren't in the game yet for certain classes (such as caster weapons), but casters are ranking now with the expectation that gear will be available. This was a conscious design decision by the Nost team.
