### ISSUE TITLE
[AQ40 Anathema] Imperial Qiraji Regalia/Armaments dropping duplicates 

### ISSUE THREAD

**Issue by Slicy** [elysium-project/server#763]
**Bugged behavior** 
Imperial Qiraji Regalia/Armaments can currently drop duplicates off a single boss.
https://cdn.discordapp.com/attachments/292446170222034944/314419263551045632/unknown.png

Probably an issue with loot tables/pools in that regard.

**Correct behavior**
It should only be a chance of around 3% to drop either of these 2 for a boss kill in AQ40. A double Regalia or double Armaments drop for 1 boss should not be possible.

_"3.41% Chance To Drop. (5,344 in 156,780) Dropped By: 
Top 3 by Drop Percentage
Ouro (1)+ 6.23% (3,435)
Lord Kri (1)+ 5.43% (774)
Emperor Vek'nilash (1)+ 4.69% (11,916)
 
Ahn'Qiraj (Dungeon)
Battleguard Sartura (1)+ 3.46% (22,086) 	Emperor Vek'lor (1)+ 3.08% (9,769)
Emperor Vek'nilash (1)+ 4.69% (11,916) 	Fankriss the Unyielding (1)+ 4.30% (23,454)
Lord Kri (1)+ 5.43% (774) 	Ouro (1)+ 6.23% (3,435)
Princess Huhuran (1)+ 4.26% (23,691) 	Princess Yauj (1)+ 3.59% (2,088)
The Prophet Skeram (1)+ 1.24% (37,876) 	Vem (1)+ 4.21% (20,858)
Viscidus (1)+ 2.40% (833)"_

The (1) after each boss name is yet another hint that only 1 Regalia or Armaments drop per boss killed.

Not sure if a Regalia + Armaments from a single boss is supposed to be possible or not.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55924-development-update-04102017/
