### ISSUE TITLE
PVE Poison levels

### ISSUE THREAD

**Issue by Hosq** [elysium-project/server#765]
Currently all poison removal items work in pve regardless of the poison level while the tooltips of these items clearly state that they should only work up to certain levels.
[Anti-Venom](http://db.vanillagaming.org/?item=6452) - up to level 25
[Strong Anti-Venom](http://db.vanillagaming.org/?item=6453) - up to level 35
[Powerful Anti-Venom](http://db.vanillagaming.org/?item=19440)up to level 60
[Elixir of Poison Resistance](http://db.vanillagaming.org/?item=3386) - up to level 60

Correct behaviour would be for these to only work when mob that casted the poison is same level or lower as in items the tooltip. Which would mean that none of these work on bosses like viscidus and that would allow you to revert the custom CD you added to Elixir of Poison Resistance.

**Comment by StadenElysium** [comment]
As it happens, this was being discussed only yesterday and this was found:
```
We did him once in Silence, and it required farming lots and lots of elixirs of poison resistance.

We took turns in the guild farming that one cavein the wetlands.
```
http://leftoversraiding.org/index.php/topic/858/1/viscidus.html

**Comment by Hosq** [comment]
Well your reasoning for adding CD to the elixir was to prevent guilds from completely cheesing viscidus, so i think my suggestion would do a better job fixing that and without affecting PVP.

**Comment by thepparker** [comment]
These items don't check caster level, they check the spell level. What the correct level for Viscidus' poison bolt volley is, is debatable. I would say it's probably meant to be level 60, which would make the elixir and powerful anti-venom usable.
