### ISSUE TITLE
Delivery to Andron Gant

### ISSUE THREAD

**Issue by xzxKamixzx** [elysium-project/server#766]
Start from the Quest is Jediga.
End is Andron Gant in Undercity.

I give the quest to him (Gant), complete it but got not the next Quest  "Andron's Payment to Jediga".

He Show me "gray !" but im 50 and normaly i should can accept it.

**Comment by brotalnia** [comment]
Quest "Andron's Payment to Jediga" requires level 51.

**Comment by Tobschinski** [comment]
Should be 45, for all quests.
