### ISSUE TITLE
Lv 50 druid quest

### ISSUE THREAD

**Issue by Galathoria** [elysium-project/server#767]
Hello there, the last part of the druid quest given by Torwa Pathfinder in Un'Goro is not available. I succesfully completed the first three quest but the NPC does not give the last part(the one to Sunken Temple).

Could you check if this is a bug or a dev. issue?

Kind regards

**Comment by Sabre142** [comment]
Quest is released in Patch 1.7. If you're playing on Elysium PvP, it's not meant to be out.

**Comment by Galathoria** [comment]
Sorry for not specifying, I'm om Anathema (1.9)

**Comment by QAkvastskaft** [comment]
This quest was added in patch 1.10: http://wowwiki.wikia.com/wiki/Patch_1.10
"A new level 52 druid quest that takes place in Un'Goro crater has been added."

**Comment by Galathoria** [comment]
I could do 3 out of 4 of the chain thoguh and it started at 50, is that the same quest? I could do the class quest of warlock at 50.
