### ISSUE TITLE
Typo in text for quest Etched Note: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#770]
BUGGED BEHAVIOR
The name 'Clisha' is hard coded into the completion phrase:

'And it is my job to make sure you are prepared by teaching you the basics of our profession--how to tame your pet, how to fire your rifle, and many other skills that will become necessary.$b$bHunters are a strong part of our tradition and history, Clisha. You would do well to remember how important you are to the tribe. You will be respected and revered if you serve our people well.'

 CORRECT BEHAVIOR
The player's name should be substituted into the completion phrase. Like this:

'And it is my job to make sure you are prepared by teaching you the basics of our profession--how to tame your pet, how to fire your rifle, and many other skills that will become necessary.$b$bHunters are a strong part of our tradition and history, $N. You would do well to remember how important you are to the tribe. You will be respected and revered if you serve our people well.'

 SOURCES
Common sense and http://www.wowhead.com/quest=3092/etched-note

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/4545

**Comment by StadenElysium** [comment]
Guess we know who provided that data. :smirk:
