### ISSUE TITLE
Shard of the Flame and Shard of the Scale being unique

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#772]
These items should be non-unique until Patch 1.8

Sources:
http://wowwiki.wikia.com/wiki/Shard_of_the_Flame
http://wowwiki.wikia.com/wiki/Shard_of_the_Scale

**Comment by QAkvastskaft** [comment]
Shard of the Flame:
Before 1.8: http://web.archive.org/web/20050518085657/http://www.thottbot.com:80/?i=36927
After 1.8: http://web.archive.org/web/20060222104725/http://thottbot.com:80/?i=36927

Shard of the Scale:
Before 1.8: http://web.archive.org/web/20050426071239/http://www.thottbot.com:80/?i=36048
After 1.8: http://web.archive.org/web/20051111045408/http://www.thottbot.com:80/?i=36048

**Comment by GuybrushGit** [comment]
Fixed in new progressive database.
