### ISSUE TITLE
Polymorphed players keep moving

### ISSUE THREAD

**Issue by brotalnia** [elysium-project/server#800]
If you polymorph a moving player, he keeps running on your screen. When the polymorph is removed and the player moves, he appears at his real position.
![fhu85uqonruhc](https://cloud.githubusercontent.com/assets/6519171/26277981/54e45bf0-3d9a-11e7-9aae-edc8271e101c.gif)

**Comment by thepparker** [comment]
On live or dev?

**Comment by brotalnia** [comment]
Latest development branch, but it seems to only happen without mmaps, because if they are enabled the sheep moves around randomly and that sends an update to the player.

**Comment by thepparker** [comment]
Ah, right. Yea Unit::GetRandomPoint in ConfusedMovementGenerator will fail if it can't find a valid path and the spline will never be sent. It might be worth forcing a stop on initialization, would have to investigate.
