### ISSUE TITLE
Target dummy (the basic one) has an incorrect amount of health

### ISSUE THREAD

**Issue by Reiiama** [elysium-project/server#804]
I was fighting mobs in both Shadowfang Keep and a level 30 quest mob in Stormwind. When I set down the dummy, it immediately got aggro and died in one hit. 

According to the Vanilla wiki (AoWoW), basic Target Dummies have 770 hp, and no mob around level 30 hits for that much damage, so the HP value must be incorrect.

**Comment by GuybrushGit** [comment]
Dupe https://github.com/elysium-project/server/issues/478
