### ISSUE TITLE
Darrowshire - Mobs for the quest Rescue OOX-09/HL! are bugged.

### ISSUE THREAD

**Issue by Ripper007** [elysium-project/server#805]
Mobs that spawn during quest  Rescue OOX-09/HL! ( id 836), keeps spawning even the quest isn't running.
Marauding Owlbeast ( id 7808) and Vilebranch Ambusher (id 7809).

**Comment by Ripper007** [comment]
Hmm it seems the issue was posted in #643.

**Comment by m-laniakea** [comment]
Duplicate: https://github.com/elysium-project/server/issues/643
