### ISSUE TITLE
Darrowshire - Zul'Farrak Zombie keeps respawning.

### ISSUE THREAD

**Issue by Ripper007** [elysium-project/server#806]
The mobs Zul'Farrak Zombie ( id 7286) keeps respawning if the Shallow Graves(id) 128403 are looted and even if they are killed. They should despawn in 1 min or should not respawned if killed. 

Source: the vanilla db's comments are vague on this. for ex. "However, if you're soloing this at a relatively low level (say you're a level 46 pally) and really want to down this boss, do rob the graves. It takes time to kill all the zombies, but it needs to be done. He summons not only the little skeletons with his Totems, but also the zombies from the graves during the fight with him, starting with those graves closest to him. "
http://wowwiki.wikia.com/wiki/Witch_Doctor_Zum%27rah

**Comment by Kittnz** [comment]
yes, only like 3 or 4 i believe, not everything

**Comment by Ripper007** [comment]
It seems it was resolved in last patch ( 19.07). So I will close it.
