### ISSUE TITLE
Xorothian Stardust - Zeth'kur

### ISSUE THREAD

**Issue by deblood** [elysium-project/server#811]
hello

i had a quest from gorzeeki wildeyes where i had to go fetch xorodian stardust (it's a small chain).

i have the xorothian stardust in my bag now

when i came back to finish the quest with gorzeeki, there was an issue, i couldn't finish it

so  i discarded the quest in order to take it back & finally be able to finish it

but now gorzeeki won't give it again...

on top of the lost money (150g)  this quest  is of first importance since i need it to get dreadsteed in future release

can you help?

Thx !

**Comment by TNadal** [comment]
http://db.vanillagaming.org/?quest=7625

Gorzeeki Wildeyes sends you to banehollow. 

Banehollow has you kill someone and bring him the heart. 

Banehollow then gives you the quest xorathian stardust, and you can purchase the dust.

Then you take the quest that banehollow gave you to Gorzeeki Wildeyes. 

if you abandoned it, you're going to need to grab a shadowy potion (unless you have a spare) and go get the quest from banehollow again, not gorzeeki

**Comment by deblood** [comment]
Thanks a lot for the help !
