### ISSUE TITLE
Combustion broken

### ISSUE THREAD

**Issue by Hosq** [elysium-project/server#813]
It is possible to bug out combustion by dispelling hidden debuff which makes the game think your combustion has expired while still leaving whatever combustion stacks you had left. This makes it possible to get permanent 100% crit chance for fire spells

Also Combustion currently doesnt add any crit chance for blastwave.

**Comment by notpentadactyl** [comment]
This issue is known for a while and was disclosed (privately) to the GM team month ago, but apparently wasn't too important to be fixed. This public issue will most likely increase the priority.

Thanks for reporting. 👍
