### ISSUE TITLE
hots

### ISSUE THREAD

**Issue by flowqz** [elysium-project/server#822]
back than you couldnt overwrite hots, if the hot was healing for more per tick than yours. if you tried you got the errormessage "a more powerful spell is already active".

 doesnt seem like much, but for me it is an aspect of the game i want to have back, getting the most +heal and others not beeing able to overwrite it, letting healers strife to get the most +heal avialable.

 
the feature got removed with the bc preperation patch, after that you could just stack up as many hots as you wanted.

**Comment by thepparker** [comment]
It's based on spell rank not total healing. Other players using the same rank as you will be able override yours.

**Comment by flowqz** [comment]
i personally dont get why it got closed, but its still not working as intended.

**Comment by thepparker** [comment]
It IS working as intended. Like I said, it's based on spell rank/level, not which is ticking for the most. Perhaps you are talking about a specific spell that is not obeying the rule?
