### ISSUE TITLE
Warsong Exalted Reward: Outrider's Leggings

### ISSUE THREAD

**Issue by Bruus** [elysium-project/server#828]
Now that all other PvP rewards are ingame, including every item that should come with the Naxxramas Patch. Why are not the Warsong Exalted leggings ingame? 

It is still a challenge to get them and they are not even that incredible compared to other available Leg slot items that are ingame.

Please give me a reason why they are not ingame when all other PvP rewards are, including rank 14 caster gear that are supposed to be added in the same patch as Warsong Exalted leggings.

Thanks, hope you either give me a good answer or add them to the game.

**Comment by Bruus** [comment]
Why did someone down vote, respond instead.

**Comment by Sabre142** [comment]
Added in Patch 1.11.

**Comment by StadenElysium** [comment]
They'll be added later today.

**Comment by Bruus** [comment]
Great news, thanks
