### ISSUE TITLE
Commander Gor'shack quest 

### ISSUE THREAD

**Issue by ciacscott** [elysium-project/server#831]
I can't pick up the Commander Gor'shack quest even though i have completed the pre-requisites for the quest. 

can someone help me here?

**Comment by TNadal** [comment]
did disharmony of flame, commander gor'shack quest is currently available and working (on darrowshire)

![gorsh](https://cloud.githubusercontent.com/assets/15307219/26378227/a0367d06-3fe1-11e7-8284-81e7375a98e6.png)

**Comment by ciacscott** [comment]
I did Disharmony of flame (currently on Disharmony of Fire) and all that Galamav the Marksman will give me is "The Pack Mistress".  I am on Darrowshire also

**Comment by GuybrushGit** [comment]
Too low level maybe?

**Comment by thepparker** [comment]
Quest is currently available as intended, closing pending further information
