### ISSUE TITLE
Reckoning stacks disappear randomly

### ISSUE THREAD

**Issue by sovs** [elysium-project/server#835]
The talent Reckoning in the Paladin protection tree loses stacks randomly. You gain stacks when something crits you (this works), but you're supposed to keep all your stacks (up to 4) no matter what until you attack something or you log out.

On multiple occasions I've experienced the Reckoning stacks disappearing for no reason. There seems to be no pattern to it but it happens often enough that it's a major bother. It can happen in combat when I'm not attacking anything, it can happen out of combat.

Another thing is that Reckoning stacks always disappear after you exit a duel. I don't know if this is supposed to happen (so you can't have a friend crit you for stacks on purpose), but I thought I might as well bring it up. Losing stacks after duels is a minor thing, but losing stacks randomly while out in the world (or in battlegrounds) is a problem.

**Comment by Mostprovidedlinks** [comment]
its probably from weapon switching, I have proof its not meant to be removed when you switch weapons.
A retail player replied to me when I asked him in his 2006 video

**Comment by sovs** [comment]
It is not the weapon switching in my case.

**Comment by sacrednemo** [comment]
I lose reckoning charges when switching weapons, which did not happen in Vanilla.

**Comment by thepparker** [comment]
Duplicate
