### ISSUE TITLE
Black Lotus spawn glitch [Urgent!]

### ISSUE THREAD

**Issue by Raziya-Anathema** [elysium-project/server#839]
There is a Black Lotus node in The Hidden Grove in Winterspring on Anathema that has apparently been respawning in the same place since the server restarted for PvP rank updates. There are a bunch of farmers camping the spot now, knowing it's glitched and abusing it.

Please fix this!

Edit: I should specify that the Black Lotus spawn timer remains the same. About twenty minutes or so. It just seems guaranteed to repop in the same place. My friend has seen five Black Lotus pops in the same location before just out of sheer crazy luck, but this one has been respawning for hours now in the exact same spot. I guarantee it's glitched.

**Comment by Rose-zk** [comment]
This is currently happening on Zeth'Kur too. Several players has been seen abusing the bug.

**Comment by Raziya-Anathema** [comment]
Zeth'kur too? Hopefully this is fixed soon - I hear all spawns have been disabled until they fix the bug. What a mess!

**Comment by Rose-zk** [comment]
Not disabled on ZK - just witnessed a 10v10 ally vs horde battle for the spawn

**Comment by StadenElysium** [comment]
Fixed.
