### ISSUE TITLE
Warlock class quests bugged

### ISSUE THREAD

**Issue by Dozosensei** [elysium-project/server#841]
Server Elysium
The following quests : 
- http://db.vanillagaming.org/?quest=8421 - The Wrong Stuff (and i guess also the rest of the chain)
- http://db.vanillagaming.org/?quest=7603 - Kroshius' Infernal Core

are not given by the npc, please fix , thank you.

**Comment by Lorilay2** [comment]
Those quests were added in patch 1.8, so they should not be available on Elysium yet.
