### ISSUE TITLE
Clearcasting does not procc accordingly

### ISSUE THREAD

**Issue by Tuvaluuu** [elysium-project/server#842]
Hey guys,

Clearcasting is not working anymore as it should.

As a reference I use BRD farming where I pull over 20 mobs at once.
With 5 points in Arcane Concentration I should have a 10% chance and because this server is based on Mangos it counts the 10% for every mob.

Long story short, even with 20+ mobs I don't get the clearcast procc. In theory it should be almost impossible to not get it, but it happens and not only one time but all the time.

Best regards,
Tuvalu

**Comment by QAkvastskaft** [comment]
This was a bug and is now fixed

**Comment by Tuvaluuu** [comment]
Damn ...
