### ISSUE TITLE
Atal'ai Gloves of Frozen Wrath

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#849]
These BiS mage gloves either should not drop at all or have their drop rate significantly buffed. It is ridiculous that the best mage gloves until AQ have a ramdomly low drop rate compared to the other suffixes.

Atal'ai Gloves of Frozen Wrath on anathema: http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=10787&suffix=1971

Atal'ai Gloves of Fiery Wrath: http://realmplayers.com/ItemUsageInfo.aspx?realm=Ana&item=10787&suffix=1894

3 players vs 32

Either increase the drop chance or remove the frozen wrath option on these gloves.

**Comment by TNadal** [comment]
this is a duplicate, or complaint about: https://github.com/elysium-project/server/issues/375 which you also commented on in april =)
