### ISSUE TITLE
[Darrowshire] Panther Hide Sack from High Priestess Arlokk is not independent of other loot.

### ISSUE THREAD

**Issue by Vivenmort** [elysium-project/server#852]
When you kill High Priestess Arlokk she should drop:

1st: Primal Hakkari Item
2nd: Usual drops like Will of Arlokk, Overlords Onyx Band etc
3rd: A Panther Hide Sack, or nothing at all.

The Panther Hide Sack is supposed to occupy an "extra" or "bonus" loot slot seperate from the regular drops, similar to Bonereaver's Edge from Ragnaros. Instead, if she drops a Panther Hide Sack it actually consumes that second slot, so she will drop nothing except the sack and the usual Hakkari item.

**Comment by blubba22** [comment]
Same issue with the 4 Edge of Madness bosses.
If they drop a blue item, they only drop 1 of the quest items.
It should always be 2 quest items and the blue item in a "bonus loot slot" as stated above.

**Comment by QAkvastskaft** [comment]
https://web.archive.org/web/20060307041125/http://wow.allakhazam.com:80/db/item.html?witem=19914
Comment from 2005 suggests that bag and a primal is a possible loot.
"My guild took this guy down yesterday to only get this bag and a primal hakkari item.  Worst boss loot ever.            "
