### ISSUE TITLE
Krug Skullsplit (npc=15612) does no longer give signed field duty since the event is bugged.

### ISSUE THREAD

**Issue by SiguDS** [elysium-project/server#854]
Waited a long time at Krug Skullsplit to see if an event would happen or something but he seems just not to be giving out signed field duty papers. I have not been able to get it done since the wednesday update. Retaking the quest etc does not seem to change this.

**Comment by SiguDS** [comment]
Seems the event just tries to start but nothing comes from the hive and he just kinda stops in his tracks.
http://i.imgur.com/qmXT5nb.jpg

**Comment by SiguDS** [comment]
After the event then "reset" and stuff walked back you still could not get the field duty quest. http://i.imgur.com/qmXT5nb.jpg

**Comment by SiguDS** [comment]
Seems that the mob sometimes comes from the hive but when it kills krull the next time it doesn't show up.

**Comment by SiguDS** [comment]
Still kinda buggy it either evades or it despawns. Only 1 out of 12 events i have been able to get it done. Video to show: https://www.youtube.com/watch?v=nLWvfu7dey4&feature=youtu.be

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55357-anathema-updates-27092017/
