### ISSUE TITLE
Wisp form

### ISSUE THREAD

**Issue by jfac112** [elysium-project/server#861]
Wisp form seems to be bugged. Upon death you run slower.. not faster.

**Comment by Drakani** [comment]
Having the same issue. 
Sometimes I don't get the wisp form speed bonus at all when I'm a ghost, other times I keep it after resurrecting and run faster while alive. It's really hit or miss and I'm not sure what causes it other than something to do with dying.

**Comment by DearDevilGR** [comment]
i have the same problem !
the players are not reporting it because it is at their advantage

**Comment by StadenElysium** [comment]
Fixed.
