### ISSUE TITLE
Quest id 8735

### ISSUE THREAD

**Issue by sd5188934** [elysium-project/server#862]
Hi there,
I think one of my quests is bugged.
It is the Nightmare's Corruption.
Quest id 8735.
I have this quest in my list.
And all four needed fragments of the nightmares corruption.
But It turns out I can not turn them in to complete the quest.
Please advise me on the further steps and the solution.
Really appreciate it.
Thanks
Best regards.
nobbisme

**Comment by Sabre142** [comment]
Delete folder WDB.

**Comment by xniko** [comment]
Try depositing your quest items into your bank and withdrawing them. In some cases that refreshes the quest status completion.

**Comment by Lorilay2** [comment]
Abandon and retake the quest. Unless it's a quest item provided to you when you started the quest, it won't be deleted.
