### ISSUE TITLE
Book of Ferocious Bite V Drop?

### ISSUE THREAD

**Issue by arrowsong** [elysium-project/server#864]
This book should drop from The Beast from UBRS. Added in 1.9.0 for Anathema  server.
http://wowwiki.wikia.com/wiki/Book_of_Ferocious_Bite_V (source)

**Comment by QAkvastskaft** [comment]
This book was actually added in patch 1.12:
"Ferocious Bite: Book of Ferocious Bite (Rank 5) now drops off The Beast in Blackrock Spire. In addition, Ferocious Bite now increases in potency with greater attack power."

http://wowwiki.wikia.com/wiki/Patch_1.12.0
