### ISSUE TITLE
Druid Updates Are Back To FALSE

### ISSUE THREAD

**Issue by Chubzlol** [elysium-project/server#865]
Yesterday morning druid class issues were fixed:

- Noggenfogger Elixir and Savory Deviate Delight costumes DID NOT remove is effect after being shapeshifted. (CORRECT)

- Travel Form and Cat Form were scalling down when shapeshifted and were not too big as before.

 

BUT Today i log in and i notice that the bugs are back:

- Noggenfogger Elixir and Savory Deviate Delight costumes DID REMOVE is effect after being shapeshifted. (FALSE)

- Travel Form and Cat Form WERE NOT scalling down when shpeshifter. (are too big than it should)

 

What happened with update? Why did it reset? 

Thanks 

-Chubzlol

**Comment by StadenElysium** [comment]
Fixed.
