### ISSUE TITLE
Wetlands missing Quests

### ISSUE THREAD

**Issue by Floppixx** [elysium-project/server#868]
James Halloran should give me a Quest called "Young Crocolisk Skins". But he doesn't.
And Captain Stoutfist should give me a Quest called "War Banners". But he doesn't.

**Comment by AndersSahlin** [comment]
Are you following the vanilla guide? 

I think there's a dwarf outside the keep with a pre quest for "War Banners", not mentioned by the guide.

**Comment by Floppixx** [comment]
Yepp I do. And for "Young Crocolisk Skins"?

**Comment by QAkvastskaft** [comment]
Try: http://db.vanillagaming.org/?quest=469

**Comment by thepparker** [comment]
Aforementioned quest is a pre-req. Working as intended.

https://web.archive.org/web/20060515023223/http://wow.allakhazam.com:80/db/quest.html?wquest=484
