### ISSUE TITLE
Expose weakness (Hunt T2 8/8) consumes an arrow on proc

### ISSUE THREAD

**Issue by Zyrkmeister** [elysium-project/server#870]
When the hunter t2 8/8 set bonus procs and expose weakness is applied to the target, the hunter loses an extra projectile. Pretty sure this isn't intended.

Video: https://www.youtube.com/watch?v=Z2fsum6UNGA

Edit: 
-Tested enequipping arrows after firing a shot but before the arrow landed. Expose weakness procced, but no arrow was consumed.
-If multishot procs the effect, every single debuff consumes an arrow. So firing one multishot with 3 expose weakness procs consumes 1+3 arrows. 
Edit2:
I implemented workaround fixes to YaHT for annoying autoshot timer mess ups. Whisper Zyrkmeister ingame if you're interested.

**Comment by Lurkkihunter** [comment]
What's really annoying about the expose weakness proc is that since you lose an arrow, it resets autoshot timer in addons like rais and YaHT.
