### ISSUE TITLE
Ferocious Bite not scaling with Attack Power

### ISSUE THREAD

**Issue by ajanaa** [elysium-project/server#872]
Situation:  Tested out with 400 AP  and 1285 AP and there was literally no change in Damage. 

Current behaviour: Ferocious Bite R5 (Char from prior Elysium) and possible all other Ranks as well are not scaling at all with Attack Power.

Correct behaviour: Ferocious Bite (all Ranks) should be scaling with Attack Power
Source: http://vanilla-wow.wikia.com/wiki/Ferocious_Bite

**Comment by GuybrushGit** [comment]
https://github.com/elysium-project/server/pull/860
