### ISSUE TITLE
Items sharing cooldowns

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/server#882]
When you use a mana gem, your battle standard, whipper root rubers, night dragon's breath, dark runes, demonic runes  and conjured healthstone will all go on a 2 minute cooldown.

According to this video that should not happen.

https://www.youtube.com/watch?v=CStaLR0ipxY&t=9m13s

He uses a mana gem and his battle standard does not go on cooldown, neither does his night dragon's breath.

**Comment by thepparker** [comment]
This was before Patch 1.11, in which item category cooldowns did not exist in the state they do now. If you can find a video later than June 30, 2016 in which the standard is on a separate cooldown then it can be changed.

**Comment by GuybrushGit** [comment]
https://web.archive.org/web/20060716075304/http://www.thottbot.com:80/?i=8732
Jul. 2006

Shares cooldown with healthstones, runes, tubers, etc
