### ISSUE TITLE
Honor Bar decayed 100% and then it stand still 

### ISSUE THREAD

**Issue by Phildaph** [elysium-project/server#883]
Hi there,

Can you please help me fix these issues.  I was at Rank 12 (3 weeks ago).  I managed to collect more than 750K Honor Points that week and was promoted to R13.  For the next week I did not play BG at all as I was sick.  My Honor Bar drops 100% back to where I was at Rank 12.  Last week I collected more than 330K but my honor bar did not move at all.

I understand decay is only 20% per week, if this is true why is it my bar drops 100% from R13 back to where I was when I was R12.

Please help me understand and fix the issue.

Thank you.

**Comment by gemt** [comment]
its 20% of your total RP, not of your current rank. There are various guides to understanding this system on nost/elysium or other forums. Even wowwiki has a pre 2.0 honorsystem explanation. 

Dropping a full rank at R13 when you do no pvp is correct. Not ranking up again with 330k is probably correct, depends on how many other players are pvping, and how much honor they have.
