### ISSUE TITLE
Paladin test of righteous quest

### ISSUE THREAD

**Issue by Stamanka** [elysium-project/server#884]
I have all the items but the turn in npc Jordan Stilwell has a silver question mark above him and i can't turn it in. Dont want to abandon and retake as i think i might loose the quest items. 
Can anyone help please?

**Comment by Riorik** [comment]
I have the very same issue. Character Riorik on Elysium.

**Comment by Stamanka** [comment]
Riorik abandon the quest and retake it, the box pops up to let you know the items will be destroyed but they wont only the note telling you where to get them from goes. I have just done this on my server and now have the hammer. Good luck

**Comment by thepparker** [comment]
Duplicate, dev note: consult grey quest hand in compilation thread
