### ISSUE TITLE
BUG: Channeled spells sometimes don't tick their full duration

### ISSUE THREAD

**Issue by retNull** [elysium-project/server#887]
Ex. Mind Flay will only tick twice instead of three times.  Same with Arcane Missiles.

See thread https://forum.elysium-project.org/topic/37103-mind-flay-only-ticking-2x-instead-of-3x/

Kronos fixed this issue in Changelog 24/4/2017

**Comment by flowqz** [comment]
would be great if this would get fixed. but i guess kronos doesnt have open source?
