### ISSUE TITLE
Severe lag spikes and DCing every 5 - 15mins - Darrowshire

### ISSUE THREAD

**Issue by Toradh** [elysium-project/server#889]
This didn't happen after last nights restart in Darrowshire, but after logging on this morning I'm getting severe lag spikes every 5 mins and getting DC'd every 5-15mins

**Comment by TNadal** [comment]
I've been on darrowshire all morning, no issues. eastern US. jump in the support channel on discord.

**Comment by Toradh** [comment]
I'm in EU, have tried all the usual solutions. (Reset router, deleted WDB folder etc.)
