### ISSUE TITLE
I have had 3 quests bug when I try to do turn ins that involve items that I have put in the bank and taken out later.

### ISSUE THREAD

**Issue by Neophraz** [elysium-project/server#890]
The first time it happened, I just deleted the quest item and abandoned the quest. The second time I tried putting the item back in the bank. Didn't help. Tried zoning into the zone with the item on me. Didn't help. Tried several more times to turn it in, but the quest turn in always appears with a silver question mark, even though I have the item in my inventory. This latest time its happening on my character Bilbolagins on the Anathema server. I'm trying to turn in "Martek the Exiled" but the turn in shows a silver question mark. Even though I have the Fizzle Brassbolts' Letter in my inventory.

I think this may somehow be caused by having the item in the bank for a while and doing other quests and coming back to this one later. But not sure why.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/50445-development-update-19072017/
