### ISSUE TITLE
Are players allowed to help each other accross factions to kill off lower level players trying to quest?

### ISSUE THREAD

**Issue by Neophraz** [elysium-project/server#891]
I am in the the Badlands at Dustbowl on the Anathema server trying to quest the Rock Elementals and there is a level 60 Horde Warrior name Cleaton farming them. He kills off the alliance players that are trying to quest. That's fine, but then there is a level 60 alliance Warlock named Rumbaa that is killing off the horde players trying to quest. He also shows Cleaton where the alliance traps are that the hunters are placing. Is this kind of helping accross factions allowed so they can farm and prevent people from questing?

**Comment by Ripper007** [comment]
This is a bug report forum. And for a pvp server, i've seen worse.

**Comment by Neophraz** [comment]
Sorry, opened a ticket and thought that it told me that I had to report it here. I confused it with the fact that only bugs go here.
