### ISSUE TITLE
Reckoning shouldnt be removed when enterring portals or dueling or from dying

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#893]

**Comment by GuybrushGit** [comment]
http://blue.cardplace.com/cache/wow-paladin/1069149.htm

>Why didn't my Reckoning bomb go off? 
>The following things can cause you to drop your charges: 

> Ending a Duel 
> Mounting up (including gryphons) \*
> Autoattacking too early (e.g. from out of range) 
> Switching Continents 
> Switching Weapons 
> Losing control of your character (Fear, Scattershot, Blind, Polymorph, Mind Control, etc.) 

\* Proof mounting doesn't drop charges: https://youtu.be/Kr_inDkNPBQ?t=1332

Reset events from ReckCounter addon:

>-- Events below are for resetting ReckCounter
>this:RegisterEvent("PLAYER_LEAVE_COMBAT");
>this:RegisterEvent("PLAYER_DEAD");
>this:RegisterEvent("CHAT_MSG_COMBAT_SELF_HITS");
>this:RegisterEvent("CHAT_MSG_COMBAT_SELF_MISSES");

**Comment by thepparker** [comment]
Duplicate
