### ISSUE TITLE
Crystal of Zin-Malor should not change damage or mana drain when ressurecting. Should also keep damaging after ressurecting. Should also be unclickable

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/server#894]
The Crystal of Zin-Malor http://db.vanillagaming.org/?item=13347 
keeps changing the damage everytime I am resurrected after death, as far as retail goes. The damage and mana drain only changes when you equip or switch the item from your bags.

Proof is shown in this post Prebc video. Despite the video being an later patch the mechanics of this item were not changed. 

Proof also shows that the player is still being damage by the item when resurrecting. On Elysium the item stops damaging you when ressurecting.

https://www.youtube.com/watch?v=kBtSAjKmPPw

Fix 1 required: Make Crystal of Zin-Malor do the same damage and mana drain when resurrecting.
As you can see the character is taking 128 damage per second constantly after ressurecting.

Fix 2 also required: Crystal of Zin-Malor should remain doing damage to you when you resurrect until it is removed from you.

Fix 3: Make Crystal of zin malor an unclickable buff like in the retail video. Please change this. At the moment the buff is unremovable when you double click on it. In the retail video crystal of zin malor is working like on feenix. This will help certain classes escape traps without dying in duels.

This is how it should be https://youtu.be/HVWuW_PI1d0
See where the buff is? (not under the aura and unclickable like on elysium) its just like in the retail video 
https://www.youtube.com/watch?v=kBtSAjKmPPw

**Comment by Itembugs** [comment]
Crystal of zin malor should also be an unclickable buff like in the retail video. Please change this.

**Comment by Mostprovidedlinks** [comment]
This still has not been fixed as of 1.10

**Comment by thepparker** [comment]
Duplicate #1907. Newer post has more discussion, closing this
