### ISSUE TITLE
Compile error when building vmap_assembler on Linux

### ISSUE THREAD

**Issue by Itzamnaaj** [elysium-project/server#895]
When trying to compile the vmap_assembler tool on Linux, compilation fails with the following error:

`/home/itzamna/src/elysium-server/src/game/vmap/VMapManager2.cpp:28:19: fatal error: World.h: No such file or directory`

Steps to reproduce the problem:

1. `cd src/contrib/vmap_assembler`
2. `cmake -DCMAKE_CXX_FLAGS="-march=native -O2 -pipe -std=c++11" .` (it won't compile without using C++11)
3. `make -jX`, X being the number of threads.

Of course, World.h does exist in src/game. After changing the include in VMapManager2.cpp to `#include "../World.h"` it does find World.h, but now it complains about not finding Nostalrius.h:

`/home/itzamna/src/elysium-server/src/game/vmap/../World.h:34:24: fatal error: Nostalrius.h: No such file or directory`

I'm sure the fix will be trivial.

**Comment by Thetruecrow** [comment]
Wondering if the recent changes to extractors have resolved this issue for you?

**Comment by Itzamnaaj** [comment]
Hello Thetruecrow,

Thank you for looking into this. Sadly, when compiling with `-DUSE_EXTRACTORS=1`, I now get the following compilation errors:

`/home/itzamna/src/elysium-server/contrib/vmap_extractor/vmapextract/adtfile.h:22:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/extractor/dbcfile.cpp:22:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/vmap_extractor/vmapextract/adtfile.h:22:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/vmap_extractor/vmapextract/adtfile.h:22:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/vmap_extractor/vmapextract/model.cpp:23:29: fatal error: loadlib\loadlib.h: No such file or directory`

`/home/itzamna/src/elysium-server/contrib/extractor/System.cpp:33:31: fatal error: libmpq\mpq_libmpq.h: No such file or directory`

I had managed to fix the compilations before these commits by adding the include directories to the CMakeLists.txt files and letting CMake handle setting the include paths, which might be a cleaner way than setting relative include paths in source files (which is also how CMangos does it).

**Comment by WobLight** [comment]
my branch has working extractors for linux
https://github.com/elysium-project/server/pull/324

**Comment by thepparker** [comment]
Please use the Giperion branch to build extractors
