### ISSUE TITLE
James Hyal (2) - Not eligible for this quest

### ISSUE THREAD

**Issue by RunawayCactus** [elysium-project/server#899]
When I tried to accept James Hyal (2) to go to Theramore Isle, I was told that I was not eligible for the quest. Now I can't accept it, and the quest giver no longer even offers it.

If possible, I'd like to have the quest in my log so that I can get to questing in around Theramore.

**Comment by GuybrushGit** [comment]
Quest is exclusive with http://db.vanillagaming.org/?quest=1282

**Comment by Swishe** [comment]
I had the same issue with this. Did you find a way to unlock the Theramore quests?

**Comment by GuybrushGit** [comment]
This quest does not unlock any Theramore quests, you can't complete it because you completed Smiling Jim which closes off this one.

**Comment by thepparker** [comment]
Working as intended
