### ISSUE TITLE
Weekly Honor Update

### ISSUE THREAD

**Issue by Toschka1987** [elysium-project/server#90]
Hello

Guys, what the heck happened today during the honor update? like no one got the appropriate RP. Many people got fucked so hard. like what is going on?? please check this and give us at least a respond. I got standing 20 and got bracket 3? no way. 

I am very upset right now!!! I miss 0.71% to rank 13. This has to be a mistake.

Best Regards

**Comment by birdayz** [comment]
Github is for development, you are wrong here.

**Comment by paytime** [comment]
This is not true birdayz. All new bugreports (of any kind) have to be submitted here.

**Comment by birdayz** [comment]
Nevermind then.

**Comment by slacker3007** [comment]
From Sunday to Monday I lost ~40k+ honor points. Honor kills decreased from 1700 to 700.

**Comment by kakysha** [comment]
On Darrowshire we have rather big PvP community in which many players have [HonorSpy](https://github.com/kakysha/HonorSpy) addon installed.
And for everyone who has it the actual RP given is noticeably less than HonorSpy calculates, though addon is based on formulas from pre-2.0 PvP ranking system, so no reason to not believe it.
Furthermore, we have google docs sheet with all data exported from addon and formulas in there also predict a but more RP than given in fact.

If any GMs / admins / devs can help us to find if there is a bug it would be great.

For example, prev week (that was recalculated today) on Darrowshire we had ~1024 players with >15 HKs.
My standing was 95, I had 66505 honor. Calculating using [pre-2.0 formulas](http://wowwiki.wikia.com/wiki/Honor_system_(pre-2.0_formulas)) I must be at 55% of R8, but I am at 35% of R8.

Need to dive into server code I think. But first, wanna have an approve from admins for that week pool size.

**Comment by Tobschinski** [comment]
@Toschka1987 What server and what faction do you play on?

**Comment by m-laniakea** [comment]
Dated issue.
