### ISSUE TITLE
Field Duty (CC Rep)

### ISSUE THREAD

**Issue by Ravyd** [elysium-project/server#902]
Whatever happened to the Field Duty quests awhile ago completely destroyed the quest chain. Hundreds of people were a few badges away when Krug got completely glitched out and now requires you to kill the Hunter-Killer for every task turn in.

I finally got a group today to kill the mob and thought it would be taken care of. I made sure that I started the quest and that we weren't in a raid group. We killed him (I also didn't die) and I turned it in. I come back with another Field Duty and once again he wants me to kill it again to turn in.

Hunter Killer should be killed only once to enable task assignments.

You cannot get new assignments, killing that elite every time is completely unreasonable.

**Comment by Ravyd** [comment]
Anathema realm. Possible hotfixes: buffing krug to solo Hunter-Killer, making Hunterkiller level 1 non elite with instant respawn next to quest giver

**Comment by Saltynow** [comment]
What's the matter in putting it back to what it was before? You used to start the quest chain in Cenarion Hold @Windcaller Kaldon, ran to Krug and got your field papers signed . There was some issue, in which you had 2x Prepared Field Papers in your bag after talking to him once and you had to delete 1 to turn it finally in at Krug. Guess they wanted to fix this and sth went wrong there. Now you have the problem Ravyd just explained 19 days ago: the mob spawning (if at all) is way to strong to kill it solo, which wasn't supposed to happen over and over again anyways. This way ppl can't turn in their last field duty badges. Help out on that guys!

**Comment by Aleksxz** [comment]
Video from bug tracker : https://www.youtube.com/watch?v=pOF3rGqFAwA

Sometimes the event doesn't even launch.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55357-anathema-updates-27092017/
