### ISSUE TITLE
Ubuntu Linux Compile Guide?

### ISSUE THREAD

**Issue by LucasFormiga** [elysium-project/server#908]
Where can I find a guide that teaches how to compile the Elysium Project on Ubuntu Linux?

**Comment by SilvioDoMine** [comment]
I wish to compile into linux too.

**Comment by birdayz** [comment]
https://github.com/elysium-project/server/blob/development/.travis.yml

**Comment by LucasFormiga** [comment]
Thanks @birdayz, it worked! 👍
