### ISSUE TITLE
Quest: "Are We There, Yeti?" item drop rate

### ISSUE THREAD

**Issue by Jabark** [elysium-project/server#910]
Similar to https://github.com/elysium-project/server/issues/903

The drop rate for [Pristine Yeti Horn](http://db.vanillagaming.org/?item=12367) is supposed to be 80%, yet I've killed about 50 of the mobs and not got a single horn.

**Comment by QAkvastskaft** [comment]
http://db.vanillagaming.org is not a valid source for the drop-rate on Elysium-project servers, nor is it a valid source for the correct drop-rate during 1.12, since it is the database of another project.
This is true for #903 also

**Comment by TNadal** [comment]
the drop rate on the items for this was not 80%, and may not even have been 8%. doing this on retail was reminiscent of the troll grind in STV, and often would take several clears of the big yeti cave to complete..

**Comment by Jabark** [comment]
If that's the case then fine, feel free to close this and I'll make a mental note to avoid this quest, and the other, in the future
