### ISSUE TITLE
Red Scepter Shard Quest item not appearing on Nefarian

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#912]
Did BWL today and started the Red Scepter by talking to Vael. We had a smooth run and didn't wipe. Got there with 47 minutes left on the timer. No shard found on Nefarian. 

Here is a screenshot of the problem:
http://i.imgur.com/u4xkUr4.jpg

**Comment by m-laniakea** [comment]
Do you have a video of the run?

**Comment by kevmodrome** [comment]
It doesn't look like anyone recorded, unfortunately. I can't think of anything that I did that should have resulted in this. I read the other issue about it not appearing on his body if you wipe, but we didn't wipe at all and had a very smooth run. You can see all the worldbuffs etc.

**Comment by m-laniakea** [comment]
In that case, better luck next week. There are other conditions that must be met as well. 
Please record your next attempt.

**Comment by kevmodrome** [comment]
Not sure what you mean by that? I know that only one person can pick it up and no one even had had the quest. Anyway, if you  are certain that this is not a bug then I will close the issue.

**Comment by m-laniakea** [comment]
It may be a bug, but I would have to see a continuous video of the quest to be certain.
