### ISSUE TITLE
Viscidus wont die after breaking 3rd time

### ISSUE THREAD

**Issue by Hozar1** [elysium-project/server#913]
Viscidus should die after being shattered when he is low enough %, but he starts absorbing and missing.

https://www.twitch.tv/videos/147159331

This has happened twice, have more footage.

**Comment by webdkpthroaway** [comment]
This is intended, the only way to kill Viscidus is to freeze him and shatter him WHILE he is below 5% hp.

https://youtu.be/XRRE4EM9yT0?t=278

**Comment by Hozar1** [comment]
If you checked the video i linked we froze him @ 1% and shattered him.

**Comment by smkrus** [comment]
I think there is an issue with getting him too low causing final melee attacks that would otherwise shatter him to be "absorbed," which do not trigger shatter.

**Comment by Hozar1** [comment]
Seems like when it is at 1% it doesn't distinguish between melee hits that will shatter him and random damage and just absorbs everything.
