### ISSUE TITLE
Shadowmeld

### ISSUE THREAD

**Issue by gmkhano** [elysium-project/server#914]
Shadowmeld not working proper, you should be able to do a full cast while in shadowmeld.

12:05 in
https://www.youtube.com/watch?v=FIprcu4SNcA&t=476s

**Comment by GuybrushGit** [comment]
Video is from Nov. 2005: http://www.warcraftmovies.com/movieview.php?id=9569

Should be a similar fix to https://github.com/elysium-project/server/pull/682

**Comment by WobLight** [comment]
from path 1.10 changelog
` Stealth and Invisibility effects will now be canceled at the beginning of an action (spellcast, ability use etc...), rather than at the completion of the action. `
