### ISSUE TITLE
The Way of the Weaponsmith

### ISSUE THREAD

**Issue by Hygnx** [elysium-project/server#918]
"The Way of the Weaponsmith" quest seems to be broken. I smithed
Moonsteel Broadsword: 4/4 (Complete)
Massive Iron Axe: 4/4 (Complete)
Heavy Mithril Axe: 2/2 (Complete)
Big Black Mace: 2/2 ( Complete)
My quest log shows the quest as complete. I have all 12 weapons in my inventory, but the quest NPC 'Ironus Coldsteel' has a grey question mark above his head, and when I try to turn in the quest the 'Continue' button is grey as well.

![wowscrnshot_052817_215942](https://cloud.githubusercontent.com/assets/28201105/26536302/e3968694-43f2-11e7-8162-28b4076a5e53.jpg)
![wowscrnshot_052817_215946](https://cloud.githubusercontent.com/assets/28201105/26536303/e39b3a40-43f2-11e7-8dd7-6543e1d94d49.jpg)
![wowscrnshot_052817_215949](https://cloud.githubusercontent.com/assets/28201105/26536304/e3a0c50a-43f2-11e7-8083-c4b5f66df2e9.jpg)
![wowscrnshot_052817_215952](https://cloud.githubusercontent.com/assets/28201105/26536305/e3aa6f38-43f2-11e7-9cd3-efd143e874f5.jpg)

**Comment by Aorynn** [comment]
Have you tried putting your quest items into the bank and withdrawing them?

**Comment by Hygnx** [comment]
That worked. I took the items from my inventory, put them in the bank, logged out and back, retrieved the items form the bank and was able to turn in.
