### ISSUE TITLE
Bride of the Embalmer (Darrowshire PvE)

### ISSUE THREAD

**Issue by Slynkyr** [elysium-project/server#919]
Myself and several people I was with had a problem with this quest, which involves clicking on the grave of Eliza, killing her, and then looting a quest item.  We had all tried to solo the quest at earlier times and failed, and when we tried to redo the quest in a group we were unable to click the grave to restart it.  Several people tried abandoning the quest and going back to Darkshire to reacquire it and, though they were able to get the quest again after abandoning it, they still could not click the grave to start the quest.

Two of us waited at the grave and were eventually able to complete the quest by grouping with someone who was trying the quest for the first time and was able to click the grave and start it.  After killing Eliza, we were all able to loot the quest item and complete the quest.

EDIT:  I originally reported this using the in-game ticket system and I received in-game mail from a Game Master asking me to document the bug here on Github.

**Comment by GuybrushGit** [comment]
Quest http://db.vanillagaming.org/?quest=254 should be repeatable, but before something needs to be done to prevent multiple Elizas from spawning.

**Comment by Slynkyr** [comment]
Not sure what this means exactly, if you're saying this is intentional to prevent double-spawns or that it is a problem and needs to be fixed.  Either way, people are still having trouble with it and complaining about it in chat, looking for others who have the quest to group with them and click the grave. The quest you have linked is indeed repeatable and starts at the grave, however it can't be started or repeated if you can't click the grave.

Several days ago someone was also asking for help in chat claiming there were 2 Elizas and was looking for a high level person to come and help kill them. (I did not personally witness the 2 Elizas)
