### ISSUE TITLE
Non-damage sources consume Improved Shadow Bolt charges

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#920]
Bugged behavior:
Spells such as Fear and Curse of Shadow will consume improved shadow bolt charges.

How it shoud work:
Spells that do not deal direct damage should not consume charges from this debuff.

Recorded a small clip below where you can see it:
https://vid.me/CoZh

Edit: I don't remember this happening some weeks ago but I might be wrong. Maybe something that was fixed in the last update accidently broke this?

**Comment by GuybrushGit** [comment]
Can't seem to reproduce this on dev.

**Comment by GuybrushGit** [comment]
Nvm figured it out, consumes a charge when the fear resists.

**Comment by kevmodrome** [comment]
On live it's consuming charges when i refresh fear as well. Also when I put on CoS. Corruption does not seem to consume a charge when applied to the target though.

**Comment by sknnbones** [comment]
I'm fairly certain my Lupos has eaten Shadowbolt Vuln charges before with a Warlock in group...

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/44683-development-update-19042017/
