### ISSUE TITLE
Divine shield and blessing of protection doesnt work if im sitting against stuns

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#923]
I have been stunned and attack by a rogue and this stupid bug happens. Before I die I am spam clicking bubble 4 times and it refuses to work and then I die. It says this in the screenshot. I am supposably sitting form my drinking. Please fix this Divine shield should activate regardless if im sitting or standing and stunlock should force me standing. When I was stunned I stood up.

This is happening against all stuns. On all other private servers this is fixed

two fixes can be done, make it so its impossible to sit while stunned, or make it so bubble can work anytime you are sitting or standing

Fix: please let bubbles work even while sitting or prevent ability to sit while stunned text, Thanks 

http://i.imgur.com/63rucYV.png
http://i.imgur.com/nZyXU2L.png

Bubble makes you invulnerable to all spells when you use it. 

I think the best fix is what thepparker said. To make it so we can use bubble while sitting

**Comment by thepparker** [comment]
Stuns correctly make you stand when applied, and you can cast spells with no issue. 

I'm guessing you /sit to gain reck stacks or something whilst stunned. The client does not check to prevent /sit while you are stunned and even if we were to stop the /sit being applied server-side, the client would still think you are sitting and therefore prevent you from casting. It might be worth correcting the client state though if someone does try to /sit while stunned.

**Comment by ImperfectCell** [comment]
The funny thing is it happened to me too and I didnt /sit lol

**Comment by Mostprovidedlinks** [comment]
I was actually drinking

**Comment by thepparker** [comment]
The client blocks the Divine Shield cast while sitting, not the server, so there is nothing we can do about that. I find it hard to believe you were drinking and then stunned without being considered standing, unless you started drinking right as the stun was applied. But again, that's a client side check.
