### ISSUE TITLE
Not recieving Onyxia/Nefarian Buff in Orgrimmar..?

### ISSUE THREAD

**Issue by kallenavn** [elysium-project/server#924]
Ever since I created my character, now lvl 58, I have not recieved the dragonslayer buffs? I am perfectly positioned around the statues/heads, infront of bank, every1 gets but not me..I always get them on my other characters, but not on priest. Mounted, dismounted, standing still, running..nothing works..I've probably lost about 20 heads so far..Whats going on?

**Comment by Haiwuu** [comment]
Hey, this is usually due to not having high enough reputation with orgrimmar/sw.

**Comment by Spaztick** [comment]
Is this is to prevent enemy faction members from acquiring the buff in enemy cities, or instead a "flavor" mechanic?

**Comment by Haiwuu** [comment]
Players usually hit the required reputation through questing, can't really say why its a requirement.
