### ISSUE TITLE
[Viscidus] Should take reduced damage

### ISSUE THREAD

**Issue by smkrus** [elysium-project/server#925]
Mage Frostbolt (rank 1) doing about 28 damage
https://www.youtube.com/watch?v=xfoeVJj5QOg

Hunter Auto Shot doing about 150-180 damage
https://www.youtube.com/watch?v=mYOqqOjLU_c
https://www.youtube.com/watch?v=QspWtDufeZ0

Appears to be around 1/2 - 2/3 reduced

**Comment by GuybrushGit** [comment]
He's taking reduced damage already, 50%: http://db.vanillagaming.org/?spell=25994
