### ISSUE TITLE
Oily Blackmouth can't be fished (darrowshire)

### ISSUE THREAD

**Issue by mankrik** [elysium-project/server#930]
The Oily Blackmouth fish seems to be out of any loot table. Leveling fishing from 0 to 150 lets you go from no alchemy fishes at all, directly to firefin snappers, that are the next tier alchemy fish. Tested in Barrens coast, Ashenvale coast by Zoram and Booty Bay. Apparently as schools of fishes were removed, oily blackmouths were not added to fishing looting tables.

**Comment by m-laniakea** [comment]
It can certainly be fished; it's just a matter of knowing where. However, it seems the locations are highly imbalanced in favour of the Alliance.

**Comment by mankrik** [comment]
@m-laniakea so you tried in barrens ashenvale and booty bay and got some with fishing? If not please, tell us where you got some on the hook. Thanks

**Comment by sknnbones** [comment]
Booty bay - Yes

Westfall river - yes

Barrens - No (lots of deviate though)

**Comment by mankrik** [comment]
@sknnbones so you got a lot of deviates in Barrens aye? Maybe try fishing in the sea next time, there is a place called Ratchet, you should check it out.

**Comment by sknnbones** [comment]
@mankrik I went to barrens to get deviate fish, but noticed I had caught a few oily as well after getting about 45 deviates (2 hours farming)

Westfall has much better rates (20-40 oily per hour)

**Comment by mankrik** [comment]
@sknnbones strange, as far as I know deviates are found in ponds and blackmouths in open sea

**Comment by sknnbones** [comment]
@Mankirk before pools, you could
fish Oily in westfall river (and currently still can) I've had zero catches fishing the ocean in Westfall, only the river has given me Oily.

Deviates spawn in all ponds in Barrens, and in Wailing Cavern pools.

**Comment by Slynkyr** [comment]
This has been a real problem for me (Alliance side), but I found some useful info on the Elysium forums. The real vanilla had them in the sea, but Elysium seems to have removed them from the sea and put them in inland waters for some reason. Easiest place for Horde to get them would probably be the river in the Hillsbrad Foothills.  I fish them south of the road, about halfway between the road and the sea (56,48 if you have coords).

**Comment by Lorilay2** [comment]
Oily Blackmouth are sea fish, but are incorrectly on loot tables for rivers & lakes currently.

**Comment by mprto** [comment]
Confirmed - I fished oily blackmouth out of the river in northern stranglethorn after swimming downriver from westfall. I started fishing as soon as I entered the zone and caught several oily blackmouth.
