### ISSUE TITLE
Spectral type mobs immunity part 2: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#932]
Here is a list of 3 spectral/ghost type mobs that I missed last time #704
They should have the following immunity mask (WIP and up for discussion, for example do we need mask 1 CHARM, 65536 POLY and 131072 BANISH, or is that already handled due to the Undead tag of these mobs?)

2 CONFUSED
4 DISARM
16 FEAR
512 SLEEP
8192 KNOCKOUT
16384 BLEED
8388608 HORROR

mask = 8413718

List:
Lady Moongazer				2184
Anaya Dawnrunner				3667
Wailing Spectre				12377

**Comment by GuybrushGit** [comment]
Charm / Poly / Banish masks are not needed, they are not valid targets.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/50445-development-update-19072017/
