### ISSUE TITLE
Incorrect quest availability: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#933]
Bug:
The following quests should have prerequisites:
http://db.vanillagaming.org/?quest=122
and
http://db.vanillagaming.org/?quest=124

Correct behavior:
Quest http://db.vanillagaming.org/?quest=122 should have quest http://db.vanillagaming.org/?quest=118 as a prerequisite.
Quest http://db.vanillagaming.org/?quest=124 should have quest http://db.vanillagaming.org/?quest=118 as a prerequisite.

Sources:
The dragon scales are meant to pay for the shoes if you read the quest lore.

Also discussions here: http://web.archive.org/web/20070409134837/http://www.thottbot.com:80/q122 
"
HELP!
Score 1.1     Vote: [-] [+] by devilsaur, 1.5 years ago
Hey, im a 17 NE druid and all this dude gives me is the quest: "The Price of shoes" and I looked at the quest seires for "The Price of Shoes" and "Underbelly Scales" isnt mentioned. 

What are the prerequisits for this Quest cos the reward is awsome for my Feral (shapeshift speced) druid! 

Moonwind 17 druid Crushridge
  Report  Replyok, relpy from quest
Score 1.0     Vote: [-] [+] by fellar, 10.5 months ago 
Last edit: 10.5 months ago
while this may have been long time  since u posted  your question, just for future references, i found that when i spoke to the guy vern, for the under belly scales, i had to do the price of new shoes first in order to get the  scales quest first from the same guy, hope this helps ppl, =)
"

and http://web.archive.org/web/20070409032719/http://www.thottbot.com:80/q124
"
Can't get the quest!
Score 0.00     Vote: [-] [+] by uigrad, 1.5 years ago
I'm standing right in front of Verner Osgood, but he doesn't have an '!' of any color. 

I'm level 17, so I should meet the minimum requirement.  And, I haven't done the quest yet.  I can't figure out why I can't get it!
  Report  ReplyGoldshire
Score 4.7     Vote: [-] [+] by Hayrab, 1.5 years ago
There is a quest you get that asks you to run an errand to goldshire this is a pre requisite for this quest.
"

**Comment by GuybrushGit** [comment]
Was this fixed already? The prerequisites are there.

**Comment by QAkvastskaft** [comment]
You are correct
