### ISSUE TITLE
Book Of Ferocious Bite V Doesnt Drop

### ISSUE THREAD

**Issue by Thebro1** [elysium-project/server#939]
Hallo,
So I was sent here by GM Perembula. Basically the problem is that the item Book of Ferocious Bite V doesnt drop from the boss it was supposed to. Gm said its in the game files. Does it go in game in a later patch?

**Comment by Sabre142** [comment]
http://wowwiki.wikia.com/wiki/Book_of_Ferocious_Bite_V

Added in Patch 1.12.0.
