### ISSUE TITLE
[Quest] Chapter III of "The Green Hills of Stranglethorn" chain has a little typo

### ISSUE THREAD

**Issue by Nelythia** [elysium-project/server#941]
Basically only missing a space between 21 & and.

"Bring pages 18, 20, **21and** 24 of Nesingwary's The Green Hills of Stranglethorn to Barnil Stonepot in order to complete Chapter III. "

Typo exists ingame and on db.vanillagaming.org too
http://db.vanillagaming.org/?quest=341

**Comment by some2** [comment]
AFAIK this typo existed on the official servers too. So i'm interested if this will be fixed on Elysium.
