### ISSUE TITLE
Rogue combo points

### ISSUE THREAD

**Issue by adura90** [elysium-project/server#943]
Rogue combo points should not be lost when deselecting a target. You can see in this video from World of Roguecraft where the rogue fights the infamous Maydie that he does not lose his combo points when he un-targets him after the blind. [ Time: 0:52 ] [ Video: https://www.youtube.com/watch?v=d7JYsuRD0nY ] [Note: This video is dated from 2007 and I'm certain that we all know the WoRC series. Maydie was, if I remember correctly an infamous Grand Marshal from the US server Arthas. Popular for his video with the Rammstein Feur Frei soundtrack. If this isn't enough proof, I have more videos lined up for you guys.]

**Comment by m-laniakea** [comment]
Deselecting is not the same as switching targets. Provide the mentioned evidence, please.

**Comment by adura90** [comment]
I've edited my comment to match the evidence in the video. Looking for more evidence to prove the second part of my comment.

**Comment by thepparker** [comment]
Combo points are correctly being retained on target deselection, as per patch 1.4.0 
> Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected. 

And as you have discovered, the points are correctly being dropped on target change (including targeting yourself).

**Comment by adura90** [comment]
Thank you.
