### ISSUE TITLE
Possible bug with Ultra-flash Shadow Reflector on Emperor Vek'lor

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#949]
Yesterday I was tanking Vek'lor and tried using my Ultra-flash Shadow Reflector. It doesn't seem like it was working. Not sure if this is correct or not. Tried looking around but any information I find is just about the +20SR on the trinket and not the actual use effect.

Here is the combat log:
5/31 19:16:27.314  Myakaa gains Shadow Reflector.
5/31 19:16:27.893  Emperor Vek'lor's Shadow Bolt hits Myakaa for 1066 Shadow damage. (3198 resisted)
5/31 19:16:28.654  Myakaa gains 39 Mana from Prassel's Greater Blessing of Wisdom.
5/31 19:16:29.137  Myakaa's Searing Pain crits Emperor Vek'lor for 1156 Fire damage.
5/31 19:16:30.357  Emperor Vek'lor's Shadow Bolt hits Myakaa for 1046 Shadow damage. (3137 resisted)
5/31 19:16:30.839  Myakaa's Searing Pain crits Emperor Vek'lor for 1137 Fire damage.
5/31 19:16:32.210  Shadow Reflector fades from Myakaa.

**Comment by dagochen** [comment]
Cant prove it but I guess all (or most) boss spells were not reflectedable, since a player did use that trinket against Emeriss and killed him during the 25% phase spell ;)

**Comment by gemt** [comment]
Not sure how the engineering reflectors are implemented (as in what part of the code decides what can be reflected, and what cannot be), but many spells, primarily boss spells have a not-reflectable attribute in the dbc files, so if the core properly support this attribute, and the shadow reflector is implemented correctly, and this spell has this attribute (which it probably has, since its a boss spell), then it should be correct.

**Comment by kevmodrome** [comment]
It does make sense to me that most boss skills are not reflectable, at least the AoE ones or spells such as C'Thun's dark glare. I'm not so sure what I think about spells such as Vek'lor's Shadow Bolt that is cast continuously.

**Comment by GuybrushGit** [comment]
Vek'lor's Shadow Bolt is not reflectable.

**Comment by kevmodrome** [comment]
Was this the case back in retail vanilla as well? Would be interesting to know which spells it applies to. Does it apply to all spells from bosses?

**Comment by gemt** [comment]
It most likely was as the spell has AttributesEx2 flag 0x4 (can't be reflected, just checked). As I said, most boss spells have this flag.
