### ISSUE TITLE
esES language it's not complete.

### ISSUE THREAD

**Issue by Locario** [elysium-project/server#950]
Hi all.

There are numerous columns in tables as:

creature_ai_texts
db_script_strings
locales_goosip_menu_option
npc_text
locales_pagetext
locales_points of interest
mangos_string

without traslate complete esES language

Here it's the sql files with "update" statement to update loc6 in each table to have a 95 % complete esES traslation done.

Can anyone merge with the actual db?

tnx

Link: (posts down)

**Comment by brotalnia** [comment]
Did you check that the entry id's actually match those in this update? Just because the table names are the same, doesn't mean the content is the same. Especially for things related to scripts.

**Comment by Locario** [comment]
Match id with tables, and match column names. You can check yourself if you want.

**Comment by brotalnia** [comment]
The link you pasted requires a decryption key.

**Comment by Locario** [comment]
omg, later fix it, i'm out, thanks for help

**Comment by Locario** [comment]
here is:

https://mega.nz/#!WBZSgJza!WGsQ8mER1-5iNKwTYJvb11FNQHsbDMTuvvAWkG4zT68

tnx

**Comment by paytime** [comment]
You might as well just make a proper pull request. But yes, translations in general are pretty bad atm, like german.

**Comment by Locario** [comment]
How i can do a pull request for a sql files?

I'm total newbie here.

**Comment by StadenElysium** [comment]
Translations are a *very* low priority for the project. If somebody wants to do the work of translating and merging them with the database though, we'd accept them.

**Comment by Locario** [comment]
I have this database:

https://github.com/elysium-project/database/pull/3

And i merged my esES translation.

The question is : how it's supposed i need to export all this "World" DB to be accepted as PR? What program i need to use?

Thanks for help
