### ISSUE TITLE
Abusing blitchy jump spots in WSG

### ISSUE THREAD

**Issue by Centishade** [elysium-project/server#955]
Is this against the rules? If not it should be it's disgustingly anti-fun and repetitively boring just makes me leave and hope to not have to play with someone who abuses glitches in the game.  Playing WSG fairly and normally is too hard or what?

**Comment by Unknown-as-Captain** [comment]
Either make a ticket or provide more info on which these spots are, I don't know what are you trying to accomplish with this issue

**Comment by thepparker** [comment]
Not relevant to development
