### ISSUE TITLE
Channeled spells have binary resists instead of partial resists per tick.

### ISSUE THREAD

**Issue by Spaztick** [elysium-project/server#957]
The issue was tested with Mind Flay and confirmed from other players for other channeled spells (e.g. Arcane Missiles, Drain Life).

Mind Flay has binary resists; it is either full resist and a canceled cast or full damage, compared to instant spells or spells with cast times which do partially resist. Mind Flay should channel and have partial resists occur, instead of a binary resist.

Rank 1 mind flay tests on a paladin with 220 shadow resist, done by a priest with no spell penetration and 15% spell hit (10% from shadow talents, 5% gear) resulted in 14/22 mind flays being fully resisted, 8 full damage, 0 partial resists.
http://i.imgur.com/Pnua4he.jpg

For comparison here is same targets and subjects for rank 1 Mind Blast where ALL Mind Blasts hit but were partially resisted or resisted and resulted in zero damage, with no full resists:
http://i.imgur.com/4nSn8J0.jpg

**Comment by Pleasant-Elysium** [comment]
Can you provide evidence that mind flay should be partially resisted from vanilla sources?

**Comment by Spaztick** [comment]
After reviewing retail vanilla footage and what documentation I could find it appears channeled spells **don't** partially resist after all, Arcane Missiles being the exception. It would not be "Blizzard-like" to make it behave like a channeled DoT, although why they decided to do it with Arcane Missiles and not any other channeled spell is an odd choice.
