### ISSUE TITLE
Cenarion hold infantry in Cenarion Hold cause push back in air when using blessing of protection - paladin

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#959]
Cenarion hold infantry in Cenarion Hold cause push back in air when using blessing of protection or divine shield

blessing of protection says im immune to all their physical attacks except Im being pushed and lifted in the air to the left and right unable to walk. 

Fix this please. This physical attacks shouldn't affect me

**Comment by GuybrushGit** [comment]
Whats a push back in air? A knockback?
BoP doesn't make you immune to knockbacks.

**Comment by theloras** [comment]
they do it against divine shield as well

**Comment by Mostprovidedlinks** [comment]
BoP makes you immune to all melee. the guards are pushing me in the air with it

**Comment by Mostprovidedlinks** [comment]
A knockback is physical.
BoP works on it

**Comment by Mostprovidedlinks** [comment]
Fix this please

**Comment by Mostprovidedlinks** [comment]
I think this has been fixeds, can anyone make sure of it?
