### ISSUE TITLE
Hammer of justice should work on Vanish

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#960]
Currently in many duels vanish has been causing rogues to not be stunned.

http://db.vanillagaming.org/?spell=27617

stuns arent movement impairing effects and should be stunning the rogue

https://www.youtube.com/watch?v=W9bKOW4q1M8&t=3m
https://www.youtube.com/watch?v=1ENX4QnpOJw&t=0m49s
It works on root and snares/slows. (movement impairment)
roots,nova etc

wotlk database shows
http://wotlk.evowow.com/?spell=18461
Apply Aura: Mechanic Immunity (Rooted)
Effect #2	Apply Aura: Mechanic Immunity (Ensnared)

stuns and movement are separate as you can see
http://db.vanillagaming.org/?item=20013

there is no indication that this should allow a rogue to be unaffected by stuns since it is not considered a movement impairing effect such as a slow or a snare

Edit Yes Vanish is preventing stuns from landing on the rogue. Rogues should be stunned while vanished. There is no indication or proof that it shouldnt. Show me facts yet they dont exist in the form of stuns, only movement impairment.  No evidence to prove it should and I have provided evidence such as the evidence in the tooltip and the database.

Conclusion: Just because Vanish works on these spells (Root/snares/slows. (movement impairment)
Doesnt mean it works on ALL spells.

**Comment by GuybrushGit** [comment]
Vanish is not preventing stuns, at least not in dev.

**Comment by Mostprovidedlinks** [comment]
Rogues should be stunned while vanished. There is no indication or proof that it shouldnt.

**Comment by ImperfectCell** [comment]
I agree. Until theres actual evidence then this should be changed. Rogues being immune to non movement impairment effects make NO SENSE.

**Comment by Itembugs** [comment]
Can't believe this hasn't been fixed yet.

**Comment by thepparker** [comment]
How many accounts do you have?

**Comment by GuybrushGit** [comment]
Vanish is not preventing stuns, give steps to reproduce.

**Comment by taurenrogue** [comment]
> Vanish is not preventing stuns

Shouldn't it tho :)
https://youtu.be/1C7Uvt_0oYs?t=269

**Comment by stesve** [comment]
I remember the "fix vanish" and "vanish is bugged" posts from the official forums. Usually the reply was: Latency.
