### ISSUE TITLE
Game message spam - You are dead

### ISSUE THREAD

**Issue by twinkletose** [elysium-project/server#961]
Whenever I die I am spammed with the red text "You are dead" message. Similarly whenever my pet dies I am spammed with the red text "Your target is dead" message.
I disabled all addons and even deleted all my game files and reinstalled the whole game. Still getting the message

http://i.imgur.com/m1uyhj8.png

**Comment by GuybrushGit** [comment]
This is related to the hunter tier pieces 5 set bonus.

**Comment by twinkletose** [comment]
ok that makes sense, thank you. time to upgrade a slot to dragonstalker xD

**Comment by thepparker** [comment]
Resolved
