### ISSUE TITLE
Oozing Bag not dropping from Felwood Tainted Oozes

### ISSUE THREAD

**Issue by Darkallor** [elysium-project/server#968]
The Tainted Oozes should be able to drop Oozing Bags with a chance to drop Disgusting Oozlings yet I have killed easily over 150-250 with 0 drops. Please help?

**Comment by robmonte** [comment]
Unfortunately it's just an annoyingly uncommon drop. I've done the quest on multiple accounts, keep at it.

**Comment by m-laniakea** [comment]
Also, the item you're after was added in a later patch. Disgusting Oozeling isn't in the game until Patch 1.9.

**Comment by Darkallor** [comment]
Oh I see, but can it drop from tainted oozes in felwood? Because tats how I farmed it in retail



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by m-laniakea** [comment]
@Darkallor If you're on Patch 1.9, that should be the case. 
Are you on that Patch?

**Comment by Darkallor** [comment]
I'm on nostalius aq just came out I think that's 1.9?



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by robmonte** [comment]
I apologize, I didn't read the question carefully enough and was thinking of another item. Disregard what I said!

**Comment by sknnbones** [comment]
I swear I've seen players on ZK with oozling

**Comment by thepparker** [comment]
Added later
