### ISSUE TITLE
Manual of Eviscerate IX

### ISSUE THREAD

**Issue by Shadelay** [elysium-project/server#970]
Hello, I asked the GM's about Manual of Eviscerate IX, GM Perembula specifically, and he said that it is in the game files and should be in the game as of this patch, but it is not dropping from the mobs it is supposed to, can we please have this put into the game? I would like to beat furies in my guilds raids that have their new ability lvls from AQ.
    In a ticket GM Perembula said he killed 50 of the blackhand assassin's it drops off of and did not get one, then directed me to come here and post about it. Thanks for taking up my issue.

**Comment by QAkvastskaft** [comment]
This is Invalid:
from patch 1.12 patch notes:
Eviscerate: Manual of Eviscerate (Rank 9) now drops off Blackhand Assassins in Black Rock Spire. In addition, Eviscerate now increases in potency with greater attack power."
http://wowwiki.wikia.com/wiki/Patch_1.12.0

**Comment by Shadelay** [comment]
What are you saying, it is in the game?

**Comment by Shadelay** [comment]
He killed 50 and did not get one, I have never seen one for sale or drop either

**Comment by m-laniakea** [comment]
Not supposed to drop.

**Comment by Shadelay** [comment]
wow. so fucked
