### ISSUE TITLE
Night Elf Zone Quest Bug

### ISSUE THREAD

**Issue by Heradsinn** [elysium-project/server#972]
This is regarding the quest chain where you fill vials in the moonwells, called "Crown Of The Earth". The bug is that the lore/ story part doesn't appear. As I remember it, some ghosts are supposed to appear to tell you a story, but they just never show up. If anyone else has this issue too, lemme know! :)

**Comment by GuybrushGit** [comment]
The ghosts you're thinking of are from a later patch: 
http://www.wowhead.com/npc=34585/shade-of-the-kaldorei#comments

34585 is far too high to be from vanilla

**Comment by Heradsinn** [comment]
Well that's odd, because the quest givers say and act as though the ghosts did exist. They say stuff like "what you have now learnt" and they say stuff in a way as if someone has already said something (which nobody has).
