### ISSUE TITLE
Items disappearing when picking them up from the mailbox after they are returned from AH

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#974]
So this has happened a couple of times now to me. I put up a lot of the same item in stacks of 1. When the auctions expire I go to pick them all up from the mailbox. I see the items being there and I start picking them up. It all looks good and then suddenly either the stack disappears without a trace or it looks like it's there but when I try to move it nothing happens.

This first happened a couple of months ago when I had about 130 Yellow Power Crystals up in stacks of 5 and went to pick them up after they had expired. Once the stack reached 100 it disappeared and I ended up with something like 30 left. I was on auto pilot mode and chalked it up to being tired and not noticing I had actually sold them etc.

But then now it happened again just a couple of days ago. I put up 14 Guardian Stones and they all expired. Went to the mail box to pick them up. All seemed fine until I notice I couldn't pick them up. I relog and they're all gone.

I've tried to recreate the bugs in a number of ways but haven't been able to yet. I talked to someone in the support channel on discord that had experienced the same thing.

Maybe related to #372 but it doesn't sound exactly like the issue I've been having.

**Comment by StadenElysium** [comment]
Are you using any mail addons?

**Comment by kevmodrome** [comment]
Most recently it happened when I was using Postal, first time I did not have an addon. The items just disappeared when put in the bag.

**Comment by kevmodrome** [comment]
Closing this, my memory seems to be mistaken - this is most likely an addon issue: https://github.com/shirsig/postal/commit/36785c4e9bd9d98486c89f6800ddccc06d570e48
