### ISSUE TITLE
Warlock mount quest Xorothian stardust bug

### ISSUE THREAD

**Issue by shoemaker924** [elysium-project/server#976]
I've acquired the xorothian stardust for the quest and the NPC wont let me complete it, he still appears with a grey ? above his head. The quest is "completed" in my quest log. All other quest in the chain so far have been completed. I do not want to drop the quest and pick it up again, the quest item would be deleted and costs 150g
![untitled](https://cloud.githubusercontent.com/assets/29179282/26763670/a57fe9b8-4924-11e7-828c-a03ca3d5e823.png)
![2](https://cloud.githubusercontent.com/assets/29179282/26764642/63bbce7a-4938-11e7-84fb-dd3938dde6f6.png)

**Comment by shoemaker924** [comment]
![2](https://cloud.githubusercontent.com/assets/29179282/26763767/1f62e0ee-4927-11e7-880f-ea3e8557da21.png)

**Comment by thepparker** [comment]
Possibly fixed
