### ISSUE TITLE
Max range (melee)  increases the ceiling of aggro gain? Server bug or just KTM addon?

### ISSUE THREAD

**Issue by vindruvor** [elysium-project/server#980]
VoD: https://www.twitch.tv/videos/149483694

1:12:25  you see that everyone is relatively far away from AGGRO GAIN on KTM (black window at the right part of the screen). However when I walk closer to Nefarian you see that all of a sudden everyone is very close on overaggroing. And thereafter I back away a bit from Nefarian (I can still hit melee swings) and everyone is very far away from AGGRO GAIN again.

I assume that the reasoning behind this is that Melee (those who are close to boss; i.e casters that stand very close are also included here) overaggro at 110% threat of tank, whilst ranged overaggro at 130% threat of tank (I am not one hundred percent sure on those numbers but pretty sure that ranged have a higher Aggro Gain "ceiling". 

Now, I do not know if I got a higher aggro gain **ceiling** just because I max-ranged my melee attacks on Nefarian, or if KTM just was fooling me. It could be really game changing if it really works like this on this server since I can max range on bosses with huge hit boxes and have a lot higher aggro gain ceiling.  

P.S. I do not know what is truly blizzlike, I just want to know how it works on this server :D I want to know if KTM is fooling me or not

**Comment by GuybrushGit** [comment]
Different mobs have different melee radius. KTM doesn't know this and thinks you're outside his melee range when you moved.
