### ISSUE TITLE
Ferocitas the Dream Eater (Quest) item bug

### ISSUE THREAD

**Issue by A5-Renegado** [elysium-project/server#984]
The item "Gnarlpine Necklace" bugs out when attempting too loot the Talonkai's Jewel item from it.

**Comment by GuybrushGit** [comment]
Did you level up between getting the item and opening it?

**Comment by A5-Renegado** [comment]
I don't remember, however after it first occurred, I tried to delete the item (couldn't) so I logged out and then back in. I tried to open the item again, couldn't, relogged, deleted the item, and re-earned it by killing the mob that drops it. Still couldn't open it. I definitely did not level up between getting the item and opening it both times. When I logged on the next night, I was able to open the item without a problem.
