### ISSUE TITLE
Amulet / Orb of the Darkmoon

### ISSUE THREAD

**Issue by AnikusTheRed** [elysium-project/server#989]
On the Darrowshire server these items are still showing up as rare (blue) quality when attempting to turn in tickets and claim as a reward. As of patch 1.7 , they are supposed to be upgraded to Epic (purple) quality, and  have their stats improved.

**Comment by m-laniakea** [comment]
Wrong place, but thank you.
https://github.com/elysium-project/itemization/issues/15
