### ISSUE TITLE
Not being crit by 60 PRIEST staff when sitting in duels for reckoning

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/server#996]
I was sitting to be crit by a priests melee staff during a test, the priest was level 60 and it didn't crit me.

Please fix this

**Comment by GuybrushGit** [comment]
The issue here is that players with 0% crit cannot crit, even when the target is sitting.
Your priest had his staff skill so low that his melee crit was 0%.

**Comment by sknnbones** [comment]
@Guybrushgit

But that contradicts 

> Melee attacks against a sitting target automatically hit and cause double damage. The first damage taken while sitting will cause a target to immediately stand. **The double damage registers as a critical hit in the combat log**

**Comment by Itembugs** [comment]
please fix this, I should of received a crit
