### ISSUE TITLE
Nightfall on Anathema has wrong chance on hit?

### ISSUE THREAD

**Issue by vindruvor** [elysium-project/server#998]
Current chance on hit:
Nightfall
Chance on hit: Spell damage taken by target increased by 15% for 5 sec.

This is what 1.11 patch notes say:

"The axesmith weapon Nightfall effect has been changed from -60 resistance to +15% spell damage taken. Also its speed has been decreased somewhat."

Source: http://wowwiki.wikia.com/wiki/Patch_1.11.0

So, as I see it, Nightfall on Anathema (patch 1.9) should have 'chance on hit: reduce all resistances by 60' (or something like that) up until patch 1.11? 

P.S I do not have any info on how the speed was before 1.11.0.

**Comment by GuybrushGit** [comment]
We are on patch 1.12 when it comes to spells and talents.

**Comment by vindruvor** [comment]
but that is an item? :o

**Comment by vindruvor** [comment]
Blade of Eternal Darkness has pre-1.12 chance on hit (aka no chance on hit)

**Comment by brotalnia** [comment]
Chance on hit effects are actually spells that get triggered.

**Comment by thepparker** [comment]
It depends if the previous spell effect exists in the game client or not. I can't speak for Blade of Eternal Darkness, but take BRE for example. The previous to (1.10?) spell effect was replaced to be what it is currently, therefore we cannot use the old spell effect and have it render for the client. 

This is the same for Nightfall, the old spell effect of spell 23605 has been replaced, and is now as you see it in-game.

**Comment by vindruvor** [comment]
Ok ye sounds reasonable
