### ISSUE TITLE
Clearcasting not proccing

### ISSUE THREAD

**Issue by pajlk** [elysium-project/server#999]
Can i ask what is wrong with arcane concentration talent? i started farming BRD after a long time and clearcasting doesn't seem to proc like it should. I can't get it to proc when aoeing 15+ mobs, it procs very rarely for the amount of mobs i am aoeing. I farmed like 1 or 2 months ago it procced every time like it should. what is the issue? thanks for ur time

**Comment by Haiwuu** [comment]
High proc rate was a bug and was fixed.

**Comment by pajlk** [comment]
Really? any source on that fix?
